test-data/unit/check-varargs.test
Since #2729 is closed, we can unskip tests that do exactly what @hauntsaninja said is reasonable in https://github.com/python/mypy/issues/2729#issuecomment-835901901
=> Unskip two tests in `check-varargs.test`

mypy/checker.py, mypy/subtypes.py, test-data/unit/check-inference.test, test-data/unit/check-narrowing.test
As always, fixing issues with type narrowing / inference is always very hard, because small changes can backfire.
But, this looks as a simple change. Let's see how tests will behave.
Closes #11272
=> Fixes type narrowing for overlaping runtime types

mypy/checkexpr.py, test-data/unit/check-typeguard.test
Here's what was happening in this example:
```python
from typing import Callable, Iterable, Iterator, List, Optional, TypeVar
R = TypeVar("R")
def filter(f: Callable[[T], TypeGuard[R]], it: Iterable[T]) -> Iterator[R]: ...
a: List[Optional[int]]
bb = filter(lambda x: x is not None, a)
reveal_type(bb)  # error, actually it is now: Revealed type is "typing.Iterator[R`2]"
```
Mypy uses special logic in `infer_lambda_type_using_context` to infer `lambda` type args and return type. Basically, it just returns the current callable context type. Which is `Callable[[T], TypeGuard[R]]` in our case.
But, now I've limited this function to ignore contexts with `TypeGuard`. Because I believe that `TypeGuard` must always be explicit.
After this change Mypy works correctly:
```
» mypy …
```
=> Do not auto-infer `TypeGuard` return type for `lambda`, refs #9927

mypy/checker.py, test-data/unit/check-statements.test, test-data/unit/check-unreachable-code.test
This is a very simple change, but now module bodies are also checked to be reachable.
Let's see what effect it will have.
Closes #11331
=> Checks module bodies to be reachable

.github/workflows/mypy_primer.yml
This is how it is now:
Taken from here: https://github.com/python/mypy/pull/11151
Click "View details" to see it.
I guess that new name would have better readability.
=> Change `mypy_primer` output name

mypy/checker.py, test-data/unit/check-classes.test
Closes #11398
Now cases like 
```python
from typing import Type
class MyMetaClass(type):
def __new__(cls, name, bases, attrs) -> Type['MyClass']:
pass
class MyClass(metaclass=MyMetaClass):
pass
```
Will pass.
=> Now `__new__` in a metaclass must return a subtype of `type`

test-data/unit/README.md
it's frustrating having to modify the copied code to remove the `$`. since github has a a "copy to clipboard" button, it makes sense to make to remove the `$` imo
=> remove `$` from commands so the copy to clipboard button works

mypy/join.py, mypy/test/testtypes.py, test-data/unit/check-generics.test
The initial implementation was not very careful, so I only keep the covariant part, while other cases fall back to old simple logic (which is actually correct for invariant type parameters).
=> Fix crash on join of recursive types

docs/source/generics.rst
Also change typing.Tuple to tuple, typing.Dict to dict, etc.
Using standard containers is the best practice moving
forward, so we should encourage it in examples.
I just deleted the info about `typing.List` and friends from the
"Generic class internals" section, since that shouldn't be needed
going forward, and I wanted to try to keep this doc as slim as possible.
Doesn't change behavior
Haven't tested rebuilding docs, I assume CI will test that if you approve it to run.
=> Use list[int] instead of typing.List[int] in generics.rst

mypy/semanal.py, test-data/unit/check-callable.test
This flag may be set to `True` if there are tricky forward references.
=> Clear type alias flag for assignments that are not aliases

test-data/unit/check-generic-subtyping.test
=> add test for new union syntax on generic bounds

mypy/report.py
The mypyc bug that the comment is describing sounds like mypyc/mypyc#851, which is already fixed by #10550.
The tests in mypy/test/testreports.py run this code, so if CI passes this change should be fine.
=> Remove unnecessary mypyc bug workaround

mypy/checkexpr.py
It now has a better API for that.
I've also changed `self.check_method_call_by_name` to use named args to make this call more readable.
=> Changes how errors are disabled in `visit_comparison_expr`

mypy/checkmember.py, mypy/plugin.py, mypy/plugins/attrs.py, mypy/semanal.py, mypy/suggestions.py, test-data/unit/plugins/common_api_incremental.py, test-data/unit/plugins/dyn_class.py, test-data/unit/plugins/dyn_class_from_method.py
Related to https://github.com/python/mypy/issues/6578.
`builtin_type` could be totally replaced with `named_type` after https://github.com/python/mypy/pull/11332. Also renames other `builtin_type` for consistency since all of them are actually calling `named_type`.
=> Discard deprecated `builtin_type` api

mypyc/analysis/ircheck.py, mypyc/ir/pprint.py, mypyc/test/test_ircheck.py, mypyc/test/testutil.py
Adds a new module for performing analysis checks on ir as several bugs
in mypy had underlying issues in which the ir produced by mypy was
invalid and guaranteed to have issues at runtime.
For now the checks are relatively simple - the only two supported are
some validity on basic blocks: that they terminate and that control
ops reference a basic block within the same function.
In addition it would be useful if we had an ir parser so we could have a
test framework similar to other parts of mypyc in which we simply write
the IR in text format instead of constructing the IR ast from within
python.
The first commit here implements the checking but not the presentation;
the second implements basic presentation and integrates it into the test framework.
=> [mypyc] Add a simple irchecking analysis system

mypy/pyinfo.py
Fixes #11274
As suggested in the above issue, we need to add user site packages to the list of directories *only* if site.ENABLE_USER_SITE is True.
Before the patch:
```
$ ./venv/bin/python mypy/pyinfo.py getsitepackages
['/mnt/data/dmerej/src/mypy/venv/lib/python3.9/site-packages', '/home/dmerej/.local/lib/python3.9/site-packages']
```
After the patch:
```
$ ./venv/bin/python mypy/pyinfo.py getsitepackages
['/mnt/data/dmerej/src/mypy/venv/lib/python3.9/site-packages']
```
where `venv` is the virtualenv for mypy development, as indicated in CONTRIBUTING.txt
Finally, we can check that pinfo still works outside a virtualenv:
```
$ python mypy/pyinfo.py getsitepackages
['/mnt/data/dmerej/src/mypy/venv/lib/python3.9/site-packages', '/home/dmerej/.local/lib/python3.9/site-packages']
```
=> Don't look in user site packages when using a virtual env

mypy/checker.py, mypy/checkexpr.py
Since `.clean_copy()` already ensures that `.disable_count` is `0`, there's no need to set it once again.
Follow up to https://github.com/python/mypy/pull/11451
=> Now all `.clean_copy()` calls do not use `.disable_count = 0`

mypy/semanal.py
It is not really a bug, because it kinda works. But, this version is much more readable.
=> Fix bug with `param_kind` compare with `ARG_NAMED`

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
=> Adds `slots=True` support for `@dataclass`

mypy/semanal_typeddict.py, test-data/unit/check-typeddict.test
Closes https://github.com/python/mypy/issues/3673
Adds a trivial for-loop and a helper set to check duplicates of `typeddict_bases`.
Adds a new test case `testCannotCreateTypedDictWithDuplicateBases`
=> Check duplicate bases when defining TypedDict

docs/source/additional_features.rst, docs/source/cheat_sheet_py3.rst, docs/source/class_basics.rst, docs/source/command_line.rst, docs/source/error_code_list.rst, docs/source/error_code_list2.rst, docs/source/extending_mypy.rst, docs/source/final_attrs.rst, docs/source/getting_started.rst, docs/source/kinds_of_types.rst, docs/source/literal_types.rst, docs/source/more_types.rst, docs/source/protocols.rst, docs/source/running_mypy.rst, docs/source/runtime_troubles.rst, docs/source/stubs.rst, docs/source/type_inference_and_annotations.rst, docs/source/type_narrowing.rst
As well as `Dict[X, Y]` -> `dic[X, Y]`, etc.
This is a follow-up to https://github.com/python/mypy/pull/11377, where
just a single page of the docs was transitioned.
I did a grep through the docs/ directory for anything
matching "List[", "Dict[", "Tuple[", and "Set["
and corrected any examples. Perhaps I missed something, but
my goal was to clean all of the docs.
I tried to strike a balance of how explicit to be: In places related
to collections, such as the "Explicit types for collections" section
of `type_inference_and_annotations.rst`, I kept
in notes about the differences
between `List` and `list`. But in most examples
that were focused
on some other topic, I just deleted any reference to
`typing.List`. I thought any notes there would
just add noise.
There also is a correction to …
=> Replace `List[X]` with `list[X]` in docs

mypy/checkexpr.py, test-data/unit/check-typevar-values.test
Closes #8231
When type of index expression (e.g. `foo[bar]`) is analyzed and left
expression (i.e. `foo`) has generic type (`TypeVar`) with upper bound,
for some upper bound types this type inference yields wrong result.
For example, if upper bound type is instance of `TypeDict`, mypy
considers return type of such index expression as `object`:
```
from typing import TypedDict, TypeVar
class Data(TypedDict):
x: int
T = TypeVar("T", bound=Data)
def f(data: T) -> int:
return data["x"] + 1
```
The root cause of this issue was in `visit_index_with_type` method
from `checkexpr.py` which does type analysis for index expressions. For
`TypeVar` left expression code flow goes via default branch which just
returns return type of upper bound's `__getitem__`. For some types this
return type inference …
=> Fix type inference for index expression with bounded TypeVar

mypy/plugins/attrs.py, test-data/unit/check-attr.test
Closes #11487
Refs https://github.com/python/mypy/issues/11482
Refs https://github.com/python/mypy/issues/10801
=> Adds `slots=True` support for `@attr.s`

mypy/message_registry.py, mypy/messages.py
It was duplicated, so I've decided to move it into a separate constant.
=> Microrefactoring: "not callable" error message is now a const

mypy/messages.py, test-data/unit/check-inference.test, test-data/unit/check-modules.test, test-data/unit/check-tuples.test, test-data/unit/check-unions.test
Related https://github.com/python/mypy/issues/5072
Uses `format_type` to get a more concise output.
=> Use `format_type` for `msg.type_not_iterable`

mypy/stubgen.py
As pointed out by @pranavrajpal in https://github.com/python/mypy/pull/11498#discussion_r746886480
=> Restore comment in stubgen

mypy/constraints.py, mypy/subtypes.py, mypy/types.py, test-data/unit/check-inference-context.test, test-data/unit/check-inference.test
This replaces dropping trivial (i.e. `Any`-only) constraint sets with merging the `Any` targets into every other existing constraint.
We also ignore constraint direction when comparing constraints if the target is `Any`. This is needed to be able to merge `Any` constraints for both covariant and invariant cases. For example, both `Iterable[str] | Any` and `list[str] | Any` will infer `T = str | Any` against `list[T]`.
=> Try fixing union inference including Any

mypy/checker.py, mypy/message_registry.py, mypy/messages.py, mypy/semanal_typeargs.py, test-data/unit/check-bound.test, test-data/unit/check-classes.test, test-data/unit/check-errorcodes.test, test-data/unit/check-modules.test, test-data/unit/check-namedtuple.test, test-data/unit/check-newsemanal.test, test-data/unit/check-typeddict.test, test-data/unit/fine-grained.test
Closes https://github.com/python/mypy/issues/5072, follows up to https://github.com/python/mypy/pull/11490
=> Remove `builtins.` from error messages

mypy/semanal.py, mypy/traverser.py, test-data/unit/check-custom-plugin.test
The `get_dynamic_class_hook` method of the plugin never called if the statement is a chained assignment like `Bad1 = Bad2 = declarative_base()`; Or if the statement is a chain of call expressions like `Base = declarative_base().with_optionalA()`.
1. Update existed unit test "mypy/test/testcheck.py::TypeCheckSuite::testDynamicClassPluginNegatives"
```plain
[case testDynamicClassPluginNegatives]
from mod import non_declarative_base
Bad1 = non_declarative_base()
class C1(Bad1): ...  # E: Variable "__main__.Bad1" is not valid as a type \
[file mod.py]
def non_declarative_base(): ...
[file mypy.ini]
\[mypy]
plugins=<ROOT>/test-data/unit/plugins/dyn_class.py
```
2. Add two new unit tests
```plain
[case testDynamicClassPluginChainCall]
from mod import declarative_base, Column, Instr
Base = …
```
=> Fix get_dynamic_class_hook does not work in some scenarios

mypy/modulefinder.py
This was being read repeatedly, and it was bad enough to
show up in a performance profile.
=> Only read the stdlib versions dict once per run

mypy/types.py
Don't use a generator, since they tend to be slow when compiled.
This method came up as a hot spot when profiling compiled mypy.
=> Optimize CallableType.formal_arguments

mypy/types.py
if TYPE_CHECKING is compiled inefficiently right now (mypyc/mypyc#902).
=> Minor optimization/cleanup

mypy/argmap.py, mypy/typeops.py
This should speed things up a little, because mypyc
is bad at compiling local imports (mypyc/mypyc#903).
=> Reduce the number of executed local imports

mypy/api.py, mypy/main.py, mypy/options.py
This means that we kill the mypy process at exit instead of cleanly
freeing up memory. This speeds up mypy runs by ~10% in some cases
(with compiled mypy).
We've been using this internally at work for a long time without any
issues.
Previously the slowdown was visible as a small delay after the final
message from mypy was printed.
I measured the impact on a branch with some other optimizations as
well, so on master the fraction would be slightly less, as other
things would be slower.
=> Enable --fast-exit by default to speed up mypy

mypyc/analysis/blockfreq.py, mypyc/codegen/emit.py, mypyc/codegen/emitfunc.py, mypyc/ir/ops.py, mypyc/lib-rt/CPy.h, mypyc/test-data/exceptions-freq.test, mypyc/test/test_emitfunc.py, mypyc/test/test_exceptions.py
These operations are performance-critical, but inlining everywhere
can slow down compilation a lot, so we only inline them outside error
handlers (and other rarely executed code paths).
This still can slow compilation by 10-15%, but I think that we just need
to live with it, since the performance gains are impressive. We can perhaps
claw back some of the loss by optimizing away redundant increfs/decrefs.
Also parallel compilation would make this much less significant.
This can speed up the richards benchmark by 65% (!).
With this change:
```
running richards
...........
interpreted: 0.181880s (avg of 6 iterations; stdev 0.91%)
compiled:    0.005314s (avg of 6 iterations; stdev 1.2%)
compiled is 34.229x faster
```
Using master:
```
running richards
...........
interpreted: 0.182124s (avg …
```
=> [mypyc] Inline increfs and decrefs in commonly executed blocks

mypy-requirements.txt, setup.py
Original PR #11531, modified for the 0.920 branch.
Cf. #11158
=> Bump typed_ast max dependency

mypy/message_registry.py, mypy/semanal.py, test-data/unit/semanal-errors.test, test-data/unit/semanal-types.test
Changes:
1. I've change some wordings
2. Moved the same strings into `message_registry`
3. Added extra tests for new feature. You can now specify `TypeVar('A', covariant=False)` to mirror the CPython
Closes #11442
=> Improves `TypeVar` error messages

.github/ISSUE_TEMPLATE/bug.md
This is to hopefully cut down on the number of bug reports where OP didn't search for a duplicate or at least check common issues.
=> Point to some resources at top of bug template

test-data/unit/fine-grained-follow-imports.test, test-data/unit/fine-grained-modules.test
These tests were deleting package files, but not the empty
directory, causing those directories to be interpreted as
namespace packages in #9636
Tried these out on top of #9636 and confirmed they all work. A couple changed error messages - so I needed to add flags for `--namespace-packages`, but figured that's the future anyway, so this is a good thing.
=> Update fine-grained tests to prep for --namespace-packages support

mypy/checkmember.py, test-data/unit/check-dataclasses.test, test-data/unit/check-functions.test, test-data/unit/check-functools.test, test-data/unit/check-selftype.test, test-data/unit/check-slots.test
This reverts commit 6ab0efcc2ae3bcf649098b86d1edbcab2e4b1e9b.
Reverting the change since it causes a significant backward
compatibility break. Code like this previously worked as expected:
```
class C:
def f(self) -> None: pass
g = f
C().g()  # Sometimes generates an error
```
However, #10548 broke this in a subtle way (no error on definition,
it sometimes generates an error on call), and instead required the 
introduction of a ClassVar annotation for `g`, which is non-intuitive 
and error-prone. For example, some typeshed stubs use method 
aliases such as the above (e.g. stubs for `logging`), and the change 
broke those stubs. It's also arguably inconsistent, since normally 
ClassVar annotations are optional.
Any fix to the original issue should avoid breaking method aliases
such as the …
=> Revert "Fix callable instance variable support (#10548)"

mypy/checker.py, test-data/unit/check-classes.test
It was crashing before this patch.
Closes #10134
Closes #11556
Refs #5425
=> Now we can override attributes with methods, refs #10134

mypy/checker.py, mypy/message_registry.py, test-data/unit/check-python2.test
=> Now `print >>` is properly checked on Python2

mypy/subtypes.py, test-data/unit/check-selftype.test
Correctly handle cls in generic classmethods of protocol. Closes #11115
This should correctly handle cls in classmethods. Current behavior of not passing is_classmethod seems like an omission in implementation, so this should only correct buggy behavior and shouldn't break something else.
I've included a test in the test suite (testSelfTypeProtocolClassmethodMatch)
=> Correctly handle cls in protocol classmethod

mypy/__main__.py
Catch `KeyboardInterrupt` to allow graceful exit instead of printing the traceback.
Run `mypy` and trigger a `KeyboardInterrupt`. No traceback should be shown.
=> Graceful exit on KeyboardInterrupt

mypy/stubgen.py
Not too familiar with stubgen, so maybe there's a good reason for
hardcoding, e.g. to ensure stubs capture sys.version checks in the
source? Even if that's the case, most stubs in typeshed use
sys.version checks for a) checking Python 2, b) if they're stdlib
backports. So hopefully this is a reasonable change.
Fixes #10905, fixes #10791
=> stubgen: use sys.version_info, rather than hardcoding 3.6

mypyc/__main__.py, mypyc/build.py, mypyc/test/test_run.py, setup.py
Reduce amount of debug info injected in extension modules
This can help in decreasing memory resource requirements on CI and
generating relatively thinner binaries
Resolves #11507
=> Reduce amount of debug info injected in extension modules

mypy/plugins/dataclasses.py
This is a very minor change that moves the `field_makers` constant up to the global scope.
Currently, I have duplicated this entire plugin here https://github.com/NeilGirdhar/tjax/blob/master/tjax/mypy_plugin.py, but it keeps changing.
I would like to simply add my custom dataclass and its field maker to the constant sets, and having them in the global scope (and non-final) makes that easy.
=> Factor out field_makers alongside dataclass_makers

mypy/build.py
Typeshed now declares `__file__` as an optional type.
=> Prepare for typeshed sync: __file__ could be None

mypy/checkmember.py
python/typeshed#6302 added `__getattr__`, but we don't want to always
use it, as it can result in undefined references to module attributes
being undetected.
This is an alternative to python/typeshed#6357.
Tested manually with a recent typeshed.
=> Don't use ModuleType.__getattr__ if we know module symbols

mypy/checkexpr.py
Names of some of types have changed in typeshed. Accept both
the old and the new names for now.
Tested manually with the latest typeshed.
Relevant typeshed changes: python/typeshed#6312
=> Update strict equality allowlist

mypy/checker.py, mypy/checkexpr.py, mypy/typeanal.py
Teeny weeny change to fix a typo I found in a doc string (there were duplicated indefinite articles 😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳)
I don't think we need to write any tests for this change as it's purely a doc string change.
=> Remove duplicated indefinite articles in doc strings

misc/proper_plugin.py, mypy/applytype.py, mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, mypy/constraints.py, mypy/erasetype.py, mypy/expandtype.py, mypy/fixup.py, mypy/indirection.py, mypy/join.py, mypy/meet.py, mypy/messages.py, mypy/nodes.py, mypy/sametypes.py, mypy/semanal.py, mypy/semanal_typeargs.py, mypy/server/astdiff.py, mypy/server/astmerge.py, mypy/server/deps.py, mypy/subtypes.py, mypy/test/typefixture.py, mypy/tvar_scope.py, mypy/type_visitor.py, mypy/typeanal.py, mypy/types.py, mypy/typetraverser.py, mypy/typevars.py, test-data/unit/check-parameter-specification.test
Add support for type checking several ParamSpec use cases (PEP 612).
@hauntsaninja previously added support for semantic analysis of ParamSpec
definitions, and this builds on top that foundation.
The implementation has these main things going on:
* `ParamSpecType` that is similar to `TypeVarType` but has three "flavors" that
correspond to `P`, `P.args` and `P.kwargs`
* `CallableType` represents `Callable[P, T]` if the arguments are 
(`*args: P.args`, `**kwargs: P.kwargs`) -- and more generally, there can also
be arbitrary additional prefix arguments
* Type variables of functions and classes can now be represented using
`ParamSpecType` in addition to `TypeVarType`
There are still a bunch of TODOs. Some of these are important to address before the
release that includes this. I believe that …
=> Basic support for ParamSpec type checking

mypy/checkexpr.py, test-data/unit/check-parameter-specification.test
If ParamSpec is in the context of a lambda, treat it similar
to `Callable[..., Any]`. This allows us to infer at least argument
counts and kinds. Types can't be inferred since that would require
"backwards" type inference, which we don't support.
Follow-up to #11594.
=> Improve ParamSpec type inference from lambda

mypy/argmap.py, mypy/checkexpr.py, mypy/expandtype.py, mypy/types.py, test-data/unit/check-parameter-specification.test
Check that the correct ParamSpec and flavor are used in
`*args` and `**kwargs`.
Follow-up to #11594.
=> Improve type checking of ParamSpec in calls

test-data/unit/check-overloading.test, test-data/unit/check-python38.test
I was not able to find a similar test.
This is an interesting corner-case. I think it is benefitial to have it covered.
In my opinion it works correctly. No further actions are required.
Closes #11606
=> Adds explicit test for overloads with pos-only `self`, refs #11606

mypy/message_registry.py, mypy/semanal.py, mypy/test/testsemanal.py, test-data/unit/check-classvar.test, test-data/unit/semanal-classvar.test
Some tests might fail, because I've only checked semanal test suite. I will fix them after the initial CI run.
Closes #11538
=> Now `ClassVar` cannot contain type variables, refs #11538

docs/source/more_types.rst
`NewType` is a class in Python >=3.10, meaning the mypy documentation is no longer accurate.
Closes #11620
=> Correct documentation for NewType

mypy-requirements.txt, setup.py
mypy imports TypeAlias in typing_extensions, which
was introduced in typing_extensions 3.10.0.0 by the following commit:
commit c23141fd08aba8284ce76b096bf08fd7c019b51c
Author: Ken Jin <28750310+Fidget-Spinner@users.noreply.github.com>
Date:   Sun Apr 11 03:26:42 2021 +0800
Support PEP 612 in typing_extensions (Python 3) (#774)
To test, downgrade `typing_extensions` to the minimal version in the new requirements
```
pip install typing_extensions==3.10.0.0
```
Then run the automated tests.
=> Fix typing_extensions version in requirements

mypy/checker.py, mypy/checkmember.py, mypy/plugins/default.py, test-data/unit/check-inference.test, test-data/unit/check-typeddict.test
Changes:
1. I've removed `sig` plugin for `typed_dict_delitem`, because now it properly handled in `checkmember`
2. Initial problem is now automatically solved 🙂 
Closes #10631
=> Now TypedDict member access is routed via `checkmember`

pytest.ini
Why? It is a best practice in pytest's land.
And since we have a quite complex test setup, it is better to be double sure that everything is fine.
Docs: 
- https://docs.pytest.org/en/6.2.x/example/markers.html#registering-markers and https://docs.pytest.org/en/6.2.x/reference.html#confval-markers
- https://docs.pytest.org/en/6.2.x/reference.html#command-line-flags
=> Adds strict mode to pytest

docs/source/kinds_of_types.rst
The mypy documentation is currently ambivalent on whether ``Iterator`` or ``Iterable`` is the better return-type annotation for a simple generator function. The documentation should endorse using ``Iterator`` instead of `Iterable`, in my opinion, as it is a more precise return type, and no less concise.
=> Improve documentation for annotating generator functions

README.md
While installing mypy using terminal, I faced a minor issue with README file. When we copy and paste terminal commands directly. Due to '$' character we face a error, so I want to make a minor change by removing '$'.
Please accept the pull request if you feel this change can be helpful.
=> Fix typo in README: Ready to paste terminal commands

mypy/main.py, test-data/unit/cmdline.test
Fixes #11405  by using `options.python_executable` instead of `sys.executable`.
I tested the change manually with an internal project, that was affected by #11405.
=> Install types to correct environment

mypy/build.py
This is a variant of https://github.com/python/mypy/issues/6156, albeit **not** the same exact failure site.
In one of my professional projects, we use `mypy` to lint a relatively complex Python codebase. For reasons that haven't been fully root-caused, we occasionally see JSON corruption errors that look like this:
```
File "/usr/local/bin/mypy", line 8, in <module>
sys.exit(console_entry())
File "/usr/local/lib/python3.8/dist-packages/mypy/__main__.py", line 11, in console_entry
main(None, sys.stdout, sys.stderr)
File "mypy/main.py", line 87, in main
File "mypy/main.py", line 165, in run_build
File "mypy/build.py", line 179, in build
File "mypy/build.py", line 254, in _build
File "mypy/build.py", line 2697, in dispatch
File "mypy/build.py", line 3014, …
```
=> mypy/build: Use` _load_json_file` in `load_tree`

mypy/checker.py, test-data/unit/check-overloading.test
=> Addresses review of #11630

mypy/stubtest.py, mypy/test/teststubtest.py
With missing stubs and no runtime `__all__`, we now correctly find module level constants of primitive types (like int or str). While this can have some false positives, e.g. with `from module import int_constant`, I think this is an important fix to make since it allows for saner user expectations (see the change to `test_missing_no_runtime_all`).
The change from checking `module_public` to `not module_hidden` allows better checking in cases where the stub may wish to type runtime details. This corresponds to checking `_f` and `g` in `test_non_public_1` and `test_non_public_2`. The new errors in typeshed seem largely worthwhile.
=> stubtest: increase coverage

mypyc/lib-rt/misc_ops.c, mypyc/lib-rt/pythoncapi_compat.h, mypyc/lib-rt/pythonsupport.h
"Py_TYPE(t) = metaclass;" fails with a compiler error on Python 3.11:
* https://docs.python.org/dev/whatsnew/3.11.html#c-api-changes
* https://docs.python.org/dev/c-api/structures.html#c.Py_TYPE
* Replace "Py_TYPE(t) = metaclass;" with "Py_SET_TYPE(t, metaclass);"
* Replace "Py_SIZE(self) = newsize;" with "Py_SET_SIZE(self, newsize);"
* Add a copy of pythoncapi_compat.h header to add Py_SET_TYPE() and
Py_SET_SIZE() functions to Python 3.8 and older:
https://github.com/pythoncapi/pythoncapi_compat
(Once you have, delete this section. If you leave it in, your PR may be closed without action.)
=> Port mypyc to Python 3.11: use Py_SET_SIZE()

mypy/semanal_typeddict.py, test-data/unit/check-typeddict.test
Closes https://github.com/python/mypy/issues/4299
Add a new test case `testCannotCreateTypedDictInstanceWithInlineTypedDict`
=> Better error message for nested TypedDict

mypy/semanal.py, test-data/unit/check-incremental.test
Fixes #8481
Fixes #9941
Fixes #11025
Fixes #11038
This is the unresolved crash that's been reported the most times, e.g., it's as easy to repro as `mypy --no-implicit-reexport -c 'import pytorch_lightning'` (or even `import torch`, with the right PyTorch version). I know of multiple popular Python packages that have made changes just to work around this crash. I would love to see this released, potentially along with #11630.
Thanks to @rraval for making a minimal repro!
The fix ended up being a one-liner, but it took me a bit to track down :-)
Since things worked with implicit reexport, I differentially patched in explicit reexport logic to narrow things down. This let me observe that if I hardcoded pkg.a.B to get reexported, we hit this branch, which clobbers the PlaceholderNode for …
=> Fix crash involving explicit reexport, import cycle, wildcard

mypy/checker.py, mypy/checkmember.py
=> Follow up to #11150, refactors `if`s into util function

mypy/test/data.py, mypy/test/testcheck.py, test-data/unit/check-basic.test
One test is failing right now on purpose, so you can take a look on how new namespaces work.
I will fix it in the next commit, I hope the logs will be preserved for some time to see them.
Here's a quick recap of everything in this PR:
- Here's how collect tree looks like: https://github.com/python/mypy/issues/11662#issuecomment-986284991
- You can now run a single `.test` file with `mypy/test/testcheck.py::TypeCheckSuite::check-basic.test`
- Single test will now be `mypy/test/testcheck.py::TypeCheckSuite::check-basic.test::testAssignmentAndVarDef`
Screenshots:
Refs #11662
=> Now you can run separate mypy test modules :tada:

mypy/checker.py, mypy/checkexpr.py, test-data/unit/check-unreachable-code.test
=> Fix crash involving unreachable binary ops

mypy/checker.py, mypy/checkexpr.py, test-data/unit/check-callable.test, test-data/unit/check-optional.test
This reverts commit d37c2be0f7a2002a0a8c160622d937518f902cc7.
Lambdas can't be safely deferred. There are various subtle assumptions about 
lambdas not being deferred in different parts of the codebase, and figuring out 
how to do this safely is almost certainly not worth the trouble. This would be 
very difficult to validate, since lambda deferral would probably happen very 
rarely in practice.
Also, I've seen some crashes which might be caused by this (not sure though).
=> Revert "Now `lambda` is counted as a valid context in …"

mypy/messages.py
It is not used:
The only concern I have is that some plugins might be using it. But, change it to `chk.msg.clean_copy()` should not be hard 🤔 
Some people might be confused: https://github.com/python/mypy/pull/10386#discussion_r766080260
=> Removes unused `temp_message_builder`

mypy/build.py
If we get an error when accessing the mtime of a cache file, we should handle that as if the cache is unusable for any other reason.
I've been getting a bizzare crash here in while working on Hypothesis deps; I think it's something to with with my WSL+pyenv install breaking.  Given that there was already a `TODO` comment requesting error handling here, I went ahead and added it in the obvious way.
=> Cope with `OSError` when checking cache `stat.mtime`

mypy/checker.py, mypy/checkexpr.py, mypy/plugins/enums.py, mypy/semanal.py, mypy/semanal_enum.py, test-data/unit/check-enum.test
My naive attempt to fix bug with some special `Enum` props which are treated as `Final`.
I just special case it and ignore them.
This looks like the simplest solution. And it fits `Enum` pretty well, because `Enum` is special in how class / instances are treated.
Closes #11699
=> Special cases `Enum` and some special props to be non-final, refs #11699

mypy/semanal.py, test-data/unit/check-modules.test
Fixes #11064. Co-authored by @hi-ogawa 
Pushes #11346 over the finish line. Implements the suggestion in https://github.com/python/mypy/pull/11346#pullrequestreview-805433478
=> Fix crash involving undefined cyclic `import *`

mypy/fscache.py
Originally added in #10093
Fixes #11690, fixes #10661, fixes #10822
=> Remove assumption of case sensitivity

.gitattributes
Current mypy stats are not quite correct, because `mypy/typeshed` takes a lot of space!
I propose marking `mypy/typeshed/` as vendored, so it would be excluded from stats.
Docs: https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes
=> Marks `mypy/typeshed` as vendored path

mypy/subtypes.py, mypy/typeops.py, test-data/unit/check-namedtuple.test, test-data/unit/fixtures/typing-namedtuple.pyi
In some places in our code `bool` was compared with `Union[Literal[True], Literal[False]]`.
It was later compared with each union item. And `bool` is not subtype of `Literal[True]` and `Literal[False]`
Closes #11701
Refs #11705
=> Fixes `bool` and `Literal[True, False]` subtyping, refs #11701

mypy-requirements.txt, setup.py
Tomli seems to be moving fast -- 2.0 was released ~6 months after 1.0. It
seems better to support future releases, since otherwise we risk version
conflicts in the future.
=> Drop version upper bound from tomli

mypy-requirements.txt, setup.py
This may avoid some package version conflicts in the future. We just
need to be careful to avoid making incompatible changes to
mypy-extensions, which seems like a good idea in any case.
=> Drop version upper bound for mypy-extensions

misc/cherry-pick-typeshed.py
Sometimes we only one some specific commits from typeshed (e.g. in a release
branch).
=> Add script for cherry-picking commits from typeshed

mypy/fastparse.py, mypy/test/testcheck.py, test-data/unit/check-python310.test
Generate a syntax error instead.
=> Don't crash on unsupported Python 3.10 match statement

mypy/checker.py, mypy/fastparse2.py, mypy/nodes.py, test-data/unit/check-python2.test
Original PR: #11289
This reverts commit c22beb431a682330276aff2a84b4796abadf71b4.
See #11742 for context.
=> Revert "Now typechecks `traceback` in `raise e, msg, traceback` on py2"

mypy/fastparse.py
The crash only happens with compiled mypy on Python 3.10, I think.
=> Fix crash when encountering match statement

test-data/unit/check-errorcodes.test
The syntax error changed between `3.10.0` and `3.10.1`.
https://bugs.python.org/issue46004
So far the Github actions runner still uses Python 3.10.0, which is why it hasn't yet failed on master.
https://github.com/python/mypy/runs/4532892092?check_suite_focus=true#step:3:6
=> Fix ErrorCode test for Python 3.10.1

mypy/test/data.py, test-data/unit/check-errorcodes.test, test-data/unit/fine-grained-blockers.test, test-data/unit/parse.test
Followup to #11752 The syntax error changed between `3.10.0` and `3.10.1`.
https://bugs.python.org/issue46004
I missed a few the first time around unfortunately.
https://bugs.python.org/issue46004
Instead of duplicating the original output, I chose to extend the test syntax introduced with #10404 and added support for `==` version checks.
The test runner here still uses `3.10.0`.
To test `3.10.1` I opened the same PR on my own fork: https://github.com/cdce8p/mypy/pull/2. There it runs on `3.10.1`.
=> Fix tests for Python 3.10.1 (2)

mypy/util.py
=> curses.tigetstr() can return None

mypy/build.py
Probably it was not removed when new semanal was added.
=> Fixes docs: there's no `semantic_analyzer_pass3` anymore

mypy/nodes.py, mypy/semanal.py, test-data/unit/check-enum.test, test-data/unit/check-incremental.test
I am using AST here, because `Var` does not seem to have information about having an explicit value.
I left a TODO item for it. Should we add this to `Var`?
Closes https://github.com/python/mypy/issues/11578
=> Enums with annotations and no values are fine to be subclassed

mypy/checkexpr.py, test-data/unit/check-functions.test, test-data/unit/check-redefine.test
Fixes #11774. The issue has relevant background information in the
discussion.
It may be worth it to eventually add back some restrictions, but we'd
only focus the restrictions on singledispatch functions. This is a
quick fix to work around a regression.
=> Allow calling a function with name '_'

docs/source/common_issues.rst, docs/source/kinds_of_types.rst
Refs https://www.python.org/dev/peps/pep-0613/
I hope that I am correct with mypy's version number 🙂
=> Documents explicit type aliases

mypy/typeanal.py, test-data/unit/semanal-errors.test
=> Fixes crash on subclassing `Annotated` without args

mypy/semanal.py
allows the definiton of "_" as function in builtins (e.g via typeshed).
fixes issue #9802
Fixes #9802
=> fix: do not crash if "_" is parsed in builtins

docs/source/class_basics.rst, docs/source/command_line.rst, docs/source/common_issues.rst, docs/source/generics.rst, docs/source/installed_packages.rst, docs/source/kinds_of_types.rst, docs/source/literal_types.rst, docs/source/more_types.rst, docs/source/stubtest.rst, docs/source/type_inference_and_annotations.rst
Improve consistency, grammar, formatting and clarity in the documentation. Also
some minor content fixes.
=> Various small documentation updates

.gitattributes
I was wrong, it requires the full file glob.
=> Fix glob in .gitattributes for Github stats

misc/build_wheel.py
This should catch https://github.com/mypyc/mypyc/issues/912
We never ran mypyc tests against wheels, dating back to https://github.com/python/mypy/tree/783297c9b4ed3b2af9000c3536d6e1be34fed9ea/misc
=> Run mypyc tests against built wheels

mypy/types.py, test-data/unit/check-annotated.test, test-data/unit/check-fastparse.test, test-data/unit/check-generic-alias.test, test-data/unit/check-generics.test, test-data/unit/check-namedtuple.test, test-data/unit/check-overloading.test, test-data/unit/check-selftype.test, test-data/unit/check-serialize.test, test-data/unit/check-tuples.test, test-data/unit/check-type-aliases.test, test-data/unit/merge.test, test-data/unit/pep561.test, test-data/unit/pythoneval.test, test-data/unit/semanal-classes.test, test-data/unit/semanal-python2.test, test-data/unit/semanal-types.test
Previously variadic tuples were displayed as `builtins.tuple[T]`, which
is misleading. That syntax ordinarily indicates a tuple with a single
element. This change adds the `...` ellipsis when formatting.
Result:
```python
tup: tuple[str, ...] = ()
reveal_type(tup)  # N: Revealed type is "builtins.tuple[builtins.str, ...]"
```
The formatting of non-variadic tuples is unchanged (e.g. `Tuple[T, U]`).
Fixes #9522
Lots of coverage for this already in the test suite, see test file diffs.
=> Display ellipsis when formatting variadic `tuple[T, ...]`

setup.py
Skip compiling `mypyc/__main__.py` to fix https://github.com/mypyc/mypyc/issues/912
With this patch, the tests `testCompileMypyc` and `testErrorOutput` pass during the building of the mypy 0.930 binary packages for Debian.
As for CI testing, in Debian we don't build via `python3 setup.py --use-mypyc build_ext --inplace` we use `MYPY_USE_MYPYC=1 python3 setup.py build` and then copy the results into a temporary directory, where we then run the tests.
=> Skip compiling mypyc/__main__.py

misc/build_wheel.py, mypyc/test/config.py
Follow up to #11872
The cross repo split makes this a bit of a pain to test.
=> Fix shell syntax in build_wheel

mypy/semanal_enum.py, test-data/unit/check-enum.test
I've copied special names from `object` type as well.
Closes #11820
=> Fixes regression with `__module__` and similar non-final `Enum` names

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
Any other possible cases that I've missed?
Closes #11821
Closes https://github.com/python/mypy/issues/11827
=> Fixes `__slots__` regression in 0.930, refs #11821

docs/source/command_line.rst
=> Fix typo in command line docs

mypy/checker.py, mypy/git.py, mypy/join.py, mypy/meet.py, mypy/messages.py, mypy/plugins/singledispatch.py, mypy/semanal.py, mypy/semanal_shared.py, mypy/server/update.py, mypy/subtypes.py, mypy/suggestions.py, mypy/typeanal.py, mypy/typeops.py, mypy/types.py
After working on https://github.com/python/mypy/pull/11696 I was interested in knowing how many more unused code we have.
I am not suggesting that we should remove everything I found, all items must be carefully reviewed. Because they might be used by other people. But, I am sure we can totally remove **some** of the code I found.
=> Removes a lot of unused code

docs/source/command_line.rst, docs/source/config_file.rst, setup.py
Today, I was looking at the [Report generation](https://mypy.readthedocs.io/en/stable/command_line.html#report-generation) docs, and noticed [`lxml`](https://pypi.org/project/lxml/) is listed as an additional requirement.  I thought it would be nice to add as an extra to mypy's `setup.py`.
This way, inside a `requirements-dev.txt`, someone can include `mypy[reporting]` and have `lxml` installed.
One thing to note: a [comment](https://github.com/python/mypy/blob/master/setup.py#L195) in `setup.py` says this:
```python
```
NOTE: I did not update `mypy-requirements.txt`, as I belive extra requirements don't belong there.  This will be up to the PR reviewer if he/she wants to add `lxml` to `mypy-requirements.txt`.
NOTE 2: I did not pin `lxml`.  I only tested this to work with `lxml==4.7.1`. …
=> Added reporting extras option to setup.py

MANIFEST.in
editorconfig was added in #11883 and broke check-manifest in https://github.com/mypyc/mypy_mypyc-wheels/runs/4680413534?check_suite_focus=true
=> Fix sdist build for editorconfig

docs/source/config_file.rst, mypy/config_parser.py, test-data/unit/cmdline.pyproject.test
Introduces an alternative where multiple regexes can be expressed as an array. Includes additional unit tests.
This preserves backward compatibility by allowing [multi-line values in TOML](https://github.com/python/mypy/issues/10250#issuecomment-905781154) to be treated as a single regex for those who have come to rely on that while exposing an array-based expression as a more ergonomic (and TOML-like) alternative.
Fixes #11825. Obsoletes (or is obsoleted by) #11746.
=> Preserves interpreting multi-line strings as a single value for `exclude`  in TOML files

docs/source/config_file.rst, mypy/config_parser.py, test-data/unit/cmdline.test
Partially reverts #11329 (with respect to `.ini` documentation).
Modifies existing unit tests.
Fixes #11830.
=> Revert to treating exclude in .ini as single string

mypy/semanal.py
When debugging #11887 I realised `can_be_type_alias` can do non-trivial
amounts of work. It's unlikely to ever show up on a profile,
but reordering the check means we do less work. Changed the order of
some other checks for consistency.
=> (minor) Short circuit call to `can_be_type_alias` when using PEP 613

mypy/plugins/default.py, test-data/unit/check-default-plugin.test
resolves #11852
I had to back out some of the tests added in the patch which regressed this behaviour -- once I had "fixed" them they were identical to existing tests
I added a new test to cover the behaviour that had regressed.  I had to simplify it a bit from the one in the issue due to missing fixtures
automated tests in the patch itself -- the added test fails on master:
```
___________________ testContextManagerReturnsGenericFunction ___________________
[gw2] linux -- Python 3.7.12 /tmp/mypy/.tox/py37/bin/python
data: /tmp/mypy/test-data/unit/check-default-plugin.test:45:
../mypy/mypy/test/testcheck.py:140: in run_case
self.run_case_once(testcase)
../mypy/mypy/test/testcheck.py:227: in run_case_once
assert_string_arrays_equal(output, a, msg.format(testcase.file, testcase.line))
E …
```
=> Fix regression when a contextmanager yields a generic

mypy/semanal.py, mypy/typeanal.py, test-data/unit/check-generic-alias.test
Refs https://github.com/python/mypy/issues/10303
CC @JelleZijlstra @AlexWaygood
=> Allows to use `type[T]` in stubs

mypy/semanal.py, test-data/unit/check-type-aliases.test
=> Handle `NoReturn` type aliases

mypy/semanal.py, test-data/unit/check-generic-alias.test
=> Fix PEP 585 type aliases in stubs

mypy/checker.py, mypy/typeops.py, test-data/unit/check-inference.test
First of all, this is really hard to wrap your head around! Because `--no-strict-optional` is messy.
But, looks like I found several hacks to make this work as expected.
However, I am pretty sure that we do have a lot of other places where things can blow up with `--no-strict-optional`.
Closes #11705
=> Stricter `None` handling with `--no-strict-optional`, refs #11705

mypy/checkexpr.py, mypy/checkmember.py, mypy/messages.py
It felt like a good candidate for this refactoring.
=> Turns `disable_type_names` into a context manager

mypy/erasetype.py, mypy/subtypes.py, test-data/unit/check-inference.test
Closes #11913
Refs https://github.com/python/mypy/pull/11273
CC @hauntsaninja
=> Fix crash on `ErasedType` and `covers_at_runtime`

mypy/fastparse.py, mypy/fastparse2.py, mypy/stubtest.py, mypy/test/teststubtest.py, mypy/util.py
I've started with a new unit test that illustrates the problem.
Closes https://github.com/python/typeshed/pull/6845
=> stubtest: fix literal type construction

mypy/plugin.py, mypy/semanal.py
It shouldn't be used for new code, but adding it back makes it
unnecessary to update existing plugins that no longer worked with mypy
0.930.
Related issue: https://github.com/dropbox/sqlalchemy-stubs/issues/232
=> Restore removed builtin_type() api method

mypy/plugin.py, mypy/plugins/attrs.py, mypy/test/testfinegrained.py, test-data/unit/check-attr.test, test-data/unit/fine-grained-attr.test
This PR further enhances the attrs plugin by generating a more correct `__attrs_attrs__` field.
The current version of the plugin generates this field as a tuple of attributes. This enhancement makes it a namedtuple, which is what attrs actually does in runtime. The difference is a large increase in the ergonomics of the field: instead of `A.__attrs_attrs__[0]`, a user can access an attribute using `A.__attrs_attrs__.x`. Also note the end-users don't actually use the `__attrs_attrs__` field directly, but access it using `attr.fields`, which is a very simple getter interface.
This might sound like a trivial change, but it has big repercussions down the line for static checks in libraries building on top of attrs.
I have added 2 extra tests and improved an existing one.
=> attrs namedtuple

mypyc/irbuild/expression.py, mypyc/test-data/irbuild-classes.test
This speeds up the deltablue benchmark by 15%.
=> [mypyc] Ignore super calls to object.__init__()

mypy/types.py, test-data/unit/check-namedtuple.test
This is debatable, because `__bool__` can be defined as `return True` or `return False`.
And we don't check this in scope of this PR.
But, it solves the given problem.
Closes #11819
=> NamedTuple now narrows to bool correctly, when `__bool__` is defined

mypy/types.py
PR #11543 changed the `CallableType.formal_arguments` method to return a list of formal arguments instead of yielding them. However the docstring was not updated at the time to reflect this. This PR correct this docstring.
N/A, only changes a docstring, which isn't tested.
=> Fix `CallableType.formal_arguments` docstring

mypy/checkexpr.py, mypy/exprtotype.py, mypy/semanal.py, mypy/typeanal.py, mypy/types.py
I've tried to cover all cases when we have to manually re-type all the same type-name-aliases more than once. Any extra ones that I've missed?
It was always catching my eye, but I had no time to refactor it in the past.
=> Microrefactoring: use more constants for type names

mypy/checker.py, test-data/unit/check-enum.test
=> Fix `Enum` final props and writable special members

mypyc/codegen/emitfunc.py, mypyc/test/test_emitfunc.py
If we switch true/false branches, we also need to switch between
likely/unlikely.
This has an impact at least on accessing module-level final attributes
with non-constant initializers. I couldn't see a significant
difference in benchmark results compare to master, but this seems to 
help together with some other work-in-progress improvements I have 
been working on (and the old behavior was clearly wrong).
=> [mypyc] Fix invalid unlikely() in certain rare branches

mypy/constraints.py, mypy/semanal.py, mypy/subtypes.py, mypy/types.py
I saw that `refers_to_fullname` cannot use our new `mypy.types.FINAL_DECORATOR_NAMES` constant to work. So, I've decided to allow that.
In the process:
- I've also simplified `is_named_instance` function to allow `Tuple` as well (I use `Tuple`, because it is used for constants)
- I've also reused `is_named_instance` in `refers_to_fullname`
- Refactored several tuple-specific names into a new constant
=> Refactor `is_named_instance` and `refers_to_fullname`

mypy/semanal.py, test-data/unit/check-enum.test, test-data/unit/merge.test
Fixes #11919 
This allows using enum values in place of literals.
For example:
```
def is_a(a: Literal["a"]): return None
class MyStr(Enum):
a = "a"
b = "b"
is_a(MyStr.a.value)
```
Currently this fails with
```
error: Argument 1 to "is_a" has incompatible type "str"; expected "Literal['a']"
```
The fix itself is simple - the special casing of final status for enums was being
called too late to have an effect. Moving the function call up solves
the problem.
Added a test and fixed tests that were broken by this feature
=> Make enum values final - fixes #11919

mypyc/codegen/emitfunc.py, mypyc/test-data/run-classes.test, mypyc/test/test_emitfunc.py
Previously we only raised it for refcounted types when an attribute was
undefined, potentially resulting in errors like this:
```
SystemError: initialization of m failed without raising an exception
```
Unfortunately, this slows down the richards benchmark by about 15%. We
can get the lost performance back once we have support for always
defined attributes, at the latest.
=> [mypyc] Raise AttributeError also for non-refcounted types

docs/source/literal_types.rst
The final two `reveal_type` calls [here](https://mypy.readthedocs.io/en/stable/literal_types.html#intelligent-indexing) appear to be incorrectly documented. (Index 1 holds a float, not a str)
To verify the error, run mypy against [this gist](https://gist.github.com/ChrisKeefe/b95d4812f31c6f2517b750ed97e8f463) or copy-paste the code from the public docs. 
Using the same index across all of these tuple examples feels more readable to me than changing the reported type in the comments, but I'm happy to switch it up if anyone disagrees.
Docs build successfully:
=> DOC: Fixes Intelligent indexing example

mypy/stubtest.py
=> Ignore more exceptions in stubtest

.github/workflows/test.yml, test-requirements.txt
Refs https://github.com/python/mypy/issues/11662
=> Add `3.11-dev` as `TODO` item says

mypy/checkexpr.py
I don't think we should target `python1.x` 😆
=> Microrefactoring: `py_version <= 2` should be `py_version == 2`

mypy/semanal.py, test-data/unit/check-enum.test, test-data/unit/pythoneval.test
Allows `PlaceholderNode` objects before raising an error for the attempted
reuse of a member name inside an `Enum`.
As explained in #11971 I (unfortunately) was not yet able to find a minimal reproducing example for this.
I can verify that this fixes my scenario via which I encountered the bug, but this is obviously not sufficient.
If you have any ideas how we can reproduce this, I am happy to add a corresponding unittest.
=> Fix #11971

docs/source/error_code_list.rst, mypy/errorcodes.py, mypy/semanal.py, test-data/unit/check-errorcodes.test
Adds a new `no-overload-impl` error code that is raised when overloaded functions outside of stub files are not followed by an implementation. 
I validated the doc changes and all tests are passing locally. I did not find anywhere in the tests that the error code of specific failures is checked, but please let me know if I missed something.
=> Add no-overload-impl error code

docs/source/running_mypy.rst
Reading the documentation about [how imports are found](https://mypy.readthedocs.io/en/stable/running_mypy.html#how-imports-are-found), I was confused by the note: 
"You cannot point to a [PEP 561](https://www.python.org/dev/peps/pep-0561/) package via the `MYPYPATH`, it must be installed (see [PEP 561 support](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages))".
I did not know what a PEP 561 package was, so I went to skim the documentation. This did not make me much wiser, since it describes multiple ways of distributing type hints, e.g. by providing the `py.typed` file. From [PEP 561 support](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages) it seems like what is actually referred to is specifically stub-only packages (also …
=> Clarify stub-only packages need to be installed

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
Fixes #11921
Dataclasses that inherit from Any (actually another type that we don't
know) should allow any constructor.
The way this bug was noticed was while importing a class that mypy didn't know
about with the `--ignore-missing-imports` flag:
```python
import dataclasses
from mypackage import MyClass
@dataclasses.dataclass
class Inherits(MyClass):
foo: str
i = Inherits(foo="hi", bar="bye")
```
Added appropriate test case
=> Fix __init__ in Dataclasses inheriting from Any

.github/workflows/test.yml
Closes https://github.com/python/mypy/pull/12002
Refs https://github.com/python/mypy/pull/11984
=> Fix CI by allowing it to fail on `3.11`

mypy/checkexpr.py, test-data/unit/check-unions.test
There are several discussions and comments describing the following problem (references can be found at the end of this post):
```python
def func() -> str | NoReturn:
...
func().lower()
```
At the moment the code results in: `"NoReturn" of "Union[str, NoReturn]" has no attribute "lower"`
`Union[int, NoReturn]` should be equivalent to `int`, because in case the function returns it must be `int`.
For every call expression apply `make_simplified_union`, which is already capable of transforming  `Union[int, NoReturn]` to `int`.
```
ret_type = self.check_call_expr_with_callee_type(...)
...
if isinstance(ret_type, UnionType):
ret_type = make_simplified_union(ret_type.items)
```
The following test case was added to verify the implementation is working as intended:
```
[case` …
```
=> Fix handling of NoReturn in Union

mypy/checker.py, mypy/semanal.py, mypy/stubtest.py, mypy/util.py, test-data/unit/check-enum.test, test-data/unit/check-incremental.test
Changes:
- I've moved all `final` detection logic from `semanal.py` to `checker.py`. Why? Because we need type checking! For example, methods, properties, and other descriptors are not counted as `Enum` membres
- We don't modify `.is_final` anymore. Why? It is too disruptive. Now this is a special-case for `Enum` only
Closes #11850
=> Move `final` detection for `Enum` in `checker.py`

mypy/fastparse.py
This should fix wheel builds. Our CI always targets Python 3.6
when doing a self check, which means that we won't catch issues
specific to more recent Python versions.
=> Fix self-check when targeting Python 3.10

mypy/meet.py
For some reason both `si` and `self.s` was used in this piece of code.
I think that it is more readable to use just `self.s`
=> Microrefactoring: removed useless var from `meet.py`

mypy/stubtest.py, mypy/test/teststubtest.py
Fixes https://github.com/python/typeshed/pull/6939
=> stubtest: treat dicts as a subtype of typeddict

docs/source/generics.rst
As far as I can tell, the nugget exposed by this commit lives only in PEP 544. This
copies that nugget closer to where it is likely to be spotted by the intended audience.
PEPs may not be accessible to customers who reasonably expect relevant information to be
surfaced in featured documentation. Even if customers are aware of PEPs, they may not
think to look there, and don't likely consider them primary sources. It is reasonable to
assume that is the job of the docs, with PEPs capturing more esoteric nuances,
rationales and other then-relevant details of decision-making, etc. It's also reasonable
to expect that where further study may be helpful, links from relevant sections of
primary sources to secondary materials like PEPs should exist. This commit fills in both
gaps for the subject …
=> Explain generic `Protocol[T1, T2, ...]` shorthand in Mypy docs

mypy/erasetype.py, mypy/join.py, mypy/test/testtypes.py, mypy/test/typefixture.py, test-data/unit/check-enum.test
When we erase last known values in an union with multiple
Instance types, make sure that the resulting union doesn't have
duplicate erased types. The duplicate items weren't incorrect as such,
but they could cause overly complex error messages and potentially
slow type checking performance.
This is one of the fixes extracted from #12054. Since some of the
changes may cause regressions, it's better to split the PR.
Work on #12051.
=> Simplify unions when erasing last known values

mypy/join.py, test-data/unit/check-enum.test
Make the join of a union type and Any commutative.
Previously the result dependend on the order of the operands,
which was clearly incorrect.
Fix #12051, but other use cases are affected as well.
This change was split off from #12054.
=> Fix join of Any against a union type

mypy/errors.py, test-data/unit/check-errorcodes.test
If we change the error code of a message, it can result in existing
"type: ignore" comments being ignored. If this seems to be the case,
add a note that hints about changing the ignored error code.
Give a more specific message for a set of special cased error codes
where we know the original error code. In other cases give a more
vague message.
=> Add note about wrong error code in type: ignore

mypy/types.py, test-data/unit/check-typeddict.test, test-data/unit/fixtures/typing-typeddict.pyi
Fixes #12038. This adds an accept method to Required that delegates to the inner type. @davidfstr 
I ran the tests locally and they passed. I added two small test cases to check-typeddict.test that correspond to fixed crash.
=> Fix crash involving explicit any flag and Required

docs/source/config_file.rst
Brings INI and TOML examples in line as noted.
=> Fix error in `exclude` section

docs/source/command_line.rst, docs/source/config_file.rst
I noticed the docs don't mention a rule of `allow_redefinition`
=> [docs] add more info to allow_redefinition

mypy/semanal.py, test-data/unit/check-parameter-specification.test
I've decided to add a note to users that other arguments to `ParamSpec` are not supported.
Because right now they are allowed. But, they do not make any sense.
See https://github.com/python/typing/issues/1027
=> Forbid extra `ParamSpec` arguments

mypy/checkexpr.py, mypy/ipc.py
A tiny cleanup
No new tests added, self-check will error if something is wrong
=> Delete workarounds for fixed typeshed bugs

mypy/stubtest.py, mypy/test/teststubtest.py
Stubtest now errors if `class SubClass(some_class): pass` errors at runtime, but `some_class` isn't marked with `@final` in the stub.
New errors from `--check-typeshed`, checked against typeshed commit 92d135a3:
```
_curses.window cannot be subclassed at runtime, but isn't marked with @final in the stub
_json.make_encoder cannot be subclassed at runtime, but isn't marked with @final in the stub
_json.make_scanner cannot be subclassed at runtime, but isn't marked with @final in the stub
_tkinter.TkttType cannot be subclassed at runtime, but isn't marked with @final in the stub
asyncio.constants._SendfileMode cannot be subclassed at runtime, but isn't marked with @final in the stub
ctypes.Array cannot be subclassed at runtime, but isn't marked with @final in the stub
ctypes._SimpleCData …
```
=> stubtest: error if a class should be decorated with @final

mypy/build.py, test-data/unit/cmdline.pyproject.test
On Windows (where the default encoding for `open` is usually not UTF-8), attempting to load mypy's configuration from a `pyproject.toml` fails due to being unable to decode unicode characters. With this patch, the file is read with UTF-8 as the encoding on all platforms.
Fixes #11058
Added a test which loads mypy's configuration from a `pyproject.toml` file containing non-ASCII characters.
=> Read pyproject.toml with correct encoding on Windows.

mypyc/irbuild/prepare.py
I've been running `mypyc` on a codebase and hitting frequent `AssertionError` with no helpful message. This change simply adds a helpful error message so the next fool who runs into this doesn't have to poke through `mypyc` code to find out the problem.
N/A (Should a test be added? I didn't see any failure tests for `irbuild` :thinking: )
=> Add helpful message to assert in mypyc

.github/workflows/mypy_primer_comment.yml
This PR adds a useful feature: now empty `primer` output will still add a comment: "According to mypy_primer, this change has no effect on the checked open source code."
Why is it useful?
Because in some cases it is not clear: is `mypy_primer` happy? Or is it broken?
For example, this PR https://github.com/python/mypy/pull/12118 does not have any comment.
I guess it would also benefit PR authors who can be sure that what they did is correct.
I will wait for `mypy_primer` to comment on this PR 🙂
=> Sync `mypy_primer_comment` with `typeshed`

mypy/build.py, test-data/unit/cmdline.test
Might help with breaking changes that result from #9636
=> Mention common resolutions for build errors

mypy/semanal.py, mypy/typeanal.py, mypy/types.py, test-data/unit/check-unreachable-code.test, test-data/unit/lib-stub/typing.pyi, test-data/unit/lib-stub/typing_extensions.pyi
This will exist in 3.11 and in the next release of typing-extensions. See python/cpython#30842 and python/typing#1060. The implementation simply introduces a new synonym for `NoReturn`.
I didn't do anything with `typing.assert_never` because it doesn't have any special semantics: it should work just based on the annotations.
I also added explicit support for `typing_extensions.NoReturn`. I think that one doesn't matter in practice because the typeshed stub for typing-extensions just re-exports `typing.NoReturn`. Still, it's nice for completeness.
=> Add support for Never

mypy/plugins/attrs.py, mypy/plugins/common.py, test-data/unit/check-attr.test, test-data/unit/lib-stub/attr/__init__.pyi
This is a very basic implementation. I am not yet very familiar with `__match_args__`. 
Are there any corner cases that I am missing?
=> Add `match_args` support to `attr.s()`

mypy/build.py, mypy/semanal.py, test-data/unit/check-type-aliases.test, test-data/unit/cmdline.pyproject.test, test-data/unit/fixtures/typing-medium.pyi
=> Fix use of TypeAlias from aliased imports

mypy/stubtest.py
stubtest currently does not complain if a dunder method in a stub file has an argument that should be positional-only, but is marked in the stub as being positional-or-keyword. This PR proposes to remove this exception.
Removing the exception will increase our confidence in the accuracy of typeshed stubs with regard to positional-only arguments.
The rationale for the exception was the very large number of complaints stubtest had when checking typeshed. However, I have been using this patch over the past few days to file a series of PRs to typeshed, in order to minimise the impact of this PR:
<details>
- https://github.com/python/typeshed/pull/7220
- https://github.com/python/typeshed/pull/7221
- https://github.com/python/typeshed/pull/7223
- https://github.com/python/typeshed/pull/7224
- …
=> stubtest: error for pos-only differences for dunder methods, too

mypy/typeanal.py, test-data/unit/check-functions.test, test-data/unit/fixtures/any.pyi
Using `any` instead of `Any` is an easy mistake to make because "any" has been used as a type in docstrings, editors may highlight it as it's the name for the built-in function and at least TypeScript uses it as a keyword. Here are [some examples](https://grep.app/search?q=%3A%20any%28%5C%5B%7C%2C%7C%20%3D%29&regexp=true&case=true&filter[lang][0]=Python) of this mistake in real-world Python code.
For example, for the following code:
```python
def a(b: any): pass
```
mypy currently outputs:
```
any.py:1: error: Function "builtins.any" is not valid as a type
any.py:1: note: Perhaps you need "Callable[...]" or a callback protocol?
```
I think that the given suggestion is misleading and could be improved. This pull request changes the output to:
```
any.py:1: error: Function "builtins.any" is …
```
=> Improve suggestion when using `any` as type

mypy/checkmember.py, mypy/semanal_enum.py, mypy/typeops.py, mypy/types.py, mypyc/irbuild/classdef.py, test-data/unit/check-enum.test
Similar to \_order\_ (which mypy already handles), \_ignore\_ is deleted by EnumMeta. Currently, (#12121) mypy thinks it's an error to set \_ignore\_ in an Enum subclass because 'Cannot override writable attribute "\_ignore\_" with a final one.' This PR both:
1. Makes mypy ok with setting `_ignore_` in the class body; and
2. Makes it an error to later access the (deleted) `_ignore_` attribute ('Type[E] has no attribute "\_ignore\_"')
The PR adds a test that accessing `_ignore_` after the class definition is flagged as an error. I wanted to test that (1) above has been fixed, but I couldn't figure out how to make a failing test. So I went "out of band" from the unit test themselves; I created a simple test file:
```py
from enum import Enum
class E(Enum):
_ignore_ = '' # how to assert that …
```
=> Understand the self-destructing nature of Enum._ignore_

docs/source/error_code_list2.rst, docs/source/error_codes.rst, mypy/errors.py, test-data/unit/check-errorcodes.test
#11633 added the awesome `ignore-without-code` option. During testing I noticed that in some cases an error code would be displayed multiple times. This can be rather annoying, since it's only necessary to ignore an error code once.
```
error: "type: ignore" comment without error code (currently ignored: [union-attr, arg-type, union-attr])
```
```
error: "type: ignore" comment without error code (currently ignored: [arg-type, union-attr])
```
/CC: @PeterJCLaw
_Added a new test case._
=> Deduplicate error codes for `ignore-without-code`

mypy/typeanal.py, test-data/unit/check-functions.test
Follow-up PR based on [this comment](https://github.com/python/mypy/pull/12185#pullrequestreview-883767917). Now for:
```python
def c(d: callable): pass
```
mypy will suggest:
```
callable.py:1: error: Function "builtins.callable" is not valid as a type
callable.py:1: note: Perhaps you meant "typing.Callable" instead of "callable"?
```
Added a unit test to verify the new output.
=> Suggest `typing.Callable` when using `callable` as type

mypyc/analysis/ircheck.py, mypyc/ir/ops.py, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-dict.test, mypyc/test/test_ircheck.py
This includes checks for:
- duplicate op (caused obscure bug in developing another PR that was hard to debug)
- Call operations
- Control ops
- Literal loads
- Assignments and Return (basic type coercion checking)
=> [mypyc] Implement additional ircheck checks

mypy/stubtest.py, mypy/test/teststubtest.py
Stubtest does not currently error if a function is async at runtime, but not in the stub (or vice versa). This PR fixes that!
This is an attempt at implementing a regression test for these typeshed PRs:
- https://github.com/python/typeshed/pull/6783
- https://github.com/python/typeshed/pull/7105
- https://github.com/python/typeshed/pull/7107
cc. @hauntsaninja
I've added four test cases. Note that the test file needed a bit of rejigging, as `Coroutine` wasn't defined in the stub for `typing` that `teststubtest` was using.
The changes in this PR generate three hits when checking typeshed. I'm not sure if they're true positives or not tbh:
```
error: types.AsyncGeneratorType.__anext__ is a coroutine function in the stub, but not at runtime
Stub: at line 239
def (self: …
```
=> stubtest: error if a function is async at runtime but not in the stub (and vice versa)

docs/source/error_code_list2.rst, mypy/errors.py, test-data/unit/check-errorcodes.test
Followup to https://github.com/python/mypy/pull/12194#issuecomment-1043399272
Update message for `ignore-without-code` to better capture the spirit of the check.
I've changed `use` to `consider` as suggested since I also feel this is slightly better. I'm open for other / better ideas.
Another question, do we want to remove the space between different error codes? I feel that might be a tick better.
```diff
- ... (consider "type: ignore[arg-type, union-attr]" instead)
+ ... (consider "type: ignore[arg-type,union-attr]" instead)
```
/CC: @hauntsaninja @PeterJCLaw
=> Update `ignore-without-code` message

mypy/stubtest.py, mypy/test/teststubtest.py
This PR alters stubtest so that it raises an error if a dunder method is missing from a stub. Currently, stubtest does raise an error for a few missing dunders (`__call__`, `__class_getitem__`, etc.). However, for the vast majority of them, it does not raise an error.
I have been using this patch to provide a number of fixes to typeshed over the past week or so:
<details>
- https://github.com/python/typeshed/pull/7248
- https://github.com/python/typeshed/pull/7244
- https://github.com/python/typeshed/pull/7242
- https://github.com/python/typeshed/pull/7231
- https://github.com/python/typeshed/pull/7216
- https://github.com/python/typeshed/pull/7214
- https://github.com/python/typeshed/pull/7212
- https://github.com/python/typeshed/pull/7210
- https://github.com/python/typeshed/pull/7210
- …
=> stubtest: error if a dunder method is missing from a stub

mypy/stubtest.py, mypy/test/teststubtest.py
Basically a follow up to #12203
New errors in typeshed from this:
```
_decimal.__libmpdec_version__ is not present in stub
_heapq.__about__ is not present in stub
builtins.__build_class__ is not present in stub
cgitb.__UNDEF__ is not present in stub
decimal.__libmpdec_version__ is not present in stub
sys.__unraisablehook__ is not present in stub
```
Some general housekeeping, moving things around, renaming things, adding
some comments.
=> stubtest: error if module level dunder is missing, housekeeping

mypy/stubtest.py
Fixes for https://github.com/python/typeshed/issues/7307
Amusingly, the evil runtime module that is causing havoc is... mypy,
which sqlalchemy has some extension for.
=> stubtest: catch more getattr errors

mypyc/codegen/emitwrapper.py
Follows up to https://github.com/python/mypy/pull/10679
The `WrapperGenerator` is an abstract class for wrapper generation, originally from `generate_wrapper_core`. The latter one is fully covered by the `WrapperGenerator`.
=> [mypyc] Refactor: Use WrapperGenerator for generate_wrapper_core

mypy/constraints.py, test-data/unit/check-protocols.test
We used to infer a callable in a protocol against all overload
items. This could result in incorrect results, if only one
of the overload items would actually match the protocol.
For example, we could get incorrect constraints from
an incompatible overload item.
Fix the issue by only considering the first matching overload
item.
This seems to help with protocols involving `__getitem__`.
In particular, this fixes regressions related to
`SupportsLenAndGetItem`, which is used for `random.choice`.
=> Fix inference of protocol against overloaded function

mypy/checker.py, test-data/unit/check-enum.test
Checks in Python's source:
- No classes after `Enum` base: https://github.com/python/cpython/blob/d05a66339b5e07d72d96e4c30a34cc3821bb61a2/Lib/enum.py#L971-L974
- Only a single data type: https://github.com/python/cpython/blob/d05a66339b5e07d72d96e4c30a34cc3821bb61a2/Lib/enum.py#L1011-L1012
Closes https://github.com/python/mypy/issues/11948
=> Check `Enum` definition for invalid base classes

mypy/checker.py, mypy/fastparse2.py, mypy/nodes.py, test-data/unit/check-python2.test
I hope that this time we've covered everything 🙂 
Closes https://github.com/python/mypy/issues/11742
Related https://github.com/python/mypy/pull/11743
Related https://github.com/python/mypy/pull/11289
Related https://github.com/python/mypy/issues/11700
=> Handle `raise Exception(), None` on Python2.7

mypyc/lib-rt/dict_ops.c, mypyc/lib-rt/exc_ops.c, mypyc/lib-rt/generic_ops.c, mypyc/lib-rt/misc_ops.c
We are using `Py_TYPE` in many places, however keeping several direct calls to `ob_type`. Replace them with `Py_TYPE` to maintain consistency. This PR also replaces `== Py_None` with `Py_IsNone` as `pythoncapi_compat` suggests.
=> [mypyc] Use Py_TYPE and Py_IsNone

mypy/typeshed/stdlib/logging/__init__.pyi
Fixes some regressions.
Context: https://github.com/python/typeshed/issues/7258
=> Typeshed cherry-pick: Replace some literal types in logging (#7354)

mypy/typeshed/stdlib/types.pyi
=> Typeshed cherry-pick: Use int|Any for types.FrameType.f_lineno (#6935)

mypy/constraints.py, test-data/unit/check-protocols.test
This fixes a regression where `iter(x)` could generate a false
positive if `x` has a type variable type with a bound.
=> Use type variable bound to infer constraints

docs/source/literal_types.rst
After merging https://github.com/python/mypy/pull/11805 I found out that we are missing several new `Enum` features.
This PR adds them to the docs.
Refs https://github.com/python/mypy/pull/12026
Refs https://github.com/python/mypy/pull/12035
=> Update `Enum` docs

mypy/pyinfo.py
I'm not adding a test because it's Python 2, but I did test locally.
Fixes #12202
=> Make pyinfo compatible with Python 2

mypyc/test-data/run-multimodule.test, mypyc/test/test_run.py
Tests for multi-file and separate compilation modes are a bit
special, and it seems useful to have more documentation.
=> [mypyc] Improve comments and docstrings in tests

mypy/build.py, mypy/checker.py, mypy/checkexpr.py, mypy/nodes.py, mypy/semanal.py, test-data/unit/check-expressions.test
Now `__future__` imports do not leak in `semanal.py`.
Closes #11740
Refs https://github.com/python/mypy/pull/11741
Refs https://github.com/python/mypy/pull/11276
Refs https://github.com/python/mypy/issues/11700
=> Use `__truediv__` for python2 with `__future__` import, refs #11740

mypy/build.py, mypy/renaming.py, test-data/unit/check-python310.test, test-data/unit/check-statements.test, test-data/unit/semanal-statements.test
Use renaming to allow two with statements to define the same variable
using incompatible types. The implementation is pretty simple-minded
and doesn't work in cases where there is even a hint of potential 
ambiguity about which variant of a variable a reference targets, typically 
due to functions.
This could be generalized to for statements in the future.
Fixes #12246.
=> Give "as" variables in with statements separate scopes

mypy/renaming.py
Forgot to address this feedback in #12254.
=> Minor comment tweaks

mypy/stubtest.py, mypy/test/teststubtest.py
This relaxes the new check introduced in #12212, which turned out to result in too many false-positive errors when checking stubs for third-party async libraries such as `aiofiles` (see https://github.com/python/typeshed/issues/7344).
cc. @hauntsaninja
=> Stubtest: do not error if a function is async in the stub, but not at runtime

mypy/checker.py, test-data/unit/check-enum.test
=> Fix enum regression #12258

mypyc/ir/pprint.py, test-data/unit/semanal-typeddict.test
`mypy` wound't support this syntax since it's deprecated and will be removed.
=> Remove test case for TypedDict with kwargs

docs/source/more_types.rst
=> Small doc improvements for conditional overloads

mypy/test/teststubtest.py, test-requirements.txt
yes
Fixes https://github.com/python/mypy/issues/11019
`run_stubtest` creates temp directory and prepend `sys.path` with relative path (dot `.`) wrongly assuming that the dot will be resolved to absolute path on *every* import attempt.
But in Python dot(`.`) in sys.path is actually resolved by PathFinder and cached in `sys.path_importer_cache` like:
```
sys.path_importer_cache['.']
FileFinder('/somepath/.')
```
later calls for `find_module` return None and import of `test_module` fails. This resulted in only the first test in stubtest's suite passed in non-pytest-xdist environments.
This issue was hidden with bug or feature in pytest-xdist < 2.3.0:
https://github.com/pytest-dev/pytest-xdist/issues/421
It was fixed in pytest-xdist 2.3.0:
https://github.com/pytest-dev/pytest-xdist/pull/667/ …
=> stubtest: Fix wrong assumption about relative path

mypy/test/teststubtest.py
Basically a follow up to #12282
=> teststubtest: further fix tests

mypy/stubtest.py
This reverts commit 777885f2c26cce195f6d23c80fefae1e66dfaac2.
To help with https://github.com/python/typeshed/issues/7441 and reduce risk of stubtest issues interfering with a mypy release. The extra type correctness here is really minimal.
=> Revert "stubtest pos-only differences in dunders (#12184)"

mypy/stubtest.py
This isn't actually a reversion. This logic was asymmetrical for reasons
lost to time. Although I suspect it was this way because the delta
only a few errors on typeshed.
What changed was that as a result of #12203 we actually started checking
a lot more dunder methods. Previously, we only checked dunders if either:
a) it was a special dunder, like `__init__` or `__call__`, or
b) the dunder was defined on the actual stub class itself
In particular, we started checking every dunder redefined at runtime
that the stub just inherited from object.
A possible intermediate option would be to not check positional-only
arguments in the case where a stub inherits the definition. I'll
experiment with that once typeshed CI is green.
=> stubtest: ignore more dunder pos-only errors

.github/workflows/mypy_primer.yml
PRs that only affect stubtest or stubgen are never going to have any effect on mypy_primer's output, so we can safely skip the CI check for those PRs. The same goes for PRs that only alter files in the tests directory.
=> CI: Do not run mypy_primer on stubtest/stubgen PRs

mypy/version.py, setup.py
This will allow us to stop internally having to overwrite the `__version__` file with the commit sha we use in dbx_build_tools.
=> Support MYPY_VERSION for overriding version

mypy/checker.py, mypy/errorcodes.py, mypy/message_registry.py, test-data/unit/check-async-await.test, test-data/unit/check-class-namedtuple.test, test-data/unit/check-flags.test, test-data/unit/pythoneval-asyncio.test
Generates an error when an expression has a type which has a
defined __await__ in its MRO but is not used. This includes all
builtin awaitable objects (e.g. futures, coroutines, and tasks)
but also anything a user might define which is also awaitable.
A hint is attached to suggest awaiting.
This can be extended in the future to other types of values that
may lead to a resource leak if needed, or even exposed as a plugin.
=> Error on unused awaitable expressions

mypyc/lib-rt/CPy.h, mypyc/lib-rt/int_ops.c, mypyc/lib-rt/misc_ops.c
In CPython, the id of an object is its address. It's computed by converting the pointer to an unsigned integer (`PyLong_FromVoidPtr`). A similar logic is present here, pointer is converted to a `Py_ssize_t` and `CPyTagged_FromSsize_t` is called with that integer.
There is a problem with that approach: `Py_ssize_t` cannot hold every pointer value. Sometimes overflow happens and `CPyTagged_FromSsize_t` is called with a negative integer.
With the new approach, the number is checked: If it fits in a `Py_ssize_t`, `CPyTagged_FromSsize_t` is called. If not, it is directly
converted to a `PyObject` using `PyLong_FromVoidPtr`.
Fixes #11148.
I used the Docker test in #11148. I could reproduce failure before the changes, it passed after the changes.
=> mypyc: Fix overflow in id function (CPyTagged_Id)

mypy/version.py, setup.py
This reverts commit 3a5b2a996af8e0333e5eebbdbadc9eec3d1f310e.
Attempting to fix builds. I think that we need the commit hash in the version.
=> Revert "Support MYPY_VERSION for overriding version"

mypy/fastparse.py, test-data/unit/check-overloading.test
We shouldn't merge conditional FuncDefs after an unconditional one. This matches the behavior pre 0.940.
```py
from typing import overload
class A: ...
class B: ...
@overload
def f2(x: A) -> A: ...
@overload
def f2(x: B) -> B: ...
def f2(x): ...
if True:
def f2(x): ...   # E: Name "f2" already defined on line ...
```
Closes #12335
=> Fix small conditional overload regression

docs/source/config_file.rst
In the configuration documentation, `disable_error_code` is [documented](https://github.com/python/mypy/blob/0d38613d8bd156a793a2f9f0f8f331499ad31531/docs/source/config_file.rst#miscellaneous-strictness-flags), but its counterpart `enable_error_code` is not, although `--enable-error-code` flag is documented in [the command line documentation](https://github.com/python/mypy/blob/e2852039bafaf0d7463623dd5410c02797eae21b/docs/source/command_line.rst#miscellaneous-strictness-flags).
This PR adds `enable_error_code` to the configuration documentation, with a description similar to `disable_error_code`. It also adds a similar note as the one found for `--enable-error-code` flag documentation.
=> Add missing `enable_error_code` to configuration documentation

mypy/typeshed/stdlib/email/message.pyi
Typeshed cherry-pick: Use import instead of type alias in `email/message.pyi` (#7022)
Fixes #12339 
I've confirmed that this resolves the type checking error introduced in 0.940 using hamcrest as a testbed.
=> Cherry pick the typeshed fix for 12339

docs/source/builtin_types.rst
Closes #10985 
This PR adds ``type`` and ``Type`` with a description each to both of the list of generic types in builtin_types section.
=> Add ``type`` to both lists of generic types (#10985)

mypy/constraints.py, mypy/erasetype.py, mypy/expandtype.py, mypy/fixup.py, mypy/indirection.py, mypy/join.py, mypy/main.py, mypy/meet.py, mypy/message_registry.py, mypy/options.py, mypy/sametypes.py, mypy/semanal_typeargs.py, mypy/server/astdiff.py, mypy/server/astmerge.py, mypy/server/deps.py, mypy/subtypes.py, mypy/test/testsemanal.py, mypy/type_visitor.py, mypy/typeanal.py, mypy/types.py, mypy/typetraverser.py, test-data/unit/lib-stub/typing_extensions.pyi, test-data/unit/semanal-errors.test
Adds very basic support for Unpack expressions (where Unpack
is either from typing or typing_extensions). Many of the visitors
implementations are not implemented yet.
The only supported feature we have so far is validating that the
argument to UnpackType actually makes sense. Currently we don't
support unions, though. Since TypeVarTuple isn't yet implemented,
we don't support that from UnpackType either.
We don't want anyone to start using variadic generics at all until
we have real support for it. We also don't want to implement it in
one huge PR. So mypy is learning a new flag called
--enable-incomplete-features which we can enable by default in any
testsuite that needs to use incomplete features, as well as pass on
the command line for debugging, but it is undocumented and suppressed …
=> Add UnpackType type and basic semanal

mypy/dmypy_server.py, mypy/main.py, mypy/util.py
Closes #12302 
The `messages` here could be neither error nor note, thus I modify the `count_stats ` to also count `note`.
=> Add success msg for only notes output

test-data/unit/check-flags.test
This fixes a test case, the test case included a sussy NBSP which resulted in the test being completely invalid.
I have now updated the testcase to vent the impostor expect the correct result instead.
With nbsp:
`x.trifdsgdfgm()  # E: AMONGUS [attr-defined]`
```
> pytest -n0 -k testEnableDifferentErrorCode
...
1 passed
```
with space:
`x.trifdsgdfgm()  # E: AMONGUS [attr-defined]`
```
> pytest -n0 -k testEnableDifferentErrorCode
...
_____________________________________________________________________________________________________ testEnableDifferentErrorCode _____________________________________________________________________________________________________
data: /home/amongus/projects/mypy/test-data/unit/check-flags.test:1991:
/home/amongus/projects/mypy/mypy/test/testcheck.py:140: …
```
=> Vent sussy NBSP from test case

mypy/build.py, test-data/unit/check-errorcodes.test, test-data/unit/cmdline.test, test-data/unit/pep561.test, test-data/unit/semanal-errors.test
Fixes #12232
Another "fail every 2nd run" bug
`if not self.is_module(sub_id):`, the parent can come before another child, and we fail to resolve the parent.
=> Fix caching of PEP 561 namespace packages with missing submodules

mypy/find_sources.py
flake8-bugbear released a new version with new checks.
SourceFinder is small (and we don't have many of them), so this isn't a
particularly big deal.
=> find_sources: fix lint

mypy/stubtest.py, mypy/test/teststubtest.py
This PR proposes adding checks to stubtest so that it raises an error if a variable is annotated as being writeable in the stub, but is a read-only property at runtime.
0; however, this patch was used to prepare the following PR, fixing roughly 50 hits:
- https://github.com/python/typeshed/pull/7395
- Checking the opposite scenario as well: raising an error if an attribute was marked as read-only in a stub but was a read-write property at runtime. This resulted in many false positives and 0 true positives.
- Adding a similar check for other common descriptors, such as instances of `types.GetSetDescriptorType`. Unfortunately, it is much harder to accurately determine whether or not an instance of `GetSetDescriptorType` is a read-only data descriptor, or a read-write data descriptor. (All …
=> stubtest: error if an attribute is a read-only property at runtime, but isn't read-only in the stub

README.md
Add pypi badge to readme:
I forced the label color to blue because shields thought 0.941 was a pre-release(😅)
N/A
=> readme: add pypi badges

mypy/messages.py
=> Fix: Empty reveal locals ouput

mypy/checker.py, mypy/message_registry.py, test-data/unit/check-python310.test
Allow subclasses to override `__match_args__` freely, and don't require
`__match_args__` to be final. 
This matches runtime behavior. For example, if `B` subclasses `A`, 
`case A(...)` also matches instances of `B`, using the `__match_args__` 
from `A`.
The issue was brough up by @AlexWaygood in 
https://github.com/python/mypy/pull/12411#issuecomment-1074078992.
=> Allow non-final __match_args__ and overriding

mypy/checkpattern.py, test-data/unit/check-python310.test
=> Fix crash in match statement if class name is undefined

mypy/checker.py, mypy/message_registry.py, mypy/semanal.py, test-data/unit/check-enum.test
Allows any dunder(`__name__`) attributes except `__members__` (due to it being read-only) to be overridden in enum subclasses.
Fixes #12132 
Added tests to the `check-enum` suite
I'm quite new to mypy's code. So please help out with stuff I might've missed or so. I'm also not sure if I've placed the `__members__` fail correctly or if it's better placed in the analyser. 
I also tried to fix sunder (`_name_`) attributes raising `AttributeError`s, but my changes needs a bit more polishing, so I left it for a later PR. Invalids there will raise during runtime anyways.
=> Support overriding dunder attributes in Enum subclass

mypy/checker.py, mypy/nodes.py, mypy/plugins/attrs.py, mypy/plugins/common.py, mypy/plugins/dataclasses.py, mypy/semanal.py, test-data/unit/check-attr.test, test-data/unit/check-dataclasses.test
Multiple inheritance from dataclasses and attrs classes works at runtime,
so don't complain about `__match_args__` or `__attrs_attrs__` which tend
to have incompatible types in subclasses.
Fixes #12349. Fixes #12008. Fixes #12065.
=> Fix inheritance false positives with dataclasses/attrs

mypyc/irbuild/generator.py, mypyc/test-data/fixtures/ir.py, mypyc/test-data/run-generators.test
Closes https://github.com/mypyc/mypyc/issues/790
This PR implements a close method for mypyc generators according to https://www.python.org/dev/peps/pep-0342/#new-generator-method-close
Added tests for the following cases:
- generator doesn't catch the `GeneratorExit`
- generator intercepts the `GeneratorExit` and raises `StopIteration`
- generator ignores `GeneratorExit`
- generator intercepts `GeneratorExit` but raises `RuntimeError`
=> [mypyc] Implement close method for generators

mypy/build.py
Various things can go wrong if the order of modules in the builtins
SCC that also includes typing, _typeshed and others is adjusted.
Hopefully fixes #12422. May also fix #12421.
=> Make order of processing the builtins SCC predictable

test-requirements.txt
Updates to flake8-bugbear can sporadically break our CI and create noise on PRs. Lets pin it.
=> Pin the version of bugbear

mypy/message_registry.py, mypy/semanal.py, test-data/unit/check-async-await.test, test-data/unit/check-default-plugin.test
Added a check that async for/with is in an async function.
The code and error message are similar to those checking await.
Fixes #10594
I used an expanded example from the issue as a unit test. The example was extended to also cover for loop, with expression and usage outside of a function.
Also fixed another test case using async with expression outside of an async function.
=>  semanal: Check that async for/with is inside an async function

mypy/checker.py, test-data/unit/check-overloading.test, test-data/unit/fine-grained.test
A wider return type can be useful if a decorator used for the overload
implementation gets a more precise return type as part of a typeshed
update.
Closes https://github.com/python/mypy/issues/12434.
=> Let overload item have a wider return type than implementation

test-data/unit/cmdline.test
yes
Python 3.10.3 is more correct about syntax error for
`mypy` test case `testBlocker`.
See https://bugs.python.org/issue46240 for details.
Closes #12451
=> testcmdline: Sync assumption about error message for Python 3.10.3

mypy/stubgen.py, test-data/unit/stubgen.test
Since python/typeshed#7535, typeshed has a new type `_typeshed.Incomplete`,
intended to mark fields that are partly annotated, but need more manual
investigation. This applies to all types generated by stubgen, except
when explicitly annotated with `Any` in the implementation.
I changed all stubgen tests to use `Incomplete` instead of `Any`, except `testExplicitAnyArg` and `testExplicitReturnedAny` that checked explicit `Any` annotations. These tests were kept as is.
=> stubgen: Use _typeshed.Incomplete instead of typing.Any

mypy/traverser.py, test-data/unit/stubgen.test
Since yields in nested functions will not yield outside of the function being analyzed, they can be ignored.
I changed the parent of the class used to find the yields to one that does not search through nested functions.
Fixes #11893
I added code similar to the one from the issue's example to the unit tests.
=> stubgen: Do not consider nested generators for return type

mypy/stubtest.py
#12415 (included in release 0.942) unblocked typeshed from adding missing `__match_args__` attributes (see https://github.com/python/typeshed/pull/7556). This means stubtest is now unblocked from checking the correctness of `__match_args__` attributes in the stub!
N/A
=> stubtest: enable verification of `__match_args__` attributes

mypyc/build.py
Send some more accurate optimization and debug flags to msvc.
This shouldn't fix the broken CI, but I think it's still a good idea to send correct parameters
[GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options): 
`-O0` Reduce compilation time and make debugging produce the expected results. This is the default.
`-O`/`-O1` Optimize. Optimizing compilation takes somewhat more time, and a lot more memory for a large function.
`-O2` Optimize even more.
`-O3` Optimize yet more.
`-Os` Optimize for size
[MSVC](https://docs.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=msvc-170):
`/O1` sets a combination of optimizations that generate minimum size code.
`/O2` sets a combination of optimizations that optimizes code for maximum speed.
`/Od` …
=> mypyc build: when windows use correct optimization and debug flags

mypyc/test/test_run.py
Allow extension file names such as `native.pyd` in addition to
`native.<python-version>.<ext>`. I'm not sure why the file names have
changed, but the new file names seem okay as well.
Fixes #12460.
=> Fix Windows test failures in CI

mypy/semanal.py, test-data/unit/semanal-errors.test
I don't want to have to copy paste this again for `TypeVarTuple`. The downside is the error is less specific. We could fix that by passing in a string or checking `call.callee.name`, but I think it isn't worth it. This error should still be clear enough.
=> Unify a codepath in typevarlike semanal

mypy/plugins/attrs.py, test-data/unit/check-attr.test, test-data/unit/lib-stub/attrs/__init__.pyi, test-data/unit/lib-stub/attrs/converters.pyi
As of version 21.3.0, the attrs project provides its API under both the old `attr` and new `attrs` package names. This PR adds the new names to the various constants so their special behaviour is properly recognised. 
I added additional tests to check for the special behaviour of each new function. Since they have identical behaviour, I don't think duplicating all the tests for the packages is necessary. The stubs are duplicated though to ensure the plugin detects both names and doesn't just rely on object identity via `import`. Currently the implementation defines in `attr` and [imports](https://github.com/python-attrs/attrs/blob/d785c656e5d742a74bf2dc1edfeb4ada789991c8/src/attrs/__init__.py) in `attrs`, but this future-proofs in case that changes.
=> Recognise both `attrs` and `attr` package names in the plugin

mypy/checkpattern.py
Fixed typo.
```
lenght -> length
```
=> Fix typo in checkpattern.py

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
Fixes: #12312 
Related: #10292
`Callable` attributes of a `frozen=True` dataclass were not being handled correctly: `Callable` attributes were being propertized if the dataclass was *not* frozen.
This change will always propertize `Callable` attributes before optionally freezing attributes in the dataclass plugin.
Added a test for Callable types in a frozen dataclass to `test-data/unit/check-dataclasses.test`
=> propertize Callable attributes before freezing dataclasses

docs/source/cheat_sheet_py3.rst
`AnyStr` is unused in the example. I guess it's intended to be used with `IO` as `IO[AnyStr]`, which should be more suitable than `IO[str]`. 
Given the commented instructions in the PR template, I'm not sure how I should rebuild the docs. Please let me know if there is anything missing.
=> `cheatsheet_py3.rst`: `IO[str]` to `IO[AnyStr]`

mypy/checkexpr.py, mypy/checkmember.py, mypy/expandtype.py, mypy/types.py
=> Refactoring: Remove the "erased" attribute of Instance

mypyc/primitives/dict_ops.py
`CPyDict_SetDefaultWithNone` doesn't return a borrowed reference,
since it just calls `CPyDict_SetDefault` which doesn't return a
borrowed reference. Treating the value as borrowed can cause
memory leaks.
=> [mypyc] Fix incorrect borrowed flag for setdefault() primitive

mypyc/irbuild/ll_builder.py, mypyc/test-data/exceptions-freq.test, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-constant-fold.test, mypyc/test-data/irbuild-dict.test, mypyc/test-data/irbuild-generics.test, mypyc/test-data/irbuild-lists.test, mypyc/test-data/irbuild-optional.test, mypyc/test-data/irbuild-set.test, mypyc/test-data/irbuild-statements.test, mypyc/test-data/irbuild-strip-asserts.test, mypyc/test-data/irbuild-tuple.test, mypyc/test-data/refcount.test
This avoids (potentially) creating a new int object 
every time we evaluate an integer literal in a context that
requires a boxed value. In any case this reduces the number
of C calls required.
This speeds up this microbenchmark by about 60%:
```
def f() -> None:
for j in range(1000 * 1000):
a = []
for i in range(10):
a.append(10)
```
In more realistic workloads the impact is hard to
measure and is likely below the noise floor.
=> [mypyc] Implement boxed constant integers as literals

mypy/test/testtypes.py, mypy/test/typefixture.py, mypy/typeops.py
#11962 can generate large unions with many `Instance` types with 
`last_known_value` set. This caused our union simplification algorithm
to be extremely slow, as it hit an O(n**2) code path.
We already had a fast code path for unions of regular literal types. This 
generalizes it for unions containing `Instance` types with last known
values (which behave similarly to literals in a literal type context).
Also fix a union simplification bug that I encountered while writing tests
for this change.
Work on #12408.
=> Fix union simplification performance regression

mypy/checker.py, mypy/message_registry.py, mypy/typeshed/stdlib/builtins.pyi, test-data/unit/pythoneval.test
Don't rely on `object.__slots__` being defined, since it's not
defined at runtime (and currently it's removed in typeshed).
=> Improve checking of "__slots__"

mypy/types.py
This shows up as a bottleneck in some use cases, based on
profiling.
This should help with union simplification (#12526).
=> Speed up Instance.__hash__

mypy/types.py
It can be a bottleneck in some use cases.
=> Speed up LiteralType.__hash__

mypy/checker.py, mypy/join.py, mypy/meet.py, mypy/semanal_main.py, mypy/state.py, mypy/stubtest.py, mypy/subtypes.py, mypy/suggestions.py, mypy/test/testtypes.py, mypy/typeops.py, mypy/types.py, mypy/typestate.py, mypyc/irbuild/main.py
This is very performance critical. Implement a few micro-optimizations
to speed caching a bit. In particular, we use dict.get to reduce the
number of dict lookups required, and avoid tuple concatenation which
tends to be a bit slow, as it has to construct temporary objects.
It would probably be even better to avoid using tuples as keys
altogether. This could be a reasonable follow-up improvement.
Avoid caching if last known value is set, since it reduces the 
likelihood of cache hits a lot, because the space of literal values
is big (essentially infinite).
Also make the global `strict_optional` attribute an instance-level
attribute for faster access, as we might now use it more frequently.
I extracted the cached subtype check code into a microbenchmark 
and the new implementation seems …
=> Speed up caching of subtype checks

mypy/test/testtypes.py, mypy/typeops.py
This tweaks a change made in #12539 that may have slowed things
down. The behavior introduced in the PR was more correct, but it's not
worth a potential major performance regression, since union
simplification is not something we have to get always right for
correctness.
Work on #12526.
=> Further speed up union simplification

mypy/subtypes.py
Mypyc is bad at compiling nested functions. In one use case
we were spending 7% of the mypy runtime just creating closure
objects for `check_argument`. Here I manually inline the nested
function to avoid this overhead.
Work on #12526.
=> Minor proper subtype check optimization

test-data/unit/check-parameter-specification.test
Closes #12033. It's already fixed, but this PR adds the tests from #12096 that ensure it's fixed.
=> Add tests for decorating ParamSpec

mypy/typeshed/stdlib/argparse.pyi
=> Typeshed cherry-pick: Drop some literal types from argparse

mypy/nodes.py, test-data/unit/check-type-aliases.test, test-data/unit/fixtures/typing-medium.pyi
=> Recognise LiteralString as str

README.md
GitHub has dropped support for the unauthenticated git protocol. See https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Change install from git link in README to https

mypy/constraints.py, test-data/unit/check-parameter-specification.test
Fixes #12542
This allows `parameters` to constrain to `Any`. Likely a more general solution would be allowing constraints but I'm not exactly sure of the wanted behavior here so I left in the error (to collect more samples if they exist -- failing loudly).
Added crashing case (in a minimal format)
=> Fix propagated Any constraint

mypy/checkexpr.py, mypy/errorcodes.py, mypy/literals.py, mypy/messages.py, mypy/mixedtraverser.py, mypy/nodes.py, mypy/semanal.py, mypy/server/astmerge.py, mypy/server/deps.py, mypy/server/subexpr.py, mypy/strconv.py, mypy/traverser.py, mypy/treetransform.py, mypy/types.py, mypy/visitor.py, mypyc/irbuild/expression.py, mypyc/irbuild/visitor.py, mypyc/test-data/irbuild-basic.test, test-data/unit/check-expressions.test, test-data/unit/fixtures/typing-full.pyi, test-data/unit/lib-stub/typing.pyi, test-data/unit/semanal-errors.test, test-data/unit/semanal-types.test, test-data/unit/typexport-basic.test
See python/cpython#30843.
The implementation mostly follows that of cast(). It relies on
`mypy.sametypes.is_same_type()`.
=> Add support for assert_type

docs/source/kinds_of_types.rst
The docs elsewhere have been updated to use `list[int]` instead of `typing.List[int]`, but this section still uses the deprecated `typing.Type`.
=> Docs: Use PEP 585 syntax in "The type of class objects"

mypy/checker.py, mypy/semanal.py, mypy/stubgen.py, mypy/stubtest.py, mypy/types.py, test-data/unit/check-overloading.test, test-data/unit/lib-stub/typing_extensions.pyi, test-data/unit/stubgen.test
This always existed, but was an alias for typing.overload. With
python/typing#1140, it will actually make a difference at runtime
which one you use.
=> Support typing_extensions.overload

mypy/checkexpr.py, test-data/unit/check-expressions.test
Noticed in python/typeshed#7655 that it was incorrectly inferring list[Any]
in all cases. This is because I incorrectly put Any as the type context
in the assert_type implementation. Use the current context instead, like
for reveal_type().
=> Fix type context for assert_type()

mypy/meet.py, mypy/sametypes.py, mypy/subtypes.py, mypy/typeops.py
As a followup to #9394 address a few more O(n**2) behaviors
caused by decomposing enums into unions of literals.
=> more enum-related speedups

mypy/stubtest.py, mypy/test/teststubtest.py
A followup to https://github.com/python/typeshed/pull/7634#discussion_r851603664
Stubtest currently declines to error if a stub defines a public type alias that doesn't exist at runtime. But it should!
These are the new error reported from running stubtest on the typeshed stdlib, with this patch applied:
```
error: _threading_local.localdict is not present at runtime
Stub: at line 6
Type alias for: builtins.dict
Runtime:
MISSING
error: audioop.AdpcmState is not present at runtime
Stub: at line 3
Type alias for: Tuple[builtins.int, builtins.int]
Runtime:
MISSING
error: audioop.RatecvState is not present at runtime
Stub: at line 4
Type alias for: Tuple[builtins.int, builtins.tuple[Tuple[builtins.int, builtins.int], ...]]
Runtime:
MISSING
error: itertools.Predicate is not present at runtime …
```
=> stubtest: emit error if a stub defines a public type alias that doesn't exist at runtime

mypy/fastparse.py, test-data/unit/check-overloading.test
```py
from typing import overload
class A: ...
class B: ...
class C: ...
class D: ...
@overload
def f1(g: A) -> A: ...
if True:
@overload
def f1(g: B) -> B: ...
if True:
@overload
def f1(g: C) -> C: ...
@overload
def f1(g: D) -> D: ...
def f1(g): ...
```
Closes #12606
=> Fix nested overload merging

mypy/checkpattern.py, mypy/semanal.py, mypy/tvar_scope.py, mypy/types.py, test-data/unit/check-selftype.test
This avoids confusion between type variables of two classes, which can
happen at least in some edge cases. Type variables are only the same if
both the numeric id and namespace match (plus meta level).
Fixes #12588 (though the textual presentation of type variables doesn't 
take the namespace into consideration yet).
=> Use class name as namespace for type variables

test-data/unit/check-selftype.test
Adds a minimised version of @zzzeek's repro in https://github.com/python/mypy/issues/12610#issue-1206397297 to the test suite; closes #12610.
I've confirmed locally that this test fails without #12590, and now passes.
=> Add test case for recently fixed `enumerate` regression

test-data/unit/check-generics.test
This was originally written by @A5rocks in #11657.
Related to #12590.
=> Add overlapping type variables test case

mypy/typeops.py
Recent attempts at speedup introduced some convoluted logic that both
reduced accuracy and caused performance regressions. Fix this and add
more comments to clarify the reasoning behind the optimization.
=> make_simplified_union: simpler and faster

mypy/checkexpr.py, mypy/literals.py, mypy/nodes.py, mypy/semanal.py, mypy/strconv.py, mypy/test/testtransform.py, mypy/treetransform.py, mypy/visitor.py, mypyc/irbuild/visitor.py, test-data/unit/lib-stub/typing_extensions.pyi, test-data/unit/semanal-errors.test, test-data/unit/semanal-types.test
This adds minimal support for a TypeVarTupleExpr node, gated behind the
flag to enable incomplete features. It is modeled after paramspec,
including the part where we don't support the various arguments that
have no behavior defined in PEP646.
We also include TypeVarTuple in the typing_extensions stubs for test
data and add some very basic semanal tests to verify the basic things work.
=> Add TypeVarTupleExpr node

mypy/constraints.py, mypy/erasetype.py, mypy/expandtype.py, mypy/fixup.py, mypy/indirection.py, mypy/join.py, mypy/meet.py, mypy/sametypes.py, mypy/semanal_typeargs.py, mypy/server/astdiff.py, mypy/server/astmerge.py, mypy/server/deps.py, mypy/subtypes.py, mypy/tvar_scope.py, mypy/type_visitor.py, mypy/typeanal.py, mypy/types.py, mypy/typetraverser.py, test-data/unit/semanal-errors.test
This adds the TypeVarTupleType type node and basic semanal/glue.
Type checking involving it will be added in a subsequent PR to keep each PR smaller.
This PR is mostly consisting of modifying all the visitors, but not all of them are implemented.
=> Add TypeVarTupleType type node

test-data/unit/check-selftype.test
Closes #12641.
This test fails without #12590 applied, but passes on master.
=> Add regression test for recently fixed `deque.copy()` bug

test-data/unit/check-generics.test
Closes #5551 (the bug in that issue was fixed by #12590)
=> Add test case for fixed bug regarding nested generic classes

mypy/fixup.py
I've seen crashes like this, which might be caused by not
fixing up some FakeInfos:
```
File "mypy/checkexpr.py", line 3981, in accept
File "mypy/nodes.py", line 1753, in accept
File "mypy/checkexpr.py", line 288, in visit_call_expr
File "mypy/checkexpr.py", line 371, in visit_call_expr_inner
File "mypy/checkexpr.py", line 880, in check_call_expr_with_callee_type
File "mypy/checkexpr.py", line 940, in check_call
File "mypy/checkexpr.py", line 1027, in check_callable_call
File "mypy/checkexpr.py", line 1269, in infer_function_type_arguments
File "mypy/checkexpr.py", line 1324, in infer_function_type_arguments_pass2
File "mypy/infer.py", line 47, in infer_function_type_arguments
File "mypy/constraints.py", line 72, in infer_constraints_for_callable
File "mypy/constraints.py", line 108, in …
```
=> Attempt to fix issue with ParamSpec serialization

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
=> Fix types of inherited attributes in generic dataclasses

docs/source/command_line.rst, docs/source/error_code_list.rst, docs/source/error_code_list2.rst, docs/source/error_codes.rst, docs/source/installed_packages.rst
Document some additional error codes and some general doc updates for
the 0.950 release.
=> Various documentation updates (mostly about error codes)

mypy/build.py, mypy/main.py, mypy/options.py, mypy/test/data.py, mypy/test/helpers.py, mypy/util.py, test-data/unit/cmdline.test
When profiling mypy over a large codebase, it can be useful
to know which files are slowest to typecheck.
Gather per-file timing stats and expose them through a new
(hidden) command line switch
=> introduce per-file timing-stats

mypy/checkexpr.py, mypy/checkpattern.py, mypy/errors.py
#12631 refactored the way error filtering is done but left a bunch of now-unnecessary `MessageBuilder` parameters in many methods.
This change removes all such extraneous parameters, and remove some unused methods.
=> cleanups after recent refactor of error filtering

mypy/checkexpr.py
Replace List with Dict to avoid O(n**2) behavior in `check_for_extra_actual_arguments`
This manifests for instance when initializing a set with `set([...])` instead of a set
literal `{...}`. For large sets of literals (~80k entries) this change bring the
typechecking of a single set initializer from over 1 min down to under 1s.
=> checkexpr: speedup argument count check

mypy/checkexpr.py
`fast_dict_type` and `fast_container_type` only allowed Instance but not Tuple of Instances
which was mostly an oversight, as opposed to an intentional omission.
For #9427
=> checkexpr: speedup typechecking of container literals with tuple entries

mypy/semanal.py, test-data/unit/check-classes.test
Fixes #12474 
Fix INTERNAL_ERROR when using a decorated function within class scope.
Add unit test
Run unit tests
=> Fix crash when using decorator in class scope

mypy/main.py, test-data/unit/cmdline.test
This fixes an issue with the `enable-incomplete-features` flag if the compiled version of mypy is used.
Since the default is a `bool` and no type cast is specified, any string argument will result in a TypeError.
```
mypy --enable-incomplete-features True
```
```
File "/.../bin/mypy", line 8, in <module>
sys.exit(console_entry())
File "/.../lib/python3.10/site-packages/mypy/__main__.py", line 12, in console_entry
main(None, sys.stdout, sys.stderr)
File "mypy/main.py", line 70, in main
File "mypy/main.py", line 945, in process_options
File "/.../3.10/lib/python3.10/argparse.py", line 1825, in parse_args
args, argv = self.parse_known_args(args, namespace)
File "/.../3.10/lib/python3.10/argparse.py", line 1858, in parse_known_args
namespace, args = …
```
=> Fix TypeError with hidden enable-incomplete-features flag

mypy/typeanal.py
Adds a more precise error message for a `Callable` annotation, if the
option `--disallow-any-generics` (part of `--strict` mode) has been used. The suggestion in the old
message was incorrect in this scenario.
Fixes #11757
Contents of test.py:
```python
from typing import Callable
def my_function(callback: Callable[...]) -> None:
callback()
```
Results:
```bash
$ mypy test.py --disallow-any-generics
test.py:3: error: Please use "Callable[[<parameters>], <return type>]" or "Callable[..., Any]"
$ mypy test.py
test.py:3: error: Please use "Callable[[<parameters>], <return type>]" or "Callable"
```
=> Add more precise error message for Callable annotation

mypy/types.py, test-data/unit/check-typeddict.test
Trying to hash an instance of `mypy.types.CallableType` will crash if `self.fallback.type` is a `FakeInfo`. Apparently this is the case if the `CallableType` represents a classmethod alternative constructor on a `TypedDict`. Such alternative-constructor methods aren't currently supported by mypy, but mypy also shouldn't crash if it comes across them.
Fixes #5653 (though I'm not 100% sure if this is the best solution).
Test case added to `check-typeddict.test`.
=> Ensure instances of `CallableType` can always be hashed

mypy/semanal.py, test-data/unit/check-final.test
This fixes https://github.com/python/mypy/issues/12164.
When an abstract method is tried to make as `final`, an error will be raised.
Added a simple test case to make sure mypy doesn't raise an exception.
=> Add error when making abstractmethod final

mypy/checkpattern.py, test-data/unit/check-python310.test
Changes behaviour of `PatternChecker`, so that dotted names do not cover the entire type.
Since dotted names match only one value of the type, the returned `rest_type` should also contain the type of the value.
Fixes: #12545
Included code similar to the one from the issue, modified into one file.
=> Make ValuePattern non-exhaustive

mypy/plugin.py, mypy/plugins/dataclasses.py, mypy/plugins/default.py, mypy/semanal.py, mypy/semanal_main.py, test-data/unit/check-dataclasses.test
The dataclass plugin could crash if it encountered a placeholder. Fix the issue by
running the plugin after the main semantic analysis pass, when all placeholders have 
been resolved.
Also add a new hook called `get_class_decorator_hook_2` that is used by the
dataclass plugin.
We may want to do a similar change to the attrs plugin, but let's change one thing
at a time.
Fix #12685.
=> Running dataclass transform in a later pass to fix crashes

mypy/build.py, mypy/checker.py, mypy/checkexpr.py, mypy/checkstrformat.py, mypyc/test-data/run-functions.test, test-data/unit/typexport-basic.test
Previously we could export an invalid type for a lambda passed to an
overloaded function. We find the matching overload variant by type checking
the arguments against all overload items. We exported types for lambdas 
always from the final potential overload item, even if that wasn't the matching 
one. This could result in mypyc adding invalid type coercions that could result in
bogus TypeErrors.
The fix is to store types inferred when looking for matching overload items
into temporary type maps, and only the type map from the matching item
gets merged into the exported types.
This doesn't fully solve the problem -- if there are `Any` types in the
arguments, we can still export invalid types. This should be enough to 
unblock syncing typeshed (#12766). Typeshed started triggering the …
=> [mypyc] Fix TypeError in lambda argument to overloaded function

mypy/plugins/attrs.py, mypy/plugins/default.py, test-data/unit/check-attr.test, test-data/unit/fixtures/dict.pyi
Move the attrs plugin to a later pass, so that we won't have placeholders. Fix
various issues related to forward references and generic inheritance, including 
some crashes.
This is follow-up to #12762 and related to #12656 and #12633.
=> Fix forward references and generic inheritance in attrs classes

test-data/unit/check-dataclasses.test
Closes #6217. This crash seems to have been fixed a while ago (I [can't reproduce on mypy 0.720+](https://mypy-play.net/?mypy=0.720&python=3.10&gist=324738b3c7b491e47ad2a95521c5688d)), but it doesn't seem like a regression test was ever added.
=> Add test case for fixed dataclass-classmethod crash

test-data/unit/check-dataclasses.test
Adds a test case for a crash that was fixed by https://github.com/python/mypy/pull/12762. Closes #12527.
=> Add test case for fixed generic-dataclass crash

test-data/unit/check-dataclasses.test
This test case covers a recent change in functionality:
if an attribute is defined as an InitVar, it can't be
assigned to. Previously this was supported (probably
by accident).
=> Add dataclass InitVar test case

mypy/semanal.py, mypy/semanal_namedtuple.py, test-data/unit/check-incremental.test
Make sure the fullname of a named tuple defined within a method matches 
the nesting of the definition in the symbol table. Otherwise we'll have a
crash during deserialization.
In particular, a named tuple defined within a method will now be always 
stored in the symbol table of the surrounding class, instead of the global 
symbol table. Previously there was an inconsistency between old-style 
and new-style syntax.
Fix #10913.
=> Fix nested namedtuple crash in incremental mode

mypy/semanal_namedtuple.py, test-data/unit/check-incremental.test, test-data/unit/check-namedtuple.test
=> Fix namedtuple crash in unannotated function

mypy/modulefinder.py
When an invalid python executable is passed to mypy, show an error message instead of crashing with a `FileNotFoundError` or some other exception.
The implementation of the error raises a `CompileError` instead of using the normal error handling from `mypy.errors.Errors`, similar to what we do for nonexistent files being passed to mypy:
https://github.com/python/mypy/blob/8e7e81759d3e43199bb0dced94f55157b72b2a49/mypy/build.py#L2058-L2061
I used that approach because the relevant code didn't have access to an `Errors` instance and there probably isn't much reason to support continuing to check code when the `python_executable` is incorrect.
I couldn't reproduce the crash in the test suite (I'm guessing that's because we don't try looking for site-packages in the test suite, but I haven't …
=> Avoid crashing on invalid python executables

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
Fixes #12544.
At the moment, mypy crashes on the following code:
```python
from dataclasses import dataclass
from typing_extensions import TypeAlias
class Foo: ...
@dataclass
class A:
S: TypeAlias = Foo
```
This is because mypy's `dataclasses` plugin does not currently account for the possibility of a `TypeAlias` node being inside a dataclass definition.
At runtime, [no special treatment is given](https://github.com/python/cpython/issues/91322) to fields annotated with `TypeAlias` -- they're treated just like normal instance fields with default values. As such, this PR proposes that mypy:
1. Always emits an error on encountering a `TypeAlias` node inside a dataclass definition (it probably won't have the behaviour the user expects).
2. Infers the type of the field as `type[X]` in simple …
=> Fix crash on type alias definition inside dataclass declaration

mypy/checkexpr.py, mypy/typeops.py
Deeply nested if/else expressions have a worst-case exponential behavior.
This will for instance manifest when returning literal values which cause
repeated analysis of conditional branches with subtly different type context
for each literal.
This can be optimized by observing that a simple literal context will yield
the same analysis as its fallback type, and likewise, two literals of the
same fallback type will yield the same analysis. In those case we can avoid
the repeated analysis and prevent the worst-case exponential behavior.
Fixes #9591
=> speedup typechecking of nested if expressions

mypy/checker.py, mypy/checkexpr.py
When a container (list, set, tuple, or dict) literal expression is
used as an argument to an overloaded function it will get repeatedly
typechecked. This becomes particularly problematic when the expression
is somewhat large, as seen in #9427
To avoid repeated work, add a new field in the relevant AST nodes to
cache the resolved type of the expression. Right now the cache is
only used in the fast path, although it could conceivably be leveraged
for the slow path as well in a follow-up commit.
To further reduce duplicate work, when the fast-path doesn't work, we
use the cache to make a note of that, to avoid repeatedly attempting to
take the fast path.
For #9427
=> checkexpr: cache type of container literals when possible

docs/source/command_line.rst, docs/source/running_mypy.rst, mypy/build.py, mypy/main.py, mypy/modulefinder.py, mypy/options.py, mypy/test/testcheck.py, test-data/unit/check-modules-fast.test
Given a large codebase with folder hierarchy of the form
```
foo/
company/
__init__.py
foo/
bar/
company/
__init__.py
bar/
baz/
company/
__init__.py
baz/
...
```
with >100 toplevel folders, the time spent in `load_graph`
is dominated by `find_module` because this operation is
itself `O(n)` where `n` is the number of input files, which
ends up being `O(n**2)` because it is called for every import
statement in the codebase and the way find_module work,
it will always scan through each and every one of those
toplevel directories for each and every import statement
of `company.*`
Introduce a fast path that leverages the fact that for
imports within the code being typechecked, we already
have a mapping of module import path to file path in
`BuildSourceSet`
In a real-world codebase with ~13k …
=> FindModuleCache: optionally leverage BuildSourceSet

mypy/messages.py, test-data/unit/check-varargs.test
"Fixes #12508"
We fix the issue within message.py so that it will check the incoming context and produce a different error when encountering variadic arguments. We also modified the tests accordingly. Now, it passes all the tests.
=> fix: 12508 change `invalid_var_arg` error wording

.github/workflows/test.yml, test-requirements.txt
(Note that we mark these as success)
=> Run Python 3.11 tests in CI

mypyc/test/test_run.py
We don't support running on Python 3.5 or lower anymore, so the `max` call is unnecessary because the current version will always be greater than or equal to 3.6.
This seems minor enough to rely on the current CI passing.
=> Remove unnecessary `max` call for python version in test_run.py

test-data/unit/pythoneval-asyncio.test
Helps with Python 3.11 support
=> Use async def in pythoneval tests

mypyc/irbuild/ast_helpers.py, mypyc/irbuild/builder.py, mypyc/irbuild/expression.py, mypyc/irbuild/ll_builder.py, mypyc/irbuild/statement.py, mypyc/irbuild/targets.py, mypyc/lib-rt/CPy.h, mypyc/lib-rt/int_ops.c, mypyc/lib-rt/list_ops.c, mypyc/primitives/list_ops.py, mypyc/test-data/exceptions.test, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-classes.test, mypyc/test-data/irbuild-generics.test, mypyc/test-data/irbuild-lists.test, mypyc/test-data/refcount.test, mypyc/test-data/run-lists.test
Borrow operands of tagged integer operations to reduce the number of
incref/decref operations (when it's safe to do so).
Borrow the results in list get item operations, similar to what we've been
doing with get attribute operations.
=> [mypyc] Borrow even more things

mypyc/lib-rt/exc_ops.c, mypyc/lib-rt/misc_ops.c
Closes https://github.com/mypyc/mypyc/issues/931
Closes https://github.com/mypyc/mypyc/issues/923
Related CPython modification:
https://github.com/python/cpython/issues/89874
https://github.com/python/cpython/pull/31530
=> [mypyc] Fix Python 3.11 C API errors

mypyc/lib-rt/exc_ops.c, mypyc/lib-rt/misc_ops.c, mypyc/lib-rt/pythonsupport.h
Use `PyObject_CallNoArgs` and `PyObject_CallOneArg` to replace `PyObject_CallFunctionObjArgs` in `lib-rt`, since the new API costs less memory according to https://github.com/python/cpython/pull/13890#issuecomment-502563443
Also remove the macro in `pythonsupport.h` since the two API are already covered by `pythoncapi_compat.h`.
=> [mypyc] Use PyObject_CallNoArgs and PyObject_CallOneArg instead of PyObject_CallFunctionObjArgs

mypy/checkexpr.py, test-data/unit/pythoneval-asyncio.test
=> Disallow assignments to awaited coroutines that do not return

mypy/test/data.py, mypyc/test/test_run.py
Add a `--mypyc-debug` option to pytest that compiles a test normally and then runs the resulting binary in the debugger specified.
The support for debugging runtests was already there previously, so this PR just cleans it up and adds a pytest option to use it.
I ran a mypyc test using various combinations of `--mypyc-debug` and `-s` and everything seemed to work fine.
=> Add better support for debugging mypyc runtests

mypy/stubtest.py, mypy/test/teststubtest.py
=> stubtest: check typevar and paramspec

mypy/semanal.py, test-data/unit/check-attr.test
=> Fix crash with nested attrs class

mypyc/irbuild/expression.py, mypyc/test-data/irbuild-int.test, mypyc/test-data/run-integers.test
In a microbenchmark right shift was a bit faster.
=> [mypyc] Replace integer floor division by a power of two with a shift

.gitignore, mypy/test/config.py, mypy/test/testpep561.py, runtests.py, test-requirements.txt
Fixes #12615
As discussed in the linked issue, this  PR would put a filesystem-based lock around the pip install steps of the suite of PEP561 testcases, to address race conditions.
It introduces a test-dependency on tox-dev/py-filelock. I used 3.0.0 as a lower bound, simply because that's what the tox version mentioned in tox.ini specifies as its lower bound. However from the release history it seems that Python 3.6 support was dropped in 3.4.2, hence the second line in the requirements.
I ended up just adding the location of the lock file to .gitignore -- I guess it would be possible to try and remove it after the suite has run, e.g. with atexit.register, but I didn't want to make this complicated.
No new tests, just moved the PEP561 suite from "slow" to "slower" in `runtests.py`.
=> Put filelock around PEP 561 tests (fixes #12615)

mypy/messages.py, mypy/stubtest.py, mypy/test/teststubtest.py, mypy/util.py
- error summary
- fix issue where module is presented as a stub
- handle loading modules that output or raise `BaseException`
- output formatted messages instead of tracebacks
- add some more tests
Also:
- move plural_s from messages to util
- use plural_s in summary functions
I added some tests
resolves #12547
=> stubtest: add error summary, other output nits

mypy/stubtest.py, mypy/test/teststubtest.py
=> stubtest: do not treat py files as source for mypy definitions

mypy/stubtest.py, mypy/test/teststubtest.py
=> stubtest: revert to allow mixed stubs and inline types, add test

CONTRIBUTING.md
=> `CONTRIBUTING.md`: improve docs for running tests (especially on Windows)

runtests.py
Fixes #12879
Make the PEP561 test suite optional.
`./runtests.py` will skip the PEP561 suite, whereas `./runtests.py pytest-extra` will run only that suite.
=> Make PEP561 tests opt-in (fix #12879)

.github/workflows/docs.yml, docs/source/command_line.rst
There is a minor block formatting error in `docs/source/command_line.rst`, as committed in https://github.com/python/mypy/commit/a6166b2f7e8e4cf9d176107277da223e45c3a6a1:
https://github.com/python/mypy/blob/2051024c07cd361352e081884db0a061221a9aab/docs/source/command_line.rst#L217-L236
I noticed this during a local tox build, and then wondered why this wasn't flagged in CI.
It turns out that the `docs` github workflow wants to run the build on Python 3.10, as of commit https://github.com/python/mypy/commit/fec532028dcb7def7af4356e529fffb38c4afcea:
https://github.com/python/mypy/blob/2051024c07cd361352e081884db0a061221a9aab/.github/workflows/docs.yml#L19-L25
This fails, however, because `tox.ini` specifies Python 3.7 for the `docs` build: …
=> Fix formatting error in command_line.rst as well as docs CI

mypy/semanal_main.py, test-data/unit/check-dataclasses.test, test-data/unit/fine-grained.test
The plugin may add attributes that are needed to perform the bound
check.
Fixes #12876.
=> Run dataclass plugin before checking type var bounds

test-data/unit/stubgen.test
asyncio.coroutine has been removed. I don't think this test case is
particularly useful.
Linking #12840
=> Remove failing test on Python 3.11

mypy/checkexpr.py, mypy/traverser.py, test-data/unit/check-async-await.test
Fixes https://github.com/python/mypy/issues/12924 by using a traverser to find `await` expressions within a generator and then treat it as async if it is found.
A test is added. The test fails without this patch because the function has type `Generator` inferred, not `AsyncGenerator`.
=> Treat generators with await as async.

mypy/constraints.py, test-data/unit/check-parameter-specification.test
Fixes #12930.
Currently, mypy erroneously emits two errors on this snippet:
```python
from typing_extensions import ParamSpec
from typing import Callable, TypeVar, Iterator, Iterable, Tuple
P = ParamSpec("P")
def enumerate(x: Iterable[T]) -> Iterator[Tuple[int, T]]: ...
def foo(func: Callable[P, T]) -> Callable[P, T]:
def _inner(*args: P.args, **kwargs: P.kwargs) -> T:
y = enumerate(args)  # E: Need type annotation for "y"  # E: Argument 1 to "enumerate" has incompatible type "P.args"; expected "Iterable[<nothing>]"
return func(*args, **kwargs)
return _inner
```
This is because of a bug in `constraints.py`: `ParamSpecArgs` and `ParamSpecKwargs` have upper bounds following #12668 (`tuple[object, ...]` and `dict[str, object]` respectively), but the constraints solver isn't …
=> Fix bug in constraints solver regarding `ParamSpec` upper bounds

README.md, docs/source/conf.py, docs/source/mypy_light.svg
The mypy logo wasn't loading on https://mypy.readthedocs.io/ because
it's referenced via an http:// (not https) URL. The logo's URL is
http://mypy-lang.org/static/mypy_light.svg; that server is not
accessible via https, so I've moved mypy_light.svg into docs/source and
referenced it from there.
The project README also referenced the logo via the same URL, so for
consistency, the README now points at the same logo file in docs/source.
(Although the README's logo did load because GitHub proxies external
resources referenced in markdown files).
I've rebuilt the HTML docs after this change, and verified the HTML correctly references the logo file via a relative path. So it should load correctly on readthedocs, as the logo will be available via https from their server, alongside the HTML.
=> Fix sidebar logo not loading in HTML docs

mypy/checker.py, test-data/unit/check-final.test
Fixes #12950.
Mypy currently crashes on this snippet of code:
```python
from typing import Final
class MyClass:
a: None
a: Final[int] = 1
```
This PR fixes that.
I added a test.
=> Fix crash on redefined class variable annotated with `Final[<type>]`

mypy/meet.py, test-data/unit/check-overloading.test
Fixes #12922 (a crash report).
Mypy's logic for overlapping overloads currently doesn't account for the existence of `ParamSpec`s. This PR fixes that.
I added a test that ensures that the crash report in #12922 is fixed, and that ensures that basic type inference works as expected.
I'm not 100% confident I've covered all edge cases, but I think this is better than the status quo, anyway.
=> Improve handling of overloads with `ParamSpec`

test-requirements.txt
This is the version of filelock that includes py.typed
=> Raise minimum filelock version

mypy/constraints.py, mypy/expandtype.py, mypy/type_visitor.py, mypy/typeops.py, test-data/unit/check-typevar-tuple.test
The main substance here modifies `mypy/constraints.py` to not assume that
template.items has length 1 in the case that there is an unpack. We
instead assume that that there is only a singular unpack, and do a
former pass to find what index it is in, and then resolve the unpack to
the corresponding subset of whatever tuple we are matching against.
=> Support inferring Unpack mixed with other items

mypyc/analysis/dataflow.py, mypyc/analysis/ircheck.py, mypyc/analysis/selfleaks.py, mypyc/codegen/emit.py, mypyc/codegen/emitfunc.py, mypyc/ir/ops.py, mypyc/ir/pprint.py, mypyc/ir/rtypes.py, mypyc/irbuild/ll_builder.py, mypyc/subtype.py, mypyc/test/test_emitfunc.py, mypyc/test/test_subtype.py, mypyc/transform/exceptions.py
Some IR and codegen changes that help with native int support.
This was split off from a branch with a working implementation of
native ints to make reviewing easier. Some tests and primitives 
are missing here and I will include them in follow-up PRs.
Summary of major changes below.
1) Allow ambiguous error returns from functions. Since all values
of `i64` values are valid return values, none can be reserved for 
errors. The approach here is to have the error value overlap a 
valid value, and use `PyErr_Occurred()` as a secondary check 
to make sure it actually was an error.
2) Add `Extend` op which extends a value to a larger integer
type with either zero or sign extension.
3) Improve subtype checking with native int types.
4) Fill in other minor gaps in IR and codegen support for …
=> [mypyc] Foundational work to help support native ints

mypyc/lib-rt/CPy.h, mypyc/lib-rt/int_ops.c, mypyc/lib-rt/list_ops.c, mypyc/lib-rt/mypyc_util.h, mypyc/primitives/int_ops.py, mypyc/primitives/list_ops.py
Add various C primitives that will be used to support native ints. 
The primitives aren't used for anything yet. I'll prepare follow-up PRs 
that use the primitives and include tests. I'm splitting these into a 
separate PR to make this easier to review. All of these are tested in 
my local branch, at least to a basic level.
Most of these are fairly straightforward, but we need to jump through
some hoops to make the semantics of // and % operators compatible
with Python semantics when using negative operands.
Work on https://github.com/mypyc/mypyc/issues/837.
=> [mypyc] Native int primitives

mypy/semanal.py, test-data/unit/check-modules.test
Fixes #12689
We always hid e.g. `import concurrent`, but looks like mypy
never hid `from concurrent import futures`. It's possible this fix is
pretty breaking for users, let's see what primer thinks.
I last touched this logic in #11707, which fixed cases involving
implicitly reexported symbols that shared the name of a module
=> Disallow undesirable implicit reexport with ImportFrom

mypy/checker.py, test-data/unit/check-classes.test
Fixes #5425.
Typechecking for method overrides ended in an `assert False` for any AST nodes other than `FuncDef`, `OverloadedFuncDef`, `Decorator`, and `Var`. This PR replaces this with a typecheck error for any unrecognized AST nodes instead.
Added a new test case to `check-classes.test` covering the original bug report from the example, as well as some [extra cases that Jukka mentioned](https://github.com/python/mypy/issues/5425#issuecomment-423993232) in the comments.
=> Replace hard crash with typecheck error when subclass method has the same name as type alias

mypy/fastparse.py, mypy/fastparse2.py, mypy/nodes.py
Closes #12940
The AST nodes from python versions greater than 3.7 provide the `end_col_offset` attribute. This attribute can be used to solve some issues in mypy.
https://github.com/python/mypy/issues/12288
https://github.com/python/mypy/issues/4868
https://github.com/python/mypy/issues/12513
The AST nodes will have an optional[int] type for `end_col_offset` attributre. 
For python<3.8 this attribute will be None, following the approach already been used in mypy
https://github.com/python/mypy/blob/9ccd081550010700341a46f0e08b8954e5beef70/mypy/fastparse.py#L375
Currently, the `end_line` attribute is not being tested in mypy so I believe there is no reason to create a test for `end_col_offset`.
=> Exposes `end_col_offset` attr from python AST

mypy/nodes.py, mypy/types.py
Remove redefining base class slots.
`nodes.TypeAlias.line` slot is defined in `nodes.Context`
`nodes.TypeAlias.column` slot is defined in `nodes.Context`
`nodes.PlaceholderNode.line` slot is defined in `nodes.Context`
`types.TypeAliasType.line` slot is defined in `nodes.Context`
`types.TypeAliasType.column` slot is defined in `nodes.Context`
`types.Overloaded.fallback` slot is defined in `types.FunctionLike`
No additional tests required.
=> Remove slots already defined in base class

mypy/checker.py, test-data/unit/check-enum.test
Fixes #12787.
Mypy currently emits a false-positive error for this snippet of code, even though it works fine at runtime (and this exact inheritance structure is used in `enum.py` in the stdlib):
```python
from enum import Enum, Flag
class ReprEnum(Enum): ...
class MyFlag(ReprEnum, Flag): ...
```
This PR fixes that.
I added several tests to make sure the behaviour is correct here.
=> Fix false-positive error on multiple enum base classes

mypy/plugins/dataclasses.py, mypy/semanal_namedtuple.py, mypy/test/testmerge.py, test-data/unit/check-dataclasses.test, test-data/unit/check-namedtuple.test, test-data/unit/deps.test, test-data/unit/merge.test
This PR removes autogeneration of `__match_args__` attribute for dataclasses and named tuples when running with `--python-version` set to < 3.10
Fixes #12489
=> Do not generate `__match_args__` when running with `--python-version` < 3.10

mypy/checker.py, test-data/unit/check-classes.test
Attributes can still be partially typed (e.g. `<partial list[?]>`) after
a parent-class definition if the block they are declared in is deferred.
The first pass for child classes might then encounter this type when
considering method overrides, which could cause a crash when attempting
to determine subtype compatibility.
This patch causes the subtype checker to defer the override test if the original type is still partial, avoiding the crash.  The correct error messages are still reported after this.  This is the same approach as suggested by https://github.com/python/mypy/issues/11686#issuecomment-989115227, but the test case is different to the original issue.  The original reproducer involved `@property`, which runs afoul of #4125, and a full fix there is likely better part of #7724. …
=> Fix crash overriding partial-type attribute with method

mypy/stubgen.py
Modify signature of `stubgen.main` to accept a user-provided list of arguments. This allows users to supply their own argument list without monkeying about with `sys.argv`, which improves the usefulness of embedding `stubgen` into other projects.
=> Allow passing arguments to stubgen.main

mypyc/primitives/float_ops.py, mypyc/primitives/tuple_ops.py, mypyc/test-data/irbuild-dunders.test, mypyc/test-data/run-python37.test, mypyc/test-data/run-tuples.test
- Fixes https://github.com/mypyc/mypyc/issues/924
- Fixes https://github.com/mypyc/mypyc/issues/926
- Fixes https://github.com/mypyc/mypyc/issues/935
This is a follow-up of commit 7811f085d0081d48302237faa20254c0fc3eb43a.
I took all of the downgraded / failing examples in the linked issues and rewrote them as run tests.
=> [mypyc] Add LoadAddress op for PyFloat_Type & PyTuple_Type

mypy/moduleinspect.py
Some packages may take a very long time to import, which can spuriously trip the timeout in `ModuleInspect`. To make this less likely, increase the timeout from 5s to 30s.
I could use some help with how to write an appropriate test, as it doesn't seem to obviously match any existing tests (somewhat pep561.test though it's unclear how that handles the test package). I think the general idea is to write a test that simply tries to inspect a test package whose `__init__.py` looks like:
```python
import time
time.sleep(7)
```
This works to reproduce the failure by attempting to run `stubgen` on the above.
An example of this failure occurring "in the wild" can be seen [here](https://drake-cdash.csail.mit.edu/test/776657767).
=> Increase get_package_properties timeout

misc/build_wheel.py
See https://github.com/mypyc/mypy_mypyc-wheels/pull/35 for motivation
We also need fewer lxml workarounds, since #12813 skips lxml tests
if needed
This is a bit of a pain to test since the script was moved into the
mypy repo from the wheels repo
=> Skip musllinux wheels, update for lxml changes

docs/source/protocols.rst
The documentation is not referring to keyword arguments, but to arguments in general.
Fixes #8805.
=> protocols.rst: fix documentation

tox.ini
This PR removes the py35 test environment from tox and adds py38, 39 and 310 environments.
It also sets the basepython required for the following env below to 3.10
- [testenv:lint]
- [testenv:type]
- [testenv:docs]
=> update tox, add py38,39,310 remove py35

misc/trigger_wheel_build.sh
With depth=1 only the last commit is retrieved hence the command takes less time to clone the repository.
Reference
1. https://git-scm.com/docs/git-clone
=> add depth parameter to git clone command

mypyc/irbuild/statement.py, mypyc/test-data/run-generators.test
This PR makes mypyc flush keepalives on operator assignment statements, to prevent accessing undefined variables in the generated C code.
Fixes mypyc/mypyc#941.
=> [mypyc] flush keepalives on operator assignment statements

mypyc/irbuild/statement.py, mypyc/test-data/run-generators.test
We need to flush keep alives also after a multiple assignment, as otherwise
the generated IR will be badly formed and confuse the reference count transform.
Fixes mypyc/mypyc#942.
=> [mypyc] Fix bad C generated for multiple assignment

mypyc/irbuild/statement.py, mypyc/test-data/run-generators.test
Backport of https://github.com/python/mypy/pull/13144
=> [0.970 backport] flush keepalives on operator assignment statements

.github/workflows/test.yml, mypy/defaults.py, test-data/unit/check-incremental.test, test-data/unit/fine-grained-cache-incremental.test, test-data/unit/fine-grained-modules.test, test-data/unit/pythoneval.test
This is work on dropping support for Python 3.6. 
Typeshed already dropped 3.6 support: https://github.com/python/typeshed/pull/8269
DO NOT MERGE YET! Let's wait until 0.970 is out.
=> Use Python 3.7 as default in tests, drop 3.6 in CI

mypyc/codegen/emitclass.py, mypyc/test/test_emitclass.py
Fixes https://github.com/mypyc/mypyc/issues/933 by preventing the conflicting `set(up)` name. `getter_name` has also been changed for consistency sake.
Test cases added to `test_emitclass.py`
=> [mypyc] Fix `setup` conflict when setting an attribute with name `up`

mypy/constraints.py, mypy/stubgenc.py, mypy/test/testcheck.py, mypyc/codegen/literals.py
Small refactors to simplify the codebase.
* use constructor call to avoid loops
* use comprehension in simple cases
=> refactor: use constuctor call or comprehensions instead of loops

mypy/pyinfo.py
This fixes a recent regression introduced by the change to
use sys.path
Fixes #12956
=> Handle cwd correctly in pyinfo

mypy/typeanal.py, test-data/unit/check-python310.test, test-data/unit/lib-stub/types.pyi
Fixes #11288
Warns people to not use `NoneType` as a type annotation, as requested in #11288.
**Before**
```python
from types import NoneType
def f(x: NoneType) -> None:
pass
f(None) # E: Argument 1 to "f" has incompatible type "None"; expected "NoneType"
```
**After**
```python
from types import NoneType
def f(x: NoneType) -> None: # E: NoneType should not be used as a type, please use None instead 
pass
f(None)
```
Had to edit `test-data/unit/lib-stub/types.pyi` to allow NoneType type annotation.
=> Treating NoneType as None and warning against using NoneType.

mypyc/codegen/emitclass.py, mypyc/test-data/run-classes.test
Fixes #12605 
Fixes https://github.com/mypyc/mypyc/issues/925
=> [mypyc] Fix __call__ subclasses

mypy/pyinfo.py
=> [0.970 backport] Handle cwd correctly in pyinfo

mypy/typeops.py, test-data/unit/check-unions.test, test-data/unit/fixtures/isinstancelist.pyi
After this change, narrowing to `Ellipsis` works similarly with
regards to narrowing as `None` in `Optional`s
It would be a good followup refactor to delegate some of the logic
from `is_singleton_type` to the actual mypy types so they could decide
for themselves if they are representing singleton objects
Fixes: #13117
Co-authored-by: Zsolt Cserna <cserna.zsolt@gmail.com>
=> Union types: Support narrowing to `Ellipsis` (`...`) cases of `Unions`

mypy/test/helpers.py, mypy/test/testcheck.py, mypy/test/testdeps.py, mypy/test/testfinegrained.py, mypy/test/testparse.py, mypy/test/testsemanal.py, mypy/test/testtransform.py, test-data/unit/README.md
This PR hopefully resolves https://github.com/python/mypy/issues/8650.
The main change is the `find_test_files ` helper function that looks for files matching the pattern in the unit tests directory. It has been used in the following test files for autodiscovery:
-  `testcheck.py`
-  `testdeps.py`
- ` testfinegrained.py`
- `testparse.py`
- `testsemanal.py`
I've also updated the readme. 
This is a question for maintainers - does this helper function needs unit tests and if so, where should they live? I haven't found `testhelpers.py` 🙂
=> Tests autodiscovery replacing hardcoded file list

mypy/typeops.py, mypy/types.py
This greatly reduces complexity as each type can determine for
themselves if they are representing a singleton.
`get_enum_values` has to be moved as well, as it is used by
`get_singleton_type`.
Relates-to: #13117
=> `is_singleton_type`: move business logic to type definitions

mypy/stubtest.py
=> stubtest: catch all for errors from the runtime

.github/workflows/docs.yml, .github/workflows/test.yml, mypy/test/testpep561.py, mypyc/README.md, mypyc/test-data/run-imports.test, test-data/unit/pep561.test, test-requirements.txt
=> Drop need for virtualenv

.github/workflows/docs.yml, .github/workflows/test.yml, mypyc/codegen/emitclass.py, tox.ini
:trollface: 
This change will mean that `tox -e type` will use your current interpreter instead of 3.7, this could be good or bad depending on how you look at it.
Also added an override in CI to not skip missing interpreters.
=> (🐞) Fix CI python interpreter

mypy/pyinfo.py
We run mypy/pyinfo.py as a script, and this means that mypy/types.py
could be picked up instead of the stdlib `types` module, which clearly
doesn't work. This seems to happen at least on macOS, and it broke
PEP 561 tests.
The workaround was accidentally removed as part of #13161.
This should fix #13174 and help with the wheel builds.
=> Add back workaround to avoid confusing mypy.types and types in pyinfo

mypy/nodes.py, mypy/semanal.py, mypy/semanal_namedtuple.py, mypy/subtypes.py, mypy/types.py, test-data/unit/check-class-namedtuple.test, test-data/unit/lib-stub/typing_extensions.pyi
This PR adds basic support for `typing_extensions.NamedTuple`, added to the `typing_extensions` runtime in https://github.com/python/typing_extensions/commit/7c28357e412cef215a7d66c0ef69b568b316678b and added to the typeshed stub in https://github.com/python/typeshed/commit/10f3238998737fa7c73a1005b61b5c717cc9c429.
This PR doesn't add support for _generic_ `NamedTuple`s: that'll have to come later. For now, it just teaches mypy that `typing_extensions.NamedTuple` should be treated much the same as `typing.NamedTuple` in nearly all circumstances.
I haven't cherry-picked the typeshed change in this PR (which was cherry-picked to the `0.970` branch in #13149, but doesn't exist on `master` yet). It turned out I didn't need to do the cherry-pick in order for the tests to pass. I'm happy to do …
=> Basic support for `typing_extensions.NamedTuple`

mypy/test/helpers.py
Use `mypy.test.config.test_data_prefix` instead of hard coding it. This
should fix mypy wheel builds.
Fixes #13189 (hopefully).
=> Fix checker test case collection by using correct test data prefix

mypy/stubtest.py, mypy/test/teststubtest.py
=> stubtest: fix false-positive error for Protocol `__init__`s and Protocol `__annotations__`

mypy/build.py, test-data/unit/check-errorcodes.test, test-data/unit/check-modules.test, test-data/unit/cmdline.test, test-data/unit/fine-grained-follow-imports.test, test-data/unit/pep561.test, test-data/unit/semanal-errors.test
Fixes #13085. Hopefully more robust than previous fixes along these lines.
=> Fix caching of PEP 561 namespace packages

mypy/subtypes.py, test-data/unit/check-protocols.test
Previously we had a special case for `None` and `__hash__`, but it can be extened for `__str__` as well.
```python
>>> str(None)
'None'
```
In the future we can change all our `None` hacks to use `NoneType`, but not today :)
Closes #13081
=> Make `None` compatible with `SupportsStr` protocol

mypy/constraints.py, mypy/test/testconstraints.py
This adds some basic constraints tests with the intent of adding more complex ones for variadic generics later.
=> Implement basic constraints unit tests.

README.md
Use the available [`zipball`](https://docs.github.com/en/rest/repos/contents#download-a-repository-archive-zip) option for the latest installation to prevent issues when a user might not have `git` present on the system or if the installation of `git` isn't an option e.g. by having size restrictions in the environment such as Docker image.
```
$ docker run -it python:alpine sh
/ # pip install -U pip
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.0)
Collecting pip
Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
|████████████████████████████████| 2.1 MB 8.4 MB/s 
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 21.0
Uninstalling pip-21.0:
Successfully uninstalled pip-21.0
Successfully installed pip-22.1.2
/ # …
```
=> Use GitHub's zipball as alternative to 'git+https'

mypy/main.py, mypy/modulefinder.py, mypy/pyinfo.py
This was a regression in 0.971
Fixes #13214
=> Fix site package on MYPYPATH check

mypy/subtypes.py, mypy/test/testsubtypes.py
This implements a few more tests and cases for the subtype checks for variadic generics in testsubtypes.py.
=> Implement more cases for typevartuple subtyping.

mypy/checker.py, mypy/fastparse2.py, mypy/nodes.py
After #13135 is merged, I think it is safe to say that we can now remove all python2-specific artifacts.
This is one of them. 
Originally introduced in https://github.com/python/mypy/pull/11289
=> Remove python2 specific logic for `raise` keyword check

mypy/checkexpr.py, mypy/checkstrformat.py
=> Remove python2 logic from `checkstrformat.py`

.github/workflows/test.yml, mypy/defaults.py, test-data/unit/check-incremental.test, test-data/unit/fine-grained-cache-incremental.test, test-data/unit/fine-grained-modules.test, test-data/unit/pythoneval.test
Re-apply #13101 
This is needed for https://github.com/python/mypy/pull/13252
=> Use Python 3.7 as default in tests, drop 3.6 in CI (#13101)

mypy/checker.py, mypy/checkexpr.py, mypy/exprtotype.py, mypy/fastparse.py, mypy/literals.py, mypy/nodes.py, mypy/reachability.py, mypy/semanal.py, mypy/semanal_enum.py, mypy/semanal_namedtuple.py, mypy/semanal_newtype.py, mypy/semanal_typeddict.py, mypy/server/deps.py, mypy/server/subexpr.py, mypy/stats.py, mypy/strconv.py, mypy/traverser.py, mypy/treetransform.py, mypy/visitor.py, mypyc/irbuild/visitor.py
Ref #12237 
This includes `UnicodeExpr`, `BackquoteExpr`, `PrintStmt`, and `ExecStmt`.
=> Delete Python 2 specific AST nodes

docs/source/stubgen.rst, mypy/stubgen.py
=> Drop stubgen support for Python 2

test-data/unit/check-python38.test
As a result of https://github.com/python/cpython/pull/94948
we started to fail these tests on Python 3.11b5
Linking https://github.com/python/mypy/issues/12840
=> Fix several tests on Python 3.11

mypy/config_parser.py, test-data/unit/cmdline.test
=> Clean up some Python 2 configuration

mypy/checker.py, mypy/message_registry.py
=> Remove some Python 2 type checking logic

test-data/unit/check-generics.test
This is from https://github.com/python/mypy/pull/11378#discussion_r742825540
=> Add test case involving constrained generic super

mypy/exprtotype.py, mypy/literals.py, mypy/nodes.py, mypy/treetransform.py
=> Remove from_python_3 field from StrExpr

mypy/semanal_namedtuple.py, test-data/unit/check-namedtuple.test
All tests examples I added fail at runtime. This is a tiny follow up for https://github.com/python/mypy/pull/13254
cc @JelleZijlstra
=> Prohibit bytes literals in named tuples

mypy/checkstrformat.py, mypy/server/deps.py
=> Remove python2 logic from `server/deps.py`

mypy/plugins/attrs.py
=> Remove python2 logic from `plugins/attrs.py`

mypy/checkexpr.py, mypy/message_registry.py, mypy/operators.py
=> Remove Python 2 logic from checkexpr

docs/source/mypy_daemon.rst, mypy/dmypy/client.py, mypy/exprtotype.py, mypy/fastparse.py, mypy/plugins/ctypes.py, mypy/stubgen.py, mypy/suggestions.py, mypy/test/testfinegrained.py, mypy/typeanal.py, mypy/types.py
Should be merged after https://github.com/python/mypy/pull/13264 since `checkexpr` is using `unicode` as well.
=> Remove all `builtins.unicode` references

.github/workflows/test.yml
When new commit is pushed to the CI, we can cancel old jobs for this branch.
This way we can use less CI minutes. Right now some test jobs take around 30mins.
Docs: https://docs.github.com/en/actions/using-jobs/using-concurrency
=> Cancel old test jobs in CI

mypy/build.py, mypy/reachability.py
The one in `reachability.py` made me think 🤔 
I guess it is a right thing to keep `PY2` as always false.
=> Remove python2 from `build.py` and `reachability.py`

mypy/stubtest.py, mypy/test/teststubtest.py
Stubtest currently emits false-positive errors on most of the stdlib enums in typeshed, due to this behaviour:
```python
>>> from enum import Enum
>>> class Foo(Enum):
...     BAR = 1
...
>>> Foo.BAR.value
1
>>> Foo.BAR.value = 5
File "<stdin>", line 1, in <module>
File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\types.py", line 187, in __set__
raise AttributeError("can't set attribute")
AttributeError: can't set attribute
>>> Foo.value
File "<stdin>", line 1, in <module>
File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\enum.py", line 437, in __getattr__
raise AttributeError(name) from None
AttributeError: value
```
The `value` property exists on `enum` classes, but stubtest can't see it …
=> stubtest: Fallback to `getattr_static` if an attribute can't be found on a class at runtime

test-data/unit/check-newsyntax.test
Syntax error was changed in a micro version; wheel builds use 3.10.0
=> Fix tests on Python 3.10.0

mypy/stubtest.py
CC @JelleZijlstra @AlexWaygood 
Refs https://github.com/python/typeshed/pull/8443
I will examine and remove other python2-only magic methods from `typeshed` later 🙂
=> Allow stubtest to ignore python2 only magic methods

misc/build_wheel.py
This PR has a couple of goals:
1. Adding `musllinux` mypy wheels, for more users to enjoy mypyc's performance improvements.
2. Eliminating use of an old custom-built `clang` used in CI (incompatible with newer manylinux images?).
Upgrades custom clang 6.0.1 to redhat-provided 7.0.1.
3. Building `manylinux2014` wheels instead of EOL `manylinux2010`. Those users will switch to non-compiled releases.
As available llvm versions are tied to the OS release, cibuildwheel needs to be updated to v2.3+ (Which defaults to manylinux2014) to keep `yum install` working.
As for musllinux, cibuildwheel needs to be updated to v2.2+.
This PR should handle both by upgrading to the latest release, but **needs to be merged at the same time to not break builds:** …
=> Add musllinux wheel support, Use 'official' llvm build for compilation

build-requirements.txt, mypy-requirements.txt, mypy/build.py, mypy/test/testgraph.py, mypy/util.py, mypyc/build.py, test-data/unit/cmdline.test
It should work now with `custom-typeshed-dir` and `use_builtins_fixtures`.
Fixes #1876
=> Ensure builtin modules are from typeshed sooner

mypy/modulefinder.py
=> Remove Python 2 logic from modulefinder

mypy/stubtest.py
This preserves the invariant that in `--concise` the problematic objects
are the start of each line. It also matches the pattern we have for e.g.
the "explicitly passing in defaults" error message
=> stubtest: use single line error message

mypy/stubtest.py
I also considered ignoring the module level `__pyx_capi__`, but that seems less troublesome and may have potential uses. Maybe someone more familiar with Cython knows for sure
=> stubtest: ignore __pyx_vtable__

mypy/checker.py, mypy/checkexpr.py, mypy/expandtype.py, mypy/infer.py, mypy/main.py, mypy/messages.py, mypy/options.py, mypy/sametypes.py, mypy/semanal.py, mypy/solve.py, mypy/subtypes.py, mypy/typeanal.py, mypy/typeops.py, mypy/types.py, test-data/unit/check-newsemanal.test, test-data/unit/check-recursive-types.test, test-data/unit/fixtures/isinstancelist.pyi
This PR exposes recursive type aliases that were secretly there for last ~3 years. For now they will still be behind an opt-in flag, because they are not production ready.
As we discussed with @JukkaL during PyCon, I use couple hacks to make them minimally usable, as proper solutions will take time. I may clean up some of them in near future (or may not).
You can see few added test cases to get an idea of what is supported, example:
```python
Nested = Sequence[Union[T, Nested[T]]]
def flatten(seq: Nested[T]) -> List[T]:
flat: List[T] = []
for item in seq:
if isinstance(item, Sequence):
res.extend(flatten(item))
else:
res.append(item)
return flat
reveal_type(flatten([1, [2, [3]]]))  # N: Revealed type is "builtins.list[builtins.int]"
```
There are several known issues, missing features, …
=> Enable recursive type aliases behind a flag

docs/source/cheat_sheet_py3.rst, docs/source/final_attrs.rst, docs/source/generics.rst, docs/source/getting_started.rst, docs/source/kinds_of_types.rst, docs/source/literal_types.rst, docs/source/more_types.rst, docs/source/mypy_daemon.rst
Because Mypy currently requires 3.6+, this merge request begins the process of refactoring the use of various format styles such as `.format`,  with the use of f-strings. This intentionally leaves behind certain formatting examples which are being used to demonstrate errors, such as:
```
def foo(a):
return '(' + a.split() + ')'  # No error!
```
Python added f-strings in version 3.6, with [PEP 498](https://www.python.org/dev/peps/pep-0498/). F-strings are a flexible and powerful way to concatenate strings. They make the code shorter and more readable, since the code now looks more like the output. Finally, there is also a performance benefit to using f-strings, which is an additional reason to advocate for their usage in examples.
Finally, this also leverages …
=> refactor: prefer f-strings to .format in docs

mypy/stubtest.py, mypy/test/teststubtest.py
Avoid issuing duplicate errors for keyword-only mismatches.
Fixes #13305
Fix cases where PEP 570 is used in the stub
=> stubtest: improve signature checking

mypy/semanal.py, test-data/unit/check-classes.test
This is the simplest solution I found: I just expand type alias before `isinstance(type_info, Instance)`. 
I've added several tests to make sure wrong aliases are not allowed.
Should I add anything else to the test? 
Closes #13334
Refs https://github.com/python/mypy/pull/13331
=> Support type aliases in metaclasses

mypy/semanal.py, mypy/semanal_typeargs.py, mypy/typeanal.py, mypy/types.py, test-data/unit/check-recursive-types.test
This is a follow up for #13297.
See some motivation in the original PR (also in the docstrings).
cc @JukkaL
=> Fail gracefully on invalid and/or unsupported recursive type aliases

mypy/util.py
Current color is barely visible on both my Mac and on my Linux Mint desktop. The one I propose looks much better. (Also IIUC code 90 is not even in ANSI, many terminals may not implement it at all.)
=> Use a better color for gray

docs/README.md
Updates the readme for the sphinx docs which says the docs use `sphinx_rtd_theme` when they now use `furo`.
Does not affect any code. Only a documentation change in the readme for the docs folder.
Rebuild the docs [(link to instructions)](https://github.com/python/mypy/tree/1f08cf44c7ec3dc4111aaf817958f7a51018ba38/docs) and review the changed pages for markup errors. Minimal changes so errors shouldn't cascade.
=> update theme used from sphinx_rtd_them to furo

setup.py
The package advertises its typing status to typing tools via `py.typed` file.
Adding the Trove Classifier helps advertise its typing status to PyPI browsers.
Without the classifier, this package will not appear in a scoped search:
https://pypi.org/search/?q=mypy&o=&c=Typing+%3A%3A+Typed
Post-build/release/push to pypi.org, search for `mypy` when scoped to "Typing: Typed"
=> Advertise typing status via classifier

mypy/checker.py, mypy/plugins/ctypes.py, mypy/typeanal.py, mypy/types.py, test-data/unit/check-recursive-types.test, test-data/unit/check-typeguard.test
This is another fix for recursive aliases. Ref #13297 
Previously this special casing caused `Optional[...]` to fail with infinite recursion, where `Union[..., None]` worked. I also delete a duplicate helper, and replace it with another existing one that handles type aliases properly.
(I have no idea why some TypeGuard test started passing, but we have `xfail-strict` so I am re-enabling this test.)
cc @JukkaL
=> Remove Optional[...] special-casing during semantic analysis

mypy/pyinfo.py
`pyinfo.py` can no longer be called with 2.7 and 3.6, because their support is dropped.
=> Modernize `pyinfo.py` to 3.7+

mypy/nodes.py, mypy/semanal.py, mypy/semanal_typeargs.py, mypy/type_visitor.py, mypy/typeanal.py, test-data/unit/check-recursive-types.test
This is another follow up on #13297.
We can't support aliases like `Nested = Union[T, Nested[List[T]]]` (and it looks like no-one can, without hacks like fixed type recursion limit). I would propose to just ban them for now. We can reconsider if people will ask for this.
cc @JukkaL
=> Fail gracefully on diverging recursive type aliases

mypyc/build.py, mypyc/codegen/emit.py, mypyc/codegen/emitclass.py, mypyc/codegen/emitfunc.py, mypyc/codegen/emitmodule.py, mypyc/codegen/emitwrapper.py, mypyc/crash.py, mypyc/ir/class_ir.py, mypyc/ir/ops.py, mypyc/ir/rtypes.py, mypyc/irbuild/for_helpers.py, mypyc/irbuild/nonlocalcontrol.py, mypyc/irbuild/visitor.py, mypyc/primitives/int_ops.py, mypyc/primitives/registry.py, mypyc/test/test_run.py
Second part of https://github.com/python/mypy/pull/13355
=> Run `pyupgrade` on the `mypyc` source code

mypy/stubtest.py, mypy/test/teststubtest.py
=> Allow stubtest to raise errors on abstract state mismatch

mypy/checkmember.py, mypy/fixup.py, mypy/messages.py, mypy/nodes.py, mypy/semanal.py, mypy/semanal_namedtuple.py, mypy/semanal_newtype.py, mypy/semanal_shared.py, mypy/server/astmerge.py, mypy/server/aststrip.py, mypy/server/deps.py, mypy/typeanal.py, mypy/util.py, test-data/unit/check-incremental.test, test-data/unit/check-recursive-types.test, test-data/unit/fine-grained.test
This is a continuation of #13297 
The main change here is that although named tuples are still stored in symbol tables as `TypeInfo`s, when type analyzer sees them, it creates a `TypeAliasType` targeting what it would return before (a `TupleType` with a fallback to an instance of that `TypeInfo`). Although it is a significant change, IMO this is the simplest but still clean way to support recursive named tuples.
Also it is very simple to extend to TypedDicts, but I wanted to make the latter in a separate PR, to minimize the scope of changes.
It would be great if someone can take a look at this PR soon.
The most code changes are to make named tuples semantic analysis idempotent, previously they were analyzed "for real" only once, when all types were ready. It is not possible anymore if we …
=> Support recursive named tuples

mypy/types.py, test-data/unit/check-generics.test
Fixes #12678 by updating line and column not only in an alias type variable but also recursively in arguments.
The current develop output
```
python3 -m pip install numpy mypy
echo -e "import numpy.typing as npt;\na: npt.NDArray[float]" > test_ntp.py
python3 -m mypy test_ntp.py --cache-dir=/dev/null
test_ntp.py:212: error: Type argument "float" of "dtype" must be a subtype of "generic"
python3 -m mypy test_ntp.py --cache-dir=/dev/null --pretty
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/miha/.local/lib/python3.8/site-packages/mypy/__main__.py", …
```
=> Fix reporting location in aliased types.

mypyc/lib-rt/exc_ops.c, mypyc/test-data/run-classes.test
Previously this would be `attribute 'ClsName' of 'attr_name' undefined`.
Now it's `attribute 'attr_name' of 'ClsName' undefined`.
=> [mypyc] Fix AttributeError message

docs/source/generics.rst
=> docs: use ParamSpec in "Declaring decorators"

mypy/test/testconstraints.py, mypy/test/typefixture.py, mypy/types.py
This implements some constraint tests for type var tuples. We only test SUPERTYPE_OF right now because the SUBTYPE_OF path doesn't actually seem to work yet. We also have to make `TypeList` support hash and eq in order to compare the sets.
=> Implement some constraints tests for typevar tuples.

mypy/checker.py, mypy/checkexpr.py, test-data/unit/check-abstract.test
Fixes #5374 
As discussed in the issue, we should allow this common use case, although it may be technically unsafe (e.g. if one would instantiate a class in a class decorator body).
=> Allow generic decorators on abstarct classes

docs/source/class_basics.rst, mypy/checkexpr.py, mypy/checkmember.py, mypy/nodes.py, mypy/semanal.py, test-data/unit/check-classvar.test, test-data/unit/check-dataclasses.test, test-data/unit/check-functions.test, test-data/unit/check-functools.test, test-data/unit/check-incremental.test, test-data/unit/check-selftype.test, test-data/unit/check-slots.test
Fixes https://github.com/python/mypy/issues/708
Fixes https://github.com/python/mypy/issues/5485
This builds on the original proposal by @wyfo, but handles three important issues/edge cases:
* This PR fixes serialization of `is_inferred` so that the distinction works correctly in incremental mode (I added a test)
* Dunder operator methods are always considered class variables (this is a relatively common pattern and matches Python semantics; there is an existing tests that previously needed `ClassVar[...]`)
* If we detect a `Too few arguments` error for a variable with callable type we give a note suggesting to try `ClassVar[...]`
I also add a short doc paragraph on this.
cc @JukkaL
=> Fix callable instance variable support (take 2)

mypy/plugins/attrs.py, mypy/plugins/ctypes.py, mypy/plugins/dataclasses.py, mypy/plugins/enums.py, mypy/server/deps.py, mypy/test/data.py, mypy/test/testipc.py, mypyc/analysis/dataflow.py, mypyc/codegen/emit.py, mypyc/codegen/emitwrapper.py, mypyc/ir/class_ir.py, mypyc/ir/func_ir.py, mypyc/ir/module_ir.py, mypyc/ir/ops.py, mypyc/ir/rtypes.py, mypyc/irbuild/builder.py, mypyc/irbuild/context.py, mypyc/irbuild/for_helpers.py, mypyc/irbuild/nonlocalcontrol.py, mypyc/irbuild/prepare.py, mypyc/irbuild/specialize.py, mypyc/transform/refcount.py, mypyc/transform/uninit.py
With #13391 (adding `from __future__ import annotations` everywhere), it's now possible to remove the quotes from annotations. Change generated with `pyupgrade` and excluding unrelated changes.
=> Remove quotes from annotations

mypy/checker.py, mypy/semanal.py, test-data/unit/check-abstract.test, test-data/unit/check-classes.test, test-data/unit/check-functions.test, test-data/unit/check-functools.test, test-data/unit/fixtures/property.pyi, test-data/unit/semanal-errors.test
Fixes #1362
This is based on the original idea by @graingert. I delete the old cryptic error message and instead:
* Enable the situations that we can already handle (cover 95% of what was discussed in the issue)
* For the rest give more precise error messages
=> Enable support for decorated properties where possible

mypy/checkexpr.py, test-data/unit/check-inference.test, test-data/unit/pythoneval.test
It is a minor change to fix the example in https://github.com/python/typeshed/issues/7904
=> Fix type inference for tuples in iterable context

mypy/__main__.py, mypy/api.py, mypy/main.py
`script_path` was entirely useless since `bin_dir` had been dropped long time ago by https://github.com/python/mypy/pull/5690
=> Remove useless parameter script_path of main()

mypyc/lib-rt/int_ops.c
when building a module for web assembly with pygame-web ready to use toolchain (clang 15 based and python-wasm 3.11b4). Two warnings on different signs integer comparison would make the build fail.
=> [mypyc] Fix clang warning on different signs integer

.pre-commit-config.yaml, mypy/build.py, mypy/main.py, mypy/pyinfo.py, mypy/server/astmerge.py, mypy/server/objgraph.py, mypy/stubgenc.py, mypy/types.py, mypy/util.py, mypyc/build.py, mypyc/ir/ops.py, mypyc/primitives/registry.py, mypyc/test/test_emitfunc.py, setup.cfg, test-requirements.txt
Second attempt to update the Flake8 plugins (after #13368). This time without update Flake8 itself since it's blocked by a dependency conflict.
* ~Update and pin `flake8-pyi` to `22.8.1`: https://github.com/PyCQA/flake8-pyi/blob/master/CHANGELOG.md#2281~
**Update**: Remove `flake8-pyi`. `pyi` files aren't checked anyway.
* Update `flake8-bugbear` to `22.7.1`: https://github.com/PyCQA/flake8-bugbear#2271
* Add pre-commit config for flake8
* Remove unused ignores (after black update and move to Python 3 only)
* Add `flake8-noqa` to validate `noqa` comments: https://github.com/plinss/flake8-noqa
* Require code for `noqa`
* Remove unused `noqa` comments
* Add new ignore for `B023` (`flake8-bugbear`). This causes too many false positives ATM.
> B023: Functions defined inside a loop must not …
=> Flake8 updates

mypy/stubtest.py
For an example of how the error message here is currently broken, see https://github.com/python/typeshed/runs/7405140240?check_suite_focus=true
=> stubtest: fix broken error message for async/sync mismatch

mypy/stubtest.py
Typeshed currently has 6 allowlist entries relating to `__vectorcalloffset__` attributes in 3.10 and 3.11. I don't think there's value in adding any of these to the stub: as far as I can tell, it seems to be an undocumented, CPython-specific implementation detail of the [vectorcall protocol](https://peps.python.org/pep-0590/)
=> stubtest: ignore `__vectorcalloffset__`

mypy/checkexpr.py, mypy/constraints.py, mypy/expandtype.py, mypy/maptype.py, mypy/nodes.py, mypy/semanal.py, mypy/semanal_namedtuple.py, mypy/semanal_shared.py, mypy/tvar_scope.py, mypy/typeanal.py, test-data/unit/check-classes.test, test-data/unit/check-incremental.test, test-data/unit/check-namedtuple.test, test-data/unit/check-recursive-types.test, test-data/unit/check-tuples.test, test-data/unit/fine-grained.test, test-data/unit/fixtures/tuple.pyi
Fixes #685
This builds on top of some infra I added for recursive types (Ref https://github.com/python/mypy/pull/13297). Implementation is based on the idea in https://github.com/python/mypy/pull/13297#issuecomment-1211317009. Generally it works well, but there are actually some problems for named tuples that are recursive. Special-casing them in `maptype.py` is a bit ugly, but I think this is best we can get at the moment.
An important note on runtime support for this: IIUC this should work in Python 3.11, and should work soon with `typing_extensions` on earlier versions. I didn't add any version checks here. If someone is interested in adding those, please do this.
=> Enable generic NamedTuples

.github/workflows/docs.yml, .github/workflows/test.yml, .github/workflows/test_stubgenc.yml
Adding `workflow_dispatch` as a workflow trigger means that contributors are able to manually trigger workflow runs from their mypy forks on GitHub without having to open a PR first.
=> CI: Add `workflow_dispatch` as a trigger for several workflows

mypy/semanal.py, mypy/test/testsemanal.py, test-data/unit/pythoneval.test, test-data/unit/semanal-errors.test
Closes #13411. The error for subclassing bool is now due to it being typed as final rather than a specific check.
This means `class A(bool): ...` gives `error: Cannot inherit from final class "bool"` instead of `error: "bool" is not a valid base class` and is now ignorable with `# type: ignore`.
Writing this and playing around with it a bit more made me realise my original use case in the issue was a bit silly, although I think this change still makes sense. I wont be offended if the maintainers disagree and decide to close this though 😄 
I fixed the semantic analyser test as it shouldn't do anything about extending bool now.
I didn't add a new test as I couldn't work out exactly what stubs I needed to include/change to get a bool that's typed as final. I'm also not entirely sure they're …
=> Make bool error ignorable

mypy/stubtest.py
If a module name is private, the contents of that module are likely considered implementation details by the package author. Sometimes we want to include these implementation details in a stub, and sometimes we don't, but in my opinion stubtest probably shouldn't error for these submodules being missing from the stub. This is in keeping with stubtest's approach for class and module attributes, where it generally doesn't emit an error if the attribute name is private.
=> stubtest: don't error for a missing submodule if the submodule name is private

docs/source/common_issues.rst
More generally, we shouldn't be advising use of `--no-strict-optional`
=> Remove advice for upgrading from 0.600

mypyc/irbuild/expression.py, mypyc/irbuild/for_helpers.py, mypyc/irbuild/specialize.py, mypyc/irbuild/statement.py, mypyc/lib-rt/CPy.h, mypyc/lib-rt/misc_ops.c, mypyc/lib-rt/pythonsupport.h, mypyc/primitives/generic_ops.py, mypyc/primitives/misc_ops.py, mypyc/test-data/commandline.test, mypyc/test-data/run-async.test
=> [mypyc] Implement `async for` as a statement and in comprehensions

mypy/checker.py, test-data/unit/check-bound.test, test-data/unit/check-typevar-unbound.test
TypeVars aren't iterable, but their bounds might be! Resolve a TypeVar to its bounds before trying to decide how to unpack one of its instances. This allows unpacking from instances of TypeVars with iterable bounds, which otherwise fails.
Fixes #13402.
Added a test for a minimal reproducer.
=> Allow unpacking from TypeVars with iterable bounds

misc/test_case_to_actual.py
This pull request updates the `produce_chunks` method which included an incorrectly annotated type. By updating this test, the intent is to provide greater type safety of the `produce_chunks` method. Technically, the use of `Iterator` could also be changed to a `Generator`, but this was not a true "error", but rather dependent on intent as I understood it.
N/A
=> fix: incorrect type in `misc/test_case_to_actual.py:produce_chunks` test case

mypy/checker.py, test-data/unit/check-isinstance.test
We now allow narrowing metaclasses with `issubclass`.
Closes https://github.com/python/mypy/issues/11671
=> Allow narrowing metaclasses, refs #11671

misc/actions_stubs.py, misc/analyze_cache.py, misc/async_matrix.py, misc/convert-cache.py, misc/incremental_checker.py, misc/touch_checker.py, misc/variadics.py, scripts/find_type.py, tox.ini
Refs https://github.com/python/mypy/pull/13454#pullrequestreview-1079257932
=> Run a type check on `scripts` and most of `misc` in CI

mypy/checker.py, test-data/unit/check-parameter-specification.test
If `TypeVar`s with iterable bounds can be unpacked, so can `ParamSpecArgs`! This PR is a small extension of #13425 that allows that to happen.
I added a test that currently fails on `master`, but passes with this patch applied.
=> Allow `ParamSpecArgs` to be unpacked

misc/incremental_checker.py, misc/perf_checker.py, misc/touch_checker.py, mypy/build.py, mypy/checkexpr.py, mypy/semanal.py, mypy/stubgen.py
A followup to #13427. Unlike #13427, this PR was prepared manually.
=> Remove remaining type comments in favour of PEP 526 annotations

mypy/nodes.py, mypy/report.py, mypy/server/deps.py, mypy/stats.py, mypy/test/testdeps.py, mypyc/irbuild/function.py, mypyc/irbuild/prepare.py
Another followup to #13427. The last PR I'm planning in this series.
=> Modernize a few `Counter`/`DefaultDict` annotations

misc/actions_stubs.py, mypy/reachability.py
Previous type was insisting on one value tuple, which is not correct.
=> Use correct `tuple` type

mypy/checker.py, mypy/meet.py, mypy/subtypes.py, test-data/unit/check-overloading.test
The issue was exposed by merge of subtype visitors. Fix is actually trivial, but the diff is big because I need to add and pass the new flag everywhere (`is_subtype()`, `is_proper_subtype()`, `is_equivalent()`, `is_same_type()` can call each other).
cc @Michael0x2a
=> Fix overload overlap check for UninhabitedType

mypy/typeanal.py, test-data/unit/check-parameter-specification.test
I am mostly worried about the error message here :)
Closes #13460
=> Make sure `ParamSpec` suffix and arg kind do match

mypy/semanal.py, test-data/unit/check-parameter-specification.test
Refs https://github.com/python/mypy/pull/13468
CC @JelleZijlstra
=> `ParamSpec` must not raise errors on valid attr access

mypy/messages.py, test-data/unit/check-class-namedtuple.test, test-data/unit/check-classes.test, test-data/unit/check-ctypes.test, test-data/unit/check-expressions.test, test-data/unit/check-narrowing.test, test-data/unit/check-overloading.test, test-data/unit/check-protocols.test, test-data/unit/check-python38.test, test-data/unit/check-tuples.test, test-data/unit/check-typeddict.test, test-data/unit/pythoneval.test
This is right now a WIP, because I want to take a look at what will happen with tests, mypy-primer, etc.
Later I will add new tests for new format and consider all corner cases: like pos-only `self` or `cls` parameters.
Closes #13346
=> Use correct pos-only arg formatting in `pretty_callable`

docs/source/cheat_sheet_py3.rst
In the cheat sheet there was a missing type hint:
`subject='',`  -> `subject: str = '',`
Documentation change. I verified that the output looks OK.
=> [Docs] Add missing type hint

mypy/checker.py, test-data/unit/check-abstract.test, test-data/unit/check-classes.test, test-data/unit/check-dataclasses.test, test-data/unit/check-inference.test
Fixes #4125
Previously the code compared the original signatures for properties. Now we compare just the return types, similar to how we do it in `checkmember.py`.
Note that we still only allow invariant overrides, which is stricter that for regular variables that where we allow (unsafe) covariance.
=> Allow overriding attribute with a settable property

test-data/unit/cmdline.test
Closes #13241
Haskell-style comments for the win! 🎉
=> Reenable `testFlagsFile`

mypy/checker.py, mypy/checkexpr.py, mypy/constraints.py, mypy/join.py, mypy/meet.py, mypy/messages.py, mypy/semanal.py, mypy/subtypes.py, mypy/typeanal.py, mypy/types.py, mypyc/test-data/run-functions.test, mypyc/test/test_run.py, test-data/unit/check-incremental.test, test-data/unit/check-python38.test, test-data/unit/check-varargs.test, test-data/unit/fine-grained.test
Fixes #4441 
This uses a different approach than the initial attempt, but I re-used some of the test cases from the first PR by @franekmagiera. The initial idea was to eagerly expand the signature of the function during semantic analysis, but it didn't work well with fine-grained mode and also mypy in general relies on function definition and its type being consistent (and rewriting `FuncDef` sounds too sketchy). So instead I add a boolean flag to `CallableType` to indicate whether type of `**kwargs` is each item type or the "packed" type.
I also add few helpers and safety net in form of a `NewType()`, but in general I am surprised how few places needed normalizing the signatures (because most relevant code paths go through `check_callable_call()` and/or `is_callable_compatible()`). …
=> Allow using TypedDict for more precise typing of **kwds

mypy/checkmember.py, test-data/unit/check-overloading.test
Fixes #7781 
The fix is trivial. I guess this case was overlooked because someone thought static methods are all `Decorators`, well not always ;-)
=> Fix overloaded static methods on instances

mypy/messages.py
The same as `ErrorWatcher` constructor.
=> Use correct type annotation for `.filter_errors`

mypy/join.py, mypy/test/testinfer.py, tox.ini
I've just noticed it in a couple of places :)
=> Use new tuples

mypy/checkexpr.py, mypy/types.py, test-data/unit/check-super.test
Fixes #9282 
It looks like `super()` checking is too strict for methods with self-types. Mypy explicitly allows self-type annotation to be a supertype of current class, so to be consistent, I relax the check for `super()` as well.
=> Allow using super() in methods with self-types

mypy/binder.py, test-data/unit/check-statements.test
We now correctly handle deleted `TypeInfo` 
Closes #13226
This is a new part of mypy for me, so careful review is required.
=> Mypy can now understand deleted `TypeInfo`

mypy/subtypes.py, test-data/unit/check-protocols.test
Fixes #6393 
This is unspecified behavior in terms of PEP 544, so we just try to do something meaningful (see test case). At least we should not crash.
=> Fix crash when nested class appears in a protocol

mypy/fastparse.py
Fixes #13499
Today this code reads like "stubs should all target 3.7" and this
is indeed how typeshed operates. But authors of pyi other than typeshed
should probably be allowed to choose what Python version they're
targetting. Since typeshed runs checks against 3.7, this should not
cause testing regressions for typeshed.
This code goes back to #3000 back in the typed_ast days, when this
allowed stubs to use much newer syntax features than the base Python
version, so in some ways this is in the spirit of the original code.
=> Allow stubs to use newer syntax than 3.7

mypy/messages.py, mypy/subtypes.py, test-data/unit/check-protocols.test
Fixes #4536
This use case is specified by PEP 544 but was not implemented. Only instances (not class objects) were allowed as protocol implementations. The PR is quite straightforward, essentially I just pass a `class_obj` flag everywhere to know whether we need or not to bind self in a method.
cc @JukkaL
=> Allow classes as protocol implementations

test-data/unit/check-classes.test
=> Add test cases for method property overrides

mypy/fastparse.py, test-data/unit/check-errorcodes.test
Blocking errors are a bad user experience and there's no reason for this
one to be one / there is another code path for invalid type ignores that
is non-blocking.
Fixes half of #12299. The half it doesn't fix is that ideally users
shouldn't be getting these warnings from third party libraries.
Also see https://github.com/python/mypy/issues/12162#issuecomment-1212554729
But that's for another PR
=> Make invalid type ignore comments non-blocking

mypy/checker.py
The code involved is really old. The mentioned test case does not
trigger any errors. I cannot find any mention of this error message in
any non-ancient mypy issues
=> Assert original type exists during function redefinition

docs/source/command_line.rst, docs/source/config_file.rst
=> Mention how to test third party stubs

mypy/constraints.py, test-data/unit/check-protocols.test
I forgot to add this to yesterdays PR #13501
=> Add type inference for class object vs generic protocol

mypy/checkpattern.py, test-data/unit/check-python310.test
Fixes #12533 
The fix is trivial. I also noticed the whole procedure in that function doesn't make much sense, left a TODO about it.
=> Fix match crash on unions including tuples

mypy/options.py, test-data/unit/check-incremental.test
=> Fix error codes option serialization

mypyc/transform/exceptions.py
This might slightly improve performance when using native ints,
and it's consistent with how other error handler branches are
treated as rare.
Now the generated error handling code when calling a function
that returns a native int looks something like this (the
`unlikely(...)` part is new):
```
cpy_r_r0 = CPyDef_f();
cpy_r_r1 = cpy_r_r0 == -113;
if (unlikely(cpy_r_r1)) goto CPyL2;
```
=> [mypyc] Mark magic-overlapping error handler branches as rare

mypy/nodes.py, mypy/semanal.py, test-data/unit/check-protocols.test
Fixes #6801
Fixes #10577
Fixes #12642
Fixes #12337
Fixes #10639 
Fixes #13390 
All these crashes are in a sense duplicates of each other. Fix is trivial, except I decided to ban type aliases in protocol bodies. Already in the examples in issues, I have found two cases where people wrote `foo = list[str]`, where they clearly wanted `foo: list[str]`. This can cause hard to spot false negatives.
=> Fix crashes on special forms in protocol bodies

runtests.py
- `typeshed-ci` is not used in `typeshed` itself, moreover, `TypeshedSuite` does not exist anymore
- `SAMPLES` is also pointing to non-existant `SamplesSuite`
It is time to remove them.
=> runtests: Remove unused tasks and targets

docs/source/common_issues.rst, mypy/fastparse.py, test-data/unit/check-errorcodes.test
Per-module error codes were added in #13502, let's recommend using them.
The existing type ignore behaviour is pretty unintuitive; I think most
people actually want `# mypy: ignore-errors`. There are probably people
depending on the current behaviour of `# type: ignore` though.
Fixes #13435, fixes #12076, fixes #11999, fixes #11027, fixes #9318,
fixes #7839
=> Warn on module level type ignore with error code

CONTRIBUTING.md, test-data/unit/README.md, tox.ini
There were so many things from with this:
1. `cov` command (the second one after `pytest`) was never executed, since you needed to call it explicitly with `tox -e py38-cov`. But, in this case it was generated after the initial test run. So, basically you had two test runs to get coverage
2. `coverage` environment was just broken. For example, all packages are very outdated `diff-cover` is at [`6.5` right now](https://pypi.org/project/diff-cover/#history), while we had it pinned to `<2`. It tried to make it work, but no luck. After all, I don't think that we really need this undocumented and unused way of getting coverage
3. I've also added a working way to get coverage into the `CONTRIBUTING.md` file
=> tox: Remove outdate coverage targets

mypy/plugin.py, mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
Fixes #10090 
Unfortunately we cannot fully support this use case. Mypy requires explicit type annotations to generate methods for dataclasses before type checking. While type inference for bare `Final` happens during type checking. I still try to infer type if the default is a literal, otherwise give an error, and use `Any` for generated methods.
cc @AlexWaygood @JukkaL
=> Fix crash on bare Final in dataclass

mypyc/ir/pprint.py, mypyc/test-data/exceptions.test, mypyc/transform/exceptions.py
During the error handling transform we have access to always
defined attributes, which allows us to infer that certain
attribute operations will never fail.
This can improve performance and reduce the size of the generated
code.
=> [mypyc] Infer more precise error kinds for some ops

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test
This pull request:
1.  Fixes #8334. Overriding a dataclass attribute with a method or property now results in an error message, not a crash.
(Overriding an attribute with a non-attribute at runtime will result in either inconsistent behavior or an exception, so I think unconditionally disallowing this is fine.)
2.  Makes mypy report an error if you try subclassing a frozen dataclass with a non-frozen one or vice versa. Attempting to do this subclassing at runtime will raise a TypeError.
=> Improve error handling for dataclass inheritance

.github/workflows/mypy_primer.yml, misc/async_matrix.py, misc/cherry-pick-typeshed.py, misc/find_type.py, misc/fix_annotate.py, misc/upload-pypi.py, setup.cfg
Now that we use black for the whole codebase, there's not much reason to skip flake8 for the `misc` directory, since we use a uniform style everywhere.
Also, remove a few outdated references to the deleted `scripts` directory.
=> Don't skip flake8 for the `misc` directory

misc/proper_plugin.py, mypy/checker.py, mypy/checkexpr.py, mypy/constraints.py, mypy/fastparse.py, mypy/memprofile.py, mypy/nodes.py, mypy/plugins/singledispatch.py, mypy/report.py, mypy/semanal.py, mypy/server/objgraph.py, mypy/stubgen.py, mypy/stubtest.py, mypy/test/testcheck.py, mypy/test/testcmdline.py, mypy/test/testreports.py, mypy/type_visitor.py, mypy/typeanal.py, mypy_self_check.ini
This PR makes mypy's self-check stricter by enforcing the use of error codes for `type: ignore` comments.
=> selfcheck: enable the `ignore-without-code` error code

mypy/checker.py, test-data/unit/check-inference.test
=> Ignore partial type in base when inferring/checking

mypy/messages.py, mypy/subtypes.py, test-data/unit/check-protocols.test
Fixes #13537 
I also discovered another similar false negative, when a property in protocol was allowed to be implemented by an instance variable in class object. This is also unsafe because instance variable may not be present on class object at all. Only class variables are allowed (similar to mutable attributes in protocols).
_EDIT:_ positive -> negative
=> Fix interaction between ClassVar in protocols and class objects

mypy/checker.py
There isn't really a good reason to have a default here, feels like it
mainly just increases the chance of a bug. Also remove the `del code`
from the last PR.
=> checker: [minor] remove default message from check_subtype

mypy/server/astdiff.py, mypy/types.py, test-data/unit/fine-grained.test
Fix #11795 
The fix is straightforward (but ideally generic callables should be normalized in the first place, e.g. by better use of namespaces).
cc @JukkaL
=> Fix daemon crashes on generic methods

mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, mypy/erasetype.py, mypy/meet.py, mypy/server/objgraph.py, mypy/typeops.py, mypy/types.py, mypyc/irbuild/builder.py, mypyc/test-data/run-generators.test, test-data/unit/check-isinstance.test, test-data/unit/fixtures/isinstance.pyi, test-data/unit/fixtures/module.pyi
Fixes #1424
Fixes https://github.com/mypyc/mypyc/issues/939
Not that I really like `hasattr()` but this issue comes up surprisingly often. Also it looks like we can offer a simple solution that will cover 95% of use cases using `extra_attrs` for instances. Essentially the logic is like this:
* In the if branch, keep types that already has a valid attribute as is, for other inject an attribute with `Any` type using fallbacks.
* In the else branch, remove types that already have a valid attribute, while keeping the rest.
=> Support for hasattr() checks

mypy/semanal.py, test-data/unit/check-inference.test
This fixes a little regression caused by #13494
=> Fix simple literal inference in class bodies in import cycle

setup.cfg
This is a useful check, and it doesn't seem to generate false positives anymore
=> Remove F821 from the flake8 ignorelist

.pre-commit-config.yaml, test-requirements.txt
- Bump `flake8` from 3.9.2 to 5.0.4. As pointed out by @cdce8p in #13368, this has significant performance improvements.
- Bump `flake8-bugbear` from 22.7.1 to 22.8.23
- Bump `flake8-noqa` from 1.2.8 to 1.2.9
- Drop `importlib_metadata` as a test requirement. The whole test suite seems to pass without it, and it conflicts with flake8 >= 5.0.0.
=> Bump `flake8` test dependencies; remove `importlib_metadata` as a test dependency

mypy/plugins/dataclasses.py
While working on #13531, I noticed that DataclassTransformer's `collect_attributes` method was doing basically this:
```python
all_attrs = []
known_attrs = set()
for stmt in current_class:
attr = convert_stmt_to_dataclass_attr(stmt)
all_attrs.append(attr)
known_attrs.add(attr.name)
for info in current_class.mro[1:-1]:
if info is not a dataclass:
continue
super_attrs = []
for attr in info.dataclass_attributes:
if attr.name not in known_attrs:
super_attrs.append(attr)
known_attrs.add(attr.name)
elif all_attrs:
for other_attr in all_attrs:
if other_attr.name == attr.name:
all_attrs.remove(attr)
super_attrs.append(attr)
break
all_attrs = super_attrs + all_attrs
all_attrs.sort(key=lambda a: a.kw_only)
validate all_attrs
```
Constantly searching through and removing items from `all_attrs`, then …
=> Make dataclass attr collection no longer worst-case quadratic

mypyc/analysis/attrdefined.py, mypyc/codegen/emit.py, mypyc/codegen/emitclass.py, mypyc/codegen/emitfunc.py, mypyc/common.py, mypyc/ir/class_ir.py, mypyc/ir/ops.py, mypyc/irbuild/main.py, mypyc/test-data/run-i64.test, mypyc/test/test_emitfunc.py
Since native ints can't support a reserved value to mark an undefined
attribute, use a separate bitmap attribute (or attributes) to store
information about defined/undefined attributes with native int types.
The bitmap is only defined if we can't infer that an attribute is
always defined, and it's only needed for native int attributes.
We only access the bitmap if the runtime value of an attribute is
equal to the (overlapping) error value. This way the performance cost
of the bitmap is pretty low on average.
I'll add support for traits in a follow-up PR to keep this PR simple.
Work on mypyc/mypyc#837.
=> [mypyc] Track definedness of native int attributes using a bitmap

test-data/unit/README.md, tox.ini
This gets in the way more than I thought and has not inspired anyone to
make tests faster.
=> [minor] Actually, don't report test durations

mypyc/test/test_run.py
Temporary workaround to #13572 that slows down mypyc tests.
=> Work around mypyc test failures in CI

mypy/checker.py, test-data/unit/check-flags.test, test-data/unit/check-statements.test, test-data/unit/check-unreachable-code.test
This diff:
- Fixes #8129
- Fixes #13043
- Fixes #13167
For more concise repros of these various issues, see the modified test files. But in short, there were two broad categories of errors:
1.  Within the deferred pass, we tend to infer 'Any' for the types of different variables instead of the actual type. This interacts badly with our unreachable and disallow-any checks and causes spurious errors.
Arguably, the better way of handling this error is to only collect errors during the final pass. I briefly experimented with this
approach, but was unable to find a clean, efficient, and non-disruptive way of implementing this. So, I settled for sprinkling in a few more `not self.current_node_deferred` checks.
2.  The `self.msg.disallowed_any_type(...)` call is normally guarded behind a `not …
=> Fix spurious unreachable and disallow-any errors from deferred passes

mypy/semanal_classprop.py, test-data/unit/check-classes.test
=> Treat `ABCMeta` subtypes as abstract metaclasses

mypy/semanal.py, mypy/semanal_main.py, test-data/unit/check-classes.test, test-data/unit/check-modules.test
Finally! I've spent more than 8 hours on this test.
It illustrates a problem with `sympy` from https://github.com/python/mypy/pull/13565
=> Defer all types whos metaclass is not ready

mypy/checker.py
`calculate_metaclass_info()` does not mutate `info`, it returns a value.
It was never used.
Since `make_fake_typeinfo` is only used in a couple of places, we haven't noticed it.
=> Set metaclass in `make_fake_typeinfo`

misc/incremental_checker.py, mypy/checkexpr.py, mypy/config_parser.py, mypy/fastparse.py, mypy/ipc.py, mypy/main.py, mypy/messages.py, mypy/nodes.py, mypy/semanal.py, mypy/stubgen.py, mypy/stubtest.py, mypy/test/data.py, mypy/test/test_find_sources.py
This is a relic from blackening. Actually quite a few buggy strings in
here, so glad I did this.
=> Fix unnecessarily split quotes, couple string bugs

docs/source/metaclasses.rst, mypy/checker.py, mypy/semanal.py, test-data/unit/check-classes.test, test-data/unit/fine-grained.test
Recreate of https://github.com/python/mypy/pull/13565
=> Detect metaclass conflicts, refs #13563

mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, test-data/unit/check-dataclasses.test, test-data/unit/check-type-aliases.test
This pull request:
- Fixes #10357
- Fixes #9908
Currently, checkmember.py attempts handling only type aliases with Instance targets and ignores type aliases with a special form target such as `Union[...]`, `Literal[...]`, or `Callable[...]`, causing either a crash or odd runtime behavior.
This diff replaces that logic (the `instance_alias_type` function) with the more general-purpose `alias_type_in_runtime_context` function found in checkexpr.py.
I'm not actually 100% sure if the latter is a perfect substitute for the former -- the two functions seem to handle Instance type aliases a little differently. But I think this is probably fine: the long-term benefits of consolidating mypy's logic is probably worth some short-term risk.
=> Fix crash when using member type aliases in runtime contexts

mypy/checkexpr.py, test-data/unit/check-inference.test
Fixes #9234
This diff fixes a bug in `infer_lambda_type_using_context` where it blindly trusted and reused whatever fallback the context callable was using.
This causes mypy to crash in the case where the context was a dynamic constructor. This is because...
1.  The constructor has a fallback of `builtins.type`
2.  The Callable object `infer_lambda_type_using_context` returns uses this fallback as-is.
3.  The join of the LHS and RHS of the ternary ends up being a `def (Any) -> Any` with a fallback of `builtins.type`. See: https://github.com/python/mypy/blob/7ffaf230a3984faaf848fe314cf275b854a0cdb0/mypy/join.py#L578
4.  Later, we call `CallableType.is_type_obj()` and `CallableType.type_object()`. The former ends up succeeding due to the fallback, but the latter fails an assert because the …
=> Ensure we always infer a valid fallback type for lambda callables

mypyc/codegen/emit.py, mypyc/codegen/emitclass.py, mypyc/codegen/emitwrapper.py, mypyc/common.py, mypyc/ir/func_ir.py, mypyc/ir/rtypes.py, mypyc/irbuild/builder.py, mypyc/irbuild/callable_class.py, mypyc/irbuild/env_class.py, mypyc/irbuild/ll_builder.py, mypyc/test-data/irbuild-i64.test, mypyc/test-data/run-functions.test, mypyc/test-data/run-i64.test
Since native ints can't have a dedicated reserved value to mark a
missing argument, use extra bitmap arguments that are used to indicate
whether default values should be used for particular arguments. The
bitmap arguments are implicitly added at the end of a signature. They
are not visible to user code and are just an implementation detail.
This is analogous to how we track definedness of native int attributes
using bitmaps.
If a function accepts no arguments with a native int type and a default
value, the bitmap arguments won't be generated.
This doesn't handle inheritance properly. I'll fix inheritance in a
follow-up PR.
Work on https://github.com/mypyc/mypyc/issues/837.
=> [mypyc] Properly support native int argument defaults

mypy/checker.py, mypy/checkexpr.py, mypy/errorcodes.py, mypy/message_registry.py, mypy/messages.py
Let it only take an ErrorMessage. The default error now gets an error
code as well, which closes up some code paths where we were getting code
"misc".
=> checker: simplify check_simple_assignment error handling

mypyc/test-data/exceptions.test, mypyc/test-data/run-i64.test, mypyc/transform/uninit.py
There's no reserved value we can use to track if a local variable with
a native int type hasn't been initialized yet. Instead, use bitmaps to
track whether a local is defined, but only if the local has a native
int type and can be undefined.
Work on https://github.com/mypyc/mypyc/issues/837.
=> [mypyc] Support undefined locals with native int types

mypy/expandtype.py, test-data/unit/check-python310.test
Oh, this was very interesting.
During the debug sessions I learned a lot about how pattern matching and its analysis do work.
But, the problem was that `expand_type` did not preserve `.last_known_value` for some reason.
I used `.copy_modified` to preserve everything we know about `Instance`.
However, I expect that some tests might fail now. This code even has something similar in `TODO` some lines above: 
https://github.com/python/mypy/blob/88aed94ae3de2542491f6cd65d1236c4f0cdedb1/mypy/expandtype.py#L144-L148
Let's see what will happen.
Closes https://github.com/python/mypy/issues/13612
=> Fix type inference in pattern matching by positional argument

docs/source/running_mypy.rst
On Windows, `MYPYPATH` needs to be a _semicolon_-separated list of paths, rather than a _colon_-separated list of paths.
=> `MYPYPATH`: Improve docs for those running on Windows

mypy/errorcodes.py, mypy/message_registry.py, mypy/typeanal.py, test-data/unit/check-errorcodes.test
I only added codes that I was fairly confident about
=> typeanal: add error codes for many errors

mypy/semanal.py, mypy/semanal_typeddict.py, test-data/unit/check-typeddict.test
Allow a `TypedDict` to be decorated with `@final`. Like a regular class, mypy will emit an error if a final `TypedDict` is subclassed.
Relates-to: #7981
Allow `@final` to be applied to a `TypedDict`, and have mypy emit an error if class is derived from a final `TypedDict`. This goes some way towards closing #7981 and closing a feature gap with pyright, though not the whole way, as #7981 also asks for additional type narrowing for a final `TypedDict`.
`testCannotUseFinalDecoratorWithTypedDict` was removed, and `testCannotSubclassFinalTypedDict` added.
=> Allow `@final` on `TypedDict`

mypy/constraints.py, mypy/test/testconstraints.py, mypy/test/typefixture.py
This implements cases for homogenous and non-homogenous tuples in the supertype of branch for constraints checking for variadic generics. This fleshes it out enough that afterwards we can work on making the logic work for the subtype-of branch as well.
=> Implement tuple cases for typevartuple constraints

mypy/checkexpr.py, test-data/unit/check-expressions.test
`reveal_type` provides a useful note to users that it will always reveal `Any` within an unchecked function. Similarly, `assert_type` always checks against `Any`, but does not notify the user about its behavior. 
This PR adds said note, which is displayed when `assert_type` raises an error in an unchecked function
I added a test to `test-data/unit/check-expressions.test` that is comparable to the corresponding test case for `reveal_type` in an unchecked scope.
=> Note that `assert_type` always matches against any in untyped function

mypy/build.py, mypy/checker.py, mypy/errors.py, mypy/main.py, mypy/options.py, mypy/semanal.py, mypy/semanal_main.py, mypy/util.py
This was broken by https://github.com/python/mypy/pull/13155, fix is straightforward, pass custom typeshed dir from options everywhere.
=> Fix custom typeshed dir handling by is_typeshed_file()

mypy/semanal.py, test-data/unit/check-classes.test
=> Treat `Any` metaclass the same as `Any` base class

docs/source/getting_started.rst, docs/source/installed_packages.rst, docs/source/running_mypy.rst, mypy/build.py, mypy/modulefinder.py, test-data/unit/fine-grained-modules.test, test-data/unit/pythoneval.test
Fixes #13633
- Incompatible stubs aren't really a thing (that is visible to mypy at module find time) now that Python 2 support is dead.
- Adjust some documentation wording to clarify use of `--python-executable`
=> Better errors for missing imports

mypyc/irbuild/specialize.py, mypyc/test-data/irbuild-i32.test, mypyc/test-data/irbuild-i64.test, mypyc/test-data/run-i32.test, mypyc/test-data/run-i64.test
These are now optimized for i32, i64 and int arguments.
`i32(x)` truncates from `i64`, but does a range check when converting from `int`. The rationale is that implicit conversions from `int` perform range checks to avoid silently corrupting data, and explicit coercions use the same semantics. However, conversions from `i64` to `i32` must be explicit and thus there is no implicit corruption possible. Truncation is also a very fast operation, which we generally prefer when working purely on native integers. A range check would introduce some overhead. I'm not sure if this is the best approach, however, and this feels a bit inconsistent. 
I'll add optimized conversions from float in another PR once we support unboxed floats. Conversions from other types could also be improved in the future. …
=> [mypyc] Generate efficient code for (some) conversions i64(x) and i32(x)

mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, mypy/expandtype.py, mypy/maptype.py
Removing a bunch of `TODO` items.
=> refactor: Use `@overload` for `expand_type`

mypy/build.py, mypy/partially_defined.py, mypy/server/update.py, test-data/unit/check-partially-defined.test
This builds on #13601 to add support for statements like `continue`, `break`, `return`, `raise` in partially defined variables check. The simplest example is:
```python
def f1() -> int:
if int():
x = 1
else:
return 0
return x
```
Previously, mypy would generate a false positive on the last line of example. See test cases for more details.
Adding this support was relatively simple, given all the already existing code. 
Things that aren't supported yet: `match`, `with`, and detecting unreachable blocks.
After this PR, when enabling this check on mypy itself, it generates 18 errors, all of them are potential bugs.
Tests added.
=> Add support for jump statements in partially defined vars check

mypy/checker.py, test-data/unit/check-bound.test, test-data/unit/check-typevar-unbound.test
TypeVars aren't iterable, but their bounds might be! Resolve a TypeVar to its bounds before trying to decide how to unpack one of its instances.
Fixes #13402
=> [0.980 backport] Allow unpacking from TypeVars with iterable bounds (#13425)

mypy/partially_defined.py, test-data/unit/check-partially-defined.test
Generating errors after first occurrence is pure noise -- if the variable is actually undefined, the code would stop executing there.
Added tests.
=> Report partially undefined variables only on first occurrence

mypy/partially_defined.py, test-data/unit/check-partially-defined.test
Description
Adds support for `DictionaryComprehension` nodes for the partially defined check.
/CC: @ilinum
=> Handle DictComp when checking for partially defined vars

test-data/unit/check-parameter-specification.test, test-data/unit/check-python38.test
The CI has started to sporadically fail depending on whether 3.10.6 is picked up by GitHub Actions (okay) or 3.10.7 (not okay). For example:
- https://github.com/python/mypy/actions/runs/3046671132/jobs/4909772702
- https://github.com/python/mypy/actions/runs/3046723692/jobs/4909887963
On Python 3.10.7 (but not on Python 3.10.6), mypy correctly rejects using PEP 570 syntax unless `--python-version` is set to 3.8 or higher (this is due to https://github.com/python/cpython/pull/95935). However, this makes several unit tests fail.
This PR updates those unit tests so that the CI passes on both 3.10.6 and 3.10.7
=> Update pos-only unit tests for Python 3.10.7

mypy/stubtest.py, mypy/test/teststubtest.py
Closes https://github.com/python/mypy/issues/13646
=> stubtest: Detect abstract properties mismatches

test-data/unit/check-parameter-specification.test, test-data/unit/check-python38.test
Backport #13660 to fix test issues with Python 3.10.7.
https://github.com/python/mypy/actions/runs/3046723692/jobs/4909887963
=> [0.980 backport] Update pos-only unit tests for Python 3.10.7 (#13660)

.github/workflows/test.yml
I don't think testing the different architecture gains us anything, and [we don't build mypyc compiled wheels for win32 anyway](https://github.com/mypyc/mypy_mypyc-wheels/blob/aabe075c7abe8baa0b212cc14e7ab607dffa6934/build_wheel.py#L35), so there shouldn't be a difference between the two. This should provide a nice speedup to the test suite as well.
These tests were initially introduced in https://github.com/python/mypy/pull/8327.
=> Don't run test suite on 32bit Windows

.github/workflows/test.yml, build-requirements.txt, mypy-requirements.txt, pyproject.toml, setup.py
I probably should have held off on merging https://github.com/mypyc/mypy_mypyc-wheels/pull/47 until whenever the 0.980 release happened.
=> [0.980 backport] build changes

docs/source/cheat_sheet_py3.rst, docs/source/type_inference_and_annotations.rst
=> Update cheat sheet docs

docs/source/existing_code.rst
See #13681
In particular, it's really common to want to make progress towards `--strict`, and we currently don't really have any guidance on doing so. Per-module ignore_errors is also a really useful tool for adopting mypy.
=> Major update to "using mypy with existing codebase"

docs/source/runtime_troubles.rst
See #13681
PEP 563 is in limbo, so fix incorrect statements
Mention what type comments are since we've deleted most documentation of type comments when dropping support for Python 2
The new docs theme underemphasises notes, so maybe warning role is better
=> Update runtime_troubles docs

README.md, docs/source/index.rst
See #13681
I previously reworked some of the language in the README and I think it makes sense to re-use the same words in the docs intro. I've merged the two where I felt one was lacking.
=> Use the same language in the docs intro and README

mypy/constraints.py, mypy/nodes.py, mypy/semanal.py, mypy/test/testconstraints.py, test-data/unit/check-typevar-tuple.test, test-data/unit/semanal-errors.test
Originally this PR was intended to add some test cases from PEP646. However it became immediately apparent that there was a major bug in the implementation where we expected the definition to look like:
```
class Foo(Generic[Ts])
```
When it is supposed to be
```
class Foo(Generic[Unpack[Ts]])
```
This fixes that.
=> Fix typevar tuple handling to expect unpack in class def

mypy/constraints.py, mypy/typevartuples.py, test-data/unit/check-typevar-tuple.test
The existing logic for splitting mapped & template into prefix, middle, and suffix does not handle the case where the template middle itself is not a singleton unpack but rather itself has a prefix & suffix.
In this case we need to pull out the prefix & suffix by doing a second round of splitting on the middle. Originally we weren't sure if the PEP required implementing this double split, but one of the PEP646 test cases requires it.
=> Tweak constraints handling for splitting typevartuples

mypy/stubgen.py, mypy/stubgenc.py, mypy/test/teststubgen.py
Note: This change is part of a series of upcoming MRs to improve `stubgenc`. 
`stubgenc` tries 3 approaches to infer signatures for a function.  There are two problems with the current design:
1. the logic for how these approaches are applied is somewhat convoluted, to the point that it's not even clear at first that there are 3 distinct approaches (from rst files, from docstrings, fallback guess).
2. there's not a clear path for how a developer would create a new approach.  
Here's the heart of the current logic (comments added for clarity):
```python
if (
name in ("__new__", "__init__")
and name not in sigs
and class_name
and class_name in class_sigs
): 
inferred: Optional[List[FunctionSig]] = [
FunctionSig(
name=name,
args=infer_arg_sig_from_anon_docstring(class_sigs[class_name]), …
```
=> stubgenc: Introduce an object-oriented system for extracting function signatures

mypy/semanal.py, mypy/semanal_namedtuple.py, mypy/typeanal.py, test-data/unit/check-classes.test, test-data/unit/check-namedtuple.test, test-data/unit/check-typeddict.test
Fixes #12112.
The reason why mypy was crashing with a "Must not defer during final iteration" error in the following snippet:
def test() -> None:
T = TypeVar('T', bound='Foo')
class Foo:
def bar(self, foo: T) -> None:
pass
...was because mypy did not seem to be updating the types of the `bar` callable on each pass: the `bind_function_type_variables` method in `typeanal.py` always returned the _old_ type variables instead of using the new updated ones we found by calling `self.lookup_qualified(...)`.
This in turn prevented us from making any forward progress when mypy generated a CallableType containing a placedholder type variable. So, we repeated the semanal passes until we hit the limit and crashed.
I opted to fix this by having the function always return the …
=> Fix crash with generic class definition in function

mypy/join.py, test-data/unit/check-classes.test
This pull request fixes #9838.
It turns out that when an object is using a metaclass, it uses that metaclass as the fallback instead of `builtins.type`.
This caused the `if t.fallback.type.fullname != "builtins.type"` check we were performing in `join_similar_callables` and combine_similar_callables` to pick the wrong fallback in the case where we were attempting to join a function against a constructor for an object that used a metaclass.
This ended up causing a crash later for basically the exact same reason discussed in #13576: using `abc.ABCMeta` causes `Callable.is_type_obj()` to return true, which causes us to enter a codepath where we call `Callable.type_object()`. But this function is not prepared to handle the case where the return type of the callable is a Union, causing an …
=> Fix joining a function against metaclass-using object constructors

docs/source/type_inference_and_annotations.rst
See #13681.
Prefer mypy: ignore-errors over module level type: ignore, which is surprising. Fold starred expr section into talking about PEP 526 declaration only. Don't talk about stubs.
=> Update type inference and annotations

mypy/checker.py, test-data/unit/check-classes.test, test-data/unit/check-typevar-unbound.test
Also don't complain about other TypeVarLikeTypes
Implements https://github.com/python/mypy/pull/13166#issuecomment-1186582122
=> Suggest using upper bound for unbound tvar

mypy/checkpattern.py, test-data/unit/check-python310.test
Fixes #12886
`contract_starred_pattern_types` and `expand_starred_pattern_types` are sort of like inverses of each other, so you get crashes if `contracted_inner_types` and `contracted_new_inner_types` don't correspond (in the case that `can_match` gets set to `False`). ~When `can_match` is False, we don't need `contracted_new_inner_types`, so this PR just moves an if statement up a little bit and indent everything.~ I'm not sure `can_match` is doing anything useful, so this PR now just gets rid of it.
=> Fix crash in match statement with unmatchable ClassPattern

mypy/checker.py, mypy/typeshed/stdlib/_typeshed/__init__.pyi, test-data/unit/check-generic-subtyping.test, test-data/unit/fixtures/typing-full.pyi
Fixes https://github.com/python/mypy/issues/13713, fixes https://github.com/python/mypy/issues/736, fixes https://github.com/python/mypy/issues/8611
=> Fix unsound variance

mypy/checker.py, mypy/messages.py, test-data/unit/check-functions.test, test-data/unit/check-modules.test, test-data/unit/check-newsemanal.test, test-data/unit/check-unions.test, test-data/unit/check-unreachable-code.test
=> Better diagnostic for conditional function mismatch

mypy/report.py
=> Fix crash with report generation on namespace packages

mypy/plugins/dataclasses.py, test-data/unit/check-dataclasses.test, test-data/unit/fine-grained.test
Fixes half of https://github.com/python/mypy/issues/4536#issuecomment-1256742112
=> Treat __dataclass_fields__ as ClassVar

docs/source/protocols.rst
See #13681.
The current documentation page isn't friendly because it's basically an API reference before we get to the fun bit about typing.Protocol.
=> Talk about user defined protocols first

mypy/semanal.py, test-data/unit/check-recursive-types.test
As `mypy_primer` in https://github.com/python/mypy/pull/13516 shows, some people actually use this, and I don't see any good reason to not allow this. (Note: I tried to enable the same for recursive NamedTuples and TypedDicts, but this affects how nested classes work in general, so people will need to use qualified names there).
=> Allow recursive aliases at class scope

mypy/build.py
=> Respect per-module follow_import for empty folders

mypy/semanal.py, test-data/unit/check-dataclasses.test
This should fix a crash discovered by `mypy_primer` in https://github.com/python/mypy/pull/13516
The logic here is that when type aliases have placeholders they are updated _in place_ (the node gets a new resolved target type). But this means that some variables annotated with type aliases may not get stored types, unless we defer targets where they are defined.
This didn't cause troubles before, because we waited for type alias to be complete before putting it into symbol table. Now it is not possible, we need to put something into symbol table for partially complete aliases to support recursive aliases (similar to recursive classes).
Also, it was tricky to come up with a repro for this issue, because when it happens, the variable gets a "silent" `Any` type, and only when it appears in a …
=> Always re-process annotations refering to an alias on update

mypy/build.py, mypy/server/update.py, test-data/unit/fine-grained-modules.test
If daemon was running and additional third party code was installed, mypy
daemon would report errors from the code. This was inconsistent with 
non-daemon mypy and the initial daemon run. If mypy was run with strict
options, this could results lots of errors being generated.
The same code is used to silence errors from typeshed. I'm using typeshed in 
the test case since it was easier to do.
I also manually verified that this works with pytest, aiohttp and some typeshed
stub packages.
Fixes #13140.
=> Silence errors from third party packages in daemon

mypy/dmypy/client.py, mypy/dmypy_server.py
Capture stdout in daemon and display it in the client. This makes it possible to use debug prints in 
the daemon when doing end-to-end testing. They previously only worked in daemon test cases.
=> Support debug prints in mypy daemon

mypy/messages.py, test-data/unit/check-parameter-specification.test
Resolves #13711, resolves #13429
=> Improve error message for `--strict-concatenate`

mypy/messages.py, test-data/unit/check-protocols.test
=> Improve error message for implicitly abstract functions

mypy/server/update.py, mypy/test/testfinegrained.py, test-data/unit/fine-grained-blockers.test, test-data/unit/fine-grained-follow-imports.test, test-data/unit/fine-grained-modules.test, test-data/unit/fine-grained.test
This fixes an annoyance where the messages got reshuffled between daemon runs.
Also if there are messages from files that didn't generate messages during the previous run, move them towards the end to make them more visible.
The implementation is a bit messy since we only have a list of formatted lines where it's most natural to sort the messages, but individual messages can be split across multiple lines.
Fix #13141.
=> Preserve file order of messages during successive daemon runs

test-data/unit/check-typeddict.test
This is a small follow-up to #13678 and #13755.
In the former diff, I added a TypeVar scope frame around TypedDict creation. However, I had really no good reason for doing this at the time: I wasn't able to find a bug due to the missing frame and added it purely speculatively, out of a desire for symmetry.
It turns out this missing frame does legitimately cause some issues, which were reported in the latter.
So, this diff encodes one of the reported bugs as a test case to make sure we don't regress.
=> Add test case for missing TypedDict TypeVar scope frame

setup.py
setup.py:
Change `setup()` call to include pip in the list of dependencies passed to `install_requires`.
Pip is required for the `mypy --install-types` feature. Without specifically adding it, minimal environments (e.g. venvs) will not have pip installed and therefore have no way of installing required types (e.g. for tests).
Fixes #13580
=> Add pip to install_requires

mypy/subtypes.py, test-data/unit/check-inference.test
Fixes https://github.com/python/mypy/issues/13756
=> Restore Type vs Callable special-casing that was broken in refactoring

docs/source/error_code_list.rst, mypy/errorcodes.py, mypy/messages.py, test-data/unit/check-errorcodes.test
Ref #4717 
This will allow people who consider this check too strict to opt-out easily using `--disable-error-code=type-abstract`.
=> Use a dedicated error code for abstract type object type error

mypyc/test-data/run-classes.test
Ref #12840 
Traceback formatting is simply different on Python 3.11.
=> Fix one mypyc test case on Python 3.11

mypy/checker.py, mypy/subtypes.py, mypy/types.py, test-data/unit/check-isinstance.test, test-data/unit/check-modules.test, test-data/unit/fine-grained-inspect.test, test-data/unit/lib-stub/types.pyi
Fixes https://github.com/python/mypy/issues/13771#issuecomment-1262749908
=> Fix module and protocol subtyping, module hasattr

mypyc/codegen/emitmodule.py
Signed-off-by: jinzewu <294843472@qq.com>
Remove unnecessary comment line since the `compile_modules_to_c` function has no `ops` argument.
=> Remove unnecessary comment line

mypy/checker.py, mypy/meet.py, mypy/subtypes.py, mypy/typeops.py, test-data/unit/check-classes.test, test-data/unit/check-expressions.test, test-data/unit/check-isinstance.test, test-data/unit/check-unions.test, test-data/unit/fixtures/tuple.pyi
Fixes #13760 
Fixes #6060
Fixes #12824
This is a right thing to do, but let's what `mypy_primer` will be. This also required re-applying #6181 (which is also a right thing to do) otherwise some tests fail.
=> Ignore promotions when simplifying unions

mypy/maptype.py
This should help people who need to `import mypy.reports` directly, see https://github.com/python/mypy/pull/13396#discussion_r985683512
=> Move an import to avoid cyclic imports

mypy/dmypy/client.py, mypy/util.py
Fixes #13806
This PR adds support for a FORCE_COLOR environment variable. If both MYPY_FORCE_COLOR and FORCE_COLOR are present, mypy will continue to use MYPY_FORCE_COLOR over FORCE_COLOR. However, if only FORCE_COLOR is set, mypy will use that environment variable in much the same way it currently uses MYPY_FORCE_COLOR.
MYPY_FORCE_COLOR appears to be undocumented and untested currently, so this PR doesn't add any tests. However, @hugovk has tested this change manually and using GitHub Actions, and reports that it appears to work as expected.
=> Fall back to FORCE_COLOR environment variable if MYPY_FORCE_COLOR is not present

mypyc/lib-rt/misc_ops.c
Hopefully this will fix the last failing test on Python 3.11
cc @JukkaL @msullivan @hauntsaninja
=> Opt out from the managed dict for compiled classes on Python 3.11

.github/workflows/test.yml
For now we run non-compiled version. (I tried compiling mypy locally and it failed with couple errors, some deprecation error, and a weird pointer type mismatch)
I also ass Python 3.12 that will always pass, just to be prepared for the next version
=> Run tests on Python 3.11 as required

test-requirements.txt
`typed_ast` is not directly used in tests, and is never imported on Python 3.8+.
Its requirement should be defined as a regular one (for Python < 3.8).
Saw it's installed while trying 3.11 wheels build and thought it's odd :P
=> Remove typed_ast tests requirement

mypy/checkexpr.py, mypy/join.py, mypy/nodes.py, mypy/semanal.py, mypy/semanal_classprop.py, test-data/unit/check-recursive-types.test
Fixes #13795
Calculating tuple fallbacks on the fly creates a cycle between joins and subtyping. Although IMO this is conceptually not a right thing, it is hard to get rid of (unless we want to use unions in the fallbacks, cc @JukkaL). So instead I re-worked how `join_types()` works w.r.t. `get_proper_type()`, essentially it now follows the golden rule "Always pass on the original type if possible".
=> Make join of recursive types more robust

mypy/stubtest.py
=> stubtest: catch SyntaxError from inspect.getsourcelines

pyproject.toml
Our current isort config doesn't fully work for the pre-commit hook. Whereas in tox isort is called with the global `.` path, pre-commit passes all filenames individually.
E.g. running this command will also reformat the `mypy/typeshed` directory:
```
pre-commit run isort --all-files
```
Using `skip_glob` instead of `skip` will resolve the issue.
https://pycqa.github.io/isort/docs/configuration/options.html#skip-glob
Followup to https://github.com/python/mypy/pull/13832#issuecomment-1272552104
/CC: @hauntsaninja
=> Fix isort skip config

mypy/messages.py, mypy/typeanal.py, test-data/unit/check-varargs.test
This fixes couple issues discovered in https://github.com/python/mypy/pull/13790:
* A crash on empty `Unpack`
* Wrong behavior with implicit generic `Any`
The latter was actually caused by somewhat reckless handling of generic `TypedDict`s, wrong argument count was handled inconsistently there.
=> Fix minor issues with keywords Unpack

mypy/checker.py, mypy/errorcodes.py, mypy/messages.py, test-data/unit/check-classes.test, test-data/unit/check-dataclasses.test, test-data/unit/check-errorcodes.test, test-data/unit/check-incremental.test, test-data/unit/check-inference-context.test, test-data/unit/check-newsemanal.test, test-data/unit/check-statements.test
Closes #3948
This however gives a note instead of an error, so that type checking result will be success. I also added an error code for the note so that people can opt-out if they want to.
=> Add a note on variable annotation within unchecked function

mypy/build.py, test-data/unit/check-incremental.test
Fixes #13825
We add also types encountered in locally defined symbols, not just expressions. I think we may also need to add base-classes/metaclass for `TypeInfo`s, I will check and add if needed ~tomorrow.
=> Fix crash on missing indirect dependencies

mypyc/test/test_commandline.py
This fixes the testErrorOutput and testCompileMypyc test cases by setting up the module search path explicitly.
=> [mypyc] Fix command-line tests on Python 3.11

.github/workflows/test.yml
This will give us more confidence that compiled mypy works on 3.11.
=> Use mypyc for Python 3.11 tests in CI

mypy/typeanal.py, test-data/unit/check-basic.test, test-data/unit/check-errorcodes.test, test-data/unit/fine-grained.test
@AlexWaygood do you have any suggestions about the error message?
=> Suggest to use a protocol instead of a module

mypy/errors.py, test-data/unit/check-errorcodes.test
This will hint people affected by #13851 what to do to silence this. I am not doing it for all notes as this will cause too much noise (especially for some nicely formatted multi-line notes like possible overloads, incompatible overrides, or protocol mismatches), instead we can select specific codes that we want to show.
cc @svalentin
=> Show error codes for some notes

mypy/constraints.py, mypy/messages.py, mypy/subtypes.py, mypy/test/testsubtypes.py, mypy/typevartuples.py, test-data/unit/check-typevar-tuple.test
This adds a new Pep646 test case which demonstrates that like with the constraints from PR #13716 we need to split twice for subtyping when handling Unpacks.
It also demonstrates a weakness of the previous PR which is that the middle-prefix and the prefix may need to be handled differently so we introduce another splitting function that returns a 10-tuple instead of a 6-tuple and reimplement the 6-tuple version on top of the 10-tuple version.
Complicating things further, the test case reveals that there are error cases where split_with_mapped_and_template cannot actually unpack the middle a second time because the mapped middle is too short to do the unpack. We also now have to deal with the case where there was no unpack in the template in which case we only do a single split.
In …
=> Extend support for tuple subtyping with typevar tuples

misc/upload-pypi.py
After we started using black upload-pypi broke because we switched the style of quotes. This remedies that.
=> Fix quotes for upload-pypi version check

.github/workflows/sync_typeshed.yml
Otherwise the commit it wants to cherry-pick doesn't exist: https://github.com/python/mypy/actions/runs/3253702865/jobs/5341201852
=> sync_typeshed: add fetch-depth: 0

test-data/unit/check-parameter-specification.test
It was very confusing, because `int` and `str` were messed up.
=> Change `testParamSpecApplyConcatenateTwice` test

mypyc/irbuild/prepare.py, mypyc/test-data/run-i64.test
Avoid creating duplicate bitmap arguments for the constructor. These would generate broken C with errors like these:
```
build/__native.c:122:74: error: redefinition of parameter ‘cpy_r___bitmap’
122 | PyObject *CPyDef_Foo(int64_t cpy_r_xx, uint32_t cpy_r___bitmap, uint32_t cpy_r___bitmap)
```
=> [mypyc] Fix native int default args in __init__

mypy/applytype.py, mypy/checker.py, mypy/checkexpr.py, mypy/constraints.py, mypy/expandtype.py, mypy/messages.py, test-data/unit/check-typevar-tuple.test
This implements the most basic support for the *args feature but various edge cases are not handled in this PR because of the large volume of places that needed to be modified to support this.
In particular, we need to special handle the ARG_STAR argument in several places for the case where the type is a UnpackType. Finally when we actually check a function we need to construct a TupleType instead of a builtins.tuple.
=> Implement basic *args support for variadic generics

mypy/checkmember.py
We're dealing with the get descriptor here but calling it `__set__`, probably a copy-paste from similar code elsewhere. I think this only affects messages.
=> Fix __set__ to __get__ in messages

docs/source/cheat_sheet_py3.rst
- Mention PEP 604 unions
- Separate out the 3.8 stuff to keep things more readable
- Remove mention of typing.Match
- Remove unnecessary mention of stub
- Make classes more prominent
- Clarify that forward references fail at runtime
- More of an example for Any
- Mention None return
- Make default value example mean something
- Move Union docs to builtin types
Linking #13681
=> Improve cheat sheet

mypy/messages.py, test-data/unit/check-modules.test
Also only suggest public API for attribute access suggestions
Fixes #13908
Accomplishes a similar thing to #9084 (the logic from there could be improved too, will send a PR for that next)
=> Mention implicit export on missing attribute access

docs/source/extending_mypy.rst
Changes:
- Removes notes about old semantic analyzer, it is long gone
- Removes outdated `contextlib` example, see https://github.com/python/mypy/pull/13923
- Changes `get_function_hook` wording. Because we cannot promise that we do track exact values in all cases
=> Update `extending_mypy.rst` docs

mypy/partially_defined.py, test-data/unit/check-partially-defined.test, test-data/unit/check-python310.test
This adds support for match statements for the partially-defined variables check. This should completely cover all match features. 
In addition, during testing, I found a bug in the generic branch tracking logic, which is also fixed here.
Because match is only supported in python 3.10, I had to put the tests in a separate file, which is a bit unfortunate; let me know if you have better ideas.
=> Support match statement in partially defined check

docs/source/stubtest.rst
Some of my students asked about this. I think it is better to have this information in the docs: it is important.
=> [Docs] Add warning about `stubtest` code execution

mypy/semanal.py, test-data/unit/check-flags.test, test-data/unit/check-modules.test
Related to #13917 and #13908. This handles situations involving per-module re-exports correctly / is consistent with the error you'd get with attribute access.
=> Always mention explicit export when relevant

mypyc/ir/func_ir.py, mypyc/irbuild/function.py, mypyc/irbuild/ll_builder.py, mypyc/sametype.py, mypyc/test-data/irbuild-glue-methods.test, mypyc/test-data/irbuild-i64.test, mypyc/test-data/run-i64.test
This fixes handling of bitmap arguments used to track default values of arguments with native int types in method overrides.
The main use case is a method override that adds a native int argument with a default value to the base class signature.
Also generate an error if we don't support generating a glue method for an override. This can happen if the positions of bits in the bitmap would change in the subclass. We also don't support switching between error values and default value bitmaps in glue methods. These could be supported, but it would be complicated and doesn't seem worth it.
Work on mypyc/mypyc#837.
=> [mypyc] Fix glue methods with native int types

mypyc/analysis/ircheck.py, mypyc/test/test_ircheck.py
It's okay to take an address of a register, pass it to a function that initializes the register, and then read the register. Ircheck complained about an invalid op reference to register in this case. It affected at least async code.
=> [mypyc] Fix ircheck if register is initialized through LoadAddress

mypy/checker.py, test-data/unit/pythoneval.test
- Add type inference for `dict.keys` membership
Also for containership checks on `typing.KeysView.` This is to bring the
following cases into alignment:
from typing import KeysView
key: str | None
d: dict[str, int]
kv: KeysView[str]
if key in d:
...
if key in d.keys():
...
if key in kv:
...
Before this change only the first `if` would narrow the type of `key`.
I've just added a test under `test-data/unit/pythoneval.test` as
`test-data/unit/fixtures/dict.pyi` doesn't include `dict.keys`, and
adding it requires importing `dict_keys` from `_collections_abc` in
those stubs, which then requires adding `_collections_abc.pyi` stubs,
which would have to be complete since e.g.
`testGenericAliasCollectionsABCReveal` expects most of the types in
those stubs to be defined (this is the same approach …
=> Add type inference for `dict.keys` membership

mypy/main.py, mypy/options.py, mypy/semanal_classprop.py, test-data/unit/check-flags.test
It might be useful to run mypy_primer without promotions in typeshed. This would give us more confidence in changes stemming from https://github.com/python/typeshed/issues/9001
=> Add hidden options to disable bytes promotion

mypy/typeshed/stdlib/builtins.pyi
This is allegedly causing large performance problems, see 13821
typeshed/8231 had zero hits on mypy_primer, so it's not the worst thing to undo. Patching this in typeshed also feels weird, since there's a more general soundness issue. If a typevar has a bound or constraint, we might not want to solve it to a Literal.
If we can confirm the performance regression or fix the unsoundness within mypy, I might pursue upstreaming this in typeshed.
(Reminder: add this to the sync_typeshed script once merged)
=> Revert sum literal integer change

mypy/semanal.py, mypy/typeanal.py, test-data/unit/check-parameter-specification.test
=> Warn on invalid `*args` and `**kwargs` with `ParamSpec`

mypy/semanal_typeddict.py, test-data/unit/check-typeddict.test
Fixes #13066
During the semanal phase, mypy opts to ignore and skip processing any malformed or illegal statements inside of a TypedDict class definition, such as method definitions.
Skipping semanal analysis on these statements can cause any number of odd downstream problems: the type-checking phase assumes that all semanal-only semantic constructs (e.g. FakeInfo) have been purged by this point, and so can crash at any point once this precondition has been violated.
This diff opts to solve this problem by filtering down the list of statements so we keep only the ones we know are legal within a TypedDict definition.
The other possible solution to this problem is to modify mypy so we skip checking TypedDict class bodies entirely during type checking and fine-grained deps analysis. Doing …
=> Fix crash with malformed TypedDicts and disllow-any-expr

mypy/semanal.py, test-data/unit/check-flags.test, test-data/unit/check-modules.test
Fixes some of #13965, fixes #12749
We also need to modify attribute access logic (this is the TODO in the PR), which is a little trickier. But cases like #13933 convinced me it's worth making this change, even before I get around to figuring that out.
=> Preserve (some) implicitly exported types

mypy/ipc.py
As per the TODO comments, this PR removes some unnecessary `assert`s in `mypy/ipc.py`. When these `assert`s were added in #6148, typeshed wasn't able to use `Literal` types yet. However, nowadays, typeshed has precise `Literal` overloads for `_winapi.WriteFile` and `_winapi.ConnectNamedType`, meaning mypy is able to precisely infer the return type of these function calls without the need for the `assert`s in `mypy/ipc.py`: https://github.com/python/typeshed/blob/main/stdlib/_winapi.pyi.
=> `mypy/ipc.py`: Remove some typeshed-related TODOs

mypy/checker.py, mypy/semanal.py, test-data/unit/check-classes.test, test-data/unit/check-incremental.test, test-data/unit/check-modules.test, test-data/unit/check-protocols.test, test-data/unit/check-redefine.test
This changes our importing logic to be more consistent and to treat import statements more like assignments.
Fixes #13803, fixes #13914, fixes half of #12965, probably fixes #12574
The primary motivation for this is when typing modules as protocols, as in #13803. But it turns out we already allowed redefinition with "from" imports, so this also seems like a nice consistency win.
We move shared logic from visit_import_all and visit_import_from (via process_imported_symbol) into add_imported_symbol. We then reuse it in visit_import.
To simplify stuff, we inline the code from add_module_symbol into visit_import. Then we copy over logic from add_symbol, because MypyFile is not a SymbolTableNode, but this isn't the worst thing ever.
Finally, we now need to check non-from import statements like …
=> Better story for import redefinitions

mypyc/build.py
Closes https://github.com/mypyc/mypyc/issues/956
This was originally a part of #13953, see https://github.com/python/mypy/pull/13953#discussion_r1007593391
=> Fix Mypyc not compiling on Arch Linux

docs/source/running_mypy.rst
See #13681
More clearly point out the speed cost and the alternative of installing stub packages directly
=> Clarify docs surrounding install-types

mypy/subtypes.py, test-data/unit/check-classes.test, test-data/unit/check-selftype.test
=> Fix and optimise overload compatibility checking

mypy/checker.py, mypy/fastparse.py, mypy/message_registry.py, mypy/nodes.py, mypy/strconv.py, mypy/treetransform.py, mypyc/irbuild/statement.py, test-data/unit/check-python311.test, test-data/unit/fixtures/exception.pyi
Ref #12840 
It looks like from the point of view of type checking support is quite easy. Mypyc support however requires some actual work, so I don't include it in this PR.
=> Add support for exception groups and except*

mypy/checker.py, mypy/checkexpr.py, mypy/plugins/enums.py, mypy/typeops.py, test-data/unit/check-enum.test
Fixes #12109.
The original issue reported that the bug had to do with the use of the `--follow-imports=skip` flag. However, it turned out this was a red herring after closer inspection: I was able to trigger a more minimal repro both with and without this flag:
```python
from enum import Enum
class Foo(Enum):
a = []  # E: Need type annotation for "a" (hint: "a: List[<type>] = ...")
b = None
def check(self) -> None:
reveal_type(Foo.a.value)  # N: Revealed type is "<partial list[?]>"
reveal_type(Foo.b.value)  # N: Revealed type is "<partial None>"
```
The first two `reveal_types` demonstrate the crux of the bug: the enum plugin does not correctly handle and convert partial types into regular types when inferring the type of the `.value` field.
This can then cause any number of downstream …
=> Fix crash with PartialTypes and the enum plugin

misc/upload-pypi.py
Tried to make it in a way such that we can add more rules for platforms we want to filter out in the future.
Tested it with `python3 misc/upload-pypi.py --dry-run 0.990`
Fixes #14026
=> Filter out wasm32 wheel in upload-pypi.py

mypy/constraints.py, mypy/types.py, test-data/unit/check-recursive-types.test
Fixes #14031 
It turns out premature optimization is the root of all evil. (It turns out this costs us less than 1% time on self-check).
=> Fix crash on inference with recursive alias to recursive instance

mypyc/codegen/emit.py, mypyc/test/test_emit.py, mypyc/test/test_emitfunc.py, mypyc/test/test_emitwrapper.py
By using tabs instead of spaces for indentation in the emitted C code we are able to reduce the file size by almost 9%:
| File | Size |
|------|------|
| `build/__native_74cdc94b2b24dafac2a2.c` (spaces) | 86.5MB |
| `build/__native_74cdc94b2b24dafac2a2.c` (tabs)   | 79.6MB |
For this particular file we save about 6.9MB, or 8.7%.
I checked, and this has no effect on the compilation speed, which is to be expected. At the very least opening these auto generated files inside an editor will be faster, even if the compilation isn't any faster.
I am interested in making mypy/mypyc faster, and this seemed like a low-hanging fruit that could be beneficial.
=> [mypyc] Use tabs instead of spaces in emitted C code

mypy/build.py, mypy/dmypy_server.py, mypy/modulefinder.py, mypy/server/update.py, mypy/test/testcmdline.py, test-data/unit/cmdline.test
#13768 had a bug so that errors were sometimes silenced in files that were under a 
directory in `sys.path`. `sys.path` sometimes includes the current working directory, 
resulting in no errors reported at all. Fix it by always reporting errors if a file was passed 
on the command line.
When using import following errors can still be ignored, which is questionable, but
this didn't change recently so I'm not addressing it here.
Fixes #14042.
=> Don't ignore errors in files passed on the command line

docs/source/command_line.rst
=> Update --no-warn-no-return docs for empty body changes

mypy/report.py
Fixes #14046. Similar to #13733
Best reviewed with hide whitespace.
=> Fix another crash with report generation on namespace packages

mypy/checker.py, test-data/unit/check-functions.test
Fixes #14027 (issue was surfaced by #13509)
=> Fix crash with function redefinition

docs/source/error_code_list2.rst, mypy/checker.py, mypy/errorcodes.py, mypy/message_registry.py, mypy/semanal.py, mypyc/test-data/irbuild-statements.test, test-data/unit/check-errorcodes.test
Add a separate error code for `truthy-iterable`.
`Iterable` does not implement `__len__`, so passing a `Generator` would always evaluate to `true`. Suggest `Collection` as alternative.
In most cases this isn't an issue as the function is often called with `list` anyway. However, the dedicated check can pinpoint subtle errors that might get unnoticed otherwise.
=> Add error-code for `truthy-iterable`

mypy/checker.py, mypy/constraints.py, mypy/messages.py, mypy/subtypes.py, mypy/test/testtypegen.py, test-data/unit/check-protocols.test, test-data/unit/fine-grained-inspect.test, test-data/unit/fixtures/tuple.pyi, test-data/unit/lib-stub/builtins.pyi
Fixes https://github.com/python/mypy/issues/10976
Fixes https://github.com/python/mypy/issues/10403
This is quite straightforward. Note that we will not allow _arbitrary_ attributes on functions, only those that are defined in `types.FunctionType` (or more precisely `builtins.function` that is identical). We have a separate issue for arbitrary attributes https://github.com/python/mypy/issues/2087
=> Support additinal attributes in callback protocols

mypy/checker.py, test-data/unit/check-incremental.test
Fixes #9654
Seems to be quite straightforward. Erased types should never be stored on variables, it is just a temporary thing for nested generic calls.
=> Fix crash on partial type inference within a lambda

mypy/checker.py, mypy/join.py, mypy/meet.py, test-data/unit/check-classes.test, test-data/unit/check-isinstance.test, test-data/unit/check-type-promotion.test, test-data/unit/fixtures/primitives.pyi
Fixes #14030 
FWIW this looks like an acceptable compromise after discussions in the issue. Also it is easy to implement. Let's see what `mypy_primer` will show.
=> Don't consider a branch unreachable if there is possible promotion

mypy/nodes.py
IIRC `ImportedName` was used by old semantic analyzer, that is long gone now.
cc @JukkaL
=> Delete unused symbol node

mypy/dmypy_server.py, test-data/unit/daemon.test
Fixes: #14101
This prevents non-error messages (e.g. warnings) from causing dmypy to return exit code 1.
=> Prevent warnings from causing dmypy to fail

mypy/messages.py, mypy/subtypes.py, test-data/unit/check-protocols.test
Fixes #10289
Unless I am missing something, this indeed looks safe, so I am going to allow this.
cc @JukkaL
=> Allow class variable as implementation for read only attribute

mypy/messages.py, mypy/nodes.py, mypy/report.py, mypy/semanal.py, mypy/semanal_typeargs.py, mypy/stats.py, mypy/strconv.py
When I was working on a different PR for Mypy, I came across these functions:
```python
def get_line(self) -> int:
"""Don't use. Use x.line."""
return self.line
def get_column(self) -> int:
"""Don't use. Use x.column."""
return self.column
```
So I just went ahead and removed them.
=> Remove `get_line()` and `get_column()` functions

mypy/checkexpr.py, test-data/unit/check-selftype.test
Fixes #12344 
FWIW this is unsafe (since we don't know where the mixin will appear in the MRO of the actual implementation), but the alternative is having annoying false positives like this issue and e.g. https://github.com/python/mypy/issues/4335
cc @JukkaL
=> Allow super() for mixin protocols

mypy/applytype.py, mypy/checker.py, mypy/checkexpr.py, mypy/constraints.py, mypy/expandtype.py, mypy/typevartuples.py, test-data/unit/check-typevar-tuple.test
This requires handling more cases in the various places that we previously modified to support *args in general. We also need to refresh the formals-to-actuals twice in checkexpr as now it can happen in the infer_function_type_arguments_using_context call.
The handling here is kind of asymmetric, because we can convert prefices into positional arguments, but there is no equivalent for suffices, so we represent that as a Tuple[Unpack[...], <suffix>] and handle that case separately in some spots.
We also support various edge cases like passing in a tuple without any typevartuples involved.
=> Handle prefix/suffix in typevartuple *args support

mypy/checkexpr.py, test-data/unit/check-parameter-specification.test
Fixes #13903 
The fix is straightforward, the formal to actual map needs to be refreshed twice, after both using external _and_ internal type context.
=> Fix crash during ParamSpec inference

mypy/checkmember.py, mypy/types.py, test-data/unit/check-selftype.test
Fixes #14108 
This fixes both new and old style of working with self types. After all I fixed the new style by simply expanding self type, then `bind_self()` does its job, so effect on the instance will be the same.
I had two options fixing this, other one (that I didn't go with) is making the callable generic in new style, if it appears in `ClassVar`. This however has two downsides: implementation is tricky, and this adds and edge case to an existing edge case. So instead I choose internal consistency within the new style, rather than similarity between old and new style.
=> Correctly support self types in callable ClassVar

mypy/messages.py, mypy/subtypes.py, test-data/unit/check-protocols.test, test-data/unit/fixtures/type.pyi
Fixes #10482 
This is not very principled, but should work except people will want to explicitly check some metaclass `__call__`.
=> Fix class objects falling back to metaclass for callback protocol

.github/workflows/mypy_primer_comment.yml
=> mypy_primer: truncate per-project output

mypy/semanal.py, test-data/unit/pythoneval.test
Fixes #12483
Fixes https://github.com/python/typeshed/issues/7564
Ref #12841
The fix is straightforward. I can't use a unit test for this because there are some builtins fixtures that don't have tuple, so I can't do version check.
=> Correctly handle Enum name on Python 3.11

docs/source/generics.rst
- Added missing cast import
- Changed revealed type
Just changed documentation
=> Update code example in "Declaring decorators"

mypy/type_visitor.py, mypy/typeanal.py, test-data/unit/reports.test
See https://github.com/python/mypy/pull/14130 for context.
Btw it looks like these `Any` reports are quite broken in general. Some issues I found:
* Many types are reported twice (even non-recursive)
* Explicit `Any` in alias r.h.s are not counted (because of reckless `res = make_any_non_explicit(res)` in semanal.py)
* For generic aliases we count their r.h.s. as containing `Any` from omitted generics
I tried to fix these things, but it is not trivial, so maybe we can do it later in a separate PR.
=> Fix type query for recursive aliases

mypy/checkmember.py, test-data/unit/check-incremental.test
Fixes #14137 
Fix is trivial, I just forgot to call `super()` in one of my previous PRs.
cc @hauntsaninja @JukkaL
=> Fix incremental crash on generic function appearing in nested position
