python/mypy

mypy/test/testtypes.py
mypy/test/typefixture.py
mypy/types.py

While working on another PR I noticed that current behavior of `has_recursive_types()` is inconsistent, it returns `False` is there is a recursive type nested as an argument to a generic non-recursive alias. I wasn't able to find any situation where this actually matters, but I think it is better if this function behaves consistently.

Make is_recursive and has_recursive_types() more consistent

---

docs/source/generics.rst

The documentation shows an example in the ["Decorator factories"](https://mypy.readthedocs.io/en/stable/generics.html#decorator-factories) section and it looks like this:
```python
def atomic(__func: Callable[..., Any] = None, *, savepoint: bool = True):
```
However, if you save the file and run mypy, it complains about the previous line:
error: Incompatible default for argument "__func" (default has type "None", argument has type "Callable[..., Any]")  [assignment]
note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
This change adds Optional around `Callable[..., Any]]` which avoids the above error message.

Doc: Add Optional in Decorator factories

---

mypy/checker.py
mypy/semanal.py
mypy/stubtest.py
mypy/treetransform.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-classes.test
test-data/unit/check-python38.test
test-data/unit/check-selftype.test
test-data/unit/semanal-types.test

Fixes #5865 
Looks quite easy and safe, unless I am missing something. Most changes in the diff are just moving stuff around.
Previously we only applied argument types before type checking, but it looks like we can totally do this in semantic analyzer. I also enable variable annotated as `type` (or equivalently `Type[Any]`), this use case was mentioned in the comments.
This PR also accidentally fixes two additional bugs, one related to type variables with values vs walrus operator, another one for type variables with values vs self types. I include test cases for those as well.

Allow function arguments as base classes

---

mypy/partially_defined.py
test-data/unit/check-partially-defined.test
test-data/unit/check-python310.test

This adds support for unreachable blocks in `partially-defined` check.
Currently, this only supports blocks that are detected as unreachable during semantic analysis (so mostly stuff like python version, etc.).
This doesn't support more advanced cases (see #13926 for an example what's not covered).
Closes #13929

[partially defined] handle unreachable blocks

---

mypy/build.py
mypy/errorcodes.py
mypy/messages.py
mypy/partially_defined.py
test-data/unit/check-partially-defined.test

This implements a check when a variable is defined before use. Something like:
```python
def foo() -> None:
x = y
y: int = 1
```
I've combined this check with the partially defined check but added a separate error code. It's probably worth cleaning it up and making the separation between the two checks a bit more clear. I can do this in a follow-up PR.
Fixes #14124

Detect variables that are used before they're defined

---

test-requirements.txt

Windows wheels for Python 3.11 are not included in the release, and `cibuildwheels` cannot build them, this causes mypy wheel build failure on Windows for Python 3.11, see e.g. https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/3527396237/jobs/5916408981
We need to do this until https://github.com/lxml/lxml/pull/360 is released (hopefully in next few weeks).
cc @hauntsaninja @JukkaL

Don't install lxml on Windows on Python 3.11

---

mypy/meet.py
mypy/subtypes.py

This gives around 1% speed-up on self check, and may give even more for code that is heavy on overloads.

Simplify callable overlap logic

---

mypy/build.py
mypy/checker.py
mypy/checkexpr.py
mypy/main.py
mypy/options.py
mypy/util.py

This should help with the investigation of tricky performance regressions like https://github.com/python/mypy/issues/13821.
I tried to implement in such a way that it will give minimal impact when not used (since I am touching a hot method).

Add intenal flag for per-line type checking peformance

---

docs/source/generics.rst
mypy/checker.py
mypy/checkexpr.py
mypy/erasetype.py
mypy/expandtype.py
mypy/fixup.py
mypy/mixedtraverser.py
mypy/nodes.py
mypy/semanal.py
mypy/semanal_typeargs.py
mypy/semanal_typeddict.py
mypy/server/astdiff.py
mypy/server/astmerge.py
mypy/subtypes.py
mypy/test/testtypes.py
mypy/test/typefixture.py
mypy/typeanal.py
mypy/types.py
mypy/typetraverser.py
test-data/unit/check-generics.test
test-data/unit/check-isinstance.test
test-data/unit/check-literal.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-type-aliases.test

Fixes #11855 
Fixes #7084
Fixes #10445
Should fix #4987
After thinking about this for some time, it looks like the best way to implement this is by switching type aliases from unbound to bound type variables. Then I can essentially simply share (or copy in one small place, to avoid cyclic imports) all the logic that currently exists for `ParamSpec` and `Concatenate` in `expand_type()` etc.
This will also address a big piece of tech debt, and will get some benefits (almost) for free, such as checking bounds/values for alias type variables, and much tighter handling of unbound type variables.
Note that in this PR I change logic for emitting some errors, I try to avoid showing multiple errors for the same location/reason. But this is not an essential part of this PR (it is just some test …

Support ParamSpec variables in type aliases

---

mypy/checker.py
mypy/checkexpr.py
mypy/nodes.py
mypy/semanal.py
mypy/server/aststrip.py
mypy/strconv.py
mypy/traverser.py
mypy/treetransform.py
test-data/unit/check-type-aliases.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test

Fix aliases like this and other aliases involving new-style unions:
```
A = type[int] | str
```
Fixes #12392. Fixes #14158.

Fix issues with type aliases and new style unions

---

mypy/checkexpr.py
test-data/unit/check-type-aliases.test
test-data/unit/pythoneval.test

Fix type aliases like these:
```
T = tuple[int, str]
```
Type applications involving fixed-length tuples still don't fully work. The inferred type is a variable-length tuple when constructing a tuple using a type application, e.g. `tuple[int, str]((1, ""))`. This seems a pretty low-priority issue, whereas the type alias use case seems common.
Most of the work was by @sobolevn originally in #12134. I just finished it up.
Fixes #11098.

Fix type aliases with fixed-length tuples

---

mypy/plugins/attrs.py
test-data/unit/check-attr.test

Fixes #6715 
Fix is straightforward, currently we assume that if we have a variable in MRO, and its name appears in current class, it is from this class, which in fact may not be the case when a variable is overridden with a property or method.
I also add a test case for a crash that was previously reported in the same issue but is already (accidentally?) fixed.

Fix crash on overriding with frozen attrs

---

mypy/partially_defined.py
test-data/unit/check-partially-defined.test

We previously used `use-before-def` code here but this commit switched it to use `partially-defined`. This particular check generates a lot of false positives, in particular around loops of the form:
```python
for i in range(2)
if i == 0:
x = 1
else:
y = x
```
While in an ideal world mypy has no false positives, it's not feasible for us to handle this correctly in the short-term. Moving this to partially-defined error code makes the `use-before-def` have a much lower false positive rate, which is a plus. Unfortunately, `partially-defined` will always have a higher false positive rate. This means that if we enable it by default, lots of people will disable this check. We want to avoid the same thing happening to use-before-def check.
See [this …

Switch error code used to report vars defined in different branch

---

mypy/build.py
mypy/errorcodes.py
mypy/partially_defined.py
test-data/unit/check-partially-defined.test

These are the issues that I've found using mypy-primer.
You should be able to review this PR commit-by-commit. Each commit includes the relevant tests:
- Process imports correctly
- Support for function names
- Skip stub files (this change has no tests)
- Handle builtins and implicit module attrs (e.g. `str` and `__doc__`)
- Improved support for lambdas.

Implement miscellaneous fixes for partially-defined check

---

mypy/evalexpr.py
mypy/stubtest.py
mypy/test/teststubtest.py

Helps with python/typeshed#8988.

stubtest: if a default is present in the stub, check that it is correct

---

mypy/build.py
mypy/partially_defined.py
test-data/unit/check-partially-defined.test

`else` in loops is executed if the loop didn't exit via a raise, return, or a break. Therefore, we should treat it execution as unconditional if there is not a break statement.
This PR also improves error messages in `else`, reporting them as "may be undefined" instead of "used before definition"
Fixes #14097

[partially defined] rework handling of else in loops

---

mypy/partially_defined.py
test-data/unit/check-partially-defined.test

In order to know to use `partially-defined` code vs `use-before-def`, we had to check if a variable is defined in any branches, not just in the current one.
This would cause an error to be reported as a `use-before-def` and not `partially-defined` code.

[partially defined] use correct error code in nested if statements

---

mypy/build.py
mypy/partially_defined.py
test-data/unit/check-partially-defined.test

We should not check untyped functions unless --check-untyped-defs is set.
This is part of the reason why #14166 saw so many new errors reported in open source projects.

[partially defined] respect check-untyped-defs flag

---

mypy/checkexpr.py
test-data/unit/check-super.test

Fix a crash when incorrect super() is used outside a method

---

mypy/semanal.py
test-data/unit/check-classes.test
test-data/unit/check-dataclasses.test

Fixes #14199 
This is straightforward, just use the same logic as for regular (user defined) type variables.

Fix crash in Self type on forward reference in upper bound

---

mypy/constraints.py
test-data/unit/check-parameter-specification.test

Most types can be considered as callables, constructing the type itself. When a constraint was created for a ParamSpec variable, the return type would be set to NoneType, which conflicts with assumptions that CallableType makes when it is the constructor of another type, crashing mypy. This patch replaces the return type by UninhabitedType instead, which stops CallableType from considering itself as a constructor.

Fix ParamSpec constraint for types as callable

---

docs/source/running_mypy.rst

Fix typo - remove an unneeded period
https://mypy.readthedocs.io/en/stable/running_mypy.html#ignore-missing-imports

[docs] Update `running_mypy.rst` - fix typo

---

mypy/partially_defined.py
test-data/unit/check-partially-defined.test

Previously, we would ignore any class definitions and would fail to detect undefined classes and functions. This updates the logic to handle them.
Closes #686

[use before def] handle class and function definitions

---

mypy/stubtest.py

We have multiple of these in `typeshed`: https://github.com/python/typeshed/search?q=__warningregistry__

[stubtest] Add `__warningregistry__` to the list of ignored module dunders

---

mypy/partially_defined.py
test-data/unit/check-partially-defined.test

This is a workaround until we implement better handling for variables undefined in global scope (see #14213).
We treat `global/nonlocal` as a variable declaration. I've included test cases that should fail in the future once we implement the check properly.

[partially defined] fix false positive with global/nonlocal vars

---

mypy/partially_defined.py
test-data/unit/check-partially-defined.test

The goal of partially-defined check is to detect variables that could be undefined but semantic analyzer doesn't detect them as undefined. In this case, a variable was defined in a branch that returns, so semantic analyzer considered it defined when it was not.
I've discovered this when testing support for try/except statements (#14114).

[partially defined] fix a false-negative with variable defined in a skipped branch

---

mypy/checker.py
test-data/unit/check-async-await.test
test-data/unit/check-statements.test

Fix false negatives involving Unions and generators or coroutines

---

mypy/copytype.py
mypy/nodes.py
mypy/semanal.py
mypy/test/typefixture.py
mypy/treetransform.py
mypy/tvar_scope.py
mypy/typeanal.py
mypy/types.py
mypy/typevars.py
test-data/unit/semanal-errors.test
test-data/unit/semanal-types.test

We want to eventually decomission the use of TypeList for constraints/expanded values of TypeVarTupleTypes. In order to do that we will need a reference to the tuple fallback. All the places we currently construct these TypeLists for the use in variadic generics have access to a TypeVarTupleType, so putting the tuple fallback into the typevar type is a reasonable way to make that information accessible where we need it.
In order to get it into the type, we first put it into the expr by making a symbol table lookup in semanal.

Give TypeVarTupleType a fallback

---

mypy/stubtest.py
mypy/test/teststubtest.py

Right now `stubtest` gives this error for `__all__`:
```
error: passlib.handlers.oracle names exported from the stub do not correspond to the names exported at runtime. This is probably due to an inaccurate `__all__` in the stub or things being missing from the stub.
Stub: in file /Users/sobolev/Desktop/typeshed/stubs/passlib/passlib/handlers/oracle.pyi
Names exported in the stub but not at runtime: ['oracle10', 'oracle11']
Runtime:
Names exported at runtime but not in the stub: ['oracle10g', 'oracle11g']
```
(Context: there's a real error in `__all__`: https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/passlib/handlers/oracle.py#L18)
The only way to ignore it is to ignore the whole module. This is not right.
We need to be able to ignore just `some_module.__all__`.

[stubtest] Error related to `__all__` must have it in the error path

---

mypy/main.py

Previously --fast-exit would actually disable the fast_exit option. Now it behaves as expected (a no-op, since fast exit is enabled by default).

Fix --fast-exit argument

---

README.md

See https://github.com/lbolla/emacs-flycheck-mypy#readme

Flycheck-mypy is deprecated. Its functionality was merged in Flycheck

---

README.md
docs/source/index.rst
setup.py

Ref #13685 
cc @Michael0x2a @JukkaL @hauntsaninja

Stop saying mypy is beta software

---

mypy/config_parser.py
test-data/unit/check-custom-plugin.test
test-data/unit/cmdline.test

Now these two samples are identical:
```ini
[mypy]
enable_error_code =
truthy-bool,
redundant-expr,
unused-awaitable,
ignore-without-code
```
and
```ini
[mypy]
enable_error_code =
truthy-bool,
redundant-expr,
unused-awaitable,
ignore-without-code,
```
I've covered some of the changed values, but not all (they are identical - no need to create so many slow tests).
I've also checked `pyproject.toml`. It does not have this problem: it uses `[]` to create arrays, so no trailing commas are used there.

[conf] Allow trailing commas in `ini` configuration of multiline values

---

mypyc/analysis/attrdefined.py
mypyc/codegen/emit.py
mypyc/codegen/emitclass.py
mypyc/codegen/emitfunc.py
mypyc/codegen/emitwrapper.py
mypyc/ir/func_ir.py
mypyc/ir/ops.py
mypyc/ir/rtypes.py
mypyc/irbuild/builder.py
mypyc/irbuild/env_class.py
mypyc/irbuild/ll_builder.py
mypyc/test-data/run-i64.test
mypyc/transform/exceptions.py
mypyc/transform/uninit.py

A tuple such as `tuple[i64, i64]` can't have a dedicated error value, so use overlapping error values, similarly to how we support plain native integers such as `i64`.
For a heterogeneous tuple such as as `tuple[i64, str]` we attempt to store the error value in the smallest item index where the value type supports error values (1 in this example).
This affects error returns, undefined attributes, default arguments and undefined locals.

[mypyc] Support tuples of native ints

---

mypy/constraints.py
mypy/expandtype.py
mypy/test/testconstraints.py

Now that the fallback is available, we can construct TupleTypes instead of TypeLists which will simplify constraint solving as it won't need to know to match TupleTypes with TypeLists.

Replace TypeList in constraints with TupleType

---

.github/workflows/test.yml
tox.ini

Last time i checked it wasn't the 1960's. So I think the CI could be colorized.
Configured pytest, tox, mypy(#7771) and pip¹ (I already already colorized black and isort when I initially added them)
1: Pip doesn't work yet https://github.com/pypa/pip/issues/10909, so this is just a placedholder for when it (hopefully) soon will.

(🎁) canwecolor🚀

---

mypy/build.py
mypy/errorcodes.py
mypy/messages.py
mypy/partially_defined.py
mypy/server/update.py
test-data/unit/check-possibly-undefined.test
test-data/unit/check-python310.test
test-data/unit/check-python38.test

Rename `partially-defined` to `possibly-undefined` and `use-before-def` to `used-before-def`.
Ref #14226

Rename `partially-defined` error codes

---

mypy/stubtest.py

This came up in https://github.com/python/typeshed/pull/9347

stubtest: catch BaseException on imports

---

mypy/stubtest.py
mypyc/common.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/getargsfast.c
mypyc/lib-rt/pythonsupport.h

`#if PY_MAJOR_VERSION >= 3 && PY_MINOR_VERSION >= 7`
For example, this is true for Python 3.7-3.11 but also true for Python 4.7-4.11. Instead, `PY_VERSION_HEX` should be used.
https://docs.python.org/3.11/c-api/apiabiversion.html
```c
/* Version as a single 4-byte hex number, e.g. 0x010502B2 == 1.5.2b2.
Use this for numeric comparisons, e.g. #if PY_VERSION_HEX >= ... */
```
https://github.com/python/cpython/blob/2e279e85fece187b6058718ac7e82d1692461e26/Include/patchlevel.h#L29-L30
---
Remove compatibility code that only applied to EOL and unsupported Python versions (<= 3.6).

Replace unsafe PY_*_VERSION comparisons to fix for Python 4.0

---

.github/workflows/test.yml
mypyc/test/test_run.py
test-requirements.txt

Adding a fail-able 3.12-dev job to the CI

(🎁) Add 3.12-dev to CI

---

mypy/partially_defined.py
test-data/unit/check-possibly-undefined.test

A similar case was addressed in #14176 but I missed the part where it doesn't need to be defined in a different branch. This makes the fix more complete.

[used-before-def] fix false positive inside loop

---

mypy/partially_defined.py
test-data/unit/check-possibly-undefined.test

In particular, ran into an issue with an `if TYPE_CHECKING` case, so I added a test for that.

[undefined vars] skip visiting unreachable else clauses

---

mypy/semanal.py
test-data/unit/check-generics.test
test-data/unit/lib-stub/typing_extensions.pyi

This PR only adds the existing `TypeVar` support for the `typing_extensions` variant.
I.e. it does not include support for `default` or `infer_variance`.
Fixes #14312

Add basic support for `typing_extensions.TypeVar`

---

mypy/build.py
mypy/main.py
mypy/options.py

Currently, `mypy_primer` sets `--cache-dir=/dev/null` which disables cache generation. This can result in errors being missed which would normally come up during  `tree.serialize()`. Removing `--cache-dir=/dev/null` isn't practical.
This PR adds a new debug / test option `--debug-serialize` which runs `tree.serialize()` even if cache generation is disabled to help detect serialize errors earlier.
**Refs**
* #14137
* https://github.com/hauntsaninja/mypy_primer/pull/54#pullrequestreview-1187145602
cc: @hauntsaninja

Add `--debug-serialize` option

---

.github/workflows/mypy_primer.yml

Enable the `--debug-serialize` option to help catch issues during serialization which would normally be skipped by mypy_primer.
Followup to #14155

Enable `--debug-serialize` for mypy_primer

---

mypy/types.py

The implementation copied lots of callable types even when not using
the new feature, which was expensive. Now we only generate a copy if a
callable actually uses TypedDict types for **kwds.
This made self check 7-8% faster (when compiled with -O0).
The original implementation was in https://github.com/python/mypy/pull/13471.

Optimize implementation of TypedDict types for **kwds

---

mypy/subtypes.py

Avoid the use of a nested function, which are a bit slow when compiled with mypyc. Also avoid a callable value and instead call a function directly, which allows using faster native calls.
Based on a quick experiment, this speeds up self check by about 3%.
This addresses some of the slowdown introduced in #13303.

Optimize type parameter checks in subtype checking

---

mypy/subtypes.py

Mypyc isn't good at compiling nested functions, and this one was in one of the hottest code paths in all of mypy. The nested function wasn't even used that often, but mypyc would still construct a closure object every time.
This adds some code duplication, but it's well worth it. Amazingly, this speeds up self-check by about 10%, if my measurements are to be trusted!
This addresses some of the slowdown introduced in #13303. #14324 addresses another related slowdown.

Optimize subtype checking by avoiding a nested function

---

mypyc/codegen/emit.py
mypyc/test/test_emit.py
mypyc/test/test_emitfunc.py
mypyc/test/test_emitwrapper.py

This reverts commit dbcbb3f5c3ef791c98088da0bd1dfa6cbf51f301.
The indentation in generated code is now inconsistent if using 4-space tabs. We should either use tabs or spaces consistently everywhere, since we can't expect everybody to have the same tab width.
The broken indentation can be seen by compiling a hello world program and opening it in an editor configured to use 4-space tabs.
Since there is a lot of code in mypyc that assumes a 4-space indentation, fixing it all is probably only feasible by normalizing the indentation during the emit phase. However, the normalization step might actually slow down compilation slightly, whereas the intent of the original change to improve efficiency, so this change may ultimately be impractical. In the future we should make it possible to …

Revert "[mypyc] Use tabs instead of spaces in emitted C code (#14016)"

---

docs/source/type_narrowing.rst

The former does not render properly in the docs
This is a tiny follow up from https://github.com/python/mypy/pull/14246#issuecomment-1336467793

Switch :py:func:`type` to py:class:`type` in type_narrowing.rst

---

mypy/checker.py
mypy/checkexpr.py
mypy/semanal_shared.py
mypy/typeanal.py
mypy/types.py

I measured a 1% performance improvement in self check.

Change various type queries into faster bool type queries

---

mypy/build.py
mypy/checkexpr.py
mypy/constraints.py
mypy/mro.py
mypy/server/astmerge.py
mypy/server/aststrip.py
mypy/server/deps.py
mypy/server/update.py
mypy/solve.py
mypy/subtypes.py
mypy/test/testdeps.py
mypy/typestate.py

This helps mypyc, since accessing mutable attributes of singleton instances is faster than accessing class variables. The implementation is also arguably a bit cleaner.
This seems performance-neutral or a very minor optimization, but if we continue to add attributes to TypeState, this can help.

Refactor TypeState into a singleton class

---

mypy/checkexpr.py

Mypyc can't optimize context managers yet, so it's best to avoid them in hot code paths.
This sacrifices some code quality for a considerable perf gain. This improved self-check performance by 4%.

Avoid the use of a context manager in hot code path

---

misc/perf_compare.py

The script compiles some mypy commits in parallel and then measures how long each version takes to self-check a specific mypy commit. It measures the performance 15 times for each commit and takes the average.
Based on some experiments, the noise floor on my Linux desktop is about 0.5% to 1.0%. Any difference above 1.0% is likely significant, I believe. For differences between 0.5% and 1.0% it makes sense to repeat the measurement a few times.
The interesting part of the output looks something like this:
```
...
=== Results ===
145d8a41b17ab1ba8707589be9cb5d56bbebd0ea 8.207s (0.0%)
145d8a41b17ab1ba8707589be9cb5d56bbebd0ea~1 8.105s (-1.2%)
```

Tool to compare performance of any number of mypy commits/branches

---

docs/source/additional_features.rst

The docs build is currently failing on `master`: see e.g. https://github.com/python/mypy/actions/runs/3748461486/jobs/6365827914.
It looks like it was broken by the release of `attrs` 22.2.0 earlier today. Specifically, it looks like https://github.com/python-attrs/attrs/commit/1bb28648248e1bed63c1c6b077e7fe4b8260efc8 broke mypy's docs build.
I think this fixes things.

Fix docs build

---

mypy/stubtest.py
mypy/test/teststubtest.py

Stubtest currently has both false-positives and false-negatives when it comes to verifying constants in the global namespace of a module.
The import of `string.ascii_letters` is an implementation detail, but stubtest will complain about it missing from the stub:
```python
from string import ascii_letters
```
`IMPORTANT_REGEX` is defined in the module, but stubtest will erroneously conclude (on Python 3.10+) that the constant has been imported from another module, due to the fact that `IMPORTANT_REGEX.__module__` is `"re"`:
```python
import re
IMPORTANT_REGEX = re.compile("foo")
```
This PR fixes the false positive by using `inspect.getsourcelines()` to dynamically retrieve the module source code. It then uses `symtable` to analyse that source code to gather a list of names which are known …

Stubtest: Improve heuristics for determining whether global-namespace names are imported

---

docs/source/common_issues.rst

Improve searchability for module level type ignore errors

---

mypy/meet.py
mypy/typeops.py

This makes the implementation of hasattr() checks faster (introduced in #13544).
In particular, since the `extra_attrs` attribute used for hasattr() checks is usually None, I micro-optimized the codepaths to avoid expensive operations whenever there are no hasattr() checks. 
Also avoid expensive operations on simple unions and order `isinstance` checks so that common types are checked first.
I measured a 2% performance uplift in self-check.

Speed up the implementation of hasattr() checks

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/errors.py
mypy/messages.py

This helps with await-related errors introduced in #12958, in particular, which are expensive to generate. If errors are ignored (e.g. in third-party libraries) or we don't care about the error message, use simpler error message logic. We also often filter out error messages temporarily, so any effort in constructing a nice error message is wasted.
We could skip even more logic, but this should cover many of the important code paths.
This speeds up self check by about 2%.

Avoid slow error message logic if errors not shown to user

---

.github/workflows/mypy_primer_comment.yml

Resolves the following warning:
By using https://github.com/kanga333/comment-hider/releases/tag/v0.4.0

mypy_primer_comment: Resolve node.js 12 actions deprecation warning

---

mypy/types.py

I want to get rid of all the bogus types eventually.

Micro-optimization: avoid Bogus[int] types that cause needless boxing

---

mypy/subtypes.py
mypy/types.py

Enums are exploded into Union of Literal when narrowed.
Conditional branches on enum values can result in multiple distinct narrowing
of the same enum which are later subject to subtype checks (most notably via
`is_same_type`, when exiting frame context in the binder). Such checks would
have quadratic complexity: `O(N*M)` where `N` and `M` are the number of entries
in each narrowed enum variable, and led to drastic slowdown if any of the enums
involved has a large number of values.
Implement a linear-time fast path where literals are quickly filtered, with
a fallback to the slow path for more complex values.
In our codebase there is one method with a chain of a dozen `if` statements
operating on instances of an enum with a hundreds of values. Prior to the
regression it was typechecked in …

subtypes: fast path for Union/Union subtype check

---

mypy/build.py
mypy/server/update.py
test-data/unit/check-flags.test

This one would occur because we set the errors module with global options, instead of per-module override ones.
It only mattered for checks that happened after the partially undefined checks, which (I believe) is only the unused `type: ignore` checks.
This was discovered when updating tests for #14166.
I've also cleaned up the function signature a little.

[undefined vars] fix per-module error code override bug

---

mypy/partially_defined.py
test-data/unit/check-possibly-undefined.test

These errors are already reported by the (new) semantic analyzer. 
I've discovered this while updating unit tests for new semanal in #14166.
Tests are included.

[undefined vars] do not double report errors in class defs

---

mypy/typeanal.py

This makes mypy a bit faster and the implementation seems a little cleaner as well.

Optimization: Remove expensive context manager in type analyzer

---

mypy/types.py

Use lazy initialization to avoid method calls in `__init__`. This allows mypyc to infer more always defined attributes.

Optimization: Enable always defined attributes in Type subclasses

---

test-requirements.txt

Address dependabot alert about security vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2022-40897).

Require setuptools>=65.5.1

---

mypy/semanal.py

Optimization: Avoid a few uses of contextmanagers in semantic analyzer

---

mypyc/irbuild/mapper.py
mypyc/test-data/irbuild-lists.test
mypyc/test-data/irbuild-optional.test

We can sometimes simplify a mypyc RType union, even if the mypy union couldn't be simplified. A typical example is `list[x] | list[y]` which can be simplified to just `list`. Previously this would generate a redundant union `union[list, list]`.

[mypyc] Simplify union types

---

mypyc/irbuild/classdef.py
mypyc/test-data/commandline.test

[mypyc] Improve error message for multiple inheritance.

---

mypy/stubtest.py

There's a small semantic change in this PR (instead of returning `False` if trying to access the `__module__` attribute raises an exception, we now just move on to the next heuristic). But the main purpose of this PR is to make the code more readable, as this function was getting quite hard to understand.

Stubtest: clean up the `_belongs_to_runtime` function

---

mypy/stubtest.py

This error is *only* emitted if `__all__` is included in the stub, so the 'if present' clause is unnecessary

Stubtest: Improve error message for `__all__`-related errors

---

mypy/semanal.py
mypy/type_visitor.py
mypy/typeanal.py

The biggest change is replacing some calls to bound methods with trait method calls, which are faster when compiled.
Also remove an unused argument to TypeVarLikeQuery and make a few misc tweaks.
(Various small optimizations, including these, together netted a 6% performance improvement in self check.)

Some semantic analyzer micro-optimizations

---

mypy/checkexpr.py
mypy/types.py

These are used a lot, so it makes sense to tune them a bit. We now avoid allocations in a common case, when compiled.
(Various small optimizations, including these, together netted a 6% performance improvement in self check.)

Micro-optimize get_proper_type(s)

---

mypy/typeops.py

If there is only one non-union item, there's nothing interesting to do. This is pretty common, and it avoids a fairly expensive `_remove_redundant_union_items` call.

Speed up make_simplified_union

---

mypy/semanal.py
test-data/unit/check-python311.test
test-data/unit/lib-stub/typing.pyi

Add missing check for `typing.Unpack` to fix running with `--python 3.11`.

Fix Unpack imported from typing

---

mypy/messages.py
mypy/semanal.py
test-data/unit/check-kwargs.test
test-data/unit/check-modules.test
test-data/unit/semanal-modules.test

When checking manticore with `--check-untyped-defs`, this is a 4x total speedup from master, from ~320s to ~80s (uncompiled).
I looked into this because of https://github.com/python/typeshed/pull/9443#issuecomment-1369120219

Improve performance for errors on class with many attributes

---

README.md

Now that the site is accessible via HTTPS
- #9919
Fetch the badge using a secure link, especially since this will be used an example for others. Also, non-secure badges will not be shown in some contexts, such as DockerHub, so this makes the example both more secure and more generally useful.

Use secure HTTPS link for Mypy badge

---

mypy/semanal.py
test-data/unit/check-classes.test
test-data/unit/check-functions.test
test-data/unit/check-super.test
test-data/unit/fine-grained.test
test-data/unit/semanal-errors.test

More helpful error for missing self

---

mypyc/irbuild/expression.py
mypyc/test-data/irbuild-basic.test

For example, here the call to ID is simply a no-op at runtime, returning 1 unchanged.
ID = NewType('ID', int)
person = ID(1)
Resolves https://github.com/mypyc/mypyc/issues/958

[mypyc] Compile away NewType type calls

---

docs/source/config_file.rst

#6076 made report generation disable cache but we didn't document it.

Document that report generation disables cache

---

mypy/constraints.py
test-data/unit/check-unions.test

Fix function argument inference for constrained type variables within unions (Fixes #3644).
Handling of constrained type variables of function `filter_satisfiable` of module `constraints` was missing (as was indicated by a removed ToDo).

Fix function argument inference for constrained type variables within unions (Fixes #3644).

---

mypy/util.py

While this doesn't currently appear anywhere in usages, it would be incorrect to say
`0 error found` or `-4 line earlier`

(🐞) fix `util.plural_s` for zero and negative

---

mypy/checkexpr.py
mypy/constraints.py
mypy/expandtype.py
mypy/subtypes.py
mypy/typeanal.py
mypy/types.py
mypy/typevartuples.py
test-data/unit/check-typevar-tuple.test
test-data/unit/semanal-errors.test
test-data/unit/semanal-types.test

Implements support for unpacking varlength tuples from *args, but because it became apparent that several parts of constraints building were doing nearly the same thing for typevar tuples, we begin extracting out some of the logic for re-use. Some existing callsites still should be switched to the new helpers but it is defered to future PRs.

Begin unifying logic for constraint building

---

mypyc/irbuild/classdef.py
mypyc/test-data/run-tuples.test

Take this example:
from typing import NamedTuple
class VTableMethod(NamedTuple):
cls: "ClassIR"
class ClassIR: pass
In irbuild::classdef::add_non_ext_class_attr_ann(), mypyc tries to assign the ClassIR type object to VTableMethod's \_\_annotations\_\_. This causes a segfault as ClassIR won't be initialized and allocated until *after* the NamedTuple is set up.
Fortunately, AssignmentStmt preserves the unanalyzed type (UnboundType). If `stmt.unanalyzed_type.orginal_str_expr` is not None, then we know we're dealing with a forward ref and should just load the string instead.
Unfortunately, it seems difficult (or impossible?) to infer whether an annotation is a forward reference when the annotations future is enabled and the annotation isn't a string.
I guess this fixes …

[mypyc] Don't load forward ref targets while setting up non-ext __annotations__

---

mypy/modulefinder.py

The `FindModuleCache` currently matches files without an extension when `--namespace_packages` is enabled while [the docs](https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules) don't mention that this should be the case. The "near-miss" logic collects candidates for modules, which could correctly include a _directory_ `foo/bar/baz` when looking for `foo/bar/baz`. However, the current logic also picks up a _file_ `foo/bar/baz`. This means that, if both a file `foo/bar/baz` and `foo/bar/baz.py` exist, the first one is actually picked, resulting in unexpected behaviour.
The condition that checks `exists_case` on `foo/bar/baz` should also check that it is indeed a directory by checking that it is not a file. I'm open to different fixes of course, but this …

Don't read scripts without extensions as modules in namespace mode

---

docs/source/error_code_list.rst
docs/source/error_code_list2.rst

This error was enabled by default since its introduction (#13686); document it in the correct section.

Move truthy-function docs from “optional checks” to “enabled by default”

---

mypyc/irbuild/ll_builder.py
mypyc/irbuild/specialize.py
mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-bool.test
mypyc/test-data/irbuild-i64.test
mypyc/test-data/irbuild-int.test
mypyc/test-data/run-bools.test
mypyc/test-data/run-i64.test
mypyc/test-data/run-integers.test
mypyc/test-data/run-strings.test
mypyc/test/test_irbuild.py

Speed up various conversions between bool and integer types. These cases are covered:
* `bool(x)` for various types
* `int(x)` for `bool` and integer arguments
* Implicit coercion from `bool` to an integer type
Support both regular `int` values and native int values.
(Various small optimizations, including these, together netted a 6% performance improvement in self check.)

[mypyc] Faster bool and integer conversions

---

.pre-commit-config.yaml
test-requirements.txt

update black and isort, but not flake8, it requires python 3.8

(🔼) update dependencies

---

mypy/checker.py
mypy/checkexpr.py
mypy/nodes.py
mypy/partially_defined.py
mypy/semanal.py
mypy/server/aststrip.py
mypy/server/deps.py
mypy/strconv.py
mypy/stubtest.py
mypy/test/testsemanal.py
mypy/tvar_scope.py
mypy/typeanal.py
mypyc/irbuild/builder.py
mypyc/irbuild/function.py
test-data/unit/plugins/customentry.py

The type Bogus[X] is treated as Any when the code is compiled with mypyc, while it's equivalent to X when only type checking. They are sometimes used when X is not actually the real type of a value, but changing it to the correct type would be complicated.
Bogus[str] types are pretty awkward, since we are lying to the type checker and mypyc only sees Any types.
An empty fullname is now represented by "" instead of None, so we no longer need a Bogus[str] type.
This might break some plugins, so we should document this in release notes and the relevant issue that tracks plugin incompatibilities.

Refactoring: make the type of fullname str instead of Bogus[str]

---

runtests.py

Give flake8 3 parallel processes. Previously it was sequential. 
Assuming that most developers have a machine with at least 4 cores, we have at least one left for self check, which is run in parallel with lint.

Run lint in parallel in runtest.py

---

mypyc/build.py
mypyc/test-data/commandline.test
mypyc/test/test_commandline.py

For example the warning for "treating generator comprehension as list" doesn't get printed unless there were errors too. This was due to the fact mypyc/build.py was only checking errors.num_errors to decide whether to print messages to STDOUT.
To be honest, the generate_c() logic was pretty messy, so I broke out the message printing logic into a separate helper function and made liberal use of early exits.
Fixes https://github.com/mypyc/mypyc/issues/873#issuecomment-871055474.

[mypyc] Always emit warnings

---

misc/docker/Dockerfile
misc/docker/README.md
misc/docker/build.py
misc/docker/run-wrapper.sh
misc/docker/run.sh

This speeds up running `pytest mypyc/test/test_run.py` by over 3x on a Mac mini M1. Mypy test performance is fairly similar to running natively.
Example of how to use these on macOS:
```
$ colima start -c 8  # Start VM
$ python3 misc/docker/build.py  # Build Ubuntu container with test dependencies
$ misc/docker/run.sh pytest mypyc/test/test_run.py  # Run tests in container
```
Also add a README that documents how to use these.
Closes #14453.

Add scripts for running mypy and mypyc tests inside a Docker container

---

mypy/constraints.py
mypy/test/testconstraints.py

The visit_tuple_type method of the constraints visitor does similar logic to the new helper for building constraints for typevar tuples, so we reimplement it using that. This also fixes a bug that was uncovered in the implementation of the helper.

Re-use constraints helper in constraints visitor

---

mypy/nodes.py
mypyc/irbuild/specialize.py
mypyc/test-data/irbuild-dunders.test

int() and float() calls on native classes can simply call the associated dunder if the RInstance defines it, no need to load the type and call it.
bool() calls were already optimized merely a few days ago, but there wasn't an IRbuild test verifying this so I added one.
---
Follow up to https://github.com/python/mypy/pull/14422. I saw the PR and it reminded me that I had this old patch laying around :)

[mypyc] Optimize int()/float()/complex() on native classes

---

mypy/expandtype.py
test-data/unit/check-typevar-tuple.test

Mainly adds some tests that were previously disabled since they failed, as well as tests for handling prefices. Suffices tests are not added yet because when a suffix is involved we can't use the existing solution since it will construct positional args after *args, when we really need something like `*tuple[*args, <suffix>]` in order to encode this in the type info.
We also refactor out the manipulation of the arg names/kinds/types into its own helper which will make control flow less annoying to deal with.
We are deferring the implementation of suffices until more parts of the PEP are implemented since it doesn't seem as important (e.g. in other parts of the language this is not supported)

Improve CallableType handling with typevar tuples

---

mypy/semanal.py
test-data/unit/check-classes.test

Fixes #14475
The fix is straightforward. We need to use the "guarded accept" at this stage, similar to e.g. `clean_up_bases_and_infer_type_variables()`.

Fix false positive on generic base class with six

---

mypy/semanal.py
test-data/unit/check-recursive-types.test

Fixes #14460
Recursive TypedDicts/NamedTuples defined with call syntax that have item types that look like type applications suffer the same chicken-and-egg problem that recursive type aliases. Fortunately, there is a very simple way to distinguish them without fully analyzing rvalues, this is what this PR does.

Fix recursive TypedDicts/NamedTuples defined with call syntax

---

mypy/semanal.py
test-data/unit/check-async-await.test

Fixes #14345
I also decided to make this error a blocker, since it is essentially a syntax error. (And also a similar error for `yield` is a blocker).

Fix crash in await inside comprehension outside function

---

mypyc/test-data/irbuild-i64.test

This tests already supported functionality to detect regressions.

[mypyc] Add irbuild test case for cast(i64, ...)

---

mypy/expandtype.py
test-data/unit/check-selftype.test

Fixes #14374
It looks like we need to special-case `Self` in `expand_type()` to support it in generics over `TypeVar` with values, since `Self` is the only type variable that can legitimately have other type variables in its upper bound.

Properly expand type in generic class with Self and TypeVar with values

---

mypy/checkmember.py
mypy/nodes.py
mypy/semanal.py
mypy/server/astdiff.py
mypy/subtypes.py
test-data/unit/check-classes.test
test-data/unit/check-incremental.test
test-data/unit/fine-grained.test

Fixes #14254
This essentially re-implements https://github.com/python/mypy/pull/13605 in a simpler way that also works in incremental mode. Also I decided to set `meta_fallback_to_any` in case of errors, to match how we do this for base classes.

Fix crash on Any metaclass in incremental mode

---

mypy/server/astdiff.py
mypy/server/update.py
test-data/unit/fine-grained.test

Ref #14329
This fixes one of the crashes reported in the issue. In fact, using recursive type caught this crash statically, plus another subtle crash in `snapshot_optional_type()`, _without a single false positive_ (I was able to cleanly type also symbol table snapshots, but decided it is not worth the churn since we only ever compare them with `==`, supported by ~every Python object). I feel triumphant :-)

Fix crash in astdiff and clean it up

---

mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-typeddict.test
test-data/unit/check-unions.test
test-data/unit/fixtures/dict.pyi

Fixes #14481 (regression)
Fixes #13274
Fixes #8533
Most notably, if literal matches multiple items in union, it is not an error, it is only an error if it matches none of them, so I adjust the error message accordingly.
An import caveat is that an unrelated error like `{"key": 42 + "no"}` can cause no item to match (an hence an extra error), but I think it is fine, since we still show the actual error, and avoiding this would require some dirty hacks.
Also note there was an (obvious) bug in one of the fixtures, that caused one of repros not repro in tests, fixing it required tweaking an unrelated test.

Properly support union of TypedDicts as dict literal context

---

mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/semanal_newtype.py
mypy/semanal_shared.py
mypy/semanal_typeddict.py
mypy/types.py
test-data/unit/fine-grained-follow-imports.test

Fixes #14329
This fixes the second crash reported in the issue (other one is already fixed). This one is tricky, it looks like it happens only when we bring in a new import cycle in an incremental update with `--follow-import=normal`. To explain the reason, a little reminder of how semantic analyzer passes work:
* Originally, we recorded progress automatically when some new symbol was resolved and added to symbol tables.
* With implementation of recursive types, this mechanism was insufficient, as recursive types require modifying some symbols _in place_, this is why `force_progress` flag was added to `defer()`.
* I was only careful with this flag for recursive type aliases (that were implemented first), for other things (like recursive TypedDicts, etc) I just always passed …

Fix crash in daemon mode on new import cycle

---

mypy/checker.py
test-data/unit/check-errorcodes.test

There are two reasons I'm proposing this change. First, we know that many subclasses of 'object' can be falsy. Second, mypy sometimes simplifies `object | Any` into just `object`. The latter was considered always truthy, while the prior one wasn't. Now both of them are treated consistently. An alternative fix would be to not simplify unions like `object | Any`, but this seems a bit ad hoc.
This only has an effect when the `truthy-bool` error code is explicitly enabled.
Fixes #14480. This doesn't just fix the regression but fixes a more general issue.

Don't consider 'object' always truthy

---

mypy/checkexpr.py
test-data/unit/check-expressions.test
test-data/unit/fixtures/bool.pyi
test-data/unit/fixtures/set.pyi

Don't complain about comparing lists, variable-length tuples or sets if one of the operands has an item type with a custom `__eq__` method.
Fix #14511.

Fix strict equality check if operand item type has custom __eq__

---

test-data/unit/fixtures/attr.pyi
test-data/unit/fixtures/bool.pyi
test-data/unit/fixtures/dict.pyi
test-data/unit/fixtures/exception.pyi
test-data/unit/fixtures/ops.pyi
test-data/unit/fixtures/staticmethod.pyi
test-data/unit/fixtures/tuple.pyi
test-data/unit/fixtures/type.pyi
test-data/unit/lib-stub/__builtin__.pyi

Removed references to `class unicode` under test-data/unit as it is deprecated.

Fixes #14512

---

mypyc/analysis/attrdefined.py
mypyc/codegen/emitfunc.py
mypyc/ir/class_ir.py
mypyc/irbuild/classdef.py
mypyc/irbuild/function.py
mypyc/irbuild/prepare.py
mypyc/irbuild/vtable.py
mypyc/test-data/run-i64.test

Regular trait attributes are accessed via looking up the field offset from a vtable. This doesn't work with native ints, since they may also require access to a defined attributes bitmap, and also looking that up from a vtable would be too complicated.
Work around this may always accessing trait native int attributes using accessor methods. These can raise an exception if an attribute is undefined.
Add empty accessor methods in traits for each attribute with overlapping error values. Also synthesize real accessors in each concrete subclass.
When accessing the attribute using a concrete subclass, still prefer direct field and bitmap access. Only attribute access through a trait type requires accessors to be used.
Work on mypyc/mypyc#837.

[mypyc] Support inheriting native int attributes from traits

---

mypy/checkexpr.py
test-data/unit/check-expressions.test

Fixes regression introduced in #14513.

Fix strict equality with enum type with custom __eq__

---

mypy/semanal.py
mypy/semanal_main.py

Fixes #11860 (?)
Typeshed is currently unable to import Sequence, MutableSequence, or ByteString from collections.abc within builtins.pyi. It seems this is because:
1. In order to analyze `collections.abc`, we first need to analyze `collections`.
2. Since `collections` is a package containing an `__init__.pyi` file, the `add_implicit_module_attrs` function will try adding the `__path__` variable to the symboltable.
3. The `__path__` variable has type `builtins.str`. But str is a subclass of Sequence, which we have not analyzed yet since we're still in the middle of analyzing `collections` and `collections.abc`.
This diff tries repairing this by:
1. Adding `_collections_abc` and `collections.abc` to the set of special-cased core modules we deliberately process early.
2. Modifying …

Adjust SCC setup to enable earlier collections.abc import in typeshed

---

mypy/semanal.py
mypy/semanal_main.py

A backport of #14088 to the `release-1.0` branch.

[1.0 backport] Adjust SCC setup to enable earlier collections.abc import in typeshed

---

mypy/checkexpr.py
test-data/unit/check-inference.test

Fixes: #14548
Fixed case when untyped list item type resolving can lead to an internal crash.
Code to reproduce this issue:
```py
arr = []
arr.append(arr.append(1))
```
Basically, the issue is that after the first resolving of `arr.append` method, `var` is deleted from `partial_types`, and as war as `arr.append` is a nested call we try to delete the same `var` that was already deleted.

[1.0 backport] Fix internal crash when resolve same partial type twice (#14552)

---

mypy/semanal.py
test-data/unit/check-python38.test
test-data/unit/check-statements.test

Fixes #14201
The fix is trivial, turn an assert condition into a blocker error (with message matching Python syntax error). I also add a test case for a crash from the same issue that looks already fixed.

Fix a crash on walrus in comprehension at class scope

---

mypy/constraints.py
test-data/unit/check-protocols.test
test-data/unit/pythoneval.test

Fixes #12553
This looks quite niche, but also it was mentioned recently couple times for a real-life use case: enum classes, and implementation looks simple.

Support protocol inference for Type[T] via metaclass

---

mypy/stubgen.py
test-data/unit/stubgen.test

stubgen: fix crash with PEP 604 union in typevar bound

---

mypyc/irbuild/statement.py
mypyc/test-data/irbuild-try.test
mypyc/test-data/run-generators.test
mypyc/test-data/run-misc.test

Closes mypyc/mypyc#904
Directly calls enter and exit handlers in the case that the context manager is implemented natively.
Unfortunately the implementation becomes a bit more complicated because there are two different places where we call exit in different ways, and they both need to support the native and non-native cases.

[mypyc] Optimize __(a)enter__/__(a)exit__ paths for native case

---

mypy/plugins/attrs.py
test-data/unit/fine-grained-attr.test

Use correct fullname for `__attrs_attrs__` ClassVar to fix issue with warm cache.
Closes #14099
(cherry picked from commit 8e9f89a8498a1242cf1a163f6dbdbd15da54c9a0)

[1.0 backport] Fix `AttrsInstance` protocol check with cache (#14551)

---

mypy/stubgen.py
test-data/unit/stubgen.test

stubgen currently allows a variable to be an alias to another, but only at the module level.
For example: 
```python
def func() -> int:
return 2
aliased_func = func
class Foo:
def meth() -> int:
return 2
aliased_meth = meth
```
produces:
```python
def func() -> int: ...
aliased_func = func
class Foo:
def meth() -> int: ...
aliased_meth: Incomplete   # <--- should be  `aliased_meth = meth`
```
At the class level, these aliased variables are marked as `Incomplete`.   
In my experience, enabling aliases below the top level produces better stubs.  
I'm not sure what the original reservations were around use of these aliases.  If the concerns about class-level aliases are still valid, I can add an option to enable them.

stubgen: Allow aliases below the top level

---

mypy/semanal.py
mypy/typeanal.py

Clean up from https://github.com/python/mypy/pull/14159

Remove dead branch when analysing type aliases

---

mypy/messages.py
test-data/unit/check-incremental.test
test-data/unit/check-modules.test
test-data/unit/check-protocols.test
test-data/unit/fine-grained.test

This makes it consistent with other error messages, e.g.
https://github.com/python/mypy/blob/1a781e7b46fa362718259187ca1f7cdfd9fad136/mypy/semanal.py#L2572-L2574

In error messages, quote just the module's name

---

mypy/types.py
test-data/unit/check-parameter-specification.test

Fixes #14565
The fix looks simple, looks like an obvious omission.

Fix crash on prefixed paramspec with deferral

---

mypy/plugins/common.py
mypy/semanal.py
test-data/unit/check-dataclass-transform.test

The initial implementation of `typing.dataclass_transform` only supported the no-argument `@decorator` form; this adds support for the `@decorator(...)` form supporting the same arguments we support for `dataclasses.dataclass`. This also matches the list of arguments specified in [PEP 681](https://peps.python.org/pep-0681/#decorator-function-and-class-metaclass-parameters).

[dataclass_transform] support class decorator parameters

---

docs/source/cheat_sheet_py3.rst
docs/source/getting_started.rst
docs/source/index.rst
docs/source/running_mypy.rst
docs/source/stubs.rst

For the most part, this shortens the Getting Started page, which was getting a little too long to read comfortably and had caveats that aren't super important.
The cheat sheet does a really great job of "show, don't tell", so recommend that even more aggressively for beginners. The BankAccount example was nice, and the cheat sheet was missing a discussion on inheritance, so move a version of that over there.
Finally, most users of mypy don't need to know the details of typeshed and stub files, especially not when getting started. So reframe as a more generic section about types for third party libraries.
Linking #13681

More improvements to getting started docs

---

mypy/types.py
test-data/unit/check-parameter-specification.test

Fixes #14565
The fix looks simple, looks like an obvious omission.

[1.0 Backport] Fix crash on prefixed paramspec with deferral (#14569)

---

docs/source/common_issues.rst
docs/source/running_mypy.rst

Improve the Common Issues page

---

docs/source/protocols.rst

Improve protocols documentation

---

docs/source/generics.rst

Linking https://github.com/python/mypy/issues/13681

Improve Generics docs page

---

mypy/semanal_enum.py
test-data/unit/check-enum.test

Clarifying this is a mypy limitation, not an Enum() requirement.
Not a true fix, but a workaround for #5317 to avoid confusion (as seen by the many duplicates
Just clarifying a somewhat misleading error message

Improve misleading message in Enum() (#5317)

---

docs/source/error_code_list.rst

Adding documentation for used-before-def check.

[used before def] add documentation

---

misc/sync-typeshed.py

Also use pyproject.toml instead of README.md because there are fewer pyproject.toml in mypy

Update commit hashes in sync-typeshed

---

mypyc/codegen/emitclass.py
mypyc/primitives/generic_ops.py
mypyc/test-data/fixtures/ir.py
mypyc/test-data/irbuild-any.test
mypyc/test-data/run-dunders.test

Pretty simple. Towards https://github.com/mypyc/mypyc/issues/553.

[mypyc] Support __(r)divmod__ dunders

---

mypyc/irbuild/prepare.py
mypyc/test-data/irbuild-classes.test

Require that all the attribute definitions have the same type. Overriding with a different type is unsafe, and we don't want to add runtime checks when accessing an attribute that might be overridden with a different type. If the types would have different runtime representations, supporting that at all would be complicated.
Fixes mypyc/mypyc#970.

[mypyc] Detect if attribute definition conflicts with base class/trait

---

mypyc/irbuild/prepare.py
mypyc/test-data/commandline.test

It would raise even if there were only non-trait bases, leading to this slightly confusing situation:
class A: pass
class B: pass
class C(A, B): pass  # E: Non-trait bases must appear first in parent list
Now the bases must include a non-trait *and* the first base must be a trait to error. This leads to some false-negatives when there's more than one non-trait base, but in that case, it's better to only tell the user that multiple inheritance is not supported.
See also: https://github.com/mypyc/mypyc/issues/826#issuecomment-1383215915

[mypyc] Raise "non-trait base must be first..." error less frequently

---

docs/source/error_code_list.rst
docs/source/error_codes.rst
mypy/errorcodes.py
mypy/errors.py
mypy/messages.py
test-data/unit/check-errorcodes.test

Fixes #2427
If this will cause a too big fallout, we may need to add some special logic, so that `type: ignore[assignment]` will cover `[method-assign]`.

Use a dedicated error code for assignment to method

---

mypyc/codegen/emitclass.py
mypyc/codegen/emitfunc.py
mypyc/common.py
mypyc/doc/using_type_annotations.rst
mypyc/irbuild/function.py
mypyc/irbuild/ll_builder.py
mypyc/lib-rt/dict_ops.c
mypyc/lib-rt/str_ops.c
mypyc/test/test_run.py

Fix a few typos in mypyc's comments and docstrings.

---

mypy/stubgen.py
test-data/unit/stubgen.test

When a PEP 604 Union exists in the runtime, stubgen was generating a `Union[...]` syntax without importing `Union` from `typing`. With this change, stubgen preserves the ` | `-unions in the output.
Fixes #12929
Closes #13428
Ref #12920

[stubgen] Preserve PEP 604 Unions in generated pyi files

---

docs/source/error_code_list.rst
mypy/errorcodes.py
mypy/messages.py
test-data/unit/check-errorcodes.test

The PR that added the error code didn't make into 1.0, so I make it a sub-code, to improve backwards compatibility. Also fixing a type while I am touching this code.

Make typeddict-unknown-key sub-code of typeddict-item

---

docs/source/error_code_list.rst
mypy/checkexpr.py
mypy/plugins/default.py

Ref #7178
This code is used for some TypedDict errors, but `misc` was used for others. I make it more consistent. Also this code looks undocumented, so I add some basic docs.

Consistently use literal-required error code for TypedDicts

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test
test-data/unit/check-dataclasses.test

Small changes prompted by @JukkaL's [comment](https://github.com/python/mypy/pull/14580#discussion_r1098776695) on another review. Splitting this out from that PR since it's unrelated and the messages here have been around for a few years.
This commit specifically adds quotes around Python identifiers in two error messages, and points the error for `"eq" must be True if "order" is True` more directly at the decorator that triggers the error message.

adjust inconsistent dataclasses plugin error messages

---

mypy/traverser.py
test-data/unit/check-python38.test

Fixes #14626.
I believe changing the way that we analyze call expression makes sense (first, we analyze the callee, then we analyze the arguments).

[used before def] correctly handle walrus operator

---

mypy/types.py
test-data/unit/check-typevar-values.test

Fix crash on deferred value constrained TypeVar

---

mypy/traverser.py
test-data/unit/check-python38.test

Fixes #14626.
I believe changing the way that we analyze call expression makes sense (first, we analyze the callee, then we analyze the arguments).

[backport] [used before def] correctly handle walrus operator (#14646)

---

mypy/partially_defined.py
test-data/unit/check-python310.test

The subject needs to be processed outside of match statement and not as part of the first branch.
Fixes #14659.

[used before def] handle walrus declaration in match subject correctly

---

mypy/nodes.py
mypy/plugins/dataclasses.py
mypy/semanal.py
mypy/semanal_main.py
mypy/semanal_shared.py
test-data/unit/check-dataclass-transform.test
test-data/unit/fixtures/dataclasses.pyi

Support dataclass_transforms that use inheritance or metaclasses rather than decorators. This only needs plumbing changes so that we can get the correct metadata for a given class and trigger the dataclasses transform plugin; logic should otherwise remain the same.
The code changes here are a little invasive because of how the dataclasses plugin handles it's "reason" (ie, the AST node that triggered the plugin). Currently it takes a `ClassDefContext` where `reason: Expression`, but in the case of inheritance/metaclass-based transforms, it makes more sense for the class definition itself to be the reason (since the parent class and keyword args are supplied in the class definition itself). To accommodate for this, I refactored the `DataclassTransformer` class to take a `reason: Expression …

[dataclass_transform] support subclass/metaclass-based transforms

---

mypy/nodes.py

This PR removes the unused `imported_names` field from the `ImportAll` node class. Nothing outside of this class references it, so it should be safe to remove.

Remove unused `imported_names` field

---

mypy/semanal_shared.py
test-data/unit/check-dataclass-transform.test

Extends the existing decorator support to include overloads. This doesn't require much extra work: we just update `find_dataclass_transform_spec` to search for the first overload decorated with `dataclass_transform()`.

[dataclass_transform] support function overloads

---

mypy/partially_defined.py
test-data/unit/check-python310.test

[backport] [used before def] handle walrus declaration in match subject correctly

---

mypyc/test-data/irbuild-i64.test

Add 64-bit and 32-bit variants of the test.
Fixes #14633.

[mypyc] Fix test case testI64Cast on 32-bit architectures

---

mypy/plugins/attrs.py
mypy/plugins/common.py
mypy/plugins/dataclasses.py
mypy/semanal.py
mypy/semanal_shared.py
mypy/semanal_typeddict.py
test-data/unit/check-attr.test
test-data/unit/check-dataclass-transform.test
test-data/unit/check-typeddict.test

Follow up on some of the recurring feedback from #14580 and #14657. There are many error messages similar to `X must be True or False.` in MyPy. This commit updates them all to:
- remove the dangling period for consistency with other error messages
- clarify that we need a `True` or `False` literal
- use the `literal-required` error code for consistency with other literal errors
This should have no impact outside of error message formatting.

consolidate literal bool argument error messages

---

mypyc/test-data/irbuild-i64.test

[backport] [mypyc] Fix test case testI64Cast on 32-bit architectures

---

mypy/message_registry.py
mypy/plugin.py
mypy/plugins/dataclasses.py
mypy/semanal.py
test-data/unit/check-dataclass-transform.test

These are analogous to `dataclasses.field`/`dataclasses.Field`.
Like most dataclass_transform features so far, this commit mostly just plumbs through the necessary metadata so that we can re-use the existing `dataclasses` plugin logic. It also adds support for the `alias=` and `factory=` kwargs for fields, which are small; we rely on typeshed to enforce that these aren't used with `dataclasses.field`.

[dataclass_transform] support field_specifiers

---

mypy/fixup.py
mypy/nodes.py
test-data/unit/check-incremental.test

[Backport] Fix generic TypedDict/NamedTuple fixup

---

.github/workflows/test.yml

Debian does build 32bit (on Linux), and there was a recent regression
This PR would have caught #14633 earlier
No change in total CI time [(32 minutes)](https://github.com/python/mypy/actions/runs/4174210017) versus the baseline [(33 minutes)](https://github.com/python/mypy/actions/runs/4166467338)
Confirmation that the new CI test catches the previous error is at https://github.com/python/mypy/actions/runs/4174055572/jobs/7227150570#step:7:44

Test with 32-bit Python

---

mypyc/codegen/literals.py
mypyc/irbuild/builder.py
mypyc/test-data/irbuild-dict.test

An optimization to make iterating over dict.keys(), dict.values() and dict.items() faster caused mypyc to crash while compiling a Union of dictionaries. This commit fixes the optimization helpers to properly handle unions.
irbuild.Builder.get_dict_base_type() now returns list[Instance] with the union items. In the common case we don't have a union, a single-element list is returned. And get_dict_key_type() and get_dict_value_type() will now build a simplified RUnion as needed.
Fixes https://github.com/mypyc/mypyc/issues/965 and probably #14694.

[mypyc] (Re-)Support iterating over an Union of dicts

---

mypy/checker.py
mypy/errors.py
mypy/fastparse.py
mypy/messages.py
mypy/nodes.py
mypy/test/data.py
test-data/unit/check-abstract.test
test-data/unit/check-classes.test
test-data/unit/check-columns.test
test-data/unit/daemon.test
test-data/unit/fine-grained-inspect.test

Modifies arguments parsed from the AST to use the AST's row and column information. Modifies function definitions to not overwrite their arguments' locations. Modifies incorrect override messages to use the locations of arguments instead of the method itself. Modifies tests to expect the new locations.
I'm not sure whether this handles bound arguments correctly; it passes tests but I don't know whether there's some edge case I'm missing.
Fixes #8298.

Give arguments a more reasonable location

---

mypy/checkexpr.py
test-data/unit/check-optional.test

Fixes a bug introduced in https://github.com/python/mypy/pull/14384 wherein a union that includes `None` is no longer treated as a valid right-hand type for the `in` operator in `no-strict-optional` mode. (The reported error is `error: "None" has no attribute "__iter__" (not iterable)  [attr-defined]`).

Fix for bug with `in` operation on optionals in `no-strict-optional` mode

---

.pre-commit-config.yaml
test-requirements.txt

Release notes: https://github.com/PyCQA/isort/releases/tag/5.11.5
This resolves an issue with `pre-commit` and `poetry` which caused the pre-commit `isort` install to fail.
**Edit**: `5.12.0` requires Python 3.8

Update isort to 5.11.5

---

mypy/stubinfo.py

Resolves #14328
Remove the sqlalchemy comment because it's now a PEP 561 package

Suggestions for pandas-stubs and lxml-stubs

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test

`dataclasses` uses a `__dataclass_fields__` attribute on each class to mark that it is a dataclass, and Typeshed checks for this attribute in its stubs for functions like `dataclasses.is_dataclass` and `dataclasses.asdict`.
In #14667, I mistakenly removed this attribute for classes transformed by a `dataclass_transform`. This was due to a misinterpretation of PEP 681 on my part; after rereading the [section on dataclass semantics](https://peps.python.org/pep-0681/#dataclass-semantics), it says:
> Except where stated otherwise in this PEP, classes impacted by `dataclass_transform`, either by inheriting from a class that is decorated with `dataclass_transform` or by being decorated with a function decorated with `dataclass_transform`, are assumed to behave like stdlib dataclass.
The PEP …

[dataclass_transform] include __dataclass_fields__ in transformed types

---

mypy/nodes.py
mypy/server/astdiff.py
test-data/unit/fine-grained-dataclass-transform.test

Adds support for triggering rechecking of downstream classes when `@dataclass_transform` is added or removed from a function/class, as well as when parameters to `dataclass_transform` are updated. These changes aren't propagated normally since they don't change the type signature of the `dataclass_transform` decorator.
Also adds new a new `find-grained-dataclass-transform.test` file to test the new logic.
(cherry picked from commit 29bcc7ffe1118d01c374a12957b09e4d42c1c69e)

[1.1 backport] [dataclass_transform] detect transform spec changes in incremental mode (#14695)

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test

`dataclasses` uses a `__dataclass_fields__` attribute on each class to mark that it is a dataclass, and Typeshed checks for this attribute in its stubs for functions like `dataclasses.is_dataclass` and `dataclasses.asdict`.
In #14667, I mistakenly removed this attribute for classes transformed by a `dataclass_transform`. This was due to a misinterpretation of PEP 681 on my part; after rereading the [section on dataclass semantics](https://peps.python.org/pep-0681/#dataclass-semantics), it says:
> Except where stated otherwise in this PEP, classes impacted by
`dataclass_transform`, either by inheriting from a class that is decorated with `dataclass_transform` or by being decorated with a function decorated with `dataclass_transform`, are assumed to behave like stdlib dataclass.
The PEP …

[1.1 backport] [dataclass_transform] include __dataclass_fields__ in transformed types (#14752)

---

mypy/dmypy/client.py
mypy/dmypy_server.py

Previously stdout from mypy daemon was propagated to the client, but some verbose logging is written to stderr and it wasn't propagated. Now propagate stderr as well. Tested manually.
This builds on top of #13769.

Show logging written to stderr in mypy daemon

---

mypyc/build.py
setup.py

A simple type-only change since mypyc explicitely uses setuptools' monkeypatching. And `setup.py` imports from setuptools.
Tests should stay the same. This should fix a sudden failure of tests once https://github.com/python/typeshed/pull/9795 is merged.

Support next types-setuptools update

---

build-requirements.txt
pyproject.toml

The mypyc build is failing on `master` due to the latest release of `types-setuptools`: see, e.g. https://github.com/python/mypy/actions/runs/4275505309/jobs/7442902732.
#14787 fixes the mypyc _build_, but there's still a bunch of mypyc tests failing on that PR. I haven't got time to debug them right now (and I'm also not particularly knowledgeable about mypyc!), so this is a stopgap PR to pin `types-setuptools` so that we avoid the latest release.

Pin `types-setuptools` to <67.4.0.2

---

mypy/checker.py
test-data/unit/check-unreachable-code.test

In general code that follows any calls to methods annotated with `NoReturn` is considered unreachable. However calls like `variable['foo'] = 'foo'` are not treated this way. Moreover, `variable.__setitem__('foo', 'foo')` is interpreted properly, so this behavior is inconsistent. After this change both variants result in marking remaining part of the branch as unreachable.
Added test case where code after indexed assignment should be reported is unreachable:
```python
[case testSetitemNoReturn]
from typing import NoReturn
class Foo:
def __setitem__(self, key: str, value: str) -> NoReturn:
raise Exception
Foo()['a'] = 'a'
x = 0  # E: Statement is unreachable
[builtins fixtures/exception.pyi]
```

Honor `NoReturn` as `__setitem__` return type to mark unreachable code.

---

build-requirements.txt
mypyc/build.py
pyproject.toml

- The latest release of `types-setuptools` started causing type-check errors (and, therefore, mypyc build errors) on the `master` branch: see, e.g. https://github.com/python/mypy/actions/runs/4275505309/jobs/7442902732.
- #14781 addressed some of the new errors, but didn't quite fix the build.
- #14788 then pinned the `types-setuptools` dependency as a temporary stopgap measure.
- This PR now attempts to unpin `types-setuptools` and fix the build errors in a more principled way.

Unpin the `types-setuptools` build dependency

---

mypy/build.py
mypy/main.py
mypy/options.py
mypy/refinfo.py

When run with `--export-ref-info`, store line-level reference information in the cache, in a JSON file with a `.refs.json` extension. It includes the line numbers and targets of each RefExpr in the program. This only works properly if incremental mode is disabled.
The target can either be a fullname, or `*.name` for an `name` attribute reference where the type of the object is unknown.
This is an undocumented, experimental feature that may be useful for certain tools, but it shouldn't be used in production use cases.

[undocumented] Optionally export line-level information about references

---

.editorconfig

I found this while looking at https://github.com/python/mypy/blob/master/.pre-commit-config.yaml My IDE suggested 4 spaces instead of 2

Add `yaml` extension to `.editorconfig`

---

docs/source/common_issues.rst
mypy/fastparse.py
test-data/unit/check-errorcodes.test
test-data/unit/check-inline-config.test

I went with the smallest change possible.
@xitop, please, take a look. Does it make sense to you? :)
Closes #14750

Add test and docs for top level `mypy: disable-error-code` comment

---

mypyc/test/test_run.py

Typeshed has a more accurate annotation for this attribute these days

Remove an unnecessary `cast` to `Any`

---

mypy/build.py
mypyc/codegen/emitmodule.py

By default, Python outputs spaces after commas and colons when dumping JSON data. This is normally fine, but when exporting large amounts of JSON (such as cache info) it is more space efficient to export JSON without whitespaces. To do this, simply pass `separators=(",", ":")` to `json.dumps()`.
Although the space savings aren't massive, they do reduce the size of the cache folder by a couple of megabytes:
| Method  | Size   |
|---------|--------|
| Current | 31.2MB |
| This PR | 29.3MB |
For comparison, the size of the cache folder with the `--sqlite-cache` option is about 27.5MB.

Reduce size of JSON data in Mypy cache

---

mypy/nodes.py
mypy/semanal.py
mypyc/ir/class_ir.py
mypyc/irbuild/builder.py
mypyc/irbuild/expression.py
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-classes.test

If the class has no subclasses, we can statically bind the call target:
```
class C:
@classmethod
def f(cls) -> int:
return cls.g()  # This can be statically bound, same as C.g()
@classmethod
def g(cls) -> int:
return 1
```
For this to be safe, also reject assignments to the "cls" argument in
classmethods in compiled code.
This makes the deltablue benchmark about 11% faster.

[mypyc] Optimize classmethod calls via cls

---

mypyc/irbuild/builder.py
mypyc/test-data/irbuild-lists.test

Previously type aliases were looked up from the globals dictionary, even if the target was a primitive type such as list. Now type aliases are treated the same as direct references to types in calls, since type aliases are assumed to be immutable.
This speeds up the deltablue benchmark by about 4%.

[mypyc] Use primitives for calls via type aliases

---

mypyc/build.py
setup.py

The mypyc build was recently broken by a new release of `types-setuptools`. This was fixed on `master` by the following two PRs:
- #14781
- #14787
However, the mypyc build is still broken on the 1.1 branch: https://github.com/python/mypy/actions/runs/4311688115/jobs/7521345529.
This PR cherry-picks the two PRs that fixed the build to the 1.1 branch.

[Release 1.1] Cherry-pick some mypyc build fixes

---

mypy/checker.py
test-data/unit/check-inference.test

Fixes #14819.
Mypy currently silently infers an `Any` type when unpacking an iterator that doesn't explicitly inherit from `typing.Iterator` (i.e., an iterator that's a _structural_ subtype of `typing.Iterator`, but not a _nominal_ subtype):
```python
class Foo:
count: int
def __init__(self) -> None:
self.count = 0
def __iter__(self: T) -> T:
return self
def __next__(self) -> int:
self.count += 1
if self.count > 3:
raise StopIteration
return self.count
a, b, c = Foo()
reveal_type(a)  # note: Revealed type is "Any"
```
However, we have enough information here to infer that the type of `a` should really be `int`. This PR fixes that bug.
There's discussion on the issue thread about an alternative solution that would involve changing some mypy …

Fix `Any` inference when unpacking iterators that don't directly inherit from `typing.Iterator`

---

mypy/types.py

In #4070, `CallableType.__init__` was changed to accept `arg_names: Sequence[str | None]` so we could pass e.g. `list[str]` to it. We're making a similar change to `CallableType.copy_modified`.

CallableType.copy_modified: accept sequence for arg_names

---

mypy/stubinfo.py

Fixes #14841.
`types-backports` is obsolete and leads to incorrect suggestions; see the issue.
`types-backports_abc` was removed from typeshed in python/typeshed#7533.

stubinfo: remove two obsolete packages

---

mypy/checker.py
test-data/unit/check-python310.test

Fix narrow for walrus expressions used in match statements

---

docs/source/error_code_list.rst
docs/source/error_codes.rst

I reviewed documentation changes to be included in mypy 1.1.

Some minor documentation tweaks

---

mypy/stubtest.py
mypy/types.py

The `stubtest.py` cast is no longer needed -- I think the mypyc issue was fixed by https://github.com/python/typeshed/pull/9146.
The `types.py` casts were never needed. They were added relatively recently by somebody called "Alex Waygood".

Remove unnecessary casts in `stubtest.py` and `types.py`

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test
test-data/unit/check-dataclasses.test

Fixes: #14853
Adding support for `if` statements in the dataclass_transform class, so the attributes defined conditionally are treated as those that are directly in class body.

Support if statements in dataclass_transform class

---

mypy/build.py
mypy/refinfo.py

Previously most member expressions only produced the wildcard reference such as `*.attr` when using the (undocumented) `--export-ref-info` flag. Use the type of the object to generate better fullnames, such as `module.Cls.attr`.

Generate better reference information for member expressions

---

mypy/semanal_namedtuple.py

Split off from #14860, since this one is a no-brainer.
`args[0]` has just been narrowed to be of type `StrExpr` in the lines immediately above, and `args` is the same as `call.args`.

Remove unnecessary cast in `semanal_namedtuple.py`

---

mypy/nodes.py
mypy/semanal_enum.py
mypy/semanal_namedtuple.py
mypy/stubgen.py

There are several places in the code base where we need to narrow `list[Expression]` -> `list[StrExpr]`. Currently we do this using `cast`s, but `TypeGuard`s are arguably a much more idiomatic way to do this kind of operation nowadays.

Add a helper function for narrowing `list[Expression]` to `list[StrExpr]`

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/expandtype.py
mypy/server/astdiff.py

By adding another overload, `CallableType -> CallableType`, we can avoid the need for several `cast`s across the code base.

Improve the signatures of `expand_type` and `expand_type_by_instance`

---

mypy/semanal.py

Fixes #14871
Note that this doesn't affect the exit code; it's just about what non-fatal notes get printed during successful runs

Add error code to typing_extensions suggestion

---

mypy/checkexpr.py
mypy/message_registry.py
test-data/unit/check-expressions.test
test-data/unit/check-tuples.test
test-data/unit/fixtures/slice.pyi

Helps with #2410, as suggested by BvB93 in https://github.com/python/mypy/issues/2410#issuecomment-863091868
PEP 696 will be the real solution here, since it will allow us to make slice generic with few backward compatibility issues

Allow SupportsIndex in slice expressions

---

mypy/checker.py
test-data/unit/check-selftype.test

Fixes #14866
Basically does the potential todo I'd mentioned in #14017

Fix incompatible overrides of overloaded generics with self types

---

build-requirements.txt
mypy/fastparse.py
pyproject.toml

The latest version of `types-typed-ast` includes https://github.com/python/typeshed/commit/62a833c50f99e3bb32770cf74a119505e2e42961, which means we now have an unused `type: ignore` comment, which causes the selfcheck to fail with the latest version of `types-typed-ast`

Fix selfcheck with the latest version of `types-typed-ast`

---

mypy/fixup.py
test-data/unit/check-incremental.test

Fix crash on ParamSpec in incremental mode

---

test-data/unit/check-classes.test

Follow-up to #14893
See #14892 for more discussion

Fix misleading TODO comment in `testIterableUnpackingWithGetAttr`

---

mypy/constraints.py
mypy/expandtype.py
mypy/messages.py
mypy/subtypes.py
mypy/types.py
test-data/unit/check-parameter-specification.test

I ran into the duplication issue personally, but this also fixes https://github.com/python/mypy/issues/12734
Also:
- Fixes #12909

Don't duplicate ParamSpec prefixes and properly substitute Paramspecs

---

mypy/checkmember.py
mypy/messages.py
test-data/unit/check-classes.test

Fixes #14755.
This case is already covered by `check-classes.test::testTypeUsingTypeCClassMethodFromTypeVarUnionBound`, now we just remove from it errors that shouldn't be reported.

Handle type[TypeVar] (fixes #14755)

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test

Fixes #14857. The initial implementation overlooked this statement in [PEP 681](https://peps.python.org/pep-0681/#dataclass-semantics):
> Similarly, a class that directly specifies a metaclass that is decorated with dataclass_transform is considered neither frozen nor non-frozen.
As far as I can tell, this is a special case that _only_ applies to classes that directly specify a `dataclass_transform` metaclass. This is import for projects like Pydantic, which requires clients to use a base class but still supports a `frozen` parameter.
Note that this allows mixed frozen and non-frozen behavior if the base class _does_ have fields:
```
@dataclass_transform()
class Meta(type): ...
class Base(metaclass=Meta, frozen=False):
base: int = 0
class Foo(Base, frozen=True):
foo: int = 0
foo = Foo() …
```

[dataclass_transform] fix frozen behavior for base classes with direct metaclasses

---

mypy/expandtype.py
test-data/unit/check-type-aliases.test

Fixes #14744
Note: I didn't add the fix yet (which is simple, although really subtle), because I want to check that test case I added consistently fails with compiled mypy.

Fix crash on single item union of alias

---

mypy/stubtest.py
mypy/test/teststubtest.py

[stubtest] Respect `@final` runtime decorator, enforce it in stubs

---

mypy/nodes.py
test-data/unit/check-protocols.test

Fixes #14889
Fix is straightforward. PEP 544 doesn't say anything about this, but IMO ignoring the import (i.e. not counting it as a member) is the most reasonable thing to do.

Fix crash on class-level import in protocol definition

---

mypyc/doc/float_operations.rst
mypyc/doc/int_operations.rst
mypyc/doc/performance_tips_and_tricks.rst
mypyc/doc/using_type_annotations.rst

These were undocumented previously.

[mypyc] Document native floats and integers

---

mypyc/lib-rt/float_ops.c

I'm trying to fix this error:
```
float_ops.c:9:15: error: function declaration isn't a prototype [-Werror=strict-prototypes]
9 | static double CPy_DomainError() {
```

[mypyc] Be stricter about function prototypes

---

mypy/stubtest.py
mypy/test/teststubtest.py

#13323 means that stubtest will currently emit an error if the runtime is decorated with `@abstractmethod` but the stub is not, but _only_ if the stub is not an overloaded function, as overloaded functions have a different internal representation in mypy. This PR fixes that discrepancy.

Stubtest: check that the stub is abstract if the runtime is, even when the stub is an overloaded method

---

mypy/stubtest.py
mypy/test/teststubtest.py

This implements most of #14924. The only thing it _doesn't_ implement is verification for overloaded methods decorated with `@final` -- I tried working on that, but hit #14950.

Stubtest: verify stub methods or properties are decorated with `@final` if they are decorated with `@final` at runtime

---

mypy/nodes.py
test-data/unit/fine-grained-dataclass-transform.test

Fix a typo when serializing the `frozen_default` parameter; fixes #14952.

[dataclass_transform] fix serialization for frozen_default

---

mypy/build.py
mypy/checker.py
mypy/checkexpr.py
mypy/checkpattern.py
mypy/errors.py
mypy/messages.py
mypy/nodes.py
mypy/partially_defined.py
mypy/semanal.py
mypy/semanal_enum.py
mypy/semanal_namedtuple.py
mypy/stubgen.py
mypy/test/data.py
mypy/test/testpep561.py
mypyc/codegen/emitwrapper.py
mypyc/irbuild/ll_builder.py
mypyc/irbuild/statement.py

This PR removes certain `len()` comparisons when it would be faster/more succinct to do a truthy check instead, such as `len(x) == 0` vs `not x`.
This fixes the [`FURB115`](https://github.com/dosisod/refurb/blob/master/docs/checks.md#furb115-no-len-compare) errors in Refurb (see #14887).

Simplify `len()` comparisons

---

mypy/subtypes.py
test-data/unit/check-selftype.test

Fix narrowing union types that include Self with isinstance (Fixes #14912).
The special case of bound type variables was not handled in function `covers_at_runtime` of module `subtypes`.  So I added it and defined the test case `testNarrowSelfType`.

Fix narrowing union types that include Self with isinstance (Fixes #14912).

---

mypy/plugins/attrs.py
test-data/unit/check-attr.test

When creating generic classes using `attrs`, converters with type vars are not properly integrated into the generated `__init__`:
```python
from typing import TypeVar, Generic, List, Iterable, Iterator
import attr
T = TypeVar('T')
def int_gen() -> Iterator[int]:
yield 1
def list_converter(x: Iterable[T]) -> List[T]:
return list(x)
@attr.s(auto_attribs=True)
class A(Generic[T]):
x: List[T] = attr.ib(converter=list_converter)
y: T = attr.ib()
a1 = A([1], 2)   # E: Argument 1 to "A" has incompatible type "Iterator[int]"; expected "Iterable[T]"
```
This MR fixes the bug by copying type vars from the field/attrib into the type extracted from the converter.

Add support for converters with TypeVars on generic attrs classes

---

mypy/semanal.py
test-data/unit/check-typeguard.test

I was checking through my previous contributions and noticed I messed up the logic here. I added a test case that currently is wrong.
Followup to #14238
I haven't run this on my own machine (it's a one line change....) but presumably CI will pass!

Don't accidentally ignore typeguard validity for staticmethods

---

mypy/test/teststubtest.py

I was working on adding some extra checks around type aliases to stubtest, and realised that some tests for type aliases that I added previously could be made much less verbose and much easier to read. (Consolidate the imports into a single case at the top.)

Make some stubtest tests less verbose

---

mypy/checkstrformat.py
mypyc/test-data/run-strings.test
test-data/unit/check-errorcodes.test
test-data/unit/check-formatting.test

Fixes #11806
This error message was last changed in #11139 to make it more applicable to f-strings. Since users are still getting confused, it makes sense to be more explicit about what the recommended fix is. There was also an extra set of quotes and a mention of Python 3 that didn't help.
I think this is still very much a useful error, it caught a bug I had recently.

Improve bytes formatting error

---

docs/source/more_types.rst

Some of the examples here neither ran nor type checked. Remove mention and use of deprecated APIs.
Also go into some detail about async generators. Document #5385 since it comes up not infrequently.
Linking #13681

Improve async documentation

---

docs/source/cheat_sheet_py3.rst
docs/source/runtime_troubles.rst

Everyone can use future annotations now. Also forward references are the most type hinting popular question on Stack Overflow, so give a little more detail.
The IO example should go with standard duck types.
I moved the async example to the bottom. It basically just works as you'd expect, maybe we should remove it altogether.
Linking #13681

Improvements to cheat sheet

---

docs/source/error_code_list.rst
mypy/errorcodes.py

Add documentation for bytes formatting error code

---

README.md
conftest.py
docs/Makefile
docs/make.bat
docs/source/additional_features.rst
docs/source/conf.py
docs/source/faq.rst
docs/source/index.rst
misc/remove-eol-whitespace.sh
mypy/build.py
mypy/plugins/attrs.py
mypy/test/data.py
mypyc/doc/introduction.rst
mypyc/doc/make.bat
pytest.ini
setup.py

Also updated a few links that were pointing to redirects.
Skipped following files:
* XML/SVG files linking to XML namespaces
* `mypyc/external` - looks like vendored code
* `LICENSE` - because it's verbatim legal text, also pythonlabs.com isn't available on HTTPS

Convert insecure links to use HTTPS

---

mypy/stubgen.py

While working on https://github.com/python/mypy/pull/14981 I've noticed several outdated Python ideoms that we don't use in this project anymore.
This PR changes them to be modern.
Since this is a simple refactoring, I will merge this after the CI is green.

Modernize stubgen

---

mypy/stubtest.py
mypy/test/teststubtest.py
test-data/unit/lib-stub/typing_extensions.pyi

Fix stubtest false positives with TypedDicts at runtime

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test

Infer `__init__` argument types from the signatures of descriptor `__set__` methods, if present. We can't (easily) perform full type inference in a plugin, so we cheat and use a simplified implementation that should still cover most use cases. Here we assume that `__set__` is not decorated or overloaded, in particular.
Fixes #14868.

Support descriptors in dataclass transform

---

docs/source/stubtest.rst

Could help with e.g. https://github.com/matplotlib/matplotlib/pull/24976

stubtest: improve allowlist documentation

---

mypy/errors.py
mypy/server/update.py
test-data/unit/daemon.test

This adds a commit which fixes issue https://github.com/python/mypy/issues/9655 wherein some types of error would be lost when a file was re-processed by dmypy. Regression tests are also included.
This also fixes another error where sometimes files would not be re-processed by dmypy if the only error in the file was either "unused type ignore" or "ignore without code".

Fix disappearing errors when re-running dmypy check

---

docs/source/runtime_troubles.rst

The section "Using classes that are generic in stubs but not at runtime" on the runtime_troubles.html page is very helpful, but naive readers who follow its instructions will almost inevitably create a runtime `NameError`. This PR updates the example to include an `annotations` import that will avert such a `NameError`.

Clarify "Using types...but not at runtime" docs

---

mypy/subtypes.py
mypy/typestate.py

A possible solution for https://github.com/python/mypy/issues/14867 (I just copy everything from positive caches).

Add negative subtype caches

---

mypy/plugins/attrs.py
test-data/unit/check-attr.test

Fixes the error on the last line of this example:
```python
@attrs.define
class A:
x: int
T = TypeVar('T', bound=A)
def f(t: T) -> None:
_ = attrs.evolve(t, x=42)  # E: Argument 1 to "evolve" has incompatible type "T"; expected an attrs class
```
Since `T` is bounded by `A`, we know it can be treated as `A`.

Fix attrs.evolve on bound TypeVar

---

docs/source/cheat_sheet_py3.rst

In `cheat_sheep_py3.rst` functions examples, there is one function example misaligned with to other examples in the code block. This PR just removes leading space.

Fix alignment of cheat sheet example

---

mypy/stubgen.py
test-data/unit/stubgen.test

[stubgen] Add `@functools.cached_property` support

---

mypy/messages.py
mypy/subtypes.py
mypy/typeops.py
test-data/unit/check-protocols.test

Fix error for callback protocol matching against callable type object

---

mypy/stubgen.py
mypy/stubgenc.py
mypy/test/teststubgen.py

This bundles together a handful of improvements to stubgenc.  Each one has its own commit, but it can be somewhat time consuming to get a PR reviewed and merged, so I'm putting them together for the sake of expediency.  I'll break them up if it is preferred.
An overview of the main changes:
- infer return types for known special methods:  previously only argument types were inferred
- check class docstrings for signatures in addition to `__init__`:  shiboken binding generator is known to put constructor signatures in class docstrings rather than on `__init__`
- use the list of analyzed modules to produce better imports:  previously when given `foo.Bar.Spangle`, it was assumed that `import foo.Bar` should be added, however, it could be that `Bar.Spangle` refers to nested classes within the …

Improvements to stubgenc

---

mypy/checkexpr.py
mypy/checkstrformat.py
mypy/test/data.py
mypy/test/testdeps.py
mypyc/test-data/fixtures/ir.py
mypyc/test-data/fixtures/typing-full.pyi
test-data/unit/check-expressions.test
test-data/unit/check-formatting.test
test-data/unit/check-generic-subtyping.test
test-data/unit/check-incremental.test
test-data/unit/check-inference.test
test-data/unit/check-kwargs.test
test-data/unit/fine-grained-dataclass-transform.test
test-data/unit/fine-grained-modules.test
test-data/unit/fine-grained.test
test-data/unit/fixtures/args.pyi
test-data/unit/fixtures/dataclasses.pyi
test-data/unit/fixtures/dict.pyi
test-data/unit/fixtures/paramspec.pyi
test-data/unit/fixtures/primitives.pyi
test-data/unit/fixtures/tuple.pyi
test-data/unit/fixtures/typing-async.pyi
test-data/unit/fixtures/typing-full.pyi
test-data/unit/fixtures/typing-medium.pyi
test-data/unit/fixtures/typing-namedtuple.pyi
test-data/unit/fixtures/typing-typeddict.pyi
test-data/unit/lib-stub/_typeshed.pyi
test-data/unit/lib-stub/builtins.pyi
test-data/unit/lib-stub/typing.pyi

Fixes #14986
This PR allows any object matching `_typeshed.SupportsKeysAndGetItem[str, Any]` to be unpacked with `**`.

Allow objects matching `SupportsKeysAndGetItem` to be unpacked

---

mypyc/rt_subtype.py
mypyc/test-data/run-bools.test
mypyc/test/test_typeops.py

Fixes https://github.com/mypyc/mypyc/issues/982

[mypyc] Fix unions of bools and ints

---

mypy/checker.py
test-data/unit/check-selftype.test

Fixes #15041
Related to #14882 and #14017 (the older one is where I added the xfail test)

Fix bounded self types in override incompatibility checking

---

test-data/unit/check-errorcodes.test

Add a test for the code path exercised in #15094

Regression test for make_simplified_union truthiness

---

mypy/subtypes.py

This is a performance optimisation for subtyping between two unions that are largely the same.
Fixes #14034
This makes @adriangb's example in https://github.com/python/mypy/issues/14034#issuecomment-1470252641 finish basically instantly. I could add it as a unit test?
Type checking pydantic core is still not fast — takes like four or five minutes with uncompiled mypy — but at least it's now feasible. I think there's room for doing some optimisation in make_simplified_union that would improve this.

Fix performance in union subtyping

---

mypyc/ir/rtypes.py
mypyc/test/test_typeops.py

I figured this might be faster and less code. Also just curious what the process is like to contribute to mypy.

Use dict keys for order-preserving dedupes instead of set + list

---

mypy/options.py

This is a workaround for correctly detecting the platform when building mypy with mypyc on the Emscripten platform. This fixes https://github.com/mypyc/mypy_mypyc-wheels/issues/62. `pyodide build` overrides `sysconfig` for the host based on the target (confirmed on the pyodide matrix, [see also where the code is actually changed](https://github.com/pyodide/pyodide/blob/e835bf05ff4aa463024aaeb9689ae70ea5771314/pyodide-build/pyodide_build/pypabuild.py#L43-L50)).
This should only change things when checking/building for the emscripten platform. There isn't really a cleaner workaround that I can think of unfortunately, the main issue is cross compiling is tricky with setuptools.

Fix sys.platform when cross-compiling with emscripten

---

mypy/checker.py
test-data/unit/check-narrowing.test

Resolves #10915, resolves #9786
See the discussion in #10915. I'm sympathetic to the difference between
identity and equality here being surprising and that mypy doesn't
usually make concessions to mutability when type checking.
The old test cases are pretty explicit about their intentions and are
worth reading. Curious to see what people (and mypy-primer) have to say
about this.

Allow narrowing enum values using ==

---

mypy/treetransform.py
test-data/unit/check-async-await.test

Propagate additional function flags in TransformVisitor.
Work on #14706.

Fix nested async functions when using TypeVar value restriction

---

mypy/message_registry.py
mypy/semanal.py
test-data/unit/check-classes.test

Generates error when staticmethod and classmethod decorators are both used

---

mypy/main.py
mypy/messages.py
mypy/options.py
mypy/test/helpers.py
mypy/test/testcheck.py
mypy/test/testcmdline.py
test-data/unit/check-union-error-syntax.test
test-data/unit/daemon.test

This should fix https://github.com/python/mypy/issues/15082:
If the python version is set to 3.10 or later union error reports are going to be displayed using the `X | Y` syntax.
If None is found in a union it is shown as the last element in order to improve visibility (`Union[bool, None, str]` becomes `"bool | str | None"`. 
To achieve this an option `use_or_syntax()` is created that is set to true if the python version is 3.10 or later.
For testing a hidden flag --force-union-syntax is used that sets the option to false.

Use X | Y union syntax in error messages

---

mypy/message_registry.py
test-data/unit/check-modules.test
test-data/unit/check-python311.test
test-data/unit/check-statements.test

Fixes #5349 - Updating Error Messaging for Invalid Exception Type

MyPy Exception Type Error Message Update

---

mypy/messages.py
test-data/unit/check-classes.test
test-data/unit/lib-stub/numbers.pyi

Types from `numbers` aren't really supported in any useful way. Make it more explicit, since this is surprising.
Work on #3186.

Add explanation if argument type is incompatible because of a "numbers" type

---

mypy/defaults.py

Fixes #14915 
When there are more than 200 errors to report, mypy "softly" trims the output without notifying the user that it did so. We want to currently disable this by setting the `--soft-error-limit` default to `-1` which would list out _all_ the errors.

Set soft error limit default to -1 (unlimited)

---

mypy/checkexpr.py
test-data/unit/check-expressions.test

Fixes #12923
assert_type(42, int) ... had issues.  #12923 was a bit of a mess as the OP was or wasn't currently accurate.
Added two tests to repo the current problem, which now pass.

Use source_type.last_known_value when Instance.  Fixes #12923

---

test-data/unit/check-classes.test
test-data/unit/check-flags.test
test-data/unit/check-incremental.test
test-data/unit/check-plugin-attrs.test
test-data/unit/fine-grained-attr.test
test-data/unit/fine-grained.test
test-data/unit/fixtures/plugin_attrs.pyi

- the library is named "attrs", not "attr"[^1]
- "attrs" could mean a test of Python attributes, so adding "plugin"
[^1]: at some point we'd also need to change tests to use `attrs.define` and `attrs.fields` in all but tests meant to exercise the "old API"

Rename attrs tests

---

mypy/messages.py
test-data/unit/check-lowercase.test

Fixes #13027 (or at least half of it)

Surface lowercase `type` instead of `Type` in error messages on Python 3.9 and above

---

mypy/stubgen.py

This is required when using stubgen in a parallel build system, such as GNU make.
I don't know how to test this using your test framework. I verified it manually.

Make stubgen respect MYPY_CACHE_DIR

---

README.md

Adjusting the README to comply with Markdown Linting rules:
- MD032/blanks-around-lists: Lists should be surrounded by blank lines
- MD012/no-multiple-blanks: Multiple consecutive blank lines [Expected: 1; Actual: 2]
- MD046/code-block-style: Code block style [Expected: fenced; Actual: indented]
- MD004/ul-style: Unordered list style [Expected: dash; Actual: asterisk]
- MD034/no-bare-urls: Bare URL used

MyPy README Formatting Cleanup

---

mypy/applytype.py
mypy/checker.py
mypy/checkexpr.py
mypy/constraints.py
mypy/meet.py
mypy/semanal.py
mypy/stubgen.py
mypy/subtypes.py
mypy/types.py
mypyc/irbuild/expression.py

This PR fixes the [`FURB121`](https://github.com/dosisod/refurb/blob/master/docs/checks.md#furb121-use-isinstance-issubclass-tuple) error code in [Refurb](https://github.com/dosisod/refurb).
See #14887

Simplify `isinstance` calls

---

.github/workflows/mypy_primer_comment.yml

Fixes https://github.com/hauntsaninja/mypy_primer/issues/80

Improve mypy_primer comment

---

mypy/typeanal.py
test-data/unit/check-recursive-types.test

Fixes #15018 
The fix is quite straightforward: function-scope aliases are not supported anyway, so we just give up early and let the error appear.

Fix a crash when function-scope recursive alias appears as upper bound

---

docs/source/kinds_of_types.rst
docs/source/protocols.rst

Related: https://github.com/python/mypy/issues/15024. Phrasing might be incorrect, I'll take reviews if required

Clarify usage of callables regarding type object in docs

---

mypy/applytype.py
mypy/expandtype.py
mypy/subtypes.py
test-data/unit/check-generics.test

Fixes #15060 
The example in the issue contains another case where an erased type may legitimately appear in a generic function. Namely, when we have a lambda in a generic context, and its body contains a call to a generic _method_. First, since we infer the type of lambda in erased context, some of lambda parameters may get assigned a type containing erased components. Then, when accessing a generic method on such type we may get a callable that is both generic and has erased components, thus causing the crash (actually there are two very similar crashes depending on the details of the generic method).
Provided that we now have two legitimate cases for erased type appearing in `expand_type()`, and special-casing (enabling) them would be tricky (a lot of functions will need to have …

Fix crash on lambda in generic context with generic method in body

---

mypy/applytype.py
mypy/typeanal.py
test-data/unit/check-typevar-tuple.test

This adds tests for mixing star args with typevar tuples from PEP646. In order to do this we have to handle an additional case in applytype where the result of expanding an unpack is a homogenous tuple rather than a list of types.
This PR also includes (partially by accident) a fix to the empty case for type analysis. After re-reading the PEP we discover that the empty case is meant to be inferred as a Tuple[Any, ...] rather than an empty tuple and must fix that behavior as well as some of the previous test cases that assumed that it meant an empty tuple.
When we actually call `target(*args)` from the testcase in `call` we expose a crash in mypy. This will be handled by a subsequent PR.

[PEP646] Add tests/fixes for callable star args behavior

---

mypy/checker.py
test-data/unit/check-optional.test

See https://github.com/python/mypy/pull/15133#issuecomment-1533794642 for context.

Fix crash related to propagating type narrowing to nested functions

---

mypy/messages.py
test-data/unit/check-assert-type-fail.test

When assert_type fails, when the type of value examined and the specified type have the same name, mypy returns an error with more descriptive and distinct names.
Error: Expression is of type "mypy-test.SupportsIndex", not "typing_extensions.SupportsIndex"
instead of
Error: Expression is of type "SupportsIndex", not "SupportsIndex" (previous behavior)
Added unit tests in test-data/unit/check-assert-type-fail.test.

Output distinct types when type names are ambiguous

---

mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-expressions.test
test-data/unit/check-generics.test
test-data/unit/check-python38.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test

Fixes #12977
IMO current dict expression inference logic is quite arbitrary: we only take the non-star items to infer resulting type, then enforce it on the remaining (star) items. In this PR I simplify the logic to simply put all expressions as arguments into the same call. This has following benefits:
* Makes everything more consistent/predictable.
* Fixes one of top upvoted bugs
* Makes dict item indexes correct (previously we reshuffled them causing wrong indexes for non-star items after star items)
* No more weird wordings like `List item <n>` or `Argument <n> to "update" of "dict"`
* I also fix the end position of generated expressions to show correct spans in errors
The only downside is that we will see `Cannot infer type argument` error instead of `Incompatible type` more often. …

Make dict expression inference more consistent

---

mypy/subtypes.py
mypy/test/testtypes.py
mypy/typeops.py
test-data/unit/check-type-aliases.test

Fixes #15192
The following code optimises make_simplified_union in the common case that there are exact duplicates in the union. In this regard, this is similar to #15104
There's a behaviour change in one unit test. I think it's good? We'll see what mypy_primer has to say.
To get this to work, I needed to use partial tuple fallbacks in a couple places (these maybe had the potential to be latent crashes anyway?) There were some interesting things going on with recursive type aliases and type state assumptions
This is about a 25% speedup on the pydantic codebase and about a 2% speedup on self check (measured with uncompiled mypy)

Speed up make_simplified_union, fix recursive tuple crash

---

mypy/stubgen.py
test-data/unit/stubgen.test

stubgen: Fix missing total from TypedDict class

---

.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml
test-requirements.txt
tox.ini

x-ref: #15197
I updated the python version used for linting to 3.10. This gives us some time before we have to update again.
The only downside I see is if someone is using a 3.7 python environment locally and they run linters in that environment or if they installed tox with python 3.7 and they run `tox run -e lint`. A note can be added in the contributing guide to tell users what python versions are supported for dev tools. Another solution would be to delay merging this PR until python 3.7 support is dropped altogether but in this case the pre-commit-ci updates and the #15197 situation would happen again.
(cc @AlexWaygood)

Update linters and python version for linting in CI

---

mypy/expandtype.py
mypy/types.py
test-data/unit/check-typeguard.test

This used to be a source of code duplication, and also using the "native" visitor will allow us to implement new features for type aliases easily (e.g. variadic type aliases, that I am going to do in next PR).

Use native ExpandTypeVisitor for expanding type aliases as well

---

mypy/typeops.py
test-data/unit/check-recursive-types.test

Fix recursive type alias crash in make_simplified_union

---

mypy/errorcodes.py

When starting mypy daemon, we pickle options. Error codes are part of options and need to be pickle-able. This decorator is needed for this to be possible with mypyc.
Fixes #14671

Mark ErrorCodes as serializable

---

docs/source/cheat_sheet_py3.rst

Forgotten comma between parameters.

fix: typo fix for positional-only and keyword-only arguments

---

runtests.py
test-requirements.txt
tox.ini

This makes it easier to maintain the configurations for the various linting tools we use in CI. It also makes it easier for contributors to run the linting tools locally. `black`, `isort` and `flake8` are all very fast checks, so I think it makes sense to just run them all together in `runtests.py`. 
With this PR, the following three invocations will all be equivalent:
```
pre-commit run --all-files
python runtests.py lint
tox -e lint
```
Closes #15076

Centralise linting config in `.pre-commit-config.yaml`

---

mypyc/doc/getting_started.rst

Update the link to latest version MS has on its website. (there's no more build tools for 2017, just 2022) and also provide a bit more information as to what to install. The Windows SDK is needed as well.

Update getting started docs for mypyc for Windows

---

docs/source/config_file.rst

pre-commit is failing on `master`: https://github.com/python/mypy/actions/runs/4970566646/jobs/8894519893
The cause was a merge race between #15234 and #15237

`config_file.rst`: fix lint

---

mypyc/primitives/dict_ops.py
mypyc/test-data/run-misc.test

[mypyc] Support unpacking mappings in dict display

---

mypy/dmypy/client.py
mypy/dmypy_server.py

Currently, when starting the mypy daemon, we're passing the timeout and log_file as part of the pickled options. This can cause problems if the daemon has issues with the pickling. In this case we won't be able to log what the problem was.
Let's pass the log_file and timeout as first class args. This also has the advantage that we can now start the daemon in the foreground with these args from the command line in a human writeable way.

Pass log-file and timeout args to daemon as proper args

---

mypy/test/testpythoneval.py
mypy/typeanal.py
test-data/unit/pythoneval.test

We were checking only for `typing_extensions.Unpack`, which breaks code when checking at 3.11+ even if importing `typing_extensions` because its just a re-export from `typing`.
These basic pythoneval tests also assert that the feature at least somewhat works with the real stubs - otherwise up until now we had basically no coverage of that, and were relying on the fake typing stubs to be close enough to the real thing.

Fix type analysis for typing.Unpack

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/main.py

Fixes #9963, #12693.
Previously addressed in #9964.
`disallow_untyped_defs` is a superset of `disallow_incomplete_defs`, as seen here:
- https://mypy-play.net/?mypy=latest&python=3.11&gist=cddd4c1921f3f5d5ac34a514bec1675f
- https://mypy-play.net/?mypy=latest&python=3.11&gist=cddd4c1921f3f5d5ac34a514bec1675f&flags=disallow-untyped-defs
The latter playground results in:
```
main.py:1: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
```

Clarify difference between disallow_untyped_defs and disallow_incomplete_defs

---

test-data/unit/check-assert-type-fail.test

Closes #15153.
This issue was already addressed in #15184; we're adding a regression test.

Add regression test for asserting distinct callable types

---

docs/source/mypy_daemon.rst

Fixes https://github.com/python/mypy/issues/15214 but adding a note to the dmypy docs.

Add `--local-partial-types` note to dmypy docs

---

docs/source/additional_features.rst
mypyc/test-data/run-attrs.test
test-data/unit/check-flags.test
test-data/unit/check-incremental.test
test-data/unit/check-plugin-attrs.test
test-data/unit/fine-grained-attr.test
test-data/unit/lib-stub/attrs/__init__.pyi
test-data/unit/stubgen.test

"attrs" namespace, "attrs.define" and "attrs.field" are the recommended new namespace and API of the attrs library (see https://www.attrs.org/en/stable/names.html) so we should modernize the bulk of our tests to use the current API.

Use attrs and @attrs.define in tests

---

mypy/stubgen.py
test-data/unit/stubgen.test

This PR refactors name resolution in stubgen to make it simple to use and fixes a bunch of related bugs especially when run in `--parse-only` mode. It mainly does the following:
1. Adds a `get_fullname` method that resolves the full name of both `NameExpr` and `MemberExpr` taking into account import aliases
2. Use this method everywhere manual resolution was done including the decorator processors
3. Simplify decorator processing by consolidating `process_decorator`, `process_name_expr_decorator`, and `process_member_expr_decorator` into a single method thanks to the common name resolution using `get_fullname`
4. Fix occurrences of some hard-coded implicitly-added names (like `Incomplete` from `_typeshed`) by using `self.typing_name()` and `self.add_typing_import` which take into account …

stubgen: fixes and simplifications

---

mypy/checker.py
mypy/messages.py
test-data/unit/check-abstract.test
test-data/unit/check-classes.test
test-data/unit/check-dataclasses.test
test-data/unit/check-functions.test
test-data/unit/check-plugin-attrs.test

Previously the "signature incompatible with supertype" error only included detailed comparison when both types are callables; now it will compare in all cases.

Detailed 'signature incompatible with supertype' for non-callables

---

mypyc/codegen/emit.py
mypyc/codegen/emitfunc.py
mypyc/ir/ops.py
mypyc/test/test_emitfunc.py

This PR removes labels which are never jumped to, as well as removing gotos that jump directly to the next label (and removes the now redundant label). I had a small issue with the `GetAttr` op code as it would insert C code after the end of the branch which could not be detected at the IR level, as seen in https://github.com/mypyc/mypyc/issues/600#issuecomment-1319530780 .
Here are some basic stats on the file sizes before and after this PR:
Building with `MYPY_OPT_LEVEL=0`, `MYPY_DEBUG_LEVEL=1`:
| Branch   | `.so` size      | `.c` size       | `.c` lines      |
|----------|-----------------|-----------------|-----------------|
| `master` | 43.9 MB         | 79.7 MB         | 2290675         |
| This PR  | 43.6 MB (-0.6%) | 78.6 MB (-1.4%) | 2179967 (-4.8%) |
Building with …

[mypyc] Remove unused labels and gotos

---

mypy/refinfo.py

Previously they were sometimes reported as `builtins.type.method_name` (i.e. a method of `builtins.type` instead of e.g. `module.ClsName`). Now report them as `module.ClsName.method_name`.

Fix class method and static method calls with --export-ref-info

---

mypy/refinfo.py
mypy/test/test_ref_info.py
test-data/unit/ref-info.test
test-data/unit/typexport-basic.test

The regular function body has no type information if the function uses
a type variable with a value restriction in its signature. Instead look
at the expanded versions of the function body. This will produce
duplicate references for some expressions, but that seems benign.
Also add a foundation for writing tests for --export-ref-info and add a
few test cases.

Fix --export-ref-info with type variable with value restrictions

---

mypy/semanal.py
test-data/unit/check-modules.test
test-data/unit/fixtures/module_all.pyi

See #12582. pyright supports this pattern as well.

Support __all__.remove

---

mypyc/codegen/emitfunc.py
mypyc/transform/exceptions.py

`adjust_error_kinds()` should be run over every block, but the old impl. of `insert_exception_handling()` would stop iterating over blocks once it generated a default error handler. This made sense for its original purpose, but unfortunately limits the effectiveness of `adjust_error_kinds()`.
Changing `insert_exception_handling()` to loop over every block no matter what also means we can get rid of the weird GetAttr special casing in the branch emit logic (stumbling across that is what made me investigate in the first place!).
This reduces self-compile LOC by 1.1% in my experiments (avoiding error branches sometimes eliminates register assignments or on-error decrefs... according to my brief look through the C diff between master and this patch).
| Revision | Self-compile C LOC | …

[mypyc] Try adjusting error kinds for all blocks

---

mypy/renaming.py
test-data/unit/check-python310.test

Fix match subject ignoring redefinitions

---

mypy/stubgen.py
test-data/unit/stubgen.test

Consider this python code:
```python
from typing import Generic, TypeVar
class C(Generic[T]): ...
```
This is what stubgen produced before:
```python
T = TypeVar('T')
class C: ...
```
and this after:
```python
from typing import Generic, TypeVar
T = TypeVar('T')
class C(Generic[T]): ...
```
Note that stubgen handles generics correctly in --parse-only mode already.

stubgen: Do not remove Generic from base classes

---

mypy/checker.py
mypy/checkexpr.py
mypy/copytype.py
mypy/expandtype.py
mypy/fixup.py
mypy/indirection.py
mypy/nodes.py
mypy/plugins/attrs.py
mypy/plugins/dataclasses.py
mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/semanal_shared.py
mypy/server/astdiff.py
mypy/server/astmerge.py
mypy/server/deps.py
mypy/test/testtypes.py
mypy/test/typefixture.py
mypy/treetransform.py
mypy/tvar_scope.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py
mypy/typevars.py

Start implementing [PEP 696](https://peps.python.org/pep-0696/) TypeVar defaults. This PR
* Adds a `default` parameter to `TypeVarLikeExpr` and `TypeVarLikeType`.
* Updates most visitors to account for the new `default` parameter.
* Update existing calls to add value for `default` => `AnyType(TypeOfAny.from_omitted_generics)`.
A followup PR will update the semantic analyzer and add basic tests for `TypeVar`, `ParamSpec`, and `TypeVarTuple` calls with a `default` argument. -> #14873
Ref #14851

Add foundation for TypeVar defaults (PEP 696)

---

mypy/test/data.py
mypy/test/helpers.py
mypy/test/testcheck.py
mypy/test/testupdatedata.py
mypy/test/update_data.py

Fixes #15265.
The new implementation works for two kinds of 'check' tests:
- Test cases whose assertions are in `[out]` and/or `[outN]` sections, have those sections rewritten with the new results
- Test cases whose assertions are inlined as Python comments in `[case ...]` and `[file ...]` sections, have the actual results inlined into source code
The two scenarios are mutually exclusive: if `[out]` is updated, then `[case ...]` won't be.
Details:
- The "fixes" are enqueued and applied in reverse order to prevent line offsets from shifting as it incrementally changes the file. 
- The update preserves spacing between the source code and comment to reduce diff noise.
- Like the previous implementation, we only update "check" data tests.

Improve --update-data handler

---

mypy/errorcodes.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/custom_errorcode.py

A class marked with `allow_interpreted_subclasses=True` implicitly supports serialization while also allowing it to be subclassed by pure Python code.
Fixes #15255
https://mypyc.readthedocs.io/en/latest/differences_from_python.html#pickling-and-copying-objects
https://mypyc.readthedocs.io/en/latest/native_classes.html#inheritance

Fix crash with custom ErrorCodes

---

mypyc/irbuild/builder.py
mypyc/test-data/run-misc.test

```python
def f(b: bool) -> None:
if b:
y = 1
else:
y = None
f(False)
```
On encountering y = 1, mypyc uses the expression type to determine the
variable rtype. This usually works (as mypy infers the variable type
based on the first assignment and doesn't let it change afterwards),
except in this situation.
NameExpr(y)'s type is int, but the variable should really be int | None.
Fortunately, we can use the Var node's type information which is
correct... instead of blindly assuming the first assignment's type is
right.
Fixes mypyc/mypyc#964

[mypyc] Use correct rtype for variable with inferred optional type

---

docs/source/config_file.rst

It appears that in the context of the `config_file.rst`, there is a consistent use of `boolean`, but only `no_site_packages` was mentioned as `bool`. Therefore, I have made the correction.

fix(docs): bool -> boolean in config_file.rst

---

mypy/test/testupdatedata.py

This should allow the inner pytest to pass even when the outer pytest is invoked outside of the mypy root, e.g.
```shell
cd ..
pytest mypy/mypy/test/testupdatedata.py
```
Addresses https://github.com/python/mypy/pull/15283#issuecomment-1578609223.

testupdatedata: fix cwd

---

mypy/test/data.py
mypy/test/meta/test_parse_data.py
mypy/test/meta/test_update_data.py

Quality of life improvements:
- Consolidate parser messages in a common function. We're using `pytest.fail(..., pytrace=False)` to eliminate stack trace noise.
- Make sure error messages have correct line offsets, that refer to the global line number in the file (that you can scroll to with an editor). Previously we used `TestItem.line` which is relative to testcase (e.g. for main item of testcase starting at line 1234, it'll be 1).
- Always parse `case` sections, erroring out on invalid names; previously invalid [case]s were ignored during `split_test_cases` but then resurfaced when parsing (as they'd end up being a section of the preceding case):
```
[case abc]
...
[case something-invalid]  <-- skipped during split_test_cases, raised as invalid section of abc
...
```
- Remove the …

Make .test parser friendlier

---

mypy/messages.py
test-data/unit/check-typeddict.test

Fix crash when indexing TypedDict with empty key

---

mypy/stubtest.py

Fix stubtest crash in explicit init subclass

---

mypy/semanal.py
test-data/unit/check-abstract.test

Fixes #4165. The this should probably error bit is #13649

Fix abstract and non-abstract variant error for prop.deleter

---

mypy/semanal.py
test-data/unit/check-namedtuple.test
test-data/unit/fixtures/typing-namedtuple.pyi

Fixes #15380
Note I also update the `NamedTuple` fixture to be much closer to real definition in `typing.pyi` in typeshed.

Fix crash on NamedTuple as attribute

---

mypy/build.py
mypy/messages.py
test-data/unit/check-flags.test
test-data/unit/cmdline.test

Fixes #15246 
Likely fixes #15319, but I didn't find a repro.
Note I also cleanup one thing, there should be clear separation:
* `CORE_BUILTIN_MODULES` must be always available, and their content must be unaltered, since we rely on it.
* `semanal_main.core_modules` should be analyzed first among `builtins` SCC in a specific order.

Fix crash on follow_imports_for_stubs

---

mypy/checker.py
mypy/plugin.py
mypy/plugins/attrs.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/function_sig_hook.py

Fixes #14845.
p.s. In the issue above, I was concerned that adding this method would create an avenue for infinite recursions (if called carelessly), but in fact I haven't managed to induce it, e.g. FunctionSigContext has `args` but not the call expression itself.

Add get_expression_type to CheckerPluginInterface

---

mypy/checker.py
test-data/unit/check-flags.test

Fixes #9656
Although it is not clear this is actually a bug, it is kind of inconsistent to say "Returning Any from function declared to return ..." for lambdas, that never have annotations, their types are always inferred, not declared. Also it is a surprisingly popular issue that is a one line fix, so I think we should do it.

Always allow returning Any from lambda

---

mypyc/codegen/emitclass.py

While investigating something unrelated I stumbled across the `*_setup` functions, and I noticed that they contain a lot of code that looks like this:
```c
self->abc = NULL;
self->xyz = NULL;
// ...
```
Something told me that assigning `NULL` to a bunch of fields is propably not needed, and when looking at the docs for `tp_alloc()` I found this reference to [`allocfunc`](https://docs.python.org/3/c-api/typeobj.html#c.allocfunc), the typedef for `tp_alloc()`:
> It should return a pointer to a block of memory of adequate length for the instance, suitably aligned, ***and initialized to zeros***, ...
Emphasis is mine.
Basically I added a simple check that removes lines that assigns `NULL` values in setup functions. This removes about ~4100 lines from the C file when self-compiling.

[mypyc] Don't explicitly assign `NULL` values in setup functions

---

mypy/test/helpers.py
test-data/unit/check-classes.test
test-data/unit/check-overloading.test
test-data/unit/check-recursive-types.test
test-data/unit/check-tuples.test
test-data/unit/semanal-errors.test
test-data/unit/semanal-statements.test

Remove special casing for "cannot" in error messages

---

docs/source/conf.py
docs/source/html_builder.py

Makes the HTML builder generate a _refs.html file that redirects (global) refs (when provided as a hash i.e. `_refs.html#some-ref`) to the appropriate document.
This allows tools (e.g. #15431) to link to well-known refs.

docs: ref redirector

---

mypy/dmypy/client.py
mypy/dmypy_server.py
mypy/errorcodes.py
mypy/options.py
test-data/unit/daemon.test

Fixes #10709 
Two changes here:
* Add equality methods to `ErrorCode` because they may appear in options snapshots
* Use stable comparison for option snapshots, since `Options.apply_changes()` does some unrelated things with flags
Both are only relevant on Windows where options may roundtrip as: `options -> snapshot -> pickle -> base64 -> unpickle -> apply_changes`.

Fix dmypy run on Windows

---

docs/source/error_code_list.rst
docs/source/error_code_list2.rst
docs/source/error_codes.rst
docs/source/html_builder.py

Fixes #15431
After this PR one will be able to easily find documentation for given error code using `https://mypy.readthedocs.io/en/stable/_refs.html#code-{code as reported by mypy}`, for example `https://mypy.readthedocs.io/en/stable/_refs.html#code-attr-defined`.

Use consistent anchors for error codes

---

mypy/checkexpr.py
mypy/nodes.py
test-data/unit/check-typevar-defaults.test

Check that `default` type is a subtype of `bound` or one of the constraint types.
Add `default` to nodes `__match_args__`. Missed that initially.
Ref: #14851

Additional validation for TypeVar defaults (PEP 696)

---

mypy/dmypy_server.py
test-data/unit/daemon.test
test-data/unit/fine-grained.test

Fixes #5343
Fixes #12249
This can potentially slow down runs in situations where multiple unchanged files are re-added to source list. Potentially, we can track whether modules had errors permanently (not just from previous run), and then only re-check those unchanged re-added files that had errors before. I am not sure if this is important.

Fix re-added file with errors in mypy daemon

---

mypyc/codegen/emit.py
mypyc/codegen/emitmodule.py
mypyc/lib-rt/CPy.h
mypyc/test/test_emit.py

This simplifies things a bit. All the C compilers we care about should support this.
This will make things easier once we support more types represented as C structs.
I expect this to have no measurable impact on performance.

[mypyc] Use C99 compound literals for undefined tuple values

---

docs/source/protocols.rst

Small improvements to protocol documentation

---

mypy/join.py

The tests added with this piece of code now pass even without it. It looks like the crash was properly fixed by https://github.com/python/mypy/pull/13371

Delete a ProperType join hack

---

mypyc/lib-rt/mypyc_util.h

It's currently unused but I have other PRs that will need this.
We can later make this more general and support things like "are we running on Python 3.12 beta 2 or later", but this seems good enough for now.

[mypyc] Add Python 3.12 feature macro

---

mypyc/lib-rt/exc_ops.c

See https://github.com/python/cpython/pull/102935.
Work on https://github.com/mypyc/mypyc/issues/995.

[mypyc] Don't use _PyErr_ChainExceptions on 3.12, since it's deprecated

---

docs/source/installed_packages.rst

Use setuptools instead of distutils in docs

---

mypy/test/meta/test_parse_data.py
mypy/test/meta/test_update_data.py

Since tests are parallelized, the temporary test name must be unique.

meta tests: fix flake

---

mypy-requirements.txt
pyproject.toml
setup.py

Mypy started using `typing_extensions.Self` which is only available in `>=4.0.0`.
https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-401-november-30-2021
Fixes: #15487

Bump typing_extensions dependency

---

test-requirements.txt

Pip version `21.3` is required to support editable installs with PEP 660. Currently, the mypy wheel build fails for `cp38-macosx_x86_64` with the following error:
```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /Users/runner/work/mypy_mypyc-wheels/mypy_mypyc-wheels/mypy/test-data/packages/typedpkg
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```
https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/5323325694/jobs/9640999946#step:4:6103
https://pip.pypa.io/en/stable/news/#id232

Add pip as test requirement to support editable installs in tests with PEP 660

---

mypy/build.py

All recent versions (declared in `setup.py`) have `TypedDict` there. So, no need to use `mypy-extensions` here.
(crossref: found while working on https://github.com/typeddjango/django-stubs/pull/1566)

Do not import `TypedDict` from `mypy-extensions`, use `typing-extensions`

---

mypy/test/testpep561.py
test-requirements.txt

This reverts #15482. Upgrading pip was the right idea, however the test case creates a new temporary venv which still uses the original pip version. Added a new call to upgrade pip to `pip>=21.3.1` for editable installs.
This does indeed fix the issue. I was able to verify it with Github Actions on my fork.
/CC: @hauntsaninja

Fix PEP 561 - editable install - test case

---

docs/source/extending_mypy.rst

All other hooks have `()`, so adding it will make the docs consistent.
Right now it is:

Use `()` for `get_function_sig_hook` docs

---

test-requirements.txt

We don't use either of these in our own code at all. Neither of them should be needed in 2023.
py used to be a dependency of pytest but no longer is. It was added to test-requirements.txt 6 years ago in order to pin a specific version to fix an issue where some tests were failing: https://github.com/python/mypy/commit/5168c2580ff81ba114776936bdeaf5d81812c34a and https://github.com/python/mypy/commit/ad6dd4ed6923a5eb6227fc9bfcb8e30a5e0fde53.
pytest-forked used to be a dependency of pytest-xdist, but no longer is. It was added to test-requirements.txt` 4 years ago in order to pin a specific version to fix builds on macOS: https://github.com/python/mypy/commit/e006b94e097184451e6baf9b9c55e56176728ab8.

Remove `py` and `pytest-forked` test dependencies

---

test-requirements.txt

pytest 7.4.0 was just released, and our CI on `master` is very red as a result. Looks like we're using a private API that we shouldn't be: https://github.com/python/mypy/pull/15501#issuecomment-1604177495. For now let's just pin to pytest <7.4.0.
https://pypi.org/project/pytest/7.4.0/

Unbreak CI

---

mypy/fastparse.py
test-data/unit/check-async-await.test

Fix async iterator body stripping

---

mypyc/codegen/emitclass.py

Got this working with a little trial and error.
Work on mypyc/mypyc#995.

[mypyc] Fix classes with __dict__ on 3.12

---

mypyc/lib-rt/exc_ops.c

I think we relied on undocumented behavior on older Python versions. Now it works consistently across all supported Python versions.
Work on mypyc/mypyc#995.

[mypyc] Fix generators on Python 3.12

---

mypy/semanal_main.py

This reverts commit 66602fcde3468d7a284aa89cb280d448f454e07b.
For https://github.com/python/typeshed/pull/10351

Revert "Fix spurious errors on builtins.open (#15161)"

---

mypy/plugins/dataclasses.py

It is not needed, because it is always serialized as `bool` and is always present.
It was added a long time ago in https://github.com/python/mypy/pull/10867 as a compat layer. But, since then we've added at least one `is_neither_frozen_nor_nonfrozen` attribute that is serialized / deserialized in a common way.
So, let's remove this hack for good.

Remove special handling of `kw_only` in `dataclass` plugin serialization

---

mypyc/lib-rt/int_ops.c

Two recent mypyc PRs didn't work together (#15470 and #15464). Fix them.

[mypyc] Fix i16 on Python 3.12

---

.readthedocs.yaml
mypyc/.readthedocs.yaml

[ReadTheDocs will stop building projects without a configuration file in September](https://blog.readthedocs.com/migrate-configuration-v2/). Let's migrate early. Not sure how to test this, frankly. 
@hauntsaninja I'll need your help as I don't have admin access to the mypy RTD project. Once this is merged, you'll have to set this field for mypy.
(I can set this for mypyc myself.)

Add ReadTheDocs configuration files

---

mypy/nodes.py
test-data/unit/check-protocols.test

Fixes #11884
Fixes #11886
Tests have been added for these cases.
PR is based on #11885
@sobolevn
CPython holds a collection of attributes which it excludes from protocols. [It can be viewed here](https://github.com/python/cpython/blob/fc32522b081c895f3798e4a16788b800cff08166/Lib/typing.py#L1672-L1693). This list isn't a public part of the API so I copied it into Mypy.  Using this collection directly from Python would cause version-based problems anyways.
I'm not sure about where `EXCLUDED_ATTRIBUTES` should go in Mypy.  Different versions of CPython also exclude different things and I'm not sure how to handle that in Mypy's source.  `__class_getitem__` was added to this collection in Python 3.9 for example. This is using the latest version of the collection which is likely to change again …

Exclude the same special attributes from Protocol as CPython

---

pyproject.toml

Fix sdist and python wheel build.
https://github.com/mgedmin/check-manifest
https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/5384036273/jobs/9771489841#step:5:32

Fix check-manifest action

---

.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
mypy/copytype.py
pyproject.toml
test-requirements.txt
tox.ini

- Add `fix = true` to `pyproject.toml`. This means ruff will apply autofixes when possible if `ruff .` is run (and will apply autofixes to PRs).
- Remove isort as a test dependency; just use ruff instead. It has the same import-sorting style, is faster, and requires less configuration.
- Remove an outdated paragraph in `CONTRIBUTING.md` about how you'll get a CI failure if you don't run black and isort before filing a PR. This is no longer true since we switched to using pre-commit.ci.

Improve ruff config

---

docs/source/error_code_list.rst
docs/source/error_code_list2.rst
docs/source/html_builder.py
mypy/errorcodes.py

I am adding these mostly to get rid of the allowlist in `html_builder.py`, please feel free to tweak these docs, cc @JukkaL @hauntsaninja @JelleZijlstra

Add missing docs for error codes

---

mypyc/irbuild/classdef.py

Fixes #15542
This fixes tests for me locally, but the situation will still be problematic, in that things won't work on 3.7 if you have this code and have older typing-extensions, or if you don't have this code and you have newer typing-extensions.
Given that 3.7 is dead, I'm not sure we need to care much, but this will hopefully get CI green for now.

Fix tests on 3.7

---

mypy/main.py

Fixes #15527
Namespaces are untyped, so this only gets caught by mypyc.
I didn't know about this feature, looks like it's explicitly documented as experimental. Guess no one has used it in a long, long time.

Fix find occurrences flag

---

mypy/checkmember.py
mypy/plugins/dataclasses.py
mypy/semanal.py
test-data/unit/check-selftype.test
test-data/unit/pythoneval.test

Fixes #15529
The fix is straightforward, hopefully there will be no fallout. (Note that #14075 would also fix this, but I am still not sure we should do that)

Rebind self-types in subclass methods without Self annotation

---

mypy-requirements.txt
mypyc/irbuild/classdef.py
pyproject.toml
setup.py

The changes made in #15543 mean that mypy's tests will no longer pass if you've got `typing_extensions<4.7` installed and you're running on Python 3.7. But if we go with this solution instead, our tests will pass on Python 3.7 regardless of whether you have `typing_extensions==4.6.3` or `typing_extensions==4.7.0` installed. (I've verified this locally.)

Enforce typing_extensions >=4.7.0 on py37

---

mypyc/doc/differences_from_python.rst
mypyc/doc/native_classes.rst
mypyc/doc/using_type_annotations.rst

[mypyc] Document more unsupported features & update supported features

---

mypyc/test-data/driver/driver.py

Fix stdout flushing to avoid empty lines getting out of alignment with the rest of the output.
Display the name of a failed test function, since it's sometimes not visible in the traceback
(at least if some incorrectly propagates exceptions).

[mypyc] Improve failure reporting in default run test driver

---

mypyc/codegen/emitclass.py

This fixes the testPickling test case in mypyc/test-data/run-classes.test on Python 3.12.
Handle another case that was missed in #15471. On 3.12 we rely on Py_TPFLAGS_MANAGED_DICT and shouldn't define an explicit `__dict__` member.
Work on mypyc/mypyc#995.

[mypyc] Fix 3.12 issue with pickling of instances with __dict__

---

mypy/expandtype.py
mypy/test/testtypes.py

Now it passes:
```
» pytest mypy/test/testtypes.py   
=================================== test session starts ===================================
platform darwin -- Python 3.11.3, pytest-7.3.2, pluggy-1.2.0
rootdir: /Users/sobolev/Desktop/mypy
configfile: pyproject.toml
plugins: cov-4.1.0, xdist-3.3.1
12 workers [116 items]    
.......................................s...................s....................... [ 71%]
.................................                                                   [100%]
============================= 114 passed, 2 skipped in 0.63s ==============================
```
I've also fixed this problem:
```
» python mypy/expandtype.py
File "/Users/sobolev/Desktop/mypy/mypy/expandtype.py", line 7, in <module>
import …
```

Solve import cycles for `mypy/expandtype.py` and `mypy/test/testtypes.py`

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test
test-data/unit/pythoneval.test

There were few cases when someone forgot to call `strict_optional_set()` in dataclasses plugin, let's move the calls directly to two places where they are needed for typeops. This may cause a tiny perf regression, but is much more robust in terms of preventing bugs.

Fix strict optional handling in dataclasses

---

mypy/semanal_namedtuple.py
test-data/unit/check-newsemanal.test

It appears that mypy currently synthesises two fictional parameters for the NamedTuple classmethod `_make()`: `new` and `len`. I'm not sure why we do this? They've never existed at runtime, and all tests pass if we remove them (except for two that need to be changed slightly, due to the output of `reveal_type(namedtuple_cls._make)` changing).
It looks like we've been adding these parameters since support for `_make()` was first added in 2016: https://github.com/python/mypy/pull/1810. I can't find any reference in that PR thread about why we add these parameters, however.
This PR proposes that we stop adding these parameters, which makes the output of `reveal_type(namedtuple_class._make)` much more accurate :)

Don't add strange fictional parameters to the signature of `NamedTuple._make()`

---

mypyc/build.py

Python 3.12 no longer ships `distutils` (PEP 632), so we must rely on `setuptools`, which
includes a vendored (but modified) version of `distutils`. However, the stubs for the vendored
`distutils` are not very complete, so we need some workarounds to pass type checking.

[mypyc] Fix self-compilation on Python 3.12

---

misc/sync-typeshed.py

If misc/sync-typeshed.py fails to apply a cherry pick, it just fails. Let's try to give the user a chance to manually merge the CP and continue with the script.
This should block for user input only in cases where stdin is a tty. So automation should continue failing. (but the only way to test is by running it)

When sync-typeshed fails to apply CP allow manual user merges

---

mypyc/test-data/run-classes.test
test-requirements.txt

Only one test fails if we remove `six` as a test dependency. The test was added in https://github.com/python/mypy/pull/8119, and isn't really testing anything to do with `six` specifically -- it's just a general test for mypyc's handling of metaclasses -- so I think it's fine to change the test so that it just doesn't import `six` anymore. We will still have plenty of other tests that check that mypy's special handling of `six` works correctly.

Remove `six` as a test dependency

---

mypy/test/helpers.py
mypy/test/testcheck.py
mypy/test/testfinegrained.py

Enabling `--strict-optional` in all test files would require a lot of changes currently. This PR adds a blacklist for test files which still require `--no-strict-optional`. It will allow us to update those incrementally.
_The same could be done for the `force_uppercase_builtins` and `force_union_syntax` settings afterwards._

Add foundation to enable `--strict-optional` in all test files

---

mypy/test/testcheck.py
test-data/unit/check-abstract.test
test-data/unit/check-async-await.test
test-data/unit/check-classes.test
test-data/unit/check-enum.test

Enable strict optional for more test files (1)

---

mypy/test/testcheck.py
test-data/unit/check-functions.test
test-data/unit/check-generic-subtyping.test
test-data/unit/check-generics.test

Followup to https://github.com/python/mypy/pull/15586

Enable strict optional for more test files (6)

---

mypyc/lib-rt/misc_ops.c

Fix the testProtocol test case in mypyc/test-data/run-classes.test.
There was a comment indicating that the code that causes the test to fail on 3.12 is required Python versions older than 3.7, so let's remove it. We only support 3.8 and later these days.
Work on https://github.com/mypyc/mypyc/issues/995.

[mypyc] Fix multiple inheritance with a protocol on Python 3.12

---

test-requirements.txt

`lxml==4.9.3` was released yesterday which caused the wheel builder to fail again.
https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/5473072463/jobs/9966070811#step:4:6979
The `lxml` project decided to change the manylinux builds from `manylinux2014` to `manylinux_2_28`. Thus to test our wheels we would need to compile `lxml` from source. Until will update to `manylinux_2_28` ourselves, I think pinning `lxml<4.9.3` is the best option.
https://pypi.org/project/lxml/4.9.2/#files
https://pypi.org/project/lxml/4.9.3/#files

Add upper bound for lxml

---

mypy/test/testcheck.py
test-data/unit/check-namedtuple.test
test-data/unit/check-overloading.test
test-data/unit/check-plugin-attrs.test
test-data/unit/check-statements.test
test-data/unit/check-tuples.test

Followup to https://github.com/python/mypy/pull/15586

Enable strict optional for more test files (8)

---

mypy/test/testcheck.py
test-data/unit/check-modules.test
test-data/unit/check-unions.test
test-data/unit/check-varargs.test

Followup to https://github.com/python/mypy/pull/15586
This will be the last one 🚀

Enable strict optional for more test files (9)

---

mypy/stubdoc.py
mypy/test/teststubgen.py

Encourted this while testing stubgen on pandas:
```console
$ stubgen -p pandas
File "/tmp/.venv/bin/stubgen", line 8, in <module>
sys.exit(main())
File "mypy/stubgen.py", line 1945, in main
File "mypy/stubgen.py", line 1799, in generate_stubs
File "/tmp/.venv/lib/python3.10/site-packages/mypy/stubgenc.py", line 212, in generate_stub_for_c_module
generate_c_type_stub(
File "/tmp/.venv/lib/python3.10/site-packages/mypy/stubgenc.py", line 528, in generate_c_type_stub
generate_c_function_stub(
File "/tmp/.venv/lib/python3.10/site-packages/mypy/stubgenc.py", line 337, in generate_c_function_stub
inferred = sig_gen.get_method_sig(
File "/tmp/.venv/lib/python3.10/site-packages/mypy/stubgenc.py", line 140, in get_method_sig
inferred = self.get_function_sig(cls, …
```

stubdoc: Fix crash on non-str docstring

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test

Support optional for custom dataclass descriptors

---

mypy/stubgen.py
test-data/unit/stubgen.test

These are treated the same way as `TypeVar` except imported from `typing_extensions` instead of `typing` by default.

stubgen: Support `ParamSpec` and `TypeVarTuple`

---

mypy/test/data.py
test-requirements.txt

The 7.4.0 release of pytest broke mypy because we were using some undocumented, private API that was removed. Ideally we'd stop using the private API, but nobody seems to remember why we started using the private API in the first place (see https://github.com/python/mypy/pull/15501#issuecomment-1607083799, and following comments). For now it (unfortunately) seems safer to just migrate to the new private API rather than try to figure out an alternative using public API.
I also took @bluetech's advice in https://github.com/python/mypy/pull/15501#issuecomment-1606259499 to improve the type annotations in the method in question.

Bump pytest to >=7.4.0

---

mypy/test/data.py

Fixes a [gotcha](https://github.com/python/mypy/pull/15283#issuecomment-1631820071) with `--update-data`.
When using `--update-data` with parallelized tests (xdist), the line offsets determined at test time may become wrong by update time, as multiple workers perform their updates to the same file.
This makes it so we exit with a usage error when `--update-data` is used with parallelism.

tests: --update-data incompatible with xdist

---

mypy/plugins/attrs.py
mypy/plugins/default.py
test-data/unit/check-plugin-attrs.test

Fixes #15639.
The new-style API `attrs.define` [enables slots by default](https://www.attrs.org/en/stable/api.html#attrs.define).

attrs: define defaults to slots=True

---

mypy/checkexpr.py
test-data/unit/check-abstract.test

The PR is quite simple (and I would like to keep it this way): 
- Before we were only checking `type[]` type
- Now we also check `tuple[type[], ...]` type
There might be other types that we want to add in the future here: `TypedDictType`, etc?
But, let's do it one by one, because smaller PRs are easier to merge :)
Closes #15264

Check tuples of abstract types

---

mypy/fastparse.py

This fixes the test case testFStringWithFormatSpecifierExpression on Python 3.12.
Strip redundant empty string literal from AST generated from f-string. It's not generated on earlier Python versions and it seems fine to just drop it.

Fix parse test case on Python 3.12

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Closes https://github.com/python/mypy/issues/15647

Add runtime `__slots__` attribute to dataclasses

---

mypy/plugins/attrs.py
test-data/unit/check-plugin-attrs.test

This is similar to https://github.com/python/mypy/pull/15649 but for `attrs` :)
Refs https://github.com/python/mypy/issues/15647

Add runtime `__slots__` attribute to `attrs`

---

mypy/checker.py
mypyc/test-data/run-misc.test
test-data/unit/check-classes.test
test-data/unit/check-fastparse.test
test-data/unit/check-incremental.test
test-data/unit/check-inference-context.test
test-data/unit/check-native-int.test
test-data/unit/check-statements.test
test-data/unit/check-typevar-tuple.test
test-data/unit/check-unreachable-code.test
test-data/unit/fine-grained.test

- On module-level, now we'll skip remaining statements once unreachable. This brings the behavior in line with function-level behavior.
- For module and function code, if `--warn-unreachable` is enabled, we'll emit an error, just once, on the first unreachable statement that's not a no-op statement. Previously a no-op statement would not have the "Unreachable statement" error, but the subsequent statements did not have the error either, e.g.
```diff
raise Exception
assert False  # no error since it's a "no-op statement"
-foo = 42
+foo = 42  # E: Unreachable statement
spam = "ham"  # no error since we warn just once
```

Consistently avoid type-checking unreachable code

---

test-data/unit/check-literal.test

Since #15386, any uninhabited type in module scope causes the rest of the block to go unchecked.
Fixes #15657.

Fix testLiteralMeets failure

---

mypy/checker.py
mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test
test-data/unit/deps.test

The root cause is hacky creation of incomplete symbols; instead switching to `add_method_to_class` which does the necessary housekeeping.
Fixes #15618.

Fix dataclass/protocol crash on joining types

---

mypy/typeshed/stdlib/unittest/mock.pyi

Typeshed cherry-pick: Fix @patch when `new` is missing (#10459)

---

mypy/defaults.py
mypy/main.py
mypy/test/helpers.py

Remove the `--py2` argument. It already creates a parser error.
https://github.com/python/mypy/blob/7a9418356082092d2cb1585acb816b2074cff43e/mypy/main.py#L1267-L1271

Remove `--py2` argument

---

mypy/test/data.py
test-data/unit/check-literal.test

The "Skip path normalization" option applies to all [out]s of a test case, so it's more correct for it to be a "case" option rather than an "out" option.
This also simplifies the parsing of "out" sections' args.

tests: skip-path-normalization should be a testcase option

---

mypy/checker.py
test-data/unit/check-typevar-unbound.test
test-data/unit/deps-generics.test

Completes a `TODO` item :)
Refs https://github.com/python/mypy/issues/15724

Raise errors on unbound TypeVars with values

---

mypy/stubtest.py

Cherry-pick of https://github.com/python/mypy/commit/6bdcc92002a5e1a6feb1528d0221802f7514c836 to the release 1.5 branch. This fixes a recent stubtest regression that was inadvertently introduced by https://github.com/python/mypy/commit/6f2bfff521e708f015af1eec5118db4600b829be

[release 1.5 cherry-pick] stubtest: Fix `__mypy-replace` false positives (#15689)

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

It exists at runtime.
Fixes #15748

Add `__match_args__` to dataclasses with no fields 

---

mypy/stubgen.py
test-data/unit/stubgen.test

Closes https://github.com/python/mypy/issues/15638

[stubgen] Add required `...` rhs to `NamedTuple` fields with default values

---

mypy/checker.py
test-data/unit/check-narrowing.test

`flatten_types` forgot about the second way we represent `tuple` inside.
Closes https://github.com/python/mypy/issues/15443

Correctly narrow types for `tuple[type[X], ...]`

---

mypy/test/teststubtest.py

This is a test case for https://github.com/python/mypy/pull/15680 from `stubtest`'s point of view.

[stubtest] Test `NamedTuple` definitions with default fields

---

tox.ini

Remove the Python 37 environment from the `tox.ini` since Python 3.7 is now end of life.

Remove the Python 37 environment from the `tox.ini`

---

mypy/erasetype.py
mypy/nodes.py
mypy/patterns.py
mypy/server/astmerge.py
mypy/types.py

While working on https://github.com/python/mypy/pull/15776 I've noticed that some `RuntimeError` do not have enough metadata to understand what is going on.
CI: https://github.com/python/mypy/actions/runs/5700479199/job/15450345887
This is the traceback I got:
```
_______________________ testNamedTupleNestedClassRecheck _______________________
[gw1] linux -- Python 3.10.12 /home/runner/work/mypy/mypy/.tox/py/bin/python
data: /home/runner/work/mypy/mypy/test-data/unit/fine-grained.test:10213:
/home/runner/work/mypy/mypy/.tox/py/lib/python3.10/site-packages/_pytest/runner.py:341: in from_call
result: Optional[TResult] = func()
/home/runner/work/mypy/mypy/.tox/py/lib/python3.10/site-packages/_pytest/runner.py:262: in <lambda>
lambda: ihook(item=item, **kwds), when=when, reraise=reraise …
```

Raise `RuntimeError` with better error messages

---

runtests.py
tox.ini

It solves two problems:
1. `fix_annotate` and `async_matrix` were removed in https://github.com/python/mypy/pull/15728
2. It is better to reuse stuff like `runtests.py` not to rewrite the same command we already have

Better `tox` configuration

---

mypy/checker.py
test-data/unit/check-plugin-attrs.test
test-data/unit/fixtures/plugin_attrs.pyi

Fixes #15393. A little hacky, but not an unreasonable way of providing type context.

Fix inference for attrs.fields

---

mypy/messages.py
mypy/test/testtypes.py
mypy/types.py
test-data/unit/check-async-await.test
test-data/unit/check-dataclasses.test
test-data/unit/check-namedtuple.test
test-data/unit/check-overloading.test
test-data/unit/check-python310.test
test-data/unit/check-tuples.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typevar-tuple.test
test-data/unit/fine-grained.test
test-data/unit/typexport-basic.test

Closes https://github.com/python/mypy/issues/15782

Change `tuple[]` repr to `tuple[()]`

---

mypy/checker.py
mypy/checkexpr.py
mypy/plugins/common.py
mypy/suggestions.py
mypy/types_utils.py
test-data/unit/check-narrowing.test
test-data/unit/fixtures/primitives.pyi

Fixes #15759.
The type narrowing logic internally used `is_optional()` to check whether an operand type might be None. `is_optional()` only considers `UnionType`, and ignored an immediate `NoneType` type, which clearly is None-able.
I have created a new helper `can_be_none()`, which does also consider immediate `NoneType`.
The narrowing logic here could be further improved, but that's out of scope for the bugfix.
```python
def func(val: str | None) -> None:
if val == None:
reveal_type(val)  # ❌ Revealed type is "builtins.str"
if val in (None,):
reveal_type(val)  # ❌ Revealed type is "builtins.str"
def func(val: str | None) -> None:
if val == None:
reveal_type(val)  # ✅ Revealed type is "Union[builtins.str, None]"
if val in (None,):
reveal_type(val)  # ✅ Revealed type is …
```

Fix type narrowing of `== None` and `in (None,)` conditions

---

.pre-commit-config.yaml

The black pre-commit mirror is now hosted at: https://github.com/psf/black-pre-commit-mirror

Update black pre-commit mirror link

---

mypy/solve.py
mypy/test/testsolve.py
mypy/test/typefixture.py
test-data/unit/check-generics.test

This is a third PR in series following https://github.com/python/mypy/pull/15287 and https://github.com/python/mypy/pull/15754. This one is quite simple: I just add basic support for polymorphic inference involving type variables with upper bounds and values. A complete support would be quite complicated, and it will be a corner case to already rare situation. Finally, it is written in a way that is easy to tune in the future.
I also use this PR to add some unit tests for all three PRs so far, other two PRs only added integration tests (and I clean up existing unit tests as well).

New type inference: add support for upper bounds and values

---

docs/source/error_code_list.rst

See https://github.com/python/mypy/pull/14740
My PR was pretty old and predates the nice check to ensure error codes are documented.

Document new import error codes

---

mypyc/codegen/emitclass.py
mypyc/codegen/emitmodule.py
mypyc/common.py
mypyc/test/testutil.py

Looks like `capi_version < 3.7` is not supported, so I changed the lowest version to be `3.7`.
Based on the discord discussion.

The oldest CAPI version we support right now is 3.7

---

MANIFEST.in

Add tox.ini to sdist

---

mypy/plugins/attrs.py
test-data/unit/check-plugin-attrs.test

Fix inheriting from generic @frozen attrs class

---

mypy/typeops.py
test-data/unit/check-unreachable-code.test

This adds support for `Literal` as return type of `__bool__` in the reachability analysis.
Example:
```
class AlwaysFalse:
def __bool__(self) -> Literal[False]: ...
if AlwaysFalse():
x = 1                   <- this line is unreachable
```
Addresses https://github.com/python/mypy/issues/7008
Fixes parts of https://github.com/python/mypy/issues/15523 (Handling `bool()` should probably be a separate PR)
To be honest, I did not understand what the purpose of this code was / why "the branch was even taken or analzyed" before: 
```
if ret_type and ret_type.can_be_false and not ret_type.can_be_true:
new_t = copy_type(t)
new_t.can_be_true = False
return new_t
```
Now instead of the branch is taken with the updated type, it is marked as unreachable.
Edit: It is probably for the case that …

Support __bool__ with Literal in --warn-unreachable

---

mypy/applytype.py
test-data/unit/check-typevar-defaults.test

Use TypeVar defaults to resolve fallback return type of functions.
**Note**: Defaults for TypeVarTuples don't yet work, probably a result of the limited support for `Unpack` / `TypeVarTuple`.
Ref: #14851

Apply TypeVar defaults to functions (PEP 696)

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/checkexpr.py
mypy/config_parser.py
mypy/main.py
mypy/options.py
test-data/unit/check-flags.test

Fixes #10757 
It is surprisingly one of the most upvoted issues. Also it looks quite easy to implement, so why not. Note I also try to improve docs for per-module logic for `disallow_untyped_calls`, as there is currently some confusion.

Add option to selectively disable --disallow-untyped-calls

---

test-data/unit/check-formatting.test

Adds a regression test for #12665, which is a strange bug that was fixed somewhat by accident

Add regression test for fixed bug involving bytes formatting

---

test-data/unit/fixtures/primitives.pyi

This fixes some weird test failures I was seeing locally when trying to run just the tests in `check-enum.test` (invoked via `pytest mypy/test/testcheck.py::TypeCheckSuite::check-enum.test`):
<details>
```pytb
> pytest mypy/test/testcheck.py::TypeCheckSuite::check-enum.test
=================================================================== test session starts ===================================================================
platform win32 -- Python 3.11.2, pytest-7.4.0, pluggy-1.2.0
rootdir: C:\Users\alexw\coding\mypy
configfile: pyproject.toml
plugins: cov-4.1.0, xdist-3.3.1
4 workers [99 items]
............................................................F...F.......F..........................                                                  [100%] …
```

Add missing type annotations to the `primitives.pyi` fixture

---

docs/source/error_code_list.rst
docs/source/more_types.rst
docs/source/runtime_troubles.rst
tox.ini

Fixes #13196.
Enable the nit-picky mode on sphinx-build in tox, as this will facilitate the detection of potential issues related to missing references.

Fix all the missing references found within the docs

---

mypy/applytype.py
mypy/checker.py
mypy/checkexpr.py
mypy/constraints.py
mypy/expandtype.py
mypy/join.py
mypy/meet.py
mypy/options.py
mypy/solve.py
mypy/subtypes.py
mypy/test/testtypes.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/typeops.py
mypy/types.py
test-data/unit/check-functions.test
test-data/unit/check-generics.test
test-data/unit/check-inference-context.test
test-data/unit/check-inference.test
test-data/unit/check-overloading.test
test-data/unit/check-parameter-specification.test

This is a third follow-up for https://github.com/python/mypy/pull/15287 (likely there will be just one more PR, for `TypeVarTuple`s, and few less important items I mentioned in the original PR I will leave for more distant future).
After all this PR turned out to be larger than I wanted. The problem is that `Concatenate` support for `ParamSpec` was quite broken, and this caused many of my tests fail. So I decided to include some major cleanup in this PR (I tried splitting it into a separate PR but it turned out to be tricky). After all, if one ignores added tests, it is almost net zero line count.
The main problems that I encountered are:
* First, valid substitutions for a `ParamSpecType` were: another `ParamSpecType`, `Parameters`, and `CallableType` (and also `AnyType` and …

Polymorphic inference: support for parameter specifications and lambdas

---

mypy/dmypy/client.py

When running dmypy, the communication between client and server is via JSON. The JSON contains the keys "out" and "err" for the actual result of "check" command, and "stdout" and "stderr" for the any other stdout and stderr text.
show_stats is shown when running with --verbose. It's meant to show other keys in the JSON response, like python version or time taken. It already had some special casing to only show 1 line of text for "out" and "err". Let's add "stdout" and "stderr" to the special casing as well. Also, let's show the remaining number of characters as well.
Finally, added a comment in code about stdout, stderr, out, err and how we shouldn't confuse them. (I did)
Some more cleanup is needed in this area of the codebase, but will be a separate PR.
show_stats outputs something like …

[dmypy] special case stdout and stderr in show_stats too

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/semanal.py
test-data/unit/check-generics.test
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test
test-data/unit/check-parameter-specification.test
test-data/unit/lib-stub/functools.pyi

Fixes https://github.com/python/mypy/issues/15737
Fixes https://github.com/python/mypy/issues/12844
Fixes https://github.com/python/mypy/issues/12716
My goal was to fix the `ParamSpec` issues, but it turns out decorated overloads were not supported at all. Namely:
* Decorators on overload items were ignored, caller would see original undecorated item types
* Overload item overlap checks were performed for original types, while arguably we should use decorated types
* Overload items completeness w.r.t. to implementation was checked with decorated implementation, and undecorated items
Here I add basic support using same logic as for regular decorated functions: initially set type to `None` and defer callers until definition is type-checked. Note this results in few more `Cannot determine …

Basic support for decorated overloads

---

mypy/semanal.py
mypy/typeanal.py
test-data/unit/check-literal.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-typevar-defaults.test
test-data/unit/semanal-errors.test

Fixes https://github.com/python/mypy/issues/14761
Fixes https://github.com/python/mypy/issues/15318
Fixes https://github.com/python/mypy/issues/14656
Fixes https://github.com/python/mypy/issues/13518
I noticed there is a bunch of inconsistencies in `semanal`/`typeanal` for ParamSpecs, so I decided do a small cleanup. Using this opportunity I also allow `Concatenate[int, ...]` (with literal Ellipsis), and reduce verbosity of some errors.
cc @A5rocks

Allow Ellipsis in Concatenate; cleanup ParamSpec literals

---

mypy/typeops.py
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/14968
Fixes https://github.com/python/mypy/issues/13911
The fix is simple, as I predicted on Discord, we simply should use `get_all_type_vars()` instead of `get_type_vars()` (that specifically returns only `TypeVarType`). I also use this opportunity to tidy-up code in `bind_self()`, it should be now more readable, and much faster (especially when compiled with mypyc).
cc @A5rocks

Support self-types containing ParamSpec

---

mypy/checker.py
test-data/unit/check-python310.test

Improve match narrowing and reachability analysis

---

mypy/stubgen.py

I noticed that almost all calls to `typing_name` also call `add_typing_import`.

(🎁) `StubGenerator.add_typing_import` returns the name

---

mypy/checkexpr.py
test-data/unit/check-expressions.test

Now it is quite the same as `reveal_type`. Which is defined here: https://github.com/python/mypy/blob/2c1fd97986064161c542956bb3d9d5043dc0a480/mypy/checkexpr.py#L4297
Closes #15851

Fix `assert_type` failures when some nodes are deferred

---

mypy/stubtest.py
mypy/test/teststubtest.py
test-data/unit/lib-stub/enum.pyi

Fixes #15923.
Note: the test cases I've added reproduce the crash, but only if you're using a compiled version of mypy. (Some of them only repro the crash on <=py310, but some repro it on py311+ as well.)
We run stubtest tests in CI with compiled mypy, so they do repro the crash in the context of our CI.

Fix edge-case stubtest crashes when an instanace of an `enum.Flag` that is not a member of that `enum.Flag` is used as a parameter default

---

mypy/checkmember.py
test-data/unit/check-classes.test
test-data/unit/check-incremental.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-plugin-attrs.test
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/15934
I think this is a right thing to do, it may even fix some other rare accidental `TypeVar` clashes not involving self-types. This causes a bit of churn in tests, but not too much.

Use TypeVar refresh uniformly for class object access

---

mypy/typeanal.py
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/15948
The fix is straightforward: invalid type variable resulted in applying type arguments packing/simplification when we shouldn't. Making the latter more strict fixes the issue.
cc @A5rocks

Fix crash on invalid type variable with ParamSpec

---

mypy/exprtotype.py
mypy/fastparse.py
mypy/typeanal.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/15412
Two new things here as specified by PEP 646:
* Using star for an (explicit) type unpaking in callables, like `Callable[[str, *tuple[int, ...]], None]`
* Allowing suffix items after a variadic item, like `Callable[[X, Unpack[Ys], Z], bool]`
Implementation is straightforward. Btw while working in this I accidentally fixed a nasty bug, tuple types were often not given any line/column numbers, so if such type becomes a location of an error, it is impossible to ignore.

Support PEP 646 syntax for Callable

---

mypy/expandtype.py
mypy/maptype.py
mypy/nodes.py
mypy/semanal.py
mypy/semanal_typeargs.py
mypy/semanal_typeddict.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/15946
Note this actually adds support also for variadic NamedTuples and variadic TypedDicts. Not that anyone requested this, but since generic NamedTuples and generic TypedDicts are supported using the same mechanism (special aliases) as generic tuple types (like `class A(Tuple[T, S]): ...` in the issue), it looked more risky and arbitrary to _not_support them.
Btw the implementation is simple, but while I was working on this, I accidentally found a problem with my general idea of doing certain type normlaizations in `semanal_typeargs.py`. The problem is that sometimes we can call `get_proper_type()` during semantic analysis, so all the code that gets triggered by this (mostly `expand_type()`) can't really rely on types being normalized. …

Support user defined variadic tuple types

---

mypy/stubtest.py

I did a trial run with my typeshed fork using GitHub Actions to see what the results of running stubtest on typeshed's stdlib stubs were with mypy's master branch. It's a good job that I did, as it revealed that there were a few flaws in the logic I introduced in #15729:
- It's not easy to predict where stdlib modules are going to be located. (It varies between platforms, and between venvs and conda envs; on some platforms it's in a completely different directory to the Python executable.)
- Some modules appear to raise `SystemExit` when stubtest tries to import them in CI, leading stubtest to instantly exit without logging a message to the terminal.
- Importing some `test.*` submodules leads to unraisable exceptions being printed to the terminal at the end of the stubtest run, which is …

Fixes to stubtest's new check for missing stdlib modules

---

mypy/plugins/attrs.py
mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test
test-data/unit/check-plugin-attrs.test

Doing the same thing we do for regular classes.
Fixes #15975

attrs, dataclasses: don't enforce slots when base doesn't

---

mypy/expandtype.py
mypy/semanal_main.py
mypy/semanal_typeargs.py
test-data/unit/check-typevar-tuple.test

This is a small but possibly important PR. Wherever possible we should represent user error and/or failed type inference as `*tuple[Any, ...]`/`*tuple[<nothing>, ...]`, rather than `Unpack[Any]`/`Unpack[<nothing>]` or plain `Any`/`<nothing>`. This way we will not need any special casing for failure conditions in various places without risking a crash instead of a graceful failure (error message).

Optimize Unpack for failures

---

.github/workflows/build_wheels.yml
.github/workflows/docs.yml
.github/workflows/mypy_primer.yml
.github/workflows/test.yml
.github/workflows/test_stubgenc.yml

Two main changes:
1. Always use secure permissions, when some workflow does not do anything, it has to be `contents: read` only
2. Be more consistent with canceling workflows

Improve GitHub Actions specs

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclass-transform.test
test-data/unit/check-dataclasses.test
test-data/unit/lib-stub/_typeshed.pyi
test-data/unit/lib-stub/dataclasses.pyi

If the dataclasses plugin cannot determine a signature for `dataclasses.replace`, it should not report an error. The underlying typeshed signature will get a shot at verifying the type and reporting an error, and it would enable the following pattern (without typing `replace`'s kwargs, though):
```python
from dataclasses import is_dataclass, replace
def foo(x: object):
if is_dataclass(x) and not isinstance(x, type):
#
y = replace(x)
```

dataclasses.replace: fall through to typeshed sig

---

.github/workflows/docs.yml
.github/workflows/test.yml

Try upgrading tox

---

mypy/plugins/attrs.py
test-data/unit/check-plugin-attrs.test
test-data/unit/lib-stub/attrs/__init__.pyi

Since https://github.com/python-attrs/attrs/pull/890 (≥ 22.1.0) `attrs.fields` is typed to accept a protocol.
Since https://github.com/python-attrs/attrs/pull/997 (≥ 22.2.0) `attrs.has` is a type-guard.
Support both by removing the explicit error reporting and letting it fall through to the type stub.
Fixes #15980.

attrs: remove fields type check

---

mypy/checkmember.py
test-data/unit/check-functions.test

Fix inference for properties with __call__

---

mypy/checkexpr.py
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/15984
Fix is straightforward, `ParamSpec` inference special-casing should put instances with `__call__` and callable types on same ground.

Fix ParamSpec inference for callback protocols

---

mypy/messages.py
test-data/unit/check-async-await.test

For issue described in #5070 and documented in #14973, add a contextual link to the docs.

Add hint for AsyncIterator incompatible return type

---

mypy/version.py

We've cut the release branch for 1.6, so the dev version should now be 1.7.

Update version number for 1.6

---

mypy/checker.py

This e.g. makes sure both code paths receive my fix in #15688

Deduplicate iterable logic

---

mypy/config_parser.py

Fix crash when parsing error code config with typo

---

mypy/fastparse.py
mypy/test/helpers.py
mypy/test/testcheck.py
test-data/unit/check-python312.test

Mypy does not yet support PEP 695
Fixes #16011, linking #15238

Make PEP 695 constructs give a reasonable error message

---

mypy/build.py
mypy/errors.py
mypy/report.py
mypy/test/testcheck.py
mypy/test/testcmdline.py
mypy/test/testreports.py
test-data/unit/pep561.test

Fixes #16003. Follow up to #14740

Match note error codes to import error codes

---

docs/source/error_code_list.rst
mypy/messages.py
test-data/unit/check-errorcodes.test
test-data/unit/check-expressions.test
test-data/unit/check-functions.test
test-data/unit/check-inference.test
test-data/unit/check-optional.test
test-data/unit/check-tuples.test
test-data/unit/check-varargs.test
test-data/unit/pythoneval-asyncio.test

Fixes #3226.
Aims to provide better assistance to users who may be confused when their void functions technically return None.

Reword the error message related to void functions

---

mypy/report.py

Fixes #15979. Fix is similar to that in `iterate_python_lines`.

Fix crash with report generation on namespace packages (again)

---

docs/source/additional_features.rst

Document behavior discussed in https://github.com/python/typing/discussions/1456.

docs: document dataclass_transform behavior

---

docs/source/type_narrowing.rst

Fixes #15653.
I did not use @erictraut's "quantum entanglement" metaphor, though I find it to be quite illustrative :)

Document we're not tracking relationships between symbols

---

mypy/checkmember.py
mypy/config_parser.py
mypy/main.py
mypy/messages.py
mypy/solve.py
mypyc/ir/class_ir.py
mypyc/ir/ops.py
mypyc/ir/rtypes.py
pyproject.toml

For example, this [review comment](https://github.com/python/mypy/pull/15481#discussion_r1313755961) could've been spared with [UP036](https://beta.ruff.rs/docs/rules/outdated-version-block/).

ruff: add pyupgrade

---

mypy/nodes.py
mypy/semanal.py

Some builtin aliases are available for all python versions that we support. So, there's no need to check them in `semanal`:
https://github.com/python/mypy/blob/8738886861682e0d168ea321c2cc6ee5b566cb8b/mypy/semanal.py#L673-L689

Remove type aliases that are long supported

---

.github/workflows/build_wheels.yml
.github/workflows/docs.yml
.github/workflows/mypy_primer.yml
.github/workflows/sync_typeshed.yml
.github/workflows/test.yml
.github/workflows/test_stubgenc.yml

Looks like recent CI failures are related.
Release docs: https://github.com/actions/checkout/releases/tag/v4.0.0

Use latest `actions/checkout@v4`

---

docs/source/config_file.rst

Users don't know about them: https://github.com/typeddjango/pytest-mypy-plugins/issues/126
Since they are quite important for testing, I think that it is a must to include them.

Document `force_union_syntax` and `force_uppercase_builtins`

---

docs/source/command_line.rst

Refs https://github.com/python/mypy/pull/16048

Add docs about `--force-uppercase-builtins` and `--force-union-syntax`

---

mypy/options.py

Add `new_type_inference` to the list of options affecting the cache.

Clear cache when adding --new-type-inference

---

.github/workflows/docs.yml

1. #16061 added a new error code, but didn't add any docs for the new error code
2. Because nothing in the `docs/` directory was modified, the docs CI job didn't run on that PR
3. Now the docs build is failing on `master` because we have an error code without any documentation: https://github.com/python/mypy/actions/runs/6112378542/job/16589719563

Build the docs in CI for all PRs touching the `mypy/` directory

---

CONTRIBUTING.md
tox.ini

Documentation changes are visible [here](https://github.com/posita/mypy/blob/posita/0/tweak-contributing-docs/CONTRIBUTING.md#using-tox). Commit message below.
---
The blurb on how to use `tox` existed in the middle of the [**Running tests** section](/mypy/blob/master/CONTRIBUTING.md#running-tests), and was bookended without headings by non-`tox` workflow material. This more clearly delineates between `tox` and non-`tox` workflows for the newcomer.
This also non-invasively allows running arbitrary commands using `testenv:dev`.
``` sh
% tox -e dev
% tox -e dev -- mypy runtests.py
dev: commands[2]> mypy runtests.py
Success: no issues found in 1 source file
% tox -e dev --override testenv:dev.allowlist_externals+=env -- env
test_case.py
dev: commands[2]> env
HOME=/home/posita …
```

Clearly differentiate between venv and tox setups in CONTRIBUTING.md

---

mypy/checker.py
mypy/nodes.py
mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Fix __post_init__() internal error

---

docs/source/error_code_list.rst
docs/source/more_types.rst
mypy/errorcodes.py
mypy/messages.py
mypy/types.py
test-data/unit/check-errorcodes.test

A new error code was introduced in
https://github.com/python/mypy/pull/16061
As per https://github.com/python/mypy/pull/16068, we didn't previously run doc builds on changes to errorcodes.py, causing tests to fail on master when this was merged.
Renaming the code as per:
https://github.com/python/mypy/pull/16061#issuecomment-1710613890 All type ignores should be unsafe, so we should save the unsafe adjective for things that are really unsafe. As it stands, there are many cases where overloads overlap somewhat benignly.
Fixes #8656

Document and rename overload-overlap error code

---

mypy/plugins/common.py
test-data/unit/check-custom-plugin.test
test-data/unit/check-incremental.test
test-data/unit/deps.test
test-data/unit/plugins/add_overloaded_method.py

There are several changes:
1. `add_overloaded_method_to_class` itself. It is very useful for plugin authors, because right now it is quite easy to add a regular method, but it is very hard to add a method with `@overload`s. I don't think that user must face all the chalenges that I've covered in this method. Moreover, it is quite easy even for experienced developers to forget some flags / props / etc (I am pretty sure that I might forgot something in the implementation)
2. `add_overloaded_method_to_class` and `add_method_to_class` now return added nodes, it is also helpful if you want to do something with this node in your plugin after it is created
3. I've refactored how `add_method_to_class` works and reused its parts in the new method as well
4. `tvar_def` in `add_method_to_class` can …

Add `add_overloaded_method_to_class` helper to `plugins/common.py`

---

mypy/exprtotype.py
mypy/fastparse.py
mypy/semanal_typeargs.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-varargs.test

Fixes https://github.com/python/mypy/issues/16082
Currently we only allow `Unpack` of a TypedDict when it appears in a function definition. This PR also allows this in `Callable` types, similarly to how we do this for variadic types.
Note this still doesn't allow having both variadic unpack and a TypedDict unpack in the same `Callable`. Supporting this is tricky, so let's not so this until people will actually ask for this. FWIW we can always suggest callback protocols for such tricky cases.

Allow TypedDict unpacking in Callable types

---

mypy/main.py
mypy/meet.py
mypy/subtypes.py
test-data/unit/check-tuples.test

Follow up to #16073 and #16076
Fix needed for https://github.com/python/mypy/pull/16053/files#r1316481395
I add test cases that would have caught my previous incorrect PR. I add an explicit case for the new desirable behaviour we see with zip.

Fix tuple[Any, ...] subtyping

---

mypy/test/helpers.py

It's annoying that one line change causes everything else to show up as a diff. Just use difflib instead. I also highlight the changed lines. We can't use FancyFormatter because it doesn't work well with pytest.

Better diffs in tests

---

mypy/semanal_typeddict.py
test-data/unit/check-incremental.test

Fixes https://github.com/python/mypy/issues/15557
FWIW I simply copy the logic for handling malformed definitions from named tuples, that seems to be much more robust.

Fix crash on malformed TypedDict in incremental mode

---

mypy/checkexpr.py
test-data/unit/check-typeddict.test
test-data/unit/reports.test

Fixes https://github.com/python/mypy/issues/16107
Fixes https://github.com/python/mypy/issues/15891
I only vaguely remember why I added those context managers, it seemed to me giving full TypedDict as context may cause false positives. But since the current way causes crashes, let's just not do this (we will see if there will be actual false positives).

Fix crash on star unpack in TypedDict

---

mypy/errors.py

Fixes #15877
Regression was introduced by #15070. Previously Errors objects created in mypyc build would just use all the default values, now they use the actual options object involved

Fix mypyc regression with pretty

---

docs/README.md

fix: `$` in copied commands

---

mypy/semanal.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/dyn_class_from_method.py

Fixes: #8359
CC @sobolevn 
`get_dynamic_class_hook()` will now additionally be called for generic classes with parameters. e.g.
```python
y = SomeGenericClass[type, ...].method()
```

Call dynamic class hook on generic classes

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

I think the current error message is enough: https://github.com/python/mypy/issues/16141
CC @ikonst and @hauntsaninja

Fix crash on dataclass field / property collision

---

mypy/types.py

This slot was not used anywhere:
```
» ag is_classmethod_class .
```
Moreover, since it was not initialized this code was failing with `AttributeError`:
```python
x: CallableType
for i in dir(x):
print(i, getattr(x, i))  # failing on `is_classmethod_class`
```

Remove `is_classmethod_class` slot from `CallableType`

---

mypy/plugins/dataclasses.py

Fixed typo.
```
heirarchy -> hierarchy
```

Fix typo in dataclasses.py

---

mypy/solve.py
mypy/subtypes.py
mypy/test/testpep561.py
test-data/unit/check-inference-context.test
test-data/unit/check-inference.test
test-data/unit/check-varargs.test

Fixes https://github.com/python/mypy/issues/230
Fixes https://github.com/python/mypy/issues/6463
I bet it fixes some other duplicates, I closed couple yesterday, but likely there are more.
This may look a bit ad-hoc, but after some thinking this now starts to make sense to me for two reasons:
* Unless I am missing something, this should be completely safe. Special-casing only applies to inferred types (i.e. empty collection literals etc).
* Empty collections _are_ actually special. Even if we solve some classes of issues with more principled solutions (e.g. I want to re-work type inference against unions in near future), there will always be some corner cases involving empty collections.
Similar issues keep coming, so I think it is a good idea to add this special-casing (especially taking …

Special-case type inference of empty collections

---

mypy/solve.py
test-data/unit/check-inference.test

Fixes https://github.com/python/mypy/issues/13220
This looks a bit ad-hoc, but it is probably the least disruptive solution possible.

Use upper bounds as fallback solutions for inference

---

mypy/constraints.py
test-data/unit/check-inference.test

This should help with re-enabling the use of `ParamSpec` in `functools.wraps` (as it looks like some of the new errors in https://github.com/AlexWaygood/mypy/pull/11 are caused by not handling this).

Use type variable bound when it appears as actual during inference

---

mypy/checkexpr.py
mypy/constraints.py
mypy/erasetype.py
mypy/message_registry.py
mypy/types.py
test-data/unit/check-overloading.test
test-data/unit/check-tuples.test
test-data/unit/check-typevar-tuple.test

This improves support for two features that were supported but only partially: variadic calls, and variadic indexing. Some notes:
* I did not add dedicated support for slicing of tuples with homogeneous variadic items (except for cases covered by TypeVarTuple support, i.e. those not involving splitting of variadic item). This is tricky and it is not clear what cases people actually want. I left a TODO for this.
* I prohibit multiple variadic items in a call expression. Technically, we can support some situations involving these, but this is tricky, and prohibiting this would be in the "spirit" of the PEP, IMO.
* I may have still missed some cases for the calls, since there are so many options. If you have ideas for additional test cases, please let me know.
* It was necessary to fix …

Better support for variadic calls and indexing

---

mypy/checkexpr.py
test-data/unit/check-python38.test

This fixes a regression caused by https://github.com/python/mypy/pull/16122
@cdce8p Could you please check this fixes the issue for you? I tried your snippet and it passes, but there is a certain asymmetry in the reveal types that is hard to fix.

Fix walrus interaction with empty collections

---

test-data/unit/check-typevar-tuple.test

Supersedes https://github.com/python/mypy/pull/15254
Note the error message for one of the test is slightly different. Although it _may_ suggest that `Unpack[...]` is a valid type on its own, this error is kind of more consistent with old style `*args: int` annotations.
cc @JukkaL @jhance

Add more tests for variadic Callables

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/messages.py
test-data/unit/check-async-await.test

Fix error code on "Maybe you forgot to use await" note

---

mypy/checker.py
mypy/checkexpr.py
mypy/messages.py
mypy/plugins/proper_plugin.py
mypy/typeops.py
test-data/unit/check-abstract.test
test-data/unit/pythoneval.test

Fixes most of #12320. I didn't add tests for every code path because it's niche. I also didn't fix everything, in particular the cases where we proceed to use `ret_type`

Fix cases of type object handling for overloads

---

mypy/stubtest.py

Something I've seen come up several times in typeshed is that a runtime library will have a class similar to this (which is contrived, but you hopefully see the point):
```py
class Foo:
def __init__(self, **kwargs):
self.a = kwargs.pop('a')
self.b = kwargs.pop('b')
self.c = kwargs.pop('c')
if kwargs:
raise Exception("no")
```
Somebody will then come along and try to write stubs for this class like this, which is _nearly_ correct, except that all the arguments need to be keyword-only:
```py
class Foo:
def __init__(self, a: int = ..., b: int = ..., c: int = ...) -> None: ...
```
Stubtest then (correctly!) gets very angry and reports three errors for this function. However, none of the error messages tells the author of the stub that the arguments all need to be made keyword-only:
```
error: …
```

Stubtest: add a hint when arguments in the stub need to be keyword-only

---

mypyc/lib-rt/setup.py
mypyc/test/test_external.py

When running the mypy unittests, most of the time any output files are produced into a temporary directory and cleaned up. In one case, it wasn't. Fix this for test_capi.

tests: avoid leaving artifacts in the source tree

---

mypy/semanal.py
test-data/unit/check-classes.test

Resolves #10570
Resolves #6473

__qualname__ and __module__ are available in class bodies

---

mypy/argmap.py
mypy/checker.py
mypy/checkexpr.py
mypy/constraints.py
mypy/message_registry.py
mypyc/irbuild/mapper.py
test-data/unit/check-tuples.test
test-data/unit/check-typevar-tuple.test

This is includes also related things such as tuple concatenation, special-cased tuple "re-packing", and star tuple unpacking in homogeneous collections.
It looks like we are very close to the finish line (the only major missing feature is type narrowing using `len()`, apart from this I just need to do couple technical things, and make one final search for missed code paths).
Some notes:
* Unfortunately, star items on l.h.s create lists at runtime. This means there are various cases where `list[object]` is the best type we can have.
* Note I now infer "precise" types for expressions like `(x, *y, z)`, where `y` is say `tuple[int, ...]`. This may cause errors for code that previously worked (when we will turn this feature on). For example `(1, *[], 2)[42]` will be an error. As usual, I …

Support variadic tuple packing/unpacking

---

mypyc/doc/getting_started.rst
setup.py

Add an extra for mypyc dependencies

---

mypy/partially_defined.py
test-data/unit/check-possibly-undefined.test

Thanks @AlexWaygood for sending me on this adventure. This took me a while for me to debug!
When we don't need to warn about unreachable code, we don't end up calling `self.is_noop_for_reachability(s)` (which is meant to tell us whether the code should be warned about or is `raise AssertionError` or `typing.assert_never(never)` or something). https://github.com/python/mypy/blob/6f650cff9ab21f81069e0ae30c92eae94219ea63/mypy/checker.py#L2748
This innocuous check has a side effect that turns out to be important for the partially undefined checks. These checks work by reaching into the type map populated by the checker. But if we never actually ended up analysing the code, we never populate the type map.
This therefore changes things to assume that if we couldn't find the expression in the …

Fix partially defined in the case of missing type maps

---

mypy/dmypy_server.py

After dmypy starts serving, stdout and stderr gets captured. If we have an error, we assume we can send it to the client. However, if we have an error outside of client communication, that error is lost. The easiest way to see this is to run dmypy in daemonize mode, run a check once, then Control-C to send a KeyboardInterrupt. That exception is not printed though it should. After this change you can clearly see it.
```
term1$ python3 -m mypy.dmypy daemon
term2$ python3 -m mypy.dmypy check -v test.py
[... some output ...]
term1$ [Control-C]
^CTraceback (most recent call last):
File "/home/svalentin/src/mypy-svalentin/mypy/dmypy_server.py", line 220, in serve
with server:
File "/home/svalentin/src/mypy-svalentin/mypy/ipc.py", line 232, in __enter__
self.connection, _ = self.sock.accept() …
```

show dmypy errors post serving

---

mypy/expandtype.py
mypy/types.py
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/16245
Fixes https://github.com/python/mypy/issues/16248
Unfortunately I was a bit reckless with parentheses, but in my defense `unify_generic_callable()` is kind of broken for long time, as it can return "solutions" like ```{1: T`1}```. We need a more principled approach there (IIRC there is already an issue about this in the scope of `--new-type-inference`).
(The fix is quite trivial so I am not going to wait for review too long to save time, unless there will be some issues in `mypy_primer` etc.)

Fix crash on ParamSpec unification

---

pyproject.toml

Fix `coverage` config

---

mypy/expandtype.py
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/16257
Parenthesis strike back. I hope this is the last place where I had put them wrong.

Fix crash on ParamSpec unification (for real)

---

mypy/dmypy/client.py
mypy/dmypy_server.py
mypy/dmypy_util.py
mypy/ipc.py
mypy/test/testipc.py

This does 2 things:
1. It changes the IPC code to work with multiple messages.
2. It changes the dmypy client/server communication so that it streams stdout/stderr instead of dumping everything at the end.
For 1, we have to provide a way to separate out different messages. I chose to frame messages as bytes separated by whitespace character. That means we have to encode the message in a scheme that escapes whitespace. The urllib.parse quote/unquote seems reasonable. It encodes more than needed but the application is not IPC IO limited so it should be fine. With this convention in place, all we have to do is read from the socket stream until we have a whitespace character.
The framing logic can be easily changed.
For 2, since we communicate with JSONs, it's easy to add a "finished" key …

Stream dmypy output instead of dumping everything at the end

---

.pre-commit-config.yaml
test-requirements.txt

Release post: https://astral.sh/blog/ruff-v0.1.0

Bump test deps: `ruff` and `pre-commit-hooks`

---

mypy/semanal_classprop.py

I couldn't reproduce the crash with a small example, but this seems to fix this crash in a large codebase:
```
File "/Users/jukka/src/mypy/mypy/dmypy_server.py", line 234, in serve
resp = self.run_command(command, data)
File "/Users/jukka/src/mypy/mypy/dmypy_server.py", line 281, in run_command
ret = method(self, **data)
File "/Users/jukka/src/mypy/mypy/dmypy_server.py", line 359, in cmd_check
return self.check(sources, export_types, is_tty, terminal_width)
File "/Users/jukka/src/mypy/mypy/dmypy_server.py", line 413, in check
res = self.initialize_fine_grained(sources, is_tty, terminal_width)
File "/Users/jukka/src/mypy/mypy/dmypy_server.py", line 498, in initialize_fine_grained
messages = self.fine_grained_manager.update(changed, removed)
File …
```

Attempt to fix daemon crash related to ABCs

---

mypy/exprtotype.py
mypy/fastparse.py
mypy/messages.py
mypy/options.py
mypy/semanal.py
mypy/typeanal.py
test-data/unit/check-python311.test
test-data/unit/check-python312.test

This is the last significant thing I am aware of that is needed for PEP 646 support. After this and other currently open PRs are merged, I will make an additional pass grepping for usual suspects and verifying we didn't miss anything. Then we can flip the switch and announce this as supported.

Support fancy new syntax for variadic types

---

mypy/build.py
test-data/unit/fine-grained-modules.test
test-data/unit/fine-grained.test

In some cases, mypy daemon could generate false positives about imports targeting packages with a module-level `__getattr__` methods. The root cause was that the `mypy.build.in_partial_package` function would leave a partially initialized module in the `modules` dictionary of `BuildManager`, which could probably cause all sorts of confusion. I fixed this by making sure that ASTs related to temporary `State` objects don't get persisted.
Also updated a test case to properly delete a package -- an empty directory is now actually a valid namespace package, so to delete a package we should delete the directory, not just the files inside it.

Fix daemon false positives related to module-level __getattr__

---

mypyc/codegen/emit.py

* (fix): remove call to a `.format()` method for an f-string in the emit.py module.
___
It looks like there is a redundant `.format()` call for an f-string.
Originally this was added in 040f3ab64a86efcf7093ada1b13842e56715f243 revision at [562th line](https://github.com/python/mypy/commit/040f3ab64a86efcf7093ada1b13842e56715f243#diff-09b5e6725588fd1151b6c533dc4c0e748d73d6b4e85799a7737959175832fdeeR562).
I doubt there is any need to use `.format()` when it's been formatted using the f-string simultaneously. (Although it's legal and isn't producing any exception or unexpected behaviour...)
___
I didn't create a separate issue for this since it seems like a minor fix and does not affect behavior.

fix: remove redundant `.format()`

---

mypy/semanal_newtype.py
test-data/unit/check-newtype.test

fixes #16297.
since the `.+_NAMES` constants in `types.py` are each referenced multiple times while other examples like this (i.e.  a `.+_NAMES` tuple/set used only once) are inlined, I've inlined this one.
i added a test for this but for some reason it passes without this patch, even though it fails if it's run manually outside of the test suite. any idea why this is? thank you!

Correctly recognize `typing_extensions.NewType`

---

mypy/stubgen.py
mypy/stubutil.py
test-data/unit/stubgen.test

The semantic analyzer treats properties as overloaded functions. This was previously ignored by stubgen but regressed in #15232.
This PR restores the original behavior.
Fixes #16300

stubgen: fix missing property setter in semantic analysis mode

---

mypyc/irbuild/builder.py
mypyc/irbuild/statement.py
mypyc/irbuild/visitor.py
mypyc/test-data/irbuild-unreachable.test

Skip them instead. This applies to statements after break, continue, return and raise statements.
It's common to have unreachable statements temporarily while working on a half-finished change, so generating an error is perhaps not the best option.
Fixes mypyc/mypyc#1028.

[mypyc] Don't crash on unreachable statements

---

mypy/constraints.py
mypy/join.py
mypy/meet.py
mypy/subtypes.py
mypy/types.py
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/16296
In my big refactoring I flipped the variance convention for the `Parameters` type, but I did it inconsistently in one place. After working some more with ParamSpecs, it now seems to me the original convention is easier to remember. I also now explicitly put it in the type docstring.
@hauntsaninja Not 100% sure, but this may be important enough for 1.6.2.

Clarify variance convention for Parameters

---

MANIFEST.in

This is an attempt to fix wheel builds. Perhaps we'd want to actually include the changelog in the sdist. We can decide this later after the build has bee fixed.
We've been getting these errors:
```
...
lists of files in version control and sdist do not match!
missing from sdist:
CHANGELOG.md
listing source files under version control: 830 files and directories
building an sdist: mypy-1.7.0+dev.ffe89a21058eaa6eb1c1796d9ab87aece965e2d9.tar.gz: 829 files and directories
copying source files to a temporary directory
building a clean sdist: mypy-1.7.0+dev.tar.gz: 829 files and directories
suggested MANIFEST.in rules:
include *.md
Error: Process completed with exit code 1.
``
Example failure:
https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/6555980362/job/17805243900

Fix sdist build by not including CHANGELOG.md

---

.github/workflows/test.yml

The 3.8 tests have been flaking for several weeks and I don't think anyone has a good repro or idea as to the cause

Run macOS mypyc tests with Python 3.9

---

mypyc/irbuild/builder.py
mypyc/irbuild/function.py
mypyc/test-data/irbuild-statements.test
mypyc/test-data/run-misc.test

Previously we produced duplicate functions in C, which caused C
compiler errors.

[mypyc] Generate error on duplicate function definitions

---

mypy/server/astdiff.py
test-data/unit/diff.test

Previously changing a return type to an optional type was not propagated at least in some cases, since astdiff could simplify away the optional type.

[daemon] Fix return type change to optional in generic function

---

mypy/checkexpr.py
mypy/infer.py
mypy/solve.py
test-data/unit/check-inference.test

Fixes https://github.com/python/mypy/issues/16331
Fix is straightforward: do not use the fallback, where we would not give the error in the first place.

Use upper bound as inference fallback more consistently

---

mypy/semanal.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-typevar-tuple.test
test-data/unit/semanal-types.test

Fixes https://github.com/python/mypy/issues/16285
I was not sure if it is important to support this, but taking into account the current behavior is a crash, and that implementation is quite simple, I think we should do this. Using this opportunity I also improve related error messages a bit.

Support PEP-646 and PEP-692 in the same callable

---

mypy/stubgen.py
test-data/unit/stubgen.test

This is to ensure that you don't get encoding errors if docstrings contains odd characters like emojis.

Write stubs with utf-8 encoding

---

mypy/checker.py
mypy/constraints.py
mypy/meet.py
mypy/subtypes.py
test-data/unit/check-overloading.test

Fixes https://github.com/python/mypy/issues/16338
This is kind of a major change, but it is technically correct: we should not treat `(*args: Any, **kwargs: Any)` special in `is_proper_subtype()` (only in `is_subtype()`). Unfortunately, this requires an additional flag for `is_callable_compatible()`, since currently we are passing the subtype kind information via a callback, which is not applicable to handling argument kinds.

Properly use proper subtyping for callables

---

mypy/semanal.py
test-data/unit/check-statements.test
test-data/unit/check-tuples.test
test-data/unit/semanal-errors.test

Fixes: https://github.com/python/mypy/issues/16287
Update mypy's error on starred expression to be inline with python3.11

Update starred expression error inline with Python

---

mypy/main.py
mypy/options.py
mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/semanal_newtype.py
mypy/semanal_typeddict.py
mypy/typeanal.py
test-data/unit/check-classes.test
test-data/unit/check-incremental.test
test-data/unit/check-namedtuple.test
test-data/unit/check-newsemanal.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typeddict.test
test-data/unit/check-unions.test
test-data/unit/cmdline.test

FWIW I decided to keep the old tests (where possible), just to be sure we will not re-introduce various crashes at function scope, where recursive aliases are not allowed.

Delete recursive aliases flags

---

mypy/checker.py
mypy/checkexpr.py
mypy/main.py
mypy/options.py
mypy_self_check.ini
test-data/unit/check-generics.test
test-data/unit/check-inference-context.test
test-data/unit/cmdline.test

Fixes https://github.com/python/mypy/issues/15906
I am adding `--old-type-inference` so people can disable the flag if they have issues (for few releases). IIRC there will be some fallback in `mypy_primer`, but last time I checked it was all correct. Also I don't remember if we need to update some tests, but we will see.

Enable new type inference by default

---

mypy/build.py

We were spending quite a lot of time in this function when running tests, based on profiling.

Skip expensive repr() in logging call when not needed

---

mypy/applytype.py
mypy/checker.py
mypy/checkexpr.py
mypy/checkpattern.py
mypy/constraints.py
mypy/erasetype.py
mypy/join.py
mypy/maptype.py
mypy/meet.py
mypy/semanal_shared.py
mypy/subtypes.py
mypy/typeops.py
mypy/types_utils.py
mypy/typevars.py
test-data/unit/check-incremental.test
test-data/unit/check-python310.test
test-data/unit/check-selftype.test
test-data/unit/check-typevar-tuple.test
test-data/unit/fine-grained.test

I decided to go again over various parts of variadic types implementation to double-check nothing is missing, checked interaction with various "advanced" features (dataclasses, protocols, self-types, match statement, etc.), added some more tests (including incremental), and `grep`ed for potentially unhandled cases (and did found few crashes). This mostly touches only variadic types but one thing goes beyond, the fix for self-types upper bound, I think it is correct and should be safe.
If there are no objections, next PR will flip the switch.

Some final touches for variadic types support

---

mypy/checker.py
mypy/nodes.py
mypy/semanal.py
mypy/semanal_main.py

We used to check if a file is in typeshed a lot. This seems to speed up self-check by about 2%, and this should also speed up tests a bit.

Cache information about whether file is typeshed file

---

mypy/checker.py
mypy/subtypes.py

The check was pretty expensive, though usually it's not doing anything non-trivial. Added a fast path for cases where we use the implicit self type, which covers the vast majority of cases.
This makes self-check about 4% faster.

Add fast path for checking self types

---

mypyc/build.py

Fixes #16318, as requested by setuptools maintainer

Avoid importing from setuptools._distutils

---

mypy/semanal_typeargs.py

The upper bound is usually `object`, so add a fast path and skip a potentially slow subtype check if that's the case. Also make type annotations more precise.
This seems to at least speed up type checker tests, by 1-2% or so. This also potentially speeds up self-check a bit, though probably by less than 1%.

Speed up type argument checking

---

docs/source/command_line.rst

This PR removes one of the duplicate **in** in the sentence "This option is only useful in in the absence of `__init__.py`" in the file `docs/source/command_line.rst`.
No executable code was changed. So, my changes were verified only by reviewing the final sentence in the documentation.

doc: remove duplicate word

---

mypy/dmypy_server.py
mypy/inspections.py
mypy/test/testfinegrained.py
test-data/unit/daemon.test
test-data/unit/fine-grained-inspect.test

Fixes https://github.com/python/mypy/issues/15781
The fix is to switch to already resolved paths instead of relying on `crawl_up()`. This should be more robust w.r.t. various special cases. I also tweak the tests slightly to show full file names, to have a more consistent output.

Fix dmypy inspect for namespace packages

---

mypy/inspections.py
mypy/test/testutil.py
test-data/unit/daemon.test

Fixes https://github.com/python/mypy/issues/15780
@KotlinIsland I don't have access to Windows, so can't test this end-to-end. It would be great if you can double-check the fix actually works.

Fix dmypy inspect on Windows

---

docs/source/command_line.rst
mypy/checkexpr.py
mypy/checkstrformat.py
mypy/main.py
mypy/options.py
mypy/semanal.py
mypy/test/testcheck.py
mypy/test/testfinegrained.py
mypy/test/testsemanal.py
mypy/test/testtransform.py
mypy/typeanal.py
test-data/unit/check-flags.test
test-data/unit/check-tuples.test
test-data/unit/check-typevar-tuple.test
test-data/unit/cmdline.test

Fixes https://github.com/python/mypy/issues/12280
Fixes https://github.com/python/mypy/issues/14697
In this PR:
* Enable `TypeVarTuple` and `Unpack` features.
* Delete the old blanket `--enable-incomplete-features` flag that was deprecated a year ago.
* Switch couple corner cases to `PreciseTupleTypes` feature.
* Add the draft docs about the new feature.
* Handle a previously unhandled case where variadic tuple appears in string formatting (discovered on mypy self-check, where `PreciseTupleTypes` is already enabled).

Enable Unpack/TypeVarTuple support

---

mypy/fixup.py
mypy/nodes.py
test-data/unit/fine-grained.test

If a submodule has been deleted while using a fine-grained cache, the daemon could crash during fixup, since there could be a symbol table entry in a parent package that would appear to refer to itself. Handle the case by adding a placeholder symbol table entry instead. Eventually the parent package will be reprocessed and the symbol table will be completed.

Fix daemon crash caused by deleted submodule

---

CHANGELOG.md
mypy/stubutil.py
test-data/unit/stubgen.test

stubgen: include __all__ in output

---

mypy/errorcodes.py
mypy/errors.py

Fixes https://github.com/python/mypy/issues/16375

Don't show docs links for plugin error codes

---

mypy/checkexpr.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/16380
Fix is quite straightforward, what was an `assert` really needs to be an `if`.

Fix crash on unpack call special-casing

---

mypy/dmypy_server.py
mypy/test/testfinegrained.py
test-data/unit/daemon.test

Fixes https://github.com/python/mypy/issues/15794
Unfortunately, this requires to pass `--export-types` to `dmypy run`  if one wants to inspect a file that was previously kicked out of the build.

Fix file reloading in dmypy with --export-types

---

mypy/semanal_typeddict.py
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/16395

Fix strict-optional in extending generic TypedDict

---

mypy/message_registry.py
test-data/unit/check-super.test

Now all messages use the same `"super"` formatting, it used to be a bit different.

Improve error messages for `super` checks and add more tests

---

mypy/build.py
mypy/config_parser.py
mypy/main.py
mypy/options.py
mypy/test/testerrorstream.py
mypy/test/testgraph.py
mypy/test/testutil.py
mypy/util.py
mypyc/build.py

Adds a new `--junit-format` flag to MyPy, which affects the structure of the junit file written when `--junit-xml` is specified (it has no effect when not writing a junit file). This flag can take `global` or `per_file` as values:
* `--junit-format=global` (the default) preserves the existing junit structure, creating a junit file specifying a single "test" for the entire mypy run.
* `--junit-format=per_file` will cause the junit file to have one test entry per file with failures (or a single entry, as in the existing behavior, in the case when typechecking passes).
In some settings it can be useful to know which files had typechecking failures (for example, a CI system might want to display failures by file); while that information can be parsed out of the error messages in the existing …

Allow mypy to output a junit file with per-file results

---

mypy/checkexpr.py
test-data/unit/check-inference-context.test

Fixes https://github.com/python/mypy/issues/4297
Fix is straightforward: without properly pushing lambda expression on the stack, the previous fix @JukkaL added for nested functions doesn't work for lambdas (it thinks that we are at global scope).

Fix type narrowing in lambda expressions

---

mypy/main.py
mypyc/build.py

#16388 introduced a bug where, with `--junit-format=global`, the junit file would indicate an error (with no message) even if everything passed. That was because `_generate_junit_contents` would check if `messages_by_file` was empty or not to determine if there were failures, but with `--junit-format=global` we'd pass in a dictionary of the form `{None: all_messages}`; `all_messages` would be empty, but the resulting dictionary wouldn't be.
The fix is to pass in an empty dictionary if there are no messages.
I've tested manually with `--junit-format=global` and `--junit-format=per_file` in the successful case to make sure the files are written correctly now.

Fix junit writing bug introduced in #16388

---

docs/source/error_code_list2.rst
mypy/checker.py
mypy/errorcodes.py
mypy/message_registry.py
test-data/unit/check-errorcodes.test

Fixes https://github.com/python/mypy/issues/3208
Interestingly, we already prohibit this when the override is a mutable property (goes through `FuncDef`-related code), and in multiple inheritance. The logic there is not very principled, but I just left a TODO instead of extending the scope of this PR.

Add error code for mutable covariant override

---

mypy/constraints.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/16427
The test case added in the first commit crashes.
The second commit addresses the crash - I don't know whether this fix is
correct, it just happens to stop the crash but it leads to a code branch
which just `continue`s out of a for loop iteration, so it might be
bypassing something it shouldn't. I don't completely understand it.

Handle TypeVarTupleType when checking overload constraints

---

mypy/checkexpr.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/16425
Fix is straightforward.

Fix handling of tuple type context with unpacks

---

CHANGELOG.md

Address feedback and include recently cherry-picked PRs.

Changelog updates for mypy 1.7

---

mypy/typeops.py
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/16450
The fix is a bit ad-hoc, but OTOH there is nothing meaningful we can infer in such situation, so it is probably OK.

Fix crash on Callable self in __call__

---

mypy/stubtest.py
mypy/test/teststubtest.py
mypy/types.py

We should probably lean into the type checker harder here
Fixes #14950
Fixes https://github.com/python/typeshed/pull/11009#issuecomment-1805013903

stubtest: special case final and deprecated

---

mypy/checker.py
test-data/unit/check-dataclasses.test
test-data/unit/check-final.test
test-data/unit/check-functions.test
test-data/unit/fine-grained-dataclass-transform.test
test-data/unit/fixtures/dataclasses.pyi

Fixes https://github.com/python/mypy/issues/9910
Fixes https://github.com/python/mypy/issues/16452
We already exclude private names from override type compatibility checks etc., but it looks like some override checks were still performed, we need to skip them, since private name is actually a different name in subclass.

Exclude private attributes from override checks

---

mypy/meet.py
test-data/unit/check-narrowing.test
test-data/unit/fixtures/len.pyi

Fixes https://github.com/python/mypy/issues/16468
The fix is straightforward.
Btw when fixing this I noticed that we disregard type arguments when narrowing, for example:
```python
x: Sequence[int]
if isinstance(x, tuple):
reveal_type(x)  # tuple[Any, ...], but should be `tuple[int, ...]`
```
I guess fixing this may be tricky, and it is quite old behavior.

Fix missing meet case exposed by len narrowing

---

mypy/semanal.py
mypy/test/teststubtest.py

I've noticed that `TypedDict` and `NamedTuple` classes are special cased during semantic analyzisys. They had their own logic for class-level decorators. This is fine, but we need some common ground.
As a side-effect, they can now be `type_check_only`!

Refactor class decorator: this enables `type_check_only` support for `TypedDict` and `NamedTuple`

---

CHANGELOG.md

Lets the Markdown renderer highlight the code as Python rather than leaving it un-highlighted :–)
This PR does not change mypy, nor do I believe any tests should be written, as it only affects the rendering of a few code snippets in the changelog (other snippets further down in the changelog already use the identifier).
Thanks!

Add missing language identifiers in changelog code snippets

---

mypy/solve.py
test-data/unit/check-inference.test
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/16451
This special-casing is unfortunate, but this is the best I came up so far.

Special-case unions in polymorphic inference

---

mypy/subtypes.py
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/16405
Fixes https://github.com/python/mypy/issues/16412
Imprecise argument kinds inference was added a while ago to support various edge cases with `ParamSpec`. This feature required mapping actual kinds to formal kinds, which is in general undecidable. At that time we decided to not add much special-casing, and wait for some real use-cases. So far there are two relevant issues, and it looks like both of them can be fixed with simple special-casing: ignore argument positions in subtyping if arguments can be matched by name. This adds minor unsafety, and generally doesn't look bad, so I think we should go ahead with it.

Ignore position if imprecise arguments are matched by name

---

mypy/checkexpr.py
mypy/meet.py
test-data/unit/check-expressions.test
test-data/unit/fixtures/list.pyi

Fixes https://github.com/python/mypy/issues/16473
Potentially we can turn this helper function into a proper visitor, but I don't think it is worth it as of right now.

Fix crash on strict-equality with recursive types

---

mypyc/irbuild/prebuildvisitor.py
mypyc/test-data/run-functions.test

Fixes https://github.com/python/mypy/issues/16480
Fix is straightforward, but also suspicious, since I am not sure how it ever worked without this.

[mypyc] Fix regression with nested functions

---

mypy/semanal_typeddict.py
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/16498
Fix is trivial: no operations can be done with `Required` types before unwrapping (because they are not real types).

Fix crash on unimported Any in TypedDict

---

mypy/semanal_enum.py
test-data/unit/check-incremental.test

Fixes https://github.com/python/mypy/issues/16163
Fix is straightforward: I simply copy the logic we have for invalid TypedDicts/NamedTuples.

Fix crash on invalid enum in method

---

mypy/stubtest.py

Currently, if a function exists at runtime but is missing from the stub, stubtest will emit an error message like this:
```
error: shelve.Shelf.__del__ is not present in stub
Stub: in file stdlib\shelve.pyi
MISSING
Runtime: in file C:\Users\alexw\AppData\Local\Programs\Python\Python312\Lib\shelve.py:157
<function Shelf.__del__ at 0x0000024822FD7060>
error: subprocess.Popen.__del__ is not present in stub
Stub: in file stdlib\subprocess.pyi
MISSING
Runtime: in file C:\Users\alexw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py:1120
<function Popen.__del__ at 0x00000248215D3D80>
```
This isn't particularly helpful: it doesn't tell you anything _about_ the function at runtime, just that there is one. With this PR, stubtest's error messages change to this, which is much more helpful: …

Stubtest: give more helpful errors if a function is missing from the stub

---

mypy/test/teststubtest.py
mypy/types.py
test-data/unit/lib-stub/typing_extensions.pyi

Followup from https://github.com/python/mypy/pull/16457/files#r1392715784

PEP 702: decorator is in warnings, not typing-extensions

---

mypy/stubtest.py
mypy/test/teststubtest.py

stubtest: hack for "<unrepresentable>" defaults

---

mypyc/test/test_run.py

Fixes https://github.com/python/mypy/issues/16420
Although this is not 100% clear yet, but after 20 runs on a Mac I have it no longer fails (without this patch it failed 20% of times). Btw, contrary to the comment, _my_ Linux Mint (which is an Ubuntu derivative) works perfectly (i.e. test passed 20 times even after I removed the `sleep()`). So it is not really Mac vs Linux issue.

An attempt to fix mypyc tests on MacOS

---

mypy/constraints.py
mypy/expandtype.py
test-data/unit/check-parameter-specification.test

Fixes https://github.com/python/mypy/issues/16485
My initial implementation of imprecise constraints fallback was really fragile and ad-hoc, and I now see several edge case scenarios where we may end up using imprecise constraints for a `ParamSpec` while some precise ones are available. So I re-organized it: now we just infer everything as normally, and filter out imprecise (if needed) at the very end, when we have the full picture. I also fix an accidental omission in `expand_type()`.

Make imprecise constraints handling more robust

---

mypy/checker.py
test-data/unit/check-typeguard.test

Fixes https://github.com/python/mypy/issues/16187
Note there may be some more similar crashes, I don't handle them all properly, for now I leave a TODO and replace the `assert` with `if`, so at least we should not crash on an unhandled case.

Fix crash on TypeGuard in __call__

---

docs/source/command_line.rst

Default value of `MANY_ERRORS_THRESHOLD` was set to `-1` in https://github.com/python/mypy/pull/15138, which is also the default value of the `--soft-error-limit` CLI option. However the CLI docs were not updated accordingly.

Docs: update soft-error-limit default value to -1

---

mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/semanal_typeddict.py
test-data/unit/check-namedtuple.test

Do not allow class-level keywords for `NamedTuple`

---

test-data/unit/check-class-namedtuple.test
test-data/unit/check-expressions.test
test-data/unit/check-python310.test
test-data/unit/check-tuples.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typeddict.test
test-data/unit/fixtures/dict-full.pyi
test-data/unit/fixtures/tuple.pyi

Move some definitions away from commonly used fixtures that are only needed in one or two test cases, as they will slow down many test cases.
This speeds up `mypy/test/testcheck.py` by about 5% on my Linux desktop.

Speed up tests by simplifying test fixtures

---

mypy/semanal.py

This showed up as hot spot in a CPU profile collected when running tests.
This makes `mypy/test/testcheck.py` about 2% faster on my Linux desktop.

Add fast path to analyzing special form assignments

---

misc/test-stubgenc.sh
mypy/stubdoc.py
mypy/stubgen.py
mypy/stubgenc.py
mypy/stubutil.py
test-data/pybind11_mypy_demo/src/main.cpp
test-data/pybind11_mypy_demo/stubgen-include-docs/pybind11_mypy_demo/__init__.pyi
test-data/pybind11_mypy_demo/stubgen-include-docs/pybind11_mypy_demo/basics.pyi
test-data/pybind11_mypy_demo/stubgen/pybind11_mypy_demo/basics.pyi

This addresses several regressions identified in https://github.com/python/mypy/issues/16486
The primary regression from https://github.com/python/mypy/pull/15770 is that pybind11 properties with docstrings were erroneously assigned `typeshed. Incomplete`. 
The reason for the regression is that as of the introduction of the `--include-docstring` feature (https://github.com/python/mypy/pull/13284, not my PR, ftr), `./misc/test-stubgenc.sh` began always reporting success.  That has been fixed. 
It was also pointed out that `--include-docstring` does not work for C-extensions.  This was not actually a regression as it turns out this feature was never implemented for C-extensions (though the tests suggested it had been), but luckily my efforts to unify the pure-python and C-extension …

Fix stubgen regressions with pybind11 and mypy 1.7

---

test-data/unit/lib-stub/typing_extensions.pyi

Stubtest's tests will start failing when `typing_extensions==4.9.0` comes out, due to some new `ClassVar`s on `typing_extensions.TypedDict`. This PR fixes that.
Fixes https://github.com/python/typing_extensions/issues/309

Fix stubtest's tests to work with the latest typing_extensions release

---

test-data/unit/pythoneval.test

Fixes https://github.com/python/mypy/issues/16466

Use python2 instead of docutils to test cases with no stubs available

---

mypy/util.py

Add exist_ok=True in write_junit_xml

---

mypy/report.py
mypy/stats.py
mypy/stubgen.py

This PR replaces explicit `os.path.exists(...)` checks with `os.makedirs(..., exist_ok=True)` where possible.
This removes the need for an extra existence check and slightly simplifies the code. This can also prevent race conditions like #16630.

Prefer `exist_ok=True` over explicit `os.path.exists(...)` checks

---

mypy/expandtype.py
test-data/unit/check-typevar-tuple.test

Fix crash with type alias to `Callable[[Unpack[Tuple[Any, ...]]], Any]`

---

setup.py

Currently, In the "Project links" section on `pypi.org` there is a link called `News` that goes to [a page](https://mypy-lang.org/news.html) that doesn't seem to be actively maintained. 
Made the following changes to `project_urls` in `setup.py`:
- removed link to "News" 
- added link to "Changelog" 
- added link to "Issues"

Update  `project_urls` in `setup.py`

---

docs/source/command_line.rst
mypy/main.py
mypyc/test/test_run.py
test-data/unit/cmdline.test
test-data/unit/pythoneval.test

Document --enable-incomplete-feature possible values in "mypy --help"
By the way, also remove `--enable-incomplete-feature=Unpack --enable-incomplete-feature=TypeVarTuple` when running the tests, as they are no more incomplete features.
Fixes #14452

Document --enable-incomplete-feature possible values in "mypy --help"

---

mypy/checkmember.py
test-data/unit/check-generics.test

`add_class_tvars` correctly instantiates type variables in the return type for class methods but not for static methods. Check if the analyzed member is a static method in `analyze_class_attribute_access` and substitute the type variable in the return type in `add_class_tvars` accordingly.
Fixes #16668.

Substitute type variables in return type of static methods

---

docs/source/getting_started.rst

I read 'when the program run' as a typo where the phrase intended is 'when the program runs'.

propose edit: getting_started.rst: replace 'when the program run' with 'when the program runs'

---

mypy/checker.py
mypy/main.py
mypy/options.py
mypy/test/testpythoneval.py

Skip slow and unnecessary overload checks in stdlib stubs in these tests. These checks already seem to be skipped in most other contexts, but because pythoneval tests use `--no-silence-site-packages`, the checks were enabled.
This makes pythoneval tests about 13% faster on my Linux desktop, and it should also speed up CI a bit.

Speed up pythoneval tests

---

mypy/semanal.py
mypy/typeanal.py

Merge two visitors into a single visitor that is a bit more optimized than the old visitors.
This speeds ups tests, in particular -- `mypy/test/testcheck.py` is about 4% faster and `mypy/test/testpythoneval.py` is about 3% faster.
Also self-check is about 1% faster, both interpreted and compiled.
This adds more code, but the new code is largely boilerplate, so the difficulty of maintenance seems roughly the same.

Speed up finding function type variables

---

mypy/test/testutil.py
mypy/util.py

#16388 introduced a bug where invalid xml could be produced by `write_junit_xml`, as special characters were no longer being escaped.
The fix is to revert the removal of `from xml.sax.saxutils import escape` and `escape("\n".join(messages))` in the `write_junit_xml` function.
I've added a small test case which checks that the `<`, `>`, `&` are escaped correctly in the xml.

Fix xml writing bug introduced in #16388

---

mypy/fastparse.py
test-data/unit/check-literal.test
test-data/unit/fixtures/ops.pyi

Implements python/typing#1550
Fixes #16727 (a trivial bug I found while implementing this feature)

Allow unary + in Literal

---

mypy/nodes.py

A tiny update of naming of first parameter in a classmethod.
Does not affect any existing code across the project.
___
* (refactor): An appropriate name for first parameter in classmethod in nodes.py module.

refactor: Tiny renaming

---

mypy/fastparse.py
test-data/unit/check-basic.test

See discussion in https://discuss.python.org/t/newlines-within-triple-quoted-type-expressions/42833

Accept multiline quoted annotations

---

mypy/stubtest.py
mypy/test/teststubtest.py

I checked this pretty thoroughly against typeshed.

stubtest: fix pos-only handling in overload resolution

---

mypy/stubgen.py
mypy/stubutil.py
test-data/unit/stubgen.test

stubgen: use PEP 604 unions everywhere

---

docs/source/mypy_daemon.rst

The existing documentation almost makes it seem like the user has the option to toggle this. 
Updated wording to say strictly denoting it's not configurable with explanation from the code here https://github.com/python/mypy/blob/fbb738a4626976f83a7412df73533d87483a31b7/mypy/dmypy_server.py#L196-L198.

Update mypy daemon documentation note about local partial types

---

mypy/semanal.py
mypy/semanal_typeddict.py
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/16701
This PR allows `TypedDict(...)` calls to be used as a base class. This fixes the error emitted by mypy described in https://github.com/python/mypy/issues/16701 .

Support TypedDict functional syntax as class base type

---

mypy/stubtest.py
mypy/test/teststubtest.py

Add support for setting enum members to "..."

---

mypy/messages.py
mypy/typeanal.py
test-data/unit/check-typevar-defaults.test

Start using TypeVar defaults when fixing instance types, instead of filling those with `Any`.
This PR preserves the way an invalid amount of args is handled. I.e. filling all with `Any` / defaults, instead of cutting off additional args. Thus preserving full backwards compatibility. This can be easily changed later if necessary.
`TypeVarTuple` defaults aren't handled correctly yet. Those will require additional logic which would have complicated the change here and made it more difficult to review.

Use TypeVar defaults instead of Any when fixing instance types (PEP 696)

---

mypy/stubtest.py
mypy/test/teststubtest.py

Fixes https://github.com/python/typeshed/issues/11318

stubtest: adjust symtable logic

---

mypy/checkexpr.py
mypy/typeanal.py
test-data/unit/check-typevar-defaults.test

This PR applies the TypeVar defaults to `TypeAlias` types instead of using `Any` exclusively, similar to https://github.com/python/mypy/pull/16812.
Again `TypeVarTuple` defaults aren't handled correctly yet.

Use TypeVar defaults instead of Any when fixing TypeAlias types (PEP 696)

---

docs/source/config_file.rst
docs/source/error_codes.rst
docs/source/existing_code.rst
docs/source/running_mypy.rst

Recommend `--disable-error-code=import-untyped`. It's probably strictly better than `--ignore-missing-imports` for most users.
Remove the displaying error codes section, since it's on by default.
Some more advice and discoverability for "using mypy with an existing codebase".

Various docs improvements

---

docs/source/running_mypy.rst

Fix numbering in "Cannot find implementation or library stub" section of the `running_mypy` documenation page.

[DOC] Fix numbering error

---

mypy/constraints.py
mypy/test/testconstraints.py
test-data/unit/check-typevar-tuple.test

The TypeVarTuple equality checks mentioned in PEP 646 assume TypeVarTuple to be `invariant`.
https://peps.python.org/pep-0646/#type-variable-tuple-equality
Fixes: #16739

Consider TypeVarTuple to be invariant

---

mypy/typeanal.py
test-data/unit/check-generics.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typevar-defaults.test
test-data/unit/check-typevar-tuple.test
test-data/unit/fine-grained.test

Small update to adjust the error messages following the suggestion in https://github.com/python/mypy/pull/16825#discussion_r1468507923.

Update TypeAlias error messages for bad number of arguments

---

mypy/dmypy_server.py
mypy/dmypy_util.py

`WriteToConn` replaces stdout and stderr to capture output, but causes issues because it doesn't implement the `TextIO` API (as expected of `sys.stdout` and `sys.stderr`).
By stubbing the rest of the `TextIO` API we prevent issues with other code which uses more of the API than we had previously accounted for.
Fixes https://github.com/python/mypy/issues/16678

Fix `'WriteToConn' object has no attribute 'flush'`

---

README.md

As of the 10th of September 2023 the typing-sig mail list is now replaced with [discuss.python.org](https://discuss.python.org/c/typing/32) as explained [here](https://mail.python.org/archives/list/typing-sig@python.org/thread/BENDBBUDRCRMTTK2B5HJ7RCKENFD6DW2/) and [here](https://discuss.python.org/t/about-the-typing-category/34155)
The README.md file was referencing the old link.

Update new type system discussion links

---

mypy/applytype.py
mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-typevar-defaults.test

Implement type application for callables with TypeVar defaults.
Similar to previous PRs, support for TypeVarTuples is still TODO.

Apply TypeVar defaults to callables (PEP 696)

---

mypy/checkexpr.py
test-data/unit/check-generics.test
test-data/unit/typexport-basic.test

Add missing call to store inferred types if an overload match is found early. All other code paths already do that.
I recently saw an interesting pattern in `aiohttp` to type values in an `dict[str, Any]` by subclassing dict.
```py
U = TypeVar("U")
class Key(Generic[T]):
...
class CustomDict(dict[Key[Any] | str, Any]):
@overload  # type: ignore[override]
def get(self, __key: Key[T]) -> T | None:
...
@overload
def get(self, __key: Key[T], __default: U) -> T | U:
...
@overload
def get(self, __key: str) -> Any | None:
...
@overload
def get(self, __key: str, __default: Any) -> Any:
...
def get(self, __key: Key[Any] | str, __default: Any = None) -> Any:
"""Forward to super implementation."""
return super().get(__key, __default)
@overload  # type: ignore[override]
def …
```

Fix missing type store for overloads

---

mypy/messages.py
mypy/typeanal.py
test-data/unit/check-typevar-defaults.test

Similar to TypeAlias types `Missing type parameters for generic type` should not be emitted if too many arguments are given. There is a separate error message for that.

Fix disallow-any errors for Instance types (PEP 696)

---

test-data/unit/check-async-await.test
test-data/unit/check-callable.test
test-data/unit/check-dataclass-transform.test
test-data/unit/check-dataclasses.test
test-data/unit/check-errorcodes.test
test-data/unit/check-flags.test
test-data/unit/check-generic-alias.test
test-data/unit/check-incremental.test
test-data/unit/check-literal.test
test-data/unit/check-modules.test
test-data/unit/check-namedtuple.test
test-data/unit/check-narrowing.test
test-data/unit/check-newsemanal.test
test-data/unit/check-newtype.test
test-data/unit/check-union-or-syntax.test
test-data/unit/check-unreachable-code.test
test-data/unit/deps.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test
test-requirements.in

Remove `--python-version 3.7` from tests if not necessary anymore or use `3.8` where it makes sense instead.

Remove --python-version 3.7 references from tests

---

test-data/unit/check-functools.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-python38.test
test-data/unit/check-typeddict.test

Remove the `--python-version 3.8` flag where it's used to indicate the min python version requirement. Mypy doesn't support running under Python 3.7 / the tests are only run for 3.8+.

Remove unnecessary --python-version 3.8 references from tests

---

mypy/expandtype.py
mypy/test/testtypes.py
test-data/unit/check-typevar-defaults.test

Small change to fix an error when expanding a TypeVarTuple default.
```
RuntimeError: Invalid type replacement to expand: Unpack[tuple[builtins.int, builtins.str]]
```
Ref: #14851

Expand TypeVarTuple default (PEP 696)

---

mypy/stubgen.py
mypy/test/teststubgen.py
test-data/unit/stubgen.test

stubgen: Fix crash on star unpack of TypeVarTuple

---

.pre-commit-config.yaml
pyproject.toml
test-requirements.in
test-requirements.txt

Fix this deprecation warning when running ruff on the repository directly:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'unfixable' -> 'lint.unfixable'
- 'isort' -> 'lint.isort'
```
Note that you don't see the deprecation warnings if you run ruff via pre-commit (only if you run ruff directly, e.g. via ruff .), since pre-commit [swallows all output from a tool if the tool exits with code 0](https://stackoverflow.com/questions/72895720/pre-commit-hook-does-not-echo-on-terminal/72898524#72898524).

Bump ruff to 0.2.0

---

docs/source/error_code_list2.rst

Closes https://github.com/python/mypy/issues/16880
Supercedes https://github.com/python/mypy/pull/16881

Docs: adding missing `mutable-override` to section title

---

mypy/stubtest.py

This is added to all protocol classes on Python 3.12.2+ (it was added in a patch release of 3.12 as part of a bugfix). There's no reason why you'd want to explicitly include it in a stub (and doing so would lead the type checker to incorrectly conclude that you wanted a member literally called `__non_callable_proto_members__`)
Cf. https://github.com/python/typeshed/pull/11384 and https://github.com/python/typeshed/issues/11383

Stubtest: ignore a new protocol dunder

---

mypy/defaults.py
test-data/unit/cmdline.test

This syncs up this constant to the actual minimum version that typeshed is now targetting.

Unsupport targetting 3.7.

---

mypy/stubtest.py

This is added to all protocol classes on Python 3.12.2+ (it was added in a patch release of 3.12 as part of a bugfix). There's no reason why you'd want to explicitly include it in a stub (and doing so would lead the type checker to incorrectly conclude that you wanted a member literally called `__non_callable_proto_members__`)
Cf. https://github.com/python/typeshed/pull/11384 and https://github.com/python/typeshed/issues/11383
(cherry picked from commit 517f5aee23ba218f615bcd4427bca62f120bc222)

[Release 1.9] Stubtest: ignore a new protocol dunder (#16895)

---

mypy/defaults.py
test-data/unit/cmdline.test

This syncs up this constant to the actual minimum version that typeshed is now targetting.
Co-authored-by: Marc Mueller <30130371+cdce8p@users.noreply.github.com>
(cherry picked from commit d8e3d591048cfe16dbc9cfa2ff88db38c587e3d0)

[Release 1.9] Unsupport targetting 3.7. (#16883)

---

mypy/stubtest.py

Hello mypy team,
I am working as part of a research team developing a code analysis tool for Python. One of the issues the tool discovered in mypy's codebase is that two fields in the `_Arguments` class, `mypy_config_file` and `custom_typeshed_dir`, can take on a None value, but they are not marked as such. Calling `stubtest.parse_options` on an empty list of arguments reproduces the situation where these two fields are None.
If you are interested in learning more about the tool and how it found this issue, let me know down in the comments, or you can contact me at xifaras.s@northeastern.edu. If you find that this issue is not legitimate, I would be interested in understanding why.
Note that I did not add any test cases as no functional changes to the code were made.
Thank you for your …

Correct type annotations on two fields in _Arguments that are optional but are not marked as such

---

mypy/checkexpr.py
mypy/exprtotype.py
mypy/plugins/default.py
test-data/unit/check-literal.test
test-data/unit/check-tuples.test
test-data/unit/fixtures/tuple.pyi

This makes unary positive on integers preserve the literal value of the integer, allowing `var: Literal[1] = +1` to be accepted. Basically I looked for code handling `__neg__` and added a branch for `__pos__` as well.  
Fixes #16728.

Allow inferring +int to be a Literal

---

mypy/applytype.py
mypy/expandtype.py
mypy/semanal.py
mypy/tvar_scope.py
mypy/typetraverser.py
test-data/unit/check-typevar-defaults.test

Add basic support for recursive TypeVar defaults (PEP 696)

---

mypy/plugins/dataclasses.py
mypy/stubgen.py
test-data/unit/check-dataclasses.test
test-data/unit/stubgen.test

Fixes #16811
stubgen was swallowing default values for `__init__` methods generated by the dataclass plugin making their signature incorrect. This is because the plugin does not include the argument's initializer in the generated signature. I changed it to include a dummy ellipsis so that stubgen can generate correct code.
I also fixed arguments added by the dataclass plugin with the invalid names `*` and `**` to have the valid and unique names `*generated_args` and `**generated_kwargs` (with extra underscores to make them unique if necessary). This removes the need for the hack to special case them in stubgen and is less confusing for someone looking at them in a stub file.

stubgen: Fix generated dataclass `__init__` signature

---

mypy/checker.py
test-data/unit/check-python310.test

Fixes #12998
mypy can't narrow match statements with functions subjects because the callexpr node is not a literal node. This adds a 'dummy' literal node that the match statement visitor can use to do the type narrowing.
The python grammar describes the the match subject as a named expression so this uses that nameexpr node as it's literal.

Fix narrowing on match with function subject

---

test-data/unit/lib-stub/typing_extensions.pyi

Stubtest's tests will start failing when `typing_extensions==4.10.0` comes out, due to some new `ClassVar`s on `typing_extensions.TypedDict`. This PR fixes that.
Fixes https://github.com/python/typing_extensions/issues/339. Note: there's no need to cherry-pick this to the `release-1.9.0` branch, since the daily workflow `typing_extensions` uses runs mypy's tests using the mypy `master` branch.

FIx stubtest's tests to work with the latest version of `typing_extensions`

---

mypy/messages.py
mypy/semanal.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-typevar-defaults.test

This PR adds some additional error handling for recursive TypeVar defaults.
Open issue for future PRs:
- Expanding nested recursive defaults, e.g. `T2 = list[T1 = str]`
- Scope binding, especially for TypeAliasTypes
- ~~Figure out if `visit_type_alias_type` for the `TypeVarDefaultTranslator` visitor is actually needed. _The base class does not provide a default implementation._ So far I haven't hit the `NotImplementedError`.~~

Error handling for recursive TypeVar defaults (PEP 696)

---

mypy/checker.py

Workaround parenthesised context manager issue

---

mypyc/irbuild/expression.py
mypyc/test-data/irbuild-basic.test

Fixes [mypyc/mypyc#902](https://github.com/mypyc/mypyc/issues/902)
This PR finds references of `typing.TYPE_CHECKING` or `typing_extensions.TYPE_CHECKING` and optimizes them to `False` in mypyc.

[mypyc] Optimize TYPE_CHECKING to False at Runtime

---

mypyc/irbuild/builder.py
mypyc/test-data/run-async.test

[mypyc] Remangle redefined names produced by async with

---

mypyc/irbuild/builder.py
mypyc/test-data/irbuild-basic.test

Fixes mypyc/mypyc#852.
Fixes mypyc/mypyc#990.

[mypyc] Don't crash on non-inlinable final local reads

---

mypyc/irbuild/expression.py
mypyc/irbuild/for_helpers.py
mypyc/test-data/run-misc.test

Fixes mypyc/mypyc#816. Admittedly hacky.

[mypyc] Fix compilation of unreachable comprehensions

---

docs/source/common_issues.rst
docs/source/error_code_list.rst
docs/source/error_code_list2.rst
docs/source/generics.rst
docs/source/protocols.rst
docs/source/stubs.rst
docs/source/typed_dict.rst

Since Python 3.8, `TypedDict` has been available from the `typing` module. 
As Python 3.8+ is needed to use mypy (https://github.com/python/mypy/blob/master/setup.py#L12), then it's best for the docs to reflect Python 3.8+ usage.
For previous versions, there's already a disclaimer on the page that explains that `typing_extensions` must be used: https://github.com/python/mypy/blob/master/docs/source/typed_dict.rst?plain=1#L102-L110

Docs: Update `TypedDict` import statements

---

mypy/checker.py
test-data/unit/check-functions.test

Fix override checking for decorated property

---

mypy/checkexpr.py
test-data/unit/check-typeddict.test

Allow TypedDict initialization from Type

---

pyproject.toml

I won't have any effect, but will reflect our target versions better.

Add `py312` target version to `black` config

---

CHANGELOG.md

Mostly minor, but also announce that `--local-partial-types` will be enabled by default soon and explain type parameter defaults in more detail.

Various 1.9 CHANGELOG updates

---

mypy/join.py
test-data/unit/check-inference.test

At the moment, inference fails if an empty dict is used (without annotation) as one of the types. It's because the constraint solver can't resolve `dict[str, int]` and `dict[Never, Never]`. However in this case it's more reasonable to interpret the empty dict as `dict[Any, Any]` and just using the first type instead. That matches the behavior of pyright.
```py
class A(Generic[T]): ...
def func1(a: A[T], b: T) -> T: ...
def a1(a: A[Dict[str, int]]) -> None:
reveal_type(func1(a, {}))
```
```
main: error: Cannot infer type argument 1 of "func1" (diff)
main: note: Revealed type is "Any" (diff)
main: note: Revealed type is "builtins.dict[builtins.str, builtins.int]"
```

Fix inference with UninhabitedType

---

mypy/checkmember.py
test-data/unit/check-abstract.test

Relates to:
https://discuss.python.org/t/calling-abstract-methods/42576
I think this makes mypy's behaviour more predictable

Disallow all super calls to methods with trivial bodies

---

mypyc/codegen/emitmodule.py
mypyc/irbuild/builder.py
mypyc/irbuild/ll_builder.py
mypyc/test-data/opt-copy-propagation.test
mypyc/test/test_copy_propagation.py
mypyc/transform/copy_propagation.py
mypyc/transform/ir_transform.py

This makes it easy to define simple IR-to-IR transforms by subclassing `IRTansform` and overriding some visit methods.
Add an implementation of a simple copy propagation optimization as an example.
This will be used by the implementation of mypyc/mypyc#854, and this can also be used for various optimizations.
The IR transform preserves the identities of ops that are not modified. This means that the old IR is no longer valid after the transform, but the transform can be fast since we don't need to allocate many objects if only a small subset of ops will be modified by a transform.

[mypyc] Provide an easier way to define IR-to-IR transforms

---

mypy/modulefinder.py
mypy/stubgenc.py
mypy/util.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/pythonsupport.h
tox.ini

Some follow on from https://github.com/python/mypy/pull/15566.
Also add 3.12 to tox.ini.

Remove redundant Python 3.7 code

---

mypy/types.py

Fix type narrowing for types.EllipsisType

---

mypy/messages.py
mypy/types.py
test-data/unit/check-lowercase.test

Suggest `list[x]` instead of `List[x]` on Python 3.9 and later in hints. We already suggest `x | None` instead of `Optional[x]` on 3.10+, so this makes the error messages more consistent.
Use lower-case `type[x]` when using `reveal_type` on Python 3.9 and later.

Use lower-case generics more consistently in error messages

---

mypy/plugins/attrs.py
test-data/unit/check-incremental.test
test-data/unit/check-plugin-attrs.test
test-data/unit/fixtures/plugin_attrs.pyi

This commit fixes a couple regressions in 1.9.0 from 91be285.
Attrs' logic for hashability is slightly complex:
* https://www.attrs.org/en/stable/hashing.html
* https://github.com/python-attrs/attrs/blob/9e443b18527dc96b194e92805fa751cbf8434ba9/src/attr/_make.py#L1660-L1689
Mypy now properly emulates attrs' logic so that custom `__hash__` implementations are preserved, `@frozen` subclasses are always hashable, and classes are only made unhashable based on the values of `eq` and `unsafe_hash`.
Fixes #17015
Fixes https://github.com/python/mypy/pull/16556#issuecomment-1987116488
Based on a patch in #17012
Co-Authored-By: Tin Tvrtkovic <tinchester@gmail.com>

attrs: Fix emulating hash method logic

---

mypy/semanal.py
test-data/unit/check-type-aliases.test

Fixes https://github.com/python/mypy/issues/16614#issuecomment-2000428700

Support `TypeAliasType` in a class scope

---

mypyc/ir/pprint.py
mypyc/irbuild/ast_helpers.py
mypyc/irbuild/builder.py
mypyc/irbuild/expression.py
mypyc/irbuild/function.py
mypyc/irbuild/ll_builder.py
mypyc/lower/int_ops.py
mypyc/primitives/int_ops.py
mypyc/test-data/analysis.test
mypyc/test-data/exceptions.test
mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-bool.test
mypyc/test-data/irbuild-dunders.test
mypyc/test-data/irbuild-int.test
mypyc/test-data/irbuild-lists.test
mypyc/test-data/irbuild-set.test
mypyc/test-data/irbuild-singledispatch.test
mypyc/test-data/irbuild-statements.test
mypyc/test-data/irbuild-tuple.test
mypyc/test-data/lowering-int.test
mypyc/test-data/refcount.test

Support lowering of tagged integer `<`, `<=`, `>` and `>=` operations.
Previously we had separate code paths for integer comparisons in values vs conditions. Unify these and remove the duplicate code path. The different code paths produced subtly different code, but now they are identical.
The generated code is now sometimes slightly more verbose in the slow path (big integer). I may look into simplifying it in a follow-up PR.
This also makes the output of many irbuild test cases significantly more compact.
Follow-up to #17027. Work on mypyc/mypyc#854.

[mypyc] Implement lowering for remaining tagged integer comparisons

---

mypy/checker.py
mypy/checkexpr.py
mypyc/test-data/run-generators.test
test-data/unit/check-statements.test

Improve yield from inference for unions of generators

---

mypyc/ir/ops.py
mypyc/ir/pprint.py
mypyc/irbuild/ll_builder.py
mypyc/lower/int_ops.py
mypyc/lower/list_ops.py
mypyc/lower/registry.py
mypyc/primitives/misc_ops.py
mypyc/primitives/registry.py
mypyc/test-data/irbuild-any.test
mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-classes.test
mypyc/test-data/irbuild-dict.test
mypyc/test-data/irbuild-generics.test
mypyc/test-data/irbuild-i64.test
mypyc/test-data/irbuild-lists.test
mypyc/test-data/irbuild-set.test
mypyc/test-data/irbuild-statements.test
mypyc/test-data/irbuild-str.test
mypyc/test-data/irbuild-tuple.test
mypyc/test-data/lowering-list.test
mypyc/test-data/refcount.test
mypyc/test/test_lowering.py

Add a new primitive op for initializing list items. Also add support for primitive ops that steal operands (reference counting wise).
This will also remove most instances of `WORD_SIZE` in irbuild tests, which were a bit painful, since running tests with `--update-data` removed these and they had to be manually added back for 32-bit tests to pass.

[mypyc] Refactor: use primitive op for initializing list item

---

mypy/checkexpr.py
test-data/unit/check-typeddict.test
test-data/unit/lib-stub/typing_extensions.pyi

Followup to #16963
Correctly set optional and required keys for the TypedDict init callable.
Ref: https://github.com/python/mypy/issues/11644

Fix TypedDict init from Type with optional keys

---

mypy/semanal.py
mypy/typeanal.py
test-data/unit/check-type-aliases.test

Follow up to #17038
When a type variable is bound to a class, it cannot be reused in a type alias. Previously in `TypeAliasType`, this error was reported as "not included in type_params". However in the following example, the error is misleading:
```python
from typing import Dict, Generic, TypeVar
from typing_extensions import TypeAliasType
class A(Generic[T]):
Ta11 = TypeAliasType("Ta11", Dict[str, T], type_params=(T,))
x: A.Ta11 = {"a": 1}
reveal_type(x)
```
On the master branch:
```
main.py:8: error: Type variable "T" is not included in type_params  [valid-type]
main.py:8: error: "T" is a type variable and only valid in type context  [misc]
main.py:8: error: Free type variable expected in type_params argument to TypeAliasType  [type-var]
main.py:12: note: Revealed type …
```

Improve error message for bound typevar in TypeAliasType

---

mypy/typetraverser.py
test-data/unit/check-typeguard.test
test-data/unit/check-typeis.test

Add TypeGuard and TypeIs traversing in TypeTraverserVisitor (fixes #17029)

---

mypy/checker.py
test-data/unit/check-python310.test

Fixes #12364
When matching a tuple to a sequence pattern, this change narrows the type of tuple items inside the matched case:
```py
def test(a: bool, b: bool) -> None:
match a, b:
case True, True:
reveal_type(a)  # before: "builtins.bool", after: "Literal[True]"
```
This also works with nested tuples, recursively:
```py
def test(a: bool, b: bool, c: bool) -> None:
match a, (b, c):
case _, [True, False]:
reveal_type(c)  # before: "builtins.bool", after: "Literal[False]"
```
This only partially fixes issue #12364; see [my comment there](https://github.com/python/mypy/issues/12364#issuecomment-1937375271) for more context.
---
This is my first contribution to mypy, so I may miss some context or conventions; I'm eager for any feedback!

Narrow individual items when matching a tuple to a sequence pattern

---

mypy/checkexpr.py
test-data/unit/check-formatting.test

Fixes #7563
Inside `check_str_format_call` method, it checks if expression of `format` method call is an Enum member and it takes Literal value of that Enum member to check the `format` call arguments, if so.

Fix string formatting for string enums
