python/mypy

mypy/expandtype.py
test-data/unit/check-python311.test
test-data/unit/check-python312.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typevar-tuple.test

Fix crash when expanding invalid Unpack in a `Callable` alias

---

mypy/checkmember.py
test-data/unit/check-unions.test

Fixes https://github.com/python/mypy/issues/16603
This change maps over union types when determining the types of access descriptors. Previously, the because [this conditional](https://github.com/md384/mypy/blob/c2a55afcef32ecb11a4c76c4c79539f6ba36d55c/mypy/checkmember.py#L697-L701) would fall through to the `else` case because instance type was not a singular `TypeType` (it was a Union), so we'd end up with an instance value being passed to `__get__` instead of `None`.

fix: incorrect returned type of access descriptors on unions of types

---

mypy/semanal_enum.py
test-data/unit/check-enum.test

Relates to discussion in
https://discuss.python.org/t/draft-of-typing-spec-chapter-for-enums/43496/11

Error for assignment of functional Enum to variable of different name

---

mypy/fastparse.py
mypy/semanal.py
mypy/server/astmerge.py
mypy/stubutil.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py
mypy/typetraverser.py
mypyc/irbuild/classdef.py
test-data/unit/check-final.test
test-data/unit/check-literal.test
test-data/unit/check-namedtuple.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-typeguard.test
test-data/unit/check-typeis.test

Fixes #16367
During semantic analysis, we try to parse all strings as types, including those inside Literal[]. Previously, we preserved the original string in the `UnboundType.original_str_expr` attribute, but if a type is parsed as a Union, we didn't have a place to put the value.
This PR instead always wraps string types in a RawExpressionType node, which now optionally includes a `.node` attribute containing the parsed type. This way, we don't need to worry about preserving the original string as a custom attribute on different kinds of types that can appear in this context.
The downside is that more code needs to be aware of RawExpressionType.

Fix Literal strings containing pipe characters

---

CONTRIBUTING.md

Add command about how to activate virtual environment on Windows.
Add comment to use python instead of python3 command on Windows.

Update CONTRIBUTING.md to include commands for Windows

---

CHANGELOG.md

Initial pass at blog post for Release 1.10.
Still need to add some information about the major changes. Pulled up 3 commits that seemed like we might want to write something about (under TODO), but they can move them to "Other Notable Changes and Fixes" if that's not the case.

Update CHANGELOG.md with draft for release 1.10

---

docs/source/conf.py

002f77cedc9a5c772ebcfb0c5d245a98044c8b21 removed the last reference to six, so there is no need to pull down the six docs inventory

docs: remove six from the intersphinx mappings

---

docs/source/common_issues.rst

Use lower-case `list`, `tuple`, `type` instead of `List`, `Tuple`, `Type` in documentation.

docs: Use lower-case generics

---

mypy/build.py

Contributes to #6544
Simple fix that prints the absolute path to the config file when in verbose mode

Full path to config file

---

.github/workflows/test.yml

Fix failing MacOS tests in CI
Python 3.9 is not available on the latest MacOS images https://github.com/actions/setup-python/issues/850

Pin MacOS version in GH actions

---

mypy/checkmember.py
mypy/semanal.py
mypy/typeanal.py
mypy/typeops.py
test-data/unit/check-enum.test
test-data/unit/check-literal.test

Enum private attributes are not enum members

---

.github/workflows/test.yml

At some point, Github Actions runners started having more cores: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

Run more tests in parallel

---

mypy/dmypy_server.py

dmypy receives the list of updated files via `--update` flag. If this list contains both `foo.py` and `foo.pyi`, the order matters. It seems to process the first file in the list first. But if we have a `.pyi` file, we want this to be processed first since this one contains the typing information.
Let's reverse sort the list of updated files by the extension. This should be a simple enough fix to resolve this.
Though there might be some edge cases where the list of files to update contains just pyi files, but we might need to recheck the equivalent py files even if not explicitly updated.

[dmypy] sort list of files for update by extension

---

mypy/plugins/default.py
test-data/unit/check-narrowing.test

Fixes #10514
Fixes #17118
Negative integer literals were not being correctly handled in the type narrowing process, causing mypy errors such as "Statement is unreachable" despite the checked code being valid. This fix ensures that negative integer literals are properly considered in if-statements.

Fix for type narrowing of negative integer literals

---

mypy/checker.py
mypy/fastparse.py
mypy/join.py
mypy/nodes.py
mypy/options.py
mypy/partially_defined.py
mypy/semanal.py
mypy/strconv.py
mypy/subtypes.py
mypy/test/testparse.py
mypy/traverser.py
mypy/typestate.py
mypy/visitor.py
mypyc/irbuild/visitor.py
test-data/unit/check-python312.test
test-data/unit/parse-python312.test
test-data/unit/pythoneval.test

Add basic support for most features of PEP 695. It's still not generally useful, but it
should be enough for experimentation and testing. I will continue working on 
follow-up PRs after this has been merged.
This is currently behind a feature flag: `--enable-incomplete-feature=NewGenericSyntax`
These features, among other things, are unimplemented (or at least untested):
* Recursive type aliases
* Checking for various errors
* Inference of variance in complex cases
* Dealing with unknown variance consistently
* Scoping
* Mypy daemon
* Compilation using mypyc
The trickiest remaining thing is probably variance inference in cases where some types
aren't ready (i.e. not inferred) when we need variance. I have some ideas about how to
tackle this, but it might need significant work. Currently …

[PEP 695] Partial support for new type parameter syntax in Python 3.12

---

mypy/nodes.py
mypy/semanal.py
mypy/typeanal.py
test-data/unit/check-python312.test

Type parameters get a separate scope with some special features.

[PEP 695] Implement new scoping rules for type parameters

---

mypy/semanal_namedtuple.py
test-data/unit/check-namedtuple.test
test-data/unit/semanal-namedtuple.test

A pretty marginal feature but it's now tested in the typing conformance suite,
and it was easy to add support.
For reference: https://github.com/python/typing/blob/9f7f400bb7c4c79f1fb938402e0bb3198dac0054/conformance/tests/namedtuples_define_functional.py#L46, https://github.com/python/cpython/blob/7d8725ac6f3304677d71dabdb7c184e98a62d864/Lib/collections/__init__.py#L389

Support rename=True in collections.namedtuple

---

mypy/stubtest.py

Technically it feels like we should be able to put the new dunders on `type` or something, but that wasn't enough to make false positives go away. But also we might not want to do that because it only applies to pure Python types

stubtest: changes for py313

---

mypyc/ir/ops.py
mypyc/irbuild/ll_builder.py
mypyc/primitives/int_ops.py
mypyc/primitives/registry.py

Pure primitives have no side effects, take only immutable arguments,
and never fail. These properties will enable additional
optimizations. For example, it doesn't matter in which order
these primitives are evaluated, and we can perform common
subexpression elimination on them.
Only mark a few primitives as pure for now, but we can generalize
this later.

[mypyc] Allow specifying primitives as pure

---

test-data/unit/check-python310.test

Add a test demonstrating #17230.

Add test documenting #17230

---

mypy/pyinfo.py

This Pull Request Fixes #16669 . This pull request makes a one line change to mypy/pyinfo.py to force the stdout of the python process to use utf-8.
One can replicate this error in Windows using Python3.8 just by calling the mypy/pyinfo.py module using a slightly modified code of the  `get_search_dirs` function where the python executable doesn't match the value of sys.executable. The only modification made to this code from `get_search_dirs` is the adding of a non-ascii-path to the env parameter to subprocess. 
```python
python_executable: str = r"<your_path_to_python_executable>\python.exe"
non_ascii_path = r"<any_non_ascii_path>"
env = {**dict(os.environ), "PYTHONSAFEPATH": "1"}
env.update({"PYTHONPATH": non_ascii_path}) 
try:
sys_path, site_packages = ast.literal_eval( …
```

Fixes #16669 

---

mypy/stubgen.py
test-data/unit/stubgen.test

See https://github.com/python/typing-council/issues/11

stubgen: preserve enum value initialisers

---

mypy/test/data.py
mypy/test/helpers.py

Unless there is a reason to have the error, I think this improves the developer experience.

Automatically set -n=0 when running tests with --update-data

---

mypy/fastparse.py

Fixes #17216
During conversion from a standard library AST to the mypy AST, `Var` nodes were being created inside `Argument` nodes  without acknowledging the presence of a type annotation, leading to the `Var` node's type as being always set as *inferred*:
https://github.com/python/mypy/blob/fb31409b392c5533b25173705d62ed385ee39cfb/mypy/nodes.py#L988
This causes an error at
https://github.com/python/mypy/blob/fb31409b392c5533b25173705d62ed385ee39cfb/mypyc/irbuild/expression.py#L161-L164
The fix simply acknowledges any presence of a type annotation, so the type of the relevant `Var` node is no longer considered inferred if an annotation is present.

fix: annotated argument's `var` node type is explicit, not inferred

---

mypy/checker.py
mypy/nodes.py
test-data/unit/check-dynamic-typing.test
test-data/unit/check-functions.test

This commit fixes #9618 by making MyPy always complain if a method overrides a base class method marked as `@final`.
In the process, it also adds a few additional validations:
- Always verify the `@override` decorator, which ought to be pretty backward-compatible for most projects assuming that strict override checks aren't enabled by default (and it appears to me that `--enable-error-code explicit-override` is off by default)
- Verify that the method signature is compatible (which in practice means only arity and argument name checks) *if* the `--check-untyped-defs` flag is set; it seems unlikely that a user would want mypy to validate the bodies of untyped functions but wouldn't want to be alerted about incompatible overrides.
Note: I did also explore enabling the signature …

Validate more about overrides on untyped methods

---

mypy/checker.py
mypy/join.py
test-data/unit/check-functools.test

Support unions in functools.partial

---

mypy/stubgenc.py

__firstlineno__ and __static_attributes__ are new in 3.13.
__annotate__ will be new in 3.14, so we might as well add it now.
I tried to run the test suite on 3.13. There are a ton of compilation failures from mypyc, and a number of stubgen failures that this PR will fix.

Fix stubgen for Python 3.13

---

mypy/checkmember.py
test-data/unit/check-unions.test

Fix for bug with descriptors in non-strict-optional

---

mypy/checkexpr.py
test-data/unit/check-unreachable-code.test

Don’t leak unreachability from lambda body to surrounding scope

---

mypy/checker.py
test-data/unit/check-unreachable-code.test

Avoid does not return error in lambda

---

docs/source/command_line.rst
docs/source/config_file.rst

This PR closes issue https://github.com/python/mypy/issues/16693 and a part of issue https://github.com/python/mypy/issues/17083
Propositional documentation updates for show-error-code-links, which update files command_line.rst and config_file.rst.

Add documentation for show-error-code-links

---

mypy/copytype.py
mypy/join.py
mypy/messages.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-dataclasses.test
test-data/unit/check-flags.test
test-data/unit/check-literal.test
test-data/unit/check-plugin-attrs.test
test-data/unit/check-python310.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typeddict.test

Switches the logic from https://github.com/python/mypy/pull/16994 to use ambiguous (since is_noreturn was only meant for error messages)
See also https://github.com/python/mypy/pull/15996

Use Never in more messages, use ambiguous in join

---

mypy-requirements.txt
pyproject.toml

With earlier versions of typing_extensions, the following traceback is seen:
```
File ".../bin/mypy", line 5, in <module>
from mypy.__main__ import console_entry
File ".../lib/python3.12/site-packages/mypy/__main__.py", line 9, in <module>
from mypy.main import main, process_options
File ".../lib/python3.12/site-packages/mypy/main.py", line 12, in <module>
from typing_extensions import Final
File ".../lib/python3.12/site-packages/typing_extensions.py", line 1174, in <module>
class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type
```
The error is addressed in typing_extensions in
https://github.com/python/typing_extensions/pull/162, which is included
in the 4.6.0 release.
(Explain how this …

Update 'typing_extensions' to >=4.6.0 to fix python 3.12 error

---

mypy-requirements.txt
pyproject.toml
setup.py

Followup to #17312. (Can't say I fully understand why we have to have this pin in three places :)

Sync typing_extensions pin in setup.py with the pin in the other two places

---

mypy/message_registry.py
mypy/messages.py
mypy/semanal.py
mypy/typeanal.py
test-data/unit/check-python312.test

Fix badly formed types that could be created when using aliases like `type A = list`.
Improve some error messages when using PEP 695 syntax.
Add a few PEP 695 tests.

[PEP 695] Fix a few issues and add tests

---

mypy/checkexpr.py
mypy/nodes.py
mypy/semanal.py
test-data/unit/check-python312.test
test-data/unit/check-type-aliases.test
test-data/unit/fixtures/typing-full.pyi

PEP 695 type aliases raise an exception at runtime if called.

[PEP 695] Generate error if 3.12 type alias is called

---

mypy/test/testdeps.py
mypy/test/testdiff.py
mypy/test/testfinegrained.py
mypy/traverser.py
test-data/unit/deps.test
test-data/unit/diff.test
test-data/unit/fine-grained-python312.test

Add some basic mypy daemon test coverage, and make it possible to write daemon tests that only work on recent Python versions.
Everything tested seems to work already.

[PEP 695] Add daemon tests that use new type parameter syntax

---

mypy/semanal.py
test-data/unit/check-final.test

This PR fixes and closes #17281 ,which reported a false positive when using Final within the local function scope of a protocol method.
With these changes:
- Local variables within protocol methods can be marked as Final.
- Protocol members still cannot be marked as Final
Modified ``semanal.py`` file and added a unit test in ``test-data/unit/check.final.test``

Fix False positive - Final local scope variable in Protocol

---

mypy/typeanal.py
test-data/unit/check-typeddict.test

Do not set the `unpacked_kwargs` attribute of `CallableType` to False when visiting a callable of which the `Unpack` wrapper of a `TypedDict` has already been removed.
Fixes #17225

Do not forget that a `TypedDict` was wrapped in `Unpack` after a `name-defined` error occurred.

---

mypy/checker.py
mypy/checkexpr.py
mypy/expandtype.py
mypy/join.py
mypy/meet.py
mypy/messages.py
mypy/plugins/attrs.py
mypy/plugins/dataclasses.py
mypy/plugins/functools.py
mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/semanal_shared.py
mypy/subtypes.py
mypy/test/testtypes.py
mypy/test/typefixture.py
mypy/tvar_scope.py
mypy/typeanal.py
mypy/types.py
mypyc/test-data/fixtures/testutil.py
test-data/unit/check-functions.test
test-data/unit/check-functools.test
test-data/unit/check-generics.test
test-data/unit/check-inference.test
test-data/unit/check-python311.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/16582
IMO this is long overdue. Currently, type variable IDs are 99% unique, but when they accidentally clash, it causes hard to debug issues. The implementation is generally straightforward, but it uncovered a whole bunch of unrelated bugs. Few notes:
* This still doesn't fix the type variables in nested generic callable types (those that appear in return types of another generic callable). It is non-trivial to put namespace there, and luckily this situation is already special-cased in `checkexpr.py` to avoid ID clashes.
* This uncovered a bug in overloaded dunder overrides handling, fix is simple.
* This also uncovered a deeper problem in unsafe overload overlap logic (w.r.t. partial parameters overlap). Here proper fix would be hard, so …

Use namespaces for function type variables

---

mypy/semanal.py
test-data/unit/check-python312.test

[PEP 695] Don't crash when redefining something as a type alias

---

mypy/semanal.py
test-data/unit/check-python312.test

This was generating a false positive.

[PEP 695] Fix handling of undefined name in generic function annotation

---

mypy/applytype.py
mypy/checkexpr.py

Moving towards https://github.com/python/mypy/issues/15907
This is a pure refactoring. It was surprisingly easy, this didn't add new import cycles, because there is already (somewhat fundamental) cycle `applytype.py` <-> `subtypes.py`.

Move apply_type() to applytype.py

---

mypy/typeanal.py
test-data/unit/check-recursive-types.test

Fixes https://github.com/python/mypy/issues/17132
Fix is trivial, we don't need that extra `get_proper_type()`.

Fix crash on recursive alias with an optional type

---

mypy/checker.py
test-data/unit/check-namedtuple.test

Fixes https://github.com/python/mypy/issues/17010
Fix is trivial: replicate the `TypeVar` handling logic in the caller.

Fix crash on unpacking self in NamedTuple

---

mypy/checker.py
test-data/unit/check-functions.test

Fixes https://github.com/python/mypy/issues/16896
Fix is simple, do not assume that an error context given by the caller of the override check for callable type is a method defining such type, because it may be a property.

Fix crash on invalid callable property override

---

mypy/subtypes.py
test-data/unit/check-recursive-types.test

Fixes https://github.com/python/mypy/issues/17236
It turns out we were calculating tuple fallbacks where we don't really need to. We can rely on the fact that tuple fallback is trivial for non-trivial partial fallbacks to simplify the logic and avoid the infinite recursion.

Fix crash involving recursive union of tuples

---

mypy/meet.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/17319
This is still not 100% robust, but at least it should not crash, and should cover correctly vast majority of cases.

Properly handle unpacks in overlap checks

---

mypy/applytype.py
mypy/checkexpr.py
mypy/typeanal.py
test-data/unit/check-generics.test
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/17212
Note I removed the problematic asset after all. It is hard to maintain it, since this function may be called from both explicit application, and from type inference code paths. And these two cases may have different min/max type argument count (see tests and comments for examples).

Fix type application for classes with generic constructors

---

mypy/constraints.py
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/17345
Fixes https://github.com/python/mypy/issues/17112
Fixes https://github.com/python/mypy/issues/16616
Oh well, I clearly remember I have put those lines before `if` only because otherwise the line would be 101 chars long, and I didn't want to wrap arguments. Now I see it was a bad idea, LOL.

Fix crash on TypedDict unpacking for ParamSpec

---

mypy/checker.py
test-data/unit/check-functions.test

Fixes https://github.com/python/mypy/issues/17208
While writing the fix (that is trivial), I could not notice that the relevant code simply assumes functions can have nothing but positional parameters. This could lead really misleading error messages, so I decided to fix this as well.

Fix crash when overriding with unpacked TypedDict

---

mypy/stubgenc.py

Avoid encoding errors if functions contain non-ASCII characters.

Write stubs for C module with utf-8 encoding

---

mypy/checkmember.py
mypy/plugins/enums.py
test-data/unit/check-enum.test
test-data/unit/lib-stub/enum.pyi

This PR adds support for https://docs.python.org/3.11/library/enum.html#enum.nonmember
Refs https://github.com/python/mypy/issues/12841

Support `enum.nonmember` for python3.11+

---

docs/source/error_code_list2.rst
docs/source/error_codes.rst

This page already says:
> The examples in this section use inline configuration
But some of these examples predate support for inline configuration of error codes that was added in #13502

Use inline config in the optional error codes docs

---

mypy/plugins/default.py
mypy/plugins/enums.py
test-data/unit/check-enum.test
test-data/unit/lib-stub/enum.pyi

There are no tests for `@enum.member` used as a decorator, because I can only decorate classes and functions, which are not supported right now: https://mypy-play.net/?mypy=latest&python=3.12&gist=449ee8c12eba9f807cfc7832f1ea2c49
```python
import enum
class A(enum.Enum):
class x: ...
reveal_type(A.x)  # Revealed type is "def () -> __main__.A.x"
```
This issue is separate and rather complex, so I would prefer to solve it independently.
Refs https://github.com/python/mypy/pull/17376

Support `enum.member` for python3.11+

---

mypy/errorcodes.py
mypy/fastparse.py
mypy/message_registry.py
mypy/semanal.py
test-data/unit/check-python312.test
test-data/unit/semanal-errors.test

Detect invalid number of constrained types. At least two are required, according do PEP 695.
Add tests for other simple errors.

[PEP 695] Add more error checks and tests for error conditions

---

mypy/stubgen.py
mypy/stubutil.py
test-data/unit/stubgen.test

This Fixes 2 issues with invalid `Optional` (inspired by an error reported in #17197):
- do not crash on empty `Optional`
- treat `Optional` with more than one index as an unknown type instead of choosing the first type.
It also fixes PEP 604 unions not being recognized as type aliases.

stubgen: Gracefully handle invalid `Optional` and recognize aliases to PEP 604 unions

---

mypy/checkexpr.py
mypy/checkmember.py
test-data/unit/check-classes.test
test-data/unit/check-recursive-types.test
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/16547
Fixes https://github.com/python/mypy/issues/16410
Fixes https://github.com/python/mypy/issues/5570
From the upvotes on the issue it looks like an important use case. From what I see this is an omission in the original implementation, I don't see any additional unsafety (except for the same that exists for instance methods/variables). I also incorporate a small refactoring and remove couple unused `get_proper_type()` calls.
The fix uncovered an unrelated issue with unions in descriptors, so I fix that one as well.

Allow new-style self-types in classmethods

---

mypy/meet.py
test-data/unit/check-statements.test

Fixes https://github.com/python/mypy/issues/8869
The fix seems straightforward.

Consider overlap between instances and callables

---

mypy/checkexpr.py
mypy/plugins/functools.py
test-data/unit/check-functools.test

Fixes https://github.com/python/mypy/issues/17405
Apart from fixing the crash I fix two obvious bugs I noticed while making this PR.
cc @hauntsaninja

Some cleanup in partial plugin

---

mypy/plugins/functools.py
test-data/unit/check-functools.test

Fixes https://github.com/python/mypy/issues/17301
cc @hauntsaninja

Fix explicit type for partial

---

mypy/plugins/functools.py
test-data/unit/check-functools.test

This is a bit unfortunate, but the best we can probably do.
cc @hauntsaninja

Fix previous partial fix

---

mypy/checkexpr.py
mypy/nodes.py
mypy/plugins/functools.py
test-data/unit/check-functions.test

See https://github.com/python/mypy/pull/17408 for context.

Always allow lambda calls

---

mypy/checker.py
test-data/unit/check-custom-plugin.test
test-data/unit/check-dataclasses.test
test-data/unit/plugins/add_method.py

Closes https://github.com/typeddjango/django-stubs/issues/2226
Closes https://github.com/python/mypy/issues/17417
Closes https://github.com/python/mypy/pull/17370
Closes https://github.com/python/mypy/issues/17224
This is an alternative to https://github.com/python/mypy/pull/17418
Thanks a lot to @sterliakov, I took a dataclasses test case from #17370

Do not report plugin-generated methods with `explicit-override`

---

mypy/constraints.py
mypy/expandtype.py
mypy/semanal_typeargs.py
mypy/types.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/17278
Fixes https://github.com/python/mypy/issues/17127

Fix ParamSpec inference against TypeVarTuple

---

docs/source/error_code_list2.rst

Diff:
```diff
-You can assign the value to a temporary, otherwise unused to variable to silence the error
+You can assign the value to a temporary, otherwise unused variable to silence the error
```

Fix typo in `error_code_list2.rst`

---

mypy/erasetype.py
mypy/nodes.py
mypy/semanal_typeargs.py
mypy/typevars.py
mypy/typevartuples.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/16696
Fixes https://github.com/python/mypy/issues/16695
I think there are no good reasons to not allow this anymore. Also I am using this opportunity to tighten a bit invalid instances/aliases where a regular type variable is replaced with parameters and vice versa.

Allow mixing ParamSpec and TypeVarTuple in Generic

---

mypy/plugins/attrs.py
test-data/unit/check-plugin-attrs.test

Fixes https://github.com/python/mypy/issues/13794
Fix is trivial (but unlike for dataclasses, the calls to type ops are scattered, so I simply put the whole hook inside a single `with`).

Fix strict optional handling in attrs plugin

---

mypy/checkexpr.py
test-data/unit/check-async-await.test

Fixes #10534
This PR fixes a bug in typechecking asynchronous generators.
Mypy currently typechecks a generator/comprehension as `AsyncGenerator` if the leftmost expression contains `await`, or if it contains an `async for`.
However, there are other situations where we should get async generator: If there is an `await` expression in any of the conditions or in any sequence except for the leftmost one, the generator/comprehension should also be typechecked as `AsyncGenerator`. 
I've implemented this change in Mypy and added a test case to assert this behavior. If I enter the test cases into a regular repl, I can confirm that the runtime representation is generator/async_generator as the test case expects.
According to the [language …

Fix typechecking for async generators

---

.github/workflows/mypy_primer.yml

I'd like for us to cover projects that use Python 3.12 only syntax, like homeassistant

Use Python 3.12 for mypy_primer

---

mypy/checkexpr.py
mypyc/test-data/irbuild-any.test
test-data/unit/check-errorcodes.test
test-data/unit/check-expressions.test
test-data/unit/check-functions.test
test-data/unit/check-inference-context.test
test-data/unit/check-inference.test
test-data/unit/check-optional.test
test-data/unit/check-tuples.test

Ref https://github.com/python/mypy/issues/12056
cc @JukkaL 
Again, let's check the primer...

Infer unions for ternary expressions

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Add `__replace__`, which is now present on dataclasses in 3.13, which is creating false alarms in TypeShed on dataclasses, and is needed for `copy.replace` to work properly.
Fixes https://github.com/python/mypy/issues/17471

Add `__replace__` for dataclasses

---

mypy/semanal_namedtuple.py
test-data/unit/check-namedtuple.test

Have `__replace__` for named tuples return `Self` to ensure protocol compatibility with `copy.replace` in the typeshed, and to be accurate to the actual dunder.

Have namedtuple `__replace__` return `Self`

---

mypy/semanal_classprop.py

There's no need to create and call a temporary function, when we can just call an existing method: faster and simplier.

Refactor: remove temporary `def` from `semanal_classprop.check_protocol_status`

---

mypy/semanal_namedtuple.py
test-data/unit/check-namedtuple.test

Revert "Have namedtuple `__replace__` return `Self`"

---

.github/workflows/docs.yml
.github/workflows/test.yml
test-requirements.in
test-requirements.txt

https://github.com/python/mypy/issues/17264

Run Python 3.13 tests in CI (with failures allowed)

---

docs/source/type_narrowing.rst

From [<i>Type narrowing</i> &sect; <i>Limitations</i>](https://github.com/python/mypy/blob/606971807fad1de26ebc575d327d4c1c33f71c0e/docs/source/type_narrowing.rst#limitations):
```python
def f(a: str | None, b: str | None) -> str:
if a is not None or b is not None:
return a or b  # Incompatible return value type (got "str | None", expected "str")
return 'spam'
```
A trivial counter-example is `f('', None)`, which returns `None`. Ironically, this somewhat makes Mypy's diagnostic "correct".
I propose that `str` be replaced with a custom class `C` whose `__bool__()` is not defined (does it have to be `@final` too?):
```python
class C:
pass
def f(a: C | None, b: C | None) -> C:
if a is not None or b is not None:
return a or b  # Incompatible return value type (got "C | None", expected "C") …
```

Fix cross-variable type-narrowing example

---

mypy/semanal.py
mypy/semanal_typeddict.py
mypy/stats.py
mypy/types.py
test-data/unit/check-flags.test
test-data/unit/check-semanal-error.test
test-data/unit/check-typeddict.test
test-data/unit/reports.test
test-data/unit/semanal-typeddict.test

Fixes https://github.com/python/mypy/issues/10007
Fixes https://github.com/python/mypy/issues/17477
This fixes the crash as proposed in https://github.com/python/mypy/pull/13732, but also fixes some inconsistencies in `Any` types exposed by the fix.

Fix daemon crash on invalid type in TypedDict

---

mypy/semanal_main.py
test-data/unit/check-namedtuple.test

Fixes https://github.com/python/mypy/issues/16814
This one is tricky and may expose some other bugs. But IMO this is strictly correct thing to do.

Fix crash on NamedTuple with method and error in function

---

mypy/solve.py
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/16629
This is really ad-hoc, but a proper fix would be much more hard, and this currently we have a crash in a relatively common scenario.

Fix crash on self-type in callable protocol

---

mypyc/lib-rt/pythonsupport.h

`_PyObject_FastCall` will be removed in 3.13. It can safely replaced by `PyObject_Vectorcall` (available since `3.9`) / `_PyObject_Vectorcall` (available since `3.8`). https://github.com/python/cpython/issues/106023#issuecomment-1613963489
https://peps.python.org/pep-0590/
Fixes
```cpp
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h: In function ‘update_bases’: (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h:62:20: error: implicit declaration of function ‘_PyObject_FastCall’; did you mean ‘PyObject_Call’? [-Werror=implicit-function-declaration] (diff)
62 |         new_base = _PyObject_FastCall(meth, stack, 1); (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h:62:18: error: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer …
```

Fix `_PyObject_FastCall` for Python 3.13

---

mypyc/lib-rt/mypyc_util.h
mypyc/lib-rt/pythonsupport.h

The `_PyInterpreterFrame` struct was changed in https://github.com/python/cpython/pull/105727 to store the code object in `f_executable` instead of `f_code`.
Fixes
```cpp
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h: In function ‘_PyGen_GetCode’: (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h:403:17: error: ‘_PyInterpreterFrame’ has no member named ‘f_code’ (diff)
403 |     return frame->f_code; (diff)
|                 ^~ (diff)
```

Fix `gen_is_coroutine` for Python 3.13

---

mypyc/lib-rt/dict_ops.c
mypyc/lib-rt/list_ops.c

Replace `_PyList_Extend` with `PyList_Extend` from `pythoncapi_compat.h`.
https://github.com/python/cpython/issues/111138
https://docs.python.org/dev/c-api/list.html#c.PyList_Extend
Fixes
```cpp
/home/runner/work/mypy/mypy/mypyc/lib-rt/list_ops.c: In function ‘CPyList_Extend’: (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/list_ops.c:259:12: error: implicit declaration of function ‘_PyList_Extend’; did you mean ‘CPyList_Extend’? [-Werror=implicit-function-declaration] (diff)
259 |     return _PyList_Extend((PyListObject *)o1, o2); (diff)
|            ^~~~~~~~~~~~~~ (diff)
|            CPyList_Extend (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/list_ops.c:259:12: error: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer …
```

Fix `_PyList_Extend` for Python 3.13

---

mypyc/lib-rt/pythonsupport.h

`_PyObject_LookupAttrId` was removed / replaced with `PyObject_GetOptionalAttrString` in https://github.com/python/cpython/pull/106522.
https://docs.python.org/dev/c-api/object.html#c.PyObject_GetOptionalAttrString
Fixes
```cpp
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h: In function ‘update_bases’: (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h:51:13: error: implicit declaration of function ‘_PyObject_LookupAttrId’; did you mean ‘_PyObject_GetAttrId’? [-Werror=implicit-function-declaration] (diff)
51 |         if (_PyObject_LookupAttrId(base, &PyId___mro_entries__, &meth) < 0) { (diff)
|             ^~~~~~~~~~~~~~~~~~~~~~ (diff)
|             _PyObject_GetAttrId (diff)
```

Fix `_PyObject_LookupAttrId` for Python 3.13

---

mypyc/lib-rt/getargs.c
mypyc/lib-rt/pythonsupport.h
mypyc/lib-rt/str_ops.c

Replace `_PyUnicode_EqualToASCIIString` with `PyUnicode_EqualToUTF8`.
https://docs.python.org/dev/c-api/unicode.html#c.PyUnicode_EqualToUTF8
https://github.com/python/cpython/issues/110289
Fixes
```cpp
/home/runner/work/mypy/mypy/mypyc/lib-rt/getargs.c: In function ‘vgetargskeywords’: (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h:310:45: error: implicit declaration of function ‘_PyUnicode_EqualToASCIIString’; did you mean ‘CPyUnicode_EqualToASCIIString’? [-Werror=implicit-function-declaration] (diff)
310 | #define CPyUnicode_EqualToASCIIString(x, y) _PyUnicode_EqualToASCIIString(x, y) (diff)
|                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ (diff)
/home/runner/work/mypy/mypy/mypyc/lib-rt/getargs.c:398:21: note: in expansion of macro …
```

Fix `PyUnicode` functions for Python 3.13

---

mypyc/lib-rt/pythonsupport.h

Define `Py_BUILD_CORE` required by `internal/...` header files. Include additional headers for moved private functions.
```cpp
/opt/hostedtoolcache/Python/3.13.0-beta.3/x64/include/python3.13/internal/pycore_frame.h:8:4: error: #error "this header requires Py_BUILD_CORE define" (diff)
8 | #  error "this header requires Py_BUILD_CORE define" (diff)
```

Add additional includes for Python 3.13

---

mypyc/lib-rt/pythonsupport.h

Include `internal/pycore_setobject.h` necessary for `_PySet_Update`.

Add another include for Python 3.13

---

mypyc/lib-rt/getargsfast.c

[mypyc] Don't use _PyUnicode_EQ on 3.13, as it's no longer exported

---

mypyc/lib-rt/str_ops.c

[mypyc] Don't use _PyUnicode_FastCopyCharacters on 3.13

---

mypyc/lib-rt/CPy.h
mypyc/lib-rt/misc_ops.c

Copy the implementation from CPython (with minor changes), as it's no longer exported.
Work on mypyc/mypyc#1056.

[mypyc] Don't rely on _PyType_CalculateMetaclass on 3.13

---

CHANGELOG.md

Added additional sections for major features and did various other updates.

Update CHANGELOG for mypy 1.11

---

mypy/checkexpr.py
test-data/unit/check-functions.test

Fix types.GenericAlias lookup crash

---

mypy/checkexpr.py
test-data/unit/check-type-aliases.test

Closes #17554
CC @JukkaL 
Refs https://github.com/python/mypy/pull/17320

Fix `typing.TypeAliasType` being undefined on python < 3.12

---

docs/source/conf.py

This allows the underlying theme being used to provide the pygments theme instead which looks better (subjectively).

Remove the explicit setting of a pygments theme

---

mypy/types.py
test-data/unit/check-typeddict.test

Commit 1072c78ad375b7f0511549287f54432050396717 (#17148) converted all quoted types into `RawExpressionType`, which raised an `AssertionError` when `accept`ing a `TypeTriggersVisitor`.
- Fixes #17574.
- Fixes #17587.

Fix `RawExpressionType.accept` crash with `--cache-fine-grained`

---

mypy/main.py
mypy/options.py
mypy/stubtest.py
mypy/test/teststubtest.py

This is the first PR in the series of unifing configuration parsing for different mypy tools.
I would like to have the simple and focused.

Fix error code handling in `stubtest` with `--mypy-config-file`

---

mypy/stubgen.py

The option is called `--inspect-mode`, not `--inspect`
It used to be:
```
» stubgen --help
usage: stubgen [-h] [more options, see -h]
[-m MODULE] [-p PACKAGE] [files ...]
Generate draft stubs for modules. Stubs are generated in directory ./out, to avoid
overriding files with manual changes. This directory is assumed to exist.
positional arguments:
files                 generate stubs for given files or directories
options:
--no-analysis, --parse-only
don't perform semantic analysis of sources, just parse them (only
applies to Python modules, might affect quality of stubs. Not
compatible with --inspect)
--inspect-mode        import and inspect modules instead of parsing source code.This is
the default behavior for c modules and pyc-only packages, but it
is also useful for pure python …
```

Fix `stubgen --no-analysis/--parse-only` docs

---

docs/source/command_line.rst

It was strange to see only one feature: 
```rst
.. option:: --enable-incomplete-feature {PreciseTupleTypes}
```

List all incomplete features in `--enable-incomplete-feature` docs

---

mypy/types.py
test-data/unit/check-typeddict.test

Revert "Fix `RawExpressionType.accept` crash with `--cache-fine-grained`"

---

mypy/fastparse.py
mypy/semanal.py
mypy/server/astmerge.py
mypy/stubutil.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py
mypy/typetraverser.py
mypyc/irbuild/classdef.py
test-data/unit/check-final.test
test-data/unit/check-literal.test
test-data/unit/check-namedtuple.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-typeguard.test
test-data/unit/check-typeis.test

Revert "Fix Literal strings containing pipe characters"

---

mypy/semanal_typeddict.py
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/17604
Fixes https://github.com/python/mypy/issues/17608
Fix is trivial, rectify an obvious omission in my original PR.

Unwrap TypedDict item types before storing

---

mypy/typeops.py
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/17518

Fix crash on a callable attribute with single unpack

---

mypy/checker.py
test-data/unit/check-functions.test

Fixes https://github.com/python/mypy/issues/17595

Always reset binder when checking deferred nodes

---

mypy/main.py
mypy/options.py
mypy/stubtest.py
mypy/test/teststubtest.py

Closes #17634
Refs #17628 
Refs #17629

Add `enable_incomplete_feature` validation to `stubtest`

---

mypy/checker.py
test-data/unit/check-functools.test

Resolve TypeVar upper bounds in functools.partial

---

mypy/stubtest.py
mypy/test/teststubtest.py

stubtest: Add support for cached_property

---

mypy/fastparse.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-literal.test

It is unfortunate to add two extra slots to a common type (and I guess this is why it was rejected in the original PR), but all other alternatives I tried are hacky and/or dangerous. So, this is a price to pay for introducing a new type syntax.
cc @JelleZijlstra

An alternative fix for a union-like literal string

---

mypy/stubgen.py

I was surprised to see `mypy --version` and `stubtest --version`, but no `stubgen --version`
Refs https://github.com/python/mypy/pull/12852

Stubgen add `--version`

---

mypy/stubgen.py
test-data/unit/stubgen.test

Closes https://github.com/python/mypy/issues/17661
CC @srittau @JelleZijlstra @AlexWaygood

[stubgen] Fix crash on literal class-level keywords

---

mypy/test/teststubtest.py

This adds a test for incorrect error code in `stubtest`'s config file.
Refs https://github.com/python/mypy/issues/17628

Add optional stderr result to `run_stubtest` in tests

---

mypyc/lib-rt/dict_ops.c
mypyc/lib-rt/pythonsupport.h

It's no longer available in CPython 3.13 betas.
This fixes some dict primitives on 3.13.
Work on mypyc/mypyc#1056.

[mypyc] Avoid uses of _PyObject_CallMethodOneArg on 3.13

---

mypy/fastparse.py
mypy/semanal.py
mypy/semanal_typeddict.py
mypy/server/astmerge.py
mypy/stubutil.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py
mypy/typetraverser.py
mypyc/irbuild/classdef.py
test-data/unit/check-final.test
test-data/unit/check-literal.test
test-data/unit/check-namedtuple.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-typeddict.test
test-data/unit/check-typeguard.test
test-data/unit/check-typeis.test

Bugfix release requested from https://github.com/python/mypy/issues/17285#issuecomment-2270006352 and https://github.com/python/mypy/issues/17285#issuecomment-2286617509
Includes the changes from https://github.com/python/mypy/pull/17675

1.11.2 backport bugfixes

---

mypy/typeops.py
mypy/types.py
test-data/unit/check-recursive-types.test

Fixes https://github.com/python/mypy/issues/17691
This looks quite ad-hoc, but the only clean alternative is to remove the existing recursive types optimization we have in `subtypes.py`. But the best I can get without that optimization is -7% performance penalty (on self-check). So I think it is not worth it, since it is still a corner case.
cc @JukkaL

Fix another crash scenario on recursive tuple types

---

mypyc/doc/conf.py

There was a type-ignore here. But we can simply do what mypy is asking us to do; in fact, the comment even already tells us these have to be strings, (like the other arrays).

[nit] conf.py: annotate the type, instead of ignoring the error

---

mypy/report.py
mypy/test/testreports.py
test-data/unit/reports.test

This PR resolves an issue where the Cobertura XML report generated by MyPy was missing the lines-covered and lines-valid attributes in the <coverage> element.
Changes made:
- Added the lines-covered and lines-valid attributes to the <coverage> element in the Cobertura XML report.
- Updated the CoberturaReportSuite test suite to validate that these attributes are correctly included in the generated XML.
Fixes #17689

Add missing lines-covered and lines-valid attributes

---

mypy/checker.py
mypy/checkexpr.py
test-data/unit/check-errorcodes.test

Closes https://github.com/python/mypy/issues/17769

Check for `truthy-bool` in `not ...` unary expressions

---

mypy/exprtotype.py
mypy/semanal.py
test-data/unit/check-python312.test

The rvalue expression isn't semantically analyzed, so we can't rely on the `fullname` attribute to check if there is a reference to `Annotated`. Instead, use a lookup function provided by the caller to determine the fullname.
Error reporting in the second argument to `Annotated` is still inconsistent, but this seems lower priority. I'll create a follow-up issue about (or update an existing issue if one exists).
Fixes #17751.

[PEP 695] Support Annotated[...] in new-style type aliases

---

mypy/subtypes.py
test-data/unit/check-python312.test

Fix this conformance test:
```
class ShouldBeCovariant5[T]:
def __init__(self, x: T) -> None:
self._x = x
@property
def x(self) -> T:
return self._x
vo5_1: ShouldBeCovariant5[float] = ShouldBeCovariant5[int](1)  # OK
vo5_2: ShouldBeCovariant5[int] = ShouldBeCovariant5[float](1)  # E
```
My fix is to treat such attributes as not settable when inferring variance.
Link:
https://github.com/python/typing/blob/main/conformance/tests/generics_variance_inference.py#L79

[PEP 695] Allow covariance with attribute that has "_" name prefix

---

mypy/subtypes.py
test-data/unit/check-python312.test

Fix this conformance test:
```
@dataclass(frozen=True)
class ShouldBeCovariant4[T]:
x: T
vo4_1: ShouldBeCovariant4[float] = ShouldBeCovariant4[int](1)  # OK
vo4_2: ShouldBeCovariant4[int] = ShouldBeCovariant4[float](1)  # E
```
Link:
https://github.com/python/typing/blob/main/conformance/tests/generics_variance_inference.py#L66

[PEP 695] Fix covariance of frozen dataclasses

---

mypy/semanal.py
test-data/unit/check-python312.test

Test case from typing conformance test suite:
https://github.com/python/typing/blob/main/conformance/tests/generics_syntax_declarations.py#L45

[PEP 695] Fix crash on invalid type var reference

---

mypy/subtypes.py
test-data/unit/check-python312.test
test-data/unit/fixtures/tuple-simple.pyi

Previously we only inferred variance based on member types, but if a base class has explicit variance for some type variables, we need to consider it as well.

[PEP 695] Inherit variance if base class has explicit variance

---

mypy/semanal.py
test-data/unit/check-python312.test

[PEP 695] Generate error if new-style type alias used as base class

---

mypy/messages.py
test-data/unit/check-functions.test

Fixes #17792. Related to #17791.
Currently, [`pretty_callable`](https://github.com/python/mypy/blob/5dfc7d941253553ab77836e9845cb8fdfb9d23a9/mypy/messages.py#L2862) only renders `TypeVar` upper bounds if they are of type `Instance`:
https://github.com/python/mypy/blob/5dfc7d941253553ab77836e9845cb8fdfb9d23a9/mypy/messages.py#L2943-L2949
However, there are some types that can appear as `TypeVar` upper bounds which are not represented by `Instance`, such as `UnionType` and `CallableType`. 
This PR allows such non-`Instance` upper bounds to be rendered as well.
Consider the below code. 
Playground link: https://mypy-play.net/?mypy=1.11.2&python=3.12&enable-incomplete-feature=NewGenericSyntax&gist=ba30c820cc3668e0919dadf2f391ff4b
```python
from collections.abc import Callable
from typing …
```

Fix TypeVar upper bounds sometimes not being displayed in pretty callables

---

mypy/semanal.py
test-data/unit/check-parameter-specification.test

Fixes #17765
The offender for this crash appears to be this snippet:
https://github.com/python/mypy/blob/72c413d2352da5ce1433ef241faca8f40fa1fe27/mypy/semanal.py#L5905-L5910
This branch triggers when applying type args to a type that is generic with respect to a single `ParamSpec`. It allows double brackets to be omitted when providing a parameter specification by wrapping all of the provided type arguments into a single parameter specification argument (i.e. equating `Foo[int, int]` to `Foo[[int, int]]`). This wrapping occurs  *unless*:
* there is only a single type argument, and it resolves to `Any` (e.g. `Foo[Any]`)
* **there is only a single type argument**, and it's a bracketed parameter specification or a `ParamSpec` (e.g. `Foo[[int, int]]`)
The problem occurs when multiple type …

Fix crash when passing too many type arguments to generic base class accepting single ParamSpec

---

docs/source/final_attrs.rst

I originally just wanted to quickly correct a typo in a code example (47cd9d7417e9dd4fbabc99ec691db6d0c9bb8c5d), but then I felt bad making y'all review something so trivial, so I bundled some copyedits into the PR.

Copyedit final_attrs.rst

---

docs/source/generics.rst

Provide examples using both syntax variants, and give both of the syntax variants similar prominence. It's likely that both syntax variants will continue to be widely used for a long time.
Also adjust terminology (e.g. use 'type parameter' / 'type argument' more consistently), since otherwise some descriptions would be unclear.
I didn't update examples outside the generics chapter. I'll do this in a follow-up PR.
Work on #17810.

[PEP 695] Document Python 3.12 type parameter syntax

---

docs/source/additional_features.rst
docs/source/cheat_sheet_py3.rst
docs/source/error_code_list.rst
docs/source/kinds_of_types.rst
docs/source/literal_types.rst
docs/source/metaclasses.rst
docs/source/more_types.rst
docs/source/protocols.rst
docs/source/runtime_troubles.rst
docs/source/type_narrowing.rst

Finish work started in #17816. 
Document `type` statement when discussing type aliases.
Update some examples to have both old-style and new-style variants. In less common scenarios, examples only use a single syntax variant to reduce verbosity. Also update some examples to generally use more modern features.
Closes #17810.

[PEP 695] Further documentation updates

---

mypy/typeops.py
test-data/unit/check-expressions.test
test-data/unit/check-narrowing.test
test-data/unit/check-optional.test
test-data/unit/check-python38.test

Closes #16891
```python
from typing import Literal
def f1(a: str) -> Literal[""]:
return a and exit()  # E: Incompatible return value type (got "str", expected "Literal['']")
def f2(a: int) -> Literal[0]:
return a and exit()  # E: Incompatible return value type (got "int", expected "Literal[0]")
def f3(a: bytes) -> Literal[b""]:
return a and exit()  # E: Incompatible return value type (got "bytes", expected "Literal[b'']")
```
```none
Success: no issues found in 1 source file
```

Narrow falsey str/bytes/int to literal type

---

docs/source/generics.rst

The explanation of self types uses upper bounds, so it makes sense to discuss them earlier.
I also made some other minor documentation tweaks to improve clarity.

Discuss upper bounds before self types in documentation

---

docs/source/additional_features.rst
docs/source/cheat_sheet_py3.rst
docs/source/class_basics.rst
docs/source/command_line.rst
docs/source/common_issues.rst
docs/source/dynamic_typing.rst
docs/source/error_code_list.rst
docs/source/error_code_list2.rst
docs/source/faq.rst
docs/source/generics.rst
docs/source/getting_started.rst
docs/source/kinds_of_types.rst
docs/source/more_types.rst
docs/source/protocols.rst
docs/source/runtime_troubles.rst
docs/source/type_narrowing.rst
docs/source/typed_dict.rst

Use `collections.abc.Iterable`, for example, instead of `typing.Iterable`, unless we are discussing support for older Python versions. The latter has been deprecated since Python 3.9. Also update a few other out-of-date things that I happened to notice.
Part of the motivation is that Python 3.8 will reach end of life in October, so we can soon start mostly assuming that users are on 3.9 or newer (even if we'll continue supporting 3.8 for a while still).

Update various references to deprecated type aliases in docs

---

docs/source/cheat_sheet_py3.rst
docs/source/command_line.rst
docs/source/common_issues.rst
docs/source/config_file.rst
docs/source/error_code_list.rst
docs/source/generics.rst
docs/source/getting_started.rst
docs/source/kinds_of_types.rst
docs/source/literal_types.rst
docs/source/more_types.rst
docs/source/protocols.rst
docs/source/runtime_troubles.rst
docs/source/type_inference_and_annotations.rst
docs/source/type_narrowing.rst

Soon 4 out of 5 supported Python versions will support the `X | Y` syntax,
so we can make it more prominent (Python 3.13 will be out soon, and 3.8
will reach end of life). Use it in most examples.
The syntax is available starting from Python 3.10, but it can be used
in annotations in earlier Python versions as well if using
`from __future__ import annotations`.

Make "X | Y" union syntax more prominent in documentation

---

mypy/checkpattern.py
test-data/unit/check-python310.test

Fixes #17328
Lines marked with `!!!` denote incorrect behavior. ([Playground link](https://mypy-play.net/?mypy=1.11.2&python=3.12&flags=strict%2Cwarn-unreachable&gist=7a7081c5fbc2fac9987f24e02421f24f))
```python
from typing import Literal
m4: tuple[Literal[1], int]
match m4:
case (1, 5):
reveal_type(m4)  # N: Revealed type is "tuple[Literal[1], Literal[5]]"
case (1, 6):
reveal_type(m4)  # !!! E: Statement is unreachable  [unreachable]
case _:
reveal_type(m4)  # !!! N: Revealed type is "tuple[Never, builtins.int]"
m5: tuple[Literal[1, 2], Literal["a", "b"]]
match m5:
case (1, str()):
reveal_type(m5)  # N: Revealed type is "tuple[Literal[1], Union[Literal['a'], Literal['b']]]"
case _:
reveal_type(m5)  # !!! N: Revealed type is "tuple[Literal[2], Never]"
match m5:
case (1, "a"): …
```

Fix negative narrowing of tuples in match statement

---

mypy/applytype.py
mypy/erasetype.py
mypy/expandtype.py
mypy/subtypes.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py

If TypedDict A has multiple items that refer to TypedDict B, don't duplicate the types representing B during type expansion (or generally when translating types). If TypedDicts are deeply nested, this could result in lot of redundant type objects.
Example where this could matter (assume B is a big TypedDict):
```
class B(TypedDict):
...
class A(TypedDict):
a: B
b: B
c: B
...
z: B
```
Also deduplicate large unions. It's common to have aliases that are defined as large unions, and again we want to avoid duplicating these unions.
This may help with #17231, but this fix may not be sufficient.

Avoid type size explosion when expanding types

---

mypy/nodes.py

Fixes #17847
```python
from mypy.nodes import CallExpr, MemberExpr, NameExpr, get_member_expr_fullname
m3 = MemberExpr(MemberExpr(CallExpr(NameExpr("a"), [], [], []), "b"), "c")  # a().b.c
>>> get_member_expr_fullname(m3)
'None.c'
```
```python
from mypy.nodes import CallExpr, MemberExpr, NameExpr, get_member_expr_fullname
m3 = MemberExpr(MemberExpr(CallExpr(NameExpr("a"), [], [], []), "b"), "c")  # a().b.c
>>> get_member_expr_fullname(m3) is None
True
```

Fix get_member_expr_fullname returning strings with embedded "None"

---

mypyc/test-data/run-dicts.test

Related to python/cpython@c6c3d970ba54f4ad4c4151bb262cef96d3299480 (python/cpython#121329), thanks to brianschubert for noticing

Fix tests on latest Python 3.13 (and 3.12)

---

mypy/subtypes.py
test-data/unit/check-isinstance.test
test-data/unit/check-narrowing.test

Fixes #15235
```python
class A:
pass
class B:
b: int
T = TypeVar("T", bound=A | B)
def foo(x: T) -> T:
if isinstance(x, A):
reveal_type(x)      # N: Revealed type is "__main__.A"
else:
reveal_type(x)      # N: Revealed type is "T`-1"
x.b                 # E: Item "A" of the upper bound "A | B" of type variable "T" has no attribute "b"
return x
```
```python
class A:
pass
class B:
b: int
T = TypeVar("T", bound=A | B)
def foo(x: T) -> T:
if isinstance(x, A):
reveal_type(x)      # N: Revealed type is "__main__.A"
else:
reveal_type(x)      # N: Revealed type is "T`-1"
x.b                 # ok! Upper bound of T narrowed to B
return x
```

Enable negative narrowing of Union TypeVar upper bounds

---

mypy/checker.py
test-data/unit/check-narrowing.test
test-data/unit/fixtures/narrowing.pyi

This reverts commit ed0cd4acba02ed19b1cf18ac0ac416dc251d7714.
See #17864 for context. The implementation has some issues, and I'm reverting the PR to unblock the 1.12 release.
Closes #17864. Closes #17841.

Revert "Narrow based on collection containment (#17344)"

---

mypy/typeops.py
test-data/unit/check-narrowing.test

IntEnum/StrEnum values compare equal to the corresponding int/str values, which breaks the logic we use for narrowing based on equality to a literal value. Special case IntEnum/StrEnum to avoid the incorrect behavior.
Fix #17860.

Don't use equality to narrow when value is IntEnum/StrEnum

---

mypy/checker.py
mypy/typeops.py
test-data/unit/check-narrowing.test

Fix regression introduced in #17866. It should still be possible to narrow IntEnum and StrEnum types, but only when types match or are disjoint. Add more logic to rule out narrowing when types are ambigous.

Fix narrowing of IntEnum and StrEnum types

---

mypy/checker.py
test-data/unit/check-narrowing.test

We can assume that None doesn't compare equal to an enum.

Don't consider None vs IntEnum comparison ambiguous

---

mypy/fastparse.py
mypy/message_registry.py
mypy/test/helpers.py
mypy/test/testcheck.py
test-data/unit/check-python313.test

We don't yet support default types for type parameters when using the new type parameter syntax. Generate an error instead of just ignoring them.
Also make it possible to write Python 3.13 specific tests.

[PEP 696] Report error if using unsupported type parameter defaults

---

test-data/unit/check-narrowing.test

https://github.com/python/mypy/issues/17864

Add regression test cases

---

mypy/server/astdiff.py
test-data/unit/fine-grained.test

This is quite a bad bug. Currently we rely on `SymbolNode` being updated in-place for all indirect references, but this is not the case when node kind (`FuncDef`, `Decorator`, etc.) changes, in this case a _new_ `SymbolNode` is created. I fix this by forcing reprocessing if the node kind changes.
This currently blocks support for PEP 702, see https://github.com/python/mypy/pull/17476, so I will not wait for long before merging.

Fix re-processing cross-reference when node kind changes

---

mypyc/test/test_external.py

Most time is spent in compilation, so runtime performance doesn't really matter.

[mypyc] Make C unit tests faster by compiling with -O0

---

mypy/stubtest.py

stubtest: Stop telling people to use double underscores

---

mypy/checker.py
test-data/unit/check-functools.test
test-data/unit/lib-stub/typing_extensions.pyi

Fixes https://github.com/python/mypy/issues/17556 , fixes https://github.com/python/mypy/issues/17659

Improvements to functools.partial of types

---

mypy/subtypes.py
test-data/unit/check-typeddict.test

Make ReadOnly TypedDict items covariant

---

docs/source/typed_dict.rst

Add basic documentation for mypy 1.12 release.

Document ReadOnly (PEP 705)

---

mypy/checker.py
test-data/unit/check-statements.test
test-data/unit/fixtures/notimplemented.pyi

Refs #5710
Adds special-case handling for raising `NotImplemented`:
```python
raise NotImplemented  # E: Exception must be derived from BaseException; did you mean "NotImplementedError"?
```
Per the linked issue, there's some debate as to how to best handle `NotImplemented`.  This PR special-cases its behavior in `raise` statements, whereas the leaning in the issue (at the time it was opened) was towards updating its definition in typeshed and possibly special-casing its use in the relevant dunder methods. 
Going the typeshed/special-dunder route may still happen, but it hasn't in the six years since the issue was opened. It would be nice to at least catch errors from raising `NotImplemented` in the interim.
Making this change also uncovered a regression introduced in …

Emit error for "raise NotImplemented"

---

mypyc/doc/dev-intro.md
runtests.py

Many tests are a bit slow and but don't increase test coverage by a lot. Running these fast tests should find the vast majority of issues while being significantly faster than running all mypyc tests.

[mypyc] Add "runtests.py mypyc-fast" for running fast mypyc tests

---

mypy/plugins/functools.py
test-data/unit/check-functools.test

Fix union callees with functools.partial

---

mypy/main.py

Improve the error message when running `mypy -p packagename` with a
package that doesn't have py.typed set.
> package 'example' is skipping due to missing py.typed marker. See https://mypy.readthedocs.io/en/stable/installed_packages.html for more details
Fix #17048

Better error for `mypy -p package` without py.typed

---

CHANGELOG.md

These were cherry-picked to the release branch.

Add latest 1.12 changes to changelog

---

mypy/errors.py
test-data/unit/cmdline.test

- Fix crash issue when using <code>--pretty</code> with <code>--shadow-file</code>
Example Scenario:
<code>a.py</code>
```python
b: bytes
```
<code>b.py</code>
```python
a: int = ""
b: bytes = 1
```
<code>output</code>
```
$ mypy a.py --pretty --shadow-file a.py b.py
a.py:1: error: Incompatible types in assignment (expression has type "str",
variable has type "int")
a: int = ""
^~
a.py:2: error: Incompatible types in assignment (expression has type "int",
variable has type "bytes")
b: bytes = 1
^
```
Fixes #17853

fix crash issue when using shadowfile with pretty #17853

---

mypy/checker.py
test-data/unit/check-deprecated.test

Two improvements of the current PEP 702 implementation (deprecated):
* Analyse the explicit type annotations of "normal" assignment statements (that have an rvalue).
* Dive into nested type annotations of assignment statements.
(I intend to continue working on PEP 702 and would prefer to do so in small steps if this is okay for the maintainers/reviewers.)

PEP 702 (@deprecated): improve the handling of explicit type annotations of assignment statements

---

mypyc/lib-rt/bytes_ops.c
mypyc/lib-rt/getargsfast.c
mypyc/lib-rt/pythoncapi_compat.h
mypyc/lib-rt/pythonsupport.h

Use functions added for Python 3.14
* `PyBytes_Join` added in https://github.com/python/cpython/issues/121645
* `PyUnicode_Equal` added in https://github.com/python/cpython/issues/124502

[mypyc] Sync pythoncapi_compat.h

---

mypy/build.py
mypy/fscache.py
mypy/fswatcher.py

It's late at night, so I'm probably measuring wrong, but I think I got a 1.5x speed up on the following when running at compile level 3, going from 50s to 33s on a Linux box:
```
mypy -c 'import torch' --no-incremental
```
Not really a measurable change when run interpreted.
See https://github.com/python/mypy/issues/17919

Significantly speed up file handling error paths

---

mypy/plugins/functools.py
test-data/unit/check-functools.test

Fixes https://github.com/python/mypy/issues/17411
The fix is that we remove type variables that can never be inferred from the initial `check_call()` call. Actual diff is tiny, I just moved a bunch of code, since I need formal to actual mapping sooner now.

Better handling of generic functions in partial plugin

---

mypyc/irbuild/classdef.py
mypyc/test-data/run-classes.test

This can be used to declare concise custom exceptions, e.g.
class UnknownReleaseError(ValueError): ...
which otherwise probably would be written
class UnknownReleaseError(ValueError):
pass
and is supported by CPython.
Closes https://github.com/mypyc/mypyc/issues/1069

[mypyc] Support ellipsis (...) expressions in class bodies

---

mypyc/codegen/emitclass.py
mypyc/codegen/emitfunc.py
mypyc/ir/class_ir.py
mypyc/ir/rtypes.py
mypyc/irbuild/classdef.py
mypyc/irbuild/ll_builder.py
mypyc/irbuild/prepare.py
mypyc/irbuild/util.py
mypyc/test-data/run-classes.test

Fixes #9612
This change allows to gain more efficiency where classes are annotated with `@final` bypassing entirely the vtable for method calls and property accessors.
For example:
In
```python
@final
class Vector:
__slots__ = ("_x", "_y")
def __init__(self, x: i32, y: i32) -> None:
self._x = x
self._y = y
@property
def y(self) -> i32:
return self._y
def test_vector() -> None:
v3 = Vector(1, 2)
assert v3.y == 2
```
The call will produce:
```c
...
cpy_r_r6 = CPyDef_Vector___y(cpy_r_r0);
...
```
Instead of:
```c
...
cpy_r_r1 = CPY_GET_ATTR(cpy_r_r0, CPyType_Vector, 2, farm_rush___engine___vectors2___VectorObject, int32_t); /* y */
...
```
(which uses vtable)

[mypyc] Optimize calls to final classes

---

mypyc/lib-rt/pythonsupport.h

Instead of copying the implementation of `_PyGen_GetCode` every time it changes in cpython, use the public `PyGen_GetCode` function. The current implementation would break for Python 3.14 as it has been changed upstream in https://github.com/python/cpython/pull/120835.

[mypyc] Use PyGen_GetCode in gen_is_coroutine

---

.pre-commit-config.yaml
test-requirements.in
test-requirements.txt

Update to 24.8.0 the last release with support for Python 3.8.
https://github.com/psf/black/blob/24.8.0/CHANGES.md

Update black to 24.8.0

---

.pre-commit-config.yaml
mypy/fastparse.py
mypy/ipc.py
mypy/server/astmerge.py
mypy/stubtest.py
mypy/util.py
pyproject.toml
test-requirements.in
test-requirements.txt

https://github.com/astral-sh/ruff/blob/0.6.9/CHANGELOG.md

Update ruff to 0.6.9

---

mypyc/lib-rt/pythoncapi_compat.h

https://github.com/python/mypy/pull/17929 seems to have broken the wheel builder but only on Windows with Python 3.13.
```
C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.13.0\tools\include\internal\pycore_unicodeobject.h(262): error C2375: '_PyUnicode_Equal': redefinition; different linkage
D:\a\mypy_mypyc-wheels\mypy_mypyc-wheels\mypy\mypyc\lib-rt\pythoncapi_compat.h(1540): note: see declaration of '_PyUnicode_Equal'
C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.13.0\tools\include\internal\pycore_pyhash.h(24): error C2375: '_Py_HashBytes': redefinition; different linkage
D:\a\mypy_mypyc-wheels\mypy_mypyc-wheels\mypy\mypyc\lib-rt\pythoncapi_compat.h(1567): note: see declaration of '_Py_HashBytes'
``` …

[mypyc] Fix wheel build for cp313-win

---

test-requirements.in
test-requirements.txt

This PR fixes #17902 
- Adds pre_commit to the `test-requirements.txt`
- Resolves the `module not found` for pre_commit after fresh installation of `test-requirements.txt`

fix: make pre_commit installable via test-requirements.txt

---

docs/source/conf.py

fix: #17870 
The current docs `edit` the page button gives a 404.
This PR edits the sphinx `config.py` and configures the edit button url to the `master` branch of this repository.

[docs]: fix the edit page buttton link in docs

---

.github/workflows/test.yml
pyproject.toml
test-requirements.in
test-requirements.txt

https://setuptools.pypa.io/en/stable/history.html#v75-1-0
Since setuptools `70.1` the `bdist_wheel` command is shipped with setuptools directly. It's no longer necessary to specify `wheel` as a build system requirement.

Update setuptools to 75.1.0

---

mypy/util.py

This is a pretty small win, it's below the noise floor on macrobenchmark, but if you time the hashing specifically it saves about 100ms (0.5%) on `python -m mypy -c 'import torch' --no-incremental`. blake2b is slower

Use sha1 for hashing

---

mypy/modulefinder.py
mypy/util.py

See https://github.com/python/mypy/issues/17948
There's one call site which has varargs that I leave as os.path.join, it doesn't show up on my profile. I do see the `endswith` on the profile, we could try `path[-1] == '/'` instead (could save a few dozen milliseconds)
In my work environment, this is about a 10% speedup:
```
λ hyperfine -w 1 -M 3 '/tmp/mypy_primer/timer_mypy_6eddd3ab1/venv/bin/mypy  -c "import torch" --no-incremental --python-executable /opt/oai/bin/python'
Benchmark 1: /tmp/mypy_primer/timer_mypy_6eddd3ab1/venv/bin/mypy  -c "import torch" --no-incremental --python-executable /opt/oai/bin/python
Time (mean ± σ):     30.842 s ±  0.119 s    [User: 26.383 s, System: 4.396 s]
Range (min … max):   30.706 s … 30.927 s    3 runs
```
Compared to:
```
λ hyperfine -w 1 -M 3 …
```

Let mypyc optimise os.path.join

---

mypy/build.py
mypy/modulefinder.py

See https://github.com/python/mypy/issues/17948
This is about 1.06x faster on `mypy -c 'import torch'` (in both the clean and openai environments)
- 19.094 -> 17.896 
- 34.161 -> 32.214
```
λ hyperfine -w 1 -M 3 '/tmp/mypy_primer/timer_mypy_36738b392/venv/bin/mypy  -c "import torch" --no-incremental --python-executable clean/bin/python'
Benchmark 1: /tmp/mypy_primer/timer_mypy_36738b392/venv/bin/mypy  -c "import torch" --no-incremental --python-executable clean/bin/python
Time (mean ± σ):     17.896 s ±  0.130 s    [User: 16.472 s, System: 1.408 s]
Range (min … max):   17.757 s … 18.014 s    3 runs
λ hyperfine -w 1 -M 3 '/tmp/mypy_primer/timer_mypy_36738b392/venv/bin/mypy  -c "import torch" --no-incremental --python-executable /opt/oai/bin/python' 
Benchmark 1: …
```

Use fast path in modulefinder more often

---

mypy/meet.py

Since mypyc will treat these as list comprehensions

Fix generator comprehension in meet.py

---

mypyc/lib-rt/getargs.c

`_PyDict_GetItemStringWithError ` was deprecated for Python 3.14 in https://github.com/python/cpython/pull/119855.
Use `PyDict_GetItemStringRef` instead. It was added in 3.13 but is available via `pythoncapi_compat.h`.
https://docs.python.org/3/c-api/dict.html#c.PyDict_GetItemStringRef

[mypyc] Replace deprecated _PyDict_GetItemStringWithError

---

misc/apply-cache-diff.py
misc/diff-cache.py
mypy/build.py
mypy/metastore.py
mypy/util.py
mypyc/codegen/emitmodule.py

For `mypy -c 'import torch'`, the cache load time goes from 0.44s to 0.25s as measured by manager's data_json_load_time. If I time dump times specifically, I see a saving of 0.65s to 0.07s. Overall, a pretty reasonable perf win -- should we make it a required dependency?
I don't know if the sqlite cache path is used at all (what's the status?), but let me know if I need a cleverer migration than renaming the table
See also https://github.com/python/mypy/issues/3456

Use orjson instead of json, when available

---

mypy/metastore.py

Tested via:
```
set -x
rm -rf .mypy_cache
time python -m mypy --config-file mypy_self_check.ini -p mypy
python misc/convert-cache.py --to-sqlite .mypy_cache/3.8
time python -m mypy --config-file mypy_self_check.ini -p mypy --sqlite-cache
time python -m mypy --config-file mypy_self_check.ini -p mypy --sqlite-cache
```

Fix cache-convert

---

mypy/build.py
mypy/modulefinder.py
mypy/stubinfo.py
mypy/test/teststubinfo.py

See https://github.com/python/mypy/issues/17948
This is starting to show up on profiles
- 1.01x faster on clean (below noise)
- 1.02x faster on long
- 1.02x faster on openai
- 1.01x faster on openai incremental
I had a dumb bug that was preventing the optimisation for a while, I'll see if I can make it even faster. Currently it's a small improvement
We could also get rid of the legacy stuff in mypy 2.0

Speed up stubs suggestions

---

mypy/build.py
mypy/modulefinder.py
mypy/util.py

See #17948
- 1.01x faster on clean
- 1.06x faster on long
- 1.04x faster on openai
- 1.26x faster on openai incremental

Make is_sub_path faster

---

mypy/dmypy_util.py
mypy/gclogger.py
mypy/server/update.py
mypy/types.py
mypyc/codegen/emitclass.py

* (refactor): Update using of dicts literal across several modules
___
Minor code style refactoring. Does not affect behavior.

Refactor: Minor refactoring of dict literal usage

---

test-data/unit/check-flags.test
test-data/unit/cmdline.test
test-data/unit/parse-errors.test

Relates #5966.
Below is the info what happened with the concrete test from `cmdline.test`:
1. `testErrorContextConfig` => check-flags.test (`testShowErrorContextFunction`) [duplicate]
2. `testNoConfigFile` => check-flags.test (`testNoConfigFile`) [move]
3. `testPerFileConfigSection` => check-flags.test (`testPerFileUntypedDefs`) [move]
4. `testIgnoreErrorsConfig` => check-flags.test (`testPerFileIgnoreErrors`) [move]
5. `testConfigFollowImportsNormal` => check-flags.test (`testFollowImportsNormal`) [move + modified]
6. `testConfigFollowImportsSilent` => check-flags (`testFollowImportsSilent`) [move + modified]
7. `testConfigFollowImportsSkip` => check-flags (`testFollowImportsSkip`) [move + modified]
8. `testConfigFollowImportsError` => check-flags.test (`testFollowImportsError`) [move + …

Move some tests from cmdline.test (#5966 )

---

mypy/checkexpr.py
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/17945

Fix iteration over union (when self type is involved)

---

mypy/constraints.py
test-data/unit/check-typeguard.test
test-data/unit/check-typeis.test

fix: TypeGuard becomes bool instead of Any when passed as TypeVar (fixes #17117)

---

test-data/unit/pythoneval.test

Each test has some non-trivial constant overhead, so merging tests will speed them up. Merge a few tests.
The merged tests are old and unlikely to fail (but still marginally useful), so it isn't important if test failures are now a bit more difficult to investigate.

Merge some pythoneval tests to speed them up

---

mypy/checkexpr.py
test-data/unit/check-typevar-defaults.test

Union type context wasn't handled previously, and it triggered false positives, but apparently only if a type object had type var defaults.
Fixes #17942.

Fix type object with type var default in union context

---

mypyc/__main__.py
mypyc/build.py
mypyc/irbuild/classdef.py
mypyc/irbuild/function.py
mypyc/irbuild/ll_builder.py
mypyc/irbuild/mapper.py
mypyc/irbuild/prepare.py
mypyc/options.py
mypyc/test-data/run-dunders-special.test
mypyc/test-data/run-dunders.test
mypyc/test/test_run.py

This change gives mypyc the ability to optionally optimize dunder methods that can guarantee strict adherence to its signature typing. The optimization allows to bypass vtable for dunder methods in certain cases that are applicable.
Currently, mypy has adopted the convention of accept dunder methods that return `NotImplemented` value even when its signature do not reflect this possibility. With this change and by enabling an special flag, mypyc will expect strict typing be honored and will unleash more optimizations like native call without vtable lookup for some cases on dunder method calls.
For example it could avoid calls to RichCompare Python API making the code can be fully optimized in by the C compiler when some comparison with dunders are required.
Example:
```python
@final
class …
```

[mypyc] Optimize dunder methods

---

mypy/checker.py
mypy/fastparse.py
mypy/message_registry.py
mypy/nodes.py
mypy/semanal.py
mypy/strconv.py
mypy/test/testparse.py
test-data/unit/check-python313.test
test-data/unit/check-typevar-defaults.test
test-data/unit/parse-python313.test

Add initial support for TypeVar defaults using the new syntax. Similar to the old syntax, it doesn't fully work yet for ParamSpec, TypeVarTuple and recursive TypeVar defaults.
Refs: #14851

Add initial support for new style TypeVar defaults (PEP 696)

---

mypy/version.py

I'll be making a 1.13 (that's cut from the 1.12 branch), so we should bump the version on master as well

Bump version to 1.14.0+dev

---

mypyc/irbuild/statement.py

Fixes https://github.com/mypyc/mypyc/issues/1070
Missed in https://github.com/python/mypy/pull/10543

[mypyc] fix relative imports in __init__.py

---

mypyc/namegen.py
mypyc/test/test_namegen.py

Fixes https://github.com/mypyc/mypyc/issues/1071
Adds a test to cover this case
Building certain package layouts now succeeds instead of failing. The behavior for all package layouts not affected by the error is unchanged.
In `namegen.make_module_translation_map(names)`, if argument `names` have `"foo"` and `"foo.foo"`, all suffixes found for `"foo"` are also found for `"foo.foo"`. This means that module `foo` has no unique suffixes, which currently causes an `AssertionError`.
The fix forces a module to take the last, fullest suffix if none are unique. It is guaranteed that no other module will also take the same suffix because they either will have a unique suffix to take, or they will take the fullest suffix for their name which is always going to be different.
P.S. 'suffix' or …

[mypyc] fix name generation for modules with similar full names

---

.github/workflows/docs.yml
.github/workflows/mypy_primer.yml
.github/workflows/sync_typeshed.yml
.github/workflows/test.yml
.github/workflows/test_stubgenc.yml

Prevent blocking resources unnecessarily if something goes wrong and a CI task doesn't terminate. The default timeout would be 360 minutes.

Add timeout-minutes to ci config

---

mypy/checker.py
test-data/unit/check-functions.test
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test

Fixes #17211, resolves this `# TODO`:
https://github.com/python/mypy/blob/e106dd7a0653c24d67597adf3ae6939d7ff9a376/test-data/unit/check-functions.test#L1486-L1494
```python
from typing import Callable
def dec(f: object) -> Callable[[int], None]: raise NotImplementedError
if int():
def f(x: str) -> None: pass
else:
@dec
def f() -> None: pass  # uh oh! passes without error
```
```python
from typing import Callable
def dec(f: object) -> Callable[[int], None]: raise NotImplementedError
if int():
def f(x: str) -> None: pass
else:
@dec
def f() -> None: pass  # E: All conditional function variants must have identical signatures \
```

Fix compatibility checks for conditional function definitions using decorators

---

mypy/checker.py
mypy/nodes.py
mypy/semanal.py
test-data/unit/check-inference.test
test-data/unit/fixtures/for.pyi

Preserve the literal type of index expressions a bit longer (until the next assignment) to support TypedDict lookups.
```py
from typing import TypedDict
class X(TypedDict):
hourly: int
daily: int
def func(x: X) -> None:
for var in ("hourly", "daily"):
print(x[var])
```
Closes #9230

Improve for loop index variable type narrowing

---

mypy/stubtest.py
mypy/test/teststubtest.py

Previously it wasn't an error if runtime included an
`__all__` declaration, but the stubs did not. This PR
changes this to reflect the consensus that it would
be a good idea to ensure consistency in this case.
Fixes #13300

[stubtest] Verify __all__ exists in stub

---

mypy/checkexpr.py
test-data/unit/check-literal.test

Fixes https://github.com/python/mypy/issues/18021
When I switched to (almost) always using unions as inferred from ternary expressions, I had a choice, because before we used either full context (i.e. l.h.s.) or the if type to infer the else type. After some playing I found the second one usually works better. But as we see this is not always the case, so I add some special-casing.

Fix ternary union for literals

---

docs/source/type_narrowing.rst

[Here](https://mypy.readthedocs.io/en/stable/type_narrowing.html#typeis), the markup is broken:
After applying the changes:

[docs] fix broken markup in `type_narrowing.rst`

---

mypy/stubtest.py

Mypy's error handling suggests using -`-show-traceback` and `--pdb` for more information, and this can occur while running stubtest. This MR adds support for both flags to stubtest so that the suggestions can be followed without needing to figure out the equivalent mypy invocation first.

allow the use of --show-traceback and --pdb with stubtest

---

mypy/checkexpr.py
test-data/unit/check-parameter-specification.test

Closes #18027.
Var-args and star-args overloads are handled first to handle functions like `zip` correctly in cases like `zip(*[[1],[2],[3]])`. That does not seem to be necessary in case of `ParamSpec` overloads (or at least such use case is much less obvious).
So this PR prevents `ParamSpec` overloads from floating up in the list of overload targets.

Do not prioritize ParamSpec signatures during overload resolution

---

mypy/meet.py
test-data/unit/check-selftype.test

ParamSpec types can match arbitrary parameter types, so treat them as having 'object' as the upper bound.
This also fixes issues with filtering of overload items based on self type.
Fixes #18036.

Fix overlap check for ParamSpec types

---

mypy/checker.py

Split a big function to make it easier to modify and understand.

Refactor "==" and "is" type narrowing logic

---

mypy/modulefinder.py
mypy/test/testmodulefinder.py
test-data/unit/check-modules.test

With a long sys.path (it's got 300 entries), this removes 94% of stat syscalls from running mypy. With all the filesystem caching, that's only a small time savings, though it will depend on your filesystem. Local benchmarks showed a 20% time savings but they're pretty noisy from all the I/O.

Filter to possible package paths before trying to resolve a module.

---

mypy/main.py
test-data/unit/check-flags.test

The `--follow-imports=skip` CLI option is pretty much unusable in a project where `disallow_any_unimported` is set to true in the configuration file, as this results in a large number of errors (due to both flags being incompatible). We have a pretty standard project configuration file (with `disallow_any_unimported = true` and `follow_imports = 'normal'`), but for specific local development cases where we want to run the mypy CLI with `--follow-imports=skip` it's incredibly noisy due to the number of errors produced.
This change proposes making the `disallow-any-unimported` invertible, so that the CLI can be used with `--follow-imports=skip` in a less noisy way by using:
```bash
mypy --follow-imports=skip --allow-any-unimported path/to/my/file.py
```

Make `disallow-any-unimported` flag invertible

---

mypy/checkstrformat.py
mypy/inspections.py
mypy/main.py
mypy/message_registry.py
mypy/messages.py
mypy/modulefinder.py
mypy/plugins/dataclasses.py
mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/typeanal.py

We have some strings which use implicit concatenation unnecessarily (where the whole string can fit on a single line without implicit concatenation). This PR removes them.
For some of the changed lines here, I also did some driveby modernisations to use f-strings, since I was touching those lines anyway.

Remove unnecessary concatenated strings

---

mypy/traverser.py
mypy/typeanal.py
mypy/typevartuples.py
mypyc/analysis/dataflow.py
mypyc/codegen/emitmodule.py
mypyc/irbuild/function.py

This PR just removes some functions that are unused (from what I can tell).

Remove some unused functions.

---

mypy/build.py
mypy/modulefinder.py
mypy/strconv.py
mypy/stubinfo.py
mypy/test/testmodulefinder.py
mypy/test/teststubinfo.py
test-data/unit/check-modules.test

Follow up to https://github.com/python/mypy/pull/18038
This maybe should have been two PRs

Fix approved stub ignore, remove normpath

---

docs/source/dynamic_typing.rst

This change fixes what appears to be a minor copy-paste typo in the docs.

Correct note about `--disallow-any-generics` flag in docs

---

mypy/checker.py
test-data/unit/check-classes.test

Fixes #18052
Given:
```python
from typing import Callable
class Parent:
func: Callable[[str], None]
class Child(Parent):
def func(self, x: object) -> None: pass 
```
Before:
```
Success: no issues found in 1 source file
```
After:
```
main.py:7 error: Covariant override of a mutable attribute (base class "Parent" defined the type as "Callable[[str], None]", override has type "Callable[[object], None]")
```

Emit `[mutable-override]` for covariant override of attribute with method

---

mypy/stubgen.py

This is already supported by main `mypy` binary and `dmypy` but not by `stubgen`.
I maintain https://github.com/KapJI/homeassistant-stubs which automatically generates typing stubs. Currently list of arguments there is 50 KB long and this can be longer that supported by OS (depending on configuration). It'd help to write these args to flagfile.

stubgen: Add flagfile support

---

mypy/types.py
test-data/unit/check-tuples.test

Fixes #18062
I plan to follow up with another PR that adds a better error messages for  slice expressions with `step=0` when indexing standard containers that disallow that.

Fix crash when checking slice expression with step 0 in tuple index

---

CHANGELOG.md
mypy/checker.py
mypy/checkmember.py
mypy/nodes.py
mypy/semanal_enum.py
mypy/test/teststubtest.py
mypy/typeops.py
mypy/types.py
mypyc/irbuild/classdef.py
test-data/unit/check-enum.test

Follow up to https://github.com/python/mypy/pull/17207

Issue warning for enum with no members in stub

---

mypy/config_parser.py
mypy/options.py
mypy/plugin.py
mypyc/irbuild/builder.py

This has been very dead for years, no plugin I can tell is using it

Clean up new_semantic_analyzer config

---

mypy_bootstrap.ini

We almost had all strict flags set anyway, so many it will just work.
If not, it would be easier to turn something off.

Use `strict = True` for `mypy_bootstrap.ini`

---

mypy/build.py
mypy/modulefinder.py

Check that errno is not None

---

mypy/stubgen.py
mypy/stubgenc.py
mypy/stubutil.py
mypy/test/teststubgen.py

This fixes an issue with the computation of `FunctionContext.fullname` for nested classes.  
For a module named `spangle`, with the following classes:
```python
class Foo:
class Bar:
pass
```
The previous output for the class `Bar` was `"spangle.Bar"` and with this fix it is now `"spangle.Foo.Bar"`.

stubgen:  fix FunctionContext.fullname for nested classes

---

mypy/subtypes.py
test-data/unit/check-protocols.test

Fix subtyping between Instance and Overloaded

---

docs/source/config_file.rst

Changes:
- Fix `strict_equality` markup. It used to be like this:
- Mark `strict_concatenate` as deprecated
- Add `extra_checks` confval

Update `config_file` docs

---

mypy/build.py
mypy/dmypy_server.py
mypy/metastore.py
mypy/server/update.py
mypy/util.py
test-data/unit/daemon.test

Fixes https://github.com/python/mypy/issues/18019
Fixes https://github.com/python/mypy/issues/17775
These two are essentially variations of the same thing. Instead of adding e.g. `types` to `SENSITIVE_INTERNAL_MODULES` (which would be fragile and re-introduce same crashes whenever we add a new "core" module) I add _all stdlib modules_. The only scenario when stdlib changes is when a version of mypy changes, and in this case the daemon will be (or should be) restarted anyway.
While adding tests for these I noticed a discrepancy in `--follow-imports=normal` in the daemon: the files explicitly added on the command line should be always treated as changed, since otherwise we will not detect errors if a file was removed from command line in an intermediate run.
Finally the tests also …

Fix couple crashes in dmypy

---

CONTRIBUTING.md

Fixes #18096
Update of CONTRIBUTING.md document to be able to run tests using Windows OS.
```bash
python3 runtests.py
```
Change to:
```bash
python runtests.py
```
```bash
python3 runtests.py self
python3 -m mypy --config-file mypy_self_check.ini -p mypy
```
Change to:
```bash
python runtests.py self
python -m mypy --config-file mypy_self_check.ini -p mypy
```
described above to install `tox` via `pip` (e.g., ``python3 -m pip install tox``).
Change to:
described above to install `tox` via `pip` (e.g., ``python -m pip install tox``).

Update for Windows platform. Resolves #18096

---

mypy/checker.py
test-data/unit/check-dataclasses.test

Refs #18115
When a parameter type in a method override is incompatible with the parameter type in the supertype definition, mypy emits an error using the `Argument` node as the context. 
However, sometimes the the `Argument` node doesn't have a line number set, causing the error message to have no associated line number. This happens with the  `__replace__` methods created in the dataclass plugin, which have line numbers set on the `FuncDef` nodes, but no line numbers set on the individual argument nodes. 
This PR fixes the missing line number in the error by falling-back to the FuncDef line number when a line number isn't set on the `Argument` node. 
(As an alternative fix, we could add line numbers to the `Argument` nodes in the dataclass plugin, but that looks like a more complicated …

Fix [override] error with no line number when argument node has no line number

---

mypy/checkpattern.py
test-data/unit/check-python310.test

Fixes #18140
```python
from typing import reveal_type
class A(str):
pass
class B(str):
__match_args__ = ("b",)
@property
def b(self) -> int: return 1
match A("a"):
case A(a):
reveal_type(a)  # before: Revealed type is "__main__.A"
print(type(a))  # output: <class '__main__.A'>
match B("b"):
case B(b):
reveal_type(b)  # before: Revealed type is "__main__.B"
print(type(b))  # output: <class 'int'>
```

Fix type inference of positional parameter in class pattern involving builtin subtype

---

mypy/checkpattern.py
test-data/unit/check-python310.test

Fixes #18108
This PR fixes the issue of missing value comparisons in a `MatchStmt` due to `OrPattern` incorrectly narrowing down the type of the subject.

Fix `OR` pattern structural matching exhaustiveness

---

mypy/test/data.py
mypy/test/testfinegrained.py

I often encounter test failures on Windows (failing tests are always related to `mypy` daemon). 
https://github.com/python/mypy/actions/runs/11783610549/job/32821129579
https://github.com/python/mypy/actions/runs/11767558564/job/32776369396
https://github.com/python/mypy/actions/runs/11763771676/job/32768172783
They always manifest as a `RecursionError` during test teardown, the following two frames are repeated many times:
```
___________ ERROR at teardown of testDaemonRunIgnoreMissingImports ____________
[gw3] win32 -- Python 3.8.10 D:\a\mypy\mypy\.tox\py38\Scripts\python.EXE
path = 'C:\Users\RUNNER~1\AppData\Local\Temp\mypy-test-6t6j6e1l\tmp'
onerror = <function TemporaryDirectory._rmtree.<locals>.onerror at 0x00000250EE0F94C0>
def _rmtree_unsafe(path, onerror):
try:
with …
```

[ci] Try to fix Windows CI failures

---

.pre-commit-config.yaml
test-data/unit/README.md
test-requirements.in
test-requirements.txt

#15210 standardized lint hooks invocations with pre-commit, but did not remove test requirements that became unneeded. Grepping for `ruff` and `black` revealed that they are never used directly any longer except for one outdated README notice.
Remove direct dependency on `black` and `ruff`, retaining them only in pre-commit configuration. pre-commit does not use local package installations and manages all virtual environments internally.

[chore] Remove black and ruff from test-requirements

---

mypy/util.py

Fixes the error below:
```python
File "mypy/main.py", line 102, in main
File "mypy/main.py", line 186, in run_build
File "mypy/build.py", line 194, in build
File "mypy/build.py", line 269, in _build
File "mypy/build.py", line 2935, in dispatch
File "mypy/build.py", line 3333, in process_graph
File "mypy/build.py", line 3460, in process_stale_scc
File "mypy/build.py", line 2497, in write_cache
File "mypy/build.py", line 1560, in write_cache
File "mypy/util.py", line 924, in json_dumps
TypeError: Integer exceeds 64-bit range
```
Related: https://github.com/ijl/orjson/issues/116

Fallback to stdlib json if integer exceeds 64-bit range

---

pyproject.toml
setup.py

Setuptools supports using `setup.py` and `pyproject.toml` simultaneously. This PR moves most of the static project metadata to `pyproject.toml`.
Diff for **`.dist-info/METADATA`**
```diff
Metadata-Version: 2.1
Name: mypy
Version: 1.14.0+dev
Summary: Optional static typing for Python
-Home-page: https://www.mypy-lang.org/
+Author-email: Jukka Lehtosalo <jukka.lehtosalo@iki.fi>
-Author: Jukka Lehtosalo
-Author-email: jukka.lehtosalo@iki.fi
License: MIT
+Project-URL: Homepage, https://www.mypy-lang.org/
Project-URL: Documentation, https://mypy.readthedocs.io/en/stable/index.html
...
```
**`dist-info/RECORD`** is the same (except for the changed hash for `.dist-info/METADATA`).
https://packaging.python.org/en/latest/specifications/core-metadata/

Move static project metadata to pyproject.toml

---

mypy/nodes.py
mypy/test/teststubgen.py
mypyc/lib-rt/setup.py
mypyc/test/test_emitfunc.py
pyproject.toml

The vast majority of mypy's code follows PEP 8 naming conventions. However, we currently don't enforce this in the linter config. I noticed this in a recent PR which included a `camelCase` name: https://github.com/python/mypy/pull/18132#discussion_r1836870819.
Ruff has some rules to enforce PEP 8 naming style ([pep8-naming](https://docs.astral.sh/ruff/rules/#pep8-naming-n)). I think it would be a good idea to enable some of these to help contributors catch naming discrepancies before PR review.
We have a few notable exceptions to PEP 8 naming (e.g. functions named to match ast node names), but these are easily accounted for with some config file ignores and handful of `# noqa`'s.

ruff: enable pep8-naming rules

---

mypy/checkpattern.py
test-data/unit/check-python310.test

Fixes #18089
Adds handling for bounded type variables when checking match sequence patterns. 
Previously, this crashed. Now, this correctly narrows the upper bound of the type variable:
```python
from typing import TypeVar, Sequence
T = TypeVar("T", bound=Sequence[int | str])
def accept_seq_int(x: Sequence[int]): pass
def f(x: T) -> None:
match x:
case [1, 2]:
accept_seq_int(x)  # ok: upper bound narrowed to Sequence[int]
case _:
accept_seq_int(x)  # E: Argument 1 to "accept_seq_int" has incompatible type "T"; expected "Sequence[int]"
```

Fix checking of match sequence pattern against bounded type variables

---

mypyc/irbuild/function.py
mypyc/test-data/run-classes.test

Fixes [#1075](https://github.com/mypyc/mypyc/issues/1075)
Previously, this compiled but failed to run:
```python
import collections
from typing_extensions import TypedDict
class C(TypedDict):
x: collections.deque
```
Although type of `x` was being inferred correctly, it was not looking for `collections.deque` in imported modules.

[mypyc] Loading type from imported modules.

---

mypy/checkexpr.py
test-data/unit/check-expressions.test

Fixes  #18149
Slices were made generic in https://github.com/python/typeshed/pull/11637. Currently, all slice expressions are inferred to have type `slice[Any, Any, Any]`. This PR fills in the generic type arguments more appropriately using start/stop/stride expression types.
Given
```python
class Foo:
def __getitem__[T](self, item: T) -> T: return item
x = Foo()
reveal_type(x[1:])
```
Before:
```none
main.py:5: note: Revealed type is "builtins.slice[Any, Any, Any]"
```
After:
```none
main.py:5: note: Revealed type is "builtins.slice[builtins.int, None, None]"
```

Infer generic type arguments for slice expressions

---

mypy/typeanal.py
test-data/unit/check-typeddict.test

This is allowed per the [typing spec](https://typing.readthedocs.io/en/latest/spec/typeddict.html#interaction-with-other-special-types).
Updates the TypeAnalyzer to remember whether TypedDict special forms are allowed when visiting `Annotated` types.

Allow nesting of Annotated with TypedDict special forms inside TypedDicts

---

mypy/subtypes.py
test-data/unit/check-typeddict.test

Allow TypedDict assignment of Required item to NotRequired ReadOnly item

---

mypy/checker.py
test-data/unit/check-narrowing.test

Closes #18135
This change implements the third approach mentioned in #18135, which is stricter than similar narrowings, as clarified by the new/modified code comments. Personally, I prefer this more stringent way but could also switch this PR to approach two if there is consent that convenience is more important than type safety here.

Support `==`-based narrowing of Optional

---

mypy/typeanal.py
test-data/unit/check-parameter-specification.test

Emit errors for both of the following aliases:
```python
P = ParamSpec("P")
Bad1: TypeAlias = P
Bad2: TypeAlias = Concatenate[int, P]
```
This is done by swapping a top-level call to `type.accept(analyzer)` with `analyzer.anal_type(type)`, the latter of which simply calls the former and then performs some checks.

Disallow bare `ParamSpec` in type aliases

---

mypy/semanal.py
test-data/unit/pythoneval.test

This enables typeshed to define types.DynamicClassAttribute as a different class from builtins.property without breakage.
Would enable https://github.com/python/typeshed/pull/12762
see also https://github.com/python/mypy/pull/14133
Let me know if a test case is desired for this.

special case types.DynamicClassAttribute as property-like

---

mypy/typeanal.py
test-data/unit/check-typevar-defaults.test

Fixes #18188 
Currently it seems that `None` is dropped from type variable defaults when assigning generic class to a type alias.
<details>
<summary>Example</summary>
```python
from typing_extensions import TypeVar
from typing import Generic, Union
T1 = TypeVar("T1", default=Union[int, None])
T2 = TypeVar("T2", default=Union[int, None])
class A(Generic[T1, T2]):
def __init__(self, a: T1, b: T2) -> None:
self.a = a
self.b = b
MyA = A[T1, int]
a: MyA = A(None, 10)  # error: Argument 1 to "A" has incompatible type "None"; expected "int"  [arg-type]
reveal_type(a.a)
```
</details>
The change is similar to https://github.com/python/mypy/pull/16859

Preserve typevar default None in type alias

---

mypyc/irbuild/classdef.py
mypyc/test-data/run-classes.test

Fixes [mypyc/mypyc#1065](https://github.com/mypyc/mypyc/issues/1065)
Fixes [mypyc/mypyc#1059](https://github.com/mypyc/mypyc/issues/1059)
Fixes [mypyc/mypyc#1022](https://github.com/mypyc/mypyc/issues/1022)
* Checking for enum classes using `is_enum` flag instead of `fullname` of base class. That way, mypyc recognizes classes derived from `IntEnum` as enum classes too.
* After fixing the above bug, test failures revealed that mypyc was sending all MRO classes to `__prepare__` function. For example, for the `Player` test class added in this PR, mypyc was generating C code to call `__prepare__` of the base class with `(IntEnum, int, Enum)` instead of just `(IntEnum,)`. This bug has been fixed in `classdef.py:populate_non_ext_bases`.

[mypyc] Fixing check for enum classes.

---

mypyc/irbuild/for_helpers.py
mypyc/test-data/irbuild-statements.test
mypyc/test-data/run-loops.test

Fixes [mypyc/mypyc#1046](https://github.com/mypyc/mypyc/issues/1046)
This change fixes two problems:
1. The index variable was getting instantiated even while enumerating an empty iterable.
2. After exiting the for-loop, the value of the index variable is off by 1 (see issue linked above).
This change fixes both problems by assigning the temporary register to the index variable at the beginning of the for-loop body. Before this change, this assignment was happening before the for-loop and at the end of the for-loop body.

[mypyc] Fixing index variable in for-loop with builtins.enumerate.

---

mypyc/codegen/literals.py
mypyc/lib-rt/misc_ops.c
mypyc/test-data/run-strings.test

Previously surrogates would trigger a compiler crash.

[mypyc] Support unicode surrogates in string literals

---

mypy/checkexpr.py
mypy/types.py

`mypy.checkexpr.HasTypeVarQuery` has only one usage and is virtually[^1] identical to `mypy.types.HasTypeVars`.  Merging them seems sensible. The latter has wider usage via `has_type_vars`, so it seems like the better one to keep.
Some history for the record:
* `mypy.checkexpr.HasTypeVarQuery` was added in 12 years ago a40efb48f0a40a5a4a6038960909ddec98965beb
* `mypy.types.HasTypeVars` was added 5 years ago in 59617e8f895ca12a6fb0ec46f378ce384a757118
[^1]: the only difference is that `HasTypeVars` sets `self.skip_alias_target = True`, but this seem to fit the usage of `HasTypeVarQuery` just as well.

Refactor: merge duplicate HasTypeVars query visitors

---

mypy/message_registry.py
mypy/semanal.py
mypy/typeanal.py
test-data/unit/check-python312.test
test-data/unit/semanal-errors.test

Emit an error for [this test case](https://github.com/python/typing/blob/46b05a4c10ed3841c9bc5126ba9f31dd8ae061e7/conformance/tests/generics_basic.py#L54-L55) from the conformance tests:
```python
class Test(Generic[T]):
BadConstraint2 = TypeVar("BadConstraint2", str, list[T])  # E
```

Disallow `TypeVar` constraints parameterized by type variables

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

At runtime, non init fields are not allowed when using replace. See [the source code](https://github.com/python/cpython/blob/1bc4f076d193ad157bdc69a1d62685a15f95113f/Lib/dataclasses.py#L1671-L1676) of the CPython implementation.

Do not include non-init fields in the synthesized `__replace__` method for dataclasses

---

mypy/nodes.py
mypy/treetransform.py
test-data/unit/check-unreachable-code.test

Fixes #18210
When checking function definitions with constrained type variables (i.e. type variables with value restrictions), mypy expands the function definition for each possible type variable value. However, blocks in the expanded function definitions have their `is_unreachable` reset to `False`, which leads to spurious errors in blocks that were marked as unreachable during semantic analysis.
This PR preserves the value of `is_unreachable` on blocks in the expanded function definitions.

Preserve block unreachablility when checking function definitions with constrained TypeVars

---

mypy/join.py
mypy/meet.py
mypy/test/testtypes.py

Fixes #18199 
Updated `join.py`  to return `AnyType(TypeOfAny.special_form)` for both `UnboundType` and `AnyType`.
Updated `meet.py` to return `UninhabitedType()` when visiting a `UnboundType` as a `NoneType` when `state.strict_optional` is true.

Join meet symmetric

---

mypyc/irbuild/expression.py
mypyc/test-data/run-classes.test

Fixes mypyc/mypyc#1076
This change has been copied from [mypyc/irbuild/builder.py#1084](https://github.com/advait-dixit/mypy/blob/1a9596453bf6377b8fee822cf0bf74350993ec28/mypyc/irbuild/builder.py#L1084).

[mypyc] Fixing condition to fall back to PyCall for staticmethod and classmethod

---

docs/source/command_line.rst
docs/source/error_code_list2.rst
mypy/checker.py
mypy/errorcodes.py
mypy/errors.py
mypy/main.py
mypy/options.py
mypy/typeanal.py
test-data/unit/check-deprecated.test
test-data/unit/fine-grained.test

While working on the relase of mypy 1.14 we noticed a large number of notes for deprecated. Speaking with Jukka, he suggested we make this disabled by default. And if it's disabled by default, having it as a note is not as useful. We also don't have many stand alone notes. Most notes are "attached" with an error.
This PR makes the deprecated error disabled by default, removes the flag to report it as error and always reports it as error when enabled.
CC @tyralla

Make "deprecated" Note a standard Error, disabled by default

---

mypyc/doc/bytes_operations.rst
mypyc/doc/index.rst
mypyc/doc/str_operations.rst

The docs were somewhat out of date.

[mypyc] Document optimized bytes ops and additional str ops

---

mypyc/irbuild/builder.py
mypyc/irbuild/ll_builder.py

Having the documentation in class docstrings makes it easier to find.

[mypyc] Update docstrings of IR builder classes

---

MANIFEST.in

mypyc is fully typed, so it'd be nice to get rid of mypy errors to do with missing `py.typed` markers when writing `setup.py`s or similar.
```python
import mypyc  # E: Skipping analyzing "mypyc": module is installed, but missing library stubs or py. typed marker  [import-untyped]
```

fix: mark mypyc package with `py.typed`

---

mypyc/irbuild/builder.py
mypyc/test-data/run-loops.test

Fixes mypyc/mypyc#1063.
Adding elif-blocks for getting RType of items in classes derived from `NamedTuple`.

[mypyc] Fixing iteration over NamedTuple objects.

---

mypy/checkexpr.py
test-data/unit/check-flags.test

Previously comparing a bytearray against a bytes literal was reported as a non-overlapping comparison when using `--strict-equality`. This was a false positive.
This is in preparation for disabling bytearray to bytes promotion by default in mypy 2.0.

Allow bytearray/bytes comparisons with --disable-bytearray-promotion

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/main.py
mypy/options.py
test-data/unit/check-flags.test

Add `--strict-bytes` flag

---

mypy/typeanal.py
mypy/types_utils.py
test-data/unit/check-literal.test
test-data/unit/check-recursive-types.test

Closes https://github.com/python/mypy/issues/18196

Do not allow `type[]` to contain `Literal` types

---

mypy/checker.py
mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/semanal_shared.py
mypy/semanal_typeddict.py
mypy/typeanal.py
test-data/unit/check-namedtuple.test
test-data/unit/check-typeddict.test
test-data/unit/fixtures/typing-namedtuple.pyi
test-data/unit/fixtures/typing-typeddict.pyi

Do not allow `ClassVar` and `Final` in `TypedDict` and `NamedTuple`

---

misc/perf_compare.py

With a random hash seed the measurements can vary a lot even for different builds based on the same commit. Some builds were consistently faster/slower than others, even though there were no code changes. This makes the measurements more predictable.
It looks like mypyc output has some randomness, though I haven't looked into the root cause in detail.

Use a fixed hash seed in perf_compare script

---

misc/perf_compare.py

Use `--incremental` to measure incremental instead of full self checks. The warmup runs are used to populate incremental caches.

Support measuring incremental runs in perf_compare script

---

misc/perf_compare.py

Running too many parallel builds risks running out of memory, especially on systems with 16 GB or less RAM.
By default run 8 builds, which may already be too many for smaller systems, but `-j N` can be used to lower the number of parallel builds.
Also rename `-n` to `--num-runs` to avoid ambiguity, since `-n` is used by pytest to set parallelism.

Limit build parallelism in perf_compare script

---

mypy/semanal_typeargs.py
test-data/unit/check-classes.test
test-data/unit/check-columns.test
test-data/unit/check-generics.test
test-data/unit/check-newsemanal.test

Fixes #12274
Uses the actual invalid type argument as the error context when possible.
Given:
```python
class Foo[S, T: int]: 
pass
x: Foo[str, str]
```
Before:
```
main.py:3:4: error: Type argument "str" of "Foo" must be a subtype of "int"  [type-var]
x: Foo[str, str]
^
```
After:
```
main.py:3:13: error: Type argument "str" of "Foo" must be a subtype of "int"  [type-var]
x: Foo[str, str]
^
```

Use more precise context for invalid type argument errors

---

misc/perf_compare.py

Previously the tool only supported measuring self-check performance. Now a code fragment can be passed using `-c "..."`.
A typical use case would be something like `perf_compare.py -c "import torch" ...`, to measure the speed of processing `torch`.

Enable type checking code fragment using perf_compare tool

---

mypy/plugins/default.py
test-data/unit/check-columns.test
test-data/unit/check-literal.test
test-data/unit/check-typeddict.test

Fixes #12271
Uses an applicable argument expression as the error context instead of the overall CallExpr.
**Given:**
```python
from typing import TypedDict
class A(TypedDict):
x: int
a: A
x.setdefault("y", 123)
x.setdefault("x", "bad")
b: dict[str, int]
b.setdefault("x", "bad")
```
**Before:**
```
main.py:8:1: error: TypedDict "A" has no key "y"  [typeddict-item]
a.setdefault("y", 123)
^~~~~~~~~~~~~~~~~~~~~~
main.py:9:1: error: Argument 2 to "setdefault" of "TypedDict" has incompatible type "str"; expected "int"  [typeddict-item]
a.setdefault("x", "bad")
^~~~~~~~~~~~~~~~~~~~~~~~
main.py:13:19: error: Argument 2 to "setdefault" of "MutableMapping" has incompatible type "str"; expected "int"  [arg-type]
b.setdefault("x", "bad")
^~~~~
Found 3 errors in 1 file (checked 1 source file)
``` …

Use more precise context for TypedDict plugin errors

---

mypy/graph_utils.py

Avoid redundant computation of `frozenset(scc)`.
This helps with incremental type checking of torch, since it has a big SCC. In my measurements this speeds up incremental checking of `-c "import torch"` by about 11%.

Speed up SCC dependency inference

---

mypy/fixup.py

Mypyc is bad at compiling tuple unpacking, so this should be faster, based on a microbenchmark I created. Also fewer tuple objects need to be allocated and freed.
The impact is probably too small to be measured in a real workload, but every little helps.

Micro-optimize cache deserialization (fixup)

---

mypy/build.py

Don't use a set to deduplicate mypy `Type` objects, since taking the hash of a type, and possibly comparing for equality (which is needed to add a type to a set) is more expensive than processing duplicates in TypeIndirectionVisitor. Many of the most expensive types to process are complex types such as callables, which often don't have many duplicates and have complex `__hash__` methods.
This seems to speed up type checking torch slightly, by about 0.5% (average of 100 runs).

Speed up State.finish_passes

---

CHANGELOG.md

As with all releases, I've omitted non user visible changes (e.g. refactoring, test-only changes) and trivial changes (e.g. fix typo) for individual list of PRs, but contributors should still be in the final "thanks" list.

Update changelog for release 1.14

---

misc/gen_blog_post_html.py

Our Changelog uses 3 number signs (#) for subheadings, not 4. This should generate proper `<h3>` in the blog post.
Also, code blocks are generated with just `<pre>` tags. Let's also add `<code>` tags so we can potentially apply syntax highlighting with js like highlight.js in the future, if we want to.
highlight.js detects `<pre><code> ... </code></pre>`. We can also put the language, but it detects it automatically: https://highlightjs.readthedocs.io/en/latest/readme.html#in-the-browser

[misc] Properly format subheadings and code in gen_blog_post_html.py

---

misc/gen_blog_post_html.py

Turns out that `<pre>...</pre>` blocks ignore the first empty line, but `<pre><code>...</code></pre>` blocks don't. So if we put the first real line of code on the html line after the tags, it will render as an empty line. (a problem that didn't exist for just pre tags) Let's remove those extra newlines after code tags.
(I still think it's nice to have code tags for future syntax highlighting on the blog posts)

[misc] Fix previous change to `<pre><code>`

---

mypyc/lib-rt/module_shim.tmpl
mypyc/test-data/commandline.test

Fixes mypyc/mypyc#999.
`PyCapsule_Import` was failing in sub-packages. Since the capsule is an attribute of the module, we can access the capsule from the module instead of importing it.

[mypyc] Getting capsule pointer from module instead of PyCapsule_Import.

---

mypy/stubtest.py
mypy/test/teststubtest.py

If the runtime attribute of a class is actually from the metaclass, consider it to be MISSING at runtime.
This only occurs a couple times in the stdlib: it shows up when a descriptor is present on the metaclass but not the class, and we want to lie in the stub and say it's a thing on the class anyway.
I found this after noticing that `enum.auto.__or__` had a comment that said it
didn't exist at runtime, but stubtest thought that it actually did. The issue is that on 3.10+, `type.__or__` is defined for the purpose of Union types, and stubtest doesn't know the difference between `type.__or__` and `__or__` on the actual class.
Currently this matches on these things in typeshed's stdlib:
```
abc.ABCMeta.__abstractmethods__
builtins.object.__annotations__
enum.auto.__or__
enum.auto.__ror__ …
```

stubtest: distinguish metaclass attributes from class attributes

---

mypy/checker.py
mypy/checkexpr.py
test-data/unit/check-expressions.test

Fixes #4134
Fixes #9195
Suppress errors when analyzing unreachable conditional expression branches. Same idea as what's done when analyzing the right-hand operand of `and`/`or`:
https://github.com/python/mypy/blob/973618a6bfa88398e08dc250c8427b381b3a0fce/mypy/checkexpr.py#L4252-L4256
This PR originally added filters of the same form to the places where `analyze_cond_branch` is called in `ExpressionChecker.visit_conditional_expr`. However, since 5 out of the 6  `analyze_cond_branch` call sites now use `filter_errors` for the case when `map is None`, I decided to move the error filtering logic to inside `analyze_cond_branch`.
**Given:**
```python
T = TypeVar("T", int, str)
def foo(x: T) -> T:
return x + 1 if isinstance(x, int) else x + "a"
```
**Before:**
```none …
```

Suppress errors for unreachable branches in conditional expressions

---

mypy/checker.py
mypyc/test-data/commandline.test
test-data/unit/check-narrowing.test
test-data/unit/fixtures/primitives.pyi

Revisit the body of a loop if the number of partial types has changed.

---

mypy/stubgen.py
mypy/stubutil.py

This change modifies `walk_packages` such that the full `ImporError` traceback is printed when a module cannot be imported. The goal is to provide the user with more context to debug the error.
I implemented this change by mirroring existing behavior in `find_module_paths_using_imports`: https://github.com/python/mypy/blob/9405bfd9205ea369c11150907764fa46c03cb1f7/mypy/stubgen.py#L1522-L1529

Print InspectError traceback in stubgen `walk_packages` when verbose is specified

---

mypy/dmypy/client.py

Revised the status message output from the `dmypy status` command to eliminate potential misunderstandings about the daemon's operational state.
Given the daemon’s synchronous design, the server may appear unresponsive during periods of heavy processing. When encountering a timeout, the status message could suggest that the daemon was "stuck", prompting users to prematurely consider stopping it.
Fixes #18008

Clarify status in `dmypy status` output

---

mypy/modulefinder.py

Python 3.9 added `functools.cache` which can replace `lru_cache(maxsize=None)`.
https://docs.python.org/3/library/functools.html#functools.cache

Replace lru_cache with functools.cache

---

mypyc/lib-rt/misc_ops.c
mypyc/test-data/run-classes.test

Fixes mypyc/mypyc#934.
`InitVar` variables are not attributes of a dataclass `PyTypeObject`. Adding check before removing `InitVar` keys from `PyTypeObject` in `CPyDataclass_SleightOfHand`.

[mypyc] Fixing InitVar for dataclasses.

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml

Just bring things in line with other repos

Minor changes to mypy_primer workflow

---

mypy/stubtest.py
mypy/test/teststubtest.py

See https://github.com/python/mypy/issues/18343#issuecomment-2564314519

stubtest: Fix crash with numpy array default values

---

mypy/main.py

This is in anticipation of https://github.com/python/typeshed/pull/13324

ArgumentParser: use broader file type

---

mypyc/lib-rt/getargs.c
mypyc/test-data/run-classes.test

Fixes https://github.com/mypyc/mypyc/issues/1078
Introduced in https://github.com/python/mypy/pull/17930
See the first commit to see the bug (wrong condition)

Fix getargs argument passing

---

mypy/mixedtraverser.py
mypy/traverser.py
mypy/type_visitor.py
mypy/types.py
mypy/typetraverser.py
mypy/visitor.py
mypyc/ir/rtypes.py

Extracted from #18356. Make `visit_*` method arguments positional only to ensure better LSP compatibility. Also update some visitors which don't have violations yet but are base classes for other ones, like `TypeTranslator` and `TypeQuery`.

Make visit method arguments pos-only

---

mypy/test/test_find_sources.py
mypy/test/testpep561.py

Fix LSP violations in test files

---

mypy/subtypes.py
test-data/unit/check-type-promotion.test
test-data/unit/fixtures/primitives.pyi

Fixes #18359
Fixes #18257
The change is simple but may be way too general.  Making it more precise should be straightforward, but I want to see the Mypy Primer results and hear other opinions first.

Reject promotions when checking against protocols.

---

CHANGELOG.md

Followup to #18364. The `Contributed by` should be placed in a separate paragraph.

Fix markdown formatting

---

mypy/plugin.py
mypy/semanal_shared.py
mypy/typeanal.py

Got lost when #18356 was broken up

More LSP compatibility on arg names

---

mypy/main.py

It seems that: if the mypy cache dir wasn't created, this code would do an exit, preventing the actual errors from being printed. So I've removed the exit. More information is available at the issue I claim this fixes.
Fixes #10768

Fix  --install-types masking failure details

---

mypyc/irbuild/match.py

`collections.abc.Generator` doesn't check the number of TypeVars (in contrast to `typing.Generator`). So it's possible to use `Generator[None]` even for Python 3.9.

Use Generator TypeVar defaults

---

mypy/typeops.py
test-data/unit/check-enum.test
test-data/unit/fixtures/enum.pyi

Fixes #18376
See also https://snarky.ca/unravelling-not-in-python/

Fix enum truthiness for StrEnum

---

mypy/main.py
test-data/unit/check-bound.test
test-data/unit/check-classes.test
test-data/unit/check-columns.test
test-data/unit/check-custom-plugin.test
test-data/unit/check-errorcodes.test
test-data/unit/check-incremental.test
test-data/unit/check-inference.test
test-data/unit/check-narrowing.test
test-data/unit/check-optional.test
test-data/unit/check-protocols.test
test-data/unit/deps.test

Also add it to a bunch of test cases where it is needed

Allow inverting --local-partial-types

---

misc/update-stubinfo.py

Additions in #18366 , will do removals once merged

Script to update stubinfo.py

---

mypyc/test-data/run-classes.test

Improves test added in #18350 to confirm the args are actually parsed correctly

[minor] improve getargs test

---

mypy/checker.py
test-data/unit/check-functions.test

Fix line number for decorator issues

---

CHANGELOG.md
mypy/fastparse.py
mypy/messages.py
mypy/nodes.py
mypy/plugins/common.py
test-data/unit/check-python38.test
test-data/unit/parse.test

Fixes #17655
The decorator cleanup moves a type ignore, but so does the bug fix for decorators in #18392 , so might as well batch into a single release

Fix line number for slices, clean up old logic

---

mypy/stubgen.py
test-data/unit/stubgen.test

Print annotations for self variables if given. Aside from the most common ones for `str`, `int`, `bool` etc. those were previously inferred as `Incomplete`.

[stubgen] Improve self annotations

---

mypy/stubutil.py
test-data/unit/stubgen.test

Don't replace `*Ts` with `Unpack[Ts]` on Python 3.11+.
This is broken currently since `Unpack` isn't added as import in the stub file.

[stubgen] Fix UnpackType for 3.11+

---

mypy/stubgen.py
test-data/unit/stubgen.test

Ref: https://github.com/python/mypy/issues/18081

[stubgen] Preserve dataclass_transform decorator

---

mypyc/irbuild/classdef.py
mypyc/test-data/run-classes.test

Fixes mypyc/mypyc#1080
Python requires that Enum must be the last class in the parent class list. This change fixes the index in `ClassDef.bases` list where we check for `Enum`.

Fix list index while checking for Enum class.

---

MANIFEST.in
pyproject.toml

Remove mypyc docs and some testing files from wheels. They aren't included for mypy itself as well. The sdist content will stay the same, so it's possible for distributors to continue to run the tests.
Files which will no longer be included
```
mypyc/README.md
mypyc/doc/**
mypyc/external/googletest/**
mypyc/lib-rt/setup.py
mypyc/lib-rt/test_capi.cc
mypyc/test-data/**
```

Remove unnecessary mypyc files from wheel

---

mypyc/test/test_run.py

#18416 removed the `mypyc/test-data` package from the wheel. This caused the wheel tests to fail. Use the `test_data_prefix` instead which uses the existing `MYPY_TEST_PREFIX` to determine the correct file location.
https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/12712285989

Fix mypyc wheel tests

---

mypy/checker.py
test-data/unit/check-generic-subtyping.test

Fixes #18189.
Following #18415, this fixes one more place where parent class generics aren't mapped to attributes correctly.

Fix parent generics mapping when overriding generic attribute with property

---

mypy/checker.py
test-data/unit/check-narrowing.test

Fixes #18348
Fixes #13973
Fixes #11612
Fixes #8721
Fixes #8865
Fixes #7204
I manually checked all the listed issues.  Some of them were already partly fixed by #18180.

Avoid false `unreachable` and `redundant-expr` warnings in loops.

---

mypy/checkpattern.py
mypyc/test-data/irbuild-match.test
test-data/unit/check-python310.test

Fixes #17095 (comment, the primary issue was already fixed somewhere before). Fixes #16272. Fixes #12532. Fixes #12770.
Prior to this PR mypy did not consider that `Any` can match any patterns, including sequence patterns (e.g. `case [_]`). This PR allows matching `Any` against any such patterns.

Allow `Any` to match sequence patterns in match/case

---

docs/source/common_issues.rst
docs/source/runtime_troubles.rst

I updated docs to not mention EOL 3.8, where it is possible to use other versions / examples.

Update docs not to mention 3.8 where possible

---

mypy/checker.py
test-data/unit/check-python310.test

Fixes #16793. Fixes crash in #13666.
Previously mypy considered that variables in match/case patterns must be Var's, causing a hard crash when a name of captured pattern clashes with a name of some existing function. This PR removes such assumption about Var and allows other nodes.

Prevent crashing when `match` arms use name of existing callable

---

mypy/build.py

Fixes #18454
Couldn't easily repro in test suite

Fix crash with `--cache-fine-grained --cache-dir=/dev/null`

---

mypyc/irbuild/classdef.py
mypyc/test-data/irbuild-classes.test

fixes https://github.com/mypyc/mypyc/issues/864

[mypyc] Report error for nested class instead of crashing

---

mypy/checker.py
test-data/unit/check-selftype.test

Fixes #18458. 
When checking base class compatibility, the class being defined is not yet in scope. However, it should be equivalent to the class passed to `bind_and_map_method` with free typevars, as that's exactly what we are currently defining.

Bind self to the class being defined when checking multiple inheritance

---

mypy/checker.py
test-data/unit/check-classes.test
test-data/unit/check-dataclasses.test

Refining dataclass attributes with a narrower type has historically been accepted. Mypy shouldn't emit an LSP warning for the synthesized `__replace__` method added in Python 3.13 either.
Users are instead encouraged to enable `--enable-error-code mutable-override` to highlight potential issues.
Fixes #18216

Ignore dataclass.__replace__ LSP violations

---

test-data/unit/pythoneval-asyncio.test

Starting in Python 3.14, `asyncio.get_event_loop` will raise a RuntimeError if no current loop exists in the current thread. Update the eval tests to use `asyncio.run` instead.

Update asyncio eval tests for 3.14

---

mypyc/doc/dev-intro.md
mypyc/test/test_run.py

When a tests case segfaults, detect it and print provide more information.
Add more detail to developer docs about debugging segfaults, including some macOS specific information.

[mypyc] Give more guidance about debugging segfaults in tests

---

.gitignore
mypy/test/config.py
mypy/test/data.py
mypyc/doc/dev-intro.md
mypyc/test/test_run.py

Now the generated C files for the first mypyc run test failure in a pytest session will be copied to the `.mypyc_test_output` directory, and this will be indicated in the test output. This is a convenience feature to help in the common scenario where all test failures have the same root cause, so any single output is sufficient for debugging.
Document this and `--mypyc-showc`, which allows showing generated C for every test failure. The latter is too verbose to be enabled by default.

[mypyc] Improve access to generated C on test failures and document this

---

misc/gen_blog_post_html.py

Toe get highlighting to work, we just need to import the CSS and run the highlight.js that does the highlighting in JS client side. We can add the lines at the top of the blog post to do this. I've made it only support bash and python for now to help with detection. But if we have a reason to, we can remove that and let it try them all.
In a previous PR I've added the necessary `<code>` tags.
Since we're highlighting nicely now, I also removed the extra indendation.
I've also noticed that we're pretty good at specifying the language in code blocks in the changelog. So we can take that language and use it in the code block as a class to tell highlight.js exactly what language that code block is in.
If this is useful, we can remove the limitation of only python and bash support from the top …

[misc] use highlight.js for syntax highlighting in blog post

---

mypy/config_parser.py
mypy/defaults.py
test-data/unit/cmdline.pyproject.test

Here's a solution to fix https://github.com/python/mypy/issues/10613. The tests are covered.
It adds the functionality of searching `pyproject.toml` recursively from the current directory up to a project root (directory with either `.git` or `.hg`) to `mypy`

Add a function to search for pyproject.toml in a project root

---

mypyc/irbuild/classdef.py
mypyc/irbuild/util.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/misc_ops.c
mypyc/primitives/misc_ops.py
mypyc/test-data/run-classes.test

Fixes mypyc/mypyc#1079.
`@attr.s` generates a `__init__` function which was getting lost in `CPyDataclass_SleightOfHand`. This change copies the generated `__init__` function and a couple of others ones to maintain consistency with CPython.

[mypyc] Fixing __init__ for classes with @attr.s(slots=True).

---

CHANGELOG.md
docs/source/config_file.rst
mypy/config_parser.py
mypy/defaults.py
mypy/main.py
mypy/test/test_config_parser.py
test-data/unit/cmdline.pyproject.test

Follow up to #16965
Fixes #16070
Handles other mypy configuration files and handles precedence between them. Also fixes few small things, like use in git worktrees

Walk up for all config files and handle precedence

---

mypyc/codegen/emit.py
mypyc/codegen/emitfunc.py
mypyc/common.py
mypyc/ir/rtypes.py
mypyc/lib-rt/mypyc_util.h
mypyc/test/test_emit.py
mypyc/test/test_emitfunc.py

Fixes mypyc/mypyc#1044.
The addition of object immortality in Python 3.12 (PEP 683) introduced an extra immortality check to incref and decref operations. Objects with a specific reference count are treated as immortal, and their reference counts are never updated.
It turns out that this slowed down the performance of certain workloads a lot (up to 70% increase in runtime, compared to 3.11). This PR reduces the impact of immortality via a few optimizations:
1. Assume instances of native classes and list objects are not immortal (skip immortality checks).
2. Skip incref of certain objects in some contexts when we know that they are immortal (e.g. avoid incref of `None`).
The second change should be clear. We generally depend on CPython implementation details to improve performance, and …

[mypyc] Reduce impact of immortality on reference counting performance

---

mypy/checker.py
mypy/lookup.py
test-data/unit/check-incremental.test
test-data/unit/check-isinstance.test
test-data/unit/check-narrowing.test
test-data/unit/check-protocols.test
test-data/unit/check-python310.test
test-data/unit/check-typeguard.test
test-data/unit/check-typeis.test
test-data/unit/deps.test
test-data/unit/fine-grained.test

While working on #18433, we encountered [this bug.](https://github.com/python/mypy/pull/18433#issuecomment-2583314142).  @ilevkivskyi identified [the underlying problem](https://github.com/python/mypy/pull/18433#issuecomment-2585455830), and we decided to try to reuse previously created ad hoc intersections of instances instead of always creating new ones.
While working on this PR, I realised that reusing intersections requires more complete names.  Currently, module and type variable specifications are not included, which could result in mistakes when using these names as identifiers.
So, I switched to more complete names.  Now, for example, `<subclass of "A" and "A">`  becomes `<subclass of "mod1.A[builtins.int]" and "mod2.A">`.  Hence, I had to adjust many existing test cases where …

Better names of and more compatibility between ad hoc intersections of instances

---

mypy/messages.py
test-data/unit/check-functions.test

Fixes #18493.
Improves message in #12013 and #4530, but probably still doesn't make it clear enough.
Use higher verbosity for type formatting in error message if callables' return types are compatible and supertype has some named arguments, as that is a popular source of confusion.

Hint at argument names when formatting callables with compatible return types in error messages

---

MANIFEST.in

Fixes this warning:
```
reading manifest template 'MANIFEST.in'
[…]
warning: no files found matching 'pytest.ini'
```

pytest options moved into pyproject.toml

---

mypy/semanal.py
test-data/unit/check-type-aliases.test
test-data/unit/diff.test

This is a partial revert of #18173 to unblock the 1.15 release
Fixes #18488

Fix isinstance with explicit (non generic) type alias

---

test-data/unit/check-flags.test

`mypy_extensions.NoReturn` has been redundant for a while now. With the next mypy_extensions release, it will raise a `DeprecationWarning` when imported.
Replace existing imports in tests with `typing.NoReturn`.

Update NoReturn imports in tests

---

test-data/unit/check-classes.test
test-data/unit/check-custom-plugin.test
test-data/unit/check-flags.test
test-data/unit/check-incremental.test
test-data/unit/check-isinstance.test
test-data/unit/check-literal.test
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test
test-data/unit/check-serialize.test
test-data/unit/check-statements.test
test-data/unit/check-typeddict.test
test-data/unit/deps-types.test
test-data/unit/deps.test
test-data/unit/diff.test
test-data/unit/fine-grained.test
test-data/unit/fixtures/typing-typeddict.pyi
test-data/unit/merge.test
test-data/unit/pythoneval.test
test-data/unit/reports.test
test-data/unit/semanal-errors.test
test-data/unit/semanal-typeddict.test

`mypy_extensions.TypedDict` has been redundant for a while now. With the next mypy_extensions release, it will raise a `DeprecationWarning` when imported.
Replace existing imports in tests with `typing.TypedDict`.

Update TypedDict imports in tests

---

mypy/config_parser.py
test-data/unit/check-inline-config.test

Disallow inline config of Python version

---

.github/workflows/test.yml
.pre-commit-config.yaml

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

Use new Github actions ARM runners for tests

---

mypy/renaming.py
test-data/unit/check-python311.test
test-data/unit/check-redefine.test

Fixes #18514.
Only `try` clause should be treated as fallible, this should not prevent `--allow-redefinition` from working in other try clauses (except, else, finally).

Allow redefinitions in except/else/finally

---

mypy/messages.py
test-data/unit/check-errorcodes.test
test-data/unit/check-statements.test

`typing.Literal` was added to the stdlib in Python 3.8.

Suggest typing.Literal for exit-return error messages

---

.github/workflows/mypy_primer.yml

I think this is needed for homeassistant

Run mypy_primer in 3.13

---

mypyc/lib-rt/float_ops.c
mypyc/lib-rt/mypyc_util.h

The error messages for some math functions got changed in https://github.com/python/cpython/pull/124299. Adjust mypyc to emit the same ones.
Fixes `mypyc/test/test_run.py::TestRun::run-math.test::testMathOps`

Update math error messages for 3.14

---

docs/source/command_line.rst
docs/source/config_file.rst
docs/source/existing_code.rst

Fixes https://github.com/python/mypy/issues/16189
Few things here:
* Soften a bit the language on the flag
* Delete docs for old deprecated `strict_concatenate` option that is now part of `extra_checks`
* Add a bit more motivation to the flag description
* Update docs for `--strict` flag to mention `extra_checks` instead of `strict_concatenate`
Note that the docs on config file option requested in the issue were added a while ago.

Update docs on extra_checks flag

---

mypy/checker.py
test-data/unit/check-literal.test
test-data/unit/fixtures/primitives.pyi

I am not waiting for review as the fix is obvious. The only annoying thing is that we had an exact test as in the repro but it passed accidentally because we use builtins fixtures.

Fix literal context for ternary expressions (for real)

---

mypyc/lib-rt/pythonsupport.h
mypyc/primitives/generic_ops.py
mypyc/test-data/exceptions.test
mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-bytes.test
mypyc/test-data/irbuild-classes.test
mypyc/test-data/irbuild-dict.test
mypyc/test-data/irbuild-glue-methods.test
mypyc/test-data/irbuild-match.test
mypyc/test-data/irbuild-nested.test
mypyc/test-data/irbuild-singledispatch.test
mypyc/test-data/irbuild-statements.test
mypyc/test-data/irbuild-str.test
mypyc/test-data/irbuild-try.test
mypyc/test-data/irbuild-unreachable.test
mypyc/test-data/irbuild-vectorcall.test
mypyc/test-data/refcount.test
mypyc/test/testutil.py

This PR updates the `capi_version` used for mypyc tests to `3.8` (mypy / mypyc requires `>=3.9`). Test data updates done with `--update-data`. For Python 3.8+ mypyc uses `_PyObject_Vectorcall` instead of `PyObject_CallFunctionObjArgs` and `PyObject_Call` where ever possible.
Will remove the now unnecessary `use_vectorcall` check in a followup.
https://github.com/python/mypy/blob/aa0b6f0288e6a511b750f7fe8f49a0e321362105/mypyc/common.py#L103-L105

Update capi_version for mypyc tests to 3.8

---

mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-classes.test
mypyc/test-data/irbuild-str.test
mypyc/test-data/irbuild-vectorcall.test
mypyc/test-data/refcount.test
mypyc/test/testutil.py

Followup to #18341
This PR updates the `capi_version` used for mypyc tests to `3.9` (mypy / mypyc requires `>=3.9`). For Python 3.9+ mypyc uses `PyObject_VectorcallMethod` instead of `CPyObject_CallMethodObjArgs` and select `PyObject_Vectorcall` where ever possible.
Will remove the now unnecessary `use_method_vectorcall` check in a followup.
https://github.com/python/mypy/blob/42e005c999d8341c0da6d7b93b10d05f2db2099c/mypyc/common.py#L114-L116

Update capi_version for mypyc tests to 3.9

---

mypyc/lib-rt/int_ops.c
mypyc/lib-rt/mypyc_util.h

`_PyLong_New` will be deprecated in `3.14.0a5`. Replace it with the `PyLongWriter` API available in `pythoncapi_compat.h` for older versions.
https://docs.python.org/dev/c-api/long.html#pylongwriter-api

Replace deprecated `_PyLong_new` with `PyLongWriter` API

---

mypy/checker.py
test-data/unit/check-isinstance.test
test-data/unit/check-typevar-values.test

Fixes #18428. 
Prevents rewriting `None` ("unreachable") typemaps as empty dicts ("nothing to infer")

Retain None (unreachable) when typemap is None with `type(x) is Foo` check

---

mypyc/lib-rt/pythonsupport.h

Mypyc requires Python 3.9+. The functions are available from cpython itself.

Remove old marcos for _PyObject_CallMethod..

---

mypyc/irbuild/builder.py
mypyc/irbuild/ll_builder.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/misc_ops.c
mypyc/primitives/misc_ops.py
mypyc/test/test_misc.py

It generates C code to print to stdout, but tries to preserve the error state and not affect the code it's added to.
Added test for it, but also tested this by adding
`builder.debug_print(typ)` in `add_non_ext_class_attr_ann` and it prints the class name.
It's also useful to use it like `builder.debug_print("MARKER")` and then to search in the generated C code for MARKER. For more complex debugging tasks, this is useful in finding your way around the generated C code and quickly looking at the interesting part.
I saw that there's already a misc op `CPyDebug_Print`. I haven't seen it used though. I think we can remove that one if this is proving useful.

[mypyc] Add debug op (and builder helper) for printing str or Value

---

mypy/meet.py
test-data/unit/check-namedtuple.test

Fixes https://github.com/python/mypy/issues/18562.
Fixes https://github.com/python/mypy/issues/6623.
Fixes https://github.com/python/mypy/issues/18520. (Only incidentally and I'm not exactly sure why.)
I was investigating what input mypy thought satisfied both overloads and I found that mypy is missing a check on the fallback type.

Update the overlapping check for tuples to account for NamedTuples

---

mypyc/irbuild/classdef.py

Mypyc requires Python 3.9+. This PR removes the old TypedDict and NamedTuple code for versions prior to 3.9.

Remove old TypedDict + NamedTuple code from mypyc

---

mypyc/codegen/emit.py
mypyc/codegen/emitclass.py
mypyc/codegen/emitmodule.py
mypyc/codegen/emitwrapper.py
mypyc/common.py
mypyc/irbuild/ll_builder.py

Followup to #18341 and #18546
We only support Python 3.9+, so `PyObject_Vectorcall` and `PyObject_VectorcallMethod` are always available. Remove backwards compatibility layer.

Cleanup backwards compat layer for use_vectorcall and use_method_vectorcall

---

mypyc/doc/differences_from_python.rst
mypyc/doc/native_classes.rst
mypyc/doc/performance_tips_and_tricks.rst
mypyc/doc/using_type_annotations.rst

We no longer support 3.8, so all supported Python versions support `list[t]` and friends.

[mypyc] Use lower-case generic types such as "list[t]" in docs

---

mypy/typeanal.py
test-data/unit/check-ctypes.test
test-data/unit/fixtures/float.pyi
test-data/unit/fixtures/floatdict.pyi

While doing some cleanup, I noticed a reference to `builtins.Any`. To the best of my knowledge, it was never implemented.

Remove support for `builtins.Any`

---

.pre-commit-config.yaml
CHANGELOG.md

And add a local pre-commit hook to detect when a PR number in a link text is different from the link body

Fix a few PR links in the changelog

---

mypyc/irbuild/classdef.py
mypyc/test-data/run-classes.test

This PR makes `add_non_ext_class_attr_ann` behave the same way standard python handles modules with `from __future__ import annotations` by using string types. With this we can reference types declared further in the file. But since this will change in future versions of python, let's only do this for forward references, for types that are defined further down in the same module.
This also works with string type annotations.
Fixes https://github.com/mypyc/mypyc/issues/992

[mypyc] Handle non extention classes with attribute annotations for forward defined classes

---

test-data/unit/fixtures/tuple.pyi

This makes it more similar to the real typeshed. It is needed to reproduce tricky failures in tests, e.g. https://github.com/python/mypy/pull/18585. If this causes slower tests, some tests may be switched to `tuple-simple.pyi`.

Add object self-type to tuple test fixture

---

mypy/checker.py
mypy/semanal_shared.py
mypy/type_visitor.py
test-data/unit/check-incremental.test
test-data/unit/check-inference.test

Fixes #18582. Fixes #17396. Supersedes #18351.
cc @hauntsaninja - see my comments on your original PR, maybe this change should be lifted to BoolTypeQuery and TypeQuery instead? (opening a separate PR to see CI results)

Prevent crash on generic NamedTuple with unresolved typevar bound

---

mypy/messages.py
test-data/unit/check-basic.test
test-data/unit/check-functions.test
test-data/unit/check-inference.test
test-data/unit/check-literal.test
test-data/unit/check-optional.test
test-data/unit/check-overloading.test
test-data/unit/check-typevar-values.test
test-data/unit/check-unions.test
test-data/unit/check-varargs.test
test-data/unit/cmdline.test

All supported Python versions support `list[...]` and `dict[...]`.

Use lower case "list" and "dict" in invariance notes

---

mypy/binder.py
mypy/checker.py
mypy/fastparse.py
mypy/join.py
mypy/test/testtypes.py
mypyc/test-data/irbuild-any.test
test-data/unit/check-classes.test
test-data/unit/check-dynamic-typing.test
test-data/unit/check-isinstance.test
test-data/unit/check-narrowing.test
test-data/unit/check-optional.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-python310.test
test-data/unit/check-redefine.test
test-data/unit/check-typeguard.test
test-data/unit/check-unions.test
test-data/unit/check-unreachable-code.test
test-data/unit/typexport-basic.test

This would be more consistent with what we already do for ternary expressions. Note the change in match test results from match logic not handling well the situation when initial type is a union. A possible workaround would be to force "collapsing" union of tuples back into a tuple with union, but it is not easy and was planning to do some cleanup in the match handling as well (in particular it uses joins instead of unions in a way that will be inconsistent with new binder behavior). I want to put the switch from join to union for match statement in a separate PR.
Note I also simplify a bunch of special-casing around `Any` in the binder that existed mostly because `join(Any, X) == Any`.
Fixes https://github.com/python/mypy/issues/3724

Use union types instead of join in binder

---

CHANGELOG.md

Fix markup in CHANGELOG for mypy@1.15

---

mypy/checkexpr.py
mypy/checkmember.py
test-data/unit/check-typeddict.test

Add missing TypedDict special case to checkmember.py

---

mypy/checkmember.py
mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Closes #18567 
We should allow inferenced `a: Final = 1`

Fix "not callable" issue for `@dataclass(frozen=True)` with `Final` attr

---

mypy/binder.py
mypy/literals.py
mypy/nodes.py

Hopefully this makes this a little less confusing.

Update comments and docstrings related to binder

---

mypy/config_parser.py
test-data/unit/cmdline.test

Now 
```ini
files =
a.py,
b.py
```
and 
```ini
files =
a.py,
b.py,
```
will be the same thing.
Previously, adding a traling comma would add `''` to `paths`, which resulted in a strange error like:
```
a.py: error: Duplicate module named "a" (also at "a.py") (diff)
a.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info (diff)
a.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH (diff)
```
Refs https://github.com/python/mypy/pull/14240
Refs https://github.com/python/cpython/pull/129708

Allow trailing commas for `files` setting in `mypy.ini` and `setup.ini`

---

mypy/semanal.py
test-data/unit/check-newsemanal.test
test-data/unit/check-python312.test
test-data/unit/check-type-aliases.test

Fixes https://github.com/python/mypy/issues/18505
Fixes https://github.com/python/mypy/issues/16757
Fixing the crash is trivial, we simply give an error on something like `type X = X`, instead of crashing. But then I looked at what people actually want to do, they want to create an alias to something currently in scope (not a meaningless no-op alias). Right now we special-case classes/aliases to allow forward references (including recursive type aliases). However, I don't think we have any clear "scoping rules" for forward references. For example:
```python
class C:
Y = X
class X: ...
class X: ...
```
where `Y` should point to, `__main__.X` or `__main__.C.X`? Moreover, before this PR forward references can take precedence over real references:
```python
class X: ...
class C:
Y = X  # this …
```

Fix crashes on incorectly detected recursive aliases

---

mypy/config_parser.py
test-data/unit/check-custom-plugin.test
test-data/unit/cmdline.pyproject.test
test-data/unit/cmdline.test

Refs https://github.com/python/mypy/pull/18621
Closes https://github.com/python/mypy/issues/18623
With a lot more tests.

Test and fix trailing commas in many multiline string options in `pyproject.toml`

---

mypy/semanal.py
test-data/unit/check-python311.test

Allow lambdas in except* clauses

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Fixes #18527
The fix is pretty simple.  I could not find a situation where combining `NamedTuple` and `dataclass` makes sense, so emitting an error and just not applying the dataclass transformations seems sensible.

Report that `NamedTuple` and `dataclass` are incompatile instead of crashing.

---

mypyc/irbuild/match.py
mypyc/test-data/irbuild-match.test

[mypyc] Recognize Literal types in __match_args__

---

mypy/checker.py
test-data/unit/check-functools.test

Resolves #18637
Mypy's behaviour here is not correct (see test case), but this PR makes mypy's behaviour match what it used to be before we added the functools.partial plugin
Support for overloads tracked in #17585

Improve support for functools.partial of overloaded callable protocol

---

mypy/meet.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/18105
When I implemented this initially, I only handled tuples, but forgot instances, thus causing the crash. I don't add many tests, since the instance overlap check simply relays to the tuple one, that is already tested.
(Btw I already forgot how verbose everything is in the `TypeVarTuple` world :-))

Fix overlap check for variadic generics

---

mypyc/test-data/run-misc.test
test-data/unit/check-basic.test
test-data/unit/check-enum.test
test-data/unit/check-expressions.test
test-data/unit/check-final.test
test-data/unit/check-incremental.test
test-data/unit/check-isinstance.test
test-data/unit/check-literal.test
test-data/unit/check-narrowing.test
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test
test-data/unit/check-protocols.test
test-data/unit/check-python310.test
test-data/unit/check-python38.test
test-data/unit/check-recursive-types.test
test-data/unit/check-selftype.test
test-data/unit/check-statements.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typeddict.test
test-data/unit/check-union-error-syntax.test
test-data/unit/check-union-or-syntax.test
test-data/unit/check-unreachable-code.test
test-data/unit/deps-expressions.test
test-data/unit/diff.test
test-data/unit/fine-grained.test
test-data/unit/fixtures/set.pyi
test-data/unit/lib-stub/typing.pyi
test-data/unit/merge.test
test-data/unit/pythoneval.test
test-data/unit/semanal-literal.test

`Literal` was added to Python in 3.8. Replace most `typing_extensions` imports in tests.

Update Literal imports in tests

---

docs/source/command_line.rst
docs/source/config_file.rst
docs/source/error_code_list2.rst
mypy/checker.py
mypy/main.py
mypy/options.py
mypy/typeanal.py
test-data/unit/check-deprecated.test

Suggested in https://github.com/python/mypy/pull/18192#issuecomment-2512775035
Fixes https://github.com/python/mypy/issues/18435

Add option to selectively disable deprecation warnings

---

mypy/checker.py
test-data/unit/check-inference.test

Fixes #18629. Fixes #16321. Fixes #8637.

Don't assume that for loop body index variable is always set

---

mypyc/test-data/irbuild-dict.test
mypyc/test-data/run-classes.test
mypyc/test-data/run-dicts.test
mypyc/test-data/run-functions.test
mypyc/test-data/run-misc.test
test-data/unit/check-basic.test
test-data/unit/check-dataclasses.test
test-data/unit/check-errorcodes.test
test-data/unit/check-formatting.test
test-data/unit/check-functions.test
test-data/unit/check-functools.test
test-data/unit/check-incremental.test
test-data/unit/check-inference.test
test-data/unit/check-literal.test
test-data/unit/check-modules.test
test-data/unit/check-narrowing.test
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test
test-data/unit/check-python38.test
test-data/unit/check-recursive-types.test
test-data/unit/check-typeddict.test
test-data/unit/check-typevar-tuple.test
test-data/unit/check-typevar-values.test
test-data/unit/check-varargs.test
test-data/unit/fine-grained-follow-imports.test
test-data/unit/fine-grained-suggest.test
test-data/unit/fine-grained.test
test-data/unit/fixtures/for.pyi

Followup to #18528
Replace most `typing_extensions.TypedDict` imports in tests with `typing.TypedDict`.

Update TypedDict imports in tests (2)

---

mypy/checker.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/18648
The fix is straightforward, but unlike for getter I decided to not create any ad-hoc types during `last_pass`.

Fix crash on deferred supertype and setter override

---

CHANGELOG.md

Create changelog entries for
- #18510
- #18641

Add initial changelog for 1.16

---

mypy/ipc.py

Build the socket name from directory name and name instead.
This fixes existing failing tests on Debian GNU/Hurd:
* mypy/test/testdaemon.py::DaemonSuite::*
* mypy/test/testipc.py::IPCTests::*

GNU/Hurd returns empty string from getsockname() for AF_UNIX sockets

---

mypy/checker.py
mypy/checkmember.py

The hack to use `meet_types(original_type, itype)` to select a correct element from a union appeared before we added proper handling of unions in various places related to `checkmember.py`. This is error prone, since `meet_types()` is one of least precise type ops (for good and bad reasons), and results in obscure bugs, see e.g. https://github.com/python/mypy/issues/15600
This hack should not be needed anymore, now we have three-level information available everywhere we needed it:
* `original_type` - as the name says, a type from which everything started. This is used for error messages and for plugin hooks.
* `self_type` - a specific element of the union is the original type is a union. The name is because this is what will be ultimately used by `bind_self()`
* `itype` the actual …

Delete old meet hack from checkmember.py

---

mypy/config_parser.py
mypy/defaults.py

Fixes #18650
Slightly annoying to add a test for since it would clutter up user home directory

Fix regression for user config files

---

.pre-commit-config.yaml
mypy/fastparse.py
mypy/nodes.py
mypy/stubinfo.py

Replaces #18387
Use codespell in pre-commit to detect spelling mistakes, see #18642. Ignore test and typeshed folders.

Add codespell to pre-commit config

---

mypy/checkpattern.py
test-data/unit/check-python310.test

Fixes https://github.com/python/mypy/issues/15299
The fix is straightforward, named tuples should be properly represented as tuples with fallback, not as instances.

Fix handling of named tuples in class match pattern

---

test-data/unit/check-namedtuple.test

Fixes https://github.com/python/mypy/issues/15600
The issue was previously "fixed" because of another bug. Now that everything is properly fixed, we can add this "regression" test just in case.

Test case for fixed namedtuple method call

---

mypyc/lower/registry.py
mypyc/transform/ir_transform.py
mypyc/transform/lower.py

This only works for simple initialization ops and ops where the return value is ignored. This can be used for dummy init ops that are used to give hints to data flow analysis about lifetimes of values, when initialization is done via a pointer argument (e.g. `init_my_struct(&reg)` in C).

Allow lowered opts to be deleted in lowering trasnform

---

mypy/subtypes.py
mypy/test/testsubtypes.py

Previously a code path was introduced that made fallback a subtype of its tuple type for non-generic tuples, while the intention was to cover `tuple[Any, ...]` and similar. I add a unit test + some refactoring to make this mistake much harder in future.
This may need to wait for https://github.com/python/mypy/pull/18663 to avoid "regressions" (the other fix needed to avoid "regressions" is already merged).

Fix instance vs tuple subtyping edge case

---

mypyc/doc/str_operations.rst
mypyc/lib-rt/CPy.h
mypyc/lib-rt/str_ops.c
mypyc/primitives/str_ops.py
mypyc/test-data/fixtures/ir.py
mypyc/test-data/run-strings.test

Use `PyUnicode_RSplit` to optimize `str.rsplit` calls. Although not present in the documentation, it's has actually part of the stable API since Python 3.2.
https://github.com/python/cpython/blob/v3.13.2/Doc/data/stable_abi.dat#L799
https://github.com/python/cpython/blob/main/Include/unicodeobject.h#L841-L858

[mypyc] Optimize str.rsplit

---

.github/workflows/test.yml

The `actions/checkout` issue with the new Github arm runners is reportedly fixed on `ubuntu-22.04-arm`. Let's try and see how it goes. We can always switch back later when `ubuntu-24.04-arm` is fixed as well.
Ref #18660

[ci] Use ubuntu-22.04-arm runners

---

mypyc/doc/dict_operations.rst

Support for `dict.setdefault` was added in https://github.com/python/mypy/commit/f463a3921fcd5cb360c12a84650880a2a92e0566 a few years ago.

[mypyc] Mark dict.setdefault as optimized

---

mypyc/lib-rt/pythoncapi_compat.h

Fixes: #18698 
This is a naive fix for the gcc 15 error when compiling for Python 3.12

pythoncapi_compat: don't define Py_NULL if it is already defined

---

mypyc/lib-rt/str_ops.c
mypyc/primitives/str_ops.py
mypyc/test-data/irbuild-str.test

Followup to #18678
Missed that we can also use `bool_rprimitive` as return type with a value of `2` for errors.

[mypyc] Improve str.startswith and str.endswith with tuple argument

---

test-data/unit/check-literal.test
test-data/unit/check-typeddict.test

#18640 removed almost all instances of `typing_extensions.Literal` in the tests. Re-add a simple regression test. Similarly at least one test case should import `mypy_extensions.TypedDict`.

Add regression test for typing_extensions.Literal and mypy_extensions.TypedDict

---

mypy/stubtest.py
pyproject.toml

Enforce no unnecessary duplicate isinstance calls (that could be merged into a tuple call).

Enable ruff SIM101 duplicate isinstance check

---

mypyc/doc/str_operations.rst
mypyc/primitives/str_ops.py
mypyc/test-data/run-strings.test

https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_Contains

[mypyc] Optimize str.__contains__

---

mypy/checker.py
test-data/unit/check-modules.test

This helps in rare cases, see discussion in https://github.com/python/mypy/pull/18674

Add one more type-checking pass

---

mypy/checker.py
mypy/checkexpr.py
mypy/semanal.py
test-data/unit/check-inference.test

This makes deferral logic more robust and more consistent with fine-grained mode. I also:
* Change some terminology, as "top function" is ambiguous: top-level function vs top of stack function.
* Update some docs and type annotations to match actual behavior (e.g. we do not defer lambdas)
See also https://github.com/python/mypy/pull/18674 for some more motivation.

Only defer top-level functions

---

mypyc/irbuild/main.py
mypyc/irbuild/missingtypevisitor.py
mypyc/irbuild/prebuildvisitor.py
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-python312.test

mypyc was crashing because it couldn't find the type in the type map. This PR adds a generic AnyType to the type map if an expression isn't in the map already.
Tried actually changing mypy to accept these type alias expressions, but ran into problems with nested type aliases where the inner one doesn't have the "analyzed" value and ending up with wrong results.
fixes https://github.com/mypyc/mypyc/issues/1064

Fix mypyc crash with enum type aliases

---

mypy/stubdoc.py
mypy/test/teststubgen.py

`stubgen` has a regex which it uses to reject invalid types that are extracted from docstrings.  It needed to be updated to support union shorthand: `str | int`.

stubgen: Fix valid type detection to allow pipe unions

---

.github/workflows/test.yml

The `ubuntu-24.04-arm` runners were fixed a week ago. I haven't seen any new issue reports so it should be safe to switch back.
Fixes #18660

[ci] Switch back to ubuntu-24.04-arm runners

---

mypy/stubtest.py
mypy/test/teststubtest.py

Fixes #15302, fixes #14560. Linking #18343

stubtest: better checking of runtime args with dunder names

---

mypy/stubgenc.py
mypy/test/teststubgen.py

handle arg=None in stubgenc

---

docs/source/type_narrowing.rst

In #18766 I had overlooked the existence of TypeIs. IMHO this could have been prevent by a slightly better structuring of the docs:
- add a list of all type narrowing techniques at the top
- move the "Limitations" section to the bottom, because it's generic. Because it separated the three other techniques from TypeIs I had not read on below "Limitations"

Improve docs on type narrowing

---

mypy/checker.py
mypy/semanal.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/18764
There are two things important to understand this PR:
* First, mypy has a performance optimization - we store decorator/overload type during semantic analysis in certain "trivial" situations (to avoid deferrals). Otherwise, we infer the type of decorated function or an overload variant during type checking.
* Second, for settable properties we store getter type in two places, as a `Var.type` of getter (as a decorator), and also in overall `OverloadedFuncDef.type`. The latter is ugly, but unfortunately it is hard to get rid of, since some code in multiple plugins rely on this.
It turns out there are _three_ inconsistencies in how these two things interact (first one causes the actual crash):
* For trivial settable properties (i.e. without …

Consistently store settable property type

---

mypyc/lib-rt/CPy.h
mypyc/lib-rt/str_ops.c
mypyc/primitives/str_ops.py
mypyc/test-data/fixtures/ir.py
mypyc/test-data/irbuild-str.test
mypyc/test-data/run-strings.test

Fixes mypyc/mypyc#1090.
Copying cpython implementation for strip, lstrip and rstrip to `str_ops.c`.

Add efficient primitives for str.strip().

---

mypy/constraints.py
mypy/types.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/18780
Fix is trivial: handle a missing case. Note I re-use `flatten_nested_tuples()` out of laziness. In theory, there should be at most one level of nesting at this point, after which we should put an assert (and IIRC we do something like this in other places). But I think it is not worth the effort here, as this is a quite niche edge case anyway.

Fix crash for callable with *args and suffix against Any

---

CHANGELOG.md
mypy/checker.py
test-data/unit/check-python310.test

Addressed issue #16286, which reported that `match` statements failed to narrow unions when matching on discriminant values (e.g. `tag` fields in `TypedDict`s or classes). This led to mypy complaining about missing keys/attributes inside `case` blocks even though plain `if ... ==` branches worked.
- **Binder fix in `mypy/checker.py`:**
- In `visit_match_stmt`, after calling `conditional_types_to_typemaps` for the subject, the resulting type map is passed through `propagate_up_typemap_info` (just like in the `if`/`isinstance` code paths). This means if the subject is an attribute or index expression (`d.tag` / `d["tag"]`), we try to refine the parent `d` based on the pattern.
- Corrected indentation and ensured we only push `pattern_map` when it's defined, to avoid `UnboundLocalError` in …

fix: Narrowing with "tags" on unions (of TypedDicts or normal classes) doesn't work with the match statement

---

mypy/partially_defined.py

Fix for issue uncovered in #18803.

Fix dict.get issue for typeshed update

---

.github/workflows/mypy_primer.yml
mypy/binder.py
mypy/build.py
mypy/checker.py
mypy/checkexpr.py
mypy/literals.py
mypy/main.py
mypy/nodes.py
mypy/options.py
mypy/semanal.py
test-data/unit/check-incremental.test
test-data/unit/check-python310.test
test-data/unit/check-redefine2.test

Infer union types for simple variables from multiple assignments, if the variable isn't annotated. The feature is enabled via `--allow-redefinition-new`. `--local-partial-types` must also be enabled.
This is still experimental and has known issues, so it's not documented anywhere. It works well enough that it can be used for non-trivial experimentation, however.
Closes #6233. Closes #6232. Closes #18568. Fixes #18619.
In this example, the type of `x` is inferred as `int | str` when using the new behavior:
```py
def f(i: int, s : str) -> int | str:
if i > 5:
x = i
else:
x = s  # No longer an error
reveal_type(x)  # int | str
return s
```
Here is a summary of how it works:
* Assignment widens the inferred type of a variable and always narrows (when there is no annotation).
* Simple variable …

Add flag to allow more flexible variable redefinition

---

mypy/stubtest.py

stubtest: understand override

---

docs/source/config_file.rst

Update the documentation: change occurrences of Python 2.7, use Python 3.9 instead.

Remove last occurrences of Python 2.7

---

mypy/checkexpr.py
mypy/checkmember.py

This is one last small refactoring before I start the actual non-trivial changes.

Move one more function from checkmember.py

---

mypyc/test-data/annotate-basic.test
mypyc/test/test_annotate.py

This makes it more convenient to write source code annotation tests.

[mypyc] Allow specifying annotate test case outputs using comments

---

mypyc/test/test_annotate.py

This makes it easier to figure out why a test is failing.
Example output on failure:
```
=================================== FAILURES ====================================
________________________ testAnnotateTwoOperationsOnLine ________________________
data: /Users/jukka/src/mypy/mypyc/test-data/annotate-basic.test:18:
Failed: Invalid source code output (/Users/jukka/src/mypy/mypyc/test-data/annotate-basic.test, line 18)
----------------------------- Captured stdout call ------------------------------
Generated IR:
def f(x):
x :: object
r0 :: str
r1, r2, r3 :: object
L0:
r0 = 'foo'
r1 = CPyObject_GetAttr(x, r0)
r2 = object 1
r3 = PyNumber_Add(r1, r2)
return r3
----------------------------- Captured stderr call ------------------------------
Expected:
main:2: Get non-native attribute …
```

[mypyc] Display IR on annotate test failure

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py

This is not a pure refactoring, but almost. Right now we are in a weird situation where we have two inconsistencies:
* `__set__()` is handled in `checker.py` while `__get__()` is handled in `checkmember.py`
* rules for when to use binder are slightly different between descriptors and settable properties.
This PR fixes these two things. As a nice bonus we should get free support for unions in `__set__()`.

Consolidate descriptor handling in checkmember.py

---

mypy/stubinfo.py

SciPy itself has no `py.typed` and barely any stubs, so I wrote [`scipy-stubs`](https://github.com/scipy/scipy-stubs). Recently, it has been accepted as an official scipy project. 
This stubs-only package is *complete* (no `untyped`) and *valid* (according to mypy, stubtest, pyright, basedmypy and basedpyright), and carefully annotated (by humans). 
And for what it's worth, it's also on the list of `mypy_primer` projects.
I'm open to any feedback, questions, and ideas in general; no need to hold back :)

add `scipy-stubs` as non-typeshed stub package

---

mypyc/doc/str_operations.rst
mypyc/primitives/int_ops.py
mypyc/primitives/str_ops.py
mypyc/test-data/run-strings.test

https://docs.python.org/3/c-api/object.html#c.PyObject_Repr

[mypyc] Optimize builtins.repr

---

.github/workflows/test.yml
pyproject.toml
test-requirements.in
test-requirements.txt

Setuptools `v77` was released today which adds full support for PEP 639.
https://setuptools.pypa.io/en/latest/history.html#v77-0-0
https://peps.python.org/pep-0639/
The relevant project metadata changes
```diff
...
-License: MIT
+License-Expression: MIT
...
-Classifier: License :: OSI Approved :: MIT License
...
License-File: LICENSE
+License-File: mypy/typeshed/LICENSE
...
```

Update project metadata for PEP 639

---

mypy/argmap.py
test-data/unit/check-kwargs.test

Fixes #13675. I don't know why this check was ever needed (since #11151), but it doesn't seem correct.

Admit that **kwargs mapping subtypes may have no direct type parameters

---

mypy/constraints.py
mypy/types.py
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/17755
Fix is trivial, so not really waiting for review. Btw I found few other places where we do not normalize callables. TBH I already forgot when we actually _need_ to normalize, but I don't want to just blanket add normalization, as it may be a relatively expensive function. If we will hit another similar crash, I will add more normalization accordingly (similar to what I did with kwargs unpacking).

Fix crash on type inference against non-normal callables

---

mypy/semanal.py
mypy/typeanal.py
test-data/unit/check-python312.test

Fixes #18856. This should be done by `TypeAnalyzer.anal_array` but is not - semanal only invokes its own wrapper around `anal_type`

Fix crash on multiple unpacks in a bare type application

---

mypy/checker.py
mypy/checkmember.py
test-data/unit/check-classes.test
test-data/unit/check-functions.test
test-data/unit/check-functools.test
test-data/unit/check-incremental.test
test-data/unit/check-namedtuple.test
test-data/unit/check-protocols.test
test-data/unit/check-selftype.test
test-data/unit/fine-grained.test

Fixes https://github.com/python/mypy/issues/5803
Fixes https://github.com/python/mypy/issues/18695
Fixes https://github.com/python/mypy/issues/17513
Fixes https://github.com/python/mypy/issues/13194
Fixes https://github.com/python/mypy/issues/12126
This is the first PR towards https://github.com/python/mypy/issues/7724, some notes:
* I add a new generic `suppress_errors` flag to `MemberContext` mostly as a performance optimization, but it should also be handy in the following PRs
* I noticed some inconsistencies with how we handle variable inference (e.g. we don't infer type at all if rvalue type is not compatible with superclass type). After all I decided to remove some of them, as it makes implementation of this PR simpler.
* I added a bunch of TODOs, most of those will be addressed in …

Use checkmember.py to check variable overrides

---

mypy/checker.py
mypy/nodes.py
test-data/unit/check-enum.test

Closes #18565 
This fixes the problem with `nonmember` and `member` special cases, however, it required me to change one test case.
See `testEnumReachabilityPEP484ExampleSingletonWithMethod` change, because in runtime `token` is not a member by default, at least in recent python versions. Proof:
```python
>>> from enum import Enum
>>> class Empty(Enum):
...     token = lambda x: x
...     
>>> Empty.token
<function Empty.<lambda> at 0x101251250>
>>> Empty.token.value
```
and
```python
>>> from enum import Enum
>>> class Empty(Enum):
...     token = lambda x: x
... 
>>> Empty.token
<function Empty.<lambda> at 0x104757600>
>>> Empty.token.value
File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'value'
```
So, I had to …

Always use `.enum_members` to find enum members

---

mypy/semanal.py
test-data/unit/check-enum.test
test-data/unit/check-namedtuple.test
test-data/unit/check-typeddict.test

Fixes #18736. Includes same fix for TypedDict (also crashes on master) and NamedTuple (does not crash as it rejects MemberExpr before setting .analyzed, so just for the sake of consistency)

Prevent crash when enum/typeddict call is stored as a class attribute

---

mypy/checkmember.py
test-data/unit/check-classvar.test

Currently we only bind self if the type is callable, but we actually should do this for all callable items in a union.
This use case is probably quite niche (since adding an annotation makes a variable an instance variable, and we rarely infer unions). I found it when looking at `checkmember`-related issues it was easy to handle it. I also use this opportunity to refactor and add comments to `analyze_var()`.

Handle union types when binding self

---

mypy/checkexpr.py
test-data/unit/check-parameter-specification.test

Reject duplicate `ParamSpec.{args,kwargs}` at call site

---

mypy/checkmember.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/15921
I know there were previously concerns about performance of `check_self_arg()`, but note that the code path where I add it only affects descriptors and `__getattr__`/`__setattr__`, so I think it should be OK.

Fix descriptor overload selection

---

mypy/checker.py
mypy/checkmember.py
test-data/unit/check-classes.test
test-data/unit/check-functions.test
test-data/unit/check-plugin-attrs.test
test-data/unit/check-selftype.test
test-data/unit/fixtures/module.pyi

This is a second "large" PR towards https://github.com/python/mypy/issues/7724. Here I actually expect a smaller fallout than for variables, since methods are usually less tricky, but let's see.

Use checkmember.py to check method override

---

mypy/errors.py
test-data/unit/check-errorcodes.test

Warn about unused `type: ignore` comments when error code is disabled

---

mypy/checker.py
test-data/unit/check-abstract.test
test-data/unit/check-plugin-attrs.test

This is the third "major" PR towards https://github.com/python/mypy/issues/7724
This one is mostly straightforward. I tried to preserve the existing logic about mutable overrides (to minimize fallout), as currently we e.g. don't use the covariant mutable override error code here. In future we can separately "synchronize" mutable override logic across variable override, method override, and multiple inheritance code paths (as currently all three are subtly different).

Use checkmember.py to check multiple inheritance

---

mypy/checker.py
mypy/checker_shared.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/checkpattern.py
mypy/checkstrformat.py
mypy/semanal.py

The import cycle is not a real one as `if TYPE_CHECKING: ...` is used, but it would become much bigger if I start using `checkmember` in `subtypes`, essentially it would be one huge import cycle during self-checking. So I decided to do something similar we did for semantic analyzer.

Add shared checker interface to break import cycle

---

mypy/checkmember.py
mypy/semanal.py
mypyc/irbuild/prepare.py
test-data/unit/check-functions.test

Fixes https://github.com/python/mypy/issues/11488
This is a little quality of life improvement. Implementation is straightforward. I also update mypyc to give an error instead of crashing.

Allow omitting implementation for abstract overloads

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

In runtime python does not add fields that have `kw_only` marker:
- https://github.com/python/cpython/blob/895d983b5c9716aaaab34d14d278084b9b6730d8/Lib/dataclasses.py#L1174-L1177
- https://github.com/python/cpython/blob/895d983b5c9716aaaab34d14d278084b9b6730d8/Lib/dataclasses.py#L411-L417
See:
```python
>>> import dataclasses
>>> @dataclasses.dataclass(kw_only=True)
... class A:
...     a: int
... 
>>> print(A.__match_args__)
()
```
Closes https://github.com/python/mypy/issues/18863

Do not add `kw_only` dataclass fields to `__match_args__`

---

mypy/subtypes.py
mypy/typeops.py
test-data/unit/check-literal.test

Flatten union before contracting literals when checking subtyping

---

mypy/semanal_main.py

Fixes #12664
A root cause is there is this stateful `_update_ns_ancestors` thing in `modulefinder`, so if things get called in the wrong order, you can get incorrect results.
See also the logic in `all_imported_modules_in_file` where we've fixed several bugs like this previously, like #13124 and #10937
As a result of (seemingly accidentally) reusing imports across modules, we can end up in a situation where the namespace gets added as a dependency to all other modules and so on the cached run we attempt to find namespace before package, which does not work
I am not sure this `imports` code path is even needed, so I will open an alternate PR, see #18908.
Relevant history:
- https://github.com/python/mypy/pull/6582
- https://github.com/python/mypy/pull/6179
I can't write a good test for …

Fix incremental issue with namespace packages (option 1)

---

mypy/dmypy_server.py
test-data/unit/daemon.test

Fixes #18396. Fixes #17652. Hopefully fixes #15486 (but not enough info to reproduce the original problem).
See discussion in #18396. This PR forces collecting all ancestors of all modules during dep graph traversal in incremental update. 
Ancestors are included in `load_graph`, which means not traversing them during update results in some modules being erroneously treated as deleted:
https://github.com/python/mypy/blob/a4e79ea19506948fd43bf5c14bbf8e2a0ad7158a/mypy/build.py#L3141-L3146

Traverse module ancestors when traversing reachable graph nodes during dmypy update

---

docs/source/runtime_troubles.rst

Replaced a comment in the documentation that the behavior described in pep 563 might be the default behavior with actual information about what will be declared deprecated in python 3.14

Docs: added information about deprecated pep 563

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

There is a mix-up in error messages related to frozen and non-frozen dataclass inheritance.
Currently:
- Inheriting a frozen dataclass from a non-frozen one incorrectly gives the error:
`Cannot inherit non-frozen dataclass from a frozen one`
- Inheriting a non-frozen dataclass from a frozen one gives the error:
`Cannot inherit frozen dataclass from a non-frozen one`
This PR swaps these two error messages and rephrases them for better clarity.

Fix swapped errors for frozen/non-frozen dataclass inheritance

---

mypy/dmypy/client.py
mypy/fastparse.py
mypy/main.py

Fixes #17706 
Handles recursion error during parse of too complex expressions, differentiates from internal recursion errors by attempting to unparse the ast. If builtin ast.unparse fails, then the error is ignored. Otherwise, re-raises.

Allow deeper recursion in mypy daemon, better error reporting

---

docs/source/command_line.rst

Fixes #18760
This documentation change basically clarifies strict's behavior as described in the issue, adding precedence of the strict flag with respect to other error-checking flags

Clarified strict documentation

---

mypy/fastparse.py
test-data/unit/check-fastparse.test

I made the argument explicit and left blocker=True for some ones I didn't check

Make some parse errors non-blocking

---

mypy/checkexpr.py
test-data/unit/check-warnings.test

while working on #18540 (which my original prototype based the code on `warn-redundant-casts`) I noticed the suggestion [here](https://github.com/python/mypy/issues/18540#issuecomment-2615574503) would probably make sense to apply to redundant-cast as well!
I also made sure to include the example from the [original implementation](https://github.com/python/mypy/pull/1705#issue-159944226) just to make sure I wasn't regressing that as well since it seemed related.

use is_same_type when determining if a cast is redundant

---

mypyc/lib-rt/float_ops.c

Followup to #18534
Some more error messages for math functions were changed for Python 3.14, see https://github.com/python/cpython/pull/129497.
Fixes `mypyc/test/test_run.py::TestRun::run-math.test::testMathOps`

Update math error messages for 3.14 (2)

---

mypy/main.py
mypy/options.py
mypyc/build.py
mypyc/doc/dev-intro.md

This can be useful when debugging mypyc issues. For example, you can
manually add some debug prints to the generated C and rerun mypyc
with `--skip-c-gen`. Now mypyc will build the C code again, with your
manual changes included (this assumes everything else is the same as
during the previous run).
I'm not planning to advertise this as an end-user feature.

[mypyc] Add hidden flag to skip the generation of C files

---

mypyc/test-data/run-async.test

[mypyc] Add some async tests

---

mypyc/test-data/run-async.test
mypyc/transform/spill.py

Fix segfault caused by an extra decref related to SetAttr, which steals one of
the operands. Reference count of a stolen op source must not be decremented.
Add some tests that check that we don't leak memory in async functions.

[mypyc] Fix reference count of spilled register in async def

---

mypyc/test-data/run-async.test
mypyc/transform/spill.py

Update spilling transform for async and generator functions to not require a defined attribute bitfield. We now treat temporary spilled values with overlapping error values as always defined. I'm not sure if this would be safe to do for reference counted values, so we only do this in cases where it's clearly fine.

[mypyc] Fix spilling values with overlapping error values

---

mypyc/ir/class_ir.py
mypyc/ir/rtypes.py
mypyc/test-data/run-async.test

This is a pretty tricky feature, so let's document it better.

[mypyc] Add more comments about overlapping error values

---

mypy/subtypes.py
test-data/unit/check-assert-type-fail.test

Fixes #18974. This simply adds a missed branch - we do support `is_subtype(Overload, TypeType)` but not another type order.

Add missing branch for `is_subtype(TypeType, Overload)`

---

mypy/main.py
mypy/options.py
mypy/stubtest.py

I confirmed that this fixes #18744

support for `strict_bytes` in stubtest

---

mypy/checker.py
test-data/unit/check-classes.test
test-data/unit/check-functions.test

This PR enables superclass compatibility checks for untyped methods when `--check-untyped-defs` is set. IMO this behavior is correct as `--check-untyped-defs` is essentially "treat everything as if there were `: Any` annotations on all arguments", hence checking arg count and names is sound.
This PR, however, allows `@override` on classes that have Any fallback as those are often coming from unfollowed imports. This PR started as an attempt to reject `@override` on untyped defs not found in superclass, but I think it's better to just run all compatibility checks if the flag is enabled.

Check superclass compatibility of untyped methods if `--check-untyped-defs` is set

---

mypyc/irbuild/builder.py
mypyc/irbuild/env_class.py
mypyc/irbuild/function.py
mypyc/irbuild/generator.py

The code was pretty hard to follow, since there were many conditional code paths in a very long function that handles both normal functions, nested functions and generators.
Move much of the generator-specific code to a helper function. This required moving some functionality to helper functions to avoid code duplication. Also pass a function as an argument to avoid a dependency cycle.
This is quite a big refactoring, and it's easier to follow by looking at the individual commits in this PR.

[mypyc] Refactor IR building for generator functions

---

mypy/dmypy/client.py
mypy/main.py

https://github.com/python/cpython/pull/132323 added an optional `color` argument to ArgumentParser. As a side effect the help formatters are now called with two new keyword arguments `prefix_chars` and `color`. Add `**kwargs` to the custom `AugmentedHelpFormatter` and pass it through to the super class.

Fix argparse for Python 3.14

---

mypy/dmypy/client.py
mypy/main.py
mypy/stubgen.py
mypy/stubtest.py

Support for colored output was just merged in cpython. Maybe a bit early to add it here already but it doesn't hurt either.
| Current | With color |
| --- | --- |
| <img width="1058" alt="Without color" src="https://github.com/user-attachments/assets/48edae3e-9361-4af0-aff6-7931410bcd2e" /> | <img width="944" alt="With color" src="https://github.com/user-attachments/assets/38e64082-0321-4d36-a5fe-4d59c6eddc31" /> |
The color output can be disable using various environment variables.
https://docs.python.org/3.14/using/cmdline.html#using-on-controlling-color

Enable colored output for argparse help in Python 3.14

---

mypy/checkmember.py
test-data/unit/check-final.test

Allow accessing `__init__` on final classes and when `__init__` is final

---

mypyc/lib-rt/str_ops.c

In debug build of Python 3.13, mypyc fails to build due to `_PyUnicode_CheckConsistency` being moved to internal. Let's include this, but only for Python 3.13 and only for debug builds. Technically, the assert doesn't need to be behind a Py_DEBUG, but just in case...

[mypyc] Add internal import for _PyUnicode_CheckConsistency for py 3.13

---

mypy/modulefinder.py
mypy/test/testpep561.py
test-data/packages/typedpkg_ns_nested/pyproject.toml
test-data/unit/pep561.test

Fixes #19037. See my analysis in #19037 for motivation. As a side note, with this patch the second run behaves as expected (without it mypy tries to reanalyze a lot of modules during the 2nd run, now it only rechecks the inputs with errors).

Do not cache module lookup results that may become invalid in future

---

.github/workflows/test.yml
pyproject.toml
test-requirements.in
test-requirements.txt

This reverts commit 836019a625072665904447e7612ca7c3ada73d62.
Sadly, upgrading setuptools can cause some issues downstream. This is the case with Dropbox's internal codebase. Let's wait a bit longer before upgrading requirements and pyproject.toml file.
CC @JukkaL and @cdce8p

Revert "Update project metadata for PEP 639 (#18821)"

---

mypy/stubtest.py

Hi!
We, in `django-stubs`, have a lot of usages of `@cached_property` decorator that is a part of `django`: https://docs.djangoproject.com/en/5.2/ref/utils/#django.utils.functional.cached_property
All usages of it we have to add to `subtest/allowlist.txt`, which is not great. In typing we reuse `@functools.cached_property` to have all the benefits of its inference: https://github.com/typeddjango/django-stubs/blob/ee8e8b11c37866969ff0406be20591a067dfa983/django-stubs/utils/functional.pyi#L3-L4
But, `stubtest` is not happy with this move: because in runtime objects have `django.utils.functional.cached_property` type and we see the following error:
```
error: django.http.response.HttpResponse.text is inconsistent, cannot reconcile @property on stub with runtime object
Stub: in file …
```

Add special support for `@django.cached_property` needed in `django-stubs`

---

CONTRIBUTING.md
runtests.py

I have added the capacity to run individual tests and files by specifying them to runtests.py, removing the burden of remembering the correct arguments to pytest. I have updated the contributor documentation accordingly.

Add the capacity to run individual tests and test files to runtests.py

---

mypy/main.py

Fixes #15555
This re-adds some rather-innocuous documentation to main about how to write command line flag descriptions, which were on a wiki page that was subsequently destroyed (rendering the link in the comment dead).

Re-add documentation for formatting mypy --help text 

---

misc/perf_compare.py

While working on determining the performance impact of #17875, I discovered misc/perf_compare.py. I extended its functionality slightly, introducing an -r flag to check a foreign repo instead of mypy itself. I also added a --dont-setup flag, to save time on recompiling mypy. I added several helpful printouts: the standard deviations of the samples, a line at the bottom listing the total time taken by the whole benchmarking program. I improved the cli documentation with the docstring, better descriptions, and an epilog reminding you to probably specify master.
As a caveat, I should flag: when running the benchmark on the foreign repo, it typically spits out a lot of errors, presumably because the libraries aren't installed. That makes sense to me, though, and seems fine.
Another caveat …

Add some functionality to misc/perf_compare.py

---

mypy/stubtest.py

The annotations-related ones are due to PEP 649/749. `__classdictcell__` is from PEP 695 (Python 3.12); not 100% sure what changed there.

Fix stubtest tests on 3.14

---

mypy/stubtest.py

This is a cached list of names of slots added by the `copyreg` module.
See https://github.com/typeddjango/django-stubs/pull/2584 for a case of these cropping up in `django-stubs`.

Make stubtest ignore `__slotnames__`

---

mypy/stubgenc.py

Fixes crash in #19031, but the support of `cvar`  in SWIG remains an open question.

Fall back to Incomplete if we are unable to determine the module name

---

mypy/checker.py
test-data/unit/check-final.test

Fixes #19080. There is no point applying our heuristics if the variable is declared Final - it is not reassigned anywhere.

Admit that Final variables are never redefined

---

mypy/main.py
mypy_self_check.ini
test-data/unit/check-flags.test

This is a check that ensures static correctness, so it is useful to have in --strict. Unlike making this the default behavior eventually in 2.0, which we are also planning to do, it can be added to --strict immediately due to --strict having looser backwards-compatibility requirements (or so I interpret --strict's [documentation](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict)). This PR also includes tests, for --strict and also for no flags.

add --strict-bytes to --strict

---

mypy/dmypy/client.py

I still use windows cmd, and the color codes emitted by dmypy do not work on there. instead printing a bunch of codes like ←[37m    ←[39;49;00ms. However, for whatever reason you can fix this simply by calling os.system("") once. (The main mypy program works fine, presumably because it makes an os system call somewhere before it prints.)
I did not write a test of this, as that seems difficult and unnecessary. Instead, I manually tested it, and it worked great.

Update dmypy/client.py:  Enable ANSI color codes for windows cmd

---

mypy/stubgen.py
test-data/unit/stubgen.test

stubgen: Don't generate `Incomplete | None = None` argument annotation

---

mypy/modulefinder.py

If an invalid exclude is used, the error message
```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "C:\Users\wyatt\files\gits\wyattscarpenter\!!! contributory forks\mypy\mypy\__main__.py", line 37, in <module>
console_entry()
File "C:\Users\wyatt\files\gits\wyattscarpenter\!!! contributory forks\mypy\mypy\__main__.py", line 15, in console_entry
main()
File "C:\Users\wyatt\files\gits\wyattscarpenter\!!! contributory forks\mypy\mypy\main.py", line 89, in main
sources, options = process_options(args, stdout=stdout, stderr=stderr, fscache=fscache)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\wyatt\files\gits\wyattscarpenter\!!! contributory …
```

Emit a friendlier warning on invalid exclude regex, instead of a stacktrace

---

mypy/stubdoc.py
mypy/stubgenc.py
mypy/stubutil.py
test-data/pybind11_fixtures/expected_stubs_with_docs/pybind11_fixtures/__init__.pyi
test-data/pybind11_fixtures/expected_stubs_with_docs/pybind11_fixtures/demo.pyi

Prior to this change passing `--include-docstrings`  did not generate docstrings for classes or properties, only functions.   This PR brings c-extensions up to parity with pure-python modules.
I used this feature to generate stubs for this project:  https://github.com/LumaPictures/cg-stubs/blob/master/usd/stubs/pxr/Usd/__init__.pyi

stubgenc: add support for including class and property docstrings

---

mypy/stubgen.py
test-data/unit/stubgen.test

Fixes #17037
add import for types in __exit__ method signature

stubgen: add import for types in __exit__ method signature

---

mypy/plugins/default.py
test-data/unit/check-typeddict.test

Fixes #19130. We already have these checks for `del typed_dict["readonly_notrequired_key"]`, this just aligns `.pop()` logic with that.

Forbid `.pop` of `Readonly` `NotRequired` TypedDict items

---

mypy/join.py
mypy/test/testtypes.py

Fixes #18125
Unhandled cases in `default` seem fairly dangerous

Fix nondeterministic type checking by making join between TypeType and TypeVar commute

---

docs/source/command_line.rst
docs/source/config_file.rst

The feature was introduced in #18727.

Document --allow-redefinition-new

---

mypyc/lib-rt/mypyc_util.h

Fix C compile errors on free-threaded builds. We can't (easily) access the reference count value directly, so always use the C API functions when on a free-threaded build.
Work on mypyc/mypyc#1038.

[mypyc] Fix incref/decref on free-threaded builds

---

mypyc/codegen/emitmodule.py

Split a large function and extract module execution to a new C function in preparation for supporting multi-phase init.
There are no changes in behavior.

[mypyc] Refactor extension module C generation and generated C

---

mypy/join.py
mypy/solve.py
test-data/unit/check-generics.test
test-data/unit/check-recursive-types.test

I thought about doing this in `join_type_list`, but most callers look like they do have some deterministic order.
Fixes #19121 (torchvision case only, haven't looked at xarray)
Fixes #16979 (OP case only, bzoracler case fixed by #18402)

Fix nondeterministic type checking caused by nonassociativity of joins

---

mypy/defaults.py
mypy/modulefinder.py
mypy/nodes.py
mypy/semanal.py
mypy/typeanal.py
mypyc/test-data/run-misc.test
mypyc/test/testutil.py
test-data/unit/check-annotated.test
test-data/unit/check-columns.test
test-data/unit/check-dataclasses.test
test-data/unit/check-errorcodes.test
test-data/unit/check-flags.test
test-data/unit/check-functions.test
test-data/unit/check-functools.test
test-data/unit/check-generic-alias.test
test-data/unit/check-generics.test
test-data/unit/check-lowercase.test
test-data/unit/check-python39.test
test-data/unit/check-type-aliases.test
test-data/unit/check-type-object-type-inference.test
test-data/unit/check-unreachable-code.test
test-data/unit/cmdline.test
test-data/unit/daemon.test
test-data/unit/fine-grained.test
test-data/unit/parse.test

Drop last remaining support for Python 3.8. Support for running with 3.8 was removed in #17492 already. This PR removes the option to use 3.8 with `--python-version` since the type stubs only support 3.9+, see https://github.com/python/mypy/pull/18930.

Drop support for --python-version 3.8

---

docs/source/generics.rst

This PR updates the `generics.rst` documentation to correct a method call in the `Stack` usage example. Previously, the example incorrectly used `.append('x')` on a `Stack[str]` instance, which is not a valid method for the `Stack` class.

Fix example to use correct method of Stack

---

mypy/nodes.py
test-data/unit/check-python310.test

Type objects as enum values are supported at runtime.
Fixes #19151.

Allow enum members to have type objects as values

---

mypyc/codegen/emitmodule.py
mypyc/common.py

Enable multi-phase init when using a free-threaded (no-GIL) CPython build so we can enable proper multihreading.
Work on mypyc/mypyc#1104. Work on mypyc/mypyc#1038.
The implementation is still quite incomplete. We are missing synchronization in various places, so race conditions can cause segfaults. Only single-module compilation units are supported for now.
Here's a toy benchmark I used to check that free threading works and can improve performance:
```
import sys
import threading
import time
def fib(n: int) -> int:
if n <= 1:
return n
else:
return fib(n - 1) + fib(n - 2)
NTHREADS = 6
print(f"Using {NTHREADS} threads")
print(f"{sys._is_gil_enabled()=}")
t0 = time.time()
threads = []
for i in range(NTHREADS):
t = threading.Thread(target=lambda: fib(36))
t.start()
threads.append(t)
for t …
```

[mypyc] Enable partial, unsafe support for free-threading

---

mypy/constraints.py
test-data/unit/check-inference.test

Fixes https://github.com/python/mypy/issues/8829
This case is more common in 1.16 due to some changes in binder, so it would be good to fix it. My fix may be a bit naive, but if `mypy_primer` looks good, I think it should be OK.

Infer constraints eagerly if actual is Any

---

mypy/constraints.py
mypy/nodes.py
mypy/typeops.py
test-data/unit/check-protocols.test

Fixes https://github.com/python/mypy/issues/19184
This fixes an (edge-case) regression introduced in 1.16. Fix is straightforward, only ignore `__call__` if it comes from an _actual_ metaclass.

Tighten metaclass __call__ handling in protocols

---

pyproject.toml
test-data/unit/cmdline.test

Similar to https://github.com/python/mypy/pull/17891 add the classifier for 3.14. The tests all pass and the next release is unlikely to happen before 3.14.0b3. Note though, not all features might be supported just yet.

Add classifier for Python 3.14

---

mypyc/codegen/emitclass.py
mypyc/test-data/run-classes.test

Fixes #19175.
Conditions for generating and invoking `del` method were not consistent. This change generates and invokes native code for `dealloc` and `__del__` if either `generate_full` is `True` or class has a user-defined `__del__` method.

[mypyc] Fixing condition for handling user-defined __del__

---

mypy/checker.py
test-data/unit/check-inference.test

Fixes https://github.com/python/mypy/issues/19213

Fix crash on partial type used as context

---

.github/workflows/mypy_primer.yml

It's too noisy. We added it to benchmark a specific PR

Remove --show-speed-regression in primer

---

mypyc/irbuild/callable_class.py
mypyc/irbuild/env_class.py
mypyc/irbuild/generator.py

Classes used for generators, async functions and nested functions are now final. This may slightly improve performance when using separate compilation.

[mypyc] Make some generated classes implicitly final

---

mypyc/irbuild/prepare.py
mypyc/test-data/commandline.test
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-classes.test

Without the note, it's not clear what's the easiest way forward. Also add a doc link.
Test that subclassing a built-in exception type actually works as suggested by the note.

[mypyc] Add note about using non-native class to subclass built-in types

---

mypy/checker.py
test-data/unit/check-narrowing.test
test-data/unit/check-typeddict.test

Fixes #19221. Instead of trying to use the first (maybe) overload item and erase it, just use the underlying type with Any-filled typevars

Fix type extraction from `isinstance` checks

---

mypy/checker.py
mypy/checkmember.py
mypy/nodes.py
mypy/semanal.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/19224
Note we must add an additional attribute on `OverloadedFuncDef` since decorator expressions are not serialized.

Fix properties with setters after deleters

---

mypy/main.py

Fixes #19251 
Correct url in help message"None and Optional handling" group
Checklist:
```
$ mypy -h
....
None and Optional handling:
Adjust how values of type 'None' are handled. For more context on how mypy handles values of type 'None', see:
https://mypy.readthedocs.io/en/stable/kinds_of_types.html#optional-types-and-the-none-type
...
```

Update Fix help message url for "None and Optional handling" section

---

misc/self_compile_info.py

Patch various things and run setup.py to get compilation targets without compiling anything. This can be useful for setting up a custom way of compiling mypy/mypyc.

Add script that prints compiled files when self compiling

---

mypy/checkexpr.py
mypy/checkmember.py
mypy/types.py
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/5136
Fixes https://github.com/python/mypy/issues/5491
This is a fifth "major" PR toward https://github.com/python/mypy/issues/7724. Although it would be impractical to move all the operator special-casing to `checkmember.py`, this does two things:
* Removes known inconsistencies in operator handling
* Adds a much more complete `has_operator()` helper that can be a starting point for future performance optimizations

Clean-up and move operator access to checkmember.py

---

mypy/checker.py
mypy/checkexpr.py
mypy/errors.py
mypy/messages.py
mypy/plugin.py
mypy/typeanal.py
test-data/unit/check-classes.test
test-data/unit/check-functions.test
test-data/unit/check-narrowing.test
test-data/unit/check-protocols.test
test-data/unit/fine-grained-dataclass-transform.test

Fixes https://github.com/python/mypy/issues/19240
Fixes https://github.com/python/mypy/issues/13517
Fixes https://github.com/python/mypy/issues/17791
Existing de-duplication logic is both complicated and fragile. By specifying a `parent_error` for a note explicitly, we can do everything in a more robust and simple way. In addition, this new argument makes error code matching simpler.

Fix and simplify error de-duplication

---

mypyc/codegen/emitmodule.py

Don't shorten the module name prefixes, so that the names of output files are more predictable. This can help if integrating with build systems, and it arguably also makes it easier to inspect the output manually.
Now the file name could be `__native_pkg___mod.c` instead of `__native_mod.c` for the module `pkg.mod`.

[mypyc] Derive .c file name from full module name if using multi_file

---

mypy/checkexpr.py
test-data/unit/check-inference-context.test

Fixes #12001. Fixes #6898. Fixes #15368. Improves #17790 and #11508.
When encountering `a {and,or} b`, we used to use `a` as primary context for `b` inference. This results in weird errors when `a` and `b` are completely unrelated, and in many cases return type/assignment type context can do much better. Inferring to union should be harmless in most cases, so use union of `a` and current context instead.

Use union of current context and left side for right side narrowing of binary ops

---

docs/source/protocols.rst
mypy/subtypes.py
test-data/unit/check-protocols.test

Ref https://github.com/python/mypy/issues/19274
This is a bit ugly. But I propose to have this "hot-fix" until we have a proper overhaul of instance vs class variables. To be clear: attribute access already works correctly (on both `P` and `Type[P]`), but subtyping returns false because of
```python
elif (IS_CLASSVAR in subflags) != (IS_CLASSVAR in superflags):
return False
```

Handle corner case: protocol vs classvar vs descriptor

---

mypy/checkmember.py
test-data/unit/check-generics.test

This is yet another followup for `checkmember` work.
This handles a niche use case, but it is still used in the wild, and this restores parity between logic for descriptors with `__set__()` and properties with custom setters.

Support properties with generic setters

---

mypy/suggestions.py
test-data/unit/fine-grained-suggest.test

Resolves #18940 
while I feel like just accepting any identity function would be good enough I expanded the check to explicitly allow Callables and Protocol callables

support Callable / callable Protocols in suggest decorator unwarpping

---

mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-dataclasses.test
test-data/unit/check-expressions.test
test-data/unit/check-generics.test
test-data/unit/check-inference-context.test
test-data/unit/check-inference.test
test-data/unit/check-literal.test
test-data/unit/check-overloading.test
test-data/unit/check-parameter-specification.test
test-data/unit/check-plugin-attrs.test
test-data/unit/check-protocols.test
test-data/unit/check-typevar-tuple.test

Fixes #19289
The type argument index currently shown can be wrong if other type arguments were substituted during an earlier pass.
Given:
```python
def foo[T1, T2](
a: T1,
b: T2,
c: Callable[[T2], T2],
) -> tuple[T1, T2]: ...
def bar(y: float) -> float: ...
reveal_type(foo(1, None, bar))  # Expect T1=int, T2=<failed>
```
Before:
```
main.py:9: error: Cannot infer type argument 1 of "foo"  [misc]
main.py:9: note: Revealed type is "tuple[builtins.int, Any]"
```
After:
```
main.py:9: error: Cannot infer type argument to type parameter "T2" of "foo"  [misc]
main.py:9: note: Revealed type is "tuple[builtins.int, Any]"
```

Show name of type variable in "Cannot infer type argument" message

---

mypy/checker.py
mypy/nodes.py
mypy/semanal.py
mypy/suggestions.py
mypy/typeops.py
test-data/unit/fine-grained-suggest.test

Fixes #18964. `__new__` is special - it has `is_static` set in `semanal.py`, but still has first `cls` argument. This PR tells `dmypy suggest` about that.

Fix `dmypy suggest` interaction with `__new__`

---

mypy/typeops.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/9815
Fixes https://github.com/python/mypy/issues/10848
Fixes https://github.com/python/mypy/issues/17781
Also discovered this while working on `checkmember` stuff. Previously, return type of the type object was the class where `__init__()` was defined (if there was an `Any` somewhere in MRO). And since we use return type for attribute access on type objects, it went completely sideways. Fix is simple (we accidentally used `info` instead of `def_info` in one place).

Fix constructor type for subclasses of Any

---

mypy/checker.py
test-data/unit/check-narrowing.test

Fixes https://github.com/python/mypy/issues/10399
This is another smaller cleanup for https://github.com/python/mypy/issues/7724. The current logic as documented  is IMO correct, for attributes (either properties or custom descriptors) with setter type different from getter type, we narrow the attribute type in an assignment if:
* The attribute is "normalizing", i.e. getter type is a subtype of setter type (e.g. `Sequence[Employee]` is normalized to `tuple[Employee, ...]`)
* The given r.h.s. type in the assignment is a subtype of getter type (and thus transitively the setter as well), e.g. `tuple[Manager, ...]` vs `tuple[Employee, ...]` in the example above.
The problem was that this logic was implemented too literally, as a result assignments that didn't satisfy these two rules were …

Re-widen custom properties after narrowing

---

mypy/checker.py
mypy/errors.py
test-data/unit/check-narrowing.test
test-data/unit/check-redefine2.test
test-data/unit/check-union-error-syntax.test

Fixes #19269
This PR refactors the logic implemented in #19118 (which only targeted repeatedly checked loops) and applies it to repeatedly checked finally clauses.
I moved nearly all relevant code to the class `LoopErrorWatcher`, which now has the more general name `IterationErrorWatcher`, to avoid code duplication.  However, one duplication is left, which concerns error reporting.   It would be nice and easy to move this functionality to `IterationErrorWatcher`, too, but this would result in import cycles, and I am unsure if working with `TYPE_CHECKING` and postponed importing is acceptable in such cases (both for Mypy and Mypyc). 
After the refactoring, it should not be much effort to apply the logic to other cases where code sections are analysed iteratively.   However, the only thing …

Improve the handling of "iteration dependent" errors and notes in finally clauses.

---

mypy/stubtest.py

Fixes #19071. I looked through the `open()` calls in the codebase, and only `reports.py` raises some concerns. Stubtest crashes due to this `print` call with incompatible encoding.
I tested this on Linux with `LC_CTYPE=ru_RU.CP1251` (random non-utf8 locale I found in `/usr/share/i18n/SUPPORTED`) and confirmed that `stubtest` crashes without the patch and passes with it.
Using a simple MRE (empty stub file and `A = "╙"` in a file, this symbol is `$'\u2559'`), I got this:
```
error: package.A is not present in stub
Stub: in file /tmp/tmp.Cs4RioNSuR/demo/stub/package/__init__.pyi
MISSING
Runtime: …
```

Support running stubtest in non-UTF8 terminals

---

mypy/checker.py
test-data/unit/check-classes.test

Ignore overload impl when checking __OP__ and __rOP__ compatibility

---

docs/source/generics.rst

This is a very minor fix.
The last comment in this code block:
```
my_circles: list[Circle] = []
add_one(my_circles)     # This may appear safe, but...
my_circles[-1].rotate()  # ...this will fail, since my_circles[0] is now a Shape, not a Circle
```
uses a different index 0 instead of the one used in the code -1. I think these should be same to avoid confusion. I went for 0.

[Documentation] Minor change: Unify indexes in Variance of generic types description

---

misc/perf_compare.py

Reduce default parallelism, since it could require many GBs of RAM. Add --multi-file flag which reduces RAM usage further, but performance might be slightly worse.

Tweaks to perf_compare.py script to reduce RAM usage

---

mypy/checkexpr.py

This speeds up self check by about 1.5% on my computer, according to `perf_compare.py`:
```
...
=== Results ===
master                    4.264s (0.0%) | stdev 0.024s 
HEAD                      4.201s (-1.5%) | stdev 0.030s 
```
I noticed this bottleneck when I was looking at a CPU profile generated using the script from #19322.

Speed up type checking by caching argument inference context

---

mypy/suggestions.py
test-data/unit/fine-grained-suggest.test

Fix incorrect signature suggestion from `dmypy suggest` when type name matches imported module name

---

mypy/typeanal.py
test-data/unit/check-typeguard.test
test-data/unit/check-typeis.test

Fixes #19318
Don't re-analyze `type_is`/`type_guard` if the callable's type was successfully analyzed on a previous semanal pass. After the first successful pass, the return type will have been replaced by `builtins.bool`, so subsequent analysis can't detect `Type{Guard,Is}`.

Fix `TypeGuard`/`TypeIs` being forgotten when semanal defers

---

mypy/subtypes.py
test-data/unit/check-python310.test

In particular, avoid erasing CallableType that represent type objects
Helps with #19159

Avoid erasing type objects when checking runtime cover

---

misc/perf_compare.py
misc/profile_self_check.py

The script compiles mypy and profiles self check using the 'perf' profiler.
Example of how to use this:
```
$ python misc/profile_self_check.py
... [will take several minutes]
CPU profile collected. You can now analyze the profile:
perf report -i mypy.profile.tmpdir/perf.data
```

Add script for profiling self check (Linux only)

---

misc/perf_compare.py

This was mistakenly omitted in the original PR.

Fix C compiler flags in the profile self check script

---

mypy/checkmember.py
mypy/typeops.py

In my original PR I erroneously concluded that attribute access on `TypeVar` would result in `PyObject` attribute access after mypy is compiled, but this is actually no the case. I therefore remove some workarounds (and a bit of unused code).

Remove unnecessary workarounds from bind_self()

---

mypy/checkexpr.py
test-data/unit/check-functions.test

This was discovered in #19294 where an unrelated change produced a weird notice that should not be shown. Current behavior of the added testcase: 
```
main.py:10: error: Argument 1 to "foo" has incompatible type "*list[object]"; expected "P"  [arg-type]
main.py:10: note: "list" is missing following "P" protocol member:
main.py:10: note:     arg
main.py:11: error: Argument 1 to "foo" has incompatible type "**dict[str, object]"; expected "P"  [arg-type]
main.py:11: note: "dict" is missing following "P" protocol member:
main.py:11: note:     arg
```
https://mypy-play.net/?mypy=master&python=3.12&flags=strict&gist=d0228ba7d2802db8ac4457f374ccc148

Do not show protocol compatibility note against unpacked sequence or mapping

---

mypyc/codegen/emit.py
mypyc/codegen/emitclass.py
mypyc/codegen/emitmodule.py
mypyc/ir/class_ir.py
mypyc/irbuild/generator.py
mypyc/lib-rt/mypyc_util.h
mypyc/test-data/run-generators.test

Add support for per-type free "lists" that can cache up to one instance for quick allocation.
If a free list is empty, fall back to regular object allocation.
The per-type free list can be enabled for a class by setting a flag in ClassIR. Currently there is no way for users to control this, and these must be enabled based on heuristics.
Use this free list for generator objects and coroutines, since they are often short-lived.
Use a thread local variable for the free list so that each thread in a free threaded build has a separate free list. This way we need less synchronization, and the free list hit rate is higher for multithreaded workloads.
This speeds up a microbenchmark that performs non-blocking calls of async functions in a loop by about 20%. The impact will become significantly …

[mypyc] Speed up generator allocation by using a per-type freelist

---

mypy/subtypes.py

Speeds up self-check by about 0.6%. The assertion is very hot, and the original version always created a set, which is slow.

Subtype checking micro-optimization

---

mypyc/codegen/emitfunc.py
mypyc/ir/ops.py
mypyc/irbuild/builder.py
mypyc/test/test_emitfunc.py

Also rename `allow_null` to `allow_error_value` to make it clear that this works with non-pointer types such as tuples.

[mypyc] Fix error value check for GetAttr that allows nullable values

---

mypyc/irbuild/callable_class.py
mypyc/irbuild/env_class.py

Often at most one instance is allocated at any given time, so this improves performance quite significantly in common cases. Uses the freelist feature introduced in #19316.
This speeds up self check by about 0.5% (measured 100 samples). Speeds up this microbenchmark that gets close to the maximal benefit by about 90%:
```
def f(x: int) -> int:
def inc(y: int) -> int:
return y + 1
return inc(x)
def bench(n: int) -> None:
for x in range(n):
f(x)
from time import time
bench(1000)
t0 = time()
bench(50 * 1000 * 1000)
print(time() - t0)
```

[mypyc] Use per-type free "lists" for nested functions

---

mypyc/irbuild/ll_builder.py
mypyc/test-data/irbuild-tuple.test

Got rid of unnecessary operations when comparing tuple elements returns a bit primitive.
Example code:
```
def f(x: tuple[float], y: tuple[float]) -> bool:
return x == y
```
IR before:
```
def f(x, y):
x, y :: tuple[float]
r0, r1 :: float
r2 :: bit
r3 :: object
r4 :: i32
r5 :: bit
r6, r7, r8 :: bool
L0:
r0 = x[0]
r1 = y[0]
r2 = r0 == r1
r3 = box(bit, r2)
r4 = PyObject_IsTrue(r3)
r5 = r4 >= 0 :: signed
if not r5 goto L5 (error at f:2) else goto L1 :: bool
L1:
r6 = truncate r4: i32 to builtins.bool
if not r6 goto L2 else goto L3 :: bool
L2:
r7 = 0
goto L4
L3:
r7 = 1
L4:
return r7
L5:
r8 = <error> :: bool
return r8
```
IR after:
```
def f(x, y):
x, y :: tuple[float]
r0, r1 :: float
r2 :: bit
r3 :: bool
L0:
r0 = x[0]
r1 = y[0]
r2 = r0 == r1
if not r2 goto L1 else goto L2 :: bool
L1:
r3 = 0 …
```

[mypyc] Simplify comparison of tuple elements

---

mypyc/test-data/run-strings.test

This is in preparation for adding a faster str equality primitive.

[mypyc] Add tests for string equality

---

mypyc/irbuild/context.py
mypyc/irbuild/generator.py
mypyc/irbuild/nonlocalcontrol.py
mypyc/irbuild/prepare.py
mypyc/irbuild/statement.py
mypyc/lower/misc_ops.py
mypyc/primitives/exc_ops.py

When calling a native async function using `await`, e.g. `await foo()`, avoid raising `StopIteration` to pass the return value, since this is expensive. Instead, pass an extra `PyObject **` argument to the generator helper method and use that to return the return value. This is mostly helpful when there are many calls using await that don't block (e.g. there is a fast path that is usually taken that doesn't block). When awaiting from non-compiled code, the slow path is still taken.
This builds on top of #19376.
This PR makes this microbenchmark about 3x faster, which is about the ideal scenario for this optimization:
```
import asyncio
from time import time
async def inc(x: int) -> int:
return x + 1
async def bench(n: int) -> int:
x = 0
for i in range(n):
x = await inc(x)
return x …
```

[mypyc] Speed up native-to-native calls using await

---

mypyc/irbuild/ll_builder.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/str_ops.c
mypyc/primitives/str_ops.py
mypyc/test-data/irbuild-dict.test
mypyc/test-data/irbuild-str.test
mypyc/test-data/irbuild-unreachable.test

This speeds up self check by ~1.4%.  String equality is one of the top
five most common primitive function calls in self check.
We previously used a string comparison primitive that calculated the
relative order of two strings. Usually we only care about equality,
which we can do quicker since we can fast path using a length check,
for example.
I checked the CPython implementation of string equality in 3.9 (lowest
supported Python version) and 3.13, and both of them had a fast path
based on string object kind, and equality checks overall had the same
semantics.
Current CPython implementation:
https://github.com/python/cpython/blob/main/Objects/stringlib/eq.h
Tests for this were added in #19401.

[mypyc] Add faster primitive for string equality

---

mypyc/irbuild/for_helpers.py
mypyc/irbuild/prepare.py

Call the generator helper method directly instead of calling `PyIter_Next` when calling a native generator from a native function. This way we can avoid raising StopIteration when the generator is exhausted. The approach is similar to what I used to speed up calls using await in #19398. Refer to that PR for a more detailed explanation.
This helps mostly when a generator produces a small number of values, which is quite common.
This PR improves the performance of this microbenchmark, which is a close to the ideal use case, by about 2.6x (now 5.7x faster than interpreted):
```
from typing import Iterator
def foo(x: int) -> Iterator[int]:
for a in range(x):
yield a
def bench(n: int) -> None:
for i in range(n):
for a in foo(1):
pass
from time import time
bench(1000 * 1000)
t0 = time() …
```

[mypyc] Speed up for loop over native generator

---

.github/workflows/mypy_primer.yml

Increases the number of shards by 1 which helps with https://github.com/python/mypy/issues/19403.

More shards for `mypy-primer`

---

mypy/checker.py
mypy/checker_shared.py
mypy/plugins/enums.py

Follow-up after #19352 as requested by @JukkaL

Move `is_defined_in_stub` to shared checker API to break import cycle

---

mypyc/test-data/run-lists.test

Adding back a test for `next` with a list iterator as argument. Previously this test only checked if compilation succeeded so I have removed it in #19416, now it calls the test function and checks the result.

[mypyc] Add back test for next with list iterator

---

mypyc/irbuild/ll_builder.py

I will use these in a follow-up PR. These simplify IR construction a bit. Only the most common operations have helpers for now, but we can add more later if it seems useful.

[mypyc] Add a few native int helper irbuilder methods

---

mypyc/lib-rt/CPy.h
mypyc/lib-rt/list_ops.c

We now generate low-level IR directly instead of calling a primitive function.

[mypyc] Remove the unused CPyList_GetItemUnsafe primitive

---

mypyc/irbuild/builder.py
mypyc/irbuild/for_helpers.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/list_ops.c
mypyc/lib-rt/tuple_ops.c
mypyc/primitives/dict_ops.py
mypyc/primitives/list_ops.py
mypyc/primitives/tuple_ops.py
mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-dict.test
mypyc/test-data/irbuild-generics.test
mypyc/test-data/irbuild-lists.test
mypyc/test-data/irbuild-set.test
mypyc/test-data/irbuild-statements.test
mypyc/test-data/irbuild-tuple.test
mypyc/test-data/lowering-int.test
mypyc/test-data/refcount.test

For example, when iterating over a list, now we use a native integer
for the index (which is not exposed to the user). Previously we used
tagged integers, but in these use cases they provide no real benefit.
This simplifies the IR and should slightly improve performance, as fewer
tagged int to native int conversions are needed.
Multiple ops have to be migrated in one go, as these interact with
each other, and by only changing a subset of them would actually
generate more verbose IR, as a bunch of extra coercions would be
needed.
List of impacted statements:
* For loop over sequence
* Assignment like `x, y = a` for tuple/list rvalue
* Dict iteration
* List comprehension
For example, consider this example:
```
def foo(a: list[int]) -> None:
for x in a:
pass
```
Old generated IR was like …

[mypyc] Use native integers for some sequence indexing operations

---

mypyc/irbuild/for_helpers.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/str_ops.c
mypyc/primitives/str_ops.py
mypyc/test-data/irbuild-tuple.test

Add unsafe list get item primitive. The new primitive just calls the primary get item primitive, but we could later provide an optimized primitive if this turns out to be a performance bottleneck.

[mypyc] Simplify IR generated for "for" loops over strings

---

mypyc/analysis/dataflow.py
mypyc/analysis/ircheck.py
mypyc/analysis/selfleaks.py
mypyc/codegen/emitfunc.py
mypyc/ir/ops.py
mypyc/ir/pprint.py
mypyc/test/test_emitfunc.py
mypyc/transform/ir_transform.py
mypyc/transform/refcount.py

Also add Undef value type that can currently only used as the
operand for SetElement to signify that we are creating a new
value instead of modifying an existing value.
A new struct value can be created by starting with Undef and
setting each element sequentially. Each operation produces a
new struct value, but the temporaries will be optimized away
in the later passes (currently by the C compiler, but we could
do something more clever here in the future).
This is needed to support packed arrays, which are represented
as structs. I extracted this from my packed array branch, and 
it's currently unused outside tests.

[mypyc] Add SetElement op for initializing struct values

---

mypyc/irbuild/specialize.py
mypyc/primitives/bytes_ops.py
mypyc/primitives/dict_ops.py
mypyc/primitives/float_ops.py
mypyc/primitives/int_ops.py
mypyc/primitives/list_ops.py
mypyc/primitives/misc_ops.py
mypyc/primitives/set_ops.py
mypyc/primitives/str_ops.py
mypyc/primitives/tuple_ops.py
mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-i64.test
mypyc/test-data/irbuild-isinstance.test
mypyc/test-data/irbuild-optional.test
mypyc/test-data/run-bools.test
mypyc/test-data/run-bytes.test
mypyc/test-data/run-dicts.test
mypyc/test-data/run-floats.test
mypyc/test-data/run-integers.test
mypyc/test-data/run-sets.test
mypyc/test-data/run-strings.test
mypyc/test-data/run-tuples.test

Follow-up to #19416 adding primitives for `isinstance(obj, type)` where type is built-in.

[mypyc] Add primitives for isinstance of built-in types

---

mypyc/codegen/emitfunc.py
mypyc/ir/ops.py
mypyc/ir/pprint.py
mypyc/irbuild/for_helpers.py
mypyc/irbuild/ll_builder.py
mypyc/lower/list_ops.py
mypyc/test-data/irbuild-classes.test
mypyc/test-data/irbuild-isinstance.test
mypyc/test-data/irbuild-optional.test
mypyc/test-data/irbuild-singledispatch.test
mypyc/test-data/lowering-int.test
mypyc/test-data/refcount.test

Borrowing is a dangerous default. It can only be used in very specific circumstances, so it shouldn't be the default. This is also arguably more consistent with other read ops which don't borrow by default.

[mypyc] Refactor: make LoadMem not borrow by default

---

mypy/checker.py
test-data/unit/check-dataclasses.test

Fixes #19443. This case is too niche (and should be trivially avoidable), so just not crashing should be good enough. The value is indeed redefined, and trying to massage the plugin to move the `X-redefinition` back to `X` in names is not worth the effort IMO.

Prevent a crash when InitVar is redefined with a method in a subclass

---

mypyc/irbuild/main.py
mypyc/irbuild/prepare.py
mypyc/test-data/commandline.test
mypyc/test-data/irbuild-singledispatch.test

Fixes https://github.com/mypyc/mypyc/issues/1118
Added a check for nested `@singledispatch` functions and nested functions registered to `@singledispatch` functions to report an error in mypyc. Currently either of those cases causes mypyc to crash because of the different handling of nested and top-level functions.
Changed to abort the compilation early when these errors are found so that in the transform code we can assume that the singledispatch functions are valid. This means that mypyc might not report as many errors until it quits as before, so I have split the error output test in `commandline.test` into two.

[mypyc] Report error when registering a nested function

---

mypyc/__main__.py
mypyc/build.py
mypyc/codegen/emitmodule.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/misc_ops.c
mypyc/options.py
mypyc/primitives/misc_ops.py
mypyc/transform/log_trace.py

Logging executed ops is useful for performance analysis. For example, we can look for functions which perform many slow operations and try to optimize them. I've already used this successfully to implement several optimizations. A typical optimization that this helps with is replacing a generic Python function call operation with a native call. This has also helped me identify inefficient code generated by mypyc.
Compile using `MYPYC_LOG_TRACE=1 mypyc ...` to enable trace logging. The log will be written to `mypyc_trace.txt`. Roughly 1/1000 of ops of certain kinds (e.g. primitive calls) are logged.
This can also be enabled by passing `log_trace=True` to `mypycify`.
Compared to profiling, this logging data is frequency-oriented instead of CPU time oriented, and it's mostly helpful for …

[mypyc] Optionally log a sampled operation trace to a file

---

misc/perf_compare.py
mypy/subtypes.py
mypy/types.py
test-data/unit/check-generics.test
test-data/unit/check-parameter-specification.test

Our equality implementation is conservative: if two types compare equal, we know for sure they do indeed refer to the same type, and any type is subtype of itself. This saved 0.9% in my local benchmark run.

perf: return from `is_subtype` early

---

mypy/plugins/default.py

Use precalculated set objects in more places.
This is similar to #19385. Some cases were still unoptimized.
I used trace logging (#19457) to identify functions where we were creating many set objects, and I noticed that these were unnecessary.
This is a part of a set of micro-optimizations that improve self check performance by ~5.5%.

Speed up the default plugin

---

mypy/expandtype.py

Specialize a hot for loop for the concrete `tuple` and `list` types. Also add a fast path for empty type arguments.
The approach is similar to what I used in #19459.
This is a part of a set of micro-optimizations that improve self check performance by ~5.5%.

Micro-optimize ExpandTypeVisitor

---

mypy/indirection.py

Specialize iteration for the concrete types `list` and `tuple`, since this is faster than iterating over an abstract iterable in compiled code. Also avoid constructing many temporary lists.
Duplicate some very hot code in the hopes further improving performance slightly, through inlining and possibly also better branch prediction.
The approach is similar to what I used in #19459.
This is a part of a set of micro-optimizations that improve self check performance by ~5.5%.

Micro-optimize type indirection visitor

---

mypy/server/astmerge.py
pyproject.toml

Fixes #19425. That property has no setter so it should safe to exclude. It can raise in inconsistent state that arises when it is not copied last?

Fix "ignored exception in `hasattr`" in dmypy

---

mypy/solve.py
test-data/unit/check-recursive-types.test
test-data/unit/check-typeddict.test

Current version replaces `None` (which indicates "no items") with an empty union (=`Uninhabited`). This breaks inference in some cases.
Fixes #19483.

Retain `None` as constraints bottom if no bottoms were provided

---

mypy/checker.py
test-data/unit/check-python310.test

Fixes #19507
This PR adds a check to prevent reassignment of final variables in a match statement.
Currently, the following passes without an error:
```Python
from typing import Final
FOO: Final = 8
a = 10
match a:
case FOO:
pass
print(FOO)  # FOO is reassigned, prints 10
```
MyPy already checks that the type of FOO isn't changed if used like this. I added a check in the same place that makes sure it's not `Final` either.
Since this tests the match syntax, I put the test where I did. If it's not the appropriate place for it I will move it as instructed :)

Fix #19507 Prevent final reassignment in match case

---

mypyc/codegen/emitmodule.py

When not using separate compilation, the export table is not used. Also, there's actually no simple and safe way to use it without separate compilation, since we'd have to first ensure that the structure of the export table is compatible, as otherwise the order of fields or the types of the fields could be incompatible and cause segfaults and other fun stuff.

[mypyc] Only generate an export table if using separate compilation

---

mypy/checkexpr.py

Fixes https://github.com/python/mypy/issues/14978
This is irrelevant for self-check (and for most code likely), but it is important for numerical code, where it avoids exponential slowdown in formulas involving arrays etc (see e.g. the original issue).
Unless there will be fallout in `mypy_primer` and/or there are objections, I am going to go ahead and merge it.

Use cache for OpExpr

---

mypy/checkexpr.py

Fixes https://github.com/python/mypy/issues/14271
Fixes https://github.com/python/mypy/issues/14636
TBH examples in those issues are already sufficiently fast (probably because of combined effect of fast dict literals, and the fact that there are some lists and/or function calls in that examples, so some caching already kicks in). But this PR will probably make them even faster.
This has ~0 effect on self-check.

Use cache for DictExpr as well

---

mypyc/irbuild/builder.py
mypyc/irbuild/classdef.py
mypyc/irbuild/ll_builder.py
mypyc/lib-rt/CPy.h
mypyc/lib-rt/misc_ops.c
mypyc/lib-rt/mypyc_util.h
mypyc/primitives/misc_ops.py

If they are not immortal, concurrent construction of objects by multiple
threads can cause serious contention due to reference count updates.
Making them immortal is similar to how both user-defined normal Python 
classes and built-in types in free-threaded builds are immortal.
Fix the issue for both native and non-native classes. Dataclasses still have
contention, and they may be harder to fix (this may require a fix in CPython).
This speeds up a few micro-benchmarks that construct instances of classes
in multiple threads by a big factor (5x+).

[mypyc] Make type objects immortal if using free threading

---

mypy/test/testcheck.py
mypy/test/testfscache.py

Both macOS and Windows support using case‐sensitive file systems; this fixes the test suite in those situations.

Explicitly check case‐sensitivity of file system for tests

---

mypy/checker.py
mypy/checker_shared.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/erasetype.py
mypy/fixup.py
mypy/meet.py
mypy/nodes.py
mypy/typeops.py
test-data/unit/check-selftype.test
test-data/unit/check-serialize.test

This contains two related optimizations:
* Simplify deprecation check by removing several `bind_self()` calls and instead restoring callable type definitions in `fixup.py`, and using them during overload item matching.
* Consequently, best effort filtering in `bind_self()` should be not needed anymore, since all non-trivial calls to `bind_self()` are now after `check_self_arg()` calls.
There are also few micro-optimizations I noticed when looking at relevant code. In total this gives around 1% on self-check.
Note: this may be not a no-op in some corner cases. If so, I will adjust overload filtering in `check_self_arg()`.

Optimize bind_self() and deprecation checks

---

.github/ISSUE_TEMPLATE/crash.md

People often forget or don't know how to add syntax highlighting to markdown code blocks (especially for tracebacks!). Let's help them out by pre-filling the template with code blocks that have the right language hints.

Update crash issue template to use syntax highlighting in code blocks

---

mypy/checkexpr.py
mypy/main.py
mypy/options.py

Add internal flag to disable expression cache

---

mypy/test/teststubtest.py

Closes #19509
Bisect show that the issue was fixed by #19297

Add stubtest test for property aliases

---

mypy/stubtest.py
mypy/test/teststubtest.py

In typeshed, there's a few cases of stubs like this:
```python
class _DoesNotExist: ...  # does not exist at runtime
if sys.version_info >= (3, X):
Exists = _DoesNotExist
```
Ideally, it would be nice to mark `_DoesNotExit` as `@type_check_only` to make it clear that this type isn't available at runtime. However, this currently can't be done, because doing so will make stubtest think that `Exists` is also `@type_check_only`, which sets off alarm bells due to `Exists` being available at runtime.
This PR makes it so stubtest doesn't consider `@type_check_only`-status when checking type alias targets, making it possible to mark types like the above as `@type_check_only`.

[stubtest] Allow runtime-existing aliases of types marked as `@type_check_only`

---

docs/source/common_issues.rst

This mostly just copies the verbiage from the release blog post.

[docs] Update common_issues.rst: mention orjson in the Mypy slow section

---

docs/source/common_issues.rst

Previously it was impossible to have these in at run time (more or less), but now you can just import one of them.
Tangential open question I'm curious about: Is there any interest in getting reveal_locals into typing? I've never used it myself, so I have no strong opinions one way or the other, but I'm surprised reveal_type made it in and reveal_locals didn't! I tried to find the history of this decision but gave up.

[docs] Update common_issues.rst: update information about reveal type & locals

---

mypy/fscache.py

This PR should fix the rest of the test failures in https://github.com/python/mypy/pull/19545.
A change to `os.path.relpath` in 3.13 seems to have broken the handling of Windows paths beginning with `\\`. To resolve this issue, we don't split the drive letter off of the path and instead verify the path is on the current drive. If it isn't it will never resolve to the package root because that must be on the same drive as the CWD:
https://github.com/python/mypy/blob/5b03024e829940cf3c3e3d99fc6625f569d02728/mypy/main.py#L1571-L1572
Keeping the drive letter allows relpath to properly generate a relative path and make the tests pass.
I need to investigate if the relpath change is a regression in CPython.

Fix `--package-root` tests for Windows and Python 3.13+

---

mypyc/test-data/driver/driver.py
mypyc/test-data/run-async.test

This is part of fixing the failed tests in https://github.com/python/mypy/pull/19545
The async tests previously used many invocations of `asyncio.run`, which likely caused issues with event loop management. The documentation for `asyncio.run` states:
> This function cannot be called when another asyncio event loop is running in the same thread. ...
> This function should be used as a main entry point for asyncio programs, and should ideally only be called once.
Calling `asyncio.run` multiple times could cause the test processes to hang for strange event loop reasons. This commit converts most test cases to be run in a single event loop managed by the default driver, which is now async aware.
Not all tests could be converted, e.g. the test that runs an async function in a sync context. …

[mypyc] Fix async mypyc tests on Windows

---

mypy/checkexpr.py
test-data/unit/check-typeddict.test

Fixes #19590.
Fixes #14991 (oops, I forgot I have already reported this...).
When a typeddict context does not cover all available options, proceed with checking as usual against the whole context if none of the items matches in full despite being structurally compatible.

Fix dict assignment to a wider context containing an incompatible typeddict of the same shape

---

mypy/checker.py
mypy/fastparse.py
mypy/nodes.py
mypy/semanal.py

A while ago we started stripping function bodies when checking third-party libraries. This PR pushes this idea further:
* Tighten the check in `fastparse.py` to only consider `foo.bar` as possible self attribute definition.
* Do not type-check bodies where we didn't find any `self` attribute _definitions_ during semantic analysis.
* Skip method override checks in third-party libraries.
In total this makes e.g. `mypy -c 'import torch'` ~10% faster. Surprisingly, this also has some visible impact on self-check.

Skip more method bodies in third-party libraries

---

mypy/checker.py
test-data/unit/check-typeguard.test

Fixes #19575 by adding support for TypeGaurd/TypeIs when they are used on methods off of classes which were not saved to a variable.
Solution adapted from copilot answer here and then refined: https://github.com/saulshanabrook/mypy/pull/1

Fix TypeGuard with call on temporary object 

---

mypy/checker.py
mypy/checkmember.py
mypy/fixup.py
mypy/messages.py
mypy/nodes.py
mypy/semanal.py
mypy/types.py
test-data/unit/check-classes.test
test-data/unit/check-dataclasses.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test

Fixes https://github.com/python/mypy/issues/19572
Surprisingly, when working on this I found another inconsistency in how `.definiton` is set. So after all I decided to do some cleanup, now `.definiton` should always point do the `Decortor` if the definition is a decorated function (no matter whether it is a trivial decorator like `@abstractmethod` or `@overload` or a "real" one).

Fix crash on settable property alias

---

mypyc/test-data/run-tuples.test

This might be overkill - I definitely understand if people think so, but I stumbled over this when testing https://github.com/python/mypy/pull/19578. Python doesn't come with the test module by default on Windows if installed through pymanager. Since `test.support.EqualToForwardRef` is used, I figured a clear error message about how to resolve this would be nice.
Another approach would be to just use the pre-3.14 ForwardRef code and not raise an error here. I'm not totally sure which is better.

[mypyc] Provide instructions for resolving missing test module on Windows

---

mypy/checker.py
mypy/checkexpr.py
mypy/semanal.py

This has two things (totalling 1.5% locally, but see caveat below):
* Do not use `@contextmanger` (that is relatively slow) for `local_type_map`, since it appears in multiple hot paths.
* Do not show name suggestions for import errors in third party packages (since those errors are ignored anyway). It calls `difflib` that can be extremely slow with large modules.
Btw the second will probably not affect self-check, although it did affect _my_ self-check, since apparently `pytest` depends on `numpy`. Well, they don't specify it as a package dependency, but https://github.com/pytest-dev/pytest/blob/main/src/_pytest/python_api.py#L17-L18
```python
if TYPE_CHECKING:
from numpy import ndarray
```
(and I have numpy installed in all my environments, LOL)

Two more micro-optimizations

---

mypy/checkexpr.py
test-data/unit/check-deprecated.test

This change is taken from #18682. The new code and the tests are unmodified. I only had to remove two now unnecessary calls of `warn_deprecated` which were introduced after opening #18682.

PEP 702 (@deprecated): handle "combined" overloads

---

mypyc/codegen/emitfunc.py
mypyc/common.py
mypyc/irbuild/builder.py
mypyc/irbuild/env_class.py
mypyc/irbuild/generator.py
mypyc/test-data/run-async.test
mypyc/test-data/run-generators.test

Fixes https://github.com/mypyc/mypyc/issues/1120
`async` functions were recently changed to be represented as generator classes in the IR. Their parameters are represented as attributes in those classes.
There are several methods added to every generator class by the compiler, one of those is called `send`. If there is also a parameter called `send`, mypyc assumes that the method is a property getter/setter and inserts method calls in the generated code for `GetAttr` and `SetAttr` nodes in the IR.
This is incorrect and led to the compilation error in the linked issue because the `send` method of generator classes takes one more argument than a property getter would.
The name clash is fixed by adding a prefix `__mypyc_generator_attribute__` to attribute names derived from parameters, which …

[mypyc] Add prefix to attributes of generator classes

---

mypy/messages.py
mypy/types.py
test-data/unit/check-tuples.test

Here are two things:
* Make `FormalArgument` a native class. We create huge amount of these (as callable subtyping is one of the most common subtype checks), and named tuples creation is significantly slower than native classes.
* Do not call `re.match()` in a code path of `format_type()`. This is relatively slow (as it is a `py_call()`) and it is called in almost every error message. This creates problems for code with many third-party dependencies where these errors are ignored anyway.
FWIW in total these give ~0.5% together (I didn't measure individually, but I guess the most benefit for self-check is from the first one).

Another two micro-optimizations

---

mypyc/transform/log_trace.py

Add these operations to the trace log (note that trace logging is disabled by default):
* Native attribute get/set
* Boxing and unboxing
* Casts
* Incref/decref (including some implicit increfs)
All of these are common operations and can be performance bottlenecks. There are ways to avoid or speed up most of these (possibly through new mypyc features). For example, incref/decref can sometimes be avoided by using borrowing.

[mypyc] Include more operations in the trace log

---

mypy/test/testsolve.py
mypy/test/typefixture.py
mypy/types.py
test-data/unit/check-generic-subtyping.test
test-data/unit/check-inference.test

Fixes #19641, but also reveals a test that was only passing by coincidence. This inference has never worked correctly:
```python
from typing import Mapping, Never
d: dict[Never, Never]
def run() -> Mapping[str, int]:
return d
```
As discussed, I updated the test to expect failure in that case. We should only special-case inline collection literals for that, everything else (including locals) can cause undesired false negatives.
Cc @ilevkivskyi as the original author (#16122)

Include `ambiguous` into `UninhabitedType` identity

---

mypy/semanal.py
test-data/unit/check-classes.test

Unlike other statements, return can be found in lambdas, and so is not immediately followed by another statement to check or EOF. We need to restore the previous value to continue checking it. 
Fixes #19632

Reset to previous statement when leaving `return` in semanal

---

mypy/build.py

This is a hack, but it gives ~30% perf win for `mypy -c 'import torch'` on a warm run. This should not increase memory consumption too much, since we shouldn't create any cyclic garbage during deserialization (we do create some cyclic references, like `TypeInfo` -> `SymbolTable` -> `Instance` -> `TypeInfo`, but those are genuine long-living objects).

Force all deserialized objects to the oldest GC generation

---

mypyc/irbuild/expression.py
mypyc/lib-rt/CPy.h
mypyc/primitives/misc_ops.py
mypyc/test-data/fixtures/ir.py
mypyc/test-data/irbuild-classes.test
mypyc/test-data/irbuild-try.test
mypyc/test-data/run-classes.test

Using `Py_TYPE` avoids a function call. Also specialize `x.__class__` for instances of native classes -- it's treated as equivalent to `type(x)`.  This is not generally possible, so only do it for native instances where we can make more assumptions.

[mypyc] Optimize type(x) and x.__class__

---

mypy/semanal.py
test-data/unit/check-python312.test

Don't expand PEP 695 aliases when checking node fullnames

---

mypy/fastparse.py
mypy/test/testcheck.py
mypy/test/testparse.py
test-data/unit/check-python314.test
test-data/unit/parse-python314.test

Refs #19329
Stopgap until proper support is added

Fail gracefully on unsupported template strings (PEP 750)

---

mypy/stubtest.py
mypy/test/teststubtest.py

This PR fixes the incorrect usage of the word **"argument"** in `stubtest` error messages and replaces it with the correct term **"parameter"**, as requested in issue #16508.  
According to convention:
- **Parameter** → part of the function signature
- **Argument** → actual value passed when calling the function  
Since `stubtest` deals only with *parameters*, this correction improves the accuracy of the error messages.
Fixes #16508
This is my **third contribution** to `python` (one of my previous PRs has already been merged 🎉).  
I am still a beginner, so if there are any problems with this PR, please let me know — I’ll be happy to make the necessary fixes.  
⚠️ I wasn’t able to fully test the changes locally, so I would really appreciate feedback if something needs adjustment.

stubtest: correct "argument" → "parameter" terminology in error messages

---

docs/requirements-docs.txt

Attempt to fix #19726
After #19062, the docs build script attempts to import `mypy.main`, so building the docs now requires all of mypy's base requirements to be present as well.

Include base mypy requirements in docs requirements

---

mypy/checker_shared.py
mypy/checkpattern.py
test-data/unit/check-python310.test

Since the class pattern matches any subclass, it can also be used to check whether the matched object has a specific attribute. Mypy should not emit an error for it.
```py
match m:
case object(foo=_):
m.foo
```
Using `object` for it is recommended in [PEP 635](https://peps.python.org/pep-0635/#history-and-context) and more prominently in the precursor [PEP 622](https://peps.python.org/pep-0622/#class-patterns).

Omit errors for class pattern matches against object

---

mypy/fastparse.py

The ast `ExtSlice` and `Index` classes have been deprecated (and unused) since Python 3.9.
https://docs.python.org/3.9/library/ast.html#ast.AST

Cleanup old ast classes in fastparse

---

mypy/types.py
mypyc/lib-rt/native_internal.c
mypyc/primitives/misc_ops.py
mypyc/test-data/run-classes.test

After looking more at some real data I found that:
* More than 99.9% of all `int`s are between -10 and 117. Values are a bit arbitrary TBH, the idea is that we should include small negative values (for `TypeVarId`s) and still be able to fit them in 1 byte.
* More than 99.9% of strings are shorter that 128 bytes (again the idea is to fit the length into a single byte)
Note there are very few integers that would fit in two bytes currently. This is because we only store line for type alias nodes, and type aliases are usually defined at the top of a module. We can add special case for two bytes later when needed.
We could probably save another byte for long strings and medium integers, but I don't want to have anything fancy that would only affect less than 0.1% cases.
Finally you may notice …

Use more compact cache representation for int and str

---

mypyc/irbuild/ll_builder.py
mypyc/primitives/generic_ops.py

Make the code cleaner. This will also make it easier to implement additional optimizations.
This probably fixes a few bugs as well.

[mypyc] Refactor IR build of equality and unary operators

---

mypyc/codegen/emitfunc.py
mypyc/irbuild/classdef.py
mypyc/irbuild/ll_builder.py
mypyc/test-data/irbuild-basic.test
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-dunders-special.test
mypyc/test-data/run-dunders.test

Avoid the use of `PyObject_Not` if `__eq__` returns a boolean (which is common). Also skip incref on the bool/bit result on 3.12+, since the object is immortal.
This speeds up a microbenchmark that repeatedly does `!=` operations by 20%.

[mypyc] Speed up implicit __ne__ method 

---

mypyc/analysis/attrdefined.py
mypyc/codegen/emitclass.py
mypyc/codegen/emitmodule.py
mypyc/codegen/emitwrapper.py
mypyc/ir/class_ir.py
mypyc/irbuild/expression.py
mypyc/irbuild/prepare.py
mypyc/lib-rt/misc_ops.c
mypyc/test-data/fixtures/ir.py
mypyc/test-data/fixtures/typing-full.pyi
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-classes.test

Fixes #16012 
mypyc ignored custom implementations of `__new__` because, even though a C function representing the method was generated, it was called neither in the type constructor nor in the method assigned to the `tp_new` pointer.
Now if there's a `__new__` method defined for a type, the corresponding function is called in place of the setup function which is responsible for allocating memory for new objects and initializing their attributes to default values.
The setup function is still called when creating instances of the type as calls resolving to `object.__new__()` are transformed to call the setup function. This way, `__new__` can return instances of other types and instances of the type of the class where `__new__` is defined are setup correctly.
There are a couple of …

[mypyc] Use defined __new__ method in tp_new and constructor

---

mypy/build.py
mypy/test/testcheck.py

I am not sure what happens, but for some reason after GC `freeze()`/`unfreeze()` hack https://github.com/python/mypy/pull/19681 was merged, compiled tests are running twice slower (on GH runner, but I also see much smaller but visible slow-down locally). I have two theories:
* The constant overhead we add outweighs the savings when running thousands of tiny builds.
* The 8% of extra memory we use goes over the limit in the runner because we were already very close to it.
In any case, I propose to try disabling this hack in most tests and see if it helps.
cc @JukkaL

Try fixing test times after GC hack

---

mypy/applytype.py
mypy/binder.py
mypy/plugins/common.py
mypy/semanal.py
mypy/semanal_namedtuple.py
mypy/server/aststrip.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py

Several mypy micro-optimizations. Together with batches 2 and 3 these improve self check performance by 1.8%.

Mypy micro-optimizations (batch 1/3)

---

mypy/checker.py
mypy/errors.py
test-data/unit/check-inference-context.test
test-data/unit/pythoneval.test

Fixes https://github.com/python/mypy/issues/16924
Fixes https://github.com/python/mypy/issues/15886
Mypy uses external type context first, this can cause bad type inference in return statements (see example in test case added), usually we recommend a workaround to users like replacing:
```python
return foo(x)
```
with
```python
y = foo(x)
return y
```
But this is a bit ugly, and more importantly we can essentially automatically try this workaround. This is what this PR adds. I checked performance impact, and don't see any (but for some reason noise level on my desktop is much higher now).

Use empty context as fallback for return statements

---

mypy/build.py
mypy/checker.py
mypy/checkexpr.py
mypy/types.py

This uses dedicated secondary type tags to 5 most common instances. I also move the instance cache from `checker.py` to `types.py` so it is easier to share. The latter however requires couple tweaks to not break builtins fixtures in tests (see changes in `build.py` and `checkexpr.py`).
This makes cache another ~20% smaller (so that with this PR FF is 4.5x smaller than JSON), and also this makes `mypy -c 'import torch'` almost 10% faster with warm cache (when one uses `--fixed-format-cache` obviously). I don't see any visible effect on cold cache runs.

Use dedicated tags for most common instances

---

mypy/test/helpers.py
mypyc/codegen/emitclass.py
mypyc/test-data/run-classes.test

Fixes https://github.com/mypyc/mypyc/issues/1127

[mypyc] Fix object finalization

---

mypyc/codegen/emitclass.py
mypyc/irbuild/prepare.py
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-classes.test

It's still unsupported if interpreted subclasses are allowed.

[mypyc] Allow per-class free list to be used with inheritance

---

mypyc/analysis/attrdefined.py

Incorrect processing in detect_undefined_bitmap could cause a ValueError exception in emit_undefined_attr_check.

[mypyc] Fix subclass processing in detect_undefined_bitmap

---

mypy/options.py
test-data/unit/check-incremental.test

Fixes https://github.com/python/mypy/issues/16652
This is minor and straightforward, so I am going to just merge it (assuming everything passes).

Make untyped_calls_exclude invalidate cache

---

mypy/checkexpr.py
mypy/erasetype.py
mypy/fixup.py
mypy/indirection.py
mypy/server/astdiff.py
mypy/server/astmerge.py
mypy/server/deps.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/typetraverser.py
test-data/unit/check-incremental.test
test-data/unit/fine-grained.test

Fixes https://github.com/python/mypy/issues/18087
I started from fixing an incremental crash from `fixup.py`, but then noticed we don't traverse `ParamSpec` prefix in multiple places where we should, so I fixed most of those as well.

Traverse ParamSpec prefix where we should

---

mypy/checker.py
test-data/unit/check-python310.test

Do not report exhaustive-match after deferral

---

mypy/options.py

Fixes a typo `scrict_equality` which meant `strict_equality`. While in there, I also changed a preposition to be more specific.

Update options.py: typo `scrict_equality` and phrasing

---

mypy/build.py
mypyc/test-data/run-multimodule.test
test-data/unit/check-incremental.test

Fixes https://github.com/python/mypy/issues/9554
This is another case where I am surprised id didn't work like this in the first place. Right now the freshness info originates from the dependency itself (like trust me, I am fresh, whatever it means). IMO this doesn't make much sense, instead a dependent should verify whether all dependencies are the same it last seen them. On the surface the idea is simple, but there are couple tricky parts:
* This requires splitting `write_cache()` in two phases: first write all data files in an SCC (or at least serialize them), the write all meta files. I didn't find any elegant way to do the split, but it is probably fine, as we already have this untyped meta JSON in few places.
* I am adding plugin data (used by mypyc separate compilation currently) …

Inverse interface freshness logic

---

mypy/stubtest.py

Fixes #19732
This is a simple check to point users in the right direction when they get errors because their class uses `__new__` but they wrote stubs for `__init__`. I don't feel strongly about the exact wording used here. I also considered "Maybe you meant to define `__new__` instead of `__init__`?".

stubtest: additional guidance on errors when runtime is object.__init__

---

.github/workflows/docs.yml

Part of the documentation is automatically generated from the options definitions in mypy/main.py, so we need to run the docs CI when that file is modified.
This follows up on https://github.com/python/mypy/pull/19727, which itself follows up on https://github.com/python/mypy/pull/19062

Update docs.yml: add mypy/main.py

---

mypy/main.py

This better reflects its external name, "Miscellaneous".
The current CI suffices to check that this code is correct.

Refactor/nit main.py: rename the variable other_group to misc_group

---

mypy/errorcodes.py
mypy/message_registry.py

This completes an in-line todo from 3 years ago relating to a weakness that mypy no longer has (edit: I did not read carefully enough. But I did eventually stumble upon a sufficient workaround for https://github.com/mypyc/mypyc/issues/1142), and removes code with no downside.
There is no need for tests beyond the current CI.

[refactor] Update errorcodes.py: harmonize all of the type annotations

---

mypyc/irbuild/builder.py
mypyc/irbuild/expression.py
mypyc/irbuild/specialize.py
mypyc/irbuild/statement.py
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-classes.test

#19739 introduced support for compiling `__new__` methods in native classes. Native classes differ internally from regular python types which results in `TypeError`s being raised when `object.__new__(cls)` is called when `cls` is a native class.
To avoid making this call, `super().__new__(cls)` is transformed into a call to an internal setup function. I forgot to replicate this for calls to equivalent `object.__new__(cls)` calls so this PR fixes that. This introduced a regression because before my changes, `__new__` methods with `object.__new__(cls)` were effectively ignored at runtime, and after my changes they started raising `TypeError`s.
Note that these calls are left as-is outside of `__new__` methods so it's still possible to trigger the `TypeError` but that is not a regression as …

[mypyc] Transform object.__new__ inside __new__

---

mypy/semanal.py

This has four improvements:
* Skip placeholders, they are not guaranteed to have a correct `fullname`.
* Skip nodes from `builtins`/`typing`, these don't add anything.
* Don't use `rsplit(".")` on variables/functions recursively, always use enclosing class.
* (Most importantly) add missing `maxsplit=1`.
cc @JukkaL

Improve record_imported_symbol()

---

mypy/strconv.py
test-data/unit/semanal-basic.test

to be honest I have no idea what this code does, but I know we need to fix it per advice from @hauntsaninja in #19846

fix: something Shantanu found

---

docs/source/command_line.rst
docs/source/error_code_list.rst
docs/source/mypy_daemon.rst
mypy/traverser.py

This is a grammatical error (at least in American English, which I think this project is written in) because in the relevant sense the verb "allows" is transitive and needs to apply to a noun, not a verb.
More info, if desired:
https://english.stackexchange.com/questions/60271/grammatical-complements-for-allow
https://english.stackexchange.com/questions/85069/is-the-construction-it-allows-to-proper-english
(I don't know of any weighty publications who have taken this question on, so it's just a bunch of speakers, such as myself, opining.)

[docs] Fix a common and harmless grammatical error, 'allows to'

---

mypy-requirements.txt
mypy_self_check.ini
mypyc/lib-rt/setup.py
pyproject.toml
setup.py
test-requirements.txt

Ref https://github.com/mypyc/mypyc/issues/1128
Another step towards making fixed format cache the default one.

Use published version of librt

---

mypyc/irbuild/specialize.py
mypyc/test-data/irbuild-isinstance.test
mypyc/test-data/run-misc.test

This PR specializes isinstance calls where the type argument is a tuple of primitive types.
We can skip tuple creation and the associated refcounting, and daisy-chain the primitive checks with an early exit option at each step.

[mypyc] feat: specialize isinstance for tuple of primitive types

---

mypy/semanal_shared.py
mypy/typeanal.py
test-data/unit/check-python312.test
test-data/unit/check-typevar-tuple.test

Fixes https://github.com/python/mypy/issues/19960
Fix is trivial, we can't use the "assertion" before type checking phase. I also fix missing line/column for union types. I am surprised this didn't cause problems before.
cc @JukkaL

Fix crash on invalid unpack in base class

---

mypy/cache.py

This should not be needed after we switched to `librt` published on PyPI.

Delete native_internal import fallback

---

mypy/checkexpr.py

This PR implements constant folding in `ExpressionChecker.check_str_format_call`

feat: support constant folding in `ExpressionChecker.check_str_format_call` [1/1]

---

mypyc/irbuild/expression.py

This PR attempts to constant fold the divisor value in `try_optimize_int_floor_divide`
I'm not sure any test changes are warranted for a small PR of this nature.

[mypyc] feat: support constant folding in `try_optimize_int_floor_divide` [1/1]

---

mypyc/irbuild/specialize.py

This PR adds support for constant folding inside of `translate_str_format`

[mypyc] feat: support constant folding in `translate_str_format` [1/1]

---

pyproject.toml

`librt` is needed both at build and runtime. It's already part of mypy-requirements.txt.

Add librt as runtime dependency

---

mypy/main.py

It has been around for some time with no issues so far. We can stop calling it experimental so that more people try it before we make it default.

Stop calling fixed format cache experimental

---

mypy/build.py
mypy/config_parser.py
mypy/main.py
mypy/options.py
mypy/test/teststubtest.py
test-data/unit/check-plugin-error-codes.test
test-data/unit/cmdline.test

Mypy has options for enabling or disabling specific error codes. These
work fine, except that it is not possible to enable or disable error
codes from plugins, only mypy's original error codes.
The crux of the issue is that mypy validates and rejects unknown error
codes passed in the options before it loads plugins and learns about the
any error codes that might get registered.
There are many ways to solve this. This commit tries to find a pragmatic
solution where the relevant options parsing is deferred until after
plugin loading. Error code validation in the config parser, where
plugins are not loaded yet, is also skipped entirely, since the error
code options are re-validated later anyway. This means that this commit
introduces a small observable change in behavior when running with …

Support error codes from plugins in options

---

docs/source/common_issues.rst

Updated the docs to replace typing.List with the built‑in generic list (PEP 585). The example would not work if someone copied and pasted it.

[docs] Replace `List` with built‑in `list` (PEP 585)

---

docs/source/stubtest.rst

Also fix markup in several places. It used to be:
Notice the `--` problem.

[stubtest] Improve `allowlist` docs with better example

---

mypyc/irbuild/function.py
mypyc/test-data/fixtures/ir.py
mypyc/test-data/irbuild-classes.test
mypyc/test-data/run-classes.test

The `__setattr__` wrapper that mypyc generates needs to handle deleting attributes as well because `del` statements go through the same `tp_setattro` pointer but with the value argument set to `NULL`.
The wrapper calls `__delattr__` in this case if it's overridden in the native class (or its parent). Handling of dynamic attributes is different without `__dict__` which makes a custom `__delattr__` required if the dynamic attributes are stored in a custom dictionary.
If `__delattr__` is not overridden it calls the implementation of `object.__delattr__` which results in `AttributeError` because there's no `__dict__`.
If it's defined without `__setattr__`, mypyc reports an error. It's possible to support just `__delattr__` but since it shares a slot with `__setattr__`, the wrapper generation …

[mypyc] Support deleting attributes in __setattr__ wrapper

---

mypyc/ir/ops.py

This PR modifies `TupleGet.__init__` to automatically convert negative indexes to positive indexes instead of crashing at the assert
This won't change functionality on its own, since none of the existing calling locations can pass a negative value, but will allow us to pass negative values in https://github.com/python/mypy/pull/19972 so I think we should consider this PR a prerequisite to that one

[mypyc] feat: support negative index in TupleGet op

---

mypyc/lib-rt/setup.py

Two small things here:
* Use `setuptools` extension class.
* Use same optimization levels we use when compiling mypy.

Make lib-rt/setup.py similar to mypyc extensions
