python/mypy

mypy/semanal.py
test-data/unit/check-classes.test

Implements https://github.com/python/mypy/issues/604#issuecomment-348525995.

Make return type implicitly None for type checked __init__ and __init_subclass__

---

README.md
runtests.py

I recently installed Python 3.7, which means that the `py` launcher will use it as default (even though I had installed it for testing...). I have Python 3.6 as the default for executing scripts, and the main development environment I use.
This change will use the Python executable used to run the script, instead of the default Python 3 executable (via `py -3`), if possible, or will fall back to the old behavior if the default to run a script is a Python 2 executable.
@Michael0x2a hopefully this doesn't break anything for you?

Use sys.executable for invoking mypy in runtests if it is Python 3

---

docs/source/duck_type_compatibility.rst

This PR fixes two issues with said code sample:
- The math import was missing.
- The function argument didn't match the variable name used in the function body.
Also made comment spacing consistent.

Fix the code sample on the "Duck type compatibility" docs page

---

mypy/nodes.py

In conjunction with a change that makes mypyc able to directly
generate calls to `__bool__`, this allows us to generate a much more
direct check for truthiness of TypeInfo.

Micro-optimization of TypeInfo.__bool__

---

mypy/subtypes.py
mypy/types.py

Replace the `var_arg` and `kw_arg` attributes with methods in
`CallableType`.  This speeds up type checking slightly and improves memory
use, as we only construct the values as needed.
Subtype checks for callables are now slower, but that's fine since we
construct callables at least 10x as frequently as we perform callable
subtype checks.
Also remove a somewhat expensive assertion.
This seems to give about 2-3% performance improvement on self-check
(not compiled).

Minor Callable optimizations

---

mypy/__main__.py
mypy/fastparse.py
mypy/nodes.py

This implements various small optimizations to make AST conversion
from the typed_ast AST faster in compiled mypy. This makes compiled
mypy about 4% faster on self-check, and it also makes non-compiled
mypy around 1% faster on self-check.
Notable included optimizations:
* Implement visit methods more efficiently. Don't inherit visitors from
`typed_ast` visitor classes.
* Refactor decorated methods away, as they are slow with mypyc.
* Refactor away many non-native attribute lookups.
* Refactor away some nested functions as they are slow with mypyc.
Also removed some dead code.
I'll implement the same optimizations for Python 2 AST conversion once
this PR has been accepted to avoid having to update two PRs based
on review.

Optimize mypy.fastparse (Python 3 only)

---

mypy/modulefinder.py
test-data/unit/check-modules.test

Tentative implementation of PEP 420. Fixes #1645.
Clarification of the implementation:
- `candidate_base_dirs` is a list of `(dir, verify)` tuples, laboriously pre-computed.
- The old code just looped over this list, looking for `dir/<module>`, and if found, it would verify that there were `__init__.py` files in all the right places (except if `verify` is false); the first success would be the hit;
- In PEP 420 mode, if the above approach finds no hits, we do something different for those paths that failed due to `__init__` verification; essentially we narrow down the list of candidate paths by checking for `__init__` files from the top down. Hopefully the last test added clarifies this.

Namespace packages (PEP 420)

---

mypy/options.py

Running tests I noticed a warning about this.

Use a raw string for a regex

---

mypy/build.py

This seems to speed up compiled mypy by up to about 4%, with marginal
changes to memory use.

Increase the GC threshold 3x

---

mypy/test/data.py

Fix issue caused by #5459: `.file` was initialized lazily thus reported as empty. The fix is the assignment to `self.file` in the constructor. The field `path` is redundant.
There is no progress indication in the output:
```
mypy/test/testargs.py::ArgSuite::test_coherence PASSED
mypy/test/testargs.py::ArgSuite::test_executable_inference PASSED
mypy/test/testcheck.py::TypeCheckSuite::testEmptyFile <- /Users/elazarg/workspace/mypy/test-data/unit/check-basic.test PASSED
mypy/test/testcheck.py::TypeCheckSuite::testAssignmentAndVarDef <- /Users/elazarg/workspace/mypy/test-data/unit/check-basic.test PASSED
```
Additionally
* Renamed `path` consistently to `file`. I would prefer the former, but `.file` is used by unit tests.
* Since `parse_test_case` is effectively a setup method, it is more …

Fix verbosity issue in DataDrivenTestCase

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/main.py

Note that #5728 is not fixed by this yet! The behavior is unchanged except it is no longer listed in the `--help` output.
Also add `file=sys.stderr` to a few of the `print()` calls for other deprecated options.
Also mark it deprecated in the docs (but don't delete those docs yet).

Mark --quick-and-dirty as deprecated.

---

mypy/build.py
mypy/dmypy_server.py
mypy/modulefinder.py
mypy/test/testpep561.py

In get_site_packages_dirs() the fscache argument was only used to
check for easy-install.pth, and that check appears to be done only
once.  And compute_search_paths() just passes it to
get_site_packages_dirs().  All this required a few places to create a
throwaway FileSystemCache instance.  It seems simpler to just os
os.path.isfile() and drop the fscache argument.

Remove fscache arg from two functions in modulefinder.py

---

mypy/build.py
test-data/unit/check-incremental.test

This hit me when mypyc was causing crashes after having written out
part of the cache, but subsequent runs would instead infinite loop.

Fix infinite loop on corrupted fine-grained cache

---

docs/source/command_line.rst
docs/source/config_file.rst

Follow-up for #5691. Should be cherry-picked into the release (#5741). Fixes #5757.

Add docs for --namespace-packages

---

mypy/binder.py

This allows the 'unreachable' flag to not need to be accessed via
GetAttr, and for dict operations to be done via dict primitives
(though I'm going to put up a mypyc change soon that makes that second
part always true.)
Amazingly, this gives a ~200ms speedup on self check (like 6%!).

Make Frame stop being a dict subclass

---

runtests.py

This can speed up local test runtimes by 15% to 50%. Also this makes it easier
to rerun only a part of the test suite.
Fixes #5755. 
The same issue may also affect travis and appveyor builds, and this doesn't
address them.

Split runtests.py pytest run into 3 parts to improve parallelization

---

misc/trigger_wheel_build.sh

Also only push the tags, since pushing the changes to master
clutters up the history without accomplishing anything.

Point trigger_wheel_build.sh at the new mypy_mypyc-wheels repo

---

docs/source/final_attrs.rst
docs/source/index.rst

Draft work towards #5598
@JukkaL you can either push directly to this branch or merge this and polish it afterwards.

Draft documentation for final attributes

---

mypy/errors.py
mypy/main.py
mypy/options.py

For using external debugging tools like PyCharm, the most helpful thing
to do on an internal error is to just raise an exception, rather than
printing a stacktrace or dropping to PDB.

 Add option to raise exception on internal errors

---

mypy/modulefinder.py

Tentative fix for #5784.
(An alternative fix would be not to add anything to `self.ns_ancestors` unless `self.options.namespace_packages` is set.)

Avoid "No such file or directory" if module ancestor doesn't exist

---

mypy/checkmember.py
test-data/unit/check-basic.test
test-data/unit/check-python2.test

Resolves #5680.
Sorry, I don't know if I'm doing this right. We started using Mypy about half a year ago, so I thought I'd try to make some small contribution. The comment from @ilevkivskyi made this sound simple enough, and the test passes, but I'm not entirely confident of this. There are no other hacks like this in `checkmember.py`...
Also I have no idea where this test belongs. Seems like a "basic" thing, so I put it in `check-basic.test`. 😅
Thanks!

Special case None.__bool__()

---

mypy/server/deps.py
test-data/unit/deps.test

Only uses of names should be included as logical dependencies.

Don't create logical dependencies when importing names

---

mypy/server/deps.py
test-data/unit/deps-classes.test
test-data/unit/deps.test

This fixes both normal and logical dependencies. We now generate
dependencies from potential target attributes in base classes. Also,
we don't generate logical dependencies based on the type object
in Python 2 style `super()` expressions, since they aren't
relevant.

Fix fine-grained dependencies for super()

---

docs/source/class_basics.rst

This PR fixes #5546.
I have added a section in the class basics documentation with details on when, how and when not to use ClassVar.
cc @ilevkivskyi

 Document ClassVar

---

mypy/server/deps.py
test-data/unit/deps.test

A decorated function used to have a logical dependency to the
definition scope, which didn't make much sense. They are still
required for fine-grained incremental checking.

Remove redundant logical dependencies for decorated functions

---

mypy/semanal_enum.py
test-data/unit/check-incremental.test

This fixes a crash discovered in internal codebases.

Use actual variable name for failed enum calls

---

.travis.yml

Triggering a build of mypy_mypyc wheels for a broken revision is not
actually a big deal, and waiting for the tests before starting to
build the wheels unnecessarily lengthens the critical path to
deploying a new version.

Don't wait for tests before triggering mypyc wheel build

---

mypy/binder.py
mypy/build.py
mypy/dmypy.py
mypy/dmypy_server.py
mypy/nodes.py
mypy/solve.py
mypy/stubgen.py
mypy/test/data.py
mypy/test/testmerge.py
mypy/test/typefixture.py
mypy/util.py
setup.cfg

Flake8 3.6.0 is a bit more strict on some things, so this fixes the complaints and silences W504 (line break after operator) since that is very common in our code (and we seem to silence W503 too).
For an example of what the failing flake8 output looks like, see https://travis-ci.org/python/mypy/jobs/445480219.

Correct lint errors and silence W504

---

docs/source/common_issues.rst

Fixes https://github.com/python/mypy/issues/5667

Document what to do if a class is not generic at runtime

---

mypy/errors.py

Needed to handle https://github.com/python/typeshed/pull/2557

Handle SyntaxError.offset being optional

---

mypy/util.py

Hi - this is a small addition to allow the `--junit-xml` arg to accept a string path as well as a file.
Example:
```
$ mypy file1.py --junit-xml=a.xml
$ mypy file1.py --junit.xml "this/is/a/test.xml"
$ tree this/
this/
└── is
└── a
└── test.xml
2 directories, 1 file
```

Add path expansion for write_junit_xml output argument

---

mypy/server/deps.py
test-data/unit/deps.test

This is mostly a problem with logical dependencies, but fewer redundant
dependencies is a small win in general.
Only common cases are handled. Things like tuple arguments still
generate redundant deps, but these are pretty rare.

Generate fewer redundant fine-grained dependencies for "isinstance"

---

mypy/server/deps.py
test-data/unit/deps.test
test-data/unit/fine-grained-modules.test

Add missing dependency from missing module attribute

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test
test-data/unit/check-incremental.test

Fixes #5681.
This is how the dataclasses module behaves on Python 3.7.0:
% cat test.py
from dataclasses import dataclass
@dataclass
class Mammal:
age: int
@dataclass
class Person(Mammal):
name: str
age: int
@dataclass
class SpecialPerson(Person):
special_factor: float
@dataclass
class ExtraSpecialPerson(SpecialPerson):
age: int
special_factor: float
name: str
print(Person(32, 'John'))
print(SpecialPerson(21, 'John', 0.5))
print(ExtraSpecialPerson(21, 'John', 0.5))
% python test.py
Person(age=32, name='John')
SpecialPerson(age=21, name='John', special_factor=0.5)
ExtraSpecialPerson(age=21, name='John', special_factor=0.5)

Fix dataclass inherited field ordering

---

mypy/interpreted_plugin.py
mypy/plugin.py
mypy/semanal.py
mypy/test/testdiff.py
test-data/unit/check-custom-plugin.test
test-data/unit/diff.test
test-data/unit/plugins/dyn_class.py

Fixes https://github.com/python/mypy/issues/5508
The new hook allows this:
```python
from some_lib import dynamic_base
Base = dynamic_base()
class C(Base):  # No error, the plugin acts and replaces 'Base' with a TypeInfo
...
```
This plugin hook is useful for SQLAlchemy ORM, for user-defined constructs similar to `namedtuple()`, and maybe we can even re-implement `namedtuple()` as a plugin at some point.
Here are some comments:
* I don't add `basic_new_typeinfo()` to semantic analyzer API, because it is hard to find a signature that would satisfy all possible use cases. Instead I add just `add_symbol_table_node()` and `qualified_name()`, so that a user can construct `TypeInfo` manually and add it to the symbol table. We can reconsider this when we will have more experience with this hook, …

Add plugin hook for dynamic class definition

---

mypy/plugin.py

(as suggested on Gitter by @ilevkivskyi)
This allows plugins to behave differently based on options like the Python version.

Add options attribute to all plugin APIs

---

mypy/build.py
mypy/dmypy_server.py
mypy/test/testcheck.py
mypy/test/testgraph.py
test-data/unit/check-incremental.test

Fixes https://github.com/python/mypy/issues/3592
This invalidates _all_ cache files if at least one plugin changes its `__version__` or hash of its content (this will not catch situations when there are changes in modules imported by a plugin, _and_ version is also imported, but such situations are probably very rare).
I was not sure where to place the check to invalidate all caches at the same time, so I invalidate them one by one.

Invalidate all cache files if plugins change

---

mypy/report.py
mypy/test/testcmdline.py
test-data/unit/reports.test

Fixes to reports.py -- don't crash on control characters, ensure directories earlier

---

mypy/options.py
test-data/unit/check-incremental.test

https://github.com/python/mypy/pull/5878 added cache invalidation for situations where a plugin version/hash changes but there is even simpler scenario -- if `plugins` option itself change, the cache should be invalidated as well.

Invalidate cache when a plugin is added/removed

---

mypy/semanal.py
test-data/unit/check-modules.test

Fixes #5866
There are two places where `__getattr__` generated `Var`s are created, and somehow in one of them it was given a `MDEF` kind (which caused a crash), although it is a _module_ attribute.

Always set correct kind for module __getattr__

---

mypy/checker.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/5851
This makes descriptor assignments behave more like normal assignments. This includes:
* The same error message as for normal assignment
* Using binder to restrict types (but under a bit more strict condition)
I was not able to refactor all the logic to `checkmember.py`, but this is probably OK. Also this PR can introduce potential unsafety as discussed in the issue, but this is probably not much different from using binder in some other situations.

Make descriptor assignments more like normal assignments

---

mypy/types.py

`if not MYPY` doesn't /really/ work in mypyc (it works for imports,
but not for anything that uses a variable!), and I intend to change it
to work even less.
The hack here doesn't seem to be necessary, so there is no trouble
removing it.
This is, in a funny way, a prereq for #5859, since it is necessary to make mypy work under a not-yet-posted mypyc PR I have written to make platform checks work under mypyc.
I have an alternate patch I could post that instead merges `type_visitor.py` back into `types.py`, but maybe it is useful to keep them separate?

Remove an `if not MYPY` from types.py

---

mypy/stubgen.py

PR #5814 made stubgen try to walk as a module any attribute of a C
of a C extension module of module type. This is too aggressive: mypyc
generated extension modules will often have attributes of module type
from imports that do not correspond to actual modules.
This causes a stubgen test to fail under mypy_mypyc while trying to
import `mypy.errors.os`, since `mypy.errors` imports `os`.
Only walk such a submodule when its `__name__` matches it being a
submodule.

Make stubgen less aggressive about walking C extension modules

---

misc/test_installed_version.sh
mypy/modulefinder.py
mypy/stubgen.py
mypy/test/config.py
mypy/test/data.py
mypy/test/testcmdline.py

The main motivation for all of this is to be able to validate
mypy_mypyc wheels.
Because the tests are an integrated subpackage of mypy, I couldn't
figure out a way to run the tests from the source directory against an
installed mypy, and I was reluctant to do a major overhaul of the
source organization, in part because some other projects take
advantage of some of the test infrastructure (mypyc, sqlalchemy-stubs).
So instead we run the tests from where they get installed with the
package. To support this, we allow overriding where the tests look for
test-data using a `MYPY_TEST_PREFIX` environment variable.

Add hooks for running tests on an installed version of mypy

---

mypy/dmypy.py

This speeds `dmypy status` and `dmypy check` on my test MBP by a
whopping 120ms! (But only about 40ms on my Linux laptop.)

Lazily import write_junit_xml from dmypy

---

mypy/argmap.py
mypy/checkexpr.py
mypy/constraints.py
mypy/test/testinfer.py

Most of these are imported in more than one place (in mypy or
mypyc) so it makes sense to put them in a dedicated module.

 Refactor: Move function argument mapping code to a new module 

---

misc/test_installed_version.sh

`--tmpdir` is a GNUism and a relatively recent one, at that.

Make test_installed_version.sh work on OS X and CentOS 5.

---

mypy/semanal.py
test-data/unit/check-classes.test
test-data/unit/check-functions.test

Fixes #5915.
The root cause were some improper casts when creating the `local_nodes` list. These were easy to fix by adding `isinstance(node, Var)` checks to the list comprehensions.

Fix crash when reveal_locals() encounters a class definition

---

mypy/plugins/ctypes.py
test-data/unit/check-ctypes.test
test-data/unit/fixtures/floatdict_python2.pyi

Fix ctypes plugin trying to look up bytes in Python 2

---

test-data/unit/check-classes.test
test-data/unit/check-enum.test
test-data/unit/check-functions.test
test-data/unit/check-inference.test
test-data/unit/check-isinstance.test
test-data/unit/check-overloading.test
test-data/unit/check-protocols.test
test-data/unit/check-tuples.test
test-data/unit/fine-grained.test
test-data/unit/lib-stub/builtins.pyi
test-data/unit/lib-stub/typing.pyi
test-data/unit/semanal-types.test

This seems to give almost a 4% speedup for the tests that I run most often
(on Linux).

Speed up tests by simplifying test stubs

---

mypy/semanal_typeddict.py
test-data/unit/check-classes.test
test-data/unit/check-typeddict.test
test-data/unit/deps-types.test
test-data/unit/pythoneval.test
test-data/unit/semanal-typeddict.test

The previous fallback mapping item type was join of the value
types, which is unsafe because of structural subtyping.
Fixes #5927.

Change TypedDict fallback to `Mapping[str, object]`

---

mypy/constraints.py
mypy/erasetype.py
mypy/expandtype.py
mypy/fixup.py
mypy/indirection.py
mypy/join.py
mypy/meet.py
mypy/sametypes.py
mypy/server/astdiff.py
mypy/server/astmerge.py
mypy/server/deps.py
mypy/subtypes.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py

This diff adds a 'LiteralType' class to types.py and adds a corresponding stub method to all of the type visitors.
Most of these stub methods just throw a 'NotImplementedError', though I did pencil in a few implementations that looked obvious.
The reason I'm doing this now instead of later is because I want to start by getting these kind of big, gross, multi-file changes out of the way early and try and have any subsequent pull requests be more focused.
I also want to formally confirm that the correct approach here *is* to create a new 'LiteralType' class before I start on the rest of the implementation work. (Other possible approaches would be to tack on some extra attribute to 'Instance', or make 'LiteralType' a subclass of 'Instance'.)
No tests, sorry. My plan is to work on modifying …

Add LiteralType and stub methods to type visitors

---

mypy/stubgen.py

The docstring refers to `--docpath`, but this got changed to `--doc-dir` in 74132b6e08370721c1b1d1986fb8de5c6acec93f.

Fix docstring for stubgen

---

mypy/report.py
test-data/unit/reports.test

Control characters are replaced with question marks, to avoid
outputting invalid XML. However, XML does allow tabs in content,
so make an exception for those.

Preserve tabs when creating XML reports (#5942)

---

mypy/dmypy_server.py

While thinking about what might cause flakes in #5859, I found a race
condition between `dmypy stop` and other `dmypy` commands.
`dmypy stop` will send a response and close the socket before the
status file has been deleted. This means that there is a window in
which the daemon has reported to a client that it has exited but while
a status file still exists. This can result in a number of issues,
including the daemon appearing to be stuck (instead of stopped) to
subsequent commands and also the exiting server deleting the status
file of a subsequently started server.
The fix is to remove the status file in `cmd_stop` before replying to
the request. This ensures that, as far as clients are concerned, the
daemon is exited after a stop command completes.
I tested the bug and the fix by …

Fix a race condition in dmypy

---

docs/source/running_mypy.rst
mypy/build.py
mypy/test/testpep561.py
test-data/unit/check-flags.test
test-data/unit/check-incremental.test
test-data/unit/check-modules.test
test-data/unit/check-python2.test
test-data/unit/check-semanal-error.test
test-data/unit/check-unreachable-code.test
test-data/unit/cmdline.test
test-data/unit/fine-grained-blockers.test
test-data/unit/fine-grained-modules.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test
test-data/unit/semanal-errors.test

This pull request replaces the "Perhaps setting MYPYPATH..." note with a link to https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
It also updates the docs to make that page a little more actionable: it now clearly distinguishes between different scenarios a user might find themselves in and gives concrete steps to try for each case.
It also modifies the docs to suggest that users try searching for or writing their stubs first and try silencing errors second.
Resolves https://github.com/python/mypy/issues/5241.

Stop suggesting MYPYPATH on missing imports

---

mypy/api.py
mypy/dmypy.py

Like the existing "api" for invoking mypy, it is just a thin wrapper
around calling the main function.

Provide an "API" for invoking the daemon

---

mypy/ipc.py

This is to hopefully fix flakes when running tests in slow CI...

Default to wait forever with Windows IPC

---

mypy/argmap.py
mypy/checkexpr.py
mypy/constraints.py
mypy/messages.py
test-data/unit/check-typeddict.test
test-data/unit/check-varargs.test

Expand and type check TypedDict types when used as `**kwargs` in calls.
Also refactored the implementation of checking function arguments and
removed some apparently useless code.
Fixes #5198 and another related issue: type checking calls with multiple
`*args` arguments.

Type check typed dict as caller **kwargs

---

mypy/dmypy.py
test-data/unit/daemon.test

This kills a couple birds with one stone:
1. It fixes an interaction with the new run_dmypy api where
that message winds up as the return code instead of in
stderr.
This additionally fixes a type unsoundness/mypy_mypyc crash
caused by SystemExit.code being typed as int.
2. It allows us to standardize the irregular exit codes of dmypy
as 2.

Switch away from sys.exit(error_msg) in dmypy

---

mypy/errors.py

The wrapper script we use to run mypy at Dropbox will greatly benefit from this -- it will be able to distinguish between a crash and type-checking errors.

Use exit 2 on crash to signal this is no ordinary error

---

runtests.py

The daemon tests run a bit slow with all the overhead of starting/stopping multiple times, so I thought we should classify them as slow.
Feel free to reject this however, it is mostly my opinion and I didn't gather numbers.

Put daemon tests in the slow lane

---

docs/source/class_basics.rst

This contains several changes:
* Move section to a somewhat later location, since this is not a
super essential feature.
* Make ClassVar documentation closer in style to the rest of the docs.
* Simplify example a bit and split it into two examples.
* Mention Python version requirements and `typing_extensions`.
* Add cross-reference when we mention type variables, since they
haven't been introduced yet.

Update documentation of ClassVar

---

docs/source/class_basics.rst

It's a common error to forget to implement an abstract
method, and mypy doesn't immediately generate an error.
Explain this explicitly in the documentation, since this
behavior can be confusing.

Improve documentation of ABCs

---

mypy/types.py

Remove a somewhat expensive assert that doesn't seem very useful.
This probably doesn't result in measurable savings, though.

Micro-optimize Instance.__init__

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
test-data/unit/check-literal.test
test-data/unit/fixtures/ops.pyi

This pull request modifies the 'checkmember' related code to use the LiteralType fallback as appropriate. This lets us use the underlying int, bool, str, etc methods for Literals -- basically, adds support for things like this:
foo: Literal["foobar"]
bar = foo.strip()
reveal_type(bar)  # E: Revealed type of 'builtins.str'
Note: I'm not 100% sure whether or not I've modified all the correct places. I used PyCharm to detect all case where we used TypedDictType's "fallback" field and attempted to add similar code for LiteralType, but I don't think this technique was necessarily foolproof.

Add support for literal fallbacks

---

mypy/checkexpr.py
mypy/types.py
test-data/unit/check-inference-context.test

Mitigates https://github.com/python/mypy/issues/5738 by reverting heuristics for type variable return vs instance type outer context changed in https://github.com/python/mypy/pull/5699. Both versions are kind of unprincipled, but the old one _seems_ to work better in real codebases.
This doesn't touch the core fixes in https://github.com/python/mypy/pull/5699
cc @euresti could you please double check this also fixes your `attr.Factory` use cases?

Mitigate a regression in the external context

---

docs/source/additional_features.rst

Noticed a small typo in the docs, fixed all the occurrences of it
```
$ grep DynamicallyDecoarted docs/ -R | wc -l
0
```

Small documentation typo fix

---

mypy/checkexpr.py
mypy/constraints.py
mypy/join.py
mypy/test/testtypes.py
mypy/typeanal.py
test-data/unit/check-literal.test

This pull request modifies the type checking logic so that literal expressions will have an inferred type of 'Literal' if the context asks for a literal type. That is, it implements support for this:
x: Literal[1] = 1
y = 1
reveal_type(x)  # E: Revealed type is 'Literal[1]'
reveal_type(y)  # E: Revealed type is 'builtins.int'
This pull requests also implements the `visit_literal_type` method in the  `constraints.ConstraintBuilderVisitor` and `join.TypeJoinVisitor` methods. Both visitors are exercised indirectly through the "let's use literal types in collection contexts" code, but only the latter is tested directly: I wasn't really sure how to directly test `ConstraintBuilderVisitor`.
The implementation is simple though -- I'm pretty sure literal types count as a "leaf type" so it's fine …

Make literal exprs have inferred type of 'Literal' based on context

---

mypy/dmypy.py
mypy/dmypy_server.py
mypy/dmypy_util.py
mypy/test/testfinegrained.py

Adds an argument to avoid hardcoding the path to the status file. The intent is to allow for multiple daemons running at the same time with different arguments. This is must for running both py2 and py3 mode during development of straddled code.

[daemon] add --status-file arg to dmypy

---

docs/source/more_types.rst

In particular, they are *not* compatible with any dictionary types.

Document that TypedDicts are compatible with Mapping[str, object]

---

docs/source/more_types.rst

Follow-up to #6011 (this must be merged after it).

Document supported TypedDict operations and methods

---

mypy/checkexpr.py
mypy/checkmember.py

The most important change is passing around a single instance
that replaces a bunch of arguments that got repeatedly passed
around previously. Also remove some redundant arguments.
This change makes it much easier to split long functions (in a
follow-up PR).

Refactor mypy.checkmember

---

mypy/checkexpr.py
mypy/messages.py
mypy/typeanal.py
test-data/unit/check-literal.test
test-data/unit/check-newtype.test
test-data/unit/check-typeddict.test
test-data/unit/lib-stub/typing_extensions.pyi

This pull request checks to make sure we report errors if the user tries using Literal types in invalid places. In particular, this PR...
1. Adds tests to make sure we cannot subclass Literals (mypy already directly supported this)
2. Checks to make sure we cannot use Literals inside `isinstance` and `issubclass` checks
I also wanted to add a check preventing people from attempting to instantiate a Literal (e.g. disallow `Literal[3]()` or `Literal()`), but that might require a little more work and a few changes to `typing_extensions`. (We currently don't raise an error when people try doing things like `Final()`, `Final[int]()` or `Protocol()` either).

Prohibit some illegal uses of Literal

---

mypy/typeanal.py

Mostly preserve the original structure of 
`visit_unbound_type_nonoptional`, but split it into multiple smaller
functions. Also did some other small local changes. There's still
more that can be done but I don't want to make this PR any bigger.

Refactoring: split long function in mypy.typeanal

---

misc/convert-cache.py
mypy/build.py
mypy/main.py
mypy/metastore.py
mypy/options.py
test-data/unit/check-incremental.test
test-data/unit/cmdline.test
test-data/unit/fine-grained-cache-incremental.test

File system operations on OS X are pretty slow, and untarring a large
archive of mypy cache information can get pretty slow. Work around
this by using a sqlite database to store the entire cache in one file.
To do this we introduce a generic interface for storing metadata,
called `MetadataStore`. It presents an essentially key/value
interface. We provide two implementations, one using the existing file
system backing and one using sqlite.
It is enabled with the option `--sqlite-cache`, but is not the default
yet.
I'm not sure what the right thing to do about testing is. I've tested
it with the default changed, and everything passes.

Implement a sqlite-based store for the cache

---

mypy/dmypy_server.py

`STARTUPINFO` does not have a custom `__init__` in Python < 3.7. So instead of passing attributes to it, we set them after initialization.
This has been tested all the way back to 3.4.
Fixes #6046.

Fix dmypy for older Pythons on Windows

---

mypy/semanal.py

This splits `SemanticAnalyzerPass2._visit_overloaded_func_def` into
multiple shorter functions. No behavior is changed, and the original
structure is mostly preserved.
Also do some other minor refactorings, and update comments and
docstrings.

Refactor: split long function in mypy.semanal

---

mypy/meet.py
mypy/test/testtypes.py
test-data/unit/check-literal.test

This pull request implements meets for literal types and adds some corresponding tests.
It also adds a test suite for the `is_same_type` method while we're at it. This test suite also lets you test each type's inherent `__eq__` and `__hash__`, since we do also use those throughout the code (especially for literal types).

Implement meet for literal types; add tests for 'is_same_type'

---

mypy/fscache.py
setup.py

THe main thing is fixing some predictable slash direction bugs
in the --use-mypyc support in setup.py.
There is also a temporary hack to work around a typeshed
involving the provenance of os.stat_result.

Support using mypyc under windows

---

docs/source/extending_mypy.rst
mypy/plugin.py

This adds documentation for the plugin system. To avoid duplication, I add shorter and more basic info to the docs, while adding more technical details to the module/class/method docstrings.
To save time I would propose to make one-two rounds of review here and then polish the docs in subsequent PRs.

Add plugin docs

---

mypy/test/data.py

This allows writing platform-specific test cases, or
two platform-specific variants for a single test case.
A test case with -posix is only run on Linux and macOS, while
tests with a -windows suffix will only be run on Windows.
I want this for a test case I want to add where the output
depends on line ending style. There could be other uses
in the future.

Add support for -posix and -windows test name suffixes

---

mypy/test/testtypes.py

One of the tests of LiteralType does some tests with a float literal,
to "make sure that the semantics are robust against this kind of
thing". Unfortunately, they are not. mypyc raises a TypeError
when the float is passed in.

Remove the test of LiteralType with a float

---

mypy/exprtotype.py
mypy/fastparse.py
test-data/unit/check-literal.test

While testing literal types on our internal codebases, I discovered that the current parsing logic for literal types did not correct handle strings inside literal types. In particular, suppose we have the type `Literal["3"]`. Previously, the parser would attempt to parse `"3"` as a regular type and return a `RawLiteralType(3, "builtins.int")`, which caused the type to ultimately become `Literal[3]`.
This diff modifies the string-handled code to guarantee that a string expression will only ever resolve to an UnboundType or a `RawLiteralType(..., "builtins.str")`.

Fix string parsing errors with literal types

---

mypy/stubgen.py

This PR doesn't make any semantic changes apart from renaming `-p` to `--python-executable` (to match corresponding mypy option name, and avoid confusion with `-p` option in mypy that has very different meaning).

Switch to argparse in stubgen

---

setup.py

This seems to be enough to keep Appveyor from running out of memory
during Windows builds.

Use multi-file mypyc compilation on windows

---

mypy/checkexpr.py
mypy/plugin.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/arg_kinds.py
test-data/unit/plugins/arg_names.py

References https://github.com/python/mypy/issues/5409.

Add arg_names attribute to FunctionContext and MethodContext

---

setup.py
test-requirements.txt

This pull request bumps the minimum allowed version of typed-ast to version 1.1.1. This is mostly so that we can have https://github.com/python/typed_ast/pull/49, which we need to correctly handle Literals containing unicode strings when analyzing Python 2 source code.

Bump typed-ast minimum version to 1.1.1

---

mypy/reachability.py
mypy/semanal.py
test-data/unit/check-unreachable-code.test

- Always short-circuit in the if's expression, instead of only
short-circuiting for "ALWAYS_TRUE/FALSE" constants (e.g. sys.platform
checks) and not "MYPY_TRUE/FALSE" constants (e.g. `MYPY`)
- Make --always-true and --always-false map to ALWAYS_TRUE and
ALWAYS_FALSE, respectively, instead of MYPY_TRUE and MYPY_FALSE.
The only difference between the two is a change in import priority,
but semantically uses of "--always-true" are probably closer to
"this condition should be true at compile time and runtime" than
"this condition should be true at compile time but false at
runtime".
- Fixes #5963

Short-circuit `if` expression for always true/always false vars and MYPY/TYPE_CHECKING

---

mypy/argmap.py

This only does some variable renamings, mainly to make things more 
consistent. We know use actuals/formals instead of caller/callee, as 
the latter look too similar.

Refactor argument mapping

---

mypy/plugins/ctypes.py
test-data/unit/check-ctypes.test

The error was triggered by creating an array of pointers. The stack
trace:
$ pytest -n0 -k testCtypesCharPArrayDoesNotCrash
(...)
data: /Users/kuba/projects/mypy/test-data/unit/check-ctypes.test:83:
SystemExit: 2
---------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------
File "/Users/kuba/.ve37/bin/pytest", line 11, in <module>
sys.exit(main())
File "/Users/kuba/.ve37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 77, in main
return config.hook.pytest_cmdline_main(config=config)
File "/Users/kuba/.ve37/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in …

Fix "Could not find builtin symbol 'NoneType'" in the ctypes plugin

---

docs/source/cheat_sheet.rst
docs/source/cheat_sheet_py3.rst

Fixes https://github.com/python/mypy/issues/5037
Add a paragrah to explain there are 2 ways to make the typechecker
understand that an optional is not `None`: use a if condition or an
`assert`.

Complement cheatsheet for Optionals

---

docs/source/type_inference_and_annotations.rst

mypy==0.650
```
p, q, *rs = 1, 2  # type: int, int, *List[int]
>>> error: syntax error in type comment
```
```
p, q, *rs = 1, 2  # type: int, int, List[int]
>>> error: syntax error in type comment
```

fix: fixed the type annotation in examples

---

mypy/build.py

Without this, the files in the cache map aren't found, and the build becomes O(N^2).

In bazel mode, always use "." as the cache prefix

---

mypy/semanal_pass3.py
test-data/unit/fine-grained.test

Fixes #6032 (first part)
This is a very straightforward fix. I am actually surprised no one found this before (maybe because mypy daemon is not so widely used yet).
In future, it would be great to have a mechanism to avoid such mistakes, by somehow making `refresh_top_level()` to do all the special things `visit_file()` does. I don't have any ideas now, but it probably makes sense to consider this during semantic analyzer refactoring (another possible solution is to avoid any such special things, but this should be clearly documented).

Make `refresh_top_level()` more like `visit_file()` in the third pass

---

mypy/semanal_pass3.py
test-data/unit/fine-grained.test

This PR fixes insufficient traversal of synthetic `TypeInfo`s in fine grained mode.

Second part of #6098

---

mypy/build.py
mypy/defaults.py
mypy/main.py
mypy/report.py
mypy/util.py

Move some imports that aren't always needed to functions bodies. This
speeds up mypy startup by up to 120ms on my laptop (when not compiled). 
Tests are a bit faster as well.

Speed up mypy startup by avoiding imports

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/messages.py
test-data/unit/check-classes.test
test-data/unit/check-selftype.test
test-data/unit/cmdline.test

Consolidate all mypy error messages into one place (`mypy.messages`).  This opens the door to some interesting features, such as adding language localization or a more systematic way of working with error messages, akin to error codes (#2417).  It also helps create more consistent messages.  e.g. it's now more apparent that there are a few outliers that use single quotes around type names.
I'm breaking this up change up into several PRs by module, this is the first and simplest.  Once all are complete, this will address #6116.
It's pretty straight-foward.  The biggest challenge is coming up with good constant names.  Let me know what you think.

Migrate remaining failure messages to mypy.messages (part1: mypy.checker)

---

mypy/checker.py
mypy/subtypes.py
test-data/unit/check-isinstance.test

This fixes a bug left behind by #6114, where too much would get
subtracted out of a union type after an isinstance.
Fixes #6141.

Disable promotions when restricting types in isinstance checks

---

mypy/dmypy_server.py
mypy/ipc.py
mypy/test/testipc.py

* The client-side timeout was only 1ms, which is too short.
* Fix a bug in the transmission of empty messages. Receive interprets
an empty message as representing the end of message, so the server
might close the connection after the first empty message (the data)
is sent.
Fix this by only sending the "end of message" empty message when
the data is empty.
* The second transaction in test_connect_twice does not read from
the server, which can cause server crashes when the server tries
to write. This would emit a traceback but not actually cause the
test to fail. Fix this, and add an assert so it would cause a test
failure.
(However, servers perhaps ought to be robust to this sort of thing!
dmypy_server is not.)
* Clean up and regularize the names of pipes.
The first two issues, I think, …

Fix a handful of Windows IPC and IPC test issues

---

mypy/ipc.py
mypy/test/testipc.py

Make IPCClient's timeout parameter be consistently seconds,
rather than seconds on unix and milliseconds on windows.

Fix IPC timeout incoherence

---

mypy/exprtotype.py
mypy/fastparse.py
mypy/indirection.py
mypy/plugin.py
mypy/semanal.py
mypy/semanal_newtype.py
mypy/semanal_shared.py
mypy/server/astmerge.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-fastparse.test
test-data/unit/check-literal.test
test-data/unit/check-newtype.test
test-data/unit/semanal-errors.test

This pull request improves how we handle error messages with Literal types in three different ways:
1. When the user tries constructing types like `Literal[3 + a]`, we now report an error message that says 'Invalid type: Literal[...] cannot contain arbitrary expressions'.
2. We no longer recommend using Literal[...] when doing `A = NewType('A', 4)` or `T = TypeVar('T', bound=4)`. This resolves https://github.com/python/mypy/issues/5989.
(The former suggestion is a bad one: you can't create a NewType of a Literal[...] type. The latter suggestion is a valid but stupid one: `T = TypeVar('T', bound=Literal[4])` is basically the same thing as `T = Literal[4]`.)
3. When the user tries using complex numbers inside Literals (e.g. `Literal[3j]`), we now report an error message that says 'Parameter …

Improve error messages related to literal types

---

mypy/dmypy.py
mypy/dmypy_server.py
mypy/main.py
mypy/util.py
test-data/unit/daemon.test

`dmypy run` without a target given will cause the daemon to die unexpectedly on calling `mypy.main.process_options` with improper arguments.
This catches the `SystemExit` the argument parser throws and captures `sys.stderr` for the output of the parser. I had to backport redirect_stderr since that is not available in 3.4, but the backport can be removed in a couple of months when we drop support for 3.4.
I'm not entirely sure if passing the way I'm passing the error messages is a good idea or not, but it certainly is better than dying with just `[WinError 233] No process is on the other end of the pipe`.

Fix dmypy run when no target given

---

mypy/dmypy.py
mypy/main.py
mypy/util.py

This makes it easier to recognize which build has errors when errors from different versions or platforms may be displayed in the same UI.
(Alas, we can't do this in dmypy because its check command doesn't know the options passed to the start command.)

Add the specified Python version and platform to junit.xml

---

mypy/fastparse.py
mypy/fastparse2.py

The type of Num.n is `complex`, though it can in practice also be an
`int` or a `float`, and we case on the actual type to determine which
sort of mypy ast node to use.
In #6114, promotions were disabled in `isinstance` checks, which
caused mypy to decide that the `isinstance` checks for int and float
won't match. Fix this by giving the value the type object instead of
complex.
Typeshed *does* actually annotate `n` as `Union[float, int, complex]`,
but mypy simplifies that into `complex`. (It does *not* do this
simplification for local variables with such an annotation; see
issue #6168.)

Fix mypy_mypyc crash caused by "complex" interaction

---

mypy/fastparse.py

This is just a case I missed in #6169.
I'm confident the tests actually got run for this one <_<

Fix another "complex" typed_ast interaction

---

docs/source/final_attrs.rst
docs/source/index.rst
docs/source/literal_types.rst
docs/source/more_types.rst

This pull request adds some documentation on using Literal types.
It focuses mostly on how they can be parameterized, and different ways of declaring variables to be Literal.
These docs deliberately do not mention the "intelligent indexing" feature: we don't yet support intelligently indexing using variables that are declared to be Final, so I think we should leave this feature undocumented for now.
(I'll add in that feature + update the docs once https://github.com/python/mypy/pull/6081 lands.)

Add docs for Literal types

---

mypy/nodes.py

Tested this locally, works for me, but I'm not sure if this assertion is necessary for something else.
Fixes #6108

Allow OverloadedFuncDef to have no items

---

mypy/checkexpr.py
mypy/plugins/common.py
test-data/unit/check-literal.test

This pull request adds support for intelligent indexing with variables declared using an implicit Final. This makes the following code work as expected:
```python
my_tuple: Tuple[int, str, bool]
idx: Final = 1
reveal_type(my_tuple[idx])  # Revealed type should be 'str'
```

Add support for using intelligent indexing with Final-declared variables

---

mypy/checker.py
test-data/unit/check-isinstance.test

This pull request reverts https://github.com/python/mypy/pull/6114 and https://github.com/python/mypy/pull/6142: see https://github.com/python/mypy/issues/6180 for rationale.
In short, the original fix ended up being more disruptive then anticipated: it's modifying str and unicode semantics, and we should put a little more thought into reasoning about that particular case before moving ahead with any fix here.
This should also help unblock the upcoming 0.660 release.

Re-enable promotions in isinstance checks

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/checkstrformat.py
mypy/fastparse.py
mypy/fastparse2.py
mypy/message_registry.py
mypy/messages.py
mypy/plugins/default.py
mypy/semanal.py
mypy/semanal_pass3.py
mypy/typeanal.py

This is the next step toward message filtering (#2417), and a precursor to PR #6152.
By moving constants to their own module we can easily inspect them to get both their name and value, for use within a message filtering system.

Move message constants to mypy.message_registry

---

misc/incremental_checker.py
scripts/find_type.py
test-data/stdlib-samples/3.2/incomplete/urllib/parse.py

Hello,
This is a little patch to fix `DeprecationWarning`s about invalid escape sequence.
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>

Fix all DeprecationWarning: invalid escape sequence

---

mypy/checkexpr.py
mypy/nodes.py
mypy/semanal.py
mypy/semanal_pass1.py
mypy/server/astdiff.py
mypy/strconv.py
mypy/typeanal.py
test-data/unit/semanal-symtable.test

Instead, use a `node` that is a `MypyFile` to distinguish references to
a module.
This arguably makes things a little more consistent.

Refactor: remove MODULE_REF symbol table node kind

---

setup.py

The only thing we technically don't yet support is that in 3.7,
`async` and `await` are always keywords.  But this is at best a false
negative.  Similarly, mypy doesn't change its behavior based on the
presence of `from __future__ import annotations` -- it always
implements the 3.7 behavior for annotations.

Add Python 3.7 Trove classifier

---

mypy/fscache.py
mypy/interpreted_plugin.py
mypy/test/data.py
mypy_bootstrap.ini
mypy_self_check.ini

This diff tightens up mypy's self-check slightly by enabling some of the `--strict` flags that mypy is currently already passing.
I also thought about enabling `--warn-unused-ignores` since there were only four places where we need to delete a `# type: ignore` comment, but ultimately decided against it: I don't want to complicate typeshed contributions (since typeshed's tests run mypy's self-check) and because one of those ignores looked like it was related to weird mypyc shenanigans (the lxml import in mypy/report.py).
I did go ahead and remove the other three `# type: ignores` though.

Enable strictness flags that require no source code changes

---

mypy/build.py
mypy/main.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_enum.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_namedtuple.py
mypy/newsemanal/semanal_newtype.py
mypy/newsemanal/semanal_pass1.py
mypy/newsemanal/semanal_pass3.py
mypy/newsemanal/semanal_shared.py
mypy/newsemanal/semanal_typeddict.py
mypy/newsemanal/typeanal.py
mypy/options.py
mypy/plugin.py
mypy/test/testcheck.py
test-data/unit/check-newsemanal.test

Implement basic deferred nodes functionality and remove most of old 
pass 1 functionality. Also fork `mypy.semanal_shared` since I needed
to tweak the signature of `anal_type` in an incompatible way (there are
not other changes in that module).
A *lot* of things still don't work, including functions and more than two
passes. There are a small number of tests for the new semantic 
analyzer, but I made no attempt at achieving good test coverage yet.
Work towards #6204.

Initial work towards new semantic analyzer

---

mypy/build.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_namedtuple.py
test-data/unit/check-newsemanal.test

Currently additional passes are only performed to resolve
"from import" statements and assignments. This allows
resolving indirect (exported) imports and NewType 
definitions within import cycles.
Add a fixed maximum number of iterations that should always be
enough. If we hit the maximum, it's very likely that the remaining
unbound definitions are impossible to bind, or that there is a
definition cycle.
This also includes some fixes to support importing `typing`
in tests and adds support for `True` and `False` (and a few
other small changes).

New semantic analyzer: Support multiple passes, typing imports

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/plugin.py
test-data/unit/check-newsemanal.test

These respond to some review feedback to
https://github.com/python/mypy/pull/6240.

New semantic analyzer: Various small updates

---

MANIFEST.in

When attempting to build mypy (using mypyc) from the 0.660 source release on PyPI, the install/bdist_wheel steps fail because the source distribution does not include mypy_bootstrap.ini.  This adds the file to the package manifest so that future releases include it for reproducible mypy-mypyc builds from source tarballs.

Include mypy_bootstrap.ini in PyPI packages

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

This adds support for incomplete references in base classes. If something
is incomplete, we don't create a `TypeInfo` yet and defer the current
target.
Most of the changes are related to calculating the relevant information 
needed to decide if we need to defer without mutating the `ClassDef` 
or having a `TypeInfo`.
Some things are not supported yet, such as defining class-based named
tuples or TypedDicts, and metaclasses. Also test coverage is minimal but
I think that this okay since we should be able to switch to using various
existing tests pretty soon.

New semantic analyzer: Support inheritance

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_typeddict.py
test-data/unit/check-newsemanal.test

To support deferrals, we only create a TypeInfo once there
are no incomplete references within the definition. This
required some restructuring.

New semantic analyzer: Support class-based TypedDicts

---

docs/source/extending_mypy.rst
mypy/api.py

Hi,
I was reading the documentation and found this small typo in the code examples.

fix a typo in documentation

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
test-data/unit/check-newsemanal.test

When we can't resolve a definition due to some missing dependencies,
we now don't record any additional definitions of the same name. This
is important since the first definition should always win. This applies
to things like assignments, function definitions, imports and class
definitions (anything that defines a name in the current scope).
Example of where things would go wrong:
```
from m import C  # Assume C can't be resolved yet
class C:  # Could be exposed, even though it's not the first def
pass
```
Star imports are a bit special, since they could define arbitrary names
if the target module is incomplete. We use a special name `*` to
mark this. It disallows the definition of all names.
We don't track the scopes of definitions for simplicity. If definition
of `x` goes wrong, we also …

New semantic analyzer: Fix redefinitions

---

misc/update-mypyc-version.sh
mypyc-requirements.txt

With this in place, we can make mypy_mypyc-wheels use it to determine
the version of mypyc to use.
Also add a script for quickly updating the pinned version of mypyc.

Add a mypyc-requirements file with a pinned version of mypyc

---

mypy/build.py
mypy/server/target.py
mypy/server/update.py
mypy/test/testfinegrained.py
test-data/unit/check-incremental.test
test-data/unit/fine-grained-cache-incremental.test

Currently the fine-grained deps cache file for a module contains all the
fine-grained dependencies *from* the module (that is, those whose
targets are in the module). This has the advantage that producing fine-grained
dependency cache files is nicely localized (just run it on a module), but
the downside that *loading* the fine-grained deps cache is a global operation,
requiring every cache file to be loaded.
To improve daemon performance, we invert this, and have the deps cache file
for a module contain the fine-grained dependencies *to* the module. This
complicates creating the cache files: we need to explicitly sort out triggers
into the appropriate cache file.
This, then, allows us to postpone loading deps cache files until the module
is updated.
Because protocol dependencies now get …

Associate deps cache files with the depended upon module

---

mypy/ipc.py
mypy/test/testipc.py

For some reason the tests didn't capture this, but ReadFile, not GetOverlappedResult returns _winapi.ERROR_MORE_DATA, which means that we would not do another read (instead we would fail an assert). This handles the case where there is more data to be read and correctly peeks then reads the remaining data.
I also increased the size of the test message to make sure we don't miss errors like this in the future, and added more information when assertions fail.

Fixed overlapped I/O when more data needs to be read

---

docs/source/command_line.rst
docs/source/getting_started.rst
docs/source/index.rst
docs/source/running_mypy.rst

This pull request expands our "getting started" docs so they discuss how to use type hints in more detail.
In general, I'm hoping this pull request will accomplish two main things:
1. Give users a better "tour" of the available PEP 484 types.
2. Do a better job of giving users a "heads-up" of common gotchas: for example, how dynamically typed functions aren't type-checked.
Here's a list of specific changes I made:
1. I combined "Installing mypy" and "Running mypy" into one section.
2. I modified the "Function signatures" section to focus more on the distinction between dynamic and static typing: I suspect that's a common tripup new users run into.
I also changed the examples so they'll actually produce a runtime error if you misuse them.
3. I moved the existing text on annotating …

Expand "getting started" docs to discuss type hints in more detail

---

mypy/build.py
mypy/modulefinder.py

In practice, almost all modules can be routed to the correct entry in
the lib_path by looking at just the first component of the module
name.
We take advantage of this by enumerating the contents of all of the
directories on the lib_path and building a map of which entries in
the lib_path could contain each potential top-level module that appears.
The previous cache for find_lib_path_dirs could co-exist with this,
but I removed it for simplicity since it didn't help anymore in my
measurements.
This speeds up module finding in a dmypy cold run on S by 10x.

Optimize find_module by enumerating contents of directories on lib_path

---

mypy/build.py
mypy/checkexpr.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_shared.py
mypy/newsemanal/typeanal.py
mypy/nodes.py
mypy/type_visitor.py
mypy/types.py
mypy/visitor.py
test-data/unit/check-newsemanal.test

This adds the concept of placeholder type (and placeholder `TypeInfo`),
which are types that don't have a complete definition yet. They can be
useful in certain self-referential definition such as this:
```py
class C(Sequence[C]): ...
```
In the above example, we create a placeholder `TypeInfo` for `C`
before analyzing base classes. This allow `C` in `Sequence[C]` to
be bound. Each time there's a reference to a placeholder we defer
the current target so that a proper reference can be created on a
subsequent iteration. Placeholders should not leak semantic 
analysis and will generate an error during type checking.
They aren't that useful yet, but the goal is to eventually expand them
to support general recursive types.
This PR also includes a few additional small updates, including some …

New semantic analyzer: Add placeholder types etc.

---

mypy/checkexpr.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/callable_instance.py

Previously these would be delivered as a function hook for `__call__ of Foo`;
now they are more properly a method hook for `__main__.Foo.__call__`.
Also make sure we call the method signature hook for `__call__` methods.

Fix plugin invocation for `__call__` methods

---

mypy/checkexpr.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/typeanal.py
mypy/nodes.py
mypy/visitor.py
test-data/unit/check-newsemanal.test

This generalizes the concept of placeholder nodes to also cover
assignment statements and imports. Previously they were only
created for class definitions. The main motivation is to prevent 
access to definitions in outer namespaces if there is an 
incomplete definition that should take precedence.
Fixes #6299.
This also does a few other updates:
* During the final iteration, some references to placeholder nodes
generate an error instead of producing placeholder nodes. This
allows the analysis to terminate in certain cases of import
cycles at least.
* Major refactoring of `analyze_name_lvalue`. The motivation is
that some early experiments made the old structure unwieldy,
but the refactoring may not be as important for the final design.
This seems like a code quality improvement so I'm …

New semantic analyzer: generalize placeholders to all symbol nodes

---

pyproject.toml

We run afoul of https://github.com/pypa/pip/issues/6163, which
prevents directly pip installing mypy from a source directory with pip
19.0 (because our setup.py imports from mypy for version number
related reasons).
Once a bugfix for that is out we can probably restore it.

Delete pyproject.toml to work around pip bug

---

setup.py

(The fix is part of https://github.com/python/typed_ast/commit/09a1d9c6fce86251db08eb4bb8fac6f815ace5e0 -- specifically the guards on `i` in front of various `TYPE(CHILD(n, i)) == ...` checks.)

Bump typed-ast requirement to 1.3.1, as 1.3.0 has a rare crash bug

---

docs/source/command_line.rst
docs/source/config_file.rst

Document --allow-redefinition

---

mypy/newsemanal/semanal.py

Refactor analysis of index expressions and make two small changes:
1. Don't skip analysis if the `analyzed` attribute is defined (since there
can be placeholder types that should be fixed).
2. Detect incomplete references when performing ordinary semantic
analysis.
I couldn't find immediately find test cases that would benefit from the 
above changes, but I believe that it makes to make the changes just in case.
Fixes #6298.

New semantic analyzer: clean up index expression analysis

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_namedtuple.py
test-data/unit/check-newsemanal.test

Fixes #6284 
Fixes #6285 
This doesn't add support for recursive definitions, but all the forward reference patterns that are supported in old semantic analyzer, should be also supported.
Some notes:
* I moved one function to `semanal_namedtuple.py`
* I never create new `TypeInfo`s in multi-iteration scenario
* I add a dummy type variable `_NT` to the bodies (otherwise type variable scope breaks), but it is probably fine because names starting with underscores are anyway prohibited in named tuples.

New semantic analyzer: support named tuples

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

Fixes #6293.
I only tested the most common kinds of metaclass definitions for now.
I'll create an issue for `six.with_metaclass` etc.

New semantic analyzer: fix metaclasses

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

For things like `mod.name` use the incompleteness state of `mod`
instead of the current module to determine whether the reference
targets an incomplete namespace.
Also remove some unneeded code that I encountered (MRO check).
Fixes #6326.

New semanatic analyzer: fix incomplete namespace with qualified refs

---

README.md

This pull request makes the "issue tracker" section of the README specify people should ask any questions they have on gitter.
(The initial "Got a question?" section of the README already does this, but it looks like this section was never updated to match.)

Update "issue tracker" section of the README

---

mypy/build.py

Hopefully this seems reasonable.
Fixes #6156

Give better error message (and don't crash) if bad json in the cache

---

docs/source/extending_mypy.rst
mypy/checkmember.py
mypy/plugin.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/attrhook.py
test-data/unit/plugins/attrhook2.py

Whenever we find `__getattr__` or `__getattribute__` on an instance, the getattribute hook is called to give the hook a chance to modify the return type of one of those functions.
Closes #6259, #5910
(Note: Currently there are no tests. I can add them if important.)

Use the get_attribute hook for dynamic classes

---

docs/source/config_file.rst

The rest of the documentation uses `True`/`False`.

Use capitalized boolean values in documentation

---

mypy/bogus_type.py
mypy_bootstrap.ini
mypy_self_check.ini

dmypy currently crashes on windows when compiled with mypyc
(since 0.660; it has *never* worked, I believe).
The root cause here is the abusive use of the platform variable,
which we set to 'mypyc', to tell bogus_type.py that mypyc is being used.
This (obviously) interferes with our platform checks, causing mypyc to
spuriously think code is unreachable, but because of the minutae of
how our platform checks were structured and which files are compiled,
this only breaks things for the windows daemon.
Switch to using always_true/always_false instead of abusing platform.
There is a downside to this fix, though (which is the reason I abused platform in the first place instead of using always_true/always_false): mypy will no longer typecheck *without* its config file, since it needs …

Fix dmypy on windows when compiled with mypyc

---

mypy/dmypy_server.py

When removed the sys.platform hack, the dummy `bool()` in
a unreachable code hack became, itself, unreachable.
And while mypyc is much better about unreachable branches that it used
to be, it still crashes on unreachable parts of conditional
expressions.

Remove a mypyc hack that became a liability

---

mypy/build.py
mypy/main.py
mypy/options.py

When using an externally generated sqlite cache in daemon mode,
we should already trust that the cache is valid, and all the mtime
checks are surprisingly slow. (About 1s on S on my MBP.)
Allow skipping these.
An alternative I considered was to just always skip them when using
a sqlite cache, but I think we'd need to be more careful about
when we commit if we want to guarentee cache integrity.

Add a flag to skip mtime checks on cache files

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_pass3.py
mypy/newsemanal/semanal_shared.py
mypy/newsemanal/typeanal.py

`ImportedName` and `UNBOUND_IMPORTED` aren't used in the new
semantic analyzer.
Fixes #6321.

New semantic analyzer: remove obsolete code

---

test-data/unit/pythoneval.test

This requires another (wrong, of course) addition to the errors in
testNewAnalyzerBasicTypeshed_newsemanal, since there has been a typeshed
change that causes another newsemanal error.
(This is actually the main motivation for this sync, to allow fixing the
typeshed build breakage.)

Sync typeshed (and fix typeshed build breakage)

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/checker.py
mypy/checkexpr.py
mypy/errors.py
mypy/main.py
mypy/meet.py
mypy/messages.py
mypy/options.py
test-data/unit/check-expressions.test
test-data/unit/check-flags.test
test-data/unit/fixtures/async_await.pyi
test-data/unit/fixtures/bool.pyi
test-data/unit/fixtures/bool_py2.pyi
test-data/unit/fixtures/dict.pyi
test-data/unit/fixtures/isinstancelist.pyi
test-data/unit/fixtures/primitives.pyi
test-data/unit/fixtures/typing-full.pyi

Fixes https://github.com/python/mypy/issues/1271
The new per-file flag `--strict-equality` disables equality, identity, and container checks between non-overlapping types. In general the implementation is straightforward. Here are some corner cases I have found:
* `Any` should be always safe.
* Type promotions should be ignored, `b'abc == 'abc'` should be an error.
* Checks like `if x is not None: ...`, are special cased to not be errors if `x` has non-optional type.
* `Optional[str]` and `Optional[bytes]` should be considered non-overlapping for the purpose of this flag.
* For structural containers and custom `__eq__()` (i.e. incompatible with `object.__eq__()`) I suppress the non-overlapping types error, if there is already an error originating from the method call check.
Note that I …

Add flag to prohibit equality checks between non-overlapping checks

---

mypy/build.py
mypy/dmypy.py
mypy/dmypy_server.py
mypy/fswatcher.py
mypy/main.py
mypy/options.py
mypy/test/testdaemon.py
test-data/unit/daemon.test

This has two parts:
* Add an argument to dmypy status (`--fswatcher-dump-file JSONFILE`) that tells the daemon to
write out the state of fswatcher to a file.
* Allow mypy/dmypy to use this information to avoid hashing source
files if the mtime in the cache disagrees with the disk but
the old fswatcher info agrees. (`--quickstart-file JSONFILE`)

Add a mechanism for avoiding hashing sources on daemon start

---

mypy/mixedtraverser.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_typeargs.py
mypy/typetraverser.py
test-data/unit/check-newsemanal.test

This adds a new pass that checks things like `int` being valid in
`C[int]`. We use a new pass since base classes can be incomplete
during semantic analysis, which breaks subtype checks that we 
rely on here.
The implementation abstracts AST traversal into separate classes,
so that the implementation of the pass is relatively simple.
Fixes #6288.

New semantic analyzer: check generic type arguments

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

We now remember the namespaces for comprehensions, since they behave
similarly to nested functions.
Fixes #6360.

New semantic analyzer: support comprehensions

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_shared.py
mypy/newsemanal/typeanal.py
mypy/test/hacks.py
mypy/test/helpers.py
test-data/unit/check-newsemanal.test
test-data/unit/check-type-aliases.test

Fixes https://github.com/python/mypy/issues/6355
This does three non-trivial things:
* Creates placeholder with `becomes_typeinfo=True` if r.h.s. is such a placeholder (i.e. the definition is a potential type alias).
* Defers all `Invalid type` and use of corresponding unbound types until final iteration.
* Moves few tests in newly enabled test file to new semantic analyzer only (those where new behaviour is clearly better).
I added a bunch of new tests for things that was broken, plus some variations (although some of them are trivial, replacing `NameExpr` with `MemberExpr` or `IndexExpr`).
I also verified that this PR fixes the crash in mypy self-check.

New semantic analyzer: fix corner cases in aliases to not ready classes (and other aliases)

---

mypy/newsemanal/semanal.py

There is a mypyc bug where we don't properly support
abstractproperties being implemented by regular attributes
(https://github.com/mypyc/mypyc/issues/531), so avoid that.

Fix mypy-mypyc by making final_iteration a property

---

mypy/build.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_namedtuple.py
mypy/newsemanal/semanal_shared.py
test-data/unit/check-incremental.test

Fixes https://github.com/python/mypy/issues/6413
In my original PR I missed the fact that "broken" named tuples (those where variable name and named tuple name are different) are stored under both names (one to actually access it, and other for (de)serialization).
I also extend the semantic analyzer API, and clean-up/clarify the symbol adding logic a bit.

New semantic analyzer: Fix (de)serialization of broken named tuples

---

mypy/newsemanal/semanal_pass1.py
test-data/unit/check-newsemanal.test
test-data/unit/pythoneval.test

Old semantic analyzer first pass is setting whether an import is a top level one or not. New semantic analyzer reachability pass didn't do this. As a result, this screwed up import priorities, and in turn, ordering of modules within SCCs. This caused many `Cannot determine type of 'foo'` errors since we don't defer module top levels.

New semantic analyzer: Fix import prios

---

mypy/build.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_abstract.py
mypy/newsemanal/semanal_infer.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_pass3.py
mypy/test/hacks.py
test-data/unit/check-abstract.test
test-data/unit/pythoneval.test

This fixes abstract classes by moving determination of abstract
attributes to a new pass that happens between the main semantic
analysis pass and type checking. The new pass is added mostly
to simplify the main semantic analysis pass.
This also adds simple type inference for decorated functions from
the old semantic analysis pass 3. This fixes a test case where
we need access to the signature of an abstract method when type
checking the module top level. Since module top levels can't be
deferred during type checking, the simple type inference is needed 
to remain compatible with the old semantic analyzer.
Fixes #6322.

New semantic analyzer: abstract classes

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/test/hacks.py
test-data/unit/check-newsemanal.test

To semantically analyze conditional function definitions (and function
redefinitions) we add redefinitions to a symbol table with a mangled
name of form `name-redefinition[N]`. This is necessary since 
functions are only analyzed if they can be accessed through a symbol
table.
I checked that this fixes most relevant test cases in 
`check-functions.test`. Using a decorated function in a redefinition
is still not working perfectly. That is also partially implemented in 
the old semantic analyzer. Conditionally defining an overloaded
function is also not supported. I'll create follow-up issues for these
remaining known limitations.
Fixes #6318.

New semantic analyzer: conditional function definitions

---

mypy/newsemanal/semanal.py
mypy/newsemanal/typeanal.py
mypy/test/hacks.py
test-data/unit/check-generics.test
test-data/unit/check-newsemanal.test

Fix #6420 
The fix is straightforward. I don't think this actually requires a separate pass, as it was suggested in the TODO I removed.
I also remove some unused imports and enable `check-generics.test` (without one tricky test).

New semantic analyzer: Fix instances that are type alias targets

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_typeddict.py
mypy/test/hacks.py
test-data/unit/check-typeddict.test
test-data/unit/lib-stub/mypy_extensions.pyi

Fixes https://github.com/python/mypy/issues/6286
There are no tricks, it mostly matches one-to-one the implementation of named tuples. There is however one temporary hack, that we will be able to remove when we merge analyzers. Currently type checker depends on l.h.s pointing to a (redundant) `Var` that is always created by the old analyzer.

New semantic analyzer: support assignment based TypedDict

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

Fixes https://github.com/python/mypy/issues/6434
This makes missing import behave the same way as for old analyzer in situations with multiple iterations.

New semantic analyzer: Fix missing imports

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test
test-data/unit/pythoneval.test

NamedTuple detection was incorrect.
Fixes #6446.

New semantic analyzer: fix class derived from Tuple with __init__

---

mypy/newsemanal/semanal.py
mypy/test/hacks.py
test-data/unit/check-inference.test

I also enable the existing test file with existing tests for this feature. I discovered a bug in `make_name_lvalue_var()` that caused some existing tests to fail, so I fixed it.
I skip three tests (they already have issues). I also updated one test case because the behavior is more consistent in new analyzer (it always shows `Cannot determine type`, while old one shows this error only at global scope).

New semantic analyzer: Support multiple assignments to underscore

---

mypy/newsemanal/semanal_abstract.py
mypy/newsemanal/semanal_classprop.py
mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_pass3.py
mypy/nodes.py
mypy/test/hacks.py

This adds an additional simple pass over all classes that sets
`is_classvar` flags for class variables declared in base classes.
Also refactor to share code used for symbol table iteration.
Fixes #6451.

New semantic analyzer: support class variables

---

test-data/unit/pythoneval.test

As requested from https://github.com/python/typeshed/pull/2810.  Not sure how to sync the typeshed commit if that one isn't merged yet.

Fixing error message to match new typeshed stub

---

mypy/stubdoc.py
mypy/stubgenc.py
mypy/test/teststubgen.py

Few improvements/bugfixes for stub generation from docstrings:
1. Do not generate stubs with improper type names. For now it's just regex check
2. Only generate stubs for methods that have unique argument names
3. Fix missing defaults in stubs generated from docstrings

Improvements to stubs generated from docstrings

---

docs/source/getting_started.rst

There's a minor typo in the "Getting started" page where the switch `--disallow-unchecked-defs` is mentioned, but using this results in an error saying it's an unrecognized argument. I'm just getting started with the project personally, but I believe this should instead be `--disallow-untyped-defs`

getting started guide refers to non-existant switch 

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

Fixes https://github.com/python/mypy/issues/6425
The idea is straightforward (and the same as for assignments), don't store analyzed type if there are incomplete refs encountered.
Daemon support is blocked on this since we depend on reprocessing targets with errors.

New semantic analyzer: Report undefined names in function types

---

mypy/checkmember.py

Bug #3603 strikes again. We've got this workaround in another place or
two.
I have a plan for a less bad workaround involving introducing a `SymbolNodeFuncDef` 
class, but let's stop the bleeding first.

Fix mypyc breakage caused by mypy multiple inheritance bug

---

mypy/checkexpr.py
test-data/unit/check-classes.test
test-data/unit/check-tuples.test
test-data/unit/fixtures/tuple.pyi

Fixes https://github.com/python/mypy/issues/4286
Fixes https://github.com/python/mypy/issues/2509
The fix is straightforward, map the indexing through union types. I decided to use the existing error message mentioning the full type. IMO `Value of type "Union[int, List[int]]" is not indexable` is better than `Value of type "int" is not idexable`.

Support indexing unions containing tuples

---

mypy/checkmember.py
mypy/nodes.py
mypy/plugins/common.py

A mypy bug (#3603) causes mypy to think that SymbolNodes cannot be
FuncBases, which causes mypy-mypyc to crash in code that tests
that.
Currently we work around this in a couple gross ways (like turning the
SymbolNode into Any). Work around it instead by testing directly
against a tuple of the subtypes instead of FuncBase itself.
This is the better fix promised in #6480.

Add a SYMBOL_FUNCBASE_TYPES constant to avoid multiple-inheritance bug

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py

Keep track of added names. If an iteration didn't add anything new, 
any further work is meaningless and the next iteration will be the last
one.
Avoid infinite loops by failing if the final iterations defers anything.
Fixes #6485.
Note that this doesn't deal with normal placeholder being changed
into a typeinfo placeholder, since it wasn't needed for any tests.
I can fix this if we can come up with a test case.

New semantic analyzer: remove the limit on max number of iterations

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
mypy/nodes.py
mypy/server/aststripnew.py
mypy/server/update.py
test-data/unit/fine-grained.test

This is a follow-up for #6488 
The test I added is already good, because it crashes without the fix. When https://github.com/python/mypy/pull/6500 is merged I will add a check that only necessary targets are processed.

New semantic analyzer: Sync aststrip with analyze_member_lvalue()

---

mypy/plugin.py
mypy/plugins/dataclasses.py
mypy/semanal.py
mypy/test/hacks.py
test-data/unit/check-custom-plugin.test
test-data/unit/check-dataclasses.test
test-data/unit/check-incremental.test
test-data/unit/deps.test

Fixes https://github.com/python/mypy/issues/6324
This enables two test files that previously had few crashes.
Changes in this PR:
* Add `defer()` to public plugin API, otherwise dataclasses will not works with forward references.
* Update one plugin test to use the new analyzer because the output is a bit more verbose, and probably not worth the hassle of making it identical to old analyzer.
* One test is skipped because of existing issue https://github.com/python/mypy/issues/6454
* Add the generated type variable used for self types to the class body (this is identical to named tuples and `attrs` plugin).

Fix dataclass plugin to work with new semantic analyzer

---

test-data/unit/reports.test

This removes coupling to the exact type annotation of print() in typeshed.
Cf. python/typeshed#2848

Use custom function instead of print() in tests

---

mypy/build.py
mypy/fixup.py

--quick is long dead but the machinery was reused for initial daemon
cache loads.  Update names and comments accordingly.

Remove references to quick_and_dirty in fixup.py

---

mypy/nodes.py
mypy/visitor.py

This regularizes things some, since Var is not a Statement but is a
Node.  There is still a bunch of jankiness, since a lot of other
non-Statement SymbolNodes are still missing visit methods.

Move visit_var to NodeVisitor (from StatementVisitor)

---

.travis.yml
mypy/fastparse.py
mypy/fastparse2.py
mypy/test/helpers.py
test-data/unit/check-underscores.test
test-data/unit/parse-errors.test
test-data/unit/parse.test
test-data/unit/reports.test
test-data/unit/semanal-classes.test

This required mostly changes to fastparse.py, plus a smattering of other things. The tests still don't all pass, but I believe all remaining errors are due to differences in error messages for `SyntaxError` between typed_ast and Python 3.8's ast (where a bunch of improvements and spelling changes were made, including "can't" -> "cannot").
To test, you need https://github.com/python/cpython/pull/12295 (else it crashes due to `ast.Constant` not having a `kind` field). **UPDATE:** That landed today, March 13.
**UPDATE:** This also requires a typeshed sync to incorporate https://github.com/python/typeshed/pull/2859; I've send a PR to typeshed as https://github.com/python/mypy/pull/6540. **UPDATE^2:** Those have landed.

In Python 3.8, use the stdlib ast instead of typed_ast

---

mypy/fastparse.py

Remove the conditional method definition added in #6539, which mypyc
doesn't support.

Fix mypyc build by removing conditional method definition in fastparse

---

README.md

The playground is quite convenient for quick experimentation and gist sharing. I have been using it sometimes. It makes sense to add a link to README.

Add a mention of mypy playground to README

---

mypy/newsemanal/semanal.py
mypy/test/hacks.py
test-data/unit/check-classes.test
test-data/unit/check-newsemanal.test

Fixes 10 of the 16 errors we have trying to run check-classes.test.
Fixes #6350.

Fix six.with_metaclass in the new semantic analyzer

---

test-data/unit/check-newsemanal.test

The bug open for this says that it doesn't seem to work but as far as
I can tell it seems to.
Add a test calling a forward referenced function that requires a promotion.
Closes #6398.

New semantic analyzer: add a test for int->float promotion

---

test-data/unit/check-newsemanal.test

It seems like they already work fine?
Closes #6291, #6292.

New semantic analyzer: add tests for casts and type application

---

setup.py

The mypy_mypyc-wheels Travis build is currently broken on linux
because of a mypyc bug that is dependent on the order of files passed
to mypyc. I am fixing the bug
(https://github.com/mypyc/mypyc/pull/539), but this was complicated by
files coming out of the file system APIs in an unspecified order.
Sort the targets passed to mypyc so that the mypyc compilation process
is deterministic.
(This I believe will *happen* to fix the mypy_mypyc-wheels build, because "suggestions" comes after "plugin" in the alphabet, but it isn't *really* fixed. I'll also be moving the mypyc pin.)

Sort mypyc_targets in setup.py

---

mypy/checker.py
mypy/exprtotype.py
mypy/semanal.py
mypy/test/teststubgen.py
mypy/types.py

This makes mypy check clean with the proposed --no-implicit-reexports
flag from PR #6562.
Some of the implicit reexports that were depended on were clearly
intended (type_visitor) and so made explicit, while some were clearly
unintended (Optional from mypy.types!) and fixed.
Probably worth landing this whichever way we decide on #6562, but I
think this PR is an argument in favor.

Eliminate implicit reexports

---

mypy/newsemanal/semanal.py
mypy/test/hacks.py
test-data/unit/check-modules.test
test-data/unit/check-newsemanal.test

A bunch of relevant test cases are in check-classes, which we remove
from the blacklist and manually opt out of remaining failures.
Closes #6319.

New semantic analyzer: support __all__

---

mypy/subtypes.py
test-data/unit/check-protocols.test

`NamedTuple` fields are always marked an properties. In certain situations, this causes their type to be determined incorrectly when they hold `Callable`s, resolving to the `Callable`'s return type rather than the `Callable` itself. This prevents that and fixes https://github.com/python/mypy/issues/6575.

Don't resolve Callable NamedTuple fields to their return type

---

mypy/fastparse.py
mypy/fastparse2.py
test-data/unit/check-fastparse.test

This is a hack in fastparse, but allows for the following to pass typechecking:
`x = 1  # type: str  # type: ignore`
This also handles the edge case where there is a `# type: ignore` in a comment, which we don't want to pick up. See the tests for more examples.
Fixes https://github.com/python/mypy/issues/5967

 Allow type ignores after type comments 

---

mypy/fastparse.py
mypy/fastparse2.py

Remove {*ignores} in fastparse, since mypyc does not support it

---

.travis.yml
appveyor.yml

tox 3.8.0 broke something about how we specified dependencies.
I've filed a bug with tox, but let's just pin versions for now.

Pin tox version to 3.7.0

---

misc/download-mypyc-wheels.py
setup.py

This will allow us to distribute compiled packages by default for mypy.
This will require some changes to our dropbox internal infrastructure for using mypy_mypyc wheels but it shouldn't be a big deal.

Produce a distribution named 'mypy' when built in mypyc mode

---

mypy/build.py
mypy/interpreted_plugin.py
mypy/plugin.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/depshook.py

django-stubs needs to be able to add in additional dependencies to
modules and is currently using monkeypatching to do it.
That is 1) not great and 2) breaks under mypyc.
Add a hook to support generating additional dependencies from a plugin.
One thing I'm unsure about with this PR is the handling of priorities. I'm not sure that being able to specify priorities is necessary, but I am reluctant to leave them out of the API and then need to either have two hooks or a breaking change when it turns out that something does need them. The priority constants are all defined in mypy.build, which plugins probably shouldn't be importing, but moving them to a new file seems like overkill for a super marginal plugin use case.
This should allow a fix for …

Add a get_additional_deps hook to Plugin to support django-stubs

---

mypy/newsemanal/semanal_main.py
test-data/unit/check-newsemanal.test

Previously some module dependencies genererated from `from m import *`
went missing, and this could result in crashes when deserialization,
since the target module wasn't serialized yet.
This fixes one incremental mode test case.

New semantic analyzer: store import deps generated during analysis

---

mypy/build.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_pass1.py
mypy/nodes.py
test-data/unit/check-classes.test
test-data/unit/check-incremental.test
test-data/unit/check-modules.test
test-data/unit/fine-grained-modules.test

This is slightly different from how it's implemented in the old
semantic analyzer. We don't try to check the return type, since
we can't generally do this during the initial pass. The approach
used in the old semantic samalyzer is hacky and does not always
work.
Fixes #6314.

New semantic analyzer: support module-level __getattr__

---

mypy/test/hacks.py
test-data/unit/check-functions.test

This changes a false positive to a false negative in the tests, 
which is perhaps a reasonable tradeoff for now.  I filed an 
issue about the false negative (#6610).

New semantic analyzer: enable function tests

---

mypy/checkexpr.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_classprop.py
mypy/newsemanal/semanal_main.py
mypy/test/hacks.py

Set up type promotions after the main semantic analyzer pass to
avoid the need to defer.  This fixes an issue with test stubs,
but the existing approach probably worked with typeshed.
Another benefit of this approach is that things are easier to
reason about, as the main semantic analysis pass is a bit
simpler.
This fixes the `testDivmod` type checker test case.

New semantic analyzer: fix type promotions special cases

---

mypy/lookup.py
mypy/nodes.py
test-data/unit/check-newsemanal.test

We could generate a cross ref to a dummy node from module-level
`__getattr__` which would cause a crash.

New semantic analyzer: fix deserialization crash with module __getattr__

---

mypy/checker.py
mypy/mixedtraverser.py
mypy/newsemanal/semanal.py
mypy/nodes.py
mypy/semanal.py
mypy/semanal_pass1.py
mypy/semanal_pass3.py
mypy/server/aststrip.py
mypy/server/deps.py
mypy/strconv.py
mypy/test/hacks.py
mypy/treetransform.py

Keep the original unanalyzed type around instead of modifying
the type in-place. This fixes a crash.

 New semantic analyzer: fix "with" statement with type annotation

---

mypy/newsemanal/typeanal.py
mypy/test/hacks.py
test-data/unit/check-literal.test

Also fix an issue with extra generated messages when we process
a target more than once due to forward reference within a literal
type.

New semantic analyzer: enable literal type tests

---

mypy/newsemanal/semanal.py
test-data/unit/check-incremental.test

In new semantic analyzer, `qualified_name()` returns a bare name if called inside a top-level (non-method) function. I am not sure for motivation and can't say it is generally wrong. Here is the hot-fix for a case where this is definitely wrong: generated classes.

New semantic analyzer: fix deserialization of generated classes

---

mypy/checkexpr.py
mypy/test/hacks.py
test-data/unit/check-python2.test

Also enable Python 2 tests for the new semantic analyzer.
Type check initial generated assignment statements that are used to
decompose tuples in lambda bodies. They were previously ignored 
during type checking.  
The fix isn't specific to the new semantic analyzer. I suspect that the 
tests for the old semantic analyzer worked accidentally, because the 
Var node was considered ready by default.

 New semantic analyzer: fix tuple args in lambda expressions

---

mypy/newsemanal/semanal.py
test-data/unit/check-fastparse.test
test-data/unit/check-newsemanal.test

Although this looks like an arbitrary exception from general rules, this:
* is an actual pattern used by some libraries
* matches old analyzer in most cases
* matches runtime semantics

New semantic analyzer: allow replacing submodule with a variable

---

mypy/checkexpr.py
test-data/unit/check-expressions.test

This fixes an issue where everything after a lambda was considered
unreachable.

Don't type check lambda return statement

---

mypy/newsemanal/semanal_classprop.py
test-data/unit/check-abstract.test

This matches the behavior in old analyzer, and although a bit arbitrary, this may be actually useful.

New semantic analyzer: consider NewTypes as always non-abstract

---

mypy/test/hacks.py
test-data/unit/check-overloading.test
test-data/unit/check-unions.test

Two tests that trigger crashes are disabled for now.

New semantic analyzer: enable additional tests

---

test-requirements.txt

Some mypyc CI jobs were failing because of an incompatability with new
pytest-xdists and old pytests, so bump the pytest version.
Failures haven't hit mypy CI yet but they probably will?

Update the pytest version dependency

---

docs/source/extending_mypy.rst

* Link to plugin changes announcement issue (#6617)
* Document get_additional_deps()

Add some more plugin docs

---

mypy/stubutil.py

find_module_path_and_all_py3 promises to return `__all__` as a List, but
`__all__` could be a tuple or something. Make sure to convert it.
Fixes #6639.

Fix stubgen mypyc type mismatch

---

.travis.yml
mypy/newsemanal/semanal_main.py
mypy/server/aststripnew.py

Hopefully, some tests will fail

Add tests for new semantic analyzer on older Python

---

mypy/newsemanal/semanal_enum.py
test-data/unit/check-incremental.test

The fix is straightforward: use the already computed full name for enum class (that already takes care about special cases) as a base.

New semantic analyzer: use correct fullnames for enum Vars

---

mypy/checkexpr.py
mypy/checkmember.py
test-data/unit/check-classes.test

Fix __getattr__ and operators related infinite recursion

---

mypy/memprofile.py
mypy/nodes.py
mypy/util.py

memprofile crashes when trying to call isinstance on FakeInfos, since isinstance 
will sometimes try to access `__class__`. Make `__class__` on FakeInfo work.
Also use `get_class_descriptors` instead of traversing `__slots__` directly so that
mypyc objects can be traversed.
(Though some fixes are needed to mypyc for this to work that I haven't pushed yet.)

Fix memprofile crashes and make it work with mypyc

---

mypy/build.py
mypy/checker.py
mypy/checkmember.py
mypy/errors.py
mypy/messages.py
test-data/unit/check-38.test
test-data/unit/check-fastparse.test
test-data/unit/check-flags.test
test-data/unit/check-incremental.test
test-data/unit/check-modules.test
test-data/unit/check-warnings.test
test-data/unit/cmdline.test
test-data/unit/daemon.test
test-data/unit/fine-grained-modules.test

This means that all diagnostics are errors, which maybe have some
notes "attached" to them.
This makes sense, since all diagnostics cause an error exit code.
Fixes #6574.

Turn all warnings and bare notes into errors

---

mypy/types.py
test-data/unit/check-namedtuple.test

Fix crash when namedtuple, classmethod and generic types used

---

docs/source/command_line.rst
mypy/main.py
test-data/unit/cmdline.test

With this change, passing `--config-file=` from the command line disables any active config files.

Allow disabling active config files.

---

mypy/checker.py
test-data/unit/check-isinstance.test
test.py

Fix crash when a star expression is used in isinstance

---

mypy/checker.py
test-data/unit/check-classes.test
test-data/unit/check-multiple-inheritance.test

This eliminates the error `Definition of "Nested" in base class "Base1" is incompatible with definition in base class "Base2"` in the following code, where `Nested` is redefined in `A`:
```
from typing import TypeVar, Generic
T = TypeVar('T', covariant=True)
class GenericBase(Generic[T]):
pass
class Base1:
Nested: GenericBase['Base1']
class Base2:
Nested: GenericBase['Base2']
class A(Base1, Base2):
Nested: GenericBase['A']
```
- In the case of multiple inheritance, don't give errors about definitions of an
attribute in base classes being incompatible when the attribute is redefined.
The redefinition must itself be compatible with all (non-type-ignored)
definitions of the attribute in all base classes.
This is achieved by making the following change to checking of incompatible
types in …

Loosen base class attribute compatibility checks when attribute is redefined

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

This fixes a crash discovered internally, see tests for a simplified repro.

New semantic analyzer: fix a crash with imported tricky alias

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

This fixes a crash discovered by testing the new analyzer internally.

New semantic analyzer: Fix crash in imports over existing name

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_classprop.py
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test

Fixes https://github.com/python/mypy/issues/6432
This is a hot fix that simply extends the solution in PR https://github.com/python/mypy/pull/6429 to more situations. We agreed with @JukkaL that he will clean this up when he is back from PTO.
Note that we still give the errors for redefinitions that we consider invalid (see tests), but we don't crash now.

New semantic analyzer: fix redefining symbols as overloaded functions or classes

---

mypy/fscache.py
mypy/modulefinder.py
mypy/test/testcheck.py
test-data/unit/check-modules-case.test
test-data/unit/check-modules.test

This removes one TODO item that used to cause subtle bugs internally.
The test failed on Mac without the fix, I didn't test on Windows, but I think it should be good as well.

Add case sensitive directory checks

---

mypy/newsemanal/semanal.py
test-data/unit/check-functions.test
test-data/unit/check-newsemanal.test

This PR makes another tricky corner case consistent with the old semantic analyzer, whose behavior also seems more consistent (imports can always redefine names if types are consistent).

New semantic analyzer: fix another tricky import

---

mypy/newsemanal/semanal.py
mypy/nodes.py
test-data/unit/check-newsemanal.test

In the old analyzer the first definition always wins. We should try to always preserve this logic. This is a hotfix for a problem discovered internally, we should try to find a more robust and general solution.

New semantic analyzer: When defining an alias first definition wins

---

README.md

There's no mention of the word "changelog" in the README, making it pretty difficult to scan for changes.
This is related to #5008.

Add changelog section with link to blog in README

---

docs/source/config_file.rst
mypy/main.py
mypy/options.py
test-data/unit/cmdline.test

Allow target paths to be specified through config files as an alternative to the command line.
To simplify the enforcement of which files/directories should be validated when working in a team. Rather than having to write a separate script that specifies the files, you can simply declare them in the existing `mypy.ini` (or alternative) config file.
I've tried to copy the functionality that you might expect from the typical command line, so this includes recursive file globbing. There are two main differences:
1) paths are comma- or semicolon-separated rather than just using spaces
2) by using the `glob` module we get `**` resolving to zero or more intermediate directories. In bash (at least), `*/*.py` or `**/*.py` will only match python files in the directory below the current one.
If a …

Allow files to be specified via ini config

---

mypy/typestate.py
test-data/unit/check-optional.test

Otherwise subtype relationships that are valid with strict optional
off (like List[str] <: List[Optional[str]]) can leak into strict
optional code via the subtype cache.

Track strict optional mode in typestate cache

---

mypy/checker.py
test-data/unit/check-multiple-inheritance.test
test-data/unit/pythoneval.test

Fixes https://github.com/python/mypy/issues/5973
The fix is straightforward, I just copy a bit of logic (bind self and map type) from normal override check
to the multiple inheritance one (I also factored it out in a small method to avoid duplication).
Using this opportunity I also added/expanded some docstrings.

Fix multiple inheritance check for generic classes

---

mypy/plugin.py
mypy/plugins/attrs.py
mypy/plugins/common.py
mypy/semanal.py
test-data/unit/check-attr.test
test-data/unit/check-dataclasses.test
test-data/unit/fixtures/list.pyi

The fix essentially mirrors the one for dataclasses. Note I temporary add `final_iteration` to the old analyzer, because plugin files import everything from the old one.
The non-trivial part is removing previously generated functions in plugins to make them re-entrant.

New semantic analyzer: Fix --disallow-untyped-defs with attrs plugin and forward references

---

.travis.yml
appveyor.yml
setup.cfg
tox.ini

Whenever we run with tox we automatically collect coverage data. The users can use the coverage environment to generate the report (stdout, xml, html). This also works merging outcomes from multiple environments. While at it normalized the format (indent by 4 space), and bump to tox ``3.9.0``.

add coverege report to tox run

---

setup.py

Since that is now the default for our releases, it is showing up in
the description on pypi, which seems wrong.

Remove "(mypyc-compiled version)" from package description

---

mypy/checker.py
mypy/checkmember.py
mypy/message_registry.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/1706
Fixes https://github.com/python/mypy/issues/5398
Previously, decorated constructors either resulted in silent `Any` types for class objects (in case of a decorated `__init__()`) or incorrect signatures (in case of a decorated `__new__()`).
This PR adds support for decorated constructors, implementation is straightforward.
This PR supersedes https://github.com/python/mypy/pull/5798.

Support decorated constructors

---

mypy/checkmember.py

PR #6645 introduced a mypyc failure due to the irritating #3603
intersection type issue.
Fix it by testing again SYMBOL_FUNCBASE_TYPES instead of FuncBase

Fix mypyc build

---

docs/source/command_line.rst
mypy/checkexpr.py
test-data/unit/check-expressions.test
test-data/unit/fixtures/primitives.pyi

Fixes https://github.com/python/mypy/issues/6607
Fixes https://github.com/python/mypy/issues/6608

Tweaks to --strict-equality based on user feedback

---

mypy/checkexpr.py

This avoids the crash reported in #6727. However that issue should remain open, because there's a logic bug somewhere (but it's not high enough priority to try and track it down).

Don't crash on double-underscore-prefixed keyword arg

---

setup.py
test-requirements.txt

- 1.3.2 fixed two out of bounds reads
- 1.3.3 was a dud
- 1.3.4 made it compile under newer Python 3.8 alphas
- 1.3.5 fixed a crash with unicode names on Python 3.4/3.5

Bump minimal required typed-ast version from 1.3.1 to 1.3.5

---

mypy/main.py
test-data/unit/cmdline.test

This is in line with the recommendation from #6003.
(It is called if there's something wrong with a filename.)

Make fail() in main.py use exit code 2

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Fixes https://github.com/python/mypy/issues/6516
It also fixes minor corner case that affects tests cases proposed in the issue.

Fix dataclass plugin interaction with member expressions

---

mypy/newsemanal/semanal.py
mypy/semanal.py
test-data/unit/check-classes.test
test-data/unit/check-newsemanal.test

Error when a class member is redefined

---

mypy/fastparse.py
mypy/fastparse2.py
test-data/unit/check-functions.test

Don't add self argument if nested function in method 

---

docs/source/command_line.rst

Remove mention of --python-version being set based on
--python-executable. This functionality was removed in
d2a9f9d9e8111877621eb2d2a24104f9787ae553 and --python-executable is now
only used to find PEP 561 packages. This is a documentation fix for #6205.

Correct --python-executable documentation

---

mypy/newsemanal/semanal.py
mypy/semanal.py
test-data/unit/check-expressions.test
test-data/unit/check-inference.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test
test-data/unit/semanal-errors.test

Include a note when user forgets to import something from the typing module

---

mypy/build.py

This is generally useful when debugging interactions between command line
flags and options in mypy.ini.
Fixes #6205.

Output the parsed command line and file options

---

mypy/report.py
mypy/stats.py
test-data/unit/reports.test

AnyTypes of type special-form or deriving from a special-form
should not be reported as they are a concept internal to mypy
Fixes #6765

Don't mark special-form AnyTypes during reports

---

docs/source/stubs.rst
mypy/checker.py
test-data/unit/check-modules.test
test-data/unit/fixtures/exception.pyi

Resolves https://github.com/python/mypy/issues/6531
This diff modifies the checker to allow default arguments to be used in function definitions in non-stub files as long as the body of that function is either empty or contains just a `raise NotImplementedError`. (This is after ignoring docstrings.)
For rationale on why this is useful, see the issue linked above.
One note on function bodies containing only a `raise Blah`. I was worried that letting mypy ignore the ellipsis when the function raises *any* Exception would lead to unsafe behavior -- I didn't want mypy to start allowing code that looks like this:
def halt(self, reason: str = ...) -> NoReturn:
raise MyCustomError("Fatal error: " + reason, self.line, self.current_context)
Whitelisting only NotImplementedError seemed like a good …

Allow ellipsis default args in "trivial" non-stub functions

---

mypy/fastparse.py
mypy/fastparse2.py
test-data/unit/check-fastparse.test
test-data/unit/check-literal.test
test-data/unit/parse-errors.test

Ouput bad comment during syntax error

---

mypy/checker.py
mypy/messages.py
mypy/plugins/attrs.py
mypy/test/data.py
runtests.py
test-data/unit/README.md
test-data/unit/check-classes.test
test-data/unit/check-expressions.test
test-data/unit/check-functions.test
test-data/unit/check-inference-context.test
test-data/unit/check-inference.test
test-data/unit/check-python2.test
test-data/unit/check-tuples.test
test-data/unit/cmdline.test
test-data/unit/fine-grained.test

Fixes #2463
Improve error message when partial types are found for built-in types `Dict`, `List`, `Set`, `FrozenSet`.
Messages used to be like:
```
main:3: error: Need type annotation for 'x'
```
This PR modifies it to look like:
```
main:3: error: Need type annotation for 'x' (hint: "x: List[<type>] = ...")
```
In case the variable is not of a built-in type the hints are not shown.

Improve message when an annotation is expected

---

mypy/messages.py
mypy/newsemanal/semanal.py
mypy/semanal.py
test-data/unit/check-newsemanal.test
test-data/unit/semanal-modules.test

This fixes the following case outlined in #824:
```
from subprocess import popen  # Module 'subprocess' has no attribute 'popen'
```
is now
```
from subprocess import popen  # Module 'subprocess' has no attribute 'popen'; maybe "Popen"?
```

Show closest candidates for misspellings: from..import case

---

mypy/build.py
test-data/unit/cmdline.test

Ask user about __init__ on duplicate packages

---

mypy/errors.py
mypy/fastparse.py
mypy/fastparse2.py
mypy/nodes.py
test-data/unit/check-38.test
test-data/unit/check-attr.test
test-data/unit/check-classes.test
test-data/unit/check-dataclasses.test
test-data/unit/check-incremental.test
test-data/unit/check-protocols.test
test-data/unit/parse-python2.test
test-data/unit/parse.test
test-data/unit/semanal-classes.test
test-data/unit/semanal-types.test

Fixes #3871. This change fixes a few things concerning class/function definition line numbers.
For users running mypy with Python 3.8+:
- Function definitions are now reported on the correct line, rather than the line of the first decorator plus the number of decorators.
- Class definitions are now reported on the correct line, rather than the line of the first decorator.
- **These changes are fully backward compatible with respect to `# type: ignore` lines**. In other words, existing comments will _not_ need to be moved. This is accomplished by defining an ignore "scope" just like we added to expressions with #6648. See the recent discussion at #3871 for reasoning.
For other users:
- Class definition lines are reported by using the same decorator-offset estimate as functions. This is …

Fix class/def line reporting and ignoring for 3.8+.

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/erasetype.py
mypy/fixup.py
mypy/newsemanal/typeanal.py
mypy/plugins/common.py
mypy/sametypes.py
mypy/server/astdiff.py
mypy/server/astmerge.py
mypy/server/deps.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-literal.test
test-data/unit/fine-grained.test
test-data/unit/fixtures/isinstancelist.pyi

This diff makes three changes: it fixes a bug where we incorrectly track "final" Instances, does some related refactoring, and finally modifies tuple indexing to be aware of literal contexts.
Specifically, here is an example of the bug. Note that mypy ignores the mutable nature of `bar`:
def expect_3(x: Literal[3]) -> None: ...
foo: Final = 3
bar = foo
for i in range(10):
bar = i
expect_3(bar)
To fix this bug, I decided to adjust the variable assignment logic: if the variable is non-final, we now scan the inferred type we try assigning and recursively erase all set `instance.final_value` fields.
This change ended up making the `in_final_declaration` field redundant -- after all, we're going to be actively erasing types on non-final assignments anyways. So, I decided to just remove this …

Fix incorrect tracking of "final" Instances

---

README.md

This PR is not related with any existent issue.
After I clone the project I was not able to find the folder for typeshed because I was looking for it at the mypy repo folder but actually there is a second folder also called mypy where the typeshed folder will be inside, the right path is 'mypy/mypy/typeshed'.
My suggestion is make it explicit for remove this barrier that affects everyone that try to setup their project.

Make typeshed submodules instructions more explicit

---

mypy/checker.py
test-data/unit/check-classes.test

Skip error if attribute or method is private to class

---

mypy/messages.py
test-data/unit/check-functions.test

Show only the missing argument names in error msg

---

mypy/build.py
mypy/fastparse.py
mypy/fastparse2.py
mypy/stubgen.py
mypy/test/testparse.py
test-data/unit/check-fastparse.test
test-data/unit/cmdline.test
test-data/unit/stubgen.test

Stubgen doesn't produce any output if there is a blocking error.

Generate non-blocking error for foo few/many arguments in type comment

---

mypy/test/teststubgen.py

This fixes some import tests by explicitly setting up `sys.path`.
Apparently `sys.path` is different when pytest runs test in parallel.
Fixes #6814.

Fix running stubgen tests sequentially

---

mypy/test/helpers.py
mypy/test/teststubgen.py

Follow up for https://github.com/python/mypy/issues/6814
Fixes https://github.com/python/mypy/issues/6817
I also added few minor cleanups in `mypy.test.helpers` near the code I edited.

A more robust fix for sequential stubgen tests

---

mypy/test/testpep561.py

Added logic to temporarily skip tests in testpep561.py that fail on Mac due to nesting of ```virtualenv ``` inside a ```venv```. This PR could be updated to only skip tests on Mac but I've left that out for now. Once this bug is fixed these tests should be added back in. 
Fixes [#6798](https://github.com/python/mypy/issues/6798)

Skip tests in testpep561.py

---

mypy/checker.py
test-data/unit/check-inference.test

Don't crash when partial types are used in inherited attribute

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/main.py
test-data/unit/cmdline.test

(In incremental mode it doesn't work right, and it isn't worth fixing.)
Fixes #5957

Only honor --warn-unused-configs in non-incremental mode

---

mypy/server/update.py
test-data/unit/fine-grained.test

If both module top level and a method that defines an attribute
through `self.x = y` assignment were stripped, stripping the 
method could result in a crash as the attribute had already 
been removed from the class symbol table (and was sometimes 
not added back). The root cause was some patches being 
dropped.
Fixes #6834.

Fix daemon crash when using new semantic analyzer

---

mypy/__main__.py
mypy/api.py
mypy/build.py
mypy/dmypy_server.py
mypy/errors.py
mypy/main.py
mypy/mypyc_hacks.py
mypy/test/testgraph.py

These are the changes made by @elkhadiy to resolve the problems with stdout not being thread-safe in the api.
Fixes #6125.

Fix sys.stdout overriding in mypy.api

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_newtype.py
mypy/newsemanal/semanal_shared.py
test-data/unit/check-newsemanal.test

This fixes a crash when processing the latest `unittest` stubs.
Previously we didn't always defer a target when placeholder nodes
were added to a symbol table. This could result in crashes.

New semantic analyzer: fix crash caused by leaking placeholders

---

mypy/fastparse.py
mypy/fastparse2.py
test-data/unit/fine-grained.test

Since fine-grained mode doesn't re-run the parser, non-blocking errors get lost.
There are a bunch of different approaches that could fix this but for now just
disable non-blocking errors from the parser in fine-grained mode.
Partially disables #6813.

Make parse errors always blockers in fine-grained mode

---

mypy/checkexpr.py
test-data/unit/check-overloading.test

This fixes an issue where the Any that is inferred temporarily when a
node is deferred could cause a bad overload to be picked and produce
a spurious error even though it checked properly the *second* time.

Make expression checking always produce Any once a node has been deferred

---

mypy/newsemanal/semanal_main.py
test-data/unit/fine-grained.test

This just follows the logic from `calculate_class_properties()`. I was thinking about factoring this out into a new context manager, but it doesn't really save any space.
Also `report_hang()` is still broken, but it was broken for long time and it is a separate issue.

New semantic analyzer: Fix crash in error reporting

---

mypy/fastparse.py
mypy/fastparse2.py
test-data/unit/check-ignore.test

Fixes #6852, and adds a regression test.

Fix whole-file # type: ignore comments.

---

mypy/fscache.py
mypy/main.py
mypy/messages.py
mypy/server/objgraph.py
mypy/stubgenc.py
setup.cfg

Most of the `getattr` calls with constant strings were to shut up mypy, so add a bunch of
`# type: ignore`s for those.
A couple were for other things (something dumb with mypyc, using an invalid identifier),
so those get `# noqa`.
Not totally sure if this is actually better, which is why I didn't put the PR up when I first wrote it,
but pushing now to see what other people think so I can clean up the branch.
(I'm leaning towards it being better, but only marginally.)

Renable flake8 warning about getattr with constant string

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py
test-data/unit/check-newsemanal.test

Previously things like `class A(A): pass` resulted in a crash
instead of an error message. Now we generate an error message
with some context (but still not enough).
Partially addresses #6495.

Fix reporting of likely hangs in the new semantic analyzer

---

mypy/renaming.py
test-data/unit/check-redefine.test

This is strictly speaking unsafe, but allowing this is convenient 
(and safe) in the vast majority of cases.
Fixes #6705.

Allow redefinition withing with statements

---

mypy/newsemanal/semanal_main.py
test-data/unit/check-newsemanal.test

Fix another crash related to hitting max iteration count in
the new semantic analyzer.

Fix hang reporting more (follow-up to #6872)

---

mypy/build.py
test-data/unit/fine-grained.test

This keeps the errors from getting lost by the daemon

Make inline config errors blockers

---

mypy/test/testtypes.py
mypy/types.py
test-data/unit/check-namedtuple.test

Previously some code was treated incorrectly as unreachable, since
some checks where treated as always true even though they could
be false given a None value.
Fixes  #3601.

When strict optional is disabled, anything can be falsey

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

Various fixes to `lookup_qualified`:
1. Allow qualified types that refer to unimported modules. Fixes #6866.
2. Flag module private references in the middle of a qualified name.
3. Don't allow module-level `__getattr__` in Python 3.6 and earlier
outside stubs.
4. Better error message when qualified name includes a function/variable
component.
Also includes a major refactor of `lookup_qualified`.
More cleanup is possible, but this PR seems big enough as is.

New semantic analyzer: fix issues with looking up qualified names

---

README.md

Vim-mypy is not maintained and does not work with the current version.
Syntastic is a well-maintained static grammer checking plugin for
vim that supports multiple languages.
Addressing (https://github.com/python/mypy/issues/6880)

Update readme: replace vim-mypy by syntastic

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_main.py

Modify the main entry point `refresh_partial` to call `file_context`
to make things less error-prone.
Also remove arguments that are not needed.

New semantic analyzer: refactor file_context

---

docs/source/additional_features.rst

Callback protocols should be used instead.
There are no plans to remove support for extended
callable types, though.

Document extended callable types as deprecated

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_shared.py
mypy/newsemanal/typeanal.py
test-data/unit/check-newsemanal.test

Now we detect additional problems in base classes and generate a
proper error instead of deferring indefinitely and generating an
internal error.
There are two fixes:
1. Don't treat replacing a placeholder node that may be a type with
another placeholder that may be type as progress.
2. Don't generate a placeholder type for base class during the final
iteration.
Also did some refactoring.
Fixes #6495.
Fixes #6892.

New semantic analyzer: fix issues with bad base classes

---

.travis.yml

The new argument to PyCode_New means that lxml doesn't work on 3.8
right now, so we're out of business until there's a new lxml release
that does. (If that is taking too long, we can disable the tests that
want lxml.)
There are also some other minor issues: we fail some tests with
`DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead` while running some of the eval tests.

Disable travis builds on 3.8

---

mypy/fastparse.py
mypy/test/testcheck.py
test-data/unit/check-38.test

Fixes #6878. This was actually much more straightforward than I anticipated; since we already support `__some` forms of positional-only arguments, it was just a matter of adding a couple of lines to properly pick up the new `posonlyargs` attribute from the AST.
The tricky part is the tests. Travis doesn't currently have any build environments for 3.8.0a4 (even the `python: "nightly"` image is only 3.8.0a3+... :neutral_face:), so these tests fail with syntax errors. I've skipped them for now, but they pass fine on my local Python build. I added a small check in `testcheck.py` that will emit a warning when it's safe to unskip these tests.

PEP 570: Positional-Only Arguments

---

docs/source/cheat_sheet.rst
docs/source/cheat_sheet_py3.rst

The current "cheat sheet" examples use `Iterable` to annotate the return type of generator functions.  This PR changes this to `Iterator`, which is more specific.
In most cases it doesn't matter, but the distinction becomes significant when defining an iterable class whose `__iter__` method is a generator function.
```
from typing import Iterable
class MyIterable:
def __iter__(self) -> Iterable[int]:
yield 1
mi = MyIterable()
for k in mi:  # error: "Iterable[int]" has no attribute "__next__"
pass
```

Use Iterator in documentation examples for generator functions

---

mypy/checker.py
mypy/checkexpr.py
test-data/unit/check-expressions.test
test-data/unit/check-statements.test

Fixes #4444. Now `yield from <tuple>` works as expected!
~We just add a branch to special-case `TupleType`, since neither they nor their fallbacks are properly handled by any of the other branches.~

Fix yield from TupleType.

---

mypy/test/testcheck.py
test-data/unit/check-python38.test

The `3.8-dev` Travis build environment now uses Python 3.8.0a4+!
This is left over from #6900. We aren't running 3.8 test right now for other reasons, but I've confirmed that these pass fine on my local build (@JukkaL confirmed too in the PR).

Reenable PEP 570 tests.

---

mypy/newsemanal/typeanal.py
mypy/typeanal.py
mypy/types.py
test-data/unit/check-literal.test
test-data/unit/merge.test

This diff modifies the typeanal phase so that we try analyzing the args of an UnboundType even when it turns out that UnboundType is invalid. This prevents things like RawExpressionTypes from leaking out of the semantic analysis phase.
Fixes https://github.com/python/mypy/issues/6913.

Analyze UnboundType args even when UnboundType is invalid

---

test-requirements.txt

It appears to have been pinned initially without a specific reason (in
79bce277).

test-requirements: unpin lxml

---

mypy/build.py
mypy/fastparse.py
mypy/fastparse2.py
mypy/server/update.py
test-data/unit/fine-grained.test

We do this by storing the errors generated at parse time and replaying
them when the module is reprocessed.
This restores consistency between the daemon and non-daemon for
type comments with the wrong number of arguments.

Allow non-blocking parse errors in fine-grained mode

---

mypy/server/aststripnew.py

Update docstring and comment.
The existing test coverage seemed sufficient. In particular, there
is an existing test case that changes the type of an attribute.

Follow-up to #6916 (fix daemon crash during AST strip)

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/main.py
mypy/newsemanal/semanal.py
mypy/options.py
mypy/semanal.py
test-data/unit/check-flags.test

Adds a --no-implicit-reexport flag, intended for giving modules the same behavior as stubs for re-exporting their imports.
The goal is to make it possible to prevent bad transitive imports from causing dependency issues. And to make it easier to move things to a different module.

Add --no-implicit-reexport flag

---

setup.py
test-requirements.txt

Now that typed_ast 1.4.0 is released (whose main new feature is support for extra text after `# type: ignore`).

Update typed_ast dep to 1.4.0+

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_namedtuple.py
mypy/newsemanal/typeanal.py
test-data/unit/check-basic.test
test-data/unit/check-inference.test
test-data/unit/check-newsemanal.test

This fixes scoping issue where code like this was rejected:
```py
c: C  # Forces second semantic analysis pass
class X: pass
class C:
X = X   # Should be no error here
```
The approach is to fall back to the outer scope if the definition
in the class body is not ready yet, based on the line numbers of
the definitions.
Additionally generate an error for references to names defined 
later in a class body.
This only addresses class bodies. Local scopes have a similar 
issue with references to undefined names. I'm planning to 
address that in a separate PR.
The basic fix is very simple, but various other changes were
required to support multi-line definitions and certain edge cases.
Work towards #6303.

New semantic analyzer: fix falling back to outer scope in class body

---

mypy/build.py
mypy/newsemanal/semanal.py
mypy/server/target.py
mypy/server/update.py
mypy/suggestions.py
mypy/util.py
test-data/unit/check-newsemanal.test

We shouldn't use the line number of an imported name to decide
whether it's defined when the line number refers to another
file.

New semantic analyzer: fix access to imported name in class body

---

README.md
setup.py

In https://github.com/python/mypy/issues/6740, I think we all pretty much unanimously agreed mypy ought to be labeled as "beta" at the absolute minimum.
So, might as well just do the switch now.

Document mypy as "beta" instead of "alpha" software

---

docs/source/common_issues.rst
mypy/errors.py

I noticed that several recent crash reports were from people on older mypy versions. I thought it would be good to suggest people try the latest master as that may have needed fixes. Here is a sample of the output:
```
test.py:5: error: INTERNAL ERROR -- Please try using master
https://mypy.rtfd.io/en/latest/common_issues.html#using-pre-release-mypy
If this crash persists, please report a bug at https://github.com/python/mypy/issues
version: 0.710+dev.bde68e77bc6fd209fce765f3ddcc9cb2b4c43e77.dirty
test.py:5: : note: please use --show-traceback to print a traceback when reporting a bug
```
I also edited the docs section so the title/link wouldn't be so long.

Suggest trying master branch on crash

---

test-data/unit/check-classes.test
test-data/unit/check-final.test
test-data/unit/check-flags.test
test-data/unit/fine-grained.test
test-data/unit/semanal-errors.test

Some tests are only enabled for the new semantic analyzer. For a few
I decided to create duplicate tests, but only if the test seemed
worthwhile enough, as the old semantic analyzer isn't going to change
much any more.

Enable additional tests on new semantic analyzer

---

mypy/newsemanal/semanal_typeddict.py
mypy/semanal_typeddict.py
test-data/unit/check-typeddict.test

Entries can't be *declared* in versions that don't support type
annotations, of course, but class-based TypedDict still serves a
valuable purpose in merging TypedDicts together.
This error *only* triggers on empty TypedDicts, since any non-empty
ones would have failed earlier with a syntax error. So there is no
reason to prohibit it because we can handle that case totally fine.

Allow class-based TypedDicts in all python versions

---

mypy/newsemanal/semanal_namedtuple.py
mypy/plugins/common.py
mypy/util.py
test-data/unit/check-class-namedtuple.test
test-data/unit/check-dataclasses.test

Fixes #6454
Fixes https://github.com/python/mypy/issues/6973
Note that the solution doesn't guarantee the order of numbers `N` in `foo-redefinitionN` coincides with the textual order of nodes. But it looks like we don't need this for anything.

New analyzer: resolve name clashes between generated and existing nodes

---

mypy/checker.py
test-data/unit/check-callable.test
test-data/unit/check-isinstance.test

This fixes two possible crashes I noticed while reading the code.

fix crashes with callable() and issubclass()

---

test-data/unit/check-statements.test

This crashes on old semantic initializer but doesn't crash when
using the new semantic analyzer.  The error message is pretty
poor but that's better than crashing.
Closes #5923.

Add test case for global declaration without initializer

---

test-data/unit/check-newsemanal.test
test-data/unit/fine-grained.test

This is broken with the old semantic analyzer but works with the new
semantic analyzer.
Closes #4760.

Add test case for class variable forward reference

---

mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_newtype.py
mypy/nodes.py
test-data/unit/check-newsemanal.test

Line numbers are used sometimes to decide when a name should be looked
up from an outer scope, so they should be set for placeholders.
This actually breaks some forward references to assignment-based named
tuples. The reason is that we don't set `becomes_typeinfo=True` for
the placeholders. I'm going to open a separate issue about this, as
it's an existing issue and this change only exposes it.
Fixes #6949.

New semantic analyzer: track line numbers of placeholders

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Previously InitVar attributes were missing on the second semantic
analysis pass, since the dataclasses plugin removes those attributes
from the class symbol table. This caused a crash. The fix is to reset
the attribute declarations so that they will be re-added to the symbol
table on successive semantic analysis passes.
Fixes #6955.

New semantic analyzer: fix crash related to dataclasses.InitVar

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

New semantic analyzer: fix order=True in dataclass with deferral

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

This is (kind of) an actual fix for #6952
The problem is that previously `unwrap_final()` unconditionally set `s.type` to `None` for bare `Final`, even if the type was inferred from a simple literal r.h.s. on a previous iteration. At the same time `lvalue.is_inferred_def` remained `False`, so that the type was not inferred on the second iteration.
This way `s.type` and `lvalue.is_inferred_def` may get out of sync depending on the number of iterations, thus causing weird behavior in type checker.
I generally can say the current way of storing the inferred status is error-prone, but we already have https://github.com/python/mypy/issues/6458 to track this.

 New semantic analyzer: Keep explicit type and inferred status in sync

---

docs/source/more_types.rst

It's no longer experimental since PEP 589 was accepted:
https://www.python.org/dev/peps/pep-0589/

Mark TypedDict as not experimental

---

mypy/build.py
mypy/newsemanal/semanal.py
test-data/unit/check-modules.test
test-data/unit/check-newsemanal.test
test-data/unit/fine-grained-modules.test
test-data/unit/semanal-errors.test

Previously we added each submodule implicitly to the the symbol table of
the parent package. This PR removes this and instead we look up names from
the modules dictionary if they aren't found in the symbol table. The change
only affects the new semantic analyzer.
This provides the foundation that should make it easier to fix #6828. It also 
arguably cleans up the code.
Also refactor some related code to avoid duplication.
This isn't a pure refactor since some error messages are slightly different.

New semantic analyzer: don't add submodules to symbol tables

---

mypy/suggestions.py
test-data/unit/fine-grained-suggest.test

* Fix --no-any to not spuriously reject all methods
* Support inferring types of decorated methods if the decorator
doesn't change the type
* Refuse to infer functions with then or more arguments to avoid
spending forever calculating an exponentially large number of
possibilities before deciding there are too many possibilities.
I've already successfully used this code in generating annotations at Dropbox.

dmypy suggest: handful of bug fixes/improvements

---

mypy/dmypy/client.py
mypy/suggestions.py
mypy/test/testfinegrained.py
test-data/unit/fine-grained-suggest.test

This allows preferring unicode in annotations generated for Python 2
code. pyannotate will spell unicode as Text, so this helps faciliate
porting to Python 3.
I've already successfully used this code in generating annotations at Dropbox.

dmypy suggest: add a flag to try using unicode

---

docs/source/more_types.rst
mypy/message_registry.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_typeddict.py
mypy/nodes.py
mypy/semanal.py
mypy/semanal_typeddict.py
mypy/types.py
test-data/unit/check-literal.test
test-data/unit/check-protocols.test
test-data/unit/check-typeddict.test
test-data/unit/fixtures/typing-full.pyi
test-data/unit/lib-stub/typing_extensions.pyi

This introduces the following updates:
* Allow using `typing.TypedDict` (still support all the old forms)
* Add a test for `typing.Literal` (it was already supported, but there were no tests)
* Rename `@runtime` to `@runtime_checkable`, while keeping the alias in `typing_extensions` for backwards compatibility.
(Note that `typing.Final` and `typing.Protocol` were already supported and there are tests.)
See also https://github.com/python/typeshed/pull/3070

Sync mypy with recent runtime updates in typing

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

Now imports are biased to target the submodule of current package,
but elsewhere a local definition with the same name as a submodule 
takes precedence.  Even though this doesn't quite reflect what 
happens at runtime, this seems to cover the typical use cases well, 
and the implementation is simple.
Fixes #6828.

New semantic analyzer: fix ambiguity between submodule and local def

---

mypy/main.py
mypy/test/testpep561.py

Addresses:
https://github.com/python/mypy/issues/6595

Have --package usage respect mypy_path

---

setup.py

This simple error has an unfortunately far reaching effect :(
The compiled `__main__.py` file doesn't work, so dmypy is broken with mypy 0.710 on Windows, which this fixes.
Closes #7031

Fix MYPYC_BLACKLIST on Windows

---

mypy/config_parser.py
test-data/unit/check-inline-config.test
test-data/unit/cmdline.test

Support inverting options based on `no_`, and adding or removing a `dis` prefix
in the config file (and therefore in inline configuration also).
This moves the handling of `no_` prefixes from inline configuration to the config file.
As a result, the config file is brought closer into alignment with the command line options.

Support flexible option specification in config file and inline configuration

---

mypy/newsemanal/semanal_namedtuple.py
test-data/unit/check-newsemanal.test

Previously we could rename named tuple methods that didn't have
a corresponding auto-generated method, resulting in duplicate
symbol nodes.
Fixes #7059.

New semantic analyzer: don't rename all named tuple methods

---

mypy/newsemanal/semanal.py
test-data/unit/check-async-await.test

Previously if the body was analyzed in multiple iterations, the
return type could get multiple levels of Coroutine[...] wrappers.
Fixed the problem by applying the type wrapper only during the
final iteration (nothing was deferred in the function body).
Fixes #7058.

New semantic analyzer: fix return types of async functions

---

mypy/nodes.py
test-data/unit/check-incremental.test

This fixes some inconsistent "Cannot determine type of 'foo'" errors
at least with the new semantic analyzer.
There is still a deviation between old and new semantic analyzers, but at
least this makes the new semantic analyzer behave consistently.
Fixes #7025.

Serialize ready state of Var nodes

---

mypy/test/testcheck.py
test-data/unit/check-columns.test

Added tests for many of the most common error messages. These should
cover maybe 95% of error messages (based on user logs).
This only updates tests and doesn't change any behavior.

Add more tests for column numbers in error messages

---

mypy/checker.py
test-data/unit/check-isinstance.test

While experimenting with some reachability inference logic, I discovered the following program does not seem to behave as expected:
```python
from typing import Any
from foo import A  # type: ignore
x: Any
if isinstance(x, A):
reveal_type(x)
else:
reveal_type(x)
```
Both branches really ought to be reachable: since both `x` and `A` are of type `Any`, we really can't say whether or not any particular branch will run: both branches ought to be reachable.
However, mypy currently instead assumes that only the first branch is reachable and does not type-check the second branch. So in this example, only the first `reveal_type(...)` outputs a note.
This pull request fixes this bug.

Fix reachability inference with 'isinstance(Any, Any)'

---

mypy/newsemanal/semanal.py
mypy/nodes.py
mypy/semanal.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/customize_mro.py

The semanal code that invoked it created an `Expression` directly,
which mypyc barfs on because it is a trait.
Fixes #6706.

Fix mypyc crash with plugins using `get_customize_class_mro_hook`

---

mypy/checkexpr.py
mypy/types.py
test-data/unit/check-tuples.test

This fixes #7056.
The idea is that we don't know what types a tuple slice will result in, other than a tuple of some sort.
For example, `(1,'', 3.3)[:a]` could result in `Tuple[()]`, `Tuple[int]`, `Tuple[int, str]`, or `Tuple[int, str, float]`.
I also fixed a typo I noticed in TypeOfAny.

Fix slicing tuples with nonliterals

---

mypy/checker.py
mypy/fastparse.py
mypy/fastparse2.py
mypy/newsemanal/semanal.py
mypy/newsemanal/semanal_newtype.py
mypy/newsemanal/typeanal.py
mypy/nodes.py
mypy/semanal.py
mypy/semanal_newtype.py
mypy/test/testcheck.py
mypy/treetransform.py
test-data/unit/check-classes.test
test-data/unit/check-columns.test
test-data/unit/check-functions.test
test-data/unit/check-generics.test
test-data/unit/check-literal.test
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test
test-data/unit/check-python2.test
test-data/unit/fixtures/property.pyi
test-data/unit/fixtures/property_py2.pyi

Previously many types and AST nodes didn't have 
(good) column numbers. This fixes several such issues.
In particular, this gives correct column number of simple 
types like `Foo` and `List[Foo]` in Python 3 type 
annotations.
For type comments we cheat a bit and point them to the
surrounding statement or definition, which is still a
small improvement.
For some types we may still be missing column numbers,
but this covers the most common cases.

Fixes to column number reporting

---

mypy/treetransform.py
test-data/unit/check-columns.test

Fix tree transform to not drop column numbers in many cases.

Fix columns in function with type variable value restriction

---

test-data/unit/check-classes.test
test-data/unit/check-incremental.test
test-data/unit/check-namedtuple.test
test-data/unit/check-typeddict.test
test-data/unit/check-unions.test

There is a feature regression: we no longer expand recursive definition
once. I think that this is acceptable for now. We can either try to
replicate the expansion of recursive definitions later on, or we can
wait until we have full recursive support before we do anything about
this.
Only enabled tests that do something reasonable. Recursive type aliases
and other things still don't work.
Work towards #6445.

New semantic analyzer: enable tests related to recursively defined types

---

mypy/checker.py
mypy/newsemanal/typeanal.py
test-data/unit/check-generics.test
test-data/unit/check-inference.test
test-data/unit/check-literal.test
test-data/unit/check-newsemanal.test
test-data/unit/fine-grained-cycles.test

Fixes https://github.com/python/mypy/issues/6998
This PR makes several related changes:
* Reserve `Cannot determine type` error for cases where node deferral failed etc (for example with runtime recursive definitions); don't show it after failed (ambiguous) type inference.
* Always set reasonable variable type after failed inference (like `List[Any]` for an empty list).
* Always give `Need type annotation for variable` error, not just for instances and tuples (that was ad-hoc IMO)
This may actually give some _new_ errors as compared to status quo, but as one can see from the diff, the result is negative in number of (redundant) errors.
There are couple changes in tests that look unrelated, these are because `is_same_type(..., UnboundType())` returns `True` for everything, including …

Make type inference failures more consistent

---

mypy/newsemanal/semanal.py
test-data/unit/check-attr.test

Fixes https://github.com/python/mypy/issues/6953
I first thought about actually not modifying them in `attrs` plugin, but this is non-trivial, plus there are few places apart from the plugin where we modify decorators. So for now I just restore them after each iteration (in the same way we do this for overloads and other things).

New semantic analyser: Fix special attrs decorators

---

mypy/server/aststripnew.py
test-data/unit/fine-grained.test

Fixes https://github.com/python/mypy/issues/7073
This is ugly, but really quick.

New analyser:  Quick and dirty fix for nested classes in fine grained mode

---

test-data/unit/check-newsemanal.test

New semantic analyzer: add test case for redefined nonlocal variable

---

mypy/binder.py
mypy/checker.py
mypy/checkexpr.py
mypy/main.py
mypy/messages.py
mypy/options.py
test-data/unit/check-unreachable-code.test

This diff adds a `--warn-unreachable` flag that reports an error if:
1. Any statement is inferred to be unreachable
2. Any subexpression in boolean expressions, inline if statements, and list/set/generator/dict comprehensions are always unreachable or redundant.
This only takes into account the results of *type* analysis. We do not report errors for statements that are inferred to be unreachable in the semantic analysis phase (e.g. due to `sys.platform` checks and the like).
Those checks are all intentional/deliberately flag certain branches as unreachable, so error messages would be annoying in those cases.
A few additional notes:
1. I didn't spend a huge amount of time trying to come up with error messages. They could probably do with some polishing/rewording.
2. I thought about …

Add flag to warn about unreachable branches and exprs

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test

Fixes https://github.com/python/mypy/issues/6957
Using the opportunity, I do a tiny refactoring. The only change in the logic is switching the order of things.

New analyser: Complain about type variable redefinition only after we decided it is valid

---

mypy/plugins/attrs.py
test-data/unit/check-attr.test

This is a hacky fix to better handle overloaded functions during
semantic analysis. The original approach is not very clean so this
doesn't make this worse, arguably.
Fixes #6438.

New semantic analyzer: fix handling invalid attrs converters

---

mypy/build.py
mypy/errors.py
mypy/nodes.py
mypy/strconv.py
mypy/visitor.py

I'm embarking on a (probably futile) quest to get mypy to type-check cleanly under the new `--warn-unreachable` flag.
This pull request starts off by tackling some of the low-hanging fruit. Specifically, I make three changes:
1. I removed some unnecessary 'is None' checks for the MypyFile.path field, which is annotated to be of just type `str`, not `Optional[str]`.
As a side-effect, this ends up fixing one itty-bitty bug: previously, we would not generate reports when running something like `mypy --any-exprs-report report_dir -c 'print("foobar")`.
2. I removed unnecessary "is this line or column None" checks from errors.py: those variables are only ever ints; we use "-1" as placeholders if those values are missing from various error messages.
3. I swapped a `is False:` check in …

Remove miscellaneous 'is None' checks

---

mypy/newsemanal/semanal.py
test-data/unit/check-incremental.test
test-data/unit/check-newsemanal.test
test-data/unit/check-type-aliases.test

This fixes maximum iteration count errors.
Recursive type aliases still don't work and the behavior is a
regression from the old semantic analyzer. Previously they were
truncated, but now they aren't supported at all. We could perhaps hack
something similar to what we used to have, but I don't think that it's
urgent.
This also breaks some use cases where "semi-recursive" type aliases
were supported previously. The support mechanism caused infinite
expansion for actual recursive type aliases. I couldn't come up with a
simple way to support both, so I decided to prioritize fixing infinite
expansion, as they have a worse impact on user experience.
Work towards #6445.

New semantic analyzer: fix recursive type aliases

---

mypy/newsemanal/semanal.py
mypy/newsemanal/typeanal.py
mypy/types.py
test-data/unit/check-newsemanal.test

Fixes https://github.com/python/mypy/issues/7102
This switches from using `'<unknown>'` to `None` as full name for placeholder types without a known node (and also update the outdated comment).

New analyser: use placeholder type full name correctly

---

mypy/checker.py
test-data/unit/python2eval.test

Fixes https://github.com/python/mypy/issues/7101
This fixes another manifestation of an old issue where type variables can leak where a generic function is passed as an argument to another generic function.

Fix type variables leaking from inference

---

test-data/unit/pythoneval.test

https://github.com/python/typeshed/pull/3083 fixed an issue in the `contextlib` stub file, which broke an existing mypy test that was written based off the incorrect stub file.
*NOTE*:
This commit will have to synced with that change to fix the tests + add new `decorator` tests.

Fix mypy tests for contextlib change in typeshed PR 3083

---

mypy/join.py
mypy/newsemanal/semanal_classprop.py
mypy/semanal_pass3.py
mypy/suggestions.py
mypy/types.py

This pull request is a continuation of my quest to make mypy cleanly type-check under the `--warn-unreachable` flag.
It removes some unnecessary checks we're performing against Type-related variables. Specifically:
1. We had some old code that checked if `t.accept(TypeJoinVisitor(s))` would return None. I believe this check was added back in 2014: after auditing our type visitors, it no longer seems relevant today.
2. We had a few unnecessary `if some_instance.type is not None` style checks. I believe we always set the TypeInfo when constructing Instance classes these days, so this check also seems unnecessary.
3. Finally, we had a "if TypeInfo.bases does not actually contain Instances" style check around some protocol-related code -- but `TypeInfo.bases` is of type `List[Instance]`.

Remove some "if type is None" style checks

---

mypy/newsemanal/semanal.py
test-data/unit/check-classes.test
test-data/unit/check-flags.test
test-data/unit/check-unions.test

Various recursive type definitions no longer cause crashes. 
Fix bogus messages about cyclic definitions when definition is 
acyclic when there are also recursive type definitions in the same
target.
Closes #6445.

New semantic analyzer: fix bogus messages and update tests

---

mypy/checker.py
mypy/test/testsamples.py
test-data/unit/check-inference.test
test-data/unit/check-newsemanal.test

Fixes https://github.com/python/mypy/issues/7117
As explained in the issue this didn't crash with old analyser because it was compensated by another bug: `Var.is_ready` was set to `True` in some conditions thus silently inferring an `Any` type instead of deferring the node, see added test.
The actual crash was caused by the fact that star lvalue was previously checked as a generic reference expression, instead of processing it as name definition, thus triggering a bogus unexpected deferral.

Fix new semantic analyser crash on unpacking to star lvalue and enable sample tests

---

mypy/newsemanal/semanal.py
mypy/newsemanal/typeanal.py

Document deferral logic in some detail and remove redundant
calls to `defer()`.
Work towards #7071.

New semantic analyzer: add comments and refactor

---

mypy/newsemanal/semanal.py

This produces a more useful stack trace than the existing check,
which happens after a target has already been analyzed.
I'm still keeping the old check just in case.

New semantic analyzer: fail fast if deferring during final iteration

---

mypy/plugins/attrs.py
mypy/plugins/dataclasses.py
test-data/unit/check-attr.test
test-data/unit/check-dataclasses.test

Fixes https://github.com/python/mypy/issues/7098

New analyser: fix crashes when plugins encounter a placeholder node

---

docs/source/extending_mypy.rst
mypy/plugin.py

Work towards #7071 (and more).

Document how plugins can support the new semantic analyzer

---

mypy/build.py

Internal telemetry shows it to be a hot spot in practice and I want to
dig a little deeper.
Gate some potentially expensive logging code on this path, while I'm
at it.

Add some more telemetry to graph loading

---

mypy/newsemanal/semanal.py
mypy/plugins/attrs.py
mypy/plugins/dataclasses.py
test-data/unit/check-attr.test
test-data/unit/check-dataclasses.test

Fixes https://github.com/python/mypy/issues/7076
The fix is pretty straightforward. I also add a comment about `missing_names` being per-module, not per namespace.

New analyser: Fix crash in plugins when star import blocks adding a symbol

---

mypy/modulefinder.py
mypy/test/testmodulefinder.py
test-data/packages/modulefinder/readme.txt

When used with --namespace-packages, a directory containing no `__init__.pyi`
was previously added as a candidate to near_misses even if it contained
a `__init__.py`. This logic doesn't seem sensible, particularly as this
directory was then chosen as the result of find_module() instead of
the `__init__.py` inside the directory.
This should cure #5854.

 modulefinder: use only dirs containing no __init__.py as namespace package

---

mypy/newsemanal/semanal.py
test-data/unit/check-newsemanal.test
test-data/unit/check-type-aliases.test

We special case these since a more general fix, such as looking
at line numbers of definitions, would break a ton of test cases.
Fixes #6404.

New semantic analyzer: fix issues with 'X = X' assignments

---

mypy/checkexpr.py
test-data/unit/reports.test

Fixes https://github.com/python/mypy/issues/7118
Previously left hand sides of special forms were inferred as `TypeOfAny.from_error`. Note that _total_ number of expressions in one of the tests is now smaller because of the subtle logic in visiting definitions of special forms, but I don't think it is import to keep it one-to-one with old analyser.

New analyser: Fix Any kinds for special forms

---

mypy/checkexpr.py
test-data/unit/check-expressions.test

Fixes https://github.com/python/mypy/issues/7035
The fix is straightforward: we use `get()` instead of `get_method()` and check for more symbol kinds.

Fix --strict-equality for decorated and aliased __eq__ methods

---

mypy/checkexpr.py
mypy/checkmember.py
test-data/unit/check-selftype.test
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/7149
The fix is quite straightforward, self-types should be bound to each individual component, so I just added only basic tests. Please let me know if you want better test coverage (properties, class-methods) etc.

Fix binding of self-types on unions

---

mypy/newsemanal/semanal.py

This concludes documentation that started in #7130 and #7135.
Closes #7071.

New analyzer: improve documentation of defer()

---

mypy/newsemanal/semanal.py
test-data/unit/check-incremental.test
test-data/unit/check-newsemanal.test

When we add a placeholder, we should do it through `mark_incomplete`,
since the name needs to added to the set of missing names. Otherwise
a later definition can take precedence over an earlier definition,
if the first definition initially creates a placeholder.
Fixes #7157 and probably another issue related to type alises, which
was exposed by the fix.

New analyzer: fix issues with order-dependent results

---

mypy/nodes.py

In some cases we don't know whether something could become a TypeInfo,
but it might. Not sure if this is the best way to do this, but this
helps in some scenarios (but could cause problems in others, perhaps).
Follow-up to #7158.

New analyzer: update documentation of becomes_typeinfo

---

mypy/build.py
mypy/newsemanal/semanal_main.py
mypy/test/helpers.py
mypy/test/testcheck.py
mypy/test/testfinegrained.py
test-data/unit/check-newsemanal.test

See https://github.com/python/mypy/issues/6341
This PR doesn't add actual tests, just the infra. I simply expose the existing machinery we use in the fine grained mode also to the normal tests.
Using this opportunity I also refactor `assert_module_equivalence()` and `assert_target_equivalence()` by moving `is None` checks to callers.

Add infrastructure for testing order of processing nodes in new analyser

---

docs/source/command_line.rst
docs/source/config_file.rst

This pull request adds a segment about the '--warn-unreachable' flag to the command line docs page and a shorter blurb to the config file page.

Add docs for the '--warn-unreachable' flag

---

mypy/meet.py
test-data/unit/check-expressions.test
test-data/unit/check-typeddict.test
test-data/unit/fixtures/dict.pyi
test-data/unit/fixtures/isinstancelist.pyi
test-data/unit/fixtures/list.pyi

Fixes https://github.com/python/mypy/issues/7036
This adds more "fine grained" logic for overlap between `TypedDict` and `Mapping` used by overload checks and `--strict-equality`. Basically the rules are:
* A `TypedDict` with some required keys is overlapping with `Mapping[str, <some type>]` if and only if every key type is overlapping with `<some type>`.
* A `TypedDict` with no required keys overlaps with `Mapping[str, <some type>]` if and only if at least one of key types overlaps with `<some type>`.
* Empty dictionaries are as usual in gray area, so we follow the same logic as in other places: an empty dictionary can't cause an overlap (i.e. `TypedDict` with no required keys doesn't overlap with `Mapping[str, <some type>]`), but is itself (i.e. `Mapping[<nothing>, <nothing>]`) …

Fix overlap between TypedDict and Mapping

---

mypy/newsemanal/semanal.py
mypy/newsemanal/typeanal.py
mypy/semanal.py
test-data/unit/check-basic.test
test-data/unit/check-classes.test
test-data/unit/check-columns.test
test-data/unit/check-custom-plugin.test
test-data/unit/check-functions.test
test-data/unit/check-generics.test
test-data/unit/check-incremental.test
test-data/unit/check-literal.test
test-data/unit/check-modules.test
test-data/unit/check-newsemanal.test
test-data/unit/check-newtype.test
test-data/unit/check-protocols.test
test-data/unit/check-redefine.test
test-data/unit/check-semanal-error.test
test-data/unit/check-statements.test
test-data/unit/check-type-aliases.test
test-data/unit/fine-grained-cycles.test
test-data/unit/fine-grained.test
test-data/unit/merge.test
test-data/unit/pythoneval-asyncio.test
test-data/unit/semanal-classes.test
test-data/unit/semanal-classvar.test
test-data/unit/semanal-errors.test
test-data/unit/semanal-namedtuple.test
test-data/unit/semanal-typealiases.test

Fixes https://github.com/python/mypy/issues/4030
This adds some more details to various `Invalid type` errors, and similar such as `Invalid type alias`, and `Invalid base class`. Unfortunately, `MessageBuilder` is not available in `typeanal.py`, so I put some error message formatting logic there.
Please add ideas about how to improve these errors.

Add more details for "Invalid type" errors

---

mypy/newsemanal/semanal_main.py
mypy/newsemanal/semanal_namedtuple.py
mypy/test/testcheck.py
test-data/unit/check-classes.test
test-data/unit/check-namedtuple.test
test-data/unit/check-newsemanal.test
test-data/unit/check-newtype.test
test-data/unit/check-type-aliases.test
test-data/unit/check-typeddict.test

New analyzer: add more tests for order of processing

---

mypy/checker.py
mypy/types.py

This also implements one of my old wishes: `UnionType.make_simplified_union()` should not mutate its argument.

Fix self-check (and therefore mypyc) on older Python versions

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Closes #6399. Pretty simple fix but I ran into it so figured might as well fix it. :man_shrugging:

Don't define a duplicate __init__ for dataclasses

---

mypy/checkexpr.py
mypy/messages.py
mypy/plugins/common.py
mypy/plugins/default.py
mypy/types.py
test-data/unit/check-literal.test

This pull request hacks on supports for union math when using Unions of Literals to index into tuples, NamedTuples, and TypedDicts.
It also fixes a bug I apparently introduced. Currently, mypy correctly reports an error with this code:
class Test(TypedDict):
foo: int
t: Test
t.setdefault("foo", "unrelated value")
...but does not report an error with:
key: Literal["foo"]
t.setdefault(key, "unrelated value")
This diff should make mypy report an error in both cases.
Resolves https://github.com/python/mypy/issues/6262.

Add union math for intelligent indexing

---

.travis.yml
docs/source/command_line.rst
docs/source/config_file.rst
mypy/main.py
mypy/options.py

The old semantic analyzer is still there and can be used with `--no-new-semantic-analyzer`. For running tests one can use `NEWSEMANAL=0`.

Enable new semantic analyzer by default

---

mypy/checkexpr.py
mypy/newsemanal/semanal.py
mypy/types.py
test-data/unit/check-newsemanal.test

Fixes https://github.com/python/mypy/issues/7044
The crash is caused by the fact that `.type` for broken overloads can be `None`. There is another example where we deal with this in `analyze_ref_expr()`. The crash doesn't happen on the old analyzer because it doesn't add the broken overload to the symbol table.
I solve the crash by generating a dummy `Overloaded()` type in this case. An alternative solution would be to re-analyze a broken overload as independent (re-)definitions, but I think this is more error-prone to keep an overload in AST, but a bunch of functions in symbol table.
Using this opportunity I also remove a redundant `add_symbol()` call (we always add the overload before even processing it).
Note that the behavior of the new analyzer is still different from the old one, …

New semantic analyzer: fix crash on broken overload at class scope

---

mypy/meet.py
mypy/subtypes.py
test-data/unit/check-typeddict.test

It is a relatively common pattern to narrow down typed dicts from unions with non-dict types using `isinstance(x, dict)`. Currently mypy infers `Dict[Any, Any]` after such checks which is suboptimal.
I propose to special-case this in `narrow_declared_type()` and `restrict_subtype_away()`. Using this opportunity I factored out special cases from the latter in a separate helper function.
Using this opportunity I also fix an old type erasure bug in `isinstance()` checks (type should be erased after mapping to supertype, not before).

Support selecting TypedDicts from unions

---

mypy/fixup.py
test-data/unit/fine-grained.test

This avoids possible crashes during calculations of meets and joins on a cold update. 
We do this by rejecting a fake ad-hoc `TypeInfo` created by `fixup.py` if a file containing the typed dict fallback was deleted, and instead using the generic `typing._TypedDict` fallback.

Reject fake TypeInfos for TypedDict fallbacks

---

mypy/checker.py
mypy/messages.py
mypy/newsemanal/semanal_newtype.py
mypy/semanal_newtype.py

There's no need for them to be there really and this will allow us to
produce pretty printed types without threading a MessageBuilder
through.

Extract the pretty printing functions from MessageBuilder

---

docs/source/installed_packages.rst

Updated the "Using installed packages" page to link to "Stub files" page (for new users like myself who aren't familiar with stub files).
In the second example in the "Making PEP 561 compatible packages" section, I made it explicit that the `.pyi` file is the stub file.

Add information about stub files to "Using installed packages" docs

---

mypy/stubgen.py
test-data/unit/stubgen.test

Adding 'Any' type to imports when encountered by stubgen (#7090)

---

mypy/newsemanal/semanal.py
test-data/unit/check-overloading.test

Fixes https://github.com/python/mypy/issues/7209
The fix is to never create an "empty" overload that has neither items nor implementation.

Fix crash when broken overload appears in stub file

---

mypy/message_registry.py
mypy/newsemanal/semanal.py
mypy/newsemanal/typeanal.py
mypy/semanal_pass3.py
mypy/typeanal.py
test-data/unit/check-columns.test
test-data/unit/check-flags.test
test-data/unit/check-inline-config.test
test-data/unit/cmdline.test
test-data/unit/fine-grained.test

This makes the message easier to understand for complex types.  Only
do this for the new semantic analyzer, since the old analyzer doesn't
have the information available to do it.

For --disallow-any-generic, print the name of the type

---

setup.py

This does not fix #7221 (which is likely to stay forever), but at least prevents more releases from being pushed with incomplete metadata.

Add minimum Python version to packaging metadata

---

mypy/newsemanal/semanal.py
test-data/unit/check-final.test

Fixes https://github.com/python/mypy/issues/7229
The fix is to not reprocess member expressions that are already bound. We already do this for name expressions.
As a small bonus this may give a minor perf boost.

New analyzer: don't reprocess member expressions that are already bound

---

mypy/checker.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/5846
The fix for crash is kind of straightforward. Previously `active_self_type()` always returned `None` at method scope (sic!)
While working on this I discovered couple other problems:
* Area around checking LSP is generally problematic (see also https://github.com/python/mypy/issues/5425 that I tried to fix earlier but failed). In particular, the are two ways to get current `TypeInfo`, one is from `lvalue.node.info` or `defn.info`, another is using `active_self_type()` (this is rather abusing it IMO). I don't try to fix this here (i.e. switch to always using one way) because this is a relatively large refactoring.
* Currently in type checker we defer nested functions instead of top-level ones. I believe this is not by design and is rather …

Fix the logic in active self-type calculation for current scope

---

mypy/messages.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/typetraverser.py
test-data/unit/check-basic.test
test-data/unit/check-newsemanal.test

When pretty printing types, find all groups of distinct appearing
instances that have the same short name and format them using their
fullnames.
This should eliminate error messages such as `got "List[A]", expected "Sequence[A]"`
(and a bunch of even less tricky ones we were messing up...).

Make type formatting use fullnames whenever there is ambiguity

---

mypy/build.py
mypy/newsemanal/semanal_main.py

Currently in some cases we will write out a lot of duplicate entries
in the dependency lists of modules. Refactor dependency management to
prevent this.

Prevent duplicates in module dependency lists

---

mypy/main.py
mypy/modulefinder.py
test-data/unit/cmdline.test

E.g. with this file layout:
```
src/
anamespace/
foo/
__init__.py
bar.py
```
running
`$ MYPYPATH=src mypy -p foo --namespace-packages`
will traverse into `src/anamespace/foo`
Closes #6989

Support recursive traversal into PEP 420 namespace packages

---

mypy/build.py
mypy/checkstrformat.py
mypy/defaults.py
mypy/report.py
mypy/stats.py
mypy/test/helpers.py
mypy/test/testcheck.py
mypy/test/testcmdline.py
test-data/unit/check-expressions.test
test-data/unit/check-reports.test
test-data/unit/reports.test

Previously when reporting per-line type checking precision, imports were 
treated as empty lines, which seems inconsistent. Now treat an import as
precise if the target module exists, and as imprecise if the target module is 
missing from the build.
Also add a new report, `lineprecision`, which is mostly designed to be used 
in tests. The output is more compact and cleaner than the existing 
XML-based reports.
Make it possible to run report generation tests without using full stubs,
since using full stubs is slow.
This is still not quite perfect. If using module-level `__getattr__`, the import
should probably be treated as imprecise. Also, if a missing name is ignored
using `# type: ignore`, we may want to treat that as imprecise. For multi-line
imports, we only report precision for the …

Report precision stats for imports and add new precision report

---

docs/source/config_file.rst
mypy/config_parser.py

This further extends parsing of the 'cache_dir' configuration option (as originally introduced by #6651) to do environment variable expansion in addition to user home directory expansion. This makes it much easier to integrate mypy with other tools as well as making it possible to create more generic configuration files.

Expand environment variables in cache_dir config

---

mypy/report.py
mypy/stats.py
test-data/unit/check-reports.test
test-data/unit/fixtures/isinstance.pyi
test-data/unit/reports.test

This makes various improvements to type precision reporting:
* Consider literals precise in type checked code.
* Consider class headers precise (I'll improve this later).
* Consider pass/break/continue precise in type checked code.
* Consider call imprecise if target function has imprecise argument
types, and the caller provides one of these arguments.
Some of these are still incomplete (for example, overloaded functions
aren't supported). I'll deal with these issues in follow-up PRs.

Improve type precision stats

---

mypy/checkexpr.py
mypy/checkmember.py
mypy/newsemanal/semanal.py
mypy/semanal.py
test-data/unit/check-class-namedtuple.test
test-data/unit/check-super.test

The previous implementation assumed that all super(T, x) expressions
were for instances of the current class.  This new implementation uses
the precise types of T and x to do a more accurate analysis.
Fixes #5794

Analyze super() expressions more precisely

---

mypy/newsemanal/semanal.py
mypy/nodes.py
mypy/server/aststripnew.py

It is used by aststrip.py, but not by aststripnew.py, so the new
semantic analyzer doesn't need it. Ignoring it makes some future changes
easier.

New analyzer: don't fill ImportAll.imported_names

---

docs/source/config_file.rst
mypy/config_parser.py

This closes #7272; all options in the configuration file that deal with paths will be expanded for the user home directory and environment variables.

Support expansion of all path configuration options

---

mypy/build.py
mypy/freetree.py
mypy/options.py
mypy/server/deps.py
mypy/server/update.py
mypy/test/testdeps.py
mypy/test/testmerge.py
mypy/test/testtypegen.py
mypy/typestate.py
test-data/unit/merge.test

Instead of hanging around to all of them for the entire run of the
process, free ASTs and typechecker state (especially the type map) as
soon as a module is finished being processing.
In order to have this work when generating fine-grained dependencies,
we need to produce fine-grained dependencies much earlier, so
BuildManager now has an `fg_deps` field.
In the daemon, only free typechecker state, since we want to keep ASTs
around to increase recheck speed. (A future change might use an LRU
cache to keep only some around.)

Free typechecker state and ASTs when they are no longer needed

---

scripts/dumpmodule.py
scripts/stubtest.py
tox.ini

This script broke some time ago. Update it and type-check it so at least it keeps "compiling".
The script depends on `scripts/dumpmodule` so add type annotations there as well.
See individual commits for easier review.
Refs: https://github.com/python/mypy/issues/3329#issuecomment-515668522

scripts/stubtest: make it run again and type-check it

---

mypy/newsemanal/typeanal.py
mypy/test/testcheck.py
mypy/typeanal.py
test-data/unit/check-annotated.test
test-data/unit/lib-stub/typing_extensions.pyi

Closes #7021. This adds basic support for `typing_extensions.Annotated`. Currently, we just discard all annotations and resolve to the inner type.
Plugins can use `get_type_analyze_hook` to try to intervene before this step, but most of the arguments that aren't just names or `Literal`-able values will have already been mangled by this point. Nothing other than the type sees any sort of validation, either. See the issue discussion for more on this.

Basic support for typing_extensions.Annotated.

---

mypy/indirection.py
mypy/messages.py
mypy/server/deps.py
mypy/type_visitor.py
mypy/typeanal.py
mypy/types.py
mypy/typetraverser.py

Now that the old semantic analyzer has been purged, I believe we no longer need the ForwardRef type. This commit deletes that type and associated visitor functions.
(This came up during my quest to enable `--warn-unreachable` for mypy, though I'm a little hazy on how exactly -- it's been a while. I think this indirectly helps us improve type precision with our type visitors by further helping clarify the distinction between full-fledged and semantic-analysis-only types?)

Remove the ForwardRef type

---

mypy/checkexpr.py
test-data/unit/check-expressions.test

Fixes https://github.com/python/mypy/issues/6735
The fix may produce some false negatives, since I use the same simple way of fixing as for `--warn-unreachable`.

Disable --strict-equality inside functions that have type variables with value restrictions

---

mypy/checkexpr.py
test-data/unit/pythoneval.test

Fixes https://github.com/python/mypy/issues/7275
As I mentioned in the issue, we can just whitelist some pairs of classes.

Whitelist some equality checks under --strict-equality

---

mypy/metastore.py

Every so often I am trying to test on a semi-broken python that
I built from source on a machine where I hadn't installed sqlite
and it fails because of this and doesn't need to.

Only import sqlite3 when using the sqlite metadata store

---

mypy/checkexpr.py
test-data/unit/check-columns.test
test-data/unit/check-expressions.test
test-data/unit/check-flags.test

Fixes https://github.com/python/mypy/issues/6672
A possible downside is that error messages may be scarier for new users, but on the other hand maybe more people will learn about `Literal`.

 Make --strict-equality stricter with literals

---

mypy/checker.py
mypy/checkexpr.py
mypy/semanal.py
test-data/unit/check-functions.test

This will allow us to report errors in them and also is needed to
support them in mypyc.

Analyze and check default arguments to lambdas

---

mypy/checker.py
mypy/plugin.py
mypy/semanal_shared.py
mypy/typeanal.py

Update some `fail()` methods to accept an error code argument.

Add error code arguments to plugin API

---

docs/source/getting_started.rst

"name" changed to "arg"
closes: #7189

typo error in getting started fixed

---

mypy/fastparse2.py

This fixes a deprecation warning about `<>` in Python 2 that came up every
time the full test suite was run.

Silence deprecation warning from typed-ast in tests

---

mypy/server/aststrip.py

The docstring was accidentally removed while removing the old analyzer. I also make a little update of this docstring, mostly just removing mentions of pass 2 and 3.

Restore docstring for aststrip.py

---

mypy/build.py
mypy/checker.py
mypy/checkexpr.py
mypy/errorcodes.py
mypy/fastparse.py
mypy/message_registry.py
mypy/messages.py
mypy/semanal.py
mypy/semanal_newtype.py
mypy/semanal_typeargs.py
mypy/typeanal.py
test-data/unit/check-errorcodes.test

This adds error codes to the most common messages seen at Dropbox
plus a few others that seem useful.
There are still some others I'm planning to add, but this should cover
the essentials.

Add error codes to many additional messages

---

mypy/meet.py
test-data/unit/check-expressions.test
test-data/unit/check-overloading.test

Fixes https://github.com/python/mypy/issues/7350
This also fixes an unrelated issue that went unnoticed because of a poor test (in that case the problem was because of a callable fallback, which is a metaclass for class objects).
@Michael0x2a if you don't have time to review this soon, then I will merge without waiting to unblock an internal pin move.

Fix is_overlapping_types() logic for fallback instances

---

mypy/binder.py
mypy/checker.py
test-data/unit/check-literal.test

See the test cases for simplified example of currently problematic behaviour when using `--strict-equality`.

Always erase last known value from instances when using binder or partial types

---

mypy/checker.py
test-data/unit/check-async-await.test
test-data/unit/check-errorcodes.test

`-> None` isn't the correct return type annotation for non-returning generators... so stop suggesting it!

Remove bad hints for missing generator return types.

---

mypy/nodes.py
mypy/semanal.py
test-data/unit/check-super.test
test-data/unit/fixtures/__init_subclass__.pyi

semanal: Treat __init_subclass__ as an implicit classmethod

---

mypy/meet.py
test-data/unit/check-expressions.test
test-data/unit/fixtures/python2.pyi

Using this opportunity I also made a tiny refactoring to avoid code duplication (that would grow even bigger if I would also add logic for promotions).

Consider fallback instance promotions in is_overlapping_types()

---

mypy/checkexpr.py
test-data/unit/check-overloading.test

I think this can be re-enabled since https://github.com/python/mypy/issues/5198 was fixed.

Enable TypedDict vs overload interaction that was disabled

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/semanal.py
test-data/unit/check-flags.test

Based on #7099, please see only the second commit.
Currently, in regular files, symbols imported into module A with `from B
import *` are considered explicitly exported from module A as well, i.e.
they are considered part of module's A public API.
This behavior makes sense in stub files as a shorthand (and is specified
in PEP 484), but for regular files I think it is better to be explicit:
add the symbols to `__all__`.
Fixes https://github.com/python/mypy/issues/7042
Further discussion: https://github.com/python/mypy/issues/7042#issuecomment-509005322

 Don't reexport star-imported symbols when implicit reexports are disabled

---

mypy/semanal_typeddict.py
test-data/unit/check-typeddict.test

I fix this one with a refactoring to extract the name
in the function that does the original check on what
type the first argument is.

Fix another "sloppily cast to StrExpr" mypyc bug with TypedDicts

---

mypy/build.py
mypy/semanal.py
test-data/unit/check-modules.test

The issue was reported internally. Currently we never report missing module attributes with `--ignore-missing-imports`.

Report undefined module attributes with --ignore-missing-imports

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Fixes https://github.com/python/mypy/issues/7250
Previously we just skipped attributes that are not ready, now we don't create an incomplete `__init__()` if possible, and if not possible (e.g. if attributes in some base classes are not ready) we allow updating plugin generated methods.

Don't create incomplete __init__ signatures for deferred dataclasses

---

docs/source/final_attrs.rst

"*Final names* ... should not reassigned" misses "be" after "should".

docs/final_attrs.rst: Add missing "be".

---

README.md

The previous link appears to be broken, and this is what I found.

Fixed mypyc github link

---

docs/source/protocols.rst

This PR:
* Adds a mention that `Protocol` is available in `typing` starting with Python 3.8.
* Renames `@runtime` to `@runtime_checkable`.

Update protocol docs

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Fix crash when a dataclass with a no init InitVar is inherited

---

mypy/checkexpr.py
test-data/unit/check-varargs.test

Accept empty list unpacking for function without parameter

---

mypy/fixup.py
mypy/nodes.py
mypy/semanal.py
test-data/unit/fine-grained.test

Currently they will get incorrectly serialized as xrefs because
the symbol table name doesn't match the fullname.
Fix this. (Though I don't love the way I've fixed it, if somebody has
a suggestion for something nicer.)
This could cause nondeterministc crashes under python 3.5 when it led
to crossrefs to crossrefs, since random dict iteration order meant
that the referenced crossref might not be resolved. Add some asserts
to catch these things earlier.

Fix serialization of redefined nodes

---

mypy/checker.py
test-data/unit/check-errorcodes.test

I think using `[assignment]` would be more consistent, currently bad member assignments generate `[misc]`.

Fix error code for member assignments

---

mypy/fastparse.py
test-data/unit/check-errorcodes.test

In particular, allow `# type: ignore [code]` (space after `ignore`).
Add tests for various cases (some of which already worked).

Be more flexible with spaces in "# type: ignore[code]" comments

---

.travis.yml
mypy/checkexpr.py
mypy/fastparse.py
mypy/test/testpythoneval.py
mypy/types.py
mypyc/genops.py
setup.cfg
test-data/unit/check-columns.test
test-data/unit/check-python38.test
test-data/unit/pythoneval.test

A couple things were needed to fix the tests:
* mypy failed because ast.Str.kind doesn't exist
* flake8 run with python3.8 now reports decorated function
redefinitions on the line of the function definition and not the
first decorator which means we would need to noqa overloads *twice*.
I already found it really annoying so I disabled the check.
(But it looks like the next version of pyflakes will fix the overload
issue.)
* pythoneval tests failed due to a bunch of deprecation warnings for
`@coroutine` which I silenced.
* One walrus test had broken because it hasn't been run
* The docstring of `object` changed and we were printing it in an eval test
* The column of something changed in one test
Pleasantly no actually code issues needed to be fixed.

Fix tests on 3.8 and enable it in CI

---

mypy/main.py
mypy/options.py
mypy/test/helpers.py
mypy/test/testcmdline.py
mypy/test/testpep561.py
mypy/test/testpythoneval.py
mypy/util.py
test-data/unit/cmdline.test
test-data/unit/daemon.test

Fixes https://github.com/python/mypy/issues/7368
Fixes https://github.com/python/mypy/issues/7410
This adds some basic support for output styling on Mac and Linux. The formatter does some basic error message parsing because passing them forward in a structured form would be a bigger change, however if you think this is worth doing I can refactor the PR in a more principled way.
To illustrate the result this is how the output would look:

Add support for nicer error output

---

mypyc/genops.py
mypyc/test-data/genops-basic.test

Fixes https://github.com/python/mypy/issues/7406
This makes mypyc-compiled mypy self-check 6% faster, i.e. almost completely undoes the effects of `get_proper_type()`.
The fix is straightforward I just use the implementation of a compiled overload. It looks like mypyc already emits a correct cast (see added tests).

Use native calls for compiled overloaded functions

---

mypy/build.py
mypy/checker.py
mypy/checkexpr.py
mypy/errors.py
mypy/fastparse.py
mypy/messages.py
mypy/semanal.py
mypy/semanal_shared.py
mypy/typeanal.py
test-data/unit/check-errorcodes.test

Associated note should have the same error code as the related
error, so that both will be ignored when the error is ignored.
Also make the default error code for notes to be 'misc', similar
to errors.
As a side effect, error codes for notes are now not shown. I
didn't find any notes which would benefit from having a specific
error code.
Fixes #7384.
Added tests for various notes, but they are not exhaustive.

Add error codes to notes to allow ignoring them

---

mypy/checkmember.py
test-data/unit/check-bound.test

Fixes #7427 
PR fixes using classes with tuple base as bound of `TypeVar`

Handle class with tuple base as TypeVar bound

---

docs/source/command_line.rst
docs/source/config_file.rst
mypy/main.py

This adds an environment variable MYPY_CACHE_DIR which can set the
current cache directory. This variable will override the cache_dir
setting in the configuration but can be overridden via the command line.
Fixes #7016.

Cache directory may be set via environment (#7016)

---

mypy/checkexpr.py
test-data/unit/check-tuples.test
test-data/unit/fixtures/tuple.pyi

Fixed length tuple concatenation

---

mypy/dmypy/client.py
mypy/dmypy_server.py
mypy/main.py
mypy/test/testfinegrained.py
mypy/util.py
test-data/unit/daemon.test

Fixes https://github.com/python/mypy/issues/7438
This PR makes the daemon behave the same way as the normal run (i.e. use colorized output and write a summary line). I also fix a minor bug that the summary line was colorized even if `--no-color-output` was passed.
The idea is quite simple, client passes to the server info about whether we are in tty and if yes server returns nicely formatted output. I tried running various commands on Linux and piping it through `grep`.

Colorize daemon output and add summary line

---

mypy/suggestions.py
test-data/unit/fine-grained-suggest.test

This bypasses pyannotate's parsing and processing of annotations
and allows us to just specify them directly. This is useful because
pyannotate doesn't support Callable.

Format suggestions using the "signature" pyannotate format instead

---

docs/source/command_line.rst
docs/source/config_file.rst

Fixes https://github.com/python/mypy/issues/7439.

Document how to suppress colorized output and summary line

---

mypy/build.py
mypy/dmypy/client.py
mypy/dmypy_server.py
mypy/errors.py
mypy/main.py
mypy/nodes.py
mypy/options.py
mypy/test/testfinegrained.py
mypy/test/testformatter.py
mypy/util.py
mypy_self_check.ini
test-data/unit/cmdline.test
test-data/unit/daemon.test
test-data/unit/fine-grained-blockers.test
test-data/unit/fine-grained.test

This essentially fixes https://github.com/python/mypy/issues/7411
Couple ideas I think may make the much larger amount of output more readable are:
* Use dim color for the source code snippet
* Wrap long error messages so that they are not messed up with file names etc.
An example output (dark terminal on Linux):

Show code snippets on demand

---

mypy/modulefinder.py

Fixes https://github.com/dropbox/sqlalchemy-stubs/issues/77
Alternatively (if this looks too aggressive), we can at least remove `os.path.sep` when performing the check.

Be more aggressive about site-packages in MYPYPATH

---

mypy/build.py

fix for https://github.com/python/mypy/issues/7412 looks pretty simple... not sure if this solution is general enough

Fix 7412: Exception while typechecking: KeyError: 'typing'

---

mypy/checkexpr.py
test-data/unit/check-expressions.test
test-data/unit/check-type-promotion.test
test-data/unit/fixtures/primitives.pyi

Fixes https://github.com/python/mypy/issues/7465

Apply --strict-equality special-casing for bytes also to bytearray

---

mypy/checker.py
test-data/unit/check-generics.test

Fixes https://github.com/python/mypy/issues/2511

Bind self correctly when mapping class methods from supertype

---

mypy/literals.py
mypyc/test-data/run.test
test-data/unit/check-lists.test

Binders are keyed by "literal_hash" which uses the name of the
variable as part of the key. Use the Var node instead so that
shadowing works.
Fixes mypyc/mypyc#695 but also was a bug separate from mypyc.

Fix interaction of list comprehension shadowing and binders

---

mypy/util.py

It turns out it is relatively simple to do this on Windows 10 without dependencies. Note that we can get color output on Windows 7/8 but not really underlining or other VT100 features. This should be supported on all versions of Windows 10 people are running. I'm not sure Windows 7/8 support is worth it here. Windows 7 is EOL at the end of the year, and Windows 8.1 has only 5% market share.
Fixes #7437

Enable output color and effects on Windows

---

mypy/checker.py
mypy/errors.py
mypy/fastparse.py
mypy/fixup.py
mypy/server/update.py
mypyc/genops.py
mypyc/test-data/commandline.test

Currently when we encounter #5423 (when someting is incorrectly
inferred as None), we generate code that casts a variable to None
incorrectly since we are confused about the real type.
Now produce an error message saying to add an annotation when we
detect it.
Fix up the places in mypy this caused errors.

Produce mypyc errors when encountering bug #5423

---

mypy/main.py

In many cases this makes it clickable (Tested with gnome-terminal)
I used HTTP instead of HTTPS as that's used on other places already.

Add http:// in front of the url.

---

docs/source/type_inference_and_annotations.rst

Adds missing `''` around a `print` string argument

Fix missing quotes in sample python snippet

---

mypy/types.py
mypyc/emitclass.py
mypyc/genops.py
mypyc/lib-rt/CPy.h
mypyc/test-data/genops-basic.test
mypyc/test-data/genops-classes.test
mypyc/test-data/genops-optional.test
mypyc/test-data/run-classes.test

This operates by providing default implementations of `__getstate__`
and `__setstate__` for extension classes. Our implementations work by
storing a `__mypyc_attrs__` tuple in each class that we generate and
collecting all of the attributes in it into a dict.
This is is the last big obstacle to supporting black well.
Fixes mypyc/mypyc#697.

Support pickling of extension classes

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/fastparse.py
mypy/fastparse2.py
mypy/messages.py
mypy/nodes.py
test-data/unit/check-classes.test
test-data/unit/check-columns.test
test-data/unit/check-expressions.test
test-data/unit/check-generics.test
test-data/unit/check-inference-context.test
test-data/unit/check-isinstance.test
test-data/unit/check-literal.test
test-data/unit/check-modules.test
test-data/unit/check-namedtuple.test
test-data/unit/check-newsemanal.test
test-data/unit/check-overloading.test
test-data/unit/check-python38.test
test-data/unit/check-tuples.test
test-data/unit/check-typeddict.test
test-data/unit/check-unions.test
test-data/unit/cmdline.test
test-data/unit/fine-grained.test
test-data/unit/parse-python2.test
test-data/unit/parse.test
test-data/unit/pythoneval.test
test-data/unit/semanal-expressions.test

Previously we pointed to the beginning of the call expression if there
was an incompatible argument, which is not great, particularly if there 
are multiple arguments.
Also point to incompatible list/dict/set item instead of the beginning
of a list/dict/set expression.
Note that this may require some `# type: ignore` comments to be
updated.
I had to update the output of many test cases, mostly because line
ordering was changed.

Point error to incompatible argument instead of call expression

---

mypy/checker.py
test-data/unit/check-classes.test
test-data/unit/fixtures/isinstancelist.pyi

Fix a regression caused by https://github.com/python/mypy/pull/7474
The original PR correctly added `is_classmethod=...` in `bind_self()` for supertype, but I didn't notice the same problem (flag not passed) was also present for _subtype_. The fix is trivial.

Pass is_classmethod to bind_self() also for superype

---

mypy/checkexpr.py
test-data/unit/check-expressions.test
test-data/unit/fixtures/python2.pyi

Fixes https://github.com/python/mypy/issues/7465
The previous fix only worked on Python 3.

Apply --strict-equality special-casing for bytes and bytearray on Python 2

---

setup.py

mypyc/lib-rt/setup.py (used for compiling the mypyc runtime library
tests) was getting picked up by the mypyc compilation globs, which
results in it producing a toplevel (!) module named setup.
Don't do that.

Don't compile mypyc/lib-rt/setup.py

---

mypyc/genops.py
mypyc/test-data/run.test

There are a couple parts to this:
* Compile module attribute accesses by compiling the LHS on its own
instead of by loading its fullname (which will be what mypy thinks
its source is)
* Only use the static modules if they have actually been imported
Closes mypyc/mypyc#393.
I ran into this again while finishing up my separate compilation PR and so got annoyed and fixed it.

[mypyc] Fix using values from other modules that were reexported

---

mypy/checker.py
mypy/constraints.py
mypy/join.py
mypy/messages.py
mypy/subtypes.py
test-data/unit/check-classes.test

Fix crash related with __getattr__ and __call__

---

mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-isinstance.test
test-data/unit/check-literal.test
test-data/unit/check-newtype.test
test-data/unit/check-typeddict.test

Fix this issue: https://github.com/python/mypy/issues/7478
I reused an existing error message, but noticed it has a grammatical error where it uses the word "a", but in this case should use the word "an". I considered just removing "a", and decided against it because it would break other tests. Happy to change this error message if needed.

Fix issue 7478

---

mypy/test/data.py
mypyc/test-data/run.test
test-data/unit/check-custom-plugin.test
test-data/unit/check-flags.test
test-data/unit/check-incremental.test
test-data/unit/check-modules-case.test
test-data/unit/check-modules.test
test-data/unit/check-newsemanal.test
test-data/unit/check-optional.test
test-data/unit/cmdline.test
test-data/unit/daemon.test
test-data/unit/diff.test
test-data/unit/fine-grained-modules.test
test-data/unit/fine-grained-suggest.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test
test-data/unit/reports.test

The main motivation here (though I also just like it more) is that
editor indentation modes won't get confused by unnested brackets when
editing test files in python-mode, which I do all the time.

Make tests use \[ to escape brackets instead of [[

---

mypy/fastparse.py

We've got an internal plugin that whines about such things so...

Call repr instead of str to format bytes

---

mypy/test/testfinegrained.py

The tmp_dir we computed and the real path that was showing up in
the output didn't match on OS X in the testSuggestColonMethodJSON
test. Use realpath to fix the issue.

[suggest] Use realpath to canonicalize path in test

---

docs/source/command_line.rst
docs/source/common_issues.rst
docs/source/config_file.rst
docs/source/error_code_list.rst
docs/source/error_code_list2.rst
docs/source/error_codes.rst
docs/source/index.rst
test-data/unit/check-errorcodes.test

There's a general page about what error pages and for, and I document
each error code that is supported, often with code examples.

Document error codes

---

mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/semanal.py
mypy/semanal_infer.py
mypy/subtypes.py
mypy/typeops.py
mypy/types.py
test-data/unit/check-classes.test
test-data/unit/typexport-basic.test

This is accomplished by updating the helper that constructs a callable type
from a func def to fill in the self argument.
This will make check_untyped_defs a lot more useful.

Give self argument the correct type when using check_untyped_defs

---

mypy/server/aststrip.py
test-data/unit/fine-grained.test

Only delete from self.type.names if the key is actually in there.
I've included one test case that this fixes, though I suspect there
are others. Fixes #7238.

Fix aststrip deletion crash

---

mypy/messages.py
test-data/unit/check-functions.test

Fixes [#7527](https://github.com/python/mypy/issues/7527)

Fix 7527: Correct missing positional arguments when more than one optional argument

---

mypy/checker.py
mypy/fastparse.py
test-data/unit/check-columns.test
test-data/unit/check-inference-context.test
test-data/unit/check-literal.test
test-data/unit/cmdline.test
test-data/unit/semanal-typeddict.test
test-data/unit/semenal-literal.test

This seems more logical. If there is a tuple lvalue, we point to the
incompatible tuple item.
Note that this may break some `# type: ignore` statements since
the reported line number may change (but it usually doesn't).

Point incompatible assignment errors to rvalue instead of lvalue

---

mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-errorcodes.test
test-data/unit/check-overloading.test

Either change the error code to match the related error, so that
both will always be ignored at the same time, or switch a note to
an error (in case the relevant error code is hard to predict).
Fixes #7562.

Fix some notes not being ignored when using an error code

---

test-data/unit/pythoneval.test

This is a companion commit dependent on the change
introduced in typeshed PR 3248:
https://github.com/python/typeshed/pull/3248

Switch ret. type of asyncio.gather() to list

---

MANIFEST.in

Adds mypyc/lib-rt to MANIFEST.in so that it gets included in source distributions for building with mypyc.
Verified by:
* applying this change to the v0.730 tag
* running `python setup.py sdist` to generate `mypy-0.730.tar.gz`
* creating and activating a fresh venv via `python3.7 -m venv`
* extracting the tarball
* running `pip install -U pip mypy_extensions typing_extensions typed_ast`
* running `MYPY_USE_MYPYC=1 python setup.py bdist_wheel`

Fix #7570: Include mypyc/lib-rt in source distributions

---

mypy/dmypy_server.py

This is done by setting the raise_exceptions option, which will cause
the exception to continue to be propagated.
Closes #4804.
Tested by introducing a crash in the parser and verifying the message
came through.

Notify client on all dmypy crashes

---

mypy/plugins/attrs.py
mypy/plugins/dataclasses.py
test-data/unit/check-attr.test
test-data/unit/check-dataclasses.test

The dataclasses plugin incorrectly expected json to preserve
the ordering of its dictionaries, which led to spurious errors
about "Attributes without a default cannot follow attributes with one".
Worse, the errors are reported in the wrong file: they use the line
number of the attribute but the file of the dataclass being checked!
Fix the spurious error by serializing attributes in a list, since we
care about the order.
Reporting this error for attributes in parent classes is actually
useful, since multiple inheritance can cause this error. Report the
error at the class definition site causing the problem instead.
(The error message here could certainly be improved, but right
now I just want to fix the "wrong file" bugs, which are I think
the worst kind of bugs after crashes.)

Fix spurious errors in inherited dataclasses in incremental mode

---

mypy/checker.py
test-data/unit/check-python2.test
test-data/unit/check-statements.test

Bugfix 7514

---

docs/source/additional_features.rst
docs/source/cheat_sheet.rst
docs/source/cheat_sheet_py3.rst
docs/source/command_line.rst
docs/source/common_issues.rst
docs/source/conf.py
docs/source/config_file.rst
docs/source/error_code_list.rst
docs/source/existing_code.rst
docs/source/extending_mypy.rst
docs/source/faq.rst
docs/source/generics.rst
docs/source/getting_started.rst
docs/source/installed_packages.rst
docs/source/introduction.rst
docs/source/kinds_of_types.rst
docs/source/metaclasses.rst
docs/source/more_types.rst
docs/source/protocols.rst
docs/source/python2.rst
docs/source/python36.rst
docs/source/stubgen.rst
docs/source/stubs.rst

This is the first part of adding referencing to `mypy`s docs (second part being #7624). I have configured [`intersphinx`](http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) and replaced hardcoded links with `intersphinx` references. IMO this has a huge benefit of maintaining links consistency: while the hardcoded link is unmanageable (for example, currently the link https://pythonhosted.org/six/#six.with_metaclass points to nowhere since `attrs` documentation has moved to www.attrs.org), the `intersphinx` refs are checked implicitly - if a ref is dead, Sphinx will emit a warning when building docs<sup>1</sup>. `intersphinx` is an extension that is included in Sphinx by default, so no extra dependencies needed.
Another advantage is the referencing simplicity: for …

Replace hardcoded links with intersphinx refs in docs

---

mypyc/common.py
mypyc/emitfunc.py
mypyc/emitmodule.py
mypyc/genops.py
mypyc/ops.py
mypyc/test-data/analysis.test
mypyc/test-data/exceptions.test
mypyc/test-data/genops-basic.test
mypyc/test-data/genops-classes.test
mypyc/test-data/genops-statements.test
mypyc/test-data/genops-try.test

Currently this is done for modules and finals, using the fictitious
'module' and 'final' modules. This will have bad interactions with
separate/incremental compilation, so move modules into their own
namespace and just put finals in the static namespace in the obvious
way.

[mypyc] Stop abusing module names for static namespacing

---

mypyc/emitclass.py
mypyc/genops.py
mypyc/lib-rt/CPy.h
mypyc/test-data/genops-classes.test

This lets us eliminate the CPy_FixupTraitVtable hack where we fixed up
vtables at runtime in a hokey manner and will allow us to populate
vtables with entries loaded dynamically from other modules once we
have separate compilation.

[mypyc] Do all vtable setup dynamically at runtime

---

mypyc/emit.py
mypyc/ops.py

Change how we declare and define tuple structs to prepare for separate compilation:
* Wrap declarations in an #ifdef/#define so that multiple modules
can define the same tuple types (since they are structural) and
interoperate properly.
* Declare the undefined values eagerly instead of only when they
are needed, since they might be needed by another compilationg group.
* Declare them with a typedef instead of always writing struct. This
will very slightly simplify some logic for manipulating the type string
later but mostly just looks better.

[mypyc] Tweak how tuple structs are defined

---

mypy/plugins/default.py
mypy/test/testcmdline.py
test-data/unit/check-expressions.test
test-data/unit/cmdline.test
test-data/unit/fixtures/ops.pyi

A recent typeshed change added a modulo argument to int.__pow__
which broke the plugin.
Tested manually. I didn't add a test because to be useful it would
need to be a cmdline test (so it uses the real typeshed) and this
doesn't seem worth adding a slow cmdline test for. Happy to add it if
someone disagrees though.
Fixes #7621.

Fix the int.__pow__ plugin

---

mypy/fastparse.py

We were doing this for Python 2 parsing. Do it for Python 3 also.

Silence the deprecation warning about \u

---

mypyc/emitclass.py
mypyc/genops.py
mypyc/test-data/run-classes.test

Currently if a class inherits from a nonext class or an interpreted
class and doesn't define an __init__, the parent's __init__ is not
invoked. Fix this.

[mypyc] Invoke __init__ functions inherited from non-ext classes

---

mypy/semanal.py
mypy/semanal_namedtuple.py
test-data/unit/check-namedtuple.test

Previously, it was not supported in stubs when checking in Python 2.7 or
3.5 mode.
Closes: #3464

Support NamedTuple class syntax in all stubs

---

mypy/checkexpr.py
mypy/plugins/common.py
mypy/typeops.py
test-data/unit/check-typeddict.test

Also refactored an operation away from `mypy.plugins.common` so that it
is more cleanly reusable. Also kept an alias in the original location
to avoid breaking existing plugins.
Fixes #7644.

Allow TypedDict key with literal type during construction

---

mypyc/emit.py
mypyc/emitclass.py
mypyc/emitmodule.py

This splits the headers we generate into internal headers (containing
type declarations) and external headers (containing function and
object declarations) and refactors declarations to be much more driven
by HeaderDeclaration objects. This will allow us to use
HeaderDeclaration information to populate structures for dynamic
linking in separate compilation.

[mypyc] Reorganization of headers and declarations

---

mypyc/genops.py

Pass around a NonExtClassData instead of stashing it in a member
global. It would be nice to do this with more things also.

[mypyc] Get rid of of self.non_ext_class

---

docs/source/installed_packages.rst

It's very little change, but it wasn't clear for me what `py.typed` actually is when I first read the documentation.

Clarify what py.typed actually is

---

docs/source/class_basics.rst
docs/source/command_line.rst
docs/source/config_file.rst
docs/source/getting_started.rst
docs/source/literal_types.rst
docs/source/running_mypy.rst

* single backticks don't produce verbatim text in ReST (reported by `rst-backticks` hook)
* cleaned up whitespaces reported by `doc8`

Fix ReST linters warnings

---

docs/source/additional_features.rst
docs/source/casts.rst
docs/source/class_basics.rst
docs/source/command_line.rst

* `additional_features.rst`
* `casts.rst`
* `class_basics.rst`
* `command_line.rst`

Crossreferences to standard library in mypy docs

---

docs/source/error_code_list.rst
mypy/checker.py
mypy/errorcodes.py
mypy/ipc.py
mypy/messages.py
mypy/traverser.py
test-data/stdlib-samples/3.2/subprocess.py
test-data/stdlib-samples/3.2/tempfile.py
test-data/unit/check-errorcodes.test
test-data/unit/check-statements.test

Mypy can give false positives about missing return statements
if `__exit__` that always returns `False` is annotated to return
`bool` instead of `Literal[False]`.
Add new error code and documentation for the error code since
this error condition is not very obvious.
Fixes #7577.
There are two major limitations:
1. This doesn't support async context managers.
2. This won't help if a stub has an invalid `__exit__` return type.
I'll create a follow-up issues about the above.

Give error if __exit__ returns False but is declared to return bool

---

mypy/typeops.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/7668

Fix a crash on missing self with --check-untyped-defs

---

mypy/plugins/default.py
test-data/unit/pythoneval.test

This pull request adds a plugin to infer a more precise return type for the `pathlib.Path.open(...)` method.
This method is actually nearly identical to the builtin `open(...)` method, with the only difference being that `pathlib.Path.open(...)` method doesn't have the `file` parameter. So, I refactored the logic in both plugins into a shared helper method.

Generalize the 'open' plugin for 'pathlib.Path.open'

---

docs/source/builtin_types.rst
docs/source/common_issues.rst
docs/source/config_file.rst
docs/source/dynamic_typing.rst

* `builtin_types.rst`
* `common_issues.rst`
* `config_file.rst`
* `dynamic_typing.rst`

Crossreferences to standard library in mypy docs, part 2

---

docs/source/cheat_sheet_py3.rst

Add example of non-mutable mapping to cheat sheet

---

mypy/typeops.py
test-data/unit/check-classes.test

Only return a declared type from __new__ if it is a subtype of the class

---

mypy/messages.py
test-data/unit/check-expressions.test

Currently the code for turning method call errors into operator error
messages doesn't detect __div__ and __cmp__, so fix that.
One of my main motivations here is that this fixes type ignoring these
with an error code, since previously the real error would be
`arg-type` but the note would be `operator`.
I think that longer term it is probably worth having notes automatically take
the error code of the most recent error, or some such, but that is probably worth some discussion.
I'd like to get this into the release https://github.com/python/mypy/issues/7638

Fix operator error messages for __div__ and __cmp__ on python 2

---

mypy/dmypy/client.py
mypy/dmypy_server.py
mypy/util.py

This PR:
* Fixes `MYPY_FORCE_COLOR` interaction with daemon by reading it from client instead from server.
* Adds `MYPY_FORCE_TERMINAL_WIDTH` with a similar functionality.
These (hidden) environment variables can be used by wrapper scripts.

Improve color and terminal width overrides

---

mypy/dmypy/client.py
mypy/semanal.py
mypy/suggestions.py
mypy/test/testfinegrained.py
test-data/unit/fine-grained-suggest.test

This PR adds an option to `dmypy suggest` to replace `Any` in suggested signatures with a dummy name like `FIXME` or `UNKNOWN`. The main question here is whether we should replace only the top-level `Any`s , or also nested one. I am leaning towards the former, but this is not a strong opinion.

Support FIXME names for unknown types in dmypy suggest

---

mypyc/namegen.py
mypyc/ops.py
mypyc/test-data/run.test
mypyc/test/test_namegen.py

Accomplish this by using a mapping that doesn't collide on valid
python identifiers. We map `.` to `___` and the (rare and unlikely,
but possible) `___` to `_3___`. (This collides `___` with `.3`,
which is fine.)
This makes naming not reliant on the order of processing things
which is important for separate compilation, since it will turn out
that most of our "internal" names actually do need to be exported
(but we would still like to shorten the module name part).
I also like the output better, even though it is a little more
verbose, since it makes it obvious what is a module separator and what
is an underscore.

[mypyc] Make namegen not need to use suffixes to disambiguate

---

docs/source/class_basics.rst
docs/source/error_code_list.rst
docs/source/error_code_list2.rst
docs/source/extending_mypy.rst
docs/source/faq.rst
docs/source/final_attrs.rst
docs/source/getting_started.rst
docs/source/protocols.rst

* `error_code_list.rst`
* `error_code_list2.rst`
* `extending_mypy.rst`
* `faq.rst`
* `final_attrs.rst`
* `getting_started.rst`

Crossreferences to standard library in mypy docs, part 3

---

mypy/semanal.py
test-data/unit/check-classes.test
test-data/unit/check-newsemanal.test
test-data/unit/lib-stub/future/__init__.pyi
test-data/unit/lib-stub/future/utils.pyi

This util function has the same signature and basic behavior as `six.with_metaclass`. 
Fixes #7193.

Add support for future.utils.with_metaclass

---

mypy/config_parser.py

Remove new_semantic_analyzer from config parameters

---

mypy/plugins/attrs.py
test-data/unit/check-attr.test

It still works it just emits a warning so there's no need for mypy to freak out about it.

[attrs] Remove error message about deprecated cmp

---

mypy/build.py
mypy/errors.py
test-data/unit/check-custom-plugin.test

This helps with seeing what the issue is (e.g. with django-stubs [1]).
It might be even better to have a traceback there already, no?
1: https://github.com/typeddjango/django-stubs/issues/160

Display exception string when loading a plugin failed

---

mypyc/build.py
mypyc/common.py
mypyc/emit.py
mypyc/emitclass.py
mypyc/emitfunc.py
mypyc/emitmodule.py
mypyc/emitwrapper.py
mypyc/genops.py
mypyc/namegen.py
mypyc/ops.py
mypyc/test-data/run-multimodule.test
mypyc/test/test_commandline.py
mypyc/test/test_emit.py
mypyc/test/test_emitfunc.py
mypyc/test/test_emitwrapper.py
mypyc/test/test_namegen.py
mypyc/test/test_run.py
mypyc/test/testutil.py

This adds support for separate compilation to mypyc.
A `separate` argument is added to `mypycify`. If `True`, mypyc places every
module its own separate shared library. Otherwise it can take a list of groups
of source files that should be placed in a shared library together.
The shared libraries communication with each other using the C API's intended
mechanism for communicating between C extension modules: Capsules.
Each library creates a table of pointers to all of its exported data and stores a pointer
to it in a capsule stored as a module attribute. When a library is loaded, it
loads the linking table capsules from all its dependencies and copies them
into a local copy of the table. (To eliminate the need for a pointer indirection when
accessing it.)
This adds a test mode that will …

[mypyc] Support separate compilation

---

mypy/checker.py
test-data/unit/check-enum.test

This PR adds supports for singleton types in unions using `Enum`s as described in [PEP 484](https://www.python.org/dev/peps/pep-0484/#support-for-singleton-types-in-unions) (without using `Final`).
As suggested by @Michael0x2a in [the corresponding issue](https://github.com/python/mypy/issues/7279#issuecomment-519271635), adding another case to the `is_singleton_type` and `coerce_to_literal` functions allows mypy to recognize an `Enum` with 1 value as a singleton type.
Fixes #7279

Support for singleton types in unions with Enum

---

docs/source/conf.py
docs/source/generics.rst
docs/source/installed_packages.rst
docs/source/introduction.rst
docs/source/literal_types.rst

* `generics.rst`
* `installed_packages.rst`
* `introduction.rst`
* `literal_types.rst`

Crossreferences to standard library in mypy docs, part 4

---

docs/source/more_types.rst

Added references to the `more_types.rst`. This is the second-to-last part of splitting up the changes in #7624 into more readable PRs.

Crossreferences to standard library in mypy docs, part 6

---

docs/source/kinds_of_types.rst
docs/source/metaclasses.rst
docs/source/python2.rst
docs/source/python36.rst
docs/source/running_mypy.rst
docs/source/stubs.rst
docs/source/supported_python_features.rst
docs/source/type_inference_and_annotations.rst

* `kinds_of_types.rst`
* `metaclasses.rst`
* `python2.rst`
* `python36.rst`
* `running_mypy.rst`
* `stubs.rst`
* `supported_python_features.rst`
* `type_inference_and_annotations.rst`

Crossreferences to standard library in mypy docs, part 5

---

docs/source/protocols.rst

Added references to the `protocols.rst`. This is the last part of splitting up the changes in #7624 into more readable PRs.

Crossreferences to standard library in mypy docs, part 7

---

docs/source/getting_started.rst

This PR adds a quick typo fix to the [MyPy Getting Started Docs](https://mypy.readthedocs.io/en/latest/getting_started.html). 
The initial typo does not necessarily reduce the readers comprehension.

Fix Typo in Getting Started Docs

---

README.md

ALE is another popular plugin for integrating linting into Vim; this commit documents how this can also be configured for `mypy` linting (in addition to the existing documentation for Syntastic).

Document how to integrate `mypy` into Vim with ALE

---

mypy/semanal_classprop.py
test-data/unit/check-type-promotion.test
test-data/unit/fixtures/primitives.pyi

Fixes #7714 
Currently this fails a lot of seemingly unrelated tests. I will investigate later.

Promote memoryview to bytes

---

docs/source/extending_mypy.rst
mypy/build.py
mypy/plugin.py
mypy/plugins/common.py
mypy/plugins/dataclasses.py
mypy/semanal.py
mypy/semanal_main.py
mypy/semanal_newtype.py
mypy/server/aststrip.py

Since we only have a single semantic analyzer now, generally only talk
about "the semantic analyzer" instead of "the new semantic analyzer"
in documentation and docstrings.
Plugin documentation still explains the differences between the old
and the new semantic analyzers, since some plugins might not support
the new semantic analyzer yet.

Update references to new/old semantic analyzers

---

mypy/plugins/attrs.py
test-data/unit/check-attr.test
test-data/unit/check-flags.test

This is important because `--disallow-incomplete-defs` is basically unusable otherwise, and I want to use it for e.g. HypothesisWorks/hypothesis#2071.
I'm well aware that this is a terrible hack, but it fixes #5954 for now.  @euresti had sketched out the proper fix but I just got lost in the codebase - hopefully someone will come back and fix it properly later, but for now this is good enough for me.

Avoid creating partial annotations on attrs-classes __init__ method

---

mypy/checker.py
test-data/unit/check-classes.test
test-data/unit/fixtures/dict.pyi

Fixes https://github.com/python/mypy/issues/7722
This skips checking class keywords against `__init_subclass__` for:
* Classes with custom metaclasses, because they can pop the keywords before calling `super()`.
* Classes that are special forms, like `TypedDict` etc.

Fix __init_subclass__ type check

---

mypy/checker.py
test-data/unit/check-abstract.test

This is an attempt at fixing the issue reported in #7631. I'm happy to address any issues that might be present in this first approach.
Fixes https://github.com/python/mypy/issues/7631

Correctly process properties provided in mixins

---

mypyc/build.py
mypyc/emitmodule.py
mypyc/genops.py
mypyc/ops.py
mypyc/test/test_run.py
mypyc/test/testutil.py

Have build_ir return everything in a dictionary (instead of a list of
tuples) and have compile_modules_to_c also return the IR. This allows
us to remove the IR formatting hack from compile_modules_to_c and will
let us add some IR debugging stuff to test_run.

[mypyc] Rework return values from build_ir and compile_modules_to_c

---

mypyc/emitmodule.py

Final variables were being declared twice, once via HeaderDeclaration
and once manually. Get rid of the manual one and always go through
HeaderDeclaration.
Fixes mypyc/mypyc#703.

[mypyc] Fix multi-file linker error on macOS

---

mypyc/test/test_run.py

A similar refactor is going to be needed for doing multi-stage testing
and this separates the reindentation noise from real changes.

[mypyc] Split a bunch of logic in test_run into another method

---

mypy/checkmember.py
mypy/typeops.py
test-data/unit/check-classes.test
test-data/unit/fixtures/object_with_init_subclass.pyi

Fixes https://github.com/python/mypy/issues/7735
The fix is quite straightforward, this was not triggered before because all common cases go troigh other code paths.

Fix accessing unannotated implicit class methods

---

docs/source/common_issues.rst
mypy/message_registry.py
mypy/semanal.py
mypy/typeanal.py
test-data/unit/cmdline.test

This commit introduces a recommendation for classes that don't support indexing at runtime to be escaped as string literals on missing required generic type args (BARE_GENERIC) error.
It should resolve https://github.com/python/mypy/issues/7539
This is my first time contributing here, so please let me know if there is anything I could have done better. :)

Add recommendation to use string literal escaping

---

mypy/build.py
mypy/errors.py
mypy/main.py
mypy/options.py

It is a common use case to integrate mypy into an IDE or other
environment where it's run automatically and its output is processed by
other programs instead of being read by a human.
IDEs usually are able to parse paths, lines and messages printed by mypy
and show those messages directly in their code editor right under
affected lines.
However, some IDEs, like PyCharm, support reading only absolute file
paths from tools' output.
For example, there is an issue in PyCharm's issue tracker asking for a
way to read relative paths from tools:
https://youtrack.jetbrains.com/issue/IDEA-48163
Sadly, that issue did not receive any action for 11 years already,
apparently. And there is a comment from someone saying that mypy is
affected by this problem, not having any way to force absolute paths in …

Add option to print absolute file paths

---

mypyc/build.py
mypyc/emitmodule.py
mypyc/test/test_run.py

The idea here is just that it reduces the number of compiler
invocations which speeds things up and reduces spew.

[mypyc] include instead of compiling rt .c files in non-multifile mode

---

docs/source/command_line.rst

Also added references in ``command_line.rst``. This is another suggestion for adding crossrefs to the docs. If you like this suggestion, I will add more PRs that replace verbatim option texts with references in chunks (same approach as with the stdlib crossrefs).
When reading the docs in the other PR I made earlier, I noticed the command line options are referenced throughout the docs. For that, a label is added above the command line paragraph which is linked by using the `ref` role. Although this does generate a valid link, e.g. in [Import discovery](https://mypy.readthedocs.io/en/latest/config_file.html#import-discovery):
this doesn't look nice (the verbatim formatting is missing and the double hyphens are merged to an em dash) and the overall construct (adding an anchor and using …

Mypy command line options reference anchors

---

docs/source/error_code_list.rst
docs/source/existing_code.rst
docs/source/running_mypy.rst
mypy/build.py
mypy/test/testpep561.py
test-data/unit/check-errorcodes.test
test-data/unit/check-flags.test
test-data/unit/check-incremental.test
test-data/unit/check-literal.test
test-data/unit/check-modules.test
test-data/unit/check-python2.test
test-data/unit/check-semanal-error.test
test-data/unit/check-unreachable-code.test
test-data/unit/cmdline.test
test-data/unit/fine-grained-blockers.test
test-data/unit/fine-grained-modules.test
test-data/unit/fine-grained.test
test-data/unit/pythoneval.test
test-data/unit/semanal-errors.test

It can be difficult to understand the missing module error message at times.
Changes 
> Cannot find module named '{}'
to
> Cannot find implementation or library stub for module named '{}'
This improves https://github.com/python/mypy/issues/4542
Great thanks to all that participated in that discussion, this is all of our work.
@JukkaL

Improve missing import message

---

mypy/semanal.py
test-data/unit/check-namedtuple.test
test-data/unit/pythoneval.test

Produce error when NamedTuple is assigned to attribute

---

docs/source/additional_features.rst
docs/source/command_line.rst
docs/source/common_issues.rst
docs/source/config_file.rst
docs/source/error_code_list2.rst
docs/source/error_codes.rst
docs/source/faq.rst
docs/source/getting_started.rst
docs/source/installed_packages.rst
docs/source/kinds_of_types.rst
docs/source/more_types.rst
docs/source/mypy_daemon.rst
docs/source/python2.rst
docs/source/running_mypy.rst
docs/source/stubs.rst

This is the follow-up of #7784. All options verbatim texts and `:ref:` usages are replaced with the `:option:` role.

Mypy command line options crossreferencing

---

docs/source/stubgen.rst

This is the follow-up of #7784. Added `:option:` directives in `stubgen.rst`.
Note: since there are two programs listing options (`mypy` and `stubgen`), a proper reference should be
```
:option:`program-name --option-name`
```
for example
```
:option:`mypy --py2`
```
(since `stubgen` also offers this option, so the reference to the option alone would be ambiguous otherwise).
Of course, custom text is supported, as with all roles:
```
:option:`--py2 <mypy --py2>`
```
the program name can be thus omitted in link text.

Stubgen command line options reference anchors

---

mypy/checkexpr.py
mypy/suggestions.py
test-data/unit/fine-grained-suggest.test
test-data/unit/typexport-basic.test

Do this by suppressing the use of Any contexts, which cause arguments
to be misinferred. This can cause certain things to be inferred as
`<nothing>` instead of `Any`, but that's seems fine.

[suggest] Fix inference of returned collection

---

mypy/suggestions.py
test-data/unit/fine-grained-suggest.test

Note that this *doesn't* support inference for nested functions.

[suggest] Fix return-type suggestions when there is a nested function

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

The error was:
```
(attr,) = [a for a in all_attrs if a.name == name]
ValueError: not enough values to unpack (expected 1, got 0)
```
- No need to enter in the `else` if all_attrs is empty
- And don't assume that the matching attr exists in `all_attr`

Fix internal error inheriting a dataclass duplicated field #7792

---

mypy/checkstrformat.py
test-data/unit/check-expressions.test

The problematic case was
```
t: Union[Tuple[str, int], Tuple[int, str]] = ('A', 1)
"%s %s" % t
```
The Union was treated as a single value instead of looking at the types inside
The fix consists in checking each of the union types
Two questions:
- I created a `TempNode` for each of the sub types and added the current line to keep some context, not sure it's the right way to do it.
- I'm running the check for all of the types in the union, but I've seen in the code base that it's usually checked for `any()`.
I suppose it shouldn't return an error if one of the types matches the formatting arguments, for instance with `Union[Tuple[str, int], Tuple[str, str, str]]`
If you confirm, I will have to refactor part of the check in a sub-method

handle Union type in string interpolation checker #7763

---

mypy/checkmember.py
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/7821
The same logic is already used for normal methods, I think class methods should be no different.

Use union component as a self-type in class methods

---

mypyc/genops.py
mypyc/lib-rt/CPy.h
mypyc/ops.py
mypyc/ops_misc.py
mypyc/test-data/run-classes.test

The approach here is to generate an extension class while also
populating a dictionary with the appropriate fields for the dataclass
constructor. Once the extension class is created, we swap out the
contents of its `__dict__` with the `__dict__` that `dataclass`
expects, invoke `dataclass`, and then put back all the original stuff.
Fixes #671.

[mypyc] Support generating extension classes for dataclasses

---

mypy/server/astdiff.py
test-data/unit/diff.test

Previously the snapshots could be unsortable, since the snapshot
tuples could have inconsistent types. This attemps to make the types
in tuples predictable based on the tuple prefix.
More formally, consider these two snapshot tuples:
```
(x1, ..., xn, xn+1, ...)
(y1, ..., yn, yn+1, ...)
```
If `(x1, ..., xn)` == `(y1, ..., yn)`, `xn+1` and `yn+1` must be
comparable.
Attempt to fix #7834.

Fix crashes in astdiff when sorting union items

---

setup.py

This will be useful when you want to use a stable compiler while
testing changes under mypyc.

Add a env var to allow compiling with a different mypy checkout

---

mypyc/emit.py
mypyc/genops.py
mypyc/ops.py
mypyc/options.py
mypyc/test-data/run-multimodule.test
mypyc/test/test_run.py
mypyc/test/test_serialization.py

Currently all of the global optimizations are based on the children
list, so the strategy here is to disable tracking that in separate
compilation mode. Consumers of that information then need to handle
this case.

[mypyc] Support disabling global optimizations

---

docs/source/extending_mypy.rst
mypy/build.py
mypy/interpreted_plugin.py
mypy/plugin.py
test-data/unit/check-incremental.test
test-data/unit/plugins/config_data.py

This is useful in general for plugins that might have per-module
configuration and we will be able to use it to manage the interaction
between mypyc caches and mypy caches without needing to add custom
mypyc hooks.

Add a plugin hook for specifying per-module configuration data

---

mypyc/genops.py
mypyc/test-data/exceptions.test
mypyc/test-data/genops-basic.test
mypyc/test-data/genops-try.test

ExpressionStmts had their Expressions' unused results type-checked unnecessarily.
Fixes mypyc/mypyc#489.

Don't coerce the result of an ExpressionStmt's Expression

---

test-data/unit/check-namedtuple.test
test-data/unit/check-typeddict.test

Fixes https://github.com/python/mypy/issues/4812
The fix itself was likely the new semantic analyzer. I just add test cases from the issue.

Add tests for double forward references in NamedTuple and TypedDict

---

mypy/build.py
mypy/interpreted_plugin.py
mypy/plugin.py
test-data/unit/plugins/config_data.py

This allows plugins to implement more elaborate checking where they do some checks
themselves while producing config data.

Add an is_check parameter to report_config_data

---

mypy/build.py
mypy/main.py
mypy/options.py

I find it irritatingly noisy as part of `--verbose`, especially when
using verbose to debug incremental tests.

Make `dump_stats` under its own flag

---

mypy/test/data.py

It has caused me grief several times and helped me zero times. We nuke
the temporary directory anyways, so why bother carefully trying to
deconstruct it first.
(This is blocking some tests I want to add for mypyc. I could probably fix it with some hack like I have for these things in the past but this seems better.)

Get rid of all of the clean_up tracking in the test suite

---

mypyc/build.py
setup.py

No need to make this decision at module load time. Push it back to
when we need to instantiate things.

[mypyc] Postpone when decide setuptools or distutils

---

mypy/checkexpr.py
test-data/unit/check-unions.test

Fix error when assigning a ternary with an empty collection to a union type variable 

---

mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-kwargs.test

This fixes the following case outlined in #824
```python
def f(other: A) -> None: pass
f(otter: A())
```
`Unexpected keyword argument "otter" for "f"`
is now 
`Unexpected keyword argument "otter" for "f";  did you mean "other"?`

Show closest candidates for misspellings : keyword argument case

---

misc/download-mypyc-wheels.py
misc/dump-ast.py
mypy/stubgen.py
mypy/stubgenc.py

Also make them canonical with regard to whitespace with other executable
scripts.

Add shebang lines to stubgen scripts

---

mypy/checkmember.py
mypy/message_registry.py
mypy/typeanal.py
test-data/unit/check-classvar.test
test-data/unit/semanal-classvar.test

The existing check is overly strict, because we already have a check at the use site. Also this makes  instance variables, class variables and class methods more consistent/homogeneous.
(I will merge as soon as tests pass, since this PR is small and it blocks https://github.com/python/mypy/pull/7885)

Allow generic class variables

---

mypy/checker.py
mypy/typeops.py

I keep wanting access to these functions outside of checker.py in various diffs I'm working on.
So as suggested earlier, I might as well just do this refactoring now, independent of the other PRs.

Move some enum and literal related type ops to typeops.py

---

mypy/constraints.py
test-data/unit/check-inference.test

Fixes https://github.com/python/mypy/issues/6417
Currently constraint inference against unions excludes trivially unsatisfiable items, but a corner case of a plain type variable was missing, so I add one.
(Note: this may help with constraint inference for recursive types.)

Tweak constraint inference against unions to exclude more unsatisfiable items

---

mypy/options.py

The issue was that the mechanism for transmitting Options to the daemon
on Windows used snapshot/apply_changes and those don't play well with
read-only attributes when compiled.
I've fixed this in the most expedient way for now but will do some
follow ups to clean up this mechanism and hopefully test this on
Windows in CI.

Fix compiled dmypy on Windows

---

mypy/checkmember.py
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/7926
The fix is straightforward, pass `is_classmethod` where it should be. Also wrap self argument in `Type[...]` only once, not on every iteration over overload items.

Fix self-types in access to overloaded class methods on instances

---

mypyc/build.py
mypyc/common.py
mypyc/emitmodule.py
mypyc/genops.py
mypyc/test-data/run-multimodule.test
mypyc/test/test_run.py
mypyc/test/testutil.py

This works by reworking IR generation to proceed a SCC at a time and
writing out caches of serialized IR information so that we can
generated code that calls into a module without compiling the module
in full. A mypy plugin is used to ensure cache validity by checking
that a hash of the metadata matches and that all of the generated source
is present and matches.
Closes mypyc/mypyc#682.

[mypyc] Support incremental compilation

---

MANIFEST.in
mypyc/build.py
mypyc/lib-rt/module_shim.tmpl

The point of this is that the file can now be used as a bazel
template.

[mypyc] Move the shim_template to a file

---

mypy/checker.py
mypy/typeops.py
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/7925
This PR:
* Moves `TypeVarExtractor` to `typeops.py`
* Infers and applies all and only type variables that appear in an explicit `self` type (instead of just always the first one as currently)

Make constraint inference in bind_self() more principled

---

mypyc/build.py
mypyc/common.py
mypyc/emit.py
mypyc/emitmodule.py
mypyc/test-data/run-multimodule.test
mypyc/test/test_run.py

Single-module groups will be given a dotted group name equal to the
module name by default.
A dot in a group name will put the group C extension at that
path. Generated C could will also be placed in a directory
corresponding to the full dotted name (still under the build
directory).
The direct motivation here is that bazel wants artifacts to be under
the appropriate directory, but it is cleaner in general I think.

[mypyc] Allow dots in group names

---

mypyc/build.py

This cleans things up a bit and makes it easier to build (unstable and
unsupported!) alternate build system integrations by separating out
most of the details of creating the C from anything setuptools
related.

[mypyc] Reorganize mypyc.build to pull main logic out of mypycify

---

mypy/checker.py
mypy/checkexpr.py
mypy/test/testcheck.py
mypy/typeops.py
mypy/types.py
test-data/unit/check-narrowing.test
test-data/unit/fixtures/tuple.pyi

This diff adds support for the following pattern:
```python
from typing import Enum, List
from enum import Enum
class Key(Enum):
A = 1
B = 2
class Foo:
key: Literal[Key.A]
blah: List[int]
class Bar:
key: Literal[Key.B]
something: List[str]
x: Union[Foo, Bar]
if x.key is Key.A:
reveal_type(x)  # Revealed type is 'Foo'
else:
reveal_type(x)  # Revealed type is 'Bar'
```
In short, when we do `x.key is Key.A`, we "propagate" the information we discovered about `x.key` up one level to refine the type of `x`.
We perform this propagation only when `x` is a Union and only when we are doing member or index lookups into instances, typeddicts, namedtuples, and tuples. For indexing operations, we have one additional limitation: we *must* use a literal expression in order for narrowing to work at all. …

Refine parent type when narrowing "lookup" expressions

---

mypy/typeops.py
test-data/unit/check-selftype.test

This previously caused small troubles in Dropbox internal codebase C (because of weird annotations).
For example if an `__init__()` of class `C` had its `self` argument annotated with one of its superclasses `B`, this made all calls to `C()` inferred as `B`, causing spurious errors.
This PR also makes explicit types in `__new__()` and `__init__()` treated in a more similar way.

Ignore invalid self types in constructors

---

mypy/checker.py
test-data/unit/check-classes.test

resolves #7920 
Currently, no testcases break so I did not look into  `meet.py` for further investigation

Fix `issubclass()` to narrow down types of type variables

---

mypy/main.py

This is in general better but specifically works around
mypyc/mypyc#707.

Get NoReturn from typing_extensions instead from typing

---

mypy/fastparse.py

The Python 3.8 ast stubs now (correctly!) indicate that a key in Dict
can be None. Fix fastparse to deal with this. Really the typed_ast stubs
should say this also.

Fix typechecking on Python 3.8

---

docs/source/literal_types.rst
mypy/checker.py
mypy/checkexpr.py
mypy/checkmember.py
mypy/erasetype.py
mypy/types.py
test-data/unit/check-columns.test
test-data/unit/check-enum.test
test-data/unit/check-errorcodes.test
test-data/unit/check-expressions.test
test-data/unit/check-inference-context.test
test-data/unit/check-literal.test
test-data/unit/check-newsemanal.test
test-data/unit/check-optional.test
test-data/unit/check-python38.test
test-data/unit/check-typeddict.test
test-data/unit/check-unreachable-code.test
test-data/unit/check-varargs.test
test-data/unit/merge.test
test-data/unit/typexport-basic.test

This diff changes how we format Instances with a last known value when displaying them with `reveal_type`.
Previously, we would always ignore the `last_known_value` field:
```python
x: Final = 3
reveal_type(x)  # N: Revealed type is 'builtins.int'
```
Now, we format it like `Literal[3]?`. Note that we use the question mark suffix as a way of distinguishing the type from true Literal types.
```python
x: Final = 3
y: Literal[3] = 3
reveal_type(x)  # N: Revealed type is 'Literal[3]?'
reveal_type(y)  # N: Revealed type is 'Literal[3]'
```
While making this change and auditing our tests, I also discovered we were accidentally copying over the `last_known_value` in a few places by accident. For example:
```python
from typing_extensions import Final
a = []
a.append(1)
a.append(2)     # Got no …
```

Make revealed type of Final vars distinct from non-Final vars

---

mypy/checkmember.py
test-data/unit/check-generics.test
test-data/unit/check-selftype.test
test-data/unit/lib-stub/abc.pyi

See https://github.com/python/mypy/issues/7863 for background context.
A few small notes.
1- Assignment to `t` on line 529 of checkmember.py was not being referenced til 535. Unless `get_proper_type(expand_type_by_instance(typ, itype))` is mutating `typ` or `itype` then this created ambiguity for me around whether lines 530-534 were going to be impacted by my overall change. Since it appears not to be the case, I figured it's clearer to introduce `t` no earlier than it is used, (which in hindsight with the rest of the change could probably be even later in the function.)
2- Changes to check-selftype.test appear to be a result of calling `bind_self` before `get_proper_type(expand_type_by_instance(signature, itype))` - my understanding is that `bind_self` does not register inference by …

Fix issue 7863

---

mypy/renaming.py

Fix simple typo: usuaully -> usually

---

mypy/types.py

This fixes the typo in the argument name and deals with the "fallout".
cc @Michael0x2a I double-checked and the error mypy gives is technically real, but the unsafety is so minor that I think we should assume all generics in return types covariant for overlapping overload checks.

Fix typo in get_proper_types()

---

mypy/test/teststubgen.py

It appears they do not work. If I had to guess, its something to do with the order in which the contexts are cleaned up. Perhaps reversing the nesting of the `with` and `try/finally` would help.

Skip some stubgen tests on Windows

---

mypy/checkexpr.py
test-data/unit/fine-grained-suggest.test

We weren't computing the proper fullname through TypeType (only
through type obj callables. Maybe we should get rid of those...)
This fixes these getting missed by suggestions.

Fix plugin invocation on classmethod calls through `Type`

---

mypy/dmypy/client.py
mypy/suggestions.py
mypy/test/testfinegrained.py
test-data/unit/fine-grained-suggest.test

Rework max guesses to be configurable and to throw out guesses past
the limit instead of just hard failing. This might allow succeeding in
more situations. Eliminate the maximum argument restriction since we
no longer have to compute all of the options even if we don't try
that.

[suggest] Rework max guesses and eliminate max args

---

mypyc/build.py
mypyc/cstring.py
mypyc/emitmodule.py

Using `repr()` to encode C strings relied on implementation-defined behaviour and had a number of bugs, for example:
* The C string could inadvertently contain trigraphs.
* Valid hexdecimal characters following a hexadecimal escape sequence would be parsed as part of the escape sequence.
Octal escape sequences are used for unprintable characters because they do not have the same issue as hexadecimal escape sequences.
It would be possible to mitigate the issue with hexadecimal escape sequences by emitting multiple string literals. However, the complexity is not worth it, especially as the output is not designed to be human-readable.
As an ad hoc test, I generated a Python module containing string literals for every possible character:
```python
with open("literals.py", "w") as f:
f.write( …
```

mypyc: Fix C string encoding

---

mypy/constraints.py
mypy/suggestions.py
mypy/types.py
test-data/unit/fine-grained-suggest.test

This is another take at #7810 which was reverted because it caused
internal trouble.
Do this by ignoring constraints with Any when the Any comes from the
suggestion engine. The Any context causes assigned types to be Any
overaggressively.  Restricting it only to Anys from the suggestion
engine avoids the issues seen last time. Doing it at a fine-grained
level in constraints allows us to do better refining things like `List[Any]`.

[suggest] Fix inference from collection literals

---

mypyc/genops.py
mypyc/test-data/commandline.test
mypyc/test-data/run-classes.test

This is a global behavior that will be solidly busted when doing
separate compilation. Produce an error instead. (We can probably
support it once we support interpreted inheritance.)

[mypyc] Don't make classes non-extension because of children

---

mypy/options.py
mypy/test/testdaemon.py
test-data/unit/daemon.test

If a configuration contains globs, then dmypy incorrectly detected
that the configration changed even though it did not.
This caused the daemon to always restart if a configuration contained globs.
Fixes #7576.

Prevent dmypy from restarting if the configuration contains globs.

---

mypy/erasetype.py
test-data/unit/check-expressions.test

This pull request modifies the `last_known_value` eraser so it always copies over the previously inferred value of the `can_be_true` and `can_be_false` fields.
This isn't entirely typesafe -- for example, we can sometimes accidentally infer the wrong result if we try reassigning variables or call a mutating function :
def bad1(a: List[str], b: bool) -> bool:
x = a and b
a = ["foo"]
y: bool
return x or y   # Should be an error
def bad2(a: List[str], b: bool) -> bool:
x = a and b
a.append("foo")
y: bool
return x or y   # Should be an error
But this was apparently the old behavior/something mypy wasn't previously able to detect, so I guess this is fine for now.
I also decided against modifying every `copy_modified` method in all the type classes because of this reason: I wanted to limit the …

Preserve can_be_true and can_be_false when copying types

---

mypyc/genops.py
mypyc/test-data/run-multimodule.test
mypyc/test/test_run.py

Certain parts of the mypy AST aren't present and we were relying on
them anyways. This caused a crash when subclassing and classes not
making it into the type table, preventing using fast paths.

[mypyc] Fix some deserialization related issues

---

mypy/messages.py
test-data/unit/check-generics.test

Shortened names can be confusing.

Don't shorten long generic types in messages

---

mypy/checkexpr.py
mypy/checkmember.py
mypy/messages.py
test-data/unit/check-columns.test
test-data/unit/check-modules.test
test-data/unit/pythoneval.test

Addresses the remainder of issue #824

Implements module attribute suggestions

---

mypy/semanal.py
test-data/unit/check-custom-plugin.test
test-data/unit/plugins/dyn_class_from_method.py

I would like to see this merged, and don't know if @mkurnikov has time to follow up, so I decided to make a PR based on his, which implements the suggestions from the review comments.
https://github.com/python/mypy/pull/7704
@ilevkivskyi I have implemented your suggestions (as far as I understand them), but I'm not sure how to test that they are working.
Fixes #7266

Invoke get_dynamic_class_hook on method calls

---

mypyc/genops.py
mypyc/test-data/commandline.test
mypyc/test-data/run-classes.test

Closes mypyc/mypyc#708.
Fixes a crash into an error message for overloads also.

[mypyc] Fix overloaded methods in non-extension classes

---

mypy/checker.py
test-data/unit/check-basic.test

Fix false positive: return Any from a function declared to return object

---

mypy/test/teststubgen.py

C modules in the standard library don't seem to have a __file__ in
the Python distributions that ship with Ubuntu. I think maybe they
are built into the binary? I don't know.

Remove a semi-broken stubgen assert

---

mypy/semanal.py
test-data/unit/check-literal.test
test-data/unit/check-type-aliases.test

resolves #7996
I'm not very sure about how effective the current testcase is, suggestions are welcomed.

Support type alias as Literal

---

mypy/checkmember.py
test-data/unit/check-generics.test
test-data/unit/check-selftype.test

Fixes https://github.com/python/mypy/issues/8020
There is a bunch of code/logic duplication around `bind_self()`, mostly because of https://github.com/python/mypy/issues/7724. This PR makes all three main code paths consistently follow the same structure:
1. `freshen_function_type_vars()`
2. `bind_self()`
3. `expand_type_by_instance(..., map_instance_to_supertype())` (a.k.a `map_type_from_supertype()`)
I briefly scrolled through other code paths, and it looks like this was last major/obvious inconsistency (although code around `__getattr__`/`__setattr__`/`__get__`/`__set__` looks a bit suspicious).

Make logic around bind_self() consistent in different code paths

---

docs/source/more_types.rst

Now that `TypedDict` is an official feature I think this would make sense.

Recommend typing_extensions instead of mypy_extensions for TypedDict

---

mypy/suggestions.py
test-data/unit/fine-grained-suggest.test

This would trip an assert in the `__init__` of AnyType. I fixed the
crash by properliy handling it.

[suggest] Fix crash when refining type with unresolved import type name

---

mypy-requirements.txt
mypyc/emitclass.py
mypyc/genops.py
mypyc/ops.py
mypyc/test-data/commandline.test
mypyc/test-data/run-classes.test
setup.py
test-data/unit/lib-stub/mypy_extensions.pyi

This operates by generating a "shadow vtable" containing pointers to
glue methods that dispatch to the appropriate method via the C API. We
then install those shadow vtables in interpreted subclasses so that
overridden methods will be called.
This does not support directly inheriting from traits, which I think
will require generating vtables dynamically (and maybe some more
nonsense too.)
Closes #296. (Though I will file a follow-up for traits.)

[mypyc] Add a mypyc_attr to support interpreted children

---

docs/source/stubgen.rst

Add missing options to stubgen docs and mention new heuristics it
uses to skip test and vendored modules.

Update stubgen docs

---

mypy/checkmember.py
mypy/expandtype.py
test-data/unit/check-generics.test

This is a follow up for https://github.com/python/mypy/pull/8021, that applies the fix also to non-callable types. Currently non-callable types are still wrong:
```python
R = TypeVar('R')
T = TypeVar('T')
def classproperty(f: Callable[..., R]) -> R: ...
class C(Generic[T]):
@classproperty
def test(self) -> T: ...
x: C[int]
y: Type[C[int]]
reveal_type(x.test)  # Revealed type is 'int', OK
reveal_type(y.test)  # Revealed type is 'T' ???
```
So, https://github.com/python/mypy/issues/7724 strikes again. It turns out there is not only duplicated logic for attribute kinds (decorators vs normal methods), but also for callable vs non-callable types. In latter case we still need to expand the type (like in other places, e.g., `analyze_var`).

Apply generic class fix also to non-callable types

---

mypy/checker.py
mypy/errors.py
test-data/unit/check-inference.test

Code like this no longer requires a type annotation:
```
a = []
if foo():
a = [1]
```
Work towards #1055.

Infer type for partial generic type from assignment

---

docs/source/mypy_daemon.rst

The mypy daemon has been the default way of running mypy locally
at Dropbox for well over a year. It's quite stable, though a few important
features are missing.

Mypy daemon is no longer experimental

---

mypy/checker.py
mypy/checkexpr.py
test-data/unit/check-inference.test
test-data/unit/lib-stub/collections.pyi

This example no longer needs a type annotation:
```
from collections import OrderedDict
x = OrderedDict()
x[1] = 'x'
```
Work towards #1055.

Improve type inference by supporting partial OrderedDict types

---

mypy/test/helpers.py
test-data/unit/check-literal.test

While working on https://github.com/python/mypy/pull/8024 I noticed that `# flags: --python-version X.Y` and `# flags: --python-version=X.Y` are not treated equally by the test harness, namely the latter is actually ignored. This PR should fix this, because both forms are actually used in tests.
@Michael0x2a there is some suspicious change in literal types, is it expected?

Treat --python-version X.Y and --python-version=X.Y in tests equally

---

mypy/checker.py
mypy/messages.py
test-data/unit/check-tuples.test

resolves #7977 
Current format of error message(especially for item-by-item case) need discussion
request for review if you are free @JukkaL @ilevkivskyi

Meaningful message with long tuple initializer

---

mypy/checker.py
mypy/checkexpr.py
test-data/unit/check-inference.test
test-data/unit/fine-grained.test

Work towards https://github.com/python/mypy/issues/1055
Currently partial types are supported for local variables. However, only partial `None` types are supported for `self` attributes. This PR adds the same level of support to generic partial types. They follow mostly the same rules:
* A partial type can be refined in the _same_ method where it is defined.
* But a partial type from class body can not be refined in a method, as if `local_partial_types = True`.
The logic is pretty simple: the `.node` attribute for `self.attr` expressions is set to `None`, so I added a little helper to get it from the class symbol table instead.
I add tests for various scenarios, including for partial `None` types. It may happen they are already tested elsewhere, but this way it is easy to compare …

Support generic partial types for attributes

---

mypy/build.py
test-data/unit/cmdline.test

Better error message when using pyd file as stubgen

---

mypy/checkmember.py
test-data/unit/check-serialize.test

Fixes https://github.com/python/mypy/issues/8072
The fix is straightforward, just copy the logic from the working case (see last test) to two other code paths. Note that only two first cases I added crash on master, but I also add the last one for completeness because I didn't find a similar existing test case.

Always freeze type variables that were previously freshen

---

mypy/constraints.py
test-data/unit/check-inference.test
test-data/unit/check-overloading.test
test-data/unit/pythoneval.test

Fixes https://github.com/python/mypy/issues/8051
The fix is as discussed in the issue. I didn't find a test case for the union `actual`, but I think it makes sense to simplify it as well. Note: I add the `pythoneval` test just as a regression test, if you think it is not worth it, I can remove it.

Fix 0.750 regression: union (non-)simplification should not affect inference

---

mypy/checker.py
mypy/checkexpr.py
mypy/type_visitor.py
mypy/types.py

The `inner_types` attribute seems to have no effect.

Refactor: remove unused attribute from PartialType

---

mypy/checkexpr.py
mypy/semanal.py
test-data/unit/check-classes.test

Fixes https://github.com/python/mypy/issues/8079
Previously function scope was pushed inconsistently in two branches of `visit_lambda_expr()` (it was only pushed in the second branch by `check_func_item()`). I believe there is still a small inconsistency, although I wasn't able to trigger a corresponding crash, I added a TODO about this.

Properly push scope when checking lambda expressions

---

mypy/constraints.py
mypy/subtypes.py
mypy/typeops.py
test-data/unit/check-inference.test

Fixes https://github.com/python/mypy/issues/8093
The fix is kind of simple, we really need to keep all `ErasedType`s intact to preserve the existing type inference logic, but it is also long because I need to thread the flag down like dozen function calls.
The issue itself btw highlight how fragile is current type inference logic (note that `expand_type()` implicitly calls `make_simplified_union()` too, but I think that one doesn't need to be updated because it shouldn't be called with any erased components).

Don't simplify out ErasedType from unions during type inference

---

mypy/checker.py
test-data/unit/check-inference.test

Don't infer types such as `List[<nothing>]`; infer `List[Any]` instead.
Fixes #8090.

Fix type inference regression with partial types

---

mypy/join.py
mypy/meet.py
test-data/unit/check-abstract.test

resolves #8050, following the purposed solution 2 in  https://github.com/python/mypy/issues/8050#issuecomment-560322273 and using the implementation purposed in https://github.com/python/mypy/issues/8050#issuecomment-560326219
Currently, no testcase with regard to meet of callables is available, since I'm not sure what a proper testcase would be.

Inferencing type reference of abstract class inferred from concrete type values

---

mypy/nodes.py
mypy/semanal.py
mypy/types.py

This PR:
* Removes three unused slots
* Makes recursivity test once per alias
* Documents an existing optimization (accidentally made before)
The effect of this it at the limit of precision on my laptop, but it looks like this gives around 1% speed-up (for cold runs).

Couple obvious optimizations for type aliases

---

mypy/semanal.py
test-data/unit/check-namedtuple.test
test-data/unit/pythoneval.test

Followed the discussion in https://github.com/python/mypy/pull/8107#issue-350416074, refine the code merged in #7662 by:
- move testcase from `pythoneval.test` to `check-namedtuple.test` and rename it from `testNamedTupleAtRunTime` to `testAssignNamedTupleAsAttribute`
- change `s.lvalues[0]` to `lvalue` to make it more concise

Refine testcase and variable usage for "produce error when assigning NamedTuple to attribute"

---

mypyc/lib-rt/CPy.h
mypyc/test-data/run-classes.test

We need to set `__orig_bases__` before calling the metaclass or it
will get mad.

[mypyc] Fix subclassing from abstract generic classes under 3.7

---

mypyc/genops.py
mypyc/test-data/run-classes.test

`_order_` doesn't make it into the Enum, so don't try to read it.

[mypyc] Fix interaction of Enum caching with _order_

---

mypy/checkexpr.py
mypy/messages.py
test-data/unit/check-errorcodes.test

Previously the error code for the error message was 'call-overload',
which was inconsistent. In addition, the related note had the 'operator'
error code, which made things worse. Now both the error message and
the note have the 'operator' error code.

Fix error code of binary operation involving overload

---

mypy/stubgen.py
test-data/unit/stubgen.test

Stubgen: split @abstractproperty

---

mypyc/genops.py
mypyc/test-data/genops-nested.test

Previously, with multiple lambdas, the second one would be named like `__mypyc_lambda__0_f_obj_0`, since the counter didn't increment. Now, the second one is named like `__mypyc_lambda__1_f_obj`.

Increment lambda_counter

---

mypy/semanal.py
mypy/semanal_enum.py
test-data/unit/check-enum.test
test-data/unit/check-typeddict.test

resolves #8009, simply following solution by #7662 
Additionally, when I was finishing the first version of the PR I noticed that some of #7662 could be refined:
https://github.com/python/mypy/blob/e8ae12293cf1a8e32769c2149f4c8c2ca043b790/mypy/semanal.py#L2152-L2154
Here using `lvalue` instead of `s.lvalues[0]` would be more concise.
https://github.com/python/mypy/blob/e8ae12293cf1a8e32769c2149f4c8c2ca043b790/test-data/unit/pythoneval.test#L1482-L1492
The test is in `pythoneval.test`, but it makes more sense in `check-namedtuple.test` and the name could be also changed accordingly.
@ilevkivskyi What's your opinion on this? Should these changes be made? And if so, should they be made in this PR or a sperate one.

Produce error when assigning Enum or TypedDict as attribute

---

mypy/build.py
test-data/unit/check-incremental.test

This was introduced in #1865 to fix an issue with new children modules
being added. I think we have fixed this issue in another way also since
then, since the important part of the test passes with the check removed.
(I added some more stuff to the test to increase my confidence in this
change).
I want to remove this check because it causes a *ton* of trouble with our
internal bazel integrations, where we try to generate cache artifacts for
each bazel target separately. This check means that bazel targets for
packages have their caches invalidated all the time, since they were
generated without the children.

Don't mark a module as stale if its children change

---

mypy/stubgen.py
test-data/unit/stubgen.test

When __init__ had partial type annotations, for parameters but not for
the return type, the return type was annotated as Any, which is reported
as an error by mypy when checking the generated stubs.
Make sure to annotate the return value as None also in the case of
existing type annotations for
fixes #8110

stubgen: fix return type of annotated __init__

---

mypy/dmypy_server.py
mypy/main.py
test-data/unit/daemon.test

I'm trying to fix issue #8088 , current change is just ignore the file fields in config when start from dmypy start.
I'm still not familier with dmypy, please review the PR and any advice is welcome.

dmypy start doesn't work when files is defined in mypy.ini (#8088)

---

mypy/checkmember.py
mypyc/genops.py
test-data/unit/check-enum.test

The `__order__` attribute is used to determine the definition order of enum values and does not define an enum value itself.

Exclude "__order__" attribute from Enum Union expansion

---

mypyc/lib-rt/CPy.h

On macOS, this made the generated binary about 8% smaller (when
using -O3).

[mypyc] Force type error helper to not be inlined

---

mypy/typeops.py
test-data/unit/check-enum.test

My previous attempt didn't actually work as advertised as it was lacking complete test coverage. It merely handled the case
`Bar.__order__  # E: "Type[Bar]" has no attribute "__order__"`
This PR adds more tests and implements the desired behavior this time.

Actually exclude "__order__" attribute from Enum Union expansion

---

mypy/checker.py
mypy/checkexpr.py
mypy/types.py
mypyc/test-data/fixtures/ir.py
test-data/unit/check-inference.test
test-data/unit/fixtures/dict.pyi
test-data/unit/lib-stub/collections.pyi
test-data/unit/python2eval.test

This allows inferring type of `x`, for example:
```
from collections import defaultdict
x = defaultdict(list)  # Infer defaultdict[str, List[int]]
x['foo'].append(1)
```
The implemention is not pretty and we have probably
reached about the maximum reasonable level of special
casing in type inference now.
There is a hack to work around the problem with leaking
type variable types in nested generics calls (I think).
This will break some (likely very rare) use cases.

Support type inference for defaultdict()

---

mypy/checkexpr.py
test-data/unit/check-inference.test

Previously we inferred a type from an argument like `List[Any]` but
not from plain `Any`, which was inconsistent.

Infer type from "x.extend(y)" where y has type Any (etc.)

---

mypy/constraints.py
mypy/join.py
mypy/meet.py
test-data/unit/fine-grained.test

Fixes #3279. Also fixes another related crash.

Fix some daemon crashes involving classes becoming generic

---

mypy/plugins/dataclasses.py
test-data/unit/check-dataclasses.test

Fixes #8015
Fixes #8022
This fixes two bugs related to dataclass `InitVar`s and overriding `__init__`
by changing mypy to ignore `InitVar`s in parent classes when
the class supplied its own `__init__` and set `(init=False)` on the dataclass.
It also fixes a bug with multiple inheritance of dataclasses.
Previously dataclasses attempted to look up the current class' `__init__` to find
the definition of `InitVar`s, which worked fine as long as the current class was
a direct subclass of the parent and didn't override `__init__`.
Unfortunately that didn't work when the `InitVar` came from a subclass that was
not first in MRO, or the parent had an item in its `__init__` definition that
the subclass didn't use.
Now mypy will look up the `__init__` for the current parent class that is being …

Fix bugs where overriding init in a dataclass subclass crashed mypy

---

mypy/checkexpr.py
test-data/unit/check-inference.test

This improves type inference in code like this:
```
d = {}
for k in f():
if k not in d:
d[k] = 0
else:
d[k] += 1
```
Unfortunately, this change breaks strict equality checking in 'in' operations
involving partial types. I'm not 100% sure this is a net improvement. I couldn't
find a clean way of getting strict equality working together with this.

Allow 'in' operations with partial types

---

test-data/unit/check-dataclasses.test
test-data/unit/check-errorcodes.test
test-data/unit/check-expressions.test
test-data/unit/fixtures/async_await.pyi
test-data/unit/fixtures/bool.pyi
test-data/unit/fixtures/python2.pyi
test-data/unit/fixtures/typing-full.pyi
test-data/unit/lib-stub/typing.pyi
test-data/unit/typexport-basic.test

This speeds up the set of "quick" tests that I typically run by about 2%.

Simplify default test stubs to speed up tests slightly
