docs/source/kinds_of_types.rst
This fixes #570, as well as a rendering error I encountered.
=> Add type alias docs

stubs/3.2/argparse.py, stubs/3.2/builtins.py, stubs/3.2/codecs.py, stubs/3.2/datetime.py, stubs/3.2/getpass.py, stubs/3.2/http/client.py, stubs/3.2/multiprocessing/__init__.py, stubs/3.2/multiprocessing/managers.py, stubs/3.2/multiprocessing/pool.py, stubs/3.2/queue.py, stubs/3.2/socketserver.py, stubs/3.2/subprocess.py, stubs/3.2/tarfile.py, stubs/3.2/threading.py, stubs/3.2/urllib/error.py, stubs/3.2/urllib/request.py, stubs/3.2/uuid.py
Add a few new stub files (all incomplete) and add functions to existing ones.
=> Various random additions to stubs

stubs/3.2/copy.py
Signed-off-by: James Guthrie <james@prodigi.ch>
=> Add copy.copy() to stubs

stubs/3.2/enum.py
Signed-off-by: James Guthrie <james@prodigi.ch>
=> Add value and name attributes to Enum

stubs/3.2/collections.py
Signed-off-by: James Guthrie <james@prodigi.ch>
=> Add stub for Counter.update()

mypy/checker.py, mypy/nodes.py, mypy/parse.py, mypy/semanal.py, mypy/strconv.py, mypy/test/data/check-basic.test, mypy/test/data/check-dynamic-typing.test, mypy/test/data/check-expressions.test, mypy/test/data/check-generics.test, mypy/test/data/fixtures/bool.py, mypy/test/data/fixtures/complex.py, mypy/test/data/fixtures/exception.py, mypy/test/data/fixtures/function.py, mypy/test/data/fixtures/slice.py, mypy/test/data/typexport-basic.test, mypy/traverser.py, mypy/treetransform.py, mypy/visitor.py
Fixes #127. I've also removed the `VarDef` node (issue #246).
=> Changed type of module __name__ (etc) attributes to 'str'

mypy/docstring.py, mypy/parse.py, mypy/parsetype.py, mypy/test/data/check-functions.test
=> Fall back to type info extracted from docstrings to type functions

mypy/stats.py
This makes it easier to diff two reports, for example.
=> Insert newlines in HTML report

mypy/semanal.py, mypy/test/data/semanal-statements.test
=> Fix scope for with statement defining multiple variables

mypy/maptype.py, mypy/nodes.py
These come from a very useful discussion with Jukka yesterday.
=> Expand some comments/docstrings on TypeInfo vs. Instance

mypy/build.py
Fixes #1047. This indeed prefers .pyi over .py always. To type-check x.py in the presence of x.pyi, pass it explicitly on the command line -- but then you have to also pass all the other files in the package on the command line to get the same effect. Anyway, that's less important.
I have two questions:
- I feel there should be a unit test for this. But I can't find any unittests for this section of the code.
- Instead of adding a long block comment for such a minor issue, I could also write a helper function that lists the directory and removes those *.py items that have a matching *.pyi. The total number of lines might be the same, though perhaps it might be easier to grasp. That solution won't catch the issue of having both x/ and x.py[i], but that's pretty theoretical.
Thoughts?
=> Avoid adding x.pyi twice when x.py and x.pyi are both present.

mypy/subtypes.py, mypy/test/data/check-tuples.test, mypy/test/data/lib-stub/builtins.py, mypy/test/data/lib-stub/typing.py
=> Understand that a tuple is also a Container. With test.

mypy/checkexpr.py, mypy/test/data/check-inference.test, mypy/test/data/check-weak-typing.test, mypy/test/data/fixtures/dict.py, mypy/test/data/fixtures/list.py, mypy/test/data/fixtures/set.py
Namely: set.discard, list.extend, {set,dict}.update.
It's getting a little ugly -- not sure how best to refactor this.
=> Add a few more special cases to try_infer_partial_type()

misc/fix_annotate.py, mypy/checkexpr.py, mypy/test/data/check-kwargs.test, setup.cfg
Hopefully this will pass the travis tests. If it does I'll commit it.
=> Fix #1095 (crash on undefined variable actual_types in check_argument_count())

mypy/checker.py, mypy/test/data/check-classes.test
This is not entirely finished -- I just commented out the lines that report the errors while leaving the rest of the flow in.
=> WIP: Rip out offending error messages for issue #1101.

mypy/build.py, mypy/checker.py, mypy/checkexpr.py, mypy/erasetype.py, mypy/errors.py, mypy/exprtotype.py, mypy/main.py, mypy/meet.py, mypy/messages.py, mypy/nodes.py, mypy/parse.py, mypy/parsetype.py, mypy/replacetvars.py, mypy/sametypes.py, mypy/typeanal.py, mypy/waiter.py
follow up to
https://github.com/python/mypy/pull/1250
remove typeshed change; fixes merge conflict.
=> Code Cleanup

mypy/build.py
An attempt to fix https://github.com/python/mypy/issues/1252.
=> Fix for issue #1252.

mypy/test/data/check-functions.test, mypy/typeanal.py
=> Support bare `Callable`

mypy/semanal.py, mypy/test/data/check-namedtuple.test
=> Distinguish between namedtuple without items and errors.

CONTRIBUTING.md, README.md
=> Add a CONTRIBUTING file

CONTRIBUTING.md, README.md
Switch to recommended relative-link format.
=> Link to CONTRIBUTING.md from README.md; use proper link format

mypy/checkexpr.py, mypy/checkmember.py, mypy/messages.py, mypy/semanal.py, mypy/test/data/check-classes.test, mypy/test/data/semanal-classes.test, mypy/typeanal.py, mypy/types.py
=> Give classmethod first arg a reasonable type. Fixes #292

mypy/messages.py, mypy/test/data/check-generics.test
This idea appeared in a discussion at https://github.com/python/typing/issues/79
=> Clarified error message for runtime generics

lib-python/3.2/posixpath.py, mypy/checker.py, mypy/test/data/check-isinstance.test, mypy/test/data/fixtures/isinstance.py
=> Support isinstance with a tuple of types

mypy/nodes.py, mypy/semanal.py, mypy/test/data/pythoneval.test
without introducing circular imports in typeshed
=> Second attempt to enable typing.DefaultDict

mypy/applytype.py, mypy/checkexpr.py, mypy/meet.py, mypy/nodes.py, mypy/semanal.py, mypy/strconv.py, mypy/subtypes.py, mypy/test/data/check-bound.test, mypy/test/data/check-overloading.test, mypy/test/data/fixtures/args.py, mypy/test/data/semanal-errors.test, mypy/test/data/semanal-types.test, mypy/test/testcheck.py, mypy/treetransform.py, mypy/typeanal.py, mypy/types.py
Fixes #689.
This will also need documentation, would you like me to write it and add it to this pull request?
=> Implement TypeVar(..., bound=<type>)

mypy/checkexpr.py, mypy/checkstrformat.py, mypy/exprtotype.py, mypy/fastparse.py, mypy/main.py, mypy/semanal.py
=> Update the fast parser to work with Python 2.7

mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, mypy/constraints.py, mypy/join.py, mypy/meet.py, mypy/messages.py, mypy/nodes.py, mypy/sametypes.py, mypy/semanal.py, mypy/types.py
Seeing all these unneeded casts was bugging me, so I went through and removed the obviously unnecessary casts from the modules I work with often.
=> Remove some obsolete casts

mypy/checker.py, mypy/test/data/check-tuples.test
=> Avoid crash in edge case of multiple assignment.

mypy/semanal.py, mypy/test/data/check-unreachable-code.test
=> Fix unreachability of elif blocks

mypy/build.py, mypy/main.py, mypy/test/data/cmdline.test, mypy/test/testcmdline.py, runtests.py
There are unit tests too. Discussion in #1449.
=> Redo implementation of `mypy package` and `mypy directory`

lib-typing/2.7/test_typing.py, lib-typing/2.7/typing.py, lib-typing/3.2/test_typing.py, lib-typing/3.2/typing.py, mypy/test/data/pythoneval.test
Copied typing.py from upstream repo (https://github.com/python/typing)
=> New typing.py etc.

mypy/fastparse.py
Even though this is trivial, we should wait until after the release to merge at this point.
=> Update --fast-parser installation message

mypy/build.py, mypy/test/testcheck.py
=> Fix how we decide a module exists for case-insensitive platforms.

mypy/test/data/python2eval.test, mypy/test/data/pythoneval.test
Those were added in https://github.com/python/typeshed/commit/3e37029bfec1d01584b91c2fc53818f52a849dbe
=> Tests for some new overloads in the re stubs

mypy/checkmember.py, mypy/test/data/check-namedtuple.test, mypy/test/data/fixtures/property.py
=> Fix use of property in a NamedTuple class

mypy/semanal.py, mypy/test/data/check-functions.test
=> Allow function definitions in while loops and else clauses of loops

mypy/stubgen.py, mypy/test/data/stubgen.test
=> Make stubgen generate multiple assignments (fixes #1603)

docs/source/cheat_sheet.rst
Added clarification where type definition goes in relations to function docstring.
=> Cheat Sheet Documentation

setup.py
=> Move around some code in setup.py to fix errors under Python 2

mypy/build.py, mypy/errors.py, mypy/test/data/cmdline.test
Fix for https://github.com/python/mypy/issues/1521
=> Handle error instead of crash on file with bad encoding

mypy/checkexpr.py, mypy/test/data/check-tuples.test
=> Support negative indexes in tuple slices

mypy/messages.py, mypy/test/data/check-expressions.test, mypy/test/data/check-generics.test, mypy/test/data/check-inference.test, mypy/test/data/check-tuples.test, mypy/test/data/pythoneval.test
Fixes #1617. Had to update a *lot* of test cases...
=> Show more information in incompatible types in indexes

mypy/test/data/semanal-types.test, mypy/typeanal.py
=> Fix zero argument Optional crash

docs/source/common_issues.rst
This documents the `if False: import ...` trick.
=> Add a note about cyclic dependencies (inspired by #1597).

mypy/checker.py, mypy/semanal.py, mypy/test/data/check-overloading.test
Here's a more conservative fix to https://github.com/python/mypy/issues/1614. https://github.com/python/mypy/pull/1638 shows the beginnings of another way to fix it.
This also addresses #409.
=> improve nonconsecutive and single overload errors

docs/source/kinds_of_types.rst
=> Add docs for Type[], simplified from PEP 484.

docs/source/cheat_sheet.rst
=> Include the link to PEP 484 in the cheat sheet

test-data/unit/check-inference-context.test
These used to type check before #1580.
=> Add regression tests for a fix mentioned in #1721

mypy/checker.py, test-data/unit/check-isinstance.test
=> Support `or` in `isinstance` checks

docs/source/introduction.rst
This PR takes an initial pass at revising the docs introduction page:
- use a more active voice
- highlight mypy's developer benefits
- retain the technical points from the current introduction
=> Edit intro for docs

mypy/checker.py, mypy/checkexpr.py, mypy/semanal.py, mypy/subtypes.py
Ran `mypy --warn-redundant-casts mypy`.
=> Kill the remaining redundant casts.

mypy/checkmember.py, test-data/unit/check-expressions.test
Fix for the first error in #1766.
=> Make operations on None fall back on object

mypy/build.py, mypy/test/testcheck.py, test-data/unit/check-incremental.test, test-data/unit/semanal-errors.test
This is a work-in-progress, but I just wanted to make sure any small bugfixes I might make are vetted periodically/make sure that the new tests continue to pass CI.
=> Fix some circular import/incremental mode bugs

mypy/main.py, test-data/stdlib-samples/3.2/test/test_random.py
This time around, syncing typeshed was not easy. I had to push some changes to typeshed (https://github.com/python/typeshed/pull/355) and then make some fixes to mypy itself (contained in this PR). Inspiration for all of this was #1841 but two out of three files changed there were taken care of more pleasantly than the changes there. Only the test_random.py change there (adding a `# type: ignore`) is still needed, due to #1846 -- I can't arrive at a simple but correct fix for the latter.
=> Sync typeshed

mypy/semanal.py, test-data/unit/check-classes.test
=>  Supply a minimal MRO when there's an issue with the bases.

misc/incremental_checker.py
The `incremental_checker.py` script, when run within the `misc` folder, will run incremental mode on a portion of mypy's commit history using the version of mypy in the parent folder.
The checker script will check out an independent copy of the mypy repo to test to avoid interfering with the current repo.
=> Add script to stress-test incremental mode

mypy/checkexpr.py, test-data/unit/check-kwargs.test
=> Minimal fix for crash in map_actuals_to_formals().

test-data/samples/crawl.py
This is an example that exercises some of the asyncio stubs. Requires https://github.com/python/typeshed/pull/373 before it can be merged.
=> Add crawl.py example

mypy/build.py, test-data/unit/check-warnings.test
=> Warn about unused type ignores on imports with --warn-unused-ignores

mypy/semanal.py, test-data/unit/check-classes.test
=> Don't crash when we can't determine MRO

mypy/semanal.py, test-data/unit/check-python2.test
=>  Accept unicode literals to TypeVar and NamedTuple/namedtuple

pytest.ini, test-requirements.txt
Ref. #1673.
@gnprice This one was pretty easy. ;)
=> Always run pytest tests in parallel

test-data/unit/check-optional.test
=> Add test for Callables returning None

docs/source/cheat_sheet.rst, docs/source/duck_type_compatibility.rst, docs/source/kinds_of_types.rst
This pull request adds documentation for the Text and AnyStr aliases.
=> Add documentation for Text and AnyStr

mypy/checkexpr.py, mypy/nodes.py, test-data/unit/check-expressions.test
This fixes https://github.com/python/mypy/issues/1165
=> Support `__cmp__` for Python 2

mypy/build.py, mypy/main.py, mypy/options.py, scripts/find_type.py
Adds a script for finding the type of an arbitrary expression with example vim integration.  Adds a hidden `--shadow-file` argument to mypy so the script doesn't have to make edits in-place.
=> Prototype reveal_type editor integration script

docs/source/kinds_of_types.rst
This commit adds documentation on typing coroutines. In particular, it provides examples of typing...
- `async def` functions
- Generators that use the `@asyncio.coroutine` decorator
- Subclasses of Awaitable
- Subclasses of AsyncIterator
It also adds documentation on typing generators, which was largely copied over verbatim from the documentation regarding generators in the typing module (which I added earlier but somehow neglected to also add here).
=> Document typing generators and coroutines

misc/macs.el, mypy/build.py, scripts/find_type.py
See comments in #2043.
- Bump endcol by one
- Use shadow file's stat() for cache computations
- Add example Emacs integration
=> Fix find_type.py issues and add Emacs integration example.

mypy/semanal.py, test-data/unit/check-namedtuple.test
Test for comma-separated field names
=> Don't accept underscore for namedtuple fields

mypy/nodes.py, mypy/semanal.py
Slight refactoring.
(Let me know if such minor PRs are unacceptable)
=> Extract common typeinfo creation for NewType and NamedTuple (minor)

mypy/checkexpr.py, test-data/unit/check-kwargs.test
=> Allow **kwargs after bare asterisk

mypy/fastparse2.py
This commit adds some documentation providing context into why fastparse2 exists for future readers, and adds a few missing TODOs flagging potential places for improvement.
=> Add comments and some TODOs to fastparse2

mypy/test/data.py
=> data.py: replace .close() with with

docs/source/command_line.rst, docs/source/config_file.rst
=> Document `@flagfile` and the format for `mypy.ini`.

mypy/binder.py, mypy/checker.py, mypy/checkexpr.py, mypy/nodes.py
=> Tighter types for binder, checker and checkexpr

mypy/checkexpr.py, test-data/unit/check-optional.test
=> Allow None to be inferred from context in strict Optional mode

mypy/join.py
=> Fix join_types with UninhabitedType

mypy/maptype.py, test-data/unit/check-classes.test
=> Fix crash on unpacking with invalid base class

mypy/checker.py, test-data/unit/check-optional.test
I was too lazy to wait for the specs to run on my not-too-fast computer, so we'll see what Travis has to think about this...
=> Don't error on raising from None

docs/source/python2.rst
=> Fix missspell 'iff -> if'

mypy/nodes.py
See #2279. The methods are mostly 3-4 years old.
=> Remove unused methods (nodes.py)

mypy/checker.py
=> Remove unused methods (checker.py)

mypy/errors.py
=> Remove unused methods (errors.py)

mypy/messages.py
=> Remove unused methods and obsolete messages (messages.py)

mypy/fixup.py
=> Remove unused function (fixup.py)

mypy/main.py, mypy/options.py, mypy/util.py
See e.g. https://github.com/kyrus/python-junit-xml.
=> Add new flag '--junit-xml=PATH' to write a junit.xml file

mypy/checkexpr.py, mypy/parsetype.py
=> Remove unused methods (checkexpr.py, parsetype.py)

mypy/build.py, mypy/parse.py, mypy/semanal.py, mypy/treetransform.py
See #2279.
(Sorry for the squashing these)
=> Remove unused methods (build, parse, semanal, treetransform)

docs/source/getting_started.rst, docs/source/index.rst
I try to add `getting started` section.
* reference
* [git getting started](https://git-scm.com/book/en/v1/Getting-Started)
* [httpie installation](https://github.com/jkbrzt/httpie)
* [keras installation](https://github.com/fchollet/keras)
=> Add getting started document (#2311)

docs/source/config_file.rst, mypy/build.py, mypy/main.py, mypy/options.py, mypy/semanal.py, mypy_strict_optional.ini, test-data/unit/cmdline.test
=> Change filename patterns to module patterns in mypy.ini.

mypy/solve.py
It's not Python 3.5.1 compatible.
=> Don't use DefaultDict

mypy/checkmember.py
It breaks mypy on Python 3.5.1.
=> Remove use of TYPE_CHECKING

mypy/checkexpr.py, test-data/unit/check-selftype.test
=> Quick fix for selftype+super

mypy/fastparse.py, mypy/test/testcheck.py, test-data/unit/check-underscores.test
This is a small change to https://github.com/python/mypy/pull/2303 requested by @ddfisher in https://github.com/dropbox/typed_ast/pull/21
=> Replace underscores with contains_underscores

lib-typing/2.7/test_typing.py, lib-typing/2.7/typing.py, lib-typing/3.2/test_typing.py, lib-typing/3.2/typing.py
Hopefully this is all for Python 3.6b3.
=> Various updates to typing.py

mypy/checkexpr.py, mypy/typeanal.py, mypy/types.py, test-data/unit/check-generics.test
Fixes #2416 
This is a minimalistic fix (basically just restoring status quo for invalid aliases).
=> Fix the problem with ignored potential type alias

docs/source/generics.rst
Fixes #2307 
@JukkaL Please, take a look.
=> Update docs on runtime use of generic types

mypy/checker.py, test-data/unit/check-statements.test
=> An except clause should accept an exception of Type[BaseException]

docs/source/command_line.rst, docs/source/common_issues.rst, docs/source/python36.rst
These are for the upcoming release.
=> Miscellaneous doc updates

mypy/fastparse2.py, test-data/unit/check-fastparse.test, test-data/unit/lib-stub/__builtin__.pyi
=> Fix print with trailing comma

docs/source/config_file.rst
To match the surrounding items' description style.
=> [Docs] Be a bit less imperative

mypy/types.py
This came up during testing of PR #2444.
=> Don't ever return None for the str() of an Instance

misc/incremental_checker.py
Implements the idea from #1349.
=> Add a 'random' option to select N random commits out of the last 100*N

mypy/build.py, test-data/unit/check-incremental.test
=> Compare cached options to current per-file options

mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, mypy/messages.py, test-data/unit/check-typeddict.test
Partially resolves #2486 . If the approach here looks good I can extend the diff to recognize `__setitem__` as well, which would fully resolve #2486 .
=> TypedDict: Recognize __getitem__ and __setitem__ access.

mypy/checkexpr.py, test-data/unit/check-optional.test
=> Fix lambda inference with simple Union contexts

mypy/main.py
=> Fix help message for --show-error-context

mypy/lex.py, mypy/parse.py, mypy/report.py, mypy/stubgen.py, mypy/test/data.py, mypy/test/helpers.py
Found some of these because they triggered in tests and the rest by
running git grep 'open.*read'
=> fix a few ResourceWarnings

mypy.ini, mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, mypy/git.py, mypy/messages.py, mypy/myunit/__init__.py, mypy/nodes.py, mypy/semanal.py, mypy/strconv.py, mypy/subtypes.py, mypy/test/testmoduleinfo.py, mypy/types.py
Fix low hanging fruit and whitelist historical files.
=> Disallow untyped defs in mypy

mypy/test/data.py, mypy/test/testlex.py, mypy/typefixture.py, mypy_self_check.ini
This types everything but the testextensions module, which does some fun things with exec.
=> More mypy test typing

mypy/fastparse2.py, mypy/test/testcheck.py, test-data/unit/check-python2.test
This also fixes errors in the Python 2 tests.
=> Fix several Python 2 bugs in fast parser

mypy/checker.py, mypy/fastparse.py, mypy/fastparse2.py, mypy/nodes.py, mypy/semanal.py, mypy/strconv.py, mypy/traverser.py, mypy/treetransform.py, test-data/unit/check-fastparse.test
=> Type check assert messages in fast-parser

mypy/errors.py
=> Update errors comment

docs/source/command_line.rst, mypy/checker.py, mypy/checkexpr.py, mypy/main.py, mypy/messages.py, mypy/options.py, test-data/unit/check-flags.test
=> Implement --strict-boolean flag

docs/source/command_line.rst
=> Fixed typo in api docs

setup.cfg
Comment in setup.cfg says all.
=> [flake8] Make runtests.py more deterministic

mypy/checker.py, mypy/checkexpr.py, mypy/fastparse.py, mypy/fastparse2.py, mypy/nodes.py, mypy/semanal.py, mypy/strconv.py, mypy/treetransform.py, test-data/unit/check-statements.test
=> Support type hints on with and for statements

mypy/checker.py, test-data/unit/check-statements.test
=> Raise errors when using deleted variables in conditionals

setup.cfg
=> Synchronize flake8 exclusions with .gitignore

mypy/applytype.py, test-data/unit/check-inference.test
=> Fix crash when assigning to partial type

mypy/checkexpr.py, test-data/unit/check-classes.test
Fix subissue of #2413.
Follow-up for #2475
=> Check for member in type-fallback

mypy/checker.py, test-data/unit/check-classes.test
=> Raise errors on classmethods or staticmethods subclassing conflicts

setup.cfg, setup.py, test-requirements.txt
Cherry-picked from the 0.471 release.
=> Add upper bound to typed_ast

mypy/fastparse.py, test-data/unit/check-async-await.test
Waiting on #2857 (will rebase once that gets merged)
=> Support type comments in async for/with

lib-typing/2.7/mod_generics_cache.py, lib-typing/2.7/test_typing.py, lib-typing/2.7/typing.py, lib-typing/3.2/mod_generics_cache.py, lib-typing/3.2/test_typing.py, lib-typing/3.2/typing.py
Fixes #2867 
Updates are for both Python 2, Python 3, an test files for both.
=> Update typing.py from python/typing

docs/source/common_issues.rst, docs/source/generics.rst
=> Document covariance vs invariance

mypy/checkstrformat.py, test-data/unit/check-expressions.test
=> Be aware of StarExpr in tuple when checking string conversions

docs/source/common_issues.rst, docs/source/config_file.rst, docs/source/generics.rst, docs/source/revision_history.rst
Also document the strict_boolean config file option.
=> Add 0.500 to revision history

mypy/main.py
Fix #2893 
Not sure if it's worth adding a test for this; the test itself would be rather platform-dependent, since it would depend on the OS buffering policy.
=> Catch BrokenPipeError

mypy/build.py, mypy/main.py, test-data/unit/cmdline.test
Fixes #2558 
Mypy will correctly process a script or folder even if its name contains dots (or will complain if there are no such file).
Note that mypy will not "see" files with names containing dots unless they are directly given as arguments (see tests).
=> Fix crash on file names containing dots

mypy/build.py, mypy/errors.py, mypy/main.py, mypy/options.py, test-data/unit/cmdline.test
=> Change hide_error_context to show_error_context

mypy/checker.py, test-data/unit/check-statements.test, test-data/unit/fixtures/tuple.pyi
=> Allow unions and nested tuples in except handlers

mypy/checker.py, test-data/unit/check-python2.test, test-data/unit/check-selftype.test
Fix #2950
@JukkaL what do you think?
=> Friendlier messages for selftype-related errors

mypy/nodes.py, mypy/types.py
These calls showed up in a profile run. It's a simple optimization.
=> Don't call globals() in deserialize()

mypy/checkstrformat.py, test-data/unit/check-expressions.test
Fixes #2472 and a TODO in the code.
=> Various fixes to % formatting

mypy/checker.py, mypy/checkexpr.py, mypy/fastparse.py, mypy/fastparse2.py, mypy/nodes.py, mypy/semanal.py, mypy/strconv.py, mypy/traverser.py, mypy/treetransform.py, mypy/visitor.py, test-data/unit/parse-python2.test, test-data/unit/parse.test, test-data/unit/semanal-expressions.test, test-data/unit/typexport-basic.test
=> Rename FuncExpr to LambdaExpr

mypy/checkexpr.py, mypy/test/data.py, test-data/unit/README.md, test-data/unit/check-typeddict.test
=> Accept compatible dict in place of TypedDict

mypy/checker.py, mypy/erasetype.py, mypy/expandtype.py, mypy/indirection.py, mypy/join.py, mypy/meet.py, mypy/sametypes.py, mypy/solve.py, mypy/subtypes.py, mypy/test/testtypes.py, mypy/typefixture.py, mypy/types.py
=> Get rid of ErrorType

mypy/checker.py
=> Fix crash on incorrect args count

mypy/subtypes.py
=> Tentative fix for crash in --quick mode

appveyor.yml
=> Skip AppVeyor builds for branches with PR

extensions/setup.py
Also update author, author_email, classifiers.
Fixes #3311.
=> Bump mypy_extensions version

mypy/nodes.py, mypy/semanal.py, test-data/unit/check-overloading.test
I think this fixes https://github.com/python/mypy/issues/3333
=> Fix crash on decorated non-overload function redefinition

mypy/build.py
=> Move makedirs call inside try/except.

README.md
=> Clarify submodule

mypy/semanal.py, test-data/unit/check-classes.test, test-data/unit/check-functions.test, test-data/unit/check-overloading.test, test-data/unit/semanal-errors.test
Reverts python/mypy#3396
This caused a new crash, the rollback fixes #3415.
=> Revert "Add line # of previous definition"

test-data/unit/README.md
This was something I was looking for in the quick start, and didn't find
clearly stated anywhere in the README.
=> Add 'how to run this one test' note to test quick start.

mypy/checker.py
See [this comment](https://github.com/python/mypy/pull/3473#discussion_r119157164)
=> Minor speed-up in --warn-return-any

ROADMAP.md
See [this comment](https://github.com/python/mypy/pull/3460/files#r118847066)
=> Add --strict-optional by default to the roadmap

mypy/types.py, test-data/unit/check-optional.test
=> Handle UnionType correctly in true_or_false

mypy/messages.py, test-data/unit/check-typeddict.test, test-data/unit/pythoneval.test
Made them a bit friendlier and bit more consistent.
=> Tweaks to TypedDict error messages

mypy/report.py, test-data/unit/cmdline.test
=> Fix division by zero error in AnyExpressionsReport

CONTRIBUTING.md, README.md
These are the last occurrences of the old chat room. See #3529.
=> Change python/mypy chat room to python/typing

test-data/unit/check-isinstance.test
The formatting was all over the place, making the tests hard to read. I didn't
try to get these 100% consistent, just good enough.
=> Reformat isinstance tests

mypy/build.py
If the path is different (e.g. after copying a cache from a different
machine or user) the cache entry would be trivially rejected.  Now
that we have the hash as the source of truth, we don't need to worry
so much about that.
=> Move path comparison from find_cache_meta() to validate_meta().

test-data/unit/lib-stub/typing.pyi
Helpful for the right fix in #3686.
=> Remove unnecessary methods in typing stub

mypy/semanal.py, test-data/unit/semanal-typeddict.test
=> Support docstrings in class based TypedDict

docs/source/config_file.rst, mypy/options.py, test-data/unit/cmdline.test
=> Make disallow_subclassing_any a per-module option

mypy/report.py, mypy/stats.py, test-data/unit/reports.test, xml/mypy-html.xslt, xml/mypy.xsd
Now, when you hover over a line in html-report, mypy will show types of Anys that appear on that line.
=> Report sources of Any in html-report per-line as hovertext

mypy/main.py
=> Set options.config_file to file actually read.

.travis.yml
A bunch of builds have been failing.
=> Attempt to fix flaky Travis CI builds by reducing parallelism

mypy/semanal.py, mypy/typeanal.py, test-data/unit/check-type-aliases.test
Fixes https://github.com/python/mypy/issues/3269
Fixes https://github.com/python/typing/issues/451
Also a step in the direction of #640
=>  Allow creating type aliases for None

mypy/applytype.py, mypy/checker.py, test-data/unit/check-inference.test
Fixes #3986 and two additional similar crashes on partial types.
=> Fix recently reported partial type crashes

mypy/build.py
`git` will not allow `git submodule --init update`, only `git submodule update --init`.
=> Correct suggested command to checkout typeshed

mypy/build.py, mypy/checkexpr.py, mypy/nodes.py, mypy/semanal.py
=> Rename semantic analyzer classes to SemanticAnalyzerPass[123]

mypy/test/data.py
=> Gracefully handle Ctrl+C during tests

mypy/report.py, mypy_self_check.ini
Followup from #4217 and python/typeshed#1664.
=> add back options in mypy_self_check.ini

misc/incremental_checker.py, mypy/build.py, test-data/unit/check-incremental.test
Fixes #4185.
Fixes #4198.
Fixes #4195.
Fixes #4208.
Also some improvements to mypy/incremental_checker.py and report more stats about in-memory cache.
=> Fix in-memory cache reuse

MANIFEST.in, extensions/LICENSE, extensions/MANIFEST.in
=> Add LICENSE files to sdists

mypy/fastparse.py, mypy/fastparse2.py, test-data/unit/check-fastparse.test
Fixes #4111 
This corrects a previous wrong ``--strict-optional`` change (and adds various tests).
=> Fix crash in relative imports

test-data/unit/pythoneval.test
see https://github.com/python/mypy/pull/3846#issuecomment-345395275
=> Temporary skip a test

extensions/setup.py
=> extensions: Specify dependency on typing for py<35

mypy/checker.py, mypy/nodes.py, mypy/semanal.py, mypy/semanal_pass1.py, mypy/server/astdiff.py, mypy/server/astmerge.py, mypy/server/aststrip.py, mypy/server/deps.py, mypy/server/update.py, mypy/stats.py, mypy/strconv.py, mypy/test/testdeps.py, mypy/test/testmerge.py, mypy/treetransform.py, mypy/types.py, scripts/finegrained.py, test-data/unit/deps-classes.test, test-data/unit/diff.test, test-data/unit/fine-grained.test, test-data/unit/merge.test
This contains various fixes and improvements to fine-grained incremental mode,
including these:
* Script for using fine-grained incremental mode interactively (prototype, will be
replaced with dmypy in the future).
* Basic support for type variables, named tuples and type aliases.
* Support for most kinds of types.
* Basic support for function decorators.
=> Various improvements to fine-grained incremental mode

mypy/build.py, mypy/server/aststrip.py, mypy/server/target.py, mypy/server/update.py, mypy/test/data.py, mypy/test/testfinegrained.py, mypy/test/testmerge.py, scripts/finegrained.py, test-data/unit/fine-grained-blockers.test, test-data/unit/fine-grained-modules.test, test-data/unit/merge.test
This contains several improvements to fine-grained incremental mode, 
including these:
* Support for blocking errors.
* Adding a (single) file.
* Removing a (single) file.
* Share the saved cache between dmypy and fine-grained incremental mode.
* Support re-creating a previously deleted file in test cases.
This cuts some corners for now. The main limitation is that only changes 
involving a single file are supported.
=> More improvements to fine-grained incremental mode

mypy/build.py, mypy/dmypy.py
Also tweak formatting of dmypy stats report.
=> Add more caching to speed up find_module()

docs/source/config_file.rst
=> Ignore specific module

mypy/nodes.py
Related to #4346 (but does not necessarily fix it)
=> Stop serializing Var.is_ready; it's not important and it may vary

mypy/test/testdmypy.py
Noticed this working on #4278 :)
Perhaps we should add self check back to appveyor?
=> Fix mypy self check on Windows

docs/source/common_issues.rst, docs/source/revision_history.rst
**Don't merge until at the time of release!**
=> Update revision history for 0.560

mypy/server/astdiff.py, mypy/server/astmerge.py, mypy/server/aststrip.py
Major updates to docstrings/comments in `mypy.server.astdiff`,
`mypy.server.astmerge` and `mypy.server.aststrip`.
=> Improve documentation of fine-grained incremental mode

mypy/server/deps.py, mypy/server/update.py, test-data/unit/deps-classes.test, test-data/unit/deps-expressions.test, test-data/unit/deps-generics.test, test-data/unit/deps-statements.test, test-data/unit/deps-types.test, test-data/unit/deps.test
This updates the documentation of fine-grained dependencies and the top-level
fine-grained incremental logic.
=> More improvements to documentation of fine-grained incremental mode

docs/source/faq.rst
(Hopefully) clarified and corrected the section on how mypy differs from PyPy.
=> Removal of section regarding comparison between mypy and PyPy

mypy/types.py, test-data/unit/check-incremental.test
=> Serialize additional attributes of "Any" objects

mypy/server/astdiff.py, mypy/server/astmerge.py, test-data/unit/diff.test, test-data/unit/fine-grained.test
=> Consider changes to tuple_type to be a "major" difference

test-data/unit/fine-grained-modules.test
Two test cases are still failing due to crashes. Skipping those
tests for now.
Fixes #4389. Fixes #4390.
=> Fine-grained: Add test cases for addding/deleting a package

mypy/server/astmerge.py, mypy/server/aststrip.py, mypy/server/update.py, test-data/unit/fine-grained-modules.test, test-data/unit/fine-grained.test, test-data/unit/merge.test
This fixes all of the bugs found while running fine-grained incremental on the S repo with every file changed trivially.
=> Fix a handful of fine-grained incremental bugs

mypy/test/testdeps.py, mypy/test/testmerge.py, test-data/unit/deps-classes.test, test-data/unit/diff.test, test-data/unit/fine-grained.test, test-data/unit/merge.test
This just adds some basic test coverage.
I'll add functional enum test cases in a separate PR.
=> Fine-grained: Add class-based Enum test cases

mypy/semanal.py, test-data/unit/fine-grained.test
This works around the problem but doesn't fully resolve the underlying
issue.
Fixes #4612.
=> Fine-grained: Fix crash due to nested class

mypy/server/deps.py, test-data/unit/deps-types.test, test-data/unit/diff.test, test-data/unit/fine-grained.test
Most of the test cases just replicate the class based tests (with some variations). I also add the dependencies on value types to make the enum support "future proof".
=> Add functional Enum test cases

mypy/stubgen.py
This might help debug stubgen test flake that occasionally
happens in CI (#4635).
Alternative to #4672. A notable difference is that this prints 
a traceback from importlib.
=> Add debug output to stubgen test flakes

docs/source/class_basics.rst
Related to discussion at #4758.
Fixes #4758
=> Mention that SupportsInt and friends don't support arithmetic

docs/source/command_line.rst, docs/source/revision_history.rst
This will be cherry picked in the release branch.
=> Update docs revision history for 0.580

mypy/server/deps.py, mypy/server/update.py
These seem no longer relevant.
=> Fine-grained: Remove some obsolete todo items

docs/source/command_line.rst, docs/source/config_file.rst, mypy/main.py, mypy/options.py, mypy/semanal.py, mypy/semanal_pass1.py, test-data/unit/check-flags.test
These work similarly to `if PY3` or `if MYPY`.
Fixes #3668.
=> Add --always-true and --always-false flags

mypy/server/update.py
I happened to notice some calls to file_context() using
manager.options (I got curious whether making always_true/always_false
per-module options would run into problems).  I ended up cleaning up a
few other uses of options in mypy/server/update.py.
I don't assume this requires new tests?
=> Fix some uses of manager.options that should be the per-module options

mypy/server/update.py, test-data/unit/fine-grained-modules.test
=> Fine-grained: Fix crash on changing package to module

mypy/test/testpep561.py
This won't fix the issue in https://github.com/python/mypy/issues/4883, but it might help in debugging, and is probably a good change anyway.
=> Report if uninstall of package in pep561 tests failed

mypy/test/testpep561.py
We synced the fix from typeshed.
=> remove type: ignore

mypy/main.py
In https://github.com/python/mypy/issues/4923 I noticed that "error" is repeated in these messages.
=> Remove duplicate error in message

mypy/build.py, mypy/find_sources.py, mypy/fscache.py, mypy/main.py, mypy/test/testfinegrained.py
Merge FileSystemMetaCache back into FileSystemCache and use the same fscache in builds and source finding.
=> FileSystemCache cleanups

test-data/unit/fine-grained.test
=> Fine-grained: Test f string

docs/source/additional_features.rst, docs/source/index.rst, docs/source/mypy_daemon.rst
Also discuss how to use remote caching with the mypy daemon.
=> Document mypy daemon and the dmypy utility

.gitignore, mypy/dmypy_util.py
No reason to clutter up the working directory.
=> Use `.dmypy.json` as the dmypy run file

mypy/typeanal.py, test-data/unit/check-async-await.test, test-data/unit/check-fastparse.test, test-data/unit/check-functions.test, test-data/unit/check-statements.test, test-data/unit/fine-grained.test, test-data/unit/semanal-types.test
=> Improve error message for invalid tuple types like (int, str). #4173

README.md
Replace `This should automatically installed` with `This should automatically install`.
=> Fix typo at README.md line 139

docs/source/common_issues.rst
=> Explain how to work around a certain name conflict

mypy/main.py
This pull request cleans up the message displayed when running `mypy --help` by...
1. Modifying the flag descriptions to consistently start with lowercase letters.
2. Mildly tweaking a few flag descriptions.
3. Categorizing command line flags into distinct groups.
4. Reordering the flags.
Specifically, the flags now arranged in the following order:
1. General flags (`--help`, `--version`)
2. Config file flags
3. Imports handling
4. Flags that influence how code is typechecked/alter strictness
5. Flags that alter mypy's "state" (incremental flags and "internal" flags like `--custom-typeshed-dir`)
6. Reports and error messages
7. Misc flags
Note: this pull request does not change any of the flags themselves -- it only changes the output of `--help`.
=> Reorganize and categorize command line flags

mypy/main.py
Make things a bit more consistent. Hide some unsupported options.
Improve formatting of the footer (whitespace is not preserved).
=> Minor updates to the --help text

extensions/mypy_extensions.py, mypy/binder.py, mypy/checker.py, mypy/checkexpr.py, mypy/checkmember.py, mypy/errors.py, mypy/exprtotype.py, mypy/fastparse2.py, mypy/nodes.py, mypy/plugins/attrs.py, mypy/semanal.py, mypy/semanal_pass1.py, mypy/semanal_pass3.py, mypy/server/astmerge.py, mypy/server/deps.py, mypy/server/update.py, mypy/stubgen.py, mypy/subtypes.py, mypy/traverser.py, mypy/treetransform.py, mypy/types.py, mypy/typestate.py
Minor touchup of existing code comments.
=> Fix minor typos in comments

MANIFEST.in
This fixes tests for the pypi distributed tarballs.
=> Include waiter.py

mypy/checkstrformat.py
Sample timeit shows a 1.4x speedup on my machine.
Before:
```
(venv) ~/src/python/mypy (master) % python3 -m timeit -r 10 -p -s 'from mypy.checkstrformat import StringFormatterChecker; sfc = StringFormatterChecker(None,None,None)' 'sfc.parse_conversion_specifiers("Deferring module to fine-grained update %s (%s)")'
100000 loops, best of 10: 9.32 usec per loop
```
After:
```
(venv) ~/src/python/mypy (str-format-compiled-re) % python3 -m timeit -r 10 -p -s 'from mypy.checkstrformat import StringFormatterChecker; sfc = StringFormatterChecker(None,None,None)' 'sfc.parse_conversion_specifiers("Deferring module to fine-grained update %s (%s)")'
100000 loops, best of 10: 6.65 usec per loop
```
=> Use a compiled regex when parsing string format

mypy/constraints.py, test-data/unit/check-type-promotion.test, test-data/unit/fixtures/primitives.pyi
=> Fix crash caused by protocols-promote interference

mypy/semanal.py
Supporting type aliases in mypyc is nearly a matter of just directly
compiling the assignment expressions. The snag is that mypy doesn't
semantically analyze the indexes in index expressions when defining
type variables (it instead just does type things).
Update semanal to semantically analyze the indexes. I just do this
unconditionally because it seems cheap enough that it doesn't seem
worth introducing mechanism for doing it conditionally.
=> Semantically analyze indexes in type var definitions

mypy/constraints.py, test-data/unit/pythoneval.test
=> Fix IntEnum iterability

docs/source/command_line.rst, docs/source/running_mypy.rst
Found by using https://github.com/python/mypy/pull/5356
=> Fix minor docs typos

mypy/subtypes.py, test-data/unit/check-classes.test
=> Fix descriptor access for dynamic base classes

mypy/checkmember.py, test-data/unit/check-classes.test
=> Fix a descriptor refactoring mistake

mypy/checkstrformat.py, mypy/errors.py, mypy/indirection.py, mypy/server/subexpr.py, mypy/typestate.py
mypyc doesn't support accepting `*args` or defining methods via assignment
=> More tweaks to support mypyc

mypy/checkexpr.py, test-data/unit/check-async-await.test, test-data/unit/check-isinstance.test
Fixes #5020 and updates relevant tests.
=> Fix interpretation of returned generator expressions

mypy/semanal.py, test-data/unit/check-classes.test
=> Fix false positive when using properties

mypy/checkexpr.py, mypy/dmypy_server.py, mypy/fastparse.py, mypy/fastparse2.py, mypy/report.py, mypy/semanal_pass3.py, mypy/typeanal.py
Some of these are kind of unpleasant, since I saved the best for last.
=> A handful of hacks to appease mypyc

mypy/semanal.py, mypy/semanal_pass1.py
Split a monster function into several smaller functions. Merge some almost
repeated code into a helper method.
=> Refactor semantic analysis of assignment statements

test-data/unit/README.md
Helps with issue discussed in #5688.
=> Add mention of `runtests` script to tests readme

mypy/typestate.py
mypyc optimizes accesses to `Final` class variables, but only when they
are made through a class name reference. Change TypeState to access
the caches via references to `TypeState` instead of `cls`.
This gets a modest perf win.
=> Tweak TypeState to avoid getattrs under mypyc

docs/source/final_attrs.rst
Follow-up for https://github.com/python/mypy/pull/5754
This addresses some review comments.
=> Minor adjustments to Final docs

docs/source/final_attrs.rst
Tighten the documentation a bit and avoid repetition. Make the structure clearer. 
Various minor style and grammar tweaks. Update some examples and leave out
a few others.
=> Various small updates to documentation of final/Final 

mypy/version.py
(Note that pure "0.640" only occurs in the release-0.640 branch.)
=> Bump version to 0.650+dev

test-data/stdlib-samples/3.2/fnmatch.py, test-data/stdlib-samples/3.2/test/test_fnmatch.py
Fixes DeprecationWarnings. Closes #5820.
=> Mark raw strings

mypy/dmypy.py, mypy/dmypy_server.py, mypy/fswatcher.py
This simplifies some logic in code and also is easier to use. I tested this manually and it seem to work well.
=> Merge --add into --update for daemon

mypy/test/testdaemon.py, test-data/unit/daemon.test
=> End to end tests for daemon (dmypy)

mypy/test/testdaemon.py
See https://github.com/python/mypy/pull/5906#issuecomment-439763548
=> Clean up after failing daemon tests

mypy/stubgen.py, test-data/unit/stubgen.test
=> Update stubgen to output async def and coroutine decorators

mypy/checkexpr.py
Split a huge function into multiple smaller functions. There are
no semantic changes.
=> Refactor type checking of calls

mypy/reachability.py, mypy/semanal.py, mypy/semanal_pass1.py
This just moves reachability related code to a new module.
=> Refactor reachability related code in the semantic analyzer

mypy/test/data.py, mypy/test/helpers.py, mypy/test/testcheck.py, mypy/test/testcmdline.py, mypy/test/testfinegrained.py, mypy/test/testmerge.py, mypy/test/testpep561.py, mypy/test/testpythoneval.py, mypy/test/teststubgen.py
This will make things more consistent in different environments.
=> Explicitly use UTF-8 encoding in tests

mypy/dmypy.py
=> Add argparser version in dmypy command.

mypy/metastore.py
(Running mypyc in CI is on my TODO list.)
=> Fix a mypyc breakage introduced with the sqlite change

mypy/main.py, mypy/messages.py, mypy/server/objgraph.py, mypy/types.py, mypy/util.py
Found using https://github.com/asottile/dead and manually filtering false positives.
=> Remove dead code

setup.py, test-requirements.txt
This should be cherry picked into the release branch (#6130)
=> Update the typed-ast dependency to 1.2.0

mypy/semanal.py
This just splits a long function.
=> Refactor semantic analysis of assignments

mypy/semanal.py
Primary changes:
* Remove an unnecessary context manager.
* Split long function.
=> Refactor class semantic analysis

mypy/newsemanal/semanal.py, mypy/newsemanal/semanal_enum.py, mypy/newsemanal/semanal_namedtuple.py, mypy/newsemanal/semanal_newtype.py, mypy/newsemanal/semanal_pass1.py, mypy/newsemanal/semanal_pass3.py, mypy/newsemanal/semanal_typeddict.py, mypy/newsemanal/typeanal.py
Copy the existing semantic analyzer to a new package with minimal
changes (only update imports). The new package is not used
anywhere yet.
Once the new semantic analyzer is good enough, the plan is to
replace the existing semantic analyzer with it and remove the
`mypy.newsemanal` package.
=> Copy semantic analyzer module to mypy.newsemanal

mypy/newsemanal/semanal.py, mypy/newsemanal/semanal_main.py, test-data/unit/check-newsemanal.test
Functions are analyzed after all the module top levels are ready.
Also add some missing definitions to builtins such as `None`.
=> New semantic analyzer: Basic function support

mypy/newsemanal/semanal.py
The implementation of deferred/incompleteness state remains
the same but now we have a cleaner API for accessing it.
=>  New semantic analyzer: Refactor deferred/incompleteness handling

mypy/newsemanal/semanal.py, mypy/newsemanal/semanal_main.py, mypy/newsemanal/typeanal.py, test-data/unit/check-newsemanal.test, test-data/unit/fixtures/typing-full.pyi, test-data/unit/lib-stub/typing.pyi
This adds support for several new features:
* Nested classes
* Built-in type aliases such as `List[T]`
* Overloaded functions
* Decorated functions
This also includes some smaller fixes related to generic classes, adds 
tests for other features, and makes the order of processing module top 
levels consistent across iterations.
=> New semantic analyzer: Support more features etc.

docs/source/stubgen.rst
This is mostly style and language tweaks. The content remains 
roughly the same.
=> Update documentation of stubgen

mypy/newsemanal/typeanal.py
Use `lookup_qualified` instead of `lookup` for consistency.
=> New semantic analyzer: minor refactoring in type analyzer

mypy/build.py
load_graph has shown up very hot in internal telemetry and I want to
try to break it down a bit more.
=> Add more time stats collection to parts of load_graph

mypy/newsemanal/semanal.py, mypy/semanal.py, test-data/unit/check-classes.test, test-data/unit/check-newsemanal.test
Fixes https://github.com/python/mypy/issues/6367
=> Fix crash for class level missing imports

mypy/checker.py, test-data/unit/check-protocols.test
This was discovered when working on new semantic analyzer
=> Check protocol variance after the body is analyzed

mypy/newsemanal/semanal.py, test-data/unit/check-newsemanal.test, test-data/unit/pythoneval.test
=> New semantic analyzer: fix properties

mypy/build.py
abspath() is surprisingly slow. This gave almost a second of speedup
for me on cold run startup.
This does change the cache contents, but I don't think it should
really matter.
=> Don't call abspath() on path name when validating cache

mypy/newsemanal/semanal.py, mypy/test/hacks.py
Fixes https://github.com/python/mypy/issues/6315
=> New semantic analyzer: Support implicit module attributes such as __name__

test-data/unit/check-incomplete-fixture.test, test-data/unit/check-incremental.test, test-data/unit/check-inference.test, test-data/unit/fine-grained-modules.test, test-data/unit/lib-stub/__builtin__.pyi, test-data/unit/lib-stub/builtins.pyi
=> Use generic tuple in builtin fixtures

mypy/build.py, mypy/newsemanal/semanal.py
Now it can be replaced with a proper fix.
=> Remove typing hack for new semantic analyzer

mypy/newsemanal/semanal.py, test-data/unit/check-newsemanal.test
Fixes https://github.com/python/mypy/issues/6294
=> Support class keyword arguments

mypy/newsemanal/semanal.py, test-data/unit/check-newsemanal.test
Fixes https://github.com/python/mypy/issues/6287
=> Support forward references in upper bounds

mypy/newsemanal/semanal.py
=> Amend the refactoring of add_unknown_symbol()

docs/source/more_types.rst
`viervalues()` -> `viewvalues()`
=> Update typo in more_types

mypy/build.py, mypy/newsemanal/semanal.py, mypy/test/hacks.py
=> New semantic analyzer: support --allow-redefinition

.travis.yml, pyproject.toml, setup.py, tox.ini
https://tox.readthedocs.io/en/latest/example/package.html#packaging 👍
=> enable isolated build (PEP-517 for tox)

test-data/unit/pythoneval.test
Reverts python/mypy#6469
See https://github.com/python/typeshed/pull/2817 for motivation.
=> Revert "Fixing error message to match new typeshed stub"

mypy/test/hacks.py, test-data/unit/check-final.test, test-data/unit/check-inference.test, test-data/unit/fine-grained.test, test-data/unit/lib-stub/enum.pyi, test-data/unit/semanal-errors.test
Fixes https://github.com/python/mypy/issues/6289
=> Update enum fixture to work with new analyzer and re-enable tests

mypy/newsemanal/semanal_main.py, mypy/newsemanal/semanal_pass3.py, mypy/newsemanal/semanal_typeargs.py, mypy/test/hacks.py, test-data/unit/check-flags.test, test-data/unit/lib-stub/mypy_extensions.pyi
Implement checking of missing generic type arguments.
Fix a duplicate definition in mypy_extensions fixture
to get some tests passing.
=> New semantic analyzer: enable flags tests and fix issues

misc/upload-pypi.py, mypy/ipc.py
Using the PR of pyflakes @ https://github.com/PyCQA/pyflakes/pull/443
=> Fix up a few string formatting issues

mypy/checkexpr.py, mypy/fastparse.py, mypy/ipc.py, mypy/messages.py, mypy/newsemanal/typeanal.py, mypy/nodes.py, mypy/report.py, mypy/stubdoc.py, mypy/typeanal.py
This was a big obstacle that made me reluctant to set up CI.
=> Eliminate all mypyc warnings when compiling mypy

mypy/main.py
=> Home directory expansion for config's cache_dir setting

mypyc-requirements.txt
This should fix a memory leak for the compiled version
=> Update mypyc to 0.0.1+dev.7afc879462353edc235f4a4c41f2ce3e4792e849

mypy/server/aststripnew.py
mypyc doesn't yet properly implement the "bind on function definition"
behavior of default arguments, which means that can't be abused to
capture variables in nested function defined in a loop.
Work around this in a hacky way.
=> Work around mypyc not supporting default arguments in closure

.gitignore
In case you want multiple env directories, make it globbed.
=> Add env* and .venv* to .gitignore

.travis.yml
=> Disable the dev environment travis build

README.md
Replaces 404ing link in README
Fixes https://github.com/python/mypy/issues/6732
=> Fixes #6732

mypy/dmypy.py, mypy/dmypy_server.py, mypy/suggestions.py, mypy/test/testfinegrained.py, test-data/unit/daemon.test, test-data/unit/fine-grained-suggest.test
* Add option to require that a suggestion produce no errors
* Add option to require that a suggestion not contain Any
* Handle `__init__`
* Cap the number of suggestions considered
* Improve output formatting a bunch
=> Improvements to dmypy suggest

docs/source/running_mypy.rst
Resolves https://github.com/python/mypy/issues/6660
=> Add note about relative file paths in import discovery

mypy/dmypy_server.py, setup.py, test-requirements.txt
=> Require psutil in Windows too; relax version requirements

.gitignore, setup.cfg
=> Ignore virtualenv for commits and tests

README.md
This is covered in more detail in https://github.com/python/mypy/blob/master/test-data/unit/README.md, but the instructions in the main README ought to contain all the commands needed to get tests working.
=> Add more details to test installation

mypy/build.py
Implements some ideas from #6544
=> Add startup debug information

README.md
Fixes #6788  @ethanhs, @asottile Your reviews please.
=> README.md: Add link to pre-commit hook

mypyc-requirements.txt
This should fix the mypy_mypyc build.
=> Update mypyc to 0.0.1+dev.cf3b2c1f3f459048609e33182cce2c9408fc9387

mypyc-requirements.txt
I think that this time it should actually unbreak things.
=> Update mypyc to 0.0.1+dev.8fa0ac421f47168491ea9a53c0ab20403cb6805a

mypyc-requirements.txt
This will let us use *args and **kwargs!
=> Update mypyc to 0.0.1+dev.bba6aa6c1b059fc74520c30c4e18e4dcea1ade68

mypyc-requirements.txt
... 5 mypyc updates in two days >_>. Sorry
This fixes mypy on Python 3.5.2 and earlier
=> Update mypyc to 0.0.1+dev.1e8b76a6666242abaf1a1be40d1b707ace37e7ae

mypy/newsemanal/semanal.py, mypy/semanal.py, test-data/unit/check-statements.test
See recent discussion at #833.
=> Allow list literal del.

setup.py
This should fix issues with dmypy not working in wheels
=> Add mypy.dmypy to the list of packages

.travis.yml, mypy/test/testmypyc.py
This probably doesn't work yet but our CI only triggers when there is a PR up
=> Add a CI build that uses mypyc

mypy/server/deps.py
=> Clean up fine-grained dependency generation a bit

mypy/messages.py, test-data/unit/check-unions.test
Fix https://github.com/python/mypy/issues/5895
=> Display note when having invariants in Union

mypy/newsemanal/semanal.py, mypy/newsemanal/semanal_shared.py, mypy/newsemanal/typeanal.py
=> New semantic analyzer: remove traces of pass 3

mypy/newsemanal/semanal.py
Group related methods together. Add some additional headings.
Rename a method.
There are no non-trivial changes.
=> New semantic analyzer: refactor

mypy_self_check.ini
It's good to dogfood new features before release.
=> Use new semantic analyzer in self check

mypy/newsemanal/semanal.py, mypy/semanal.py
=> Use iterable unpacking now that mypyc supports it

mypy_bootstrap.ini, mypyc-requirements.txt
I am not sure we should do this _right now_. But maybe it is at least we should use it for mypy CI build (because e.g. making this work required couple small updates in mypyc)?
(IIUC, this should initially fail, until I update the mypyc pin.)
=> Use new semantic analyzer for bootstrap

mypy/checker.py, mypy/messages.py, test-data/unit/check-abstract.test, test-data/unit/check-class-namedtuple.test, test-data/unit/check-classes.test, test-data/unit/check-selftype.test, test-data/unit/check-typevar-values.test, test-data/unit/fine-grained.test
=> Specify return types for the return types incompatible with supertype error

mypy/main.py
This fixes a crash under mypyc.
Closes #6980.
=> Fix type annotation for AugmentedHelpFormatter

mypy/newsemanal/semanal.py, test-data/unit/semanal-errors.test
These haven't been relevant in a long time.
=> New semantic analyzer: remove obsolete name reporting 

mypy/newsemanal/semanal.py
=> New semantic analyzer: remove unused code

mypy/newsemanal/semanal.py
Split long function and rename some variables. Update a few comments.
=> New semantic analyzer: refactor "import from" processing

docs/source/command_line.rst, docs/source/config_file.rst
The "next mypy release" in the text refers to the next release after 
0.710.
=> Document --new-semantic-analyzer

test-data/unit/check-newsemanal.test
Closes https://github.com/python/mypy/issues/6944
=> Add new analyzer test for tricky implicit imports

mypy/newsemanal/semanal_classprop.py, test-data/unit/pythoneval.test
=> New semantic analyzer: fix false positives from TypedDict in stub

mypy/newsemanal/semanal.py, test-data/unit/check-newsemanal.test
Fixes https://github.com/python/mypy/issues/6951
=> New semantic analyzer: Copy, don't modify, unanalyzed types

mypy/checker.py, test-data/unit/check-inference.test
Fixes https://github.com/python/mypy/issues/7126
=> Don't do any tricky inference in deferred nodes

mypy/fixup.py, mypy/nodes.py
These might help diagnose some crashes we've seen.
=> Make sure that SymbolTableNode.node is not unexpectedly None

mypy/newsemanal/semanal.py, mypy/newsemanal/semanal_main.py, test-data/unit/check-newsemanal.test
Fixes https://github.com/python/mypy/issues/6494
The issue seems to be already fixed because of how `local_definitions()` works, I just add a test case to avoid regressions.
=> New analyzer: test that class properties are calculated for classes in functions

mypy/messages.py, test-data/unit/check-python2.test
Closes #6673.
A year and a half since my last PR here... Turns out I haven't died after all :rofl:
=> Avoid telling the user to use type annotations on pre-3.5

mypy/newsemanal/semanal.py
Unused since 9eb24688c2cfe132b54577eabc09a771a5c8ac0b.
=> New analyzer: remove unused function allow_patching

mypy/checkstrformat.py, test-data/unit/check-expressions.test
=> Fix mypyc crash when interpolating bytes with a dictionary

mypy/checker.py, mypy/messages.py, test-data/unit/check-errorcodes.test
Make error codes more consistent.
=> Change error codes of a few messages

mypy/checker.py, test-data/unit/check-generics.test
Fix a regression introduced in commit f9396ef.
=> Fix crash in multiple assignment when "__iter__" returns Any

mypyc/genops.py, mypyc/test-data/run-functions.test
... this was actually as simple as removing an assert.
=> [mypyc] Support nested functions without type annotations

test-data/unit/pythoneval.test
Needed for python/typeshed#3252.
Tested by pulling in the typeshed branch in the subproject.
=> fix tuple add pythoneval tests

mypyc/emitclass.py, mypyc/emitwrapper.py, mypyc/genops.py, mypyc/prebuildvisitor.py
Tested by compiling mypy and comparing outputs on Python 3.5.
=> [mypyc] Fix some nondeterminism caused by iterating over sets/dicts

mypy/suggestions.py, test-data/unit/fine-grained-suggest.test
Solution looks quite straightforward.
=> Use TypedDict fallback as its suggestion representation

mypyc/build.py, mypyc/emitmodule.py, mypyc/errors.py, mypyc/genops.py, mypyc/test/test_run.py, mypyc/test/testutil.py
Pull Errors out into its own module and have it get managed externally
from genops. This is in preparation for separate/incremental
compilation.
=> [mypyc] Refactor mypyc error handling

test-requirements.txt
This will need to be cherry-picked
=> Fix builds on macOS

mypy/nodes.py, mypy/server/astmerge.py
Fixes https://github.com/python/mypy/issues/4646
This attribute is not used for long time.
=> Remove TypeInfo.replaced

mypyc/genops.py, mypyc/ops.py
Removing a bit of unnecessary code and reordering some things.
=> [mypyc] Some minor refactors to ops/genops

mypyc/ops.py, mypyc/test/test_run.py, mypyc/test/test_serialization.py
This is work towards incremental compilation (mypyc/mypyc#682).
Serialization format is JSON blobs similar to mypy itself.
The serialization and deserialization is not actually connected to
anything yet, except that run tests now validate that the
serialization round trips.
=> [mypyc] Implement serialization and deserialization of mypyc IR

mypy/types.py, test-data/unit/check-typeddict.test
=> Ensure that non-total TypedDicts can be falsy

mypy/suggestions.py, test-data/unit/fine-grained-suggest.test
Do this by grabbing the last function that starts on or above the
line specified.
=> [suggest] Allow requesting line numbers *in* the function

mypy/checkexpr.py, mypy/suggestions.py, test-data/unit/fine-grained-suggest.test, test-data/unit/typexport-basic.test
This reverts commit 766d58fea45c58a7c109ab1f62031fb0e9d08f3b.
Fixes #7826.
=> Revert "[suggest] Fix inference of returned collection (#7810)"

docs/source/config_file.rst
Add note about mypy_path on Windows in file config_file.rst.
Fixes #7805
=> Add note about mypy_path on Windows

mypy/meet.py, mypy/suggestions.py, test-data/unit/fine-grained-suggest.test
This is extremely simple, only taking types from function calls, but
hopefully will be pretty valuable anyway.
=> [suggest] Support a simple system for inferring argument types from uses

mypy/build.py, mypy/dmypy_server.py
This allows new plugins to be added by programs (like mypyc) that
directly invoke build.
=> Make mypy.build.build take an `extra_plugins` argument

mypy/build.py
This is a bit cleaner and I want to call some of these functions from
mypyc in a place where we don't have a BuildManager.
=> Make some stuff in mypy.build take Options instead of Manager

mypyc/build.py, mypyc/test-data/run-multimodule.test, mypyc/test/test_run.py
This isn't actually useful right now but is needed to test incremental
compilation.
=> [mypyc] Support multi-step testing for test_run

test-data/unit/check-incremental.test
Fixes https://github.com/python/mypy/issues/3327
The fix itself was likely the new semantic analyzer. I just add a test case from the issue.
=> Add a test for metaclass in import cycle

mypy/build.py
I want to be able to call this from mypyc, and it's a bit cleaner
anyway I think.
=> Pull creating a metastore out into a function in build

mypyc/genops.py, mypyc/test-data/exceptions.test
=> Skip docstring ExpressionStmts

mypyc/genops.py, mypyc/test-data/genops-classes.test
=> Fix spurious "Non-trait MRO must be linear"

mypy/checkexpr.py, test-data/unit/check-classes.test
=> Fix "Expression has type Any" error following attribute access

.travis.yml, setup.py
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Build with Python 3.8 released

test-data/unit/check-annotated.test
Fixes https://github.com/python/mypy/issues/7729
=> Add tests for PEP 593 annotated generic aliases

mypy/test/testparse.py, test-data/unit/check-generics.test, test-data/unit/check-incremental.test, test-data/unit/check-inference.test, test-data/unit/check-isinstance.test, test-data/unit/check-literal.test, test-data/unit/check-modules.test, test-data/unit/deps-expressions.test, test-data/unit/fine-grained.test, test-data/unit/parse-errors.test, test-data/unit/parse-python2.test, test-data/unit/pythoneval.test
This PR enables all skipped tests that can be enabled.
There are still 24 skipped tests left that still fail.
=> Enable a bunch of skipped tests

docs/source/mypy_daemon.rst
Document the `recheck` command and update wording in many
places. Reorder a few things.
=> Various small tweaks to mypy daemon documentation 

mypy/checker.py
It seems that in some cases `named_type` can fail, so instead I erase
the type using `erase_type`.
I don't have a simplified repro, but I verified that this fixes a crash
in an internal codebase.
=> Attempt to fix a crash related to partial defaultdict types

mypy/checkexpr.py, test-data/unit/check-modules.test
=> Fix TypedDict is recognized only when imported directly

runtests.py
I've seen this speed up `runtests.py` by about 20s when multiple cores are
available.
=> Tests: run self check and lint in parallel

mypy/checkexpr.py
Superseded by custom_special_method
=> Remove unused function custom_equality_method

mypy/checkstrformat.py, test-data/unit/check-expressions.test
=> Fix false positive for subclasses of bytes overriding __str__

docs/source/builtin_types.rst
Issue #8069 
First timer open for feedback ^^
=> Update builtin_types reflect bool subclass of int

mypy_self_check.ini
This would have helped me catch some variable annotations sooner.
=> mypy self check: add python_version = 3.5

.github/workflows/test.yml, .travis.yml, appveyor.yml, test-requirements.txt
virtualenv had a new release today that seems to break various things.
=> mypy: attempt to fix build

mypy/util.py
I refactored after I tested, which was a mistake.
=> Actually fix the api curses crash.

mypyc/genclass.py, mypyc/genops.py, mypyc/genopsutil.py
Also extract some utilities.
This mostly preserves the original structure of the code, even though it's
not optimal after extraction. This is something I plan to clean up later.
This introduces an import cycle that I will fix in a later PR.
=> [mypyc] Refactor: extract class-related genops to a new module

mypyc/genclass.py, mypyc/genfunc.py, mypyc/genops.py, mypyc/genopscontext.py, mypyc/genopsutil.py
The changes are fairly minimal beyond moving things around.
There's more refactoring that can be done later, such as removing the import cycle.
=> [mypyc] Refactor: extract function related genops to new modules

mypyc/emitmodule.py, mypyc/genops.py, mypyc/genopsmapper.py, mypyc/genopsprepare.py, mypyc/genopsvtable.py
I extracted various things that did things not directly related to the
main business of genops.
=> [mypyc] Extract more things from mypyc.genops

mypy/util.py
=> mypy: fix typeshed CI

docs/source/common_issues.rst
This is according to changes suggested in https://github.com/python/mypy/issues/7994
I will work further to update the code and point to this documentation when mypy throws error.
=> Add a section for incompatible overrides

mypyc/genexpr.py, mypyc/genops.py, mypyc/specialize.py
This follows the pattern established in recent refactoring PRs.
Also extract specializer code since it's used both by mypyc.genops
and mypyc.genexpr.
=> [mypyc] Refactor: extract IR generation for expressions from genops

mypyc/genexpr.py, mypyc/genopsvisitor.py
=> [mypyc] Refactor: move expression IR transform to top-level functions

mypyc/genclass.py, mypyc/genopsvisitor.py
=> [mypyc] Refactor: move class IR generation to top-level functions

mypyc/genclass.py, mypyc/genfunc.py, mypyc/genopsvisitor.py
=> [mypyc] Refactor: move function transform to top-level functions

mypyc/class_ir.py, mypyc/emit.py, mypyc/emitclass.py, mypyc/emitfunc.py, mypyc/emitmodule.py, mypyc/emitwrapper.py, mypyc/exceptions.py, mypyc/func_ir.py, mypyc/irbuild/builder.py, mypyc/irbuild/classdef.py, mypyc/irbuild/context.py, mypyc/irbuild/expression.py, mypyc/irbuild/function.py, mypyc/irbuild/ll_builder.py, mypyc/irbuild/mapper.py, mypyc/irbuild/prepare.py, mypyc/module_ir.py, mypyc/ops.py, mypyc/refcount.py, mypyc/sametype.py, mypyc/test/test_analysis.py, mypyc/test/test_emitfunc.py, mypyc/test/test_exceptions.py, mypyc/test/test_irbuild.py, mypyc/test/test_refcount.py, mypyc/test/test_serialization.py, mypyc/test/testutil.py, mypyc/uninit.py
=> [mypyc] Refactor: extract function IR from mypyc.ops

docs/source/common_issues.rst
Make things more explicit. Also did some style changes.
=> Clarify documentation of Liskov substitution principle

mypy/test/testpep561.py, test-data/unit/pep561.test
Fixes https://github.com/python/mypy/issues/8571
=> Make PEP 561 tests data driven

mypy/fastparse.py, mypy/fastparse2.py
=> Fix line numbers for variables bound by except

mypy/messages.py, test-data/unit/check-abstract.test, test-data/unit/check-class-namedtuple.test, test-data/unit/check-columns.test, test-data/unit/check-errorcodes.test, test-data/unit/check-expressions.test, test-data/unit/check-inference.test, test-data/unit/check-newsyntax.test, test-data/unit/check-tuples.test
=> Improve error message for bad indexed assignment

test-data/unit/check-columns.test
=> mypy tests: sidestep AST col_offset changes

mypy/checker.py, test-data/unit/check-callable.test
=> Fixes error that callable with None argument

scripts/mypyc
There's a lot that needs to be improved about this script but this was
just busted.
=> [mypyc] Fix specifying opt level with scripts/mypyc

mypyc/irbuild/ll_builder.py, mypyc/primitives/list_ops.py, mypyc/primitives/registry.py, mypyc/primitives/str_ops.py, mypyc/test-data/irbuild-lists.test
related mypyc/mypyc#709, mypyc/mypyc#734
=> Support binary ops via CallC

mypy/checkexpr.py, test-data/unit/check-literal.test
=> Don't consider comparing True and False as a dangerous comparison

docs/source/common_issues.rst
Make it closer the style used elsewhere. It's also more concise now.
=> Edits to discussion of unreachable code in the docs

test-data/unit/pythoneval.test
Change this so we can land https://github.com/python/typeshed/pull/4258
=> pythoneval.test: update for typeshed change

mypyc/irbuild/builder.py, mypyc/irbuild/expression.py, mypyc/irbuild/ll_builder.py, mypyc/primitives/int_ops.py, mypyc/test-data/analysis.test, mypyc/test-data/refcount.test, mypyc/test/test_analysis.py
relates mypyc/mypyc#741, mypyc/mypyc#743
=> [mypyc] low-level integer operations: integer equal

mypyc/irbuild/for_helpers.py, mypyc/irbuild/generator.py, mypyc/irbuild/nonlocalcontrol.py, mypyc/irbuild/statement.py, mypyc/primitives/exc_ops.py, mypyc/test-data/analysis.test, mypyc/test-data/exceptions.test, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-dict.test, mypyc/test-data/irbuild-statements.test, mypyc/test-data/irbuild-try.test, mypyc/test-data/refcount.test
relates mypyc/mypyc#734
Should we also consider building exceptions using the approach we treat int binary ops now? @JukkaL
=> [mypyc] Merge exception ops

mypyc/primitives/int_ops.py, mypyc/test-data/analysis.test, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-statements.test, mypyc/test-data/refcount.test
Relates mypyc/mypyc#741, merges all remaining integer logical ops.
=> [mypyc] Complete support of int logical ops

mypyc/irbuild/builder.py, mypyc/irbuild/callable_class.py, mypyc/irbuild/classdef.py, mypyc/irbuild/expression.py, mypyc/irbuild/function.py, mypyc/irbuild/statement.py, mypyc/primitives/misc_ops.py, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-classes.test, mypyc/test-data/irbuild-nested.test, mypyc/test-data/irbuild-try.test
=> [mypyc] Merge misc ops

mypyc/irbuild/for_helpers.py
=> [mypyc] Fix optimization for 'for x in reversed(list)'

mypyc/irbuild/builder.py, mypyc/irbuild/classdef.py, mypyc/irbuild/expression.py, mypyc/irbuild/ll_builder.py, mypyc/irbuild/specialize.py, mypyc/irbuild/statement.py, mypyc/primitives/misc_ops.py, mypyc/test-data/analysis.test, mypyc/test-data/exceptions.test, mypyc/test-data/irbuild-any.test, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-classes.test, mypyc/test-data/irbuild-dict.test, mypyc/test-data/irbuild-generics.test, mypyc/test-data/irbuild-lists.test, mypyc/test-data/irbuild-nested.test, mypyc/test-data/irbuild-optional.test, mypyc/test-data/irbuild-set.test, mypyc/test-data/irbuild-statements.test, mypyc/test-data/irbuild-try.test, mypyc/test-data/irbuild-tuple.test, mypyc/test-data/refcount.test, mypyc/test/test_emitfunc.py
This PR builds three specialized op directly in irbuild, instead of using name_ref_ops.
=> [mypyc] Build True, False and None op in irbuild

mypyc/irbuild/builder.py, mypyc/irbuild/classdef.py, mypyc/irbuild/ll_builder.py, mypyc/primitives/tuple_ops.py, mypyc/test-data/irbuild-basic.test, mypyc/test-data/irbuild-classes.test, mypyc/test-data/refcount.test
This PR supports new-style `new_tuple_op`, which completes the support of all tuple ops.
=> [mypyc] New style new_tuple_op

mypyc/analysis/dataflow.py, mypyc/codegen/emitfunc.py, mypyc/ir/ops.py, mypyc/test/test_emitfunc.py
This PR implements `SetMem` op to set value to a memory address.
=> [mypyc] Implement SetMem

README.md
#9407 - More accurate reference links in the README
N/A
=> Change travis-ci reference links to dot com

mypy/semanal.py, mypy/test/teststubtest.py
=> semanal: populate module_public even for missing modules

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md
- Remove emoji
- Instead of `## H2 headings` just use `**bold**`
- Add link to docs
- Add suggestion for new users not to file a bug
To see what it looks like: https://github.com/gvanrossum/mypy/issues/3 (you can file new bugs there as well)
=> Make the new bug templates less markup-heavy

mypy/__main__.py, mypy/main.py
The exit code was taken over from the old try/except.
Fixes #9419.
=> Wrap entry points to except BrokenPipeError

docs/source/error_code_list.rst, docs/source/literal_types.rst, mypy/checker.py, mypy/options.py, mypy/renaming.py, mypy/test/testinfer.py, mypyc/doc/introduction.rst, mypyc/ir/ops.py, mypyc/ir/rtypes.py, mypyc/test-data/run-classes.test, setup.py, test-data/stdlib-samples/3.2/random.py, test-data/stdlib-samples/3.2/tempfile.py, test-data/stdlib-samples/3.2/test/test_set.py, test-data/unit/check-newsemanal.test, test-data/unit/deps-classes.test, test-data/unit/fine-grained-follow-imports.test, test-data/unit/fixtures/object_with_init_subclass.pyi
This should not affect the current behavior.
=> Sort mypy.options.PER_MODULE_OPTIONS and fix typo

.github/workflows/test.yml, test-requirements.txt
Unpinned versions of the  following packages:
- setuptools
~~- virtualenv~~
Fixes #9401
=> Unpin package versions

README.md
(Once you have, delete this section. If you leave it in, your PR may be closed without action.)
=> DOC: README: HTTPSify docs url

mypy/test/data.py, mypyc/lib-rt/setup.py
The change to mypy.test.data is needed to work with the latest version
of pytest.
=> Self check fixes

mypy/typeanal.py, test-data/unit/check-callable.test, test-data/unit/check-future.test
=> Fix assignment of 'builtins.type' inferred as 'builtins.object'

setup.py
Background info at
https://github.com/pypa/warehouse/pull/7882#issue-412444446
=> Add News project URL

.github/ISSUE_TEMPLATE/crash.md
This might encourage users to submit higher-quality crash reports.
=> Add a separate issue form to report crashes

docs/source/cheat_sheet.rst
replace `<code>` with `...` for consistency with the rest of the document.
(Once you have, delete this section. If you leave it in, your PR may be closed without action.)
=> Fix inconsistent code marker in cheatsheet

mypy/config_parser.py
=> Continue reading next config file if no mypy section in shared conf

mypy/build.py, mypy/errors.py, test-data/unit/cmdline.test
Fixes #9727 (and effectively also adds a test for #9674)
=> build: disallow ignoring blocking errors

mypyc/test-data/irbuild-statements.test
=> Fix test failure caused by rebase

mypyc/ir/ops.py
It was a bit odd that module started with a long comment about
serialization, which isn't even the point of the file.
=> [mypyc] Minor cleanup of mypyc.ir.ops

mypyc/analysis/dataflow.py, mypyc/codegen/emitfunc.py, mypyc/ir/func_ir.py, mypyc/ir/ops.py, mypyc/ir/pprint.py, mypyc/primitives/int_ops.py, mypyc/transform/refcount.py
Tidy things up a bit, and improve documentation in code.
These mostly, but not exclusively, target `mypyc.ir.ops`.
=> [mypyc] Improve docstrings and comments + some minor refactoring

setup.py
Since my checklist in https://github.com/python/mypy/issues/9761 is
almost complete, it's time to check off this box as well.
=> Add Python 3.9 to trove classifiers

mypyc/doc/list_operations.rst, mypyc/primitives/list_ops.py, mypyc/test-data/fixtures/ir.py, mypyc/test-data/run-lists.test
Adding these since they are trivial to implement.
=> [mypyc] Add primitives for list.sort() and list.reverse()

mypy/stubtest.py
`__class_getitem__` and `__init_subclass__` are always classmethods, even if
they aren't decorated. We previously only handled this correctly if
these methods weren't overloaded.
This came up in https://github.com/python/typeshed/pull/4937
=> stubtest: fix signature construction for overload + implicit classmethod

MANIFEST.in, mypy-requirements.txt, setup.py
=> Fix pip install for new typeshed

mypy/test/testsamples.py
These haven't been working for a long time. Typeshed includes
a mypy test already, so it's fine to just remove this.
=> Remove broken typeshed tests

misc/sync-typeshed.py
Now you can sync the current typeshed master by just running
`misc/sync-typeshed.py` without any arguments.
=> Implement cloning typeshed in typeshed sync script

.github/workflows/mypy_primer_comment.yml
Fixes #10011
I think this is just vestigial from some debugging when I wrote this initially
=> mypy_primer: don't fail silently on comment failure

mypy/server/update.py, mypy/test/data.py, mypy/test/testcheck.py, mypy/test/testfinegrained.py, test-data/unit/fine-grained-follow-imports.test
=> Fix daemon crash when deleting packages

docs/source/error_codes.rst
(Once you have, delete this section. If you leave it in, your PR may be closed without action.)
=> Fix incomplete error codes documentation

misc/build_wheel.py
This will hopefully fix out of memory errors.
Work on #10074.
=> Use a 64-bit C compiler on Windows to build wheels

docs/source/common_issues.rst
This one is on our issue tracker's greatest hits.
Here's the issue I usually link: #2608
=> Add narrowing and closures to common issues

docs/source/index.rst, mypyc/doc/conf.py, mypyc/doc/index.rst, mypyc/doc/introduction.rst
Update the index page. Configure mypyc version in conf.py.
=> [mypyc] Various small doc updates

test-data/samples/generators.py
=> fix variable annotation syntax

mypyc/lib-rt/dict_ops.c, mypyc/primitives/dict_ops.py
Closes https://github.com/mypyc/mypyc/issues/831
=> [mypyc] Add incref in CPyDict_SetDefault

.travis.yml
relates https://github.com/python/mypy/pull/10345#issuecomment-823896985
=> Run compiled tests on the earliest supported Python (3.6)

mypy_self_check.ini
=> Run self check with Python 3.6

mypyc/irbuild/expression.py, mypyc/irbuild/specialize.py
Closes  https://github.com/mypyc/mypyc/issues/832
=> [mypyc] Support multiple specializers

.github/workflows/mypy_primer.yml, .github/workflows/mypy_primer_comment.yml
This is mostly the same as typeshed. The biggest difference is that we
don't post the "no effect" message. As a side effect, we also have to
run the comment hider first.
=> Port over latest GA mypy_primer changes

mypy/checkexpr.py
While reading the source code of this file, I have noticed a `TODO` that was easy to fix.
So, here it is! 👍
=> Updates docs in 'checkexpr.py' and fixes a TODO

mypyc/irbuild/ll_builder.py, mypyc/test-data/run-functions.test
=> [mypyc] Delete outdated TODOs

mypyc/analysis/dataflow.py, mypyc/build.py, mypyc/codegen/emit.py, mypyc/ir/class_ir.py, mypyc/ir/func_ir.py, mypyc/ir/rtypes.py, mypyc/irbuild/classdef.py, mypyc/irbuild/for_helpers.py, mypyc/lib-rt/pythonsupport.h, mypyc/test/testutil.py
A follow-up to https://github.com/python/mypy/pull/10792
Now I've checked all `mypyc/` files with https://github.com/codespell-project/codespell
Turns out, there are quite a lot of typos!
=> Fixes typos in mypyc

mypyc/irbuild/specialize.py
* Use docstrings in `specialize.py`
* Limit line length of comments and docstrings to 72 characters according to PEP 8
=> Use docstring in specialize.py

mypy/checker.py, test-data/unit/check-isinstance.test
Fixes #9907
For explanations, please see the commit message.
I hope changing the signature of method `TypeChecker.intersect_instances` is acceptable.
=> Fix false unreachable error reports.

mypyc/analysis/dataflow.py, mypyc/ir/ops.py, mypyc/transform/refcount.py
Add a `targets` property and a `set_target` method to `ControlOp` to
enable generic processing. Update CFG extraction, CFG cleanup, and
(most importantly) refcount insertion to operate generically.
This will make it easier to add new control ops, such as switch
statements.
=> Make the handling of ControlOp targets more generic

mypy/test/data.py, mypy/test/helpers.py, mypy/test/testcheck.py, mypy/test/testfinegrained.py, mypy/test/testpep561.py, mypyc/test-data/run-multimodule.test, mypyc/test/test_run.py, test-data/unit/pep561.test
As part of doing this I upgraded the pep561 tests to support
incremental tests, and removed at least a little of the duplication
between different incremental test suites.
=> Add an xfailed test for issue #9852

mypyc/lib-rt/CPy.h, mypyc/lib-rt/str_ops.c, mypyc/primitives/str_ops.py, mypyc/test-data/irbuild-str.test, mypyc/test-data/run-strings.test
Add primitives for `str.encode(...)`
=> [mypyc] Add primitives for str.encode()

mypy/modulefinder.py
Fixes #10483
Tested manually using importlib.metadata
=> Recognise typeshed submodules in VERSIONS

misc/proper_plugin.py
Closes #10719 
Since it is not tested, here's the demo:
=> Fixes `misc/proper_plugin` crash on `isinstance(1)`

mypy/checker.py, mypy/subtypes.py, test-data/unit/check-protocols.test
=> Fixes crash on partial `None`

mypy/constraints.py, test-data/unit/check-protocols.test
=> Fixes mypy crash on protocol with contravariant var

mypy/messages.py
TypeVarType is being imported twice, which isn't necessary.
./runtests.py
=> Remove duplicate import in mypy/messages.py

mypy_self_check.ini
So that mypy primer doesn't freak out on #9636
=> mypy self check: exclude test-data

mypy/build.py, mypy/fastparse.py, mypy/plugins/functools.py, mypy/plugins/singledispatch.py, mypy/semanal_main.py, mypy/stubgenc.py, mypy/util.py
I've noticed several missing `Final` types here and there.
I've looked though the whole project and added them where appropriate.
=> Adds `Final` types where they were missing

.github/workflows/build_wheels.yml, .github/workflows/docs.yml, .github/workflows/test.yml, .github/workflows/test_stubgenc.yml
ref https://github.com/python/mypy/pull/11406#issuecomment-954645101
Probably got missed when things were ported to Github Actions
cc @ilevkivskyi
=> Run tests on release branches

mypy/pyinfo.py
This is a follow up from https://github.com/python/mypy/pull/11444
=> Fix small error in pyinfo.py

docs/source/kinds_of_types.rst, mypy/subtypes.py, test-data/unit/check-namedtuple.test, test-data/unit/fixtures/typing-namedtuple.pyi, test-data/unit/pythoneval.test
=> Adds support for `NamedTuple` subtyping

CONTRIBUTING.md
This is my first pull request so I am not sure if this is the right way
Fixes #11473
=>  Editing Contributing.md and adding missing 'v' in the 'activate' word

mypy/semanal.py, test-data/unit/check-flags.test, test-data/unit/check-newsemanal.test
This came up in https://github.com/python/typeshed/pull/6171
=> semanal: fix module_public in the presence of getattr

mypy/constraints.py, mypy/types.py
This is a follow-up for #11460
=> Use implementation artifact Any for constraint target

mypy-requirements.txt, setup.py, test-requirements.txt
I don't believe we will make incompatible changes within `typed_ast 1.*`. Cc @JelleZijlstra @hauntsaninja
=> Bump typed_ast max dependency

mypy/server/astdiff.py, test-data/unit/diff.test
=> Fix crash related to AST diff of ParamSpec in mypy daemon

docs/requirements-docs.txt
Some context in #11412 / change as mentioned in https://github.com/python/mypy/issues/11158#issuecomment-967700843
cc @ilevkivskyi
=> Fix ReadTheDocs build on release branch

mypy/argmap.py
=> Microrefactoring: removes unused `value` from `map_actuals_to_formals`

.github/workflows/mypy_primer.yml
Solves https://github.com/hauntsaninja/mypy_primer/issues/21
=> [mypy_primer] use merge base as base commit

mypy/join.py
Looks like there was a new release of flake8-bugbear
=> Fix new lint warning

docs/source/command_line.rst
Small error I spotted while working on #11633 but is unrelated.
n/a - docs change.
=> Fix grammar for clarity

mypy-requirements.txt, setup.py
Tomli 2.0.0 was released https://pypi.org/project/tomli/2.0.0/
I think it would be good to keep up to date with this release.
=> upgrade tomli to 2.0.0

setup.py
=> Add Python 3.10 to trove classifiers

mypy/version.py
This is for the 0.930 release branch. I'll update the master to
0.940+dev afterwards.
=> Update version to 0.930+dev

mypy/typeshed/stdlib/os/__init__.pyi
Backport of https://github.com/python/typeshed/pull/6591
cc @JukkaL
=> [0.930 backport] Fix PathLike regression

.github/workflows/mypy_primer.yml
Similar reasoning to https://github.com/python/typeshed/pull/6593
=> [mypy_primer] run using 3.10

test-data/unit/semanal-errors.test
I've made a typo in https://github.com/python/mypy/pull/11814
=> Fixes typo

mypy/semanal.py, test-data/unit/check-flags.test
=> Consider import * to be an explicit re-export

CONTRIBUTING.md
mypy attracts a lot of (usually student) first-time contributors who
tend to comment on issues with things like "May I work on this issue?
Can anyone provide me guidance?" and often end up not getting a
response. This helps neither the would-be-contributor nor mypy.
The goal of this PR is to have a section we can just link to as a reply
in such situations.
=> CONTRIBUTING.md: more words for first-time contributors

mypy/checkpattern.py
Compare the `for..in` loop in line 531 with line 552, the variable in line 570 should be `pattern` instead of `value`.
=> Fix one invalid reference inside visit_class_pattern

mypy/stubinfo.py
See https://github.com/python/typeshed/issues/5863
=> Remove orjson stubs from default list

misc/build_wheel.py
Closes https://github.com/python/mypy/issues/10650
=> Support universal2 wheel

misc/proper_plugin.py
This will be broken by https://github.com/python/typeshed/pull/7454
=> Fix proper_plugin for typeshed tuple change

mypy/main.py
=> Print compilation status with `--version`

.github/workflows/mypy_primer_comment.yml
Analog to https://github.com/python/typeshed/pull/7525
=> mypy_primer: mention if output is truncated

build-requirements.txt
Noticed this was out of date so I figured it would be good to try to bump it :)
=> Update typed_ast types for build

README.md
`introduction.rst` has moved into `index.rst` in #12348 and <https://mypy.readthedocs.io/en/stable/introduction.html> is dead now.
=> Revive dead link in readme

mypy/test/data.py, mypy/test/helpers.py, mypy/test/test_find_sources.py, mypy/test/testargs.py, mypy/test/testcheck.py, mypy/test/testcmdline.py, mypy/test/testdeps.py, mypy/test/testfinegrained.py, mypy/test/testgraph.py, mypy/test/testmerge.py, mypy/test/testpep561.py, mypy/test/testpythoneval.py, mypy/test/testsemanal.py, mypy/test/teststubgen.py, mypy/test/teststubtest.py, mypy/test/testsubtypes.py, mypy/test/testtypegen.py, mypy/test/testtypes.py
Re-attempt of #10741
Ran: `pyupgrade --py36-plus $(fd -e py) --keep-runtime-typing`
I mostly only needed to change things where NamedTuple comments got
dropped.
=> mypy/test: run pyupgrade

misc/actions_stubs.py, misc/analyze_cache.py, misc/apply-cache-diff.py, misc/fix_annotate.py, misc/incremental_checker.py, misc/perf_checker.py, misc/sync-typeshed.py, misc/test_case_to_actual.py, misc/touch_checker.py, misc/variadics.py, runtests.py, scripts/find_type.py, setup.py
Re-attempt of #10741
Ran: `pyupgrade --py36-plus $(fd -e py) --keep-runtime-typing`
I mostly only needed to change things where NamedTuple comments got
dropped.
=> misc: run pyupgrade

docs/source/type_inference_and_annotations.rst
Co-authored by: @chrisbeardy
Replaces #10098
=> Mention no_type_check in docs

test-data/unit/README.md
`-xfail` has been implemented by #10635, however lack of documentation in README.
=> Add documentation for `-xfail`

mypy/stubtest.py, mypy/test/teststubtest.py
=> stubtest: allow ellipsis as default argument

mypy/stubtest.py
=> stubtest: add --version

mypy/typeshed/stdlib/_typeshed/__init__.pyi, mypy/typeshed/stdlib/unittest/case.pyi
Fixes https://github.com/python/mypy/issues/13090
=> Fix typeshed regression in unittest

mypy/fswatcher.py, mypy/modulefinder.py
Hopefully now NamedTuples work :-)
=> Use new NamedTuples in mypy

mypy/typeshed/stdlib/typing_extensions.pyi
https://github.com/python/typeshed/pull/8295
=> [0.970 backport] add typing_extensions.NamedTuple

mypyc/primitives/float_ops.py, mypyc/primitives/tuple_ops.py, mypyc/test-data/irbuild-dunders.test, mypyc/test-data/run-python37.test, mypyc/test-data/run-tuples.test
Backport of https://github.com/python/mypy/pull/13078
=> [0.970 backport] [mypyc] Add LoadAddress op for PyFloat_Type & PyTuple_Type

mypy/semanal.py, test-data/unit/semanal-basic.test
Fixes #12730
Co-authored-by: mrolle45
=> Allow nonlocal in function scoped classes

.github/workflows/build_wheels.yml, .github/workflows/docs.yml, .github/workflows/mypy_primer.yml, .github/workflows/mypy_primer_comment.yml, .github/workflows/test.yml, .github/workflows/test_stubgenc.yml
References https://github.com/python/typeshed/commit/b0202f71ebcf723f6756746c7848b53b4fe3ef41
=> Update GitHub Actions to their latest versions

mypy/errors.py
=> Fix flake8

.git-blame-ignore-revs
Required next step for #12424 and #10996
=> (🎁) Add black/isort git blame ignore rev

README.md
Oops 😁
- Introduced in #12424
- Related #10996
=> Fix black badge in readme

mypy/checkmember.py
It only had one place where `python2` was involved.
=> Remove python2 logic from `checkmember.py`

mypy/stubutil.py, mypy/util.py
=> Clean up Python 2 helpers

mypy/fastparse.py, mypy/semanal.py, mypy/semanal_classprop.py, mypy/semanal_pass1.py
=> Remove Python 2 specific semanal and parse logic

mypy/semanal.py, mypy/semanal_newtype.py, mypy/semanal_typeddict.py, test-data/unit/check-newtype.test, test-data/unit/check-typeddict.test, test-data/unit/semanal-errors.test
=> Disallow bytes in TypeVar, NewType, and TypedDict names

mypy/build.py, mypy/modulefinder.py, mypy/stubinfo.py, mypy/test/teststubinfo.py
=> Simplify stubinfo without Python 2

mypy/messages.py, mypy/operators.py, mypy/plugins/attrs.py, mypy/sharedparse.py
=> Remove python2 magic methods support

setup.py
Since we now support >=3.7 - it is time to update our `setup.py`
=> Use 3.7 in `setup.py`

misc/proper_plugin.py, test-data/unit/plugins/decimal_to_int.py
Refs https://github.com/python/mypy/pull/13366
Refs https://github.com/python/mypy/pull/13355
=> Run `pyupgrade` on all other python sources

mypy/build.py, mypy/checker.py, mypy/checkstrformat.py, mypy/fixup.py, mypy/main.py, mypy/messages.py, mypy/test/data.py, mypy/test/testdiff.py, mypy/typeanal.py
This was probably broken when `black` was initially applied.
=> Fix `" "` line joining after `black` reformat

mypy/semanal.py, test-data/unit/check-type-aliases.test
Discovered this when playing with new flag
=> Fix crash on deferred upper bound with recursive aliases enabled

build-requirements.txt, mypy/dmypy_server.py
=> Add `types-psutil` as a build requirement

mypy/stubtest.py
Fixes #13654, caused by #13629
=> Fix stubtest custom_typeshed_dir regression

mypy/stubtest.py
Fixes #13654, caused by #13629
=> [0.980 backport] Fix stubtest custom_typeshed_dir regression (#13656)

mypy/partially_defined.py, test-data/unit/check-partially-defined.test
Adds support for `WithStmt` nodes for the partially defined check.
/CC: @ilinum
=> Handle WithStmt when checking for partially defined vars

docs/source/running_mypy.rst
=> Mention files confval in "specifying code to check"

.github/ISSUE_TEMPLATE/bug.md
Suggest providing a link to the project to help fuel mypy_primer. Let Github wrap text. Phrase things more concisely.
=> Update issue template

.github/ISSUE_TEMPLATE/bug.md
Meant to do this in https://github.com/python/mypy/pull/13722
=> Mention mypy playground in bug template

docs/source/builtin_types.rst, docs/source/getting_started.rst
See #13681. I'd like to make bigger changes to this page, but still thinking them through
=> Update getting started docs

.github/workflows/sync_typeshed.yml, misc/sync-typeshed.py, tox.ini
=> Workflow to automatically sync typeshed

mypyc/lib-rt/int_ops.c
=> [mypyc] Fix C errors about shifting negative integers

mypy/main.py, mypy/test/testpythoneval.py, test-data/unit/cmdline.test
Fixes #10013
See https://github.com/python/mypy/pull/13851#issuecomment-1274345759 for motivation, also this sounds generally reasonable.
=> Return 0 if there are only notes and no errors

misc/sync-typeshed.py
Makes sure we continue to cherry pick https://github.com/python/mypy/pull/13961
=> Revert sum literal changes on an ongoing basis

test-data/unit/check-parameter-specification.test
Don't think there's a test case corresponding to the issue in #13966
=> Add another invalid ParamSpec test case

mypy/version.py
Next release is 1.0 so also update the comments.
NOTE: Should we go with 1.0 or 1.0.0? I chose 1.0.0 to make it clear that we can have minor revisions 3 numbers deep. i.e. x.y.z
=> Update version on master for next release

mypyc/irbuild/classdef.py, mypyc/test-data/run-classes.test
Fixes https://github.com/mypyc/mypyc/issues/896
=> [mypyc] allow use of enum.Enum

docs/source/running_mypy.rst
=> running_mypy.rst: Fix typo

test-requirements.txt
Ref #12840 
Hopefully it will work.
=> Enable lxml tests on Python 3.11

mypy/util.py
=> Make non-numeric non-empty FORCE_COLOR truthy

mypy/partially_defined.py
This was incorrect for a few callsites. I refactored the code to make it harder to make a mistake like this.
This wasn't visible before because we only run the PartillyDefinedVisitor if either of the error codes reported by it are enabled.
=> [partially defined] fix gating by error code

README.md
Several issues that I have seen recently could be fixed by enabling/disabling an error code. I think we should attract more attention to error code customization (especially for new users).
=> Add link to error codes in README

README.md
Now that daemon is more mature and stable I think we can attract some more attention to it.
=> Advertise mypy daemon in README

mypy/checker.py, mypy/checkexpr.py, mypy/types.py
These are part of the changes that collectively bring a 6% performance improvement. These are all pretty minor.
=> A few miscellaneous micro-optimizations

mypyc/ir/class_ir.py, mypyc/ir/ops.py, mypyc/primitives/int_ops.py, mypyc/primitives/registry.py
=> Use class-based NamedTuples in mypyc

mypy_self_check.ini
These two options in the config file are redundant.
=> (🧹) cleanup config file

mypy/moduleinspect.py
=> stubgen: treat dlls as c modules

tox.ini
=> Fix passenv for tox 4

docs/source/error_code_list2.rst, docs/source/generics.rst, docs/source/index.rst, mypy/semanal.py, test-data/unit/check-selftype.test
I looked at `git diff v0.991 master -- docs` and did some editing. There no major changes to content. Also updated one error message.
=> Various documentation and error message tweaks

mypy/version.py
The 1.0 release branch has been cut!
=> Bump version to 1.1.0+dev

docs/source/error_code_list.rst
Adding documentation for used-before-def check.
=> [1.0 backport] [used before def] add documentation (#14592)

mypy/version.py
=> Promote 1.0.0+dev to 1.0.0

misc/upload-pypi.py
When uploading 1.0.0, I realized that this script needs updating.
=> update upload-pypi script to the new versioning scheme

mypy/types.py, test-data/unit/check-typevar-values.test
=> [backport] Fix crash on deferred value constrained TypeVar (#14642)

misc/sync-typeshed.py
#14719 fixed some merge conflicts
=> Update commit hashes in sync typeshed script

mypy/version.py
The release-1.1 branch now exists.
=> Bump dev version to 1.2.0+dev

docs/source/stubtest.rst
Fixes a typo in stubtest docs.
=> Fix typo in stubtest docs

tox.ini
As the number grows starts to need search and wondering at what place to add a new one. Making sorted makes the order obvious
(will conflict with #14831 but will be easy to resolve there)
=> Sort tox testenvs to ease finding one

mypy/test/data.py, test-data/unit/check-attr.test, test-data/unit/check-enum.test, test-data/unit/check-functools.test, test-data/unit/check-isinstance.test, test-data/unit/check-modules.test, test-data/unit/check-parameter-specification.test, test-data/unit/check-protocols.test, test-data/unit/check-singledispatch.test, test-data/unit/check-slots.test, test-data/unit/check-typevar-values.test, test-data/unit/fine-grained-modules.test, test-data/unit/fine-grained.test
I didn't realize `builtins` tags in tests add two of the same file, rendering the first call of it useless! Anyways, now I know, and this PR should raise an error for anyone in similar straits. I believe I fixed all the tests?
The error message is a bit... intimidating (for some reason raising a ValueError here makes some assert trip later on which has a long traceback) but I decided to imitate the other error messages nearby.
=> Check for duplicated files in tests

misc/sync-typeshed.py
=> Update commit hashes in `misc/sync-typeshed.py` following typeshed sync

docs/source/more_types.rst
I added this section in #14973. Fixes #14996
=> Also mention overloads in async iterator documentation

CONTRIBUTING.md
Adding the following documentation updates to MyPy's CONTRIBUTING.md:
- Adding additional step to ensure contributors fork the repository.
- Markdown Formatting changes consistent with the following rules:
- MD022/blanks-around-headings/blanks-around-headers: Headings should be surrounded by blank lines
- MD040/fenced-code-language: Fenced code blocks should have a language specified
- MD004/ul-style: Unordered list style [Expected: dash; Actual: asterisk]
=> Documentation Update to CONTRIBUTING.md

misc/sync-typeshed.py
=> Update hashes in `misc/sync-typeshed.py` following typeshed sync

.pre-commit-config.yaml, test-requirements.txt
The two files got out of sync after #15167
=> Synchronize test-requirements.txt and .pre-commit-config.yaml

mypy/expandtype.py, mypy/semanal_typeddict.py
This is another PR to prepare for variadic type aliases.
=> Allow using expand_type during semantic analyzis

mypy/checker.py, mypy/checkexpr.py, mypy/constraints.py, mypy/expandtype.py, mypy/plugins/common.py, mypy/semanal.py, mypy/subtypes.py, mypy/suggestions.py, mypy/test/testtypes.py, mypy/typeanal.py, mypy/types.py, mypy/types_utils.py
This is a pure refactor to improve code organization.
=> Move some utils that use get_proper_type away from types.py

.github/workflows/test.yml
=> Fix mypyc 32-bit build

.git-blame-ignore-revs
=> .git-blame-ignore-revs: add PEP-604 refactor

mypy/checkexpr.py, mypy/copytype.py, mypy/plugins/attrs.py, mypy/plugins/dataclasses.py, mypy/semanal.py, mypy/semanal_namedtuple.py, mypy/tvar_scope.py, mypy/typeanal.py, mypy/types.py, mypy/typevars.py
Also use keyword arguments + copy_modified for this in many places
=> Propagate TypeVarType column in TypeAnalyser

mypy/stubtest.py
=> Improve stubtest error message

mypy/semanal.py, test-data/unit/check-statements.test
=> Correctly track loop depth for nested functions/classes

mypy/test/meta/test_parse_data.py
Fixes https://github.com/python/mypy/pull/15385#issuecomment-1587030261
=> test_parse_data: fix cwd

mypyc/lib-rt/pythonsupport.h
We've copied some code CPython, which was changed in 3.12.
Work on mypyc/mypyc#995.
=> [mypyc] Fix gen_is_coroutine on Python 3.12

.pre-commit-config.yaml
Might as well support mypyc usage in the ecosystem :-)
=> Switch pre-commit to using mypyc compiled Black wheels

misc/sync-typeshed.py
Got commits from https://github.com/python/mypy/commits/master after merging https://github.com/python/mypy/pull/15590
=> Update commits for sync-typeshed cherry picks

mypy/test/testcheck.py, test-data/unit/check-basic.test, test-data/unit/check-bound.test, test-data/unit/check-dynamic-typing.test
=> Enable strict optional for more test files (4)

mypy/test/testcheck.py, test-data/unit/check-expressions.test
Followup to https://github.com/python/mypy/pull/15586
=> Enable strict optional for more test files (5)

mypy/version.py
Created the [release-1.5 branch](https://github.com/python/mypy/tree/release-1.5), updating version
=> Update dev version to 1.6.0+dev

misc/cherry-pick-typeshed.py
It should exclude test_cases too
=> fix cherry-pick-typeshed

misc/sync-typeshed.py
=> Update commit hashes following typeshed sync

docs/source/cheat_sheet_py3.rst
Added a missing verb to the cheat sheet.
=> docs: added missing verb

.pre-commit-config.yaml, test-requirements.txt
Closes https://github.com/python/mypy/pull/15526
=> Update pre-commit deps

docs/source/error_codes.rst
Provide a concrete example of what file level comments would look like. Sort text into sections a little better.
=> Improve error code disabling documentation

test-data/unit/check-callable.test
See #13431
Authored by ilevkivskyi
=> Add regression test for expand type -> simplified union crash

mypy/expandtype.py, mypy/semanal_typeargs.py, mypy/test/testtypes.py, mypy/typeanal.py, mypy/types.py, test-data/unit/check-typevar-tuple.test
Fixes https://github.com/python/mypy/issues/15410
Fixes https://github.com/python/mypy/issues/15411
=> Fix type arguments validation for variadic instances

misc/sync-typeshed.py
=> Update hashes in `sync-typeshed.py` following typeshed sync

mypy/test/helpers.py, mypy/test/meta/test_diff_helper.py
=> Add meta test for new diff logic

.pre-commit-config.yaml, mypy/build.py, mypy/main.py, mypy/metastore.py, mypy/plugins/common.py, pyproject.toml, setup.py, test-requirements.txt
=> Bump ruff and black to their latest versions

mypyc/analysis/dataflow.py
This PR aims to close https://github.com/python/mypy/issues/16307.
___
* (refactor): add using of f-strings in `__str__` method
=> refactor: `__str__` in `CFG` class (#16307)

CHANGELOG.md
Add sections for related changes. Remove some internal changes and make other small tweaks.
=> Updates to 1.7 changelog

CHANGELOG.md
Add sections covering bigger changes.
=> Improvements to changelog for mypy 1.7

misc/gen_blog_post_html.py
This is an adaptation of an older script that we used to convert from a Paper doc to HTML.
This includes changes by @gvanrossum and @svalentin.
=> Script to generate release blog post from changelog

CHANGELOG.md
We are now very close to release.
=> Mark mypy 1.7 changelog as final/released

mypy/stubtest.py
=> stubtest: warn about missing __del__

misc/sync-typeshed.py
=> Update hashes in `sync-typeshed.py` following recent typeshed sync

mypy/version.py
Preparation step for the 1.8.0 release.
=> bump version to 1.9.0+dev

mypy/modulefinder.py
Closes https://github.com/python/mypy/issues/16632
=> Remove `_is_compatible_stub_package` check from `modulefinder`

mypy/types.py
I noticed the typo so I figured I might as well fix it.
=> fix a single-letter typo in a comment

mypy/stubgen.py, test-data/unit/stubgen.test
=> stubgen: Do not ignore property deleter

test-data/unit/check-generics.test
https://github.com/python/mypy/pull/15879#discussion_r1475245425
=> Fix duplicated TypeVarTuple test

mypy/version.py
The release branch has been cut: https://github.com/python/mypy/tree/release-1.9.0
Increase the dev version.
=> Bump version to 1.10.0+dev

.github/workflows/build_wheels.yml, .github/workflows/docs.yml, .github/workflows/mypy_primer.yml, .github/workflows/mypy_primer_comment.yml, .github/workflows/sync_typeshed.yml, .github/workflows/test.yml, .github/workflows/test_stubgenc.yml
Update `actions/setup-python` from `v4` to `v5` and `actions/github-script` from `v6` to `v7`.
https://github.com/actions/setup-python/releases/tag/v5.0.0
https://github.com/actions/github-script/releases/tag/v7.0.0
=> Update CI actions

docs/source/cheat_sheet_py3.rst
Improve doc, import `ClassVar` before using it.
=> [Docs] import ClassVar before using it

misc/sync-typeshed.py
=> Update commit hashes in sync-typeshed.py

mypy/version.py
https://github.com/python/mypy/tree/release-1.10
Increase the dev version.
=> Bump version to 1.11.0+dev

test-data/unit/check-python312.test
=> [PEP 695] Add tests for type alias in class body or function

mypyc/lib-rt/pythoncapi_compat.h
This helps with Python 3.13 support.
=> [mypyc] Sync pythoncapi_compat.h

mypy/build.py, mypy/errors.py, test-data/unit/check-incremental.test
Fixes https://github.com/python/mypy/issues/16766, fixes https://github.com/python/mypy/issues/17049
=> Fix error reporting on cached run after uninstallation of third party library

mypy/stubdoc.py, mypy/stubgenc.py, mypy/test/teststubgen.py
Updates the is_valid_type regex to include quotes and .
=> Add Literal support for docstrings

mypy/main.py
Fixes #17466
Change help message of '--no-namespace-packages' option
=> Fix help message for --no-namespace-packages.

CHANGELOG.md
Add a changelog for the 1.11 release.
=> CHANGELOG.md update for 1.11

mypy/checkexpr.py, test-data/unit/pythoneval.test
Mentioned by Jelle in https://github.com/python/mypy/pull/17543#issuecomment-2240829583
=> Indexing a type also produces a GenericAlias

mypy/types.py, test-data/unit/check-incremental.test
=> Fix PEP 604 isinstance caching

.github/workflows/docs.yml
=> Use newer Python in docs build

docs/source/command_line.rst
Documents the new option added by https://github.com/python/mypy/pull/11396.
=> Document `--output=json` CLI option

mypy/version.py
https://github.com/python/mypy/tree/release-1.12
=> Bump version to 1.13.0+dev

MANIFEST.in
=> Include CHANGELOG.md in sdists

docs/source/extending_mypy.rst, mypy/checkmember.py, mypy/plugin.py, test-data/unit/check-custom-plugin.test, test-data/unit/plugins/attrhook2.py
=> Add is_lvalue attribute to AttributeContext

.github/workflows/test.yml
It's started failing on master due to agent changes and also it never tested debug builds in the first place, see issues linked
https://github.com/python/mypy/actions/runs/11283075094/job/31381791947
=> Remove debug build for now

.github/workflows/mypy_primer.yml, .github/workflows/mypy_primer_comment.yml
Update the mypy_primer workflow to use actions/upload-artifact@v4.
https://github.com/actions/upload-artifact/tree/v4
=> Update mypy_primer workflow

mypy/checker.py
Move a big chunk of code to a helper function.
=> Refactor type narrowing further

docs/requirements-docs.txt, docs/source/conf.py
sorry for https://github.com/python/mypy/pull/17972 and thanks @Viicos
=> [docs] automatic copyright year update

.pre-commit-config.yaml
Taken from https://github.com/python/cpython/commit/dcda92f8fcfa70ef48935db0dc468734de897d96
I temporarly disabled some checks due to https://github.com/python/mypy/pull/17822
=> Lint github actions and dependabot.yml

docs/source/extending_mypy.rst
Small fix to correct the last sentence in the extending mypy docs.
=> Fixed typo in extending mypy docs.

docs/requirements-docs.txt, docs/source/conf.py, docs/source/running_mypy.rst
https://sphinx-inline-tabs.readthedocs.io/en/latest/
=> Add sphinx_inline_tabs to docs

test-data/unit/check-isinstance.test
Regression test for https://github.com/python/mypy/issues/11839 resolved with https://github.com/python/mypy/pull/18138.
=> Add regression test for isinstance narrowing

misc/perf_compare.py
Sometimes we need more iterations to get precise results.
=> Add num iterations option to the perf_compare internal tool

mypy/version.py
https://github.com/python/mypy/tree/release-1.14
Increase the dev version.
=> Bump version to 1.15.0+dev

docs/source/generics.rst
Found this typo while reading through the docs. `declarare` -> `declare`
=> Fix type in `generics.rst`

test-data/unit/check-namedtuple.test
See https://github.com/python/mypy/pull/18351#pullrequestreview-2525435197
Co-authored-by: ilevkivskyi
=> Add regression test for NamedTuple with recursive bound

mypy/version.py
https://github.com/python/mypy/tree/release-1.15
Increase the dev version.
=> Bump version to 1.16.0+dev

mypy/checkexpr.py, test-data/unit/check-statements.test
=> Add missing lineno to `yield from` with wrong type

mypy/plugins/default.py
=> Improve inference in tuple multiplication plugin

.pre-commit-config.yaml, mypy/test/testinfer.py, mypy/types.py
https://github.com/psf/black/releases/tag/25.1.0
=> Update black to 25.1.0

mypy/nodes.py
=> Include fullname in Var repr

mypyc/doc/frozenset_operations.rst, mypyc/doc/str_operations.rst
(Also unrelated minor formatting tweak to frozenset docs.)
=> [mypyc] Document that strip() etc. are optimized

mypy/checkmember.py
This is a pure refactoring so I am not waiting for a review.
=> Inline a trivial function in checkmember.py

test-data/unit/check-classes.test
Ref https://github.com/python/mypy/pull/18787#discussion_r2051824223
=> Fix typo in testPropertySetterDecorated

mypy/version.py
https://github.com/python/mypy/tree/release-1.16
=> Bump version to 1.17.0+dev

mypyc/test-data/run-async.test
=> [mypyc] Test function nesting with async functions

test-data/unit/stubgen.test
add test case for #16658 issue
=> stubgen: add test case for handling incomplete return types

mypy/util.py, test-data/unit/check-enum.test
Fixes https://github.com/python/mypy/issues/19271.
=> Single underscore is not a sunder

docs/source/error_code_list2.rst
Fix docs typo in
- #19144
Reference
- https://github.com/python/mypy/issues/13597#issuecomment-2962338749
=> Fix `exhaustive-match` error code in title

mypy/plugins/default.py
It looks like these nested imports are not needed anymore.
=> Remove all nested imports from default plugin

CHANGELOG.md
Add a few sections and do some editing.
=> Updates to 1.17 changelog

mypyc/ir/rtypes.py
=> chore: homogenize TypeGuard usage in rtypes.py

mypy/main.py
It is time to announce this (as still experimental obviously).
=> Make --allow-redefinition-new argument public
