- mypy/checkexpr.py
- mypy/types.py
- test-data/unit/check-unions.test
- test-data/unit/fixtures/ops.pyi
Resolves #8125 
@appleby has some really good thoughts on the issue and I tried some of them. 
The main problem is not about flattening unions inside variants since the following code generates no error
```python
from typing import Union
T1 = Union[int, float]
T2 = Union[Union[Union[int, float], float], Union[float, complex], complex]
def foo(a: T2, b: T2) -> T2:
return a + b
```
The problem, however, is because when using `TypeAliasType` to alias a Union, the `TypeAliasType` will not get flattened, so this PR fixes this.
I haven't added testcase yet, since no proper fixture file seems to support the add ops in the test code of #8125 , so lots of `error: Unsupported left operand type for + ` will be reported (running mypy using command line will pass the test code)
cc @msullivan
> Flatten TypeAliasType when it is aliased as a Union

- mypy/checker.py
- test-data/unit/check-inference.test
- test-data/unit/fixtures/set.pyi
Code like this no longer requires a type annotation:
```
x = []
x += [1, 2]
```
> Support partial type inference with += and |=

- mypy/semanal.py
- test-data/unit/check-classes.test
- test-data/unit/fixtures/staticmethod.pyi
Resolves #8161 
According to comments of `lookup` in `mypy/semanal.py`, when we look up a class attribute, we require that it is defined textually before the reference statement, thus line number is used for comparison.
When function has decorators, its line number is determined by the top decorator instead of the `def`. That's why #8161's code fails because on line 8, the `A` in `Type[A]` has the line number of 8 while the @staticmethod function `A` has the line number of 7 due to the decorator. 
Thus we need to properly handle this by introducing the number of decorators when deciding textural precedence.
> Fix incorrect name lookup for decorated methods

- .travis.yml
Previously -n12 provided fast builds, but it looks like -n2 is marginally faster 
now. Total runtime went from 1 hr 48 min to 1 hr 41 min (though with a sample
size of 1).
> Reduce Travis parallelism

- .travis.yml
Previously we ran them both compiled and interpreted, which
seems redundant.
> Only run Travis tests on Python 3.7 once (compiled)

- runtests.py
Previously various slow tests were included with fast tests, resulting
in non-optimal parallelization.
> Tests: correctly mark which tests are slow

- .travis.yml
Python 3.5.1 tests were the slowest job, and this makes them faster
(roughly from 20min to 15min).
> Run 3.5.1 tests compiled with mypyc

- mypy/checker.py
- mypy/nodes.py
- mypy/test/testinfer.py
- test-data/unit/check-enum.test
- test-data/unit/check-optional.test
This pull request is v2 (well, more like v10...) of my attempts to make our reachability code better understand chained comparisons.
Unlike https://github.com/python/mypy/pull/7169, this diff focuses exclusively on adding support for chained operation comparisons and deliberately does not attempt to change any of the semantics of how identity and equality operations are performed.
Specifically, mypy currently only examines the first two operands within a comparison expression when refining types. That means the following expressions all do not behave as expected:
```python
x: MyEnum
y: MyEnum
if x is y is MyEnum.A:
if x is MyEnum.A is y:
```
This pull request fixes this so we correctly infer the literal type
for x and y in both conditionals.
Some additional notes:
1. While analyzing our …
> Make reachability code understand chained comparisons (v2)

- mypy/checker.py
- test-data/unit/check-optional.test
This PR fixes the crash reported in https://github.com/python/mypy/issues/8230 by replacing the 'pass' with the 'continue', as suggested.
However, it does *not* fix the underlying root cause -- I don't think I actually understand the relevant pieces of code enough to feel confident volunteering a fix. So, I settled for this more limited fix.
Basically, it seems this bug is due to how we try inferring the type of the lambda in multiple passes to resolve the types. We pencil in an ErasedType during the first pass -- and then subsequently crash when attempting to type check the body during that pass. I'll leave more details about this in the linked issue.
> Fix regression in container check logic

- README.md
- runtests.py
- test-data/unit/README.md
The skipped mypyc run tests are very slow and I believe that they only
rarely fail for changes that don't touch mypyc.
The skipped tests can be run via `runtests.py mypyc-extra`.
Also explain running tests in some more detail in the the docs.
> Make runtests.py skip some slow mypyc tests by default

- mypy/util.py
fixes #8242
Original error code indexing is assuming all `msg's included a '[',  which clearly fails on  "unused 'type: ignore' comment", this PR provides correct string finding and substring indexing thus a correct colorization.
However, it also seems meaningful to add an error code for this error. Suggestions are welcomed.
> Fix incorrect "unused 'type: ignore' comment" error log coloring

- mypy/util.py
> Switch to using sha1 for hashes

- mypy/checker.py
- mypy/checkexpr.py
- mypy/checkstrformat.py
- mypy/typeops.py
- test-data/unit/check-enum.test
- test-data/unit/check-narrowing.test
- test-data/unit/check-optional.test
This pull request (finally) adds support for narrowing expressions using Literal types by equality, instead of just identity. For example, the following "tagged union" pattern is now supported:
```python
class Foo(TypedDict):
key: Literal["A"]
blah: int
class Bar(TypedDict):
key: Literal["B"]
something: str
x: Union[Foo, Bar]
if x.key == "A":
reveal_type(x)  # Revealed type is 'Foo'
else:
reveal_type(x)  # Revealed type is 'Bar'
```
Previously, this was possible to do only with Enum Literals and the `is` operator, which is perhaps not very intuitive.
The main limitation with this pull request is that it'll perform narrowing only if either the LHS or RHS contains an explicit Literal type somewhere. If this limitation is not present, we end up breaking a decent amount of real-world code -- …
> Add support for narrowing Literals using equality

- docs/source/literal_types.rst
- docs/source/more_types.rst
This pull request is a long-overdue update of the Literal type docs. It:
1. Removes the "this is alpha" warning we have at the top.
2. Mentions Literal enums are a thing (and works in a brief example of one).
3. Adds a section about "intelligent indexing".
4. Adds a section about the "tagged union" pattern (see https://github.com/python/mypy/pull/8151). I made the example focus on the TypedDict/JSON use case -- IMO that's really the only realistically useful use case for the pattern.
5. Cross-references the "tagged union" docs with the TypedDicts docs.
I also thought about making the "Unions of TypedDict" section I added to the TypedDicts doc mention using [pydantic][0] as an alternative to the "tagged union" pattern.
I personally prefer using libraries like this which handle validation …
> Update docs for Literal types

- mypy/checker.py
- mypy/checkexpr.py
- test-data/unit/check-python38.test
> Narrow types for walrus assignment in if statements

- mypy/plugins/dataclasses.py
- test-data/unit/check-dataclasses.test
Fixes #8207 
In #8159, I fixed InitVar handling so that it looked up the superclass `__init__` and used that to determine the definition of InitVars.
That fix doesn't work in the presence of `init=False` subclasses of the initial `init=False` class. In that case, the lookup fails because the first attribute reached in MRO order on the subclass is the intermediate class, which also doesn't have the variable in its `__init__`. Then mypy didn't know about the InitVar but still tried to process it as if it did, resulting in an assertion error.
This PR fixes that issue by not adding the field to the set of known attrs until an actual definition is found.
> dataclasses: Fix deeply nested InitVar definitions with init=False

- mypy/plugins/common.py
- mypy/plugins/dataclasses.py
- test-data/unit/check-attr.test
- test-data/unit/check-dataclasses.test
Store the type of an attribute in `DataclassAttribute` so we don't
need to pull it out of `TypeInfo` in a fragile way (since the child
might try to override it in a way that breaks things). This also
allows us to get rid of some pretty dodgy code having to do with
InitVars (that could cause an incremental mode crash.)
Fixes #6809 and an unreported incremental bug
> Fix some crashes in dataclasses

- scripts/stubtest.py
This is enough to get stubtest working again, e.g., with `python3 stubtest.py zipfile`.
I'm not familiar enough with the code to know precisely why we need to disable incremental, but from tracing the code we seemed to run into issues with `mypy.Build.State.meta` – let me know if there's a better fix.
> stubtest: various fixes

- mypy/main.py
- test-data/unit/check-flags.test
- test-data/unit/fixtures/ops.pyi
Fixes #7910.
The stub changes are needed for clean output when using `--strict`.
> Include --strict-equality in --strict

- mypy/checker.py
- test-data/unit/check-expressions.test
Tuple types weren't detected as containers.
Fixes #8286.
> Strict equality: detect always false container check against tuple type

- mypy/semanal_typeddict.py
- test-data/unit/check-typeddict.test
Creating a `TypedDict` type that is similar to an existing one but has different types for one or two keys is currently impossible and requires redefining the `TypedDict` completely, which can be very verbose in the case of complex types. Throwing a type error in the same way as before, but allowing the overwrite to go through, seems much more reasonable for quality of life purposes.
I understand this PR basically amounts to a design decision about how mypy handles `TypedDict`s, but I definitely think it should be considered. The lack of ability to redefine `TypedDict` types slightly causes me lots of headache and seems like something that should be supported. Let me know if we think this is a reasonable change but we want to go about it slightly differently, I'm happy to change this.
To …
> Allow redefining TypedDict keys while still throwing an error

- docs/source/command_line.rst
resolves #8046, document the `--local-partial-types` command line option
> Add docs for --local-partial-types option

- test-requirements.txt
According to https://github.com/pytest-dev/pytest/issues/6492 pytest 5.3.2 broke some things, so we should pin for now. (see also test failures in https://github.com/python/mypy/pull/8305).
> Pin pytest

- mypy/plugin.py
- mypy/semanal_shared.py
Following #7952 and #8066, since @abstractproperty is deprecated and stubgen no longer generates code with @abstractproperty, I think it is reasonable to remove its usage in mypy's own code.
> Replace @abstractproperty usage in mypy

- mypy/build.py
Kudos to pytest for the idea.
https://github.com/pytest-dev/pytest/issues/3286#issuecomment-393142058
> Automatically write .gitignore to cache dir, ignoring everything

- mypy/semanal.py
- test-data/unit/check-basic.test
- test-data/unit/fine-grained.test
Fixes #4291
This is only a partial fix. As I'm new to the codebase, I'm unaware of the way an assignment correctly works. Thus also one of the newly added tests still fail. See the inline comment on the code change for the problem.
> Fix module alias as instance attribute

- mypy/errors.py
- test-data/unit/cmdline.test
- test-data/unit/fine-grained-blockers.test
> fixed indicator position in code with tabs

- docs/source/error_code_list2.rst
- mypy/errorcodes.py
- mypy/messages.py
Closes #8190.
This introduces a new error for `unreachable_statement`.
> Add new error code for unreachable statement

- mypy/checker.py
- mypy/messages.py
- mypy/nodes.py
- mypy/semanal.py
- test-data/unit/check-incremental.test
- test-data/unit/check-isinstance.test
- test-data/unit/check-protocols.test
- test-data/unit/check-typevar-values.test
- test-data/unit/deps.test
- test-data/unit/fine-grained.test
- test-data/unit/pythoneval.test
This diff makes `isinstance(...)` and `issubclass(...)` try generating ad-hoc intersections of Instances when possible.
For example, we previously concluded the if-branch is unreachable in the following program. This PR makes mypy infer an ad-hoc intersection instead.
class A: pass
class B: pass
x: A
if isinstance(x, B):
reveal_type(x)  # N: Revealed type is 'test.<subclass of "A" and "B">'
If you try doing an `isinstance(...)` that legitimately is impossible due to conflicting method signatures or MRO issues, we continue to declare the branch unreachable. Passing in the `--warn-unreachable` flag will now also report an error about this:
x: str
if isinstance(x, bytes):
reveal_type(x)  # E: Statement is unreachable
This error message has the same limitations as the other …
> Make isinstance/issubclass generate ad-hoc intersections

- mypy/plugins/common.py
* move `mypy.plugins.common.add_method()` to `SemanticAnalyzerPluginInterface` and to `SemanticAnalyzer`
* change old implementation to call new one, to preserve backwards compatibility
* replace first `ctx` parameter with `cls: ClassDef`
Fixes https://github.com/python/mypy/issues/8244
> add add_method_to_class() function for plugins.common

- mypy/semanal_main.py
- mypy/server/astmerge.py
- mypy/server/mergecheck.py
- mypy/server/objgraph.py
- mypy/traverser.py
- test-data/unit/deps-classes.test
- test-data/unit/deps-types.test
This fixes some stuff in the mergechecker that breaks with current
mypy's and also some bugs that the mergechecker caught. The entire
fine-grained test suite now passes with the merge checker on, which I
don't think has ever been true before.
This means that we could turn it on by default, but it doubles the
runtime of the fine-grained tests (from 90s CPU time to 180s CPU time
on my laptop), so I've left it off for now.
The motivation here is that I knew intersect_callable's creation of
types during typechecking used to run afoul of the consistency checker
and so I was nervous that #8305 would cause more problems by adding
more logic of that kind. It no longer does, probably as a result of
the semantic analyzer rewrite, so I think we are in the clear on that.
> Make the fine-grained mergechecker work again

- mypyc/test-data/run.test
The stuff with gc that it was doing is fragile and it was breaking on
windows with github actions (see #8292) even with all the compiled
code removed.
> Delete testDictFree because it is too fragile

- .github/workflows/test.yml
- tox.ini
> Add GitHub Actions for testing windows

- .travis.yml
Whenever I want to submit something, I find myself needing to temporarily comment out the .travis.yml `if` condition, commit to get CI tests done and pass in my private fork and Travis, then rebase to remove that commit before I submit the PR. This should eliminate that extra annoyance.
> Allow Travis for other than python/mypy repos, e.g. contributor private

- docs/source/common_issues.rst
This is the implication of #5677 where the return type of `__init__` is inferred given that at least one argument is typed.
However, if no argument is present in `__init__`, `-> None` becomes compulsory if we are to enable type-checking on that method without using `--check-untyped-defs` flag. I believe it is worth mentioning in the section of "No errors reported for obviously wrong code".
> Update common issues to include __init__ without arguments

- docs/source/class_basics.rst
- docs/source/final_attrs.rst
- mypy/semanal_classprop.py
- test-data/unit/check-classes.test
> Report an error if final class has abstract attributes

- mypy/join.py
- mypy/test/testtypes.py
- test-data/unit/check-tuples.test
For example:
* `Tuple[int] + Tuple[bool, ...]` becomes `Tuple[int, ...]`
* `List[int] + Tuple[bool, ...]` becomes `Sequence[int]`
This solves the other part of issue #4975 (along with PR #8333) and also issue #8074. Previously Mypy simply punted and returned `object`.
> Fix joining of Sequence (e.g. variadic tuple) and fixed-length tuple

- docs/source/cheat_sheet.rst
- docs/source/cheat_sheet_py3.rst
- docs/source/generics.rst
As mentioned in https://github.com/python/mypy/issues/3157#issuecomment-578532179 I found the documentation for decorator usage to be lacking:
* Previously only bare decorators were explained, but decorator
factories are also fairly common in the real world.
* Also added decorator examples to cheat sheet page.
* Explained difference in behavior for class decorators.
* Shortened (IMO) excessive example for bare decorators.
> Improve decorators documentation (add decorator factories)

- mypy/join.py
- mypy/test/testtypes.py
- test-data/unit/check-tuples.test
For example: `Tuple[bool, int] + Tuple[bool]` becomes `Tuple[int, ...]`
Previously Mypy simply punted and returned `object`.
This solves part of #4975. The other missing handling of fixed tuple + variadic tuple will be implemented separately, if this PR goes well. :)
> Fix joining of fixed-length tuples with mismatching lengths

- docs/source/command_line.rst
> Fixes python syntax in `--local-partial-types` example

- mypy/api.py
When the main run API was made threadsafe this broke output capturing
from run_dmypy. I don't really care about the threadsafety of
run_dmypy but I do care about output capture ever working, so I am
restoring the old sys.stdout swapping behavior for run_dmypy. I'd take
a patch to thread stdout through the client if anybody really cares.
> Make mypy.api.run_dmypy actually capture the output

- scripts/stubtest.py
Hello,
I recently embarked on a rewrite of stubtest with the goal of improving our testing of typeshed. For some more context, please refer to https://github.com/python/typeshed/issues/754 That issue also links examples of output and of typeshed issues this has detected.
Some notes about what this change contains:
- Previously stubtest.py used dumpmodule.py to generate a JSON representation of runtime objects. This abandons that approach in favour of directly using runtime objects, allowing us easier and more dynamic introspection.
- Much of stubtest.py was unimplemented, most notably, examining functions. This provides new and fairly detailed implementations of verify_funcitem, verify_overloadedfuncdef, verify_var, etc.
- In particular, we can now do everything (and more!) @JukkaL …
> stubtest: rewrite

- mypy/dmypy/client.py
This prevents control characters being interpreted, though it does
uglify the output in its own way.
> Use repr to format out/err in dmypy verbose stats output

- mypy/typeanal.py
This is to handle PEP 593 support recently merged into CPython[1].
I'm wondering what to do with this test-wise, as `https://github.com/python/mypy/blob/39d6bde2ec7063bd2cec42cce9295479e744bcc7/test-data/unit/check-annotated.test` is full of imports from `typing_extensions` and ideally, when running mypy tests on CPython nightly, tests would also import `Annotated` from `typing`. But maybe it's not worth it right now.
[1] https://github.com/python/cpython/pull/18260
> Support typing.Annotated on top of typing_extensions.Annotated

- mypy/checker.py
- test-data/unit/check-incremental.test
- test-data/unit/check-isinstance.test
- test-data/unit/check-protocols.test
Ad-hoc intersection was generating type names with dots in them, which
are interpreted as module separators. I fixed this by making the names
worse and just using the bare name of the class.
There are other options that could be pursued:
* Replacing "." with some other character and then either switching it
back when displayed or just printing it. One option that I was very
tempted by was to use U+2024 ONE DOT LEADER.
* Compute the intersection names on the fly when formatting.
I decided to do the most obvious and the least tricky thing because
this isn't important.
> Fix an incremental crash bug caused by ad-hoc intersection

- mypy/test/testtypes.py
- mypy/types.py
- test-data/unit/check-narrowing.test
This means types like `Union[Literal[False], str]` can be narrowed down more easily.
One test had to be adjusted, because it started checking more aggressively whether a union could be simplified. I think that's ok, because it's doing the equivalent of simplifying `Union[Literal["foo"], str]` to `str`, which seems correct.
> Support determining whether a literal is truthy

- mypy/join.py
- test-data/unit/check-inference.test
There was one case where type promotion wasn't considered.
Fixes #8394.
> Fix join between subclass of 'unicode' and 'str'

- runtests.py
The tests are slow (around 56s sequentially on my laptop) and not very
likely to break changes not touching stubtest, so it seems reasonable
to make them opt-in outside of CI.
> Don't run stubgen tests by default in runtests.py

- mypy/checker.py
- mypy/errors.py
- mypy/semanal.py
- mypy/semanal_main.py
- mypy/util.py
This way we can call it in contexts that don't have access to
an `Errors` instance.
> Refactor: move is_typeshed_file() to mypy.util

- mypyc/genops.py
- mypyc/nonlocalcontrol.py
This is the first PR in my quest to tidy up `mypyc.genops`.
My goal is to eventually break it up into files no longer than 1500 lines
each, and with a clean dependency structure. In the initial stages there
will be many cyclic dependencies, but I plan to fix those later on.
> [mypyc] Refactor: extract non-local control classes from mypyc.genops

- mypy/stubtest.py
- setup.py
Follow up from #8380 
Thanks for the fix! The cast works, but unfortunately we have one last issue: mypyc does not like the conditional definitions necessary to work around a bug in Python 3.5.2 and earlier (https://github.com/python/mypy/pull/8380/commits/8fda109d6b07a23670cc1148155e4696d94654e0). Example stacktrace here: https://travis-ci.org/hauntsaninja/mypy/jobs/651008763
Long story short, this PR doesn't do anything, but maybe it will in the future!
> stubtest: workaround mypyc's issue with vars

- mypy/test/data.py
I can't use `# type: ignore[override]` because we use `--warn-unused-ignores`, so I just added the unused argument in a method to match superclass signature.
Also "declared" a small bunch of attributes on `DataDrivenTestCase` (currently subclasses `Any` so missing attributes are not reported).
> Fix errors in self-check related to pytest

- mypy/build.py
- mypy/test/testpythoneval.py
- test-data/unit/pythoneval.test
Special cases a small set of modules so that they must be defined in
typeshed, as otherwise it's likely that mypy can crash, as it assumes
that various things are defined in very specific ways in these modules.
Fixes #1876.
> Don't crash if module shadows special library module such as "typing"

- mypy/checker.py
- mypy/checkmember.py
- test-data/unit/check-custom-plugin.test
- test-data/unit/plugins/descriptor.py
When `__get__` and `__set__` were implicitly called they were analyzed without taking the type of the descriptor into account. That meant that they were only visible to plugins as function calls with unclear
names.
> Analyze descriptor methods as if they're methods, not functions

- mypyc/genfunc.py
- mypyc/genops.py
- mypyc/genops_for.py
- mypyc/genopscontext.py
- mypyc/ir_builder.py
- mypyc/nonlocalcontrol.py
- mypyc/ops.py
Instead we make IRBuilder do all of its building through a
LowLevelIRBuilder. A new LowLevelIRBuilder is created for each
function that is compiled (which lets LowLevelIRBuilder lose its stack
of block lists and environments and only has one of each).
A collection of the most commonly used methods in LowLevelIRBuilder
are given passthrough methods in IRBuilder for convenience.
> Make IRBuilder not inherit from LowLevelIRBuilder.

- mypyc/genfunc.py
- mypyc/genops.py
- mypyc/genstatement.py
This makes `mypyc.genfunc` depend on `mypyc.genstatement` which is a
little unfortunate.  One way to (partially) fix this would be by
extracting try statement related code from `mypyc.genstatement`.
It doesn't seem urgent, though.
> [mypyc] Refactor: extract IR generation for statements from genops

- mypyc/emitmodule.py
- mypyc/genclass.py
- mypyc/genexpr.py
- mypyc/genfunc.py
- mypyc/genops.py
- mypyc/genopsmain.py
- mypyc/genopsvisitor.py
- mypyc/genstatement.py
- mypyc/test/test_emitfunc.py
- mypyc/test/testutil.py
Add a simple visitor module that doesn't contain any implementation and just
dispatches to various transform implementations. The main benefit is that
the implementations don't need to depend on the visitor (and thus also don't
need to depend on the other implementations) and that `IRBuilder` doesn't
need to depend on the implementations.
Also extract the driver function to another module, as this would otherwise
cause an import cycle.
Some cyclic dependencies remain and wouldn't be hard to get rid of. I
wanted to keep this PR relatively simple so I didn't fix them yet.
> [mypyc] Refactor: remove cyclic deps by extracting genops visitor

- mypyc/genops.py
- mypyc/specialize.py
This also gets rid of a cyclic import.
> [mypyc] Refactor: extract builtin function specializers from genops

- mypyc/genfunc.py
- mypyc/genopsvisitor.py
- mypyc/genstatement.py
Also experiment with formatting long import statements with one name per
line.
> [mypyc] Refactor methods into top-level functions in mypyc.genstatement

- mypy/checkexpr.py
- mypy/typeops.py
- test-data/unit/check-classes.test
In particular:
- The test case mentioned in the code passes without it
- The test case changed seems to have more desirable behaviour now,
consider:
```
from typing import Any
"""
class C:
def __radd__(self, other) -> float:
return 1.234
"""
C: Any
class D(C):
pass
reveal_type("str" + D())
```
> mypy: remove has_member

- mypy/fixup.py
- mypy/nodes.py
- mypy/semanal.py
- test-data/unit/check-incremental.test
- test-data/unit/fine-grained.test
This fixes some crash bugs involving import * from an import cycle.
> Properly track module_hidden and module_public for incomplete symbols

- mypy/checker.py
- test-data/unit/check-python38.test
It is a pretty simple matter of pulling out the assignment target from
the walrus. We don't bother handling things like `x := (y := z)` since
I can't imagine they are common enough to be worth bothering but we
could in the future if anyone cares.
Fixes #8447.
> Support narrowing of walrus in most cases

- mypy/checkexpr.py
- mypy/server/deps.py
- test-data/unit/fine-grained.test
Also fix the inferred type of a callee when we use `__call__`.
Previously we stored the callable type inferred from `__call__`,
which is incorrect.
Fixes #8489.
> Fix fine-grained dependency to "__call__"

- mypy/checkexpr.py
- mypy/typeops.py
- test-data/unit/check-classes.test
It turns out that the has_member check is an important (accidental?)
performance optimization. Removing this caused a major (30+%?)
slowdown at dropbox. There might be a better way to optimize this but
I'm just going to revert it for now at least.
This reverts commit 09cdab4ffd34f89cc02f512fc35fdef57cb4c267.
> Revert "mypy: remove has_member (#8438)"

- mypy/config_parser.py
Expands on the goal of #7273 
Exactly what the title says. The docs say this:
> Some flags support user home directory and environment variable expansion. To refer to the user home directory, use ~ at the beginning of the path. To expand environment variables use $VARNAME or ${VARNAME}.
This would add `quickstart_file` and `junit_xml` to the flags that support environment variable expansion. 
The only downside I see here is if someone decides they want their JUnit XML ouput file or quickstart file something weird like `$file`
> Support environment variable interpolation for junit_xml + quickstart_file config keys

- mypyc/irbuild/builder.py
- mypyc/irbuild/callable_class.py
- mypyc/irbuild/env_class.py
- mypyc/irbuild/function.py
- mypyc/irbuild/generator.py
This extracts these things to new modules:
* Code related to generator functions (not all of it, since some was hard to extract)
* Code related to callable classes
* Code related to environment classes
> [mypyc] Refactor: extract code from mypyc.irbuild.function

- mypy/stubtest.py
- mypy/test/teststubtest.py
- refine verify_signature, fixing a false negative and improving documentation
- ignore "this", another annoying module
- support using regexes in whitelist
- add --ignore-unused-whitelist
- handle name mangling
> stubtest: various improvements

- mypyc/irbuild/builder.py
- mypyc/irbuild/expression.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/main.py
- mypyc/irbuild/specialize.py
- mypyc/irbuild/statement.py
- mypyc/irbuild/visitor.py
Extract methods that seemed out of place in `IRBuilder`, including file and
import handling, and for loop and comprehension helpers.
This also removes a cyclic import.
Closes mypyc/mypyc#714.
> [mypyc] Refactor: extract code from IRBuilder

- mypyc/ir/class_ir.py
- mypyc/ir/func_ir.py
- mypyc/ir/ops.py
- mypyc/ir/rtypes.py
Added lots of docstrings and comments, and also added detail to existing
documentation.
Also did some minor refactoring (just moving things around).
> [mypyc] Improve docstrings and comments in mypyc.ir

- docs/source/command_line.rst
- docs/source/config_file.rst
- mypy/defaults.py
PR is a fix for #8510.
I would like to add a test that makes sure `.mypy.ini` is properly detected, though I could not find a nice place to put a test for this. Open for ideas!
> PR for #8510 "[Feature-Request] Allow mypy.ini to be a dot file"

- mypy/build.py
- mypy/test/testcheck.py
- test-data/unit/check-incremental.test
Creating the metastore does not actually create the dir, it happens on demand.
> Fix adding catch-all .gitignore

- mypyc/irbuild/callable_class.py
- mypyc/irbuild/classdef.py
- mypyc/irbuild/context.py
- mypyc/irbuild/env_class.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/function.py
- mypyc/irbuild/generator.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/main.py
- mypyc/irbuild/mapper.py
- mypyc/irbuild/nonlocalcontrol.py
- mypyc/irbuild/prebuildvisitor.py
- mypyc/irbuild/prepare.py
- mypyc/irbuild/statement.py
- mypyc/irbuild/util.py
- mypyc/irbuild/vtable.py
Add and update docstrings and comments in `mypyc.irbuild`. Also try to
make the style of docstrings and comments more consistent and cleaner
looking. For example, generally make documentation lines shorter than
the max line length, for improved readability.
Group some related functions close to each other.
> [mypyc] Irbuild docstring and comment updates, and minor refactoring

- mypy/checkexpr.py
- test-data/unit/check-warnings.test
I think that 'cast(Any, o)' should not be treated as a redundant_cast even if o is Any. 
We are using mypy with ignore_missing_imports, warn_redundant_casts, warn_unused_ignores and disallow_untyped_calls.
 
The reason I suggest this is related to "type hints for third party library." In some environments, the library has partial type annotations, and not in the others.
This causes
> import torch
> torch.load(model)
may invoke 'Call to untyped function "load" in typed context' if torch is not fully typed.
On the other hand, 
> import torch
> cast(Any, torch).load(model)
may invoke 'redundant cast to Any' in some cases.
The workaround would be the code below.
> import torch
> torch_: Any = torch
> torch_.load(model)
This is OK, but this requires an extra line.
So, what I found here is that …
> Always allow to cast to Any without warnings.

- mypy/semanal_namedtuple.py
- test-data/unit/check-namedtuple.test
- test-data/unit/fine-grained.test
Fixes #8511.
This is a workaround of #4987, where UnboundTypes can leak.
> Fix invalid type causing namedtuple errors in wrong files

- README.md
**What is this PR about ?**
In `CONTRIBUTING.md` , in the section `Quick start for contributing to mypy` it is specified that you may have to use **sudo** when installing mypy.
Use `sudo` with `pip` can be a dangerous and a security risk, I have added a `NOTE` which adds the `--user` flag when running the command, as this flag works for me.
**Things I've Changed**
1. Added a `NOTE` in README.md 
**Tests** 
I've run tests using `tox`, and tests for py3.6 had succeeded, which is the python version installed on my machine
> Added note to warn user about using sudo

- .travis.yml
I've noticed mypy failing for some of my projects on Python 3.9 (dev), and it looks like this is not currently being tested for that configuration yet.
> Add Python 3.9 (dev) to test, but allow it to fail.

- mypyc/irbuild/builder.py
- mypyc/irbuild/classdef.py
- mypyc/irbuild/expression.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/function.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/statement.py
- mypyc/primitives/generic_ops.py
- mypyc/primitives/misc_ops.py
These are all simple, operate on arbitrary objects, and roughly follow the same 
implementation pattern, so it makes sense to have them in one place. There a 
few other ops that could arguably live here, but this seems like a good enough 
selection for now. We can tweak individual ops later if we feel like it.
> [mypyc] Refactor: move fallback primitive ops to a new module

- mypy/checkexpr.py
- test-data/unit/check-inference.test
The issue was caused some special casing that no longer seems required.
Fixes #6619.
> Fix type inference with lambda that returns None

- mypy/dmypy_server.py
- mypy/modulefinder.py
- mypy/server/update.py
- mypy/test/testcheck.py
- test-data/unit/fine-grained-follow-imports.test
Included fixes:
- filter out bogus suppressed modules to speed things up
- fix issue with import inside function
- fix stub packages
- also support `/` path separators on Windows
- update search path based on paths given on the command line
- support changes to files passed on the command line
- add logging
- minimal namespace package support
Namespace package support is not complete, but the issue I found isn't
specific to following imports in mypy daemon, so I didn't try to fix it
in this PR. I'll create a follow-up issue.
> Various fixes to following imports in mypy daemon

- mypy/build.py
- mypy/server/update.py
- test-data/unit/check-incremental.test
We found a bug internally caused by deleting an indirect dependency
with --follow-imports=skip and --warn-unused-ignores. This is caused
by the indirect dependency being moved from deps to suppressed by
fix_suppressed_dependencies, which loses the knowledge that it is an
indirect dependency, causing verify_dependencies to take it much more
seriously than it should be.
fix_suppressed_dependencies was added as a hotfix for an incremental
bug discovered internally in 2016 that we never found a test case
for. I hypothesized during an earlier refactor that it had been made
redundant. Since fix_suppressed_dependencies is causing trouble now,
let's put that hypothesis to the test and remove it. If this causes a
regression, then maybe we'll be able to finally extract the test case
we want.
> Fix bug by removing fix_suppressed_dependencies

- mypy/checkexpr.py
- test-data/unit/check-expressions.test
This allows function calls in the if/else branch of a conditional expression to have a return type of `None` if the conditional expression is used as an expression statement.
Fixes #8602.
> Pass allow_none_return from conditional expression to if/else subexpressions.

- mypy/dmypy_server.py
- mypy/server/update.py
- test-data/unit/fine-grained-follow-imports.test
This includes a bunch of changes to following imports:
* Fix bug with cached modules without ASTs by loading the AST as needed
* Improve docstrings and simplify code
* Rename `follow_imports`
* Merge `seen` and `sources_set`
* Address some TODO items
This may be easier to review by looking at individual commits.
I think that following imports is ready to be enabled after this has been
merged. We can always revert the change before the next release if we
we encounter major issues.
Major things I know about that still don't work (I'll try to address at least the 
first one before the next release):
* `-m` and `-p` don't work correctly with dmypy (I think that happens also
in other modes, but might be worse when following imports)
* Suppressed modules are incorrect with namespace modules …
> More improvements to following imports in mypy daemon

- docs/source/running_mypy.rst
The examples for ignoring missing imports for a specific
library are currently conflicting between:
https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-type-hints-for-third-party-library
and
https://mypy.readthedocs.io/en/stable/existing_code.html#start-small
The former uses the syntax ``[mypy-library]``.
while the latter uses the syntax ``[mypy-library.*]``.
It's the latter that captures the goal of what 99% of users are trying
to do, which is to ignore a package.
This is made clearer with a concrete example using the Ansible
package, broken into stages.
In stage 1 we have:
$ cat foo.py
import ansible
import ansible.constants
$ cat mypy.ini
[mypy]
warn_unreachable = True
[mypy-ansible]
ignore_missing_imports = True
This mirrors the current ``[mypy-foobar]``.
In this case mypy …
> Docs: use asterisk notation when ignoring library

- mypy/config_parser.py
- test-data/unit/check-flags.test
Note that setting strict = False does not invert any of the options touched by strict; instead it is the same as if strict was not set at all.
Tested only to the extent of running the tests.
Closes https://github.com/python/mypy/issues/8633
> Make strict in config a boolean

- mypy/checker.py
- mypy/messages.py
- test-data/unit/check-unions.test
Implementation of #6406. 
Tests are failing, but /i believe the fix isn't too far from the implementation I have so far.
I would really appreciate suggestions on a different way of checking the type of a string so that errors do not occur with the tests.
Thanks!
> Implementation for disallowing tuple unpacking of strings

- mypy/dmypy_server.py
We already have a bunch of tests that use this. Now enable it on the
command line so that it's possible to start using this for real and to
do interactive testing.
Closes #5870.
> Enable following imports in dmypy (--follow-imports=normal)

- mypy/build.py
- test-data/unit/cmdline.test
> Fix crash when the same file is processed under multiple names

- mypyc/doc/dev-intro.md
This adds more content and fixes some out-of-date things. Among other
things, this explains how mypyc is different from CPython, gives a few
useful resources for background information, and adds an overview of
the mypyc IR.
Also add a list of some important bits that are still missing.
> [mypyc] Add more content to introduction for mypyc contributors

- mypyc/irbuild/for_helpers.py
- mypyc/test-data/run.test
Don't modify the range start variable in a loop like this:
```
def f() -> None:
n = 0
for x in range(n, 5):
pass
print(n)  # Should be 0, not 5
```
> [mypyc] Fix for loop over range mutating start variable

- docs/source/command_line.rst
- docs/source/common_issues.rst
- docs/source/extending_mypy.rst
- docs/source/final_attrs.rst
Some minor fixes for the Sphinx documentation:
- two simple typos
- unintended word repetition/copy-paste error
- invalid markup (`:py:meth:` nested inside bold markup)
> Minor documentation fixes

- mypy/fastparse.py
- mypy/test/helpers.py
- mypyc/test-data/run.test
The structure of the AST for subscripts was changed in
https://github.com/python/cpython/pull/9605
Fixes #8627
Also fix the majority of the errors produced when running pytest with Python 3.9, but not all.
> Fix parser when using Python 3.9

- mypy/semanal.py
- test-data/unit/check-typeddict.test
Previously only {} was accepted for an empty TypedDict, which was
inconsistent.
> Accept dict() in TypedDict context

- mypy/fastparse.py
- test-data/unit/parse.test
Helps with Python 3.9 test failures
> fastparse: add line and column information for extended slices

- mypyc/test/test_run.py
I added it recently before I discovered `--mypyc-showc`.
> [mypyc] Remove unneeded debug constant

- mypy/checkexpr.py
- mypy/join.py
- mypy/messages.py
- test-data/unit/check-generics.test
- test-data/unit/check-literal.test
Fixes https://github.com/python/mypy/issues/5354
This PR allows using type aliases in runtime context and instead gives the an `object` type (which is the best type that we know). The new error messages are less specific, but the old logic caused annoying false positives for various ORMs that use non-annotation syntax, and for runtime type validation tools.
While working on this I found a minor bug in `object_or_any_from_type()` that returned `Any` for `Union[int, Any]` while it should be `object`.
> Allow type aliases in runtime context

- mypy/semanal.py
- test-data/unit/check-async-await.test
If a nested function definition was processed multiple times due to deferring, its return type would be transformed from `T` to `Coroutine[Any, Any, T]` each time. The flag `SemanticAnalyzer.deferred` was checked to prevent this double processing, but it's reset (to false) when the analyzer is restarted, so is not reliably usable here.
Fix by tracking which function definitions have had their return type wrapped, in the mapping `SemanticAnalyzer.wrapped_coro_return_types`.
Fixes #7736
> Fix coroutine return type handling after deferring

- mypy/server/update.py
We hit a bug internally involving this. I'm going to put a bit more
effort into tracking those in case they are more general, but in
general, nothing good can come of it, I think.
> [daemon] Don't do updates of builtins modules

- mypy/checkexpr.py
- test-data/unit/check-typeddict.test
- test-data/unit/fixtures/dict.pyi
This generates two error messages, which is a bit unfortunate, but it
was already happening in other similar cases.
Fixes #8774.
> Reject bytes literal as a TypedDict key

- runtests.py
The slow PEP 561 test suite was renamed recently. It should not be
part of the fast suite.
> Fix "runtests.py pytest-fast"

- mypyc/irbuild/specialize.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/pythonsupport.h
- mypyc/primitives/dict_ops.py
- mypyc/test-data/fixtures/typing-full.pyi
- mypyc/test-data/run.test
This covers both view and list versions (it looks like both are used relatively often, at least in mypy). This accompanies https://github.com/python/mypy/pull/8725 to account for cases where `keys`/`values`/`items` appear in non-loop contexts.
> [mypyc] Add primitive ops for dictionary methods

- mypyc/lib-rt/CPy.h
Somehow, this only broke on 3.9's tests, but passed everywhere else.
> [mypyc] fix syntax

- setup.cfg
- test-requirements.txt
The versions are necessary because of some change involving switching from optparse to argparse.
Here are the E741 errors that would be ignored if this was merged.
```
./mypy/fastparse.py:327:39: E741 ambiguous variable name 'l'
./mypy/fastparse.py:334:35: E741 ambiguous variable name 'l'
./mypy/fastparse.py:1339:35: E741 ambiguous variable name 'l'
./mypy/fastparse.py:1399:39: E741 ambiguous variable name 'l'
./mypy/fastparse2.py:196:35: E741 ambiguous variable name 'l'
./mypy/meet.py:214:13: E741 ambiguous variable name 'l'
./mypy/meet.py:407:20: E741 ambiguous variable name 'l'
./mypy/typeanal.py:1170:13: E741 ambiguous variable name 'l'
./mypy/traverser.py:86:13: E741 ambiguous variable name 'l'
./mypy/report.py:298:46: E741 ambiguous variable name 'l'
./mypy/semanal.py:4524:38: E741 …
```
> mypy: fix ci, use a newer flake8 and flake8-pyi, ignore a new error

- mypy/plugins/attrs.py
- runtests.py
- test-data/unit/check-attr.test
- test-data/unit/fine-grained.test
This PR fixes https://github.com/python/mypy/issues/7489
```python
import inspect
from typing import Optional
import attr
@attr.s()
class Valid:
kw_only: Optional[str] = attr.ib(default=None, kw_only=True)
param: int = attr.ib()
optional: bool = attr.ib(default=False)
valid1 = Valid(1)
print(valid1)
valid2 = Valid(2, kw_only='something')
print(valid2)
invalid2 = Valid(2, 'something')
print(invalid2)
invalid3 = Valid('something')
print(invalid3)
@attr.s()
class Valid2:
param: int = attr.ib()
kw_only: Optional[str] = attr.ib(default=None, kw_only=True)
valid3 = Valid2(3)
print(valid3)
valid4 = Valid2(4, kw_only='something')
print(valid4)
try:
invalid = Valid2(4, 'something')
except TypeError:
pass
```
produces the expected output:
```
mypy my_example.py
my_example.py:18: error: Argument 2 …
```
> Allow attrs kw_only arguments at any position

- mypy/typeops.py
- test-data/unit/check-narrowing.test
Allows for narrowing `Union[str, Literal[False]]` via `is not False`.
related: https://github.com/python/mypy/pull/8368
fixes: https://github.com/python/mypy/issues/8810
> Add narrowing Union w/ bool Literal via identity check

- mypy/constraints.py
- test-data/unit/check-overloading.test
This improves a lot of cases. I'm not totally sure why we skipped the
arguments in the past.
> Look at arguments when generating constraints for an overload

- mypy/checkexpr.py
- mypy/messages.py
- test-data/unit/check-classes.test
If we want to report error messages at the use of a type, we have to
report it when processing that type, not when we run into some code
pattern that uses it, or else we can generate unignorable misplaced
error messages.
It doesn't seem worth bothering to do the refactors that this would
require so I just moved the error messages to the use-sites and
adjusted the text to be more appropriate.
Fixes #8825.
> Fix potential wrong-file error message for unsupported Types

- mypy/dmypy/client.py
There's a fun Python 3.9 only test case failure, where "Daemon started" is
output after the error message from parsing options.  I ended up needing to
bisect to figure out why this consistently breaks on Python 3.9. The issue is
caused by https://github.com/python/cpython/pull/17646/ (which fixes a
surprisingly old BPO).
> dmypy: fix test failure on py39

- mypyc/irbuild/for_helpers.py
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-statements.test
This means we generate "i < n" instead of CPyTagged_Lt or whatever.
This doesn't actually help performance on -O3 at all, since clang is
able to figure it out. It helps on -Og, though, and it saves the
compiler having to do some work.
> [mypyc] Have for ... in range() correctly generate raw comparisons

- mypy/messages.py
- test-data/unit/check-abstract.test
- test-data/unit/check-classes.test
- test-data/unit/check-columns.test
- test-data/unit/check-dynamic-typing.test
- test-data/unit/check-errorcodes.test
- test-data/unit/check-functions.test
- test-data/unit/check-generic-subtyping.test
- test-data/unit/check-multiple-inheritance.test
Added notes as suggested in the issue description after error from
incompatible arguments in subtype is raised.
> Fixes #5705

- mypy/stubtest.py
- mypy/test/teststubtest.py
If a stub was completely missing a dunder method, we wouldn't check it against the runtime. It's noisy to check all dunder methods, but checking init, new and call catches a lot of false negatives on typeshed without much noise.
> stubtest: fix false negative with dunder methods, small changes

- mypyc/analysis.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/registry.py
- mypyc/primitives/str_ops.py
- mypyc/test-data/irbuild-basic.test
relates mypyc/mypyc#709
This PR adds a new IR op `CallC` to replace some `PrimitiveOp` that simply calls a C function. To demonstrate this prototype, `str.join` primitive is now switched from `PrimitiveOp` to `CallC`, with identical generated C code:
Test driver code
```python
from typing import List
def test_str_join_helper(helper_arg: List[str]) -> str:
helper_base = "#"
return helper_base.join(helper_arg)
def main():
l = ["a", "bb", "cc"]
print(test_str_join_helper(l))
main()
```
generated C code(for the helper function, identical before/after):
```C
PyObject *CPyDef_test_str_join_helper(PyObject *cpy_r_helper_arg) {
PyObject *cpy_r_r0;
PyObject *cpy_r_helper_base;
PyObject *cpy_r_r1;
PyObject *cpy_r_r2;
CPyL0: ;
cpy_r_r0 = CPyStatic_unicode_3; /* '#' */
CPy_INCREF(cpy_r_r0); …
```
> [mypyc]Implement CallC IR

- mypyc/lib-rt/CPy.h
- mypyc/primitives/int_ops.py
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/run.test
This is partially just shameless cheesing on an example kmod used in a
blog post (http://blog.kevmod.com/2020/05/python-performance-its-not-just-the-interpreter/comment-page-1/#comment-55896),
but it is generally useful. Probably it will be more useful as part of
more general string formatting optimizations, but it is a start.
This gives a 3x speedup on the example in the blog post.
I had been hoping to just allocate a unicode string and call sprintf
into it but that turned out to be quite a bit slower than boxing the
int and calling PyObject_Str on it! So I just implemented it.
> [mypyc] Add a primitive for formatting an int as a str

- mypyc/doc/conf.py
This is for convenience to avoid bogus mypy errors.
> [mypyc] Add "# type:ignore" to doc configuration

- mypy/checkexpr.py
- mypy/errors.py
- mypy/join.py
- mypy/meet.py
- mypy/messages.py
- mypy/nodes.py
- mypy/options.py
- mypy/ordered_dict.py
- mypy/plugins/attrs.py
- mypy/semanal_typeddict.py
- mypy/type_visitor.py
- mypy/typeanal.py
- mypy/types.py
- mypyc/codegen/emit.py
- mypyc/codegen/emitclass.py
- mypyc/codegen/emitmodule.py
- mypyc/ir/class_ir.py
- mypyc/ir/ops.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/main.py
- mypyc/irbuild/mapper.py
- mypyc/test/test_emitfunc.py
- mypyc/test/test_serialization.py
OrderedDict is written in Python and maintains its own ordering on top
of the ordering the dict provides in recent Pythons. This ordering can
differ if certain methods are called, but we don't need that. Just
always use dict when it is ordered.
> Don't use OrderedDict on Python 3.6 and greater

- test-data/unit/pythoneval.test
python/typeshed#3371 causes this to produce a different error message. open()
with no arguments doesn't seem like an important use case, so testing for it
explicitly in pythoneval isn't all that useful.
> remove open() pythoneval test

- misc/apply-cache-diff.py
- misc/diff-cache.py
This can (with some infrastructure) allow for much faster distribution
of cache artifacts.
> Add scripts to misc/ for computing and applying diffs of mypy caches

- mypy/semanal_namedtuple.py
- test-data/unit/check-incremental.test
- test-data/unit/fine-grained.test
This lets us avoid inserting line numbers into the name when the
variable name and argument to NamedTuple disagree. This is good,
because the line numbers are ugly and when combined with bug #6548
causes problems when a namedtuple is reexported.
> Use variable name to determined NamedTuple class name

- mypyc/ir/ops.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/ll_builder.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/run.test
Pull out handling of of the error checks into ll_builder, and report
the right exception.
This is groundwork for fixing some potential segfaults involving
uninitialized classes.
> [mypyc] Refactor of load_final_static, make it report NameError

- mypyc/irbuild/mapper.py
- mypyc/irbuild/util.py
- mypyc/lib-rt/CPy.h
- mypyc/test-data/run-classes.test
The idea is to represent a protocol type P as Union[P, object], so
that we'll make fast calls if a class explictly inherits from the
protocol and fall back to generic ops otherwise.
> [mypyc] Basic support for protocols

- test-data/stdlib-samples/3.2/test/support.py
This test currently fails on https://github.com/python/typeshed/pull/4137 due to mypy not recognizing the existing check as meaning the block is windows-specific, so it claims that `getwindowsversion` doesn't exist.
> Change test to platform check for windows-specific type checking

- mypyc/ir/ops.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/list_ops.py
- mypyc/primitives/registry.py
- mypyc/primitives/str_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test/test_emitfunc.py
relates mypyc/mypyc#709
This PR supports top-level function ops via recently added `CallC` IR. To demonstrate the idea, it transform `to_list` op from `PrimitiveOp` to `CallC`. It also refines `CallC` with arguments coercing and support of `steals`.
> [mypyc] Support top level function ops via CallC

- docs/source/mypy_daemon.rst
Mark this as experimental, since this hasn't tested a lot yet.
> Update docs to reflect that following imports is supported in dmypy

- mypyc/irbuild/ll_builder.py
- mypyc/primitives/int_ops.py
- mypyc/primitives/registry.py
- mypyc/test-data/analysis.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test/test_emitfunc.py
related mypyc/mypyc#709, mypyc/mypyc#734
Support unary ops and provide `int_neg_op` as an example.
> Support unary op via CallC

- mypy/checkexpr.py
- mypy/errors.py
- mypy/messages.py
- test-data/unit/check-errorcodes.test
- test-data/unit/check-isinstance.test
- test-data/unit/check-unions.test
This way we also suppress the note when ignoring the error.
> Report note about binary operation on the same line as error

- mypy/main.py
Previously junit.xml was not generated for invalid package name
errors, among other things.
> Report some additional serious errors in junit.xml

- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/ir/rtypes.py
- mypyc/test/test_emitfunc.py
closes mypyc/mypyc#735
This PR introduces a `c_int_rprimitive` RType which represents a low level, plan integer(corresponds to C's `int`). It also allows `LoadInt` to select its `rtype` to generate tagged/plain integer code accordingly.
> [mypyc] Introduce low level integer type

- MANIFEST.in
Needed for the Debian package of `mypy` as we use `mypyc` during building.
> include mypyc subdirectories in the sdist

- .gitignore
While sending a PR for a documentation update I noticed an untracked ``docs/source/_build/`` folder, containing html files for the documentation. I added the same to gitignore so to avoid them getting pushed mistakenly.
> Update .gitignore to include _build/ folder from docs/source

- mypy/checkexpr.py
- test-data/unit/check-functions.test
I think it's unnecessarily strict to raise an error in case like this.
Was:
error: "foo" does not return a value
> Make reveal_type work with call expressions returning None

- mypy/checkexpr.py
- mypy/expandtype.py
- mypy/exprtotype.py
- mypy/messages.py
- mypy/semanal_shared.py
- mypy/suggestions.py
- mypy/typeanal.py
- mypy/types.py
- test-data/unit/plugins/dyn_class.py
This cuts down on memory a bit by avoiding teh separate allocation
inside lists and by allowing all empty sequences to share the empty
tuple.
> Change some sequence components in types from lists to tuples

- README.md
The main website mypy-lang.org does not support https.
> Readme: use https links

- docs/source/common_issues.rst
Documented unreachable code issues and --warn-unreachable command usage
> Fixes #8846

- mypy/fastparse.py
> fastparse: improve error reporting for f-string syntax errors

- mypyc/primitives/dict_ops.py
- mypyc/primitives/int_ops.py
- mypyc/primitives/list_ops.py
- mypyc/primitives/misc_ops.py
- mypyc/primitives/set_ops.py
- mypyc/primitives/str_ops.py
- mypyc/test-data/analysis.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-nested.test
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/irbuild-try.test
relate mypyc/mypyc#734
This PR translates `PrimitiveOp`s with `call_emit`, which can be represented by `CallC` pretty straightforwardly, to `CallC`. Mostly translating the description.
After this PR and another following PR which handles the ones whose descriptions are explicitly used in irbuild, we'll able to see what's missing for `CallC` by analyzing the remaining primitives.
> [mypyc] translate call_emit primitive ops to CallC

- mypy/build.py
- mypy/dmypy/client.py
- mypy/dmypy_util.py
- mypy/ipc.py
- mypy/main.py
- mypy/moduleinspect.py
- mypy/stubgen.py
- mypy/stubtest.py
- mypy/stubutil.py
- mypy/suggestions.py
- mypy/util.py
- mypyc/test/test_run.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
> Fix exception causes all over the codebase

- mypyc/irbuild/builder.py
- mypyc/irbuild/expression.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/dict_ops.py
- mypyc/primitives/list_ops.py
- mypyc/primitives/tuple_ops.py
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-any.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-generics.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-tuple.test
- mypyc/test-data/refcount.test
- mypyc/test/test_emitfunc.py
related mypyc/mypyc#734
Mainly translate primitive ops that use `call_emit` and with their descriptions used elsewhere. Int ops are intentionally left out because they make a lot of changes to IR tests, therefore making them in a separate PR.
> [mypyc] Translate more primitive ops to CallC

- MANIFEST.in
This includes only the MANIFEST part of https://github.com/python/mypy/pull/8963, but not the release tester itself.
> Update MANIFEST to include more files needed for testing

- mypyc/codegen/emitfunc.py
- mypyc/common.py
- mypyc/ir/ops.py
- mypyc/ir/rtypes.py
- mypyc/irbuild/ll_builder.py
- mypyc/lib-rt/CPy.h
- mypyc/primitives/dict_ops.py
- mypyc/primitives/set_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/refcount.test
- mypyc/test/test_irbuild.py
- mypyc/test/test_refcount.py
- mypyc/transform/exceptions.py
related mypyc/mypyc#734 and mypyc/mypyc#741.
Introducing `ERR_NEG_INT` error_kind and `NEG_INT_EXPR` branch variant to support checking the return value of a call is non-negative. `set.discard` is used as an example. With some modifications, this would also support `negative_int_emit`.
> [mypyc] new error_kind and branch variant to handle call_negative_bool_emit

- mypyc/analysis.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/misc_ops.py
- mypyc/primitives/registry.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-optional.test
> [mypyc] handle negative_int_emit and Truncate op

- .gitignore
Vim creates a number of temporary files but the current settings in .gitignore only ignores ```.swp``` files.
- with this change, all vim created temporary files prefixed by ```sw```  will be ignored
- examples of potential files; swn, swo, swp, etc.
> Add changes to ignore all vim temporary files

- mypyc/irbuild/ll_builder.py
- mypyc/primitives/dict_ops.py
- mypyc/primitives/registry.py
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test/test_emitfunc.py
related mypyc/mypyc#734.
Support argument reordering via adding a new field to the description. It will solve the difference in args ordering between python syntax and C calling requirement(mostly with `in` ops). It should never be used together with variable args.
> [mypyc] Support argument reordering in CallC

- mypy/messages.py
- test-data/unit/check-errorcodes.test
> Use [arg-type] code for some one-off argument type error messages

- mypy/checker.py
- test-data/unit/check-tuples.test
> fix error that tuple with star expr

- setup.py
The recent refactoring of mypyc did not add the new packages to setup.py, so mypyc installed from PyPI does not work.
cc @JukkaL
> [mypyc] Add missing packages to setup.py

- mypyc/analysis.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/ll_builder.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-tuple.test
relates mypyc/mypyc#741
This PR introduces `BinaryIntOp` to represent all low-level integer binary operations.
The block-like logic described in mypyc/mypyc#743 would be handled differently, `BinaryIntOp` would be the building block of it.
> [mypyc] Add BinaryIntOp for low-level integer operations

- mypyc/doc/dict_operations.rst
- mypyc/doc/differences_from_python.rst
- mypyc/doc/getting_started.rst
- mypyc/doc/introduction.rst
- mypyc/doc/str_operations.rst
Includes many changes (this list is not exhaustive):
* Document how to pass mypy options.
* Document some additional primitives.
* Protocols are now supported.
* General wordsmithing.
> [mypyc] Various documentation updates

- mypyc/codegen/emit.py
follows #9110's comment
Using CPython API to box int32/int64 into PyObject*
> [mypyc] Properly box int32/int64

- mypyc/doc/dev-intro.md
- mypyc/test-data/driver/driver.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/run-strings.test
- mypyc/test-data/run.test
- mypyc/test/test_run.py
- mypyc/test/testutil.py
If a test case doesn't define driver.py, use a default driver that calls
all functions named test_* in the compiled test case and reports any
exceptions as failures.
This has a few benefits over an explicit driver:
1. Writing test cases is easier, as a test (sub) case can be defined as
one logical unit.
2. It's easy to define many sub test cases per compilation unit.
By having larger test cases, tests can run faster. Each compilation
unit has significant fixed overhead.
Also point some errors to the relevant line number in the `.test` file
to make figuring out errors easier, when we have long test case
descriptions.
Document how to write these tests. Migrate a few test cases as examples.
I'll create follow-up PRs that merges various existing test cases into
larger ones. It probably won't …
> [mypyc] Add default run test driver that calls all test_* functions 

- mypyc/test-data/run-tuples.test
- mypyc/test-data/run.test
- mypyc/test/test_run.py
Also move tuple related tests to a new test file.
Work towards mypyc/mypyc#72.
> [mypyc] Migrate some tuple test cases to the new representation

- mypyc/test/test_run.py
This speeds up run tests significantly, but it might miss some checks
only performed on higher optimization levels.
On my Linux desktop, this speeds up `pytest mypyc` from about 18s to
about 12s. It should also speed up CI builds, but I haven't measured
the impact.
Let's try this out. We can always revert this back if this turns out
to cause problems.
The environment variable MYPYC_OPT_LEVEL can be used to override
the optimization level. Example:
MYPYC_OPT_LEVEL=3 pytest mypyc
Closes mypyc/mypyc#745.
> [mypyc] Use C optimization level 0 for tests by default

- mypyc/irbuild/ll_builder.py
- mypyc/primitives/int_ops.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test/test_analysis.py
- mypyc/test/test_exceptions.py
- mypyc/test/test_irbuild.py
- mypyc/test/test_refcount.py
- mypyc/test/testutil.py
relates mypyc/mypyc#750
Generate almost identical code as before https://github.com/python/mypy/commit/be01236bcdb9a9da66e68dd0d45ff0f9a604e44a
before:
```c
CPyL1: ;
cpy_r_r4 = (Py_ssize_t)cpy_r_r3 < (Py_ssize_t)cpy_r_r2;
if (cpy_r_r4) {
goto CPyL2;
} else
goto CPyL5;
```
now with this PR:
```c
CPyL1: ;
cpy_r_r4 = cpy_r_r3 < cpy_r_r2;
if (cpy_r_r4) {
goto CPyL2;
} else
goto CPyL5;
```
> [mypyc] Generates inline compare statement on short ints and fix sieve performance regression

- mypyc/irbuild/ll_builder.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-basic.test
This a bug I find during merging int logical ops.
Here's the less-than's inline function we have now:
```C
static inline bool CPyTagged_IsLt(CPyTagged left, CPyTagged right) {
if (CPyTagged_CheckShort(left) && CPyTagged_CheckShort(right)) {
return (Py_ssize_t)left < (Py_ssize_t)right;
} else {
return CPyTagged_IsLt_(left, right);
}
}
```
Different from the equal's inline function, it checks both operands. So this PR completes that support and fix the potential bug.
> [mypyc] Check both operands when int logical op is not EQ or NEQ

- mypyc/irbuild/ll_builder.py
- mypyc/primitives/int_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-int.test
- mypyc/test/test_irbuild.py
This PR implements support for swapping operands and negating result when building logical ops mentioned in https://github.com/python/mypy/pull/9148#issuecomment-658123381. To demonstrate, NEQ is merged. Since it has no IR test, I build one `irbuild-int.test`.
> [mypyc] Support swapping operands and negating result and merge int NEQ

- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-generics.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-nested.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-strip-asserts.test
- mypyc/test-data/irbuild-tuple.test
- mypyc/test-data/refcount.test
Mypyc currently represents int and short_int using a tagged representation, which requires doubling the value when emitting to  C. Since we are moving towards low-level IR, we change `LoadInt` to store the doubled value directly if the type is int/short_int, to be explicit about the tagged representation.
> [mypyc] LoadInt store doubled value if tagged integer

- mypy/dmypy_server.py
We support normal now, so we shouldn't say that only skip and error
are supported. That said, I don't think anybody uses silent (should we
delete it?), so I only hit this because of the bug in #9165.
> Fix misleading follow_imports error message in dmypy

- mypy/config_parser.py
- test-data/unit/cmdline.test
Currently we only validate the values on the commandline, which allows
bogus values to show up which will cause us to take the `else` branch
anywhere we consider follow_imports, which isn't likely to do anything
particularly correct.
> Validate `follow_imports` values in mypy.ini

- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/ir/rtypes.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/int_ops.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test/test_emitfunc.py
https://github.com/python/mypy/commit/358522e28cd58d95daf36256c46eb7ffcc55eea4 generates inline comparison between short ints, explicit conversion to signed is missing, though, causing negative cases to fail.
This PR add explicit type casts(although the name truncate here is a little bit misleading).
This PR will fix microbenchmark `int_list`.
> [mypyc] Fix signed integer comparison

- mypy/semanal_enum.py
- test-data/unit/check-enum.test
> Add keyword arguments for Functional Enum API

- mypy/dmypy/client.py
- mypy/util.py
This PR does three related cleanups (cc'ing @ilevkivskyi who seems to have implemented most of the underlying code):
---
Use `shutil.get_terminal_size()`
The [documentation](https://docs.python.org/3/library/os.html#os.get_terminal_size) for Python's `os.get_terminal_size()` says:
> `shutil.get_terminal_size()` is the high-level function which should normally be used, `os.get_terminal_size` is the low-level implementation.
`shutil.get_terminal_size()` already [takes care of various corner cases](https://github.com/python/cpython/blob/v3.8.3/Lib/shutil.py#L1298-L1341) such as:
- Providing a fallback (to 80 columns, like the current `DEFAULT_COLUMNS`)
- Returning that fallback if `os.get_terminal_size()` raises `OSError`
- Doing the same if it returns a size of 0
In addition to that:
- It …
> Clean up terminal width handling

- docs/source/final_attrs.rst
Since Python 3.8/PEP591, `Final` and `final` are official and available from `typing`.
> Remove note that Final is experimental and import from typing

- mypyc/analysis/dataflow.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/ir/rtypes.py
- mypyc/test/test_emitfunc.py
relates mypyc/mypyc#741
Introduce `LoadMem` IR to read a memory address and convert it into a designated-type value. (The address would mostly be in `py_ssize_t` for now)
Part of efforts to implement `len` primitives: `*(Py_ssize_t*)(ob + size_offset)`
> [mypyc] Introduce LoadMem

- mypy/checker.py
- test-data/unit/check-overloading.test
When `--disallow-untyped-decorators` is used, a callable-class decorator with a `overload`s on its `__call__` implementation would incorrectly issue an "Untyped decorator makes function untyped" error, even when the overloads are typed properly. This has been reported in pytest, which does this: https://github.com/pytest-dev/pytest/issues/7589.
This fixes the problem by expanding on a previous fix in this area, #5509.
> Fix untyped decorator overload error on decorator with __call__ overloads

- mypy/typeops.py
`make_simplified_union` no longer runs for 0.5 seconds every time it's called with a Union containing 270 literals of strings.
like I explained in #9169, this only fixes half of the problem and I'm not capable of fixing the other half. This function is still called 1098 times for the "reduced" example code, and IMO it should be called only once.
> Speed up make_simplified_union for Literal[string]s (issue #9169)

- mypyc/common.py
- mypyc/ir/rtypes.py
- mypyc/primitives/struct_regsitry.py
- mypyc/rt_subtype.py
- mypyc/sametype.py
- mypyc/subtype.py
- mypyc/test/test_struct.py
relates #9211 
This PR introduces `RStruct` to represent CPython structures.
`StructInfo` is used to hold information about a unique struct-like type.
This PR also introduces several functions to compute aligned offsets and size of structure types.
> [mypyc] Introduce RStruct

- mypy/stubdoc.py
In investigating a crash when running on a PyBind11 module, I noticed a mismatch in the types; `infer_prop_type_from_docstring` can clearly get None, but it has a type of plain `str`. Fix the annotation to match the expectation. Now, when rebuilding Mypy, the error goes away and this now works without crashing, and can completely generate stubs.
Here's one of the uses where None is obviously possible:
https://github.com/python/mypy/blob/d1048867ce27f607a7f48edf33a1888789b187e7/mypy/stubgenc.py#L220-L221
Fixes #7692.
Example printout when this error is seen:
```
sys.exit(main())
File "mypy/stubgen.py", line 1564, in main
File "mypy/stubgen.py", line 1457, in generate_stubs
File "mypy/stubgenc.py", line 51, in generate_stub_for_c_module
File "mypy/stubgenc.py", line 273, in …
```
> Fix type expected by stubgenc

- mypy/stubdoc.py
- mypy/stubgenc.py
- mypy/test/teststubgen.py
Close #8995
There are two things at play here.
- Read the docstring signature in the first line of C type properties;
- Read the docstring on `property.fget` if the type cannot be inferred from the property doc itself.
The solution is a bit tailored to PyBind, in particular it can read signature that do not have names like `(self: TestType) -> PropType`.
> Improve stubgenc property type detection

- mypyc/lib-rt/getargs.c
PyUnicode_AsUnicodeAndSize has been deprecated since 3.3
Python 3.9 has compiler warnings for this deprecated function, and we
compile with Werror, causing Python 3.9 builds to fail.
I've just copied over the relevant deprecation ignoring code from the
original getargs.c (including the TODO, but I can remove that)
> mypyc: ignore deprecation

- docs/source/command_line.rst
- docs/source/common_issues.rst
- docs/source/config_file.rst
- docs/source/extending_mypy.rst
- docs/source/kinds_of_types.rst
- docs/source/running_mypy.rst
- docs/source/stubgen.rst
This also includes some minor unrelated changes that I picked up while proofreading the `.rst`s that went missing in #7652 and #7859:
* added `confval` entry for the `plugins` option
* added `option` entry for `stubgen`'s `--help` flag
* added ref to stdlib's docs for `sys.version_info`, `sys.platform`, `pdb`
Signed-off-by: oleg.hoefling <oleg.hoefling@gmail.com>
> added crossrefs to config values throughout the docs

- mypy/stubgenc.py
pybind just gained support for defining the types of `Iterator`s and `Iterable`s (https://github.com/pybind/pybind11/commit/57070fb0a084e40ceab8a9f80b9e4436a48b9e53). This change makes stubgen capable of importing in generated stubs when used in a module being analysed.
> stubgen can import Iterable and Iterator from typing

- mypy/checkstrformat.py
- test-data/unit/check-errorcodes.test
- test-data/unit/check-expressions.test
> messages: clarify bytes repr errors

- mypy/checkexpr.py
- mypy/message_registry.py
- test-data/unit/check-super.test
- test-data/unit/fixtures/__new__.pyi
Fix #8353 #7580
* The same crash occur on:
```python
class A(B):
def f(self):
super(object, self).f()
```
* It's my first PR, any critic is desirable
> Fix crash when super outside of method is called

- mypy/type_visitor.py
This makes them usable by non-compiled plugins.
This fixes the user-blocking issue in #9001.
> Make TypeQuery and TypeTranslator not traits

- mypyc/codegen/emitclass.py
- mypyc/test-data/run-traits.test
This prevents a bunch of segfaults
Closes #9001. Closes #8360.  It doesn't close either of them in a
satisfactory way, though. Really they would like actual support, which
I've opened as mypyc/mypyc#754.
Related to mypyc/mypyc#655. (At some point there used to be working
dynamic checks for at least one of these cases. Not sure when that
broke.)
> Dynamically disallow instantiating traits/interpreted subclasses

- mypy/build.py
- test-data/unit/check-flags.test
Before this, per-module flags that are handled in fastparse (in
particular no_implicit_optional) were seeing the flag's global value.
Fixes #9208
> Pass module-specific Options to fastparse.parse()

- mypy/modulefinder.py
- mypy/test/testcmdline.py
- test-data/unit/cmdline.test
Fixes https://github.com/python/mypy/issues/7405
> Improve missing module error for subdirectories (#7405)

- mypy/semanal.py
- test-data/unit/check-python38.test
Fixes https://github.com/python/mypy/issues/8986
The reported issue is for list comprehensions involving assignment expressions, though I noticed that dictionary comprehensions are also impacted.
```
lst = [1, 2, 3, 4]
processed_list = [e for elt in lst if (e := elt - 1) > 1]
dct = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
processed_dict = {k: new_v for k, v in dct.items() if (new_v := v - 1) > 1
```
On the other hand, the same declarations _inside_ a function pass:
```
def calling_function() -> None:
lst = [1, 2, 3, 4]
processed_list = [e for elt in lst if (e := elt - 1) > 1]
reveal_type(processed_list)
dct = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
processed_dict = {k: new_v for k, v in dct.items() if (new_v := v - 1) > 1}
reveal_type(processed_dict)
```
This tipped me off to it being related to the …
> Fix internal error on list/dict comprehension with walrus operator in global scope

- mypy/stubtest.py
- mypy/test/teststubtest.py
- test-data/unit/plugins/decimal_to_int.py
This fixes [9193](https://github.com/python/mypy/issues/9193).
Before: You could not use plugins during the stub loading step.
Problem: If you need plugins for regular static type checking, you may need them when loading stubs for runtime type checking as well.
Solution: Add support for loading plugins from a config file. The easiest way to do this is to just load the config file and let `build` take care of it.
> Adding config file for stubtest.py

- mypyc/analysis/dataflow.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/test/test_emitfunc.py
relates mypyc/mypyc#741
This PR introduces `GetElementPtr`, which computes the address of an element in an aggregate type.
Part of efforts to support the `len` and other macro-related primitives.
> [mypyc] Introduce GetElementPtr

- mypy/test/data.py
- mypy/test/helpers.py
- mypy/test/testfinegrained.py
- mypy/test/testipc.py
- mypy/test/testparse.py
- mypy/test/testpep561.py
- mypy/test/testpythoneval.py
- mypyc/test/testutil.py
- pytest.ini
- test-requirements.txt
The pytest Node construction API has changed to prefer a `Node.from_parent` factory over the raw constructor [1].  This PR updates a few points to conform to the recommended API to avoid the `PytestDeprecationWarning` that arises when tests are being collected with pytest 6+.
[1] https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent
> Use pytest Node.from_parent if available

- mypy/treetransform.py
- test-data/unit/check-async-await.test
- test-data/unit/fixtures/typing-async.pyi
(The test only tests 'async with', but 'async for' had the same bug so I am fixing that too.)
Fixes #9261.
> When copying a ForStmt or WithStmt, copy is_async flag

- mypy/subtypes.py
We have this really nasty bug in `returns` with our `@curry` plugin:
- Closes https://github.com/python/mypy/issues/9147
- Closes https://github.com/python/mypy/issues/8978
So, this little fix solves the problem for us with very little effort.
In the ideal world, I would have to rewrite the whole thing to make the nested structures work.
Current problem is that we have a local state in `matched_overloads` and `possible_invalid_overloads` variables that is not syncronyzed with the nested calls.
I can also add a `TODO` note for later.
Refs https://github.com/dry-python/returns/issues/410
> Fixes corner case for comparing nested overloads

- mypy/checker.py
- test-data/unit/check-statements.test
Thanks to @isra17
This fixes an issue where the following code would raise no error:
```python
def test() -> None:
try:
raise Exception()
except NotImplementedError as e:
raise Exception("notimplemented") from e
except Exception:
raise Exception("test") from e
test()
```
``e`` does not exist on the second ``except`` block, so we cannot raise from it. It would result in a runtime error:
```
UnboundLocalError: local variable 'e' referenced before assignment
```
See #9270 for details.
> check for deleted vars in 'raise from' (#9270)

- mypyc/primitives/int_ops.py
This PR cleans up unused int op definitions including `unsafe_short_add` and `int_compare_op`.
`unsafe_short_add`'s usages have been replaced with low-level integer op in #9108 and `int_compare_op` has no usages since all comparison operators are now built in irbuild.
> [mypyc] Clean up unused int op definitions

- mypyc/ir/rtypes.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/specialize.py
- mypyc/primitives/dict_ops.py
- mypyc/primitives/generic_ops.py
- mypyc/primitives/set_ops.py
- mypyc/primitives/tuple_ops.py
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-tuple.test
- mypyc/test-data/refcount.test
This PR completes the support of the new style `builtins.len` for dict, set, tuple and generic cases.
> [mypyc] Implement new-style builtins.len for all supported type

- docs/source/command_line.rst
- mypy/build.py
- mypy/errorcodes.py
- mypy/errors.py
- mypy/main.py
- mypy/options.py
- test-data/unit/check-flags.test
- test-data/unit/cmdline.test
Fixes https://github.com/python/mypy/issues/8975 
Add the `--disable-error-code` flag to disable error codes globally.
Add the `--enable-error-code` flag to enable error codes globally
This is my first time working on this repo, so please let me know anything additional that needs completing.
> Add command line support to enable/disable error codes

- mypyc/analysis/dataflow.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/irbuild/expression.py
- mypyc/primitives/dict_ops.py
- mypyc/primitives/registry.py
- mypyc/test-data/irbuild-dict.test
- mypyc/test/test_emitfunc.py
This PR introduces `LoadAddress`, an op for taking the address of a given name. 
Currently, in mypyc we only need to take the address of a name when we are using the name_ref_ops, so the op takes a string(CPython name) as its argument. We can revisit the design later if we want to take the address of arbitrary name later.
> [mypyc] Implement LoadAddress

- mypyc/irbuild/classdef.py
- mypyc/primitives/int_ops.py
- mypyc/primitives/list_ops.py
- mypyc/primitives/misc_ops.py
- mypyc/primitives/registry.py
- mypyc/primitives/str_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/refcount.test
This PR replaces name_ref_op: `int`, `str`, `list`, `type`, `NotImplemented` with LoadAddress.
The only three remaining name_ref_ops are `true`, `false` and `none`, which should be built directly in irbuild
> [mypyc] Replace name_ref_op with LoadAddress

- mypyc/ir/ops.py
- mypyc/irbuild/ll_builder.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-tuple.test
- mypyc/test-data/refcount.test
- mypyc/test/test_emitfunc.py
Add optional reference to the object from which we are reading from
to `LoadMem` so that the object won't be freed before we read memory.
Fixes mypyc/mypyc#756.
> [mypyc] Don't free target of LoadMem too early

- mypyc/ir/ops.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-generics.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-nested.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-try.test
- mypyc/test-data/irbuild-tuple.test
- mypyc/test-data/refcount.test
This PR fixes `Environment.to_lines` so that continuous registers with the same type are shown on the same line.
> [mypyc] Fix to_lines to show same type registers on the same line

- mypy/join.py
- test-data/unit/check-unions.test
Previously join of `Union[int, Any]` and `Union[int, None]` could be
`Union[int, None]` (we lost the `Any` type). Fix this by replacing a
subtype check with a proper subtype check when joining unions.
> Don't simplify away Any when joining unions

- mypy/dmypy_server.py
There are situations in complex SCCs where the semantic analyzer will
infer self dependencies, which will cause an infinite loop in dmypy
--follow-imports=normal.
It's probably a bug that we do that, and that should be fixed too, but
fixing a graph algorithm to not infinite loop on self edges seems like
a reasonable thing to do in any case.
I don't have a minimized test case yet, and am submitting this without
one because it should be harmless and because I want it to get into
the release.
> Don't infinite loop on self deps in --follow-imports=normal

- mypyc/irbuild/statement.py
- mypyc/lib-rt/CPy.h
- mypyc/primitives/exc_ops.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-try.test
This PR merges keep_propagating_op and removes unused assert_err_occurred_op. To keep the design unified, we turn to C wrapper function for now.
This completes all exception-related ops.
> [mypyc] Merge keep_propagating_op and remove unused assert_err_occurred_op

- mypyc/irbuild/ll_builder.py
- mypyc/primitives/generic_ops.py
- mypyc/primitives/misc_ops.py
- mypyc/primitives/registry.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-try.test
This PR merges the generic `in` and `op` as well as misc `builtins.bool` op, and obsoletes unused old-style registry functions: `call_void_emit`, `call_and_fail_emit`, `call_negative_bool_emit`, `negative_int_emit`, `call_negative_magic_emit`.
A test for generic `in` and misc `builtins.bool` is added.
> [mypyc] Obsolete several old-style registry functions

- mypy/typeops.py
- test-data/unit/check-literal.test
This adds support for union narrowing in if statements when condition value has defined literal annotations in `__bool__` method. Value is narrowed based on the `__bool__` method return annotation and this works even if multiple instances defines the same literal value for `__bool__` method return type.
This PR also works well with https://github.com/python/mypy/pull/9288 and makes below example to work as expected:
```python
class A:
def __bool__(self) -> Literal[True]: ...
class B:
def __bool__(self) -> Literal[False]: ...
def get_thing() -> Union[A, B]: ...
if x := get_thing():
reveal_type()  # Revealed type is '__main__.A'
else:
reveal_type()  # Revealed type is '__main__.B'
```
Partially fixes https://github.com/python/mypy/issues/9220
> Add support for using __bool__ method literal value in union narrowing in if statements

- mypy/stubgenc.py
- mypy/test/teststubgen.py
pybind11 is capable of producing type signatures that use generics (for example https://github.com/pybind/pybind11/blob/4e3d9fea74ed50a042d98f68fa35a3133482289b/include/pybind11/stl.h#L140). A user may also opt to write a signature in the docstring that uses generics.
Currently when stubgen parses one of these generics, it attempts to import a part of it. For example if a docstring had `my_func(str, int) -> List[mypackage.module_being_parsed.MyClass]`, the resulting stub file tries to import `List[mypackage.module_being_parsed`.
This change fixes this behaviour by breaking the found type down into the multiple types around `[], ` characters, adding any imports from those types that are needed, and then stripping out the name of the module being parsed.
> Fixed stubgen parsing generics from C extensions

- mypyc/irbuild/expression.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/misc_ops.py
- mypyc/primitives/registry.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-nested.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-try.test
- mypyc/test/test_emitfunc.py
This PR merges `none_object_op` and `ellipsis_op`.
> [mypyc] Merge misc object ops

- mypyc/analysis/dataflow.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/callable_class.py
- mypyc/irbuild/classdef.py
- mypyc/irbuild/expression.py
- mypyc/irbuild/generator.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/generic_ops.py
- mypyc/primitives/int_ops.py
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-nested.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test/test_emitfunc.py
`BinaryIntOp` used to represent arithmetic, bitwise and comparison operations on integer operations. However, this design prevents us to compare pointer types and all comparison operations should be of boolean return type while manually specifying this in `BinaryIntOp` is both verbose and error-prone.
This PR splits `BinaryIntOp` and moves the comparison functionalities to `ComparsionOp`.
Based on the new op, this PR also implements `is` and `is not` op.
> [mypyc] Split BinaryIntOp and introduce ComparisonOp, implements is/is not op

- docs/source/running_mypy.rst
> mention py.typed in missing imports doc

- mypyc/ir/ops.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-any.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-nested.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/irbuild-try.test
- mypyc/test-data/refcount.test
`LoadGlobal` used to have this hack to print partial name to keep consistent with the old `LoadStatic` behavior, now I've decided to make it print fullname since #9316 would need to print simple names like `NULL`.
> [mypyc] Make LoadGlobal print full name during pretty IR printing

- mypyc/irbuild/ll_builder.py
- mypyc/primitives/generic_ops.py
- mypyc/primitives/registry.py
- mypyc/primitives/str_ops.py
- mypyc/test-data/irbuild-str.test
- mypyc/test/test_irbuild.py
This PR changes the `CallC` description so that a list of extra constants can be used to a call. With this added functionality, `str.split` is implemented in new style IR.
> [mypyc] Support list of extra constants and str.split op

- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/dict_ops.c
- mypyc/lib-rt/generic_ops.c
- mypyc/primitives/dict_ops.py
- mypyc/primitives/generic_ops.py
This PR merges `get` op with `None` as default value for dict, and a power op for generic numbers, which completes the support of `generic_ops.py` and `dict_ops.py`
> [mypyc] Merge dict get op and generic power op

- mypy/messages.py
- test-data/unit/check-tuples.test
- test-data/unit/check-unions.test
- test-data/unit/check-warnings.test
This PR is addressing issue https://github.com/python/mypy/issues/9358.
- We have the same question for `union` type (other than `tuple` mentioned in https://github.com/python/mypy/issues/9358, so I made the same change for `union` type (please let me know if it's not desired)
- I hesitated if it's necessary to keep intermediate var `s`. But eventually I kept it to follow the existing practice in line https://github.com/python/mypy/blob/a08bbbb2fa37b8d2784dd3b194bcb1cd111bbcac/mypy/messages.py#L1643-L1644
> Don't simplify tuple/union types in error messages

- mypy/semanal.py
- test-data/unit/check-protocols.test
> Fixes protocols with untyped slots

- mypy/subtypes.py
- test-data/unit/check-protocols.test
> Make None compatible with Hashable

- mypy/checker.py
- mypy/checkexpr.py
- mypy/literals.py
- mypy/nodes.py
- mypy/semanal.py
- mypy/strconv.py
- mypy/treetransform.py
- mypy/visitor.py
- mypyc/irbuild/visitor.py
- test-data/unit/lib-stub/typing.pyi
- test-data/unit/lib-stub/typing_extensions.pyi
- test-data/unit/semanal-errors.test
- test-data/unit/semanal-types.test
Linking #8645
Taking Jukka's suggestion from #9250 and splitting up the PR so we can merge and review a piece at a time. If you've read what's been pushed to #9250, this is the first bit of it, except I've changed mypy_extensions to typing_extensions since PEP 612 has been accepted.
> pep612: add semanal for paramspec

- mypy/main.py
This reverts commit af00d01754e8afddaf9445db703d51076ccf6fae which
introduced a workaround for an incorrect type definition in typeshed.
The type of AugmentedHelpFormatter._fill_text() got fixed in commit
python/typeshed@686e21d330ce9a2ca16fb925554fd5eba082fb8f so we can
remove the workaround.
> Restore the correct type of AugmentedHelpFormatter._fill_text()

- .travis.yml
- mypy/test/testcheck.py
- test-data/unit/check-kwargs.test
- test-data/unit/check-python39.test
Due to Python 3.9's new parser, this has a different (and better) error
message on Python 3.9.
This is effectively a test of typed_ast / ast, so I don't think it
matters too much. I'm happy to alternatively just get rid of the test
altogether, or if people feel strongly, come up with a way to run the
test when run with older Pythons.
> mypy: get CI green for py39

- docs/source/kinds_of_types.rst
This pull request improves [Class name forward reference section](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#class-name-forward-references) of the documentation by mentioning `__future__.annotations` and closes #9311
> Add __future__.annotations in forward refs section

- mypy/config_parser.py
- mypy/test/testcmdline.py
- test-data/unit/envvars.test
Fixes #7968
The variable MYPY_CONFIG_FILE_DIR is set to the absolute path of (**ADDED: the dirname of**) the config file, prior to it being parsed.  Existing environment-variable substitution should handle the rest.
Added new file `test-data/unit/envvars.test` to list of test files in `mypy/test/testcmdline.py`.
Added one testcase, using $MYPY_CONFIG_FILE_DIR  to set `files=` in mypy.ini.
> Add MYPY_CONFIG_FILE_DIR to environment when config file is read

- mypy/config_parser.py
- mypy/test/testcmdline.py
- test-data/unit/envvars.test
Let's see what it will take to make CI pass.
Resubmit of #9403.
Fixes #7968.
Co-authored-by: aghast <aghast@aghast.dev>
> Add MYPY_CONFIG_FILE_DIR to environment when config file is read (2nd try)

- test-data/unit/cmdline.test
At the moment, python/typeshed#4473 is approved but fails the mypy self tests. This updates the `cmdline.test` file to match the new error message with overloads. Though, I'm sorta wondering if it would be less fragile to just not do this specific check at all.
Feel free to take this (and the other PR) whenever it's least annoying to merge both together. Or, let me know if I'm missing something. 🙂 
cc @JelleZijlstra
> Update int_pow test to match new overloads in typeshed

- mypy/stubtest.py
- mypy/test/teststubtest.py
Allows use of the old options to preserve backwards compatibility
A step towards https://github.com/python/typeshed/issues/4436
> stubtest: use allowlist instead of whitelist

- mypy/applytype.py
- mypy/checker.py
- mypy/checkexpr.py
- mypy/checkmember.py
- mypy/expandtype.py
- mypy/fixup.py
- mypy/messages.py
- mypy/nodes.py
- mypy/plugin.py
- mypy/plugins/default.py
- mypy/semanal.py
- mypy/semanal_shared.py
- mypy/server/astmerge.py
- mypy/test/testcheck.py
- mypy/tvar_scope.py
- mypy/type_visitor.py
- mypy/typeanal.py
- mypy/typeops.py
- mypy/types.py
- test-data/unit/check-parameter-specification.test
Linking #8645
Like #9339, much of this is in #9250. However, this PR is a little less self contained, in that it causes several future TODOs.
A lot of the changes here are necessitated by changing the type of `CallableType.variables` to `Sequence[TypeVarLikeDef]`. This is nice, because it informs me where I need to make changes in the future / integrates a little bit better with existing type var stuff. But let me know if you think I should instead add another field to CallableType.
The other decision here that I'm less sure of is not adding upper_bound and variance fields to ParamSpecDef. These fields exist on ParamSpecExpr, since PEP 612 reserves that. I figured we should add these to ParamSpecDef only once they have semantics so that it's easier to figure out where we need to define …
> pep612: more semantic analysis for paramspec

- mypy/main.py
- mypy/modulefinder.py
- mypy/test/testpep561.py
- test-data/unit/pep561.test
`-p` is similar to `-m` except that it will recursively typecheck submodules.
Unfortunately the early module walk was being done with search paths that
did not benefit from site_packages for the selected python executable,
which resulted in some packages being typechecked fine with `-m`, but
rejected as `not found` by `-p`.
Fixes #9386
> Fix search paths for `-p`

- mypy/semanal.py
- test-data/unit/check-flags.test
> Inform about no explicit export instead of attribute suggestions

- mypy/find_sources.py
- test-data/unit/cmdline.test
Currently, running `mypy typedpkg-stubs` (or any sub-file contained in the directory) in a project similar to https://github.com/ethanhs/stub-package results in an error:
```
mypy ./typedpkg-stubs
typedpkg-stubs is not a valid Python package name
```
This PR allows directories prefixed with `-stubs` which also contains a valid identifier before the `-` to be type checked.
Fixes #8229
> Recognize -stubs directories as valid package directories

- mypy/plugins/enums.py
- test-data/unit/check-enum.test
- test-data/unit/lib-stub/enum.pyi
It is very common for enums to have homogenous member-value types.
In the case where we do not know what enum member we are dealing
with, we should sniff for that case and still collapse to a known
type if that assumption holds.
As a canonical example:
```py
from enum import Enum
class Color(Enum):
RED = 1
BLUE = 2
print(Color.RED.value)
reveal_type(Color.RED.value)
def print_color_value(color: Color) -> None:
reveal_type(color.value)  # mypy reveals this as "Any", but it should be "builtins.int"
print_color_value(Color.BLUE)
```
New unit tests have been added and all existing tests still pass.
> Predict enum value type for unknown member names.

- mypy/checkmember.py
- test-data/unit/check-typevar-values.test
Fixes #4351
Using TypeVar upperbound with imported type and disabled imports following was causing missing attribute error since AnyType was not considered as upperbound option.
> Consider AnyType for TypeVar upperbound to avoid missing attribute

- mypy/checkexpr.py
- test-data/unit/check-python38.test
Assignment (walrus) expressions don't currently store their target types into the checker's type map, leading to an internal error when mypy goes to infer the type of that name downstream.  This PR stores the assignment target's type explicitly.  If this is not the right approach, feel free to comment/close this.  I just wanted to push this up so there's a demo of a potential fix.
Fixes #9054 
~Still a work in progress, need to add tests.~ A test has been added that reproduces the OP's report, and this PR fixes it.
> Store the type for assignment expr targets

- mypy/subtypes.py
- test-data/unit/check-protocols.test
In particular, this affected hashables, as in #9437 
Maybe there's a more standard way of falling back the PartialType? We could also consider moving this logic into is_subtype, but I'd be hesitant to do so. I'm okay with returning False based on the fallback Instance constructed here, but not returning True.
> Fix partial type crash during protocol checking

- mypy/checkexpr.py
- test-data/unit/check-class-namedtuple.test
- test-data/unit/check-expressions.test
> checkexpr: treat typevar values as object, not Any

- mypyc/lib-rt/CPy.h
Explicitly include `stdint.h`. I'll monitor the Appveyor build to see if
this helps.
Work on #9501.
> [mypyc] Try to fix errors about int32_t on Python 3.5 and Appveyor

- mypy/stubtest.py
Ensuring nodes.NameExpr turned out to be a little too defensive
Fixes #9506
> stubtest: allow memberexpr for overloads

- mypyc/common.py
- mypyc/irbuild/expression.py
We may be building a mixed 32/64-bit binary, so restrict the maximum integer
literal to what's supported on a 32-bit platform, since the same C code
needs to compile on both 32-bit and 64-bit architectures.
This will make some slicing operations a bit slower in 32/64-bit mode
(Python 3.5 on mac only).
Work on #9500.
> [mypyc] Try to fix mypy mac build failure on Python 3.5 on Travis

- mypy/checkexpr.py
- test-data/unit/check-flags.test
> Always type check arguments when using --disallow-untyped-calls

- mypy/typeanal.py
- test-data/unit/cmdline.test
As a result of https://github.com/python/typeshed/pull/4586
> Fix runtime not generic note for type aliases, update for PathLike

- mypy/semanal.py
- mypy/test/teststubtest.py
- test-data/unit/check-modules.test
See recent discussion on typing-sig leading to a PEP 484 amendment.
> PEP 484: only reexport for X as X forms

- mypy/semanal.py
- test-data/unit/check-modules.test
> semanal: propagate module_hidden for unknown symbols

- README.md
https://github.com/ambv/flake8-mypy is dead. flake8-mypy also disables
import following, which is suboptimal. In my experience with
mypy-primer, a lot of projects using flake8-mypy have a number of type
errors.
> README.md: remove mention of flake8-mypy

- docs/source/command_line.rst
- docs/source/config_file.rst
Added the --disable-error-code cli option and disable_error_code config option to the documentation.
> Document --disable-error-code cli and config option

- .travis.yml
Fixes #9473
Typing used to be installed on python2 but was removed by [this change](https://github.com/python/mypy/commit/def2c63990dd#diff-354f30a63fb0907d4ad57269548329e3L15), I don't know why
in `mypy/util.py:try_find_python2_interpreter()` we try to find a valid python2 interpreter with typing installed.
If we don't find it, those tests are skipped.
However on [typeshed](https://github.com/python/typeshed/blob/master/tests/mypy_selftest.py#L14), the CI installs typing on python2 for mypy self test. Thus it doesn't skip the tests.
This caused the regression issue on typeshed
I ran Travis CI on my forked repo.
I based a branch on 31862816ee87afc2b7514aec76249b884a9fdbef (the one that caused a python2 regression) and was able to reproduce the failing test: …
> Travis CI: install typing on python2 to restore some skipped tests

- mypy/stubgen.py
- test-data/unit/stubgen.test
Running `stubgen` on modules that import multiple packages using aliases did not produce the correct results:
Input:
```python
import p.a as a
import p.b as b
x: a.X
y: b.Y
```
Result:
```python
import p.b as a  # <--- wrong module!
import p.b as b
x: a.X
y: b.Y
```
I added a bunch of new tests to stubgen.test.  
I had to change one of the expected results: `testConditionalImportAll_semanal`.  Previously, if more than one module import introduced the same name into the namespace, the data structures used to track imports were simply allowed to become corrupted, and the generator would produce `import FIXME as whatever`.  After correcting the internal state to fix the issue that prompted this PR, I realized it would be difficult to maintain the current output for this test, so I chose to …
> stubgen: fix package imports with aliases

- misc/download-mypyc-wheels.py
We switched the macOS version in the mypy_mypyc-wheels repository
for Python 3.6 and 3.7 wheels.
Examples of wheel names:
https://github.com/mypyc/mypy_mypyc-wheels/releases/tag/v0.790%2Bdev.7273e9ab1664b59a74d9bd1d2361bbeb9864b7ab
The motivation for the original change was to avoid building anything 
32-bit, since that's not tested and not officially supported anyway. If
this change causes problems, we should be able to switch this back,
but let's see how this goes.
> Update wheel download script to use the correct file names for macOS

- mypy/fastparse.py
I was trying to build wheels for Python 3.9 as part of #9536, but ran
into this issue. You'll notice a couple hundred lines up msullivan
points out that mypyc can't handle conditional method definition, so
that's not an option here.
```
/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpok7vxky0
mypy/fastparse.py:1260: error: "ExtSlice" has no attribute "dims"
mypy/fastparse.py:1264: error: "Index" has no attribute "value"
ERROR: Command errored out with exit status 1: /opt/_internal/cpython-3.9.0rc2/bin/python3.9 /opt/_internal/cpython-3.9.0rc2/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpok7vxky0 Check the logs for full command output.
```
> py39: fix mypyc complaint

- mypyc/lib-rt/str_ops.c
- mypyc/primitives/str_ops.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/run-strings.test
Relates to https://github.com/mypyc/mypyc/issues/644
Includes unit test
> [mypyc] optimise startswith and endswith

- mypy/fastparse.py
Necessary because I previously didn't actually fix mypyc's complaint +
mypyc has more complaints.
The sys.version_info aliasing works around us hitting
https://github.com/python/mypy/blob/08f207ef4a09f56d710d63775771ae921c41d4bc/mypyc/irbuild/expression.py#L44
> py39: fix mypyc complaints part 2

- MANIFEST.in
- setup.py
Fixes #9584 
I haven't tested myself but this package should probably be here.
> add mypyc.analysis to setup.py

- mypyc/irbuild/statement.py
- mypyc/test-data/irbuild-basic.test
relates mypyc/mypyc#729
This PR makes simple cases like `y, x = x, y` faster.
I tend to do some future improvement based on this PR(for example, supporting `ListExpr` as @JukkaL suggested), nevertheless, this PR itself should cover the most frequent use case.
> [mypyc] Make multiple assignment faster(1st stage)

- mypy/plugin.py
- mypy/semanal.py
- mypy/semanal_namedtuple.py
- test-data/unit/check-incremental.test
- test-data/unit/check-namedtuple.test
- test-data/unit/fine-grained.test
Closes #4589
This PR modifies `check_namedtuple` to return the internal name of the namedtuples (e.g. the content of the first argument of namedtuple/NamedTuple) so that the callers, especially `analyze_namedtuple_assign`, can check if the name of the variable on the l.h.s. matches with the first argument of the namedtuple.
Added a code snippet from #4589 as the new test.
Also, I deleted `testReexportNamedTupleChange` (which was added in #6698 for https://github.com/python/mypy/issues/6548#issuecomment-484277202) since we wouldn't need to worry about this case when this is merged.
> Require first argument of namedtuple to match with variable name

- mypy/type_visitor.py
Now these types can be extended from plugin code.
Previously it was impossible:
```python
from mypy.type_visitor import TypeVisitor
class KindTranslator(TypeVisitor):
...
```
Was giving:
```
TypeError: interpreted classes cannot inherit from compiled traits
```
But, this is a very powerful tool. Some complex type manipulations do require this (or similar) tool.
For example:
- https://github.com/dry-python/returns/issues/391
- https://github.com/dry-python/returns/issues/631
More context: https://github.com/python/mypy/issues/9001#issuecomment-710315985
I actually don't have any test plan at the moment. I would be very happy to receive any advice! 👍
> TypeVisitor and Co now support allow_interpreted_subclasses=True

- docs/source/command_line.rst
- docs/source/config_file.rst
> Document local_partial_types config option

- mypy/argmap.py
- mypy/checkexpr.py
- test-data/unit/check-kwargs.test
- test-data/unit/check-python38.test
- test-data/unit/check-typeddict.test
Fixes #4708
Allows for multiple ambiguous **kwarg unpacking in a call -- all ambiguous **kwargs will map to all formal args that do not have a certain actual arg.
Fixes #9395 
Defers ambiguous **kwarg mapping until all other unambiguous formal args have been mapped -- order of **kwarg unpacking no longer affects the arg map.
Additional tests included in PR, no existing tests were changed. Below are new tests that would exhibit different behaviors if they're run without code changes in the PR:
---
```python
[case testPassingMultipleKeywordVarArgs]
from typing import Any, Dict
def f1(a: 'A', b: 'A') -> None: pass
def f2(a: 'A') -> None: pass
def f3(a: 'A', **kwargs: 'A') -> None: pass
def f4(**kwargs: 'A') -> None: pass
d = None # type: Dict[Any, Any]
d2 = None # type: Dict[Any, Any] …
```
> Improve ambiguous **kwarg checking

- mypy/checkexpr.py
- test-data/unit/check-unreachable-code.test
This paragraph explains the limitation with TypeVars:
https://github.com/python/mypy/blob/eb50379defc13cea9a8cbbdc0254a578ef6c415e/mypy/checker.py#L967-#L974
We currently have no way of checking for all the type expansions,
and it's causing one part of the issue https://github.com/python/mypy/issues/9456
Using `self.chk.should_report_unreachable_issues()` honors the suppression of
the unreachable warning for TypeVar with value restrictions
I added a test statement that reproduces the unreachable false positive.
I added another test statement that is currently a false negative for the moment, because of the suppression for TypeVar type expansions.
> disable unreachable warnings in boolean ops on TypeVars with value restriction

- setup.py
Is there a reason to not do this? It gets the right set of packages when
I run it. Saves chores like #9587 or #9061
> setup.py: use find_packages

- mypy/build.py
closes #9058 
I updated both `seen_files` and `newst` to use an absolute path to fix the problem.
> Use absolute path when checking source duplication error

- mypy/checkexpr.py
- mypy/plugin.py
- test-data/unit/check-custom-plugin.test
- test-data/unit/plugins/function_sig_hook.py
This PR introduces `get_function_signature_hook` that behaves the similar way as `get_method_signature_hook`.
Closes #9101
> Adds get_function_signature_hook

- mypyc/irbuild/builder.py
- mypyc/irbuild/ll_builder.py
- mypyc/test-data/analysis.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/irbuild-int.test
- mypyc/test-data/irbuild-nested.test
- mypyc/test-data/irbuild-optional.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/refcount.test
In a conditional context, such as in an if condition, simplify the 
IR for tagged integer comparisons. Also perform some additional 
optimizations if an operand is known to be a short integer. 
This slightly improves performance when compiling with no 
optimizations. The impact should be pretty negligible otherwise.
This is a bit simple-minded, and some further optimizations are 
possible. For example, `3 < x < 6` could be made faster. This 
covers the most common cases, however.
Closes mypyc/mypyc#758.
> [mypyc] Simplify IR for tagged integer comparisons

- mypy/build.py
- mypy/test/testcheck.py
- test-data/unit/check-incremental.test
This helps to prevent bloating backups with caches.
See https://bford.info/cachedir/ for more information about the
specification – it's supported by Borg, restic, GNU Tar and other
solutions.
> Exclude cache directories from backups using CACHEDIR.TAG

- docs/source/faq.rst
I experienced a wild goose chase while experimenting with PyPy. 
It boiled down to typed_ast not compiling with PyPy. 
I hope others will find this information more quickly now.
> Update FAQ to include MyPy not working on PyPy

- mypy/util.py
Including ANSI escape sequence for gray color that is visible in both light and dark schemed terminal. The idea is to elimate the dim color attribute and replace it with gray color that is good for both light and dark scheme terminal to make the output  much more predictable. Below screenshots show how these changes improves the error view.
- Before on dark theme using dim capname
- After on dark theme using gray color
- Before on light theme using dim capname
- After on light theme gray color
> Add gray color ANSI escape sequence 

- mypy/stubutil.py
- mypy/test/teststubgen.py
> Stubgen: normalize input paths when finding common parent directory for out files

- mypy/checkexpr.py
Typechecking of dict, set, and list literals currently
goes through typechecking of the generic dict/set/list
constructor internally. This is usually fine but becomes
horrendously slow when the number of items is large:
- for generic methods, `infer_arg_types_in_context` is
called twice
- `infer_arg_types_in_context` is O(n**2) where `n` is
the number of arguments, which, in the case of a
literal, is the number of items.
Add an `O(n)` fast path for deriving the type of simple
container literal expressions. This fast path only handle
a subset of cases but it provides a tremendous speedup for
the relatively common case of large literal constants.
The real-world example that motivated this change is a
1889 lines long dict constant representing the parsed value
of a mock JSON response from a …
> Speed up typechecking of dict, set and list expressions

- mypy/nodes.py
- mypy/semanal.py
In 3.7.2 [typing.OrderedDict](https://docs.python.org/3/library/typing.html#typing.OrderedDict) was added to the typing module. Beforehand the correct way to annotate an `OrderedDict` was as a string or using the `__future__` import. However since it has been added to the stdlib it has not been added to the *type_aliases* for mypy [as it should have](https://github.com/python/mypy/pull/7707#issuecomment-541774957).
```python
from typing import OrderedDict
d: OrderedDict[str, int] = OrderedDict()
```
```console
$ mypy test.py
test.py:3: error: Variable "typing.OrderedDict" is not valid as a type
test.py:3: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
test.py:3: error: "_Alias" not callable
Found 2 errors in 1 file (checked 1 source file)
``` …
> Add typing.OrderedDict to type_aliases

- mypy/stubtest.py
- mypy/test/teststubtest.py
- runtests.py
I probably should have done this earlier...
> stubtest: speed up tests by a lot

- mypyc/irbuild/expression.py
- mypyc/irbuild/visitor.py
- mypyc/test-data/run-python38.test
- mypyc/test/test_run.py
My assessment that this would not be too hard was accurate.
Fixes mypyc/mypyc#765.
> [mypyc] Implement the walrus operator

- mypy/stubtest.py
- mypy/test/teststubtest.py
Reckon with the fact that __init_subclass__ and __class_getitem__ are
special cased to be implicit classmethods. Note this probably doesn't
fix cases where you overload, but don't mark as classmethods.
Fix some false negatives for other special dunders.
> stubtest: improve handling of special dunders

- mypy/find_sources.py
- test-data/unit/cmdline.test
Fixes #8548
This is important to fix because it's a really common source of
surprising false negatives.
I also lay some groundwork for supporting passing in namespace packages
on the command line. The approach towards namespace packages that this
anticipates is that if you pass in files to mypy and you want mypy to
understand your namespace packages, you'll need to specify explicit
package roots.
We also make many fewer calls to crawl functions, since we just pass
around what we need.
> find_sources: find build sources recursively

- mypy/exprtotype.py
- test-data/unit/check-annotated.test
Closes #9315
This PR aims to support Annotated to create type Aliases when passing a non type as annotation, like this:
```python
class Meta:
...
x = Annotated[int, Meta()]
```
You can test with: 
```
pytest -k testAnnotatedSecondParamNonType --pdb
```
> Improve annotated support with non types

- mypy/modulefinder.py
- test-data/unit/cmdline.test
Fixes part of #5759
The other part is passing files arguments, which we make steps towards
in #9614
> modulefinder: make -p handle namespace packages correctly

- mypyc/irbuild/for_helpers.py
- mypyc/test-data/irbuild-statements.test
It sometimes was short int even though it should have been int.
> [mypyc] Fix type of for loop index register in for over range

- mypy/test/teststubtest.py
- runtests.py
I did some work to speed up stubtest tests substantially in #9621
This is a lesser win. The argument to get rid of it is that it's the
slowest mypy test and just testing for crashes on typeshed doesn't
provide much value. Since this was written, we started running stubtest
in typeshed CI and in practice all changes are tested on typeshed
anyway.
> teststubtest: drop StubtestIntegration

- mypy/checkexpr.py
The has_uninhabited_component was formerly there to avoid clobbering the
store_type call in find_partial_type_ref_fast_path. But this interaction
is avoided by making the store_type call earlier.
> checkexpr: [minor] move node specific logic into its visit

- .travis.yml
Travis-CI started giving support for Python 3.9 so this repo can also run tests on 3.9 instead of 3.9-dev. Related link from Travis [https://travis-ci.community/t/python-3-9-0-build/10091](https://travis-ci.community/t/python-3-9-0-build/10091).
This is a change on CI configuration file, previously tests was running on 3.9-dev now it runs on 3.9. I don't expect a fail but successful result of CI would be enough to test.
> Start using Python 3.9 on Travis

- runtests.py
Running a subset of tests will help speed up typeshed CI. I don't think
typeshed really benefits from running all the other tests. Worst case if
something breaks, it'll be caught when typeshed is synced in mypy.
> runtests.py: list tests to run in typeshed CI

- mypy/test/testutil.py
- mypy/util.py
Contrary to what I assumed in #9143, shutil.get_terminal_size() doesn't
actually handle a 0 width from os.get_terminal_size() - it only handles
a 0 COLUMNS environment variable.
Thus, this caused #8144 to regress.
This change re-adds and uses DEFAULT_COLUMNS and also adds the test
which was deemed unnecessary in #8145 - this regression proves that I'd
have been a good idea to add it in the first place.
(Test written by Anthony Sottile)
Fixes https://github.com/pre-commit/mirrors-mypy/issues/29
> Re-add fallback for zero terminal width

- mypy/typeanal.py
- test-data/unit/check-functions.test
The mypy syntax for a function or method that takes zero parameters
is `() -> …`. Some new mypy users will reason by symmetry that the
syntax for a method that returns nothing is likely `(…) -> ()`.
A user who incorrectly annotates a function with `… -> ()` will be
given the suggestion `Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)`.
This suggestion is unlikely to help correct the user's misconception
about how to annotate the return type of a method that does not
explicitly return a value.
This PR adds a case to TupleType syntax error handling that returns a
helpful suggestion in the case where the tuple contains zero items.
Note: The error message casing in TupleType has grown large enough
that it likely warrants relocation to `MessageBuilder`, but as there
is not a `MessageBuilder` …
> Improve Suggestion for empty TupleType syntax error

- mypy/dmypy_server.py
- mypy/main.py
- mypy/util.py
I think there's an issue for this somewhere too.
> Fix misleading error summary on compile error

- mypy/build.py
- mypy/modulefinder.py
With the changes I've been making to mypy's import handling, I think
this would be a useful thing to add preemptively.
Note that I would have found this very useful at points, and I think
others would too, eg #7672 and #8584
The existing logging ignores source_modules and source_text and doesn't
help with determining what mypy things the module name for a given file
is. This is useful for namespace package issues as in the complaint in #8584.
> build: log build sources with -v

- mypy/stubtest.py
- mypy/test/teststubtest.py
Fixes false negatives where a stub defines an object as a not callable,
but it is in fact a function
> stubtest: construct callable types from runtime values

- mypyc/primitives/float_ops.py
- mypyc/primitives/registry.py
- mypyc/test-data/fixtures/testutil.py
- mypyc/test-data/run-floats.test
- mypyc/test/test_run.py
related mypyc/mypyc#644
Implement `builtins.float` conversion from strings.
> [mypyc] Implement str-to-float primitive

- mypyc/irbuild/classdef.py
- mypyc/irbuild/ll_builder.py
- mypyc/lib-rt/CPy.h
- mypyc/primitives/misc_ops.py
- mypyc/test-data/irbuild-classes.test
relates mypyc/mypyc#753
This PR merges two remaining misc ops.
The problem with these two is that they rely on inlined `PyTypeObject *` cast during the call, while the casted object has already gone through a cast from `PyTypeObject *` to `PyObject *` before the function call(due to the highly C-coupled design in some other parts of the IR).
Thus, I think the best way(at least for now) is to use inline wrappers to merge these two ops, avoiding introducing over-complicated designs for only these two ops.
> [mypyc] Merge fast_isinstance_op and py_calc_meta_op

- mypy/fastparse.py
This got broken by https://github.com/python/typeshed/pull/4740
It took me a little bit to figure out how this evaded all our CI, but
it's because we type check with version 3.5 and mypyc only with 3.5 and
3.7. That is, we do not type check with 3.8 or later and so do not check
against stdlib's AST types.
mypyc wheels did break though, but I'm not sure anyone really looks at
those till they need to. Maybe we should add a badge for them to
the README.
I only noticed this because I was trying to get mypy_primer to mypyc
compile sometimes.
> fastparse: fix type checking on 3.8

- mypy/typeops.py
It is literally the same thing, but using `type_var_ids` is more ideomatic.
> refactor: using proper CallableType method, instead of re-implementation

- docs/source/running_mypy.rst
I was looking at #4542, an old issue that I think we've mostly
addressed, but nonetheless has an alarming number of likes. It occurs to
me that front and centre we mention an issue that most people never run
into in practice.
I also pulled the details of this. mypy's hardcoded list of stdlib
modules is incomplete, but here are the ones on the list that we do not
have stubs for (I only checked Python 3):
```
{'__dummy_stdlib1',
'__dummy_stdlib2',
'ossaudiodev',
'sqlite3.dump',
'turtledemo',
'xml.dom.expatbuilder',
'xml.dom.minicompat',
'xml.dom.xmlbuilder',
'xml.sax._exceptions',
'xml.sax.expatreader',
'xxlimited'}
```
We should maybe consider getting rid of the hardcoded list altogether.
> docs: remove mention of missing standard library stubs

- .github/workflows/mypy_primer.yml
This will run mypy_primer on mypy PRs. Changes on the open source
corpus are reported as comments on the PR.
We integrated this into typeshed CI; you can see examples here:
https://github.com/python/typeshed/pull/3183
https://github.com/python/typeshed/pull/4734
This might be a little slow. On typeshed this runs in 10 minutes, but
it's using a mypyc compiled wheel. It looks like it takes three minutes
to compile a MYPYC_OPT_LEVEL=0 wheel in our CI currently (for a ~2x
speedup in unit tests), so that's probably worth it. We could also run on
a subset of projects (sympy in particular takes a long time).
> mypy_primer: add to CI

- test-requirements.txt
pytest 6.0 causes type checking to fail against master.
Fixes #9671
> test-requirements: bump minimum pytest needed

- mypyc/doc/dev-intro.md
- mypyc/lib-rt/mypyc_util.h
Document tagged integers and some other updates.
> [mypyc] Small improvements to developer docs

- docs/source/mypy_daemon.rst
#8930 presumably forgot to remove this paragraph at the bottom of the page.
> Remove outdated paragraph about dmypy not supporting follow-imports=normal

- mypyc/doc/float_operations.rst
- mypyc/doc/int_operations.rst
- mypyc/doc/str_operations.rst
Also make some primitive descriptions more compact.
> [mypyc] Document more primitives

- mypyc/doc/introduction.rst
This is a major update of the introduction section in the mypyc docs. Shorten
it and update the order of subsections to form a better narrative.
> [mypyc] Make intro to mypyc punchier

- mypy/plugins/attrs.py
- mypy/plugins/default.py
- test-data/unit/check-attr.test
- test-data/unit/lib-stub/attr.pyi
Adds handlers for attr.define, attr.mutable, and attr.frozen.
Adds support for frozen having a non False default.
Adds support the attrib maker: field
Also includes support for auto_attribs=None which means "auto detect which method to use depending on my class".
Added a couple of simple tests.
> Add support for next-gen attrs API

- mypy/main.py
- mypy/modulefinder.py
- mypy/stubgen.py
- mypy/stubtest.py
- mypy/test/testcheck.py
- mypy/test/testmodulefinder.py
- test-data/unit/cmdline.test
This is what #9616 should have been. I noticed this as part of #9672.
Note that this has the unfortunate side effect of causing mypy to fail when run on mypy with `--namespace-packages`, since typeshed is embedded inside mypy. This isn't great, especially in the context of #9636, and maybe indicates a missing "ignore" feature.
> modulefinder: make -p actually handle namespace packages correctly

- .github/workflows/test.yml
- .travis.yml
Our version of tox is getting pretty old. In particular, upgrading
should add support for 3.10 and make builds faster.
> upgrade tox

- mypyc/ir/func_ir.py
New release of flake8-bugbear is causing lint to fail on master.
> mypyc: remove useless comparison

- docs/source/existing_code.rst
PyAnnotate also supports type annotations, not only type comments.
> Remove outdated restriction about PyAnnotate

- mypy/messages.py
- test-data/unit/check-typeddict.test
Previously the message accidentally converted all identifiers to
lowercase. By rephrasing the message, I avoided complicating the
`format_key_list()` function.
Added a test case as well.
Code:
```python
from mypy_extensions import TypedDict
Foo = TypedDict('Foo', {'camelCaseKey': str})
value: Foo = {}
```
Old output:
```
casetest.py:4: error: Key 'camelcasekey' missing for TypedDict "Foo"
```
Output after my changes:
```
casetest.py:4: error: Missing key 'camelCaseKey' for TypedDict "Foo"
```
> TypedDict: Fix casefolding of 'missing keys' error message

- mypy/typeanal.py
- test-data/unit/check-flags.test
- test-data/unit/cmdline.test
Additionally:
- Don't use a cmdline test (looks like this was previously necessary because it was testing PathLike, whose real definition is in typeshed's builtins stub, which we fixture away)
- Add asyncio.Future to the hardcoded list, since it's probably the next most common one.
> PEP 585 improvement to disallow any generic note

- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/list_ops.c
- mypyc/primitives/list_ops.py
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/run-lists.test
Implements list insert primitive for improved performance.
Related ticket: https://github.com/mypyc/mypyc/issues/644
Ensure that inserting at the start, middle and end of a list works as expected, check performance improvements.
The following script was used:
```python
from typing import List
l : List[int] = []
l.insert(0, 1)
```
Master branch:
```
def __top_level__():
r0, r1 :: object
r2 :: bit
r3 :: str
r4, r5, r6 :: object
r7 :: bit
r8 :: str
r9, r10 :: object
r11 :: dict
r12 :: str
r13 :: object
r14 :: str
r15 :: int32
r16 :: bit
r17 :: list
r18 :: dict
r19 :: str
r20 :: int32
r21 :: bit
r22 :: dict
r23 :: str
r24 :: object
r25 :: list
r26 :: str
r27, r28, r29 :: object
r30 :: None
L0:
r0 = builtins :: module
r1 = load_address _Py_NoneStruct
r2 = r0 != r1
if r2 goto L3 else goto L1 :: …
```
> [mypyc] Implement list insert primitive

- docs/source/kinds_of_types.rst
Edit the code in the `AnyString` example `concat()` calls to use sample arguments that are easier to parse, because `concat(b'a', b'b')` just seems needlessly confusing.
* Rebuild docs with `cd docs; make html`
* Review `build/html/kinds_of_types.html` for markup issues or syntax errors
* Verify code sample at `#text-and-anystr` in rendered output
> kinds_of_types: clearer sample bytestrings

- mypyc/build.py
- mypyc/codegen/emit.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/const_int.py
- mypyc/ir/func_ir.py
- mypyc/ir/module_ir.py
- mypyc/ir/ops.py
- mypyc/ir/pprint.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test/test_analysis.py
- mypyc/test/test_emit.py
- mypyc/test/test_emitfunc.py
- mypyc/test/test_exceptions.py
- mypyc/test/test_irbuild.py
- mypyc/test/test_refcount.py
Instead of generating names for ops when building IR, we now generate names 
immediately before pretty-printing or generating C. This simplifies `Environment`
and reduces the amount of mutable state we need to maintain. This a step 
towards removing the `mypyc.ir.ops.Environment` class.
Move code related to pretty-printing to `mypyc.ir.pprint`.
> [mypyc] Generate names lazily when pretty-printing IR or generating C

- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/dict_ops.c
- mypyc/primitives/dict_ops.py
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/run-dicts.test
Implements dict clear primitive for improved performance.
Related ticket: mypyc/mypyc#644
Ensure that clearing a dict works as expected, write tests and calculate performance improvements.
The following script was used:
```python
d = {'a': 1, 'b': 2, 'c': 3}
d.clear()
print(d)
```
Master branch:
```
def __top_level__():
r0, r1 :: object
r2 :: bit
r3 :: str
r4 :: object
r5, r6, r7 :: str
r8, r9, r10 :: object
r11, r12 :: dict
r13 :: str
r14 :: int32
r15 :: bit
r16 :: dict
r17 :: str
r18 :: object
r19 :: dict
r20 :: str
r21 :: object
r22 :: dict
r23 :: str
r24 :: object
r25 :: dict
r26 :: object
r27 :: str
r28, r29 :: object
r30 :: None
L0:
r0 = builtins :: module
r1 = load_address _Py_NoneStruct
r2 = r0 != r1
if r2 goto L3 else goto L1 :: bool
L1:
r3 = load_global CPyStatic_unicode_0 :: …
```
> [mypyc] Implement dict clear primitive

- mypyc/irbuild/expression.py
- mypyc/irbuild/statement.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/run-imports.test
Fix an issue where this code resulted in an unbound local `p`
error:
```
def f() -> None:
import p.submodule
print(p.x)  # Runtime error here
```
We now look up `p` from the global modules dictionary instead
of trying to use an undefined local variable.
> [mypyc] Fix using package imported inside a function

- mypy/build.py
- mypy/find_sources.py
- mypy/fscache.py
- mypy/main.py
- mypy/modulefinder.py
- mypy/options.py
- mypy/suggestions.py
- mypy/test/test_find_sources.py
This is the successor to https://github.com/python/mypy/pull/9632. Things should basically be as discussed in that PR. Since #9616 is merged, this should now resolve #5759.
We leave the Bazel integration with `--package-root` almost entirely untouched, save for a) one change that's a bugfix / doesn't affect the core of what `--package-root` is doing, b) another drive by bugfix that's not related to this PR.
Change a) fixes the package root `__init__.py` hackery when passed absolute paths. Change b) fixes the validation logic for package roots above the current directory; it was broken if you passed `..` as a package root
Since we're leaving `--package-root` alone for now, I named the new flag `--explicit-package-base` to try and avoid confusion. Doing so also matches the language used by …
> mypy: support namespace packages when passing files

- mypy/report.py
Fixes #8979
One-liner fix for path escaping bug in HTML report on windows.
> Fix path escaping bug in HTML report (GH8979)

- test-requirements.txt
The release of pytest 6.2 broke mypy's type checking of itself, since pytest 6.2 drops support for Python 3.5 (https://docs.pytest.org/en/stable/changelog.html#pytest-6-2-0-2020-12-12)
> Fix type check failure stemming from new pytest release

- docs/source/error_code_list.rst
- mypy/errorcodes.py
- mypy/semanal.py
- mypy/semanal_typeddict.py
- test-data/unit/check-errorcodes.test
This gives a new error code for code like this:
```
Foo = NamedTuple("Bar", [...])
```
Since these errors generally don't cause runtime issues, some users may want to 
disable these errors. It's now easy to do using the error code `name-match`.
> Add error code for name mistaches in named tuples and TypedDicts

- mypy/test/testcmdline.py
- mypy/test/testutil.py
Several tests rely on getting the default width of a terminal for
rendering test output. Some PTY environments (in my case the Emacs
shell) set the env var `COLUMNS` to the terminal width, which can
cause several tests to fail due to formatting mismatches.
Prior to running thesee tests, mock out `sys.environ`, removing the
`COLUMNS` env var when present.
The change should only effect environments like my own. After this change, tests pass in my environment. The change can be manually tested in other environments by running
``` Shell
COLUMNS=120 ./runtests.py
```
before, then after applying the change.
> tests: Avoid side effect of COLUMNS env var

- mypy/test/data.py
- mypy/test/helpers.py
Description
Fixing completely broken `--update-data` flag for pytest.
I had a great deal of pain to update tests as the `--update-data` flag didn't do a thing. On examining I realised that few logics are incorrect. I will try to explain them.
To determine the last line of the test it uses `item.line`. Well each item is the content between statements of the type [file], [case], [out], etc. `item.line` provides the first line of the item. Previously, `testcase.lastline` was defined as the first line of the last item. But the last item might consist of more than one line for example-
```
[out]
Error 1
Error 2
Error 3
```
Here the test case will be limited to Error 1. So we need to instead make testcase.lastline as item.line + len(item.data) - 1
Also while performing an update to test it …
> fixing the --update-data flag for pytest [reopened]

- mypyc/codegen/emitclass.py
- mypyc/lib-rt/CPy.h
See https://github.com/python/cpython/blob/master/Include/cpython/object.h#L456
Fixes https://github.com/mypyc/mypyc/issues/789.
I didn't add a test because a test needs to create a lot of nodes.
Tested manually.
> Use Py_TRASHCAN_{BEGIN,END} in tp_dealloc functions

- mypyc/analysis/dataflow.py
- mypyc/codegen/emit.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/func_ir.py
- mypyc/ir/ops.py
- mypyc/ir/pprint.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/callable_class.py
- mypyc/irbuild/classdef.py
- mypyc/irbuild/function.py
- mypyc/irbuild/generator.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/main.py
- mypyc/test-data/exceptions.test
- mypyc/test-data/refcount.test
- mypyc/test/test_analysis.py
- mypyc/test/test_emit.py
- mypyc/test/test_emitfunc.py
- mypyc/test/test_pprint.py
- mypyc/test/test_refcount.py
- mypyc/transform/exceptions.py
- mypyc/transform/refcount.py
- mypyc/transform/uninit.py
Remove `mypyc.ir.ops.Environment`. Represent potentially uninitialized variables 
explicitly in the IR by generating an assignment of an error value, instead of relying 
on the environment to keep track of uninitialized variables.
This simplifies the IR and makes it more consistent, and it will also make it a little 
easier to create new backends. More importantly, this removes one variant of
the "environment" concept. The term is less overloaded now.
> [mypyc] Remove Environment

- mypyc/README.md
- mypyc/doc/dev-intro.md
- runtests.py
- test-data/unit/README.md
Without this option, pytest can print out many lines of garbage
if there are more than 8 parallel processes being used. This can
result in test output being hard to read, and it also looks bad.
Since many new CPUs have 6+ cores, and 16+ cores are not unusual, it's
reasonable to use -q by default.
> Use the pytest -q option for tidier output with multi-core CPUs

- mypyc/irbuild/builder.py
- mypyc/irbuild/statement.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/misc_ops.c
- mypyc/primitives/misc_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/run-misc.test
Speed up multiple assignment from variable-length lists and tuples. 
This speeds up the `multiple_assignment` benchmark by around 80%.
Fix multiple lvalues in fixed-length sequence assignments.
Optimize some cases of list expressions in assignments.
Fixes mypyc/mypyc#729.
> [mypyc] Speed up and improve multiple assignment

- mypyc/irbuild/builder.py
- mypyc/irbuild/callable_class.py
- mypyc/irbuild/classdef.py
- mypyc/irbuild/expression.py
- mypyc/irbuild/function.py
- mypyc/irbuild/generator.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/main.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
Add new helpers for generating methods that reduces the required
boilerplate. Switch several existing use cases to use the new helpers.
Summary of the new helpers:
1. Call `builder.enter_method(...)` to begin generating IR for a method.
2. Call `builder.add_argument(..)` for each non-self argument.
3. Generate method body normally.
4. Call `builder.leave_method()`.
Previously `enter()` and `leave()` had to be used, along with several
additional steps, such as defining `self` explicitly. The new approach 
is much easier to use and less error-prone. 
Since not all uses of the old interface have been removed, there is 
still some duplication. It would be great to eventually always use the 
higher-level interface to generate methods and functions.
> [mypyc] Refactor method IR generation

- mypyc/ir/ops.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/context.py
- mypyc/irbuild/env_class.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/function.py
- mypyc/irbuild/nonlocalcontrol.py
- mypyc/irbuild/statement.py
- mypyc/irbuild/targets.py
Since they are only used during the IR build, define them in
`mypyc.irbuild`. Also simplify the implementation slightly.
> [mypyc] Refactor assignment targets

- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
This continues work on mypyc/mypyc#781.
> [mypyc] Remove EmitterInterface as it's not needed for anything

- mypyc/analysis/dataflow.py
- mypyc/codegen/emitfunc.py
- mypyc/ir/ops.py
- mypyc/ir/pprint.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/ll_builder.py
- mypyc/primitives/int_ops.py
- mypyc/test/test_emitfunc.py
- mypyc/test/test_pprint.py
Since `IntOp` is also used as a namespace for op constants, it's common to
refer to the class name twice per operation, making it useful to use a shorter 
name.
> [mypyc] Rename BinaryIntOp to IntOp

- mypyc/irbuild/ll_builder.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/run-integers.test
This speeds up the `if_true` microbenchmark by about 5%. Code size is also
reduced.
> [mypyc] Speed up 'if x' for int values

- mypy/main.py
- mypy/options.py
- mypy/semanal.py
- test-data/unit/check-parameter-specification.test
- test-data/unit/semanal-errors.test
- test-data/unit/semanal-types.test
This prevents users from hitting asserts before PEP 612 support is fully
implemented.
> PEP 612: hide from those who may seek to use it

- .github/workflows/mypy_primer.yml
- .github/workflows/mypy_primer_comment.yml
mypy_primer was temporarily removed in #9769. This brings it back.
See https://github.com/python/typeshed/pull/4806 for the equivalent
typeshed PR.
One change is that we now shard across three jobs for speed. We also no
longer mypyc compile, since we should be right about the point where the
gains from compilation are outweighted by compilation time (for
`--mypyc-compile-level 0`). Although if there were an easy way to share
the compiled mypys across mypy runs it would be worth it...
> Return mypy_primer to CI

- mypy/main.py
- test-data/unit/cmdline.test
Currently only files can be specified on the command line if files are
specified in mypy.ini.  This looks a great deal like a bug, especially
since packages and modules cannot be specified in the configuration
file. 
This PR changes the logic to only use the files from the ini
file if none of (modules/packages/files) are specified on the command
line and adds tests to verify the new behavior.
I would also like to add packages and modules keys to the configuration file so a project I work on can use packages as its default without arguments, but want to gauge interest in that first, where this looked like it was probably a mistake with a straightforward solution.
Three new tests have been added to the codlin.test file that test that the conflict is still noted when both are placed on the …
> allow packages/modules as args with files in cfg

- mypy/test/testtransform.py
- mypy/treetransform.py
- test-data/unit/check-generics.test
See first test case for the scenario where this causes issues (the second test case is already handled elsewhere and just added for completeness). This is an old issue, but it is important to fix it now because recent changes to PEP 484 about re-export force people to use function aliases.
> Don't expand global variables in body of a function with constrained type variables

- docs/source/builtin_types.rst
- docs/source/common_issues.rst
- docs/source/index.rst
- docs/source/kinds_of_types.rst
- docs/source/runtime_troubles.rst
Fixes #8629, fixes #8523
This creates a new page to document issues arising from discrepancies
between the runtime and annotations. I felt this was better, rather than
force-fitting things into existing pages and "common issues", for
instance, it prevents us from having to explain PEP 563 in several
different places.
I do still list the runtime errors you'd get in the "common issues" page
to preserve SEO :-)
"String literal types", "Class name forward references", and "Import
cycles" are basically the same as where they were copied over from.
This also factors out the documentation of PEP 604 that I promised when
merging that PR (it seemed pretty verbose, particularly for the "kinds
of types" page). It's also a good place to document PEP 613, when we get
around to supporting that.
> Document PEP 585, 563, 604 and more.

- mypy/moduleinspect.py
- mypy/stubdoc.py
Fixes #9888
I applied the following patch to typeshed and ran self check:
```
+@overload
+def getattr(__o: Any, name: str, __default: None) -> Optional[Any]: ...
+@overload
def getattr(__o: Any, name: str, __default: Any = ...) -> Any: ...
```
> Fix type errors stemming from getattr

- mypyc/lib-rt/list_ops.c
- mypyc/test-data/run-lists.test
The test case wasn't actually testing the primitive, since all the
calls were in the driver, which doesn't get compiled.
Also refactor the test cases to help avoid similar issues in the
future.
> [mypyc] Fix overflow error handling in list.insert and fix tests

- mypyc/irbuild/for_helpers.py
This stopped working as a side effect of typeshed changes in #9512. 
This fixes an old performance regression in the hexiom benchmark:
https://github.com/mypyc/mypyc-benchmark-results/blob/master/reports/benchmarks/hexiom.md
> [mypyc] Recognize 'six.moves.xrange' as an alias of 'range'

- mypy/stubgenc.py
This fixes an issue introduced in https://github.com/python/mypy/pull/9088/files where `Any` and `Dict` are missing from the list of default imports that stubgen can perform, due to a missing comma.
Because this is such a small change I just did a quick manual test by using stubgen on a module that uses both `Any` and `Dict`.
> Fixed Any and Dict missing from stubgen imports list

- mypy/stubgen.py
- test-data/unit/stubgen.test
Improves `stubgen` to convert functions that have been decorated with `@overload`.   `stubgen` is useful not just for creating a starting point for manually authoring stubs, but also to create automated workflows to continuously regenerate stubs for projects that want to provide stubs to third parties to hide runtime complexity from mypy. 
Added two new tests.
> stubgen: properly convert overloaded functions

- docs/source/command_line.rst
- docs/source/running_mypy.rst
This should cover the current state on master, as previously
discussed / implemented across #9742, #9683, #9632, #9616, #9614, etc.
This will need to be changed if we can make `--namespace-packages` the
default (#9636).
I haven't documented some of the finer points of the changes, since it
felt like an inappropriate level of detail (e.g. using absolute paths
when crawling, how directories with invalid package names affect
crawling, etc)
> Document new source finding behaviour

- docs/source/builtin_types.rst
- docs/source/cheat_sheet_py3.rst
- docs/source/config_file.rst
- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/kinds_of_types.rst
- docs/source/running_mypy.rst
Use the new generic built-in type syntax (`list[t]` etc.) in the cheat sheet,
getting started and built-in types sections. Most examples still use the old
syntax, but this at least introduces the new syntax early on.
Also other minor documentation tweaks.
> Various doc updates, mostly about list[t] etc.

- mypy/plugins/default.py
- test-data/unit/check-literal.test
- test-data/unit/check-typeddict.test
- test-data/unit/pythoneval.test
Fixes #9902
Previously this would throw an error, however according to PEP 589
.get() should be allowed for arbitrary expressions with type str, while
only [] throws an error.
All affected tests have been updated to the new, intended behavior. This is my first contribution to mypy, so it would be good to have an extra pair of eyes checking if everything is correct.
> Fix TypedDict.get("missing_key") with string literal

- mypy/checker.py
- test-data/unit/check-classes.test
Fixes #7205
Hello everyone,
this is my first contribution to mypy, I hope to meet your style well enough.
I added two test cases which cause mypy to crash without the provided changes. At least on my machine, the changes do not affect any other tests. 
For short explanations, please see the commit message and the (modifications of the) inline comments.
> Report incompatible assignments for descriptors with overloaded __set__ methods.

- LICENSE
- mypyc/codegen/emitclass.py
- mypyc/codegen/emitmodule.py
- mypyc/codegen/emitwrapper.py
- mypyc/common.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/getargs.c
- mypyc/lib-rt/getargsfast.c
Implement faster argument parsing based on METH_FASTCALL on supported
Python versions. 
Use `vgetargskeywordsfast` extracted from Python 3.9 with some modifications:
* Support required keyword-only arguments, `*args` and `**kwargs`
* Only support the 'O' type (to reduce code size and speed things up)
The modifications are very similar to what we have in the old-style
argument parsing logic.
The legacy calling convention is still used for `__init__` and `__call__`. I'll add
`__call__`  support in a separate PR. I haven't looked into supporting `__init__`
yet.
Here are some benchmark results (on Python 3.8)
* keyword_args_from_interpreted: 3.5x faster than before
* positional_args_from_interpreted: 1.4x faster than before
However, the above benchmarks are still slower when compiled. I'll …
> [mypyc] Use faster METH_FASTCALL wrapper functions on Python 3.7+

- mypyc/codegen/emitclass.py
- mypyc/codegen/emitmodule.py
- mypyc/codegen/emitwrapper.py
- mypyc/common.py
- mypyc/irbuild/callable_class.py
Allocate a vectorcall function pointer as a struct field for native
classes that include `__call__`, including nested functions. This
lets us use METH_FASTCALL wrapper functions with `__call__`
methods.
See https://www.python.org/dev/peps/pep-0590/ for details of why
we jump through these hoops.
This makes the `nested_func` microbenchmark about 1.5x faster.
Follow-up to #9894.
> [mypyc] Use METH_FASTCALL with "__call__"

- .travis.yml
It looks like pip just dropped Python 3.5 support, but we are not quite
yet ready to do it (as long as there's an easy workaround).
Example failure here:
https://travis-ci.com/github/python/mypy/jobs/474676438
> Fix Python 3.5 travis build by pinning pip

- mypyc/codegen/emitwrapper.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/getargsfast.c
- mypyc/test-data/run-functions.test
Add specialized argument parsing functions for these simple signatures:
1. No arguments
2. Single argument
3. No keyword-only args, *kwargs or **kwargs
The latter case covers many typical functions, such as these:
```
def f(x: int, y: int) -> int: ...
def g(x: int = 0) -> str: ...
```
The new parsing functions take a fast path when the caller passes only positional
arguments. This speeds up wrapper functions a lot in simple calls.
Microbenchmark speedups:
* `positional_args_from_interpreted` is 1.5x faster (now faster than interpreted)
* `nested_func` is 1.5x faster
* `sorted_with_key` is 14% faster (now faster than interpreted)
> [mypyc] Add fast path for simple calls in wrapper functions

- mypyc/lib-rt/getargsfast.c
Since we only use relatively few features supported by the original argument
parsing code, much of the code can be deleted.
This speeds up the `keyword_args_from_interpreted` benchmark by about 8%.
> [mypyc] Remove unused fast argument parsing code

- mypyc/codegen/emitmodule.py
- mypyc/test-data/run-strings.test
This makes us more compatible with CPython, which interns (some)
string literals.
This speeds up some microbenchmarks slightly, by around 0.5-2%.
This may give a bigger speed win when calling functions using 
vectorcalls and keyword arguments, but we'll see about that once that's 
supported. Vectorcall argument parsing code has a fast path for interned
keyword argument names.
> [mypyc] Intern string literals

- mypyc/doc/list_operations.rst
- mypyc/lib-rt/list_ops.c
- mypyc/primitives/list_ops.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/run-lists.test
This speeds up the `list_remove` microbenchmark by about 30% and the
`list_index` microbenchmark by about 55%.
There is still room for making these faster by specializing based on item
type, for example, but since these primitives aren't used very commonly,
other optimization work seems higher priority.
> [mypyc] Add primitives for list index() and remove()

- docs/source/running_mypy.rst
For whatever reason, these options get misused a lot and cause a lot of
problems. #9954 is only the latest in a long history of
misunderstanding.
I speculate that this is because of a) the bad legacy of flake8-mypy,
b) people confusing it with ignore_missing_imports
> Emphasise that users probably want --follow-imports=normal

- mypy/main.py
Fixes a typo in the error raised when envoking mypy with `--explicit-package-bases` without also providing `--namespace-packages`. Currently the error refers to a non-existing parameter `--explicit-base-dirs`.
> Fix typo in error message

- docs/source/config_file.rst
I was unsure if the `mypy_path` entry in the config file was treated relative to the config file, and found the answer in #7967 (it is treated relative to the working directory of the mypy command).
This PR documents current behavior, and mentions how `MYPY_CONFIG_FILE_DIR` can be used to refer to path relative to the configuration file.
Rebuilding docs creates expected results.
> Clarify that mypy_path is relative to CWD

- README.md
- docs/source/common_issues.rst
- mypy/git.py
- mypy/modulefinder.py
- mypyc/README.md
- setup.py
These are no longer relevant after we removed the typeshed
submodule in #9973.
> Remove references to git submodules in documentation and code

- mypy/modulefinder.py
In some cases the VERSIONS file can't be found, and it's kind of hard to debug.
> Add assertion to help debugging typeshed issues

- mypy/modulefinder.py
Previously giving an invalid value to `--custom-typeshed-dir` could
cause mypy to crash.
This is important since existing typeshed forks will not work with
the new typeshed structure.
(This may also help with mypy primer.)
> Detect invalid value for --custom-typeshed-dir

- docs/source/config_file.rst
This value appears to be supported in the config file, but is missing from the docs.
> Add explicit_package_bases to docs

- mypy/dmypy_server.py
File watcher state for files added to the build wasn't updated
correctly, resulting in crashes.
I couldn't find a way to reproduce this in our test environment,
so I only tested this manually.
Fixes #10029.
> Fix mypy daemon crash when following from a new module

- mypy/server/update.py
- test-data/unit/fine-grained-follow-imports.test
A special case for dealing with blocking errors caused false positives
when following imports. Narrowed down the special casing to only
trigger when there is blocking errors.
The logic is still quite convoluted, but at least this fixes some
issues with following imports to stub packages.
Fixes #10022.
> Fix import following issue in daemon

- mypy/build.py
Even if we assume that typeshed stubs don't change, we need the deps
when bringing in new stubs when following imports during a fine-grained
increment.
This fixes false positives when following imports to `six` and
`requests`.
Some modules are always part of the initial build, and we can still
skip generating deps for them, as an optimization.
I only tested this manually, since I couldn't figure out an easy way to
reproduce the issue in our tests.
Fixes #10033.
> Keep track of fine-grained deps for modules in typeshed

- docs/source/protocols.rst
Most code snippets from the documentation are runnable - they can be pasted into temporary `t.py` files, and then `mypy t.py` works. Doing so is a good way to make sense of the documentation.
The example about [using isinstance with protocols](https://mypy.readthedocs.io/en/stable/protocols.html#using-isinstance-with-protocols), however, throws 
```console
$ mypy t.py 
t.py:13: error: Name 'use' is not defined
```
So, here's a little PR to make the example runnable, such that we have:
```console
$ mypy t.py 
Success: no issues found in 1 source file
```
and, if we remove `@runtime_checkable`,
```console
$ mypy t.py 
t.py:14: error: Only @runtime_checkable protocols can be used with instance and class checks
```
This is just a simple doc …
> Make "Using isinstance() with protocols" example runnable

- mypyc/codegen/emitmodule.py
- mypyc/codegen/literals.py
- mypyc/ir/ops.py
- mypyc/irbuild/expression.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/misc_ops.c
- mypyc/test/test_literals.py
Add support for loading tuple literals using `LoadLiteral`. The literal tuple objects will
be constructed during module import time, similar to other literals. Only tuples containing
items of supported literal types can be represented (this includes other tuples).
Add `None`, `True` and `False` to the literals array so that they can be used as tuple
literal items.
Currently tuple literals aren't used for anything. I added some unit tests to check parts
of the implementation.
The primary use case I have in mind is supporting vectorcall APIs which expect a tuple
of keyword argument names. I will implemented this in a separate PR. This will also add 
some end-to-end testing for tuple literals.
These could be used to avoid repeatedly constructing tuples with literal values in other
contexts …
> [mypyc] Foundational support for tuple literals (+ None and bool)

- docs/source/command_line.rst
- docs/source/config_file.rst
- docs/source/running_mypy.rst
- mypy/build.py
- mypy/config_parser.py
- mypy/find_sources.py
- mypy/main.py
- mypy/modulefinder.py
- mypy/options.py
- mypy/test/test_find_sources.py
- mypy_self_check.ini
- test-data/unit/cmdline.test
Resolves #4675, resolves #9981
Additionally, we always ignore site-packages and node_modules.
Also note that this doesn't really affect import discovery; it only
directly affects passing files or packages to mypy.
The additional check before suggesting "are you missing an
__init__.py" didn't make any sense to me, so I removed it, appended to
the message and downgraded the severity to note.
> Add --exclude

- mypy/main.py
Currently cache_dir does not expand user home directory, which results
in counter-intuitive behavior when setting for instance
```MYPY_CACHE_DIR='~/.cache/mypy/'```
In this case a folder named `~` is created in the cwd where mypy is
launched.
This commit modifies the behavior and expands the ~ into the user home
directory.
Tested by setting `MYPY_CACHE_DIR=~/.cache/mypy` and checked that the folder is picked correctly.
> Expand user home directory for cache_dir

- build-requirements.txt
- test-requirements.txt
Self-compilation needs some stub packages. I'm adding them to a separate
since they are not needed for running mypy, and since we may want to
be able to build mypy without installing all test dependencies, some of which
are quite heavy.
> Add separate requirements file for mypy self-compile

- docs/source/command_line.rst
- docs/source/error_code_list.rst
- docs/source/error_code_list2.rst
- docs/source/getting_started.rst
- docs/source/type_inference_and_annotations.rst
- mypy/messages.py
- test-data/unit/check-attr.test
- test-data/unit/check-classes.test
- test-data/unit/check-columns.test
- test-data/unit/check-errorcodes.test
- test-data/unit/check-expressions.test
- test-data/unit/check-flags.test
- test-data/unit/check-functions.test
- test-data/unit/check-inference-context.test
- test-data/unit/check-inference.test
- test-data/unit/check-inline-config.test
- test-data/unit/check-literal.test
- test-data/unit/check-newsemanal.test
- test-data/unit/check-protocols.test
- test-data/unit/check-python2.test
- test-data/unit/check-python38.test
- test-data/unit/check-selftype.test
- test-data/unit/check-statements.test
- test-data/unit/check-tuples.test
- test-data/unit/check-typeddict.test
- test-data/unit/check-typevar-values.test
- test-data/unit/check-unreachable-code.test
- test-data/unit/fine-grained.test
- test-data/unit/pythoneval.test
Fixes some of #7445 
Replaces instances where single quotes are used in messages with double quotes around the ```mpypy/messages.py```
There are two to three messages that still use single quotes, that are heavily present throughout the test cases.
Updated test cases for these specific changes, no new test cases added, only modified
> Fix  (some of )  #7445

- mypy/test/test_find_sources.py
This was failing during wheel builds because we run the tests after
installation (under `site-packages`), and this confused the module
search logic. Use a temp directory instead.
> Fix test_find_sources when run under site-packages

- mypy/main.py
This (for example) fixes the option on windows where `python3.exe` is either not a thing or it is a stub that opens the windows store
run mypy with `--install-types` on windows
> use sys.executable instead of `python3` for --install-types

- docs/source/config_file.rst
- mypy/dmypy_server.py
- mypy/test/testdaemon.py
- test-data/unit/fine-grained-modules.test
Find added stubs in daemon when using `--follow-imports=skip`. Previously
it was often necessary to restart the daemon to find new stubs. This was 
inconsistent, as the initial build did follow imports to stubs but incremental
runs didn't (at least reliably).
Add an optimization that avoids checking modules within top-level packages
that clearly don't exist.
This still can regress performance in large codebases somewhat significantly.
I'll create follow-up PRs that make the regression less bad.
Also mark `follow_imports_for_stubs` as unsupported in the daemon. I don't 
think that it worked reliably before, and now it works even less well.
> Fix following stub imports in daemon when using --follow-imports=skip

- mypy/dmypy_server.py
- mypy/modulefinder.py
The skipped check is pretty slow, and it's not useful when following
imports to suppressed modules.
> Use fast path for finding modules in mypy daemon

- mypy/fscache.py
- mypy/test/testfscache.py
This speeds up resolving imports somewhat.
Add fast paths to `isfile_case`. On Linux we skip all logic, since
the file system is almost always case sensitive.
Cache results of parent directories as well.
Add tests.
> Speed up case sensitive is-file check in file system cache

- mypy/dmypy_server.py
`encodings` uses module-level `__getattr__`.  By not trying to follow
imports to the submodules, resolving imports is slightly faster.
This is usually pretty marginal, but there can be over 100 suppressed
submodules, so this may actually be significant.
> Don't try to follow imports to encodings.*

- misc/build_wheel.py
The contents are extracted from the current GitHub action definition:
https://github.com/mypyc/mypy_mypyc-wheels/blob/master/.github/workflows/build.yml
This is a fairly direct translation of the existing behavior. The
behavior should be identical to the current workflow.
The idea is to make this easier to maintain and easier to test
locally.
> Add Python script to build wheels using cibuildwheel

- mypyc/lib-rt/getargsfast.c
Fixes https://github.com/mypyc/mypyc/issues/800
I believe this is the only instance of a variable declaration inside a for-loop initialization. Removing this may help with consistent compilation across different C compiler configurations. See linked issue for more details.
> [mypyc] declare `Py_ssize_t i` outside of loop initialization

- mypy/stubgen.py
- setup.py
This might fix the out-of-memory errors we are getting when
building Windows wheels. In any case these will speed up
builds slightly.
> Reduce the size of the build by not compiling stubgen

- misc/build_wheel.py
This may reduce memory use and thus fix the builds.
> Use multi-file builds on Windows

- mypyc/codegen/emitmodule.py
- mypyc/codegen/literals.py
- mypyc/ir/ops.py
- mypyc/irbuild/expression.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/misc_ops.c
- mypyc/test/test_literals.py
This reverts commit 047e427ff960aca4565897e5e77324fc7660ff10.
Looks like that the new literal support broke Windows builds somehow.
> Revert "[mypyc] Foundational support for tuple literals... (#10041)"

- test-data/stdlib-samples/3.2/shutil.py
Mypy's example test file causes mypy errors if typeshed makes `WindowsError` available only on Windows, as it should be. This PR fixes the test to use `WindowsError` only on Windows.
See: https://github.com/python/typeshed/pull/5032
Mypy's test suite should pass after applying this patch to typeshed (patch based on 1184e6e4 which is currently latest master):
```diff
commit e26f1fa4772c26f48fff3f31a985a1c97c620917
Author: Akuli <akuviljanen17@gmail.com>
Date:   Fri Feb 19 13:47:15 2021 +0200
make WindowsError available only on windows
diff --git a/stdlib/builtins.pyi b/stdlib/builtins.pyi
index 6eaae007..7512cb94 100644
--- a/stdlib/builtins.pyi
+++ b/stdlib/builtins.pyi
@@ -1297,7 +1297,8 @@ class OSError(Exception):
EnvironmentError = OSError
IOError = OSError
-WindowsError = OSError
+if …
```
> test-data shutil sample: use WindowsError on windows only

- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/dict_ops.c
- mypyc/primitives/dict_ops.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/run-dicts.test
Implements dict copy primitive for improved performance.
Related ticket: https://github.com/mypyc/mypyc/issues/644
Ensure that both copying an empty and an non-empty dict works as expected, meaning that the original and the copied dicts contain the same key-values.
The following script was used:
```python
d = {'a': 1, 'b': 2, 'c': 3}
c = d.copy()
print(c)
```
Master branch:
```
def __top_level__():
r0, r1 :: object
r2 :: bit
r3 :: str
r4 :: object
r5, r6, r7 :: str
r8, r9, r10 :: object
r11, r12 :: dict
r13 :: str
r14 :: int32
r15 :: bit
r16 :: dict
r17 :: str
r18 :: object
r19 :: dict
r20 :: str
r21 :: object
r22, r23 :: dict
r24 :: str
r25 :: int32
r26 :: bit
r27 :: dict
r28 :: str
r29 :: object
r30 :: dict
r31 :: object
r32 :: str
r33, r34 :: object
r35 :: None
L0:
r0 = builtins :: …
```
> [mypyc] Implement dict copy primitive

- runtests.py
Alternative PR to #10052. This version uses `subprocess`.
Also removes code, which was unreachable since mypy requires python 3.5.
The changed have been manually tested on linux and a windows VM with python installed to `C:\Program Files\Python39` (So the path contains a space).
It was also tested that failure of individual tests still lead to the whole test script failing.
> Migrate runtests.py from os.system to subprocess

- mypy/build.py
- mypy/dmypy_server.py
- mypy/server/update.py
- mypy/suggestions.py
- mypy/test/testmerge.py
Processing newly installed stub files, in particular, could be quite slow incrementally
in mypy daemon. This is because adding N files results in N steps interally, each of 
which adds one file. However, each step parses all remaining files, resulting in 
an O(n**2) algorithm.
For example, processing `six` stubs could take about 40s (when not using a 
compiled mypy).
Partially address the issue by caching parsed ASTs during a single increment.
This speeds up the `import six` use case by about 3x when not using a compiled
mypy. It's still about 3x slower when using daemon, however.
> Speed up processing of new files in daemon by caching ASTs

- mypy/traverser.py
- mypy/visitor.py
Currently a very important tool - which `NodeVisitor` definitely is - is not available to be used in a 3rd party code.
Because currently inheriting from `NodeVisitor` raises an exception: `TypeError: interpreted classes cannot inherit from compiled traits`
A developer has a single choice to replicate the same visitor patter by theyself, which is not really convenient.
So, I propose to make this consistent with `TypeVisitor`, which already allows having interpreted subclasses.
Refs https://github.com/python/mypy/commit/a9fa9ab43a2655cf81c66c065d51db4618839d05
Refs https://github.com/python/mypy/issues/9001
Refs https://github.com/python/mypy/pull/9602
As https://github.com/python/mypy/pull/9602 have shown, this is fine without tests.
Correct me if I am wrong, please, and I would contribute …
> Adds ability to have subclasses for NodeVisitor and TraverserVisitor

- .github/workflows/test.yml
Updates two actions to the latest versions (`v1` is outdate as for now), changes how submodules are initialized.
Closes #9781 (GitHub Actions are currently in Alpha in dependabot, they do not work reliably).
> GitHub actions house-keeping

- mypy/stubgenc.py
- mypy/test/teststubgen.py
Fixes https://github.com/python/mypy/issues/10137
Changed `obj.mro()` to `type.mro(obj)` so it properly invokes the `mro` of `type` when `obj` is `type`
After this change, `stubgen` can properly generate pyi files for cython modules or native modules that include types inheriting the builtin `type`. Any package include such definition of class would be suitable for testing this.
Added a unittest for `generate_c_type_stub` as well.
> Fix mro invoking #10137

- misc/build_wheel.py
related to #10114 
I add a `CIBW_TEST_SKIP` in line 53 according to [this](https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon). Is it necessary? I am not sure whether it would work or not.
> Add Apple Silicon support when building wheels

- mypyc/codegen/emitmodule.py
- mypyc/codegen/literals.py
- mypyc/ir/ops.py
- mypyc/irbuild/expression.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/misc_ops.c
- mypyc/test/test_literals.py
This adds back #10041 that was reverted because of failing Windows builds.
The Windows issue was fixed in #10147, so this is a rebased version of the
original PR.
> [mypyc] Foundational support for tuple literals (+ None and bool), try 2

- mypy/plugins/enums.py
- test-data/unit/check-enum.test
In #9443, some code was added to predict the type of enum values where it is not explicitly when all enum members have the same type.
However, it didn't consider that subclasses of Enum that have a custom `__new__` implementation may use any type for the enum value (typically it would use only one of their parameters instead of a whole tuple that is specified in the definition of the member). Fix this by avoiding to guess the enum value type in classes that implement `__new__`.
In addition, the added code was buggy in that it didn't only consider class attributes as enum members, but also instance attributes assigned to self.* in `__init__`. Fix this by ignoring implicit nodes when checking the enum members.
Fixes #10000.
Apart from manually testing the example from #10000, new unit tests …
> Fix recently added enum value type prediction

- mypy/messages.py
- test-data/unit/check-protocols.test
Fix #10129
Now can generate notes successfully.
> Add UnionType support when incompatible protocol happens

- mypyc/doc/conf.py
- setup.cfg
Consistency is good.
Work on mypyc/mypyc#807.
> [mypyc] Make mypyc docs use the same theme as mypy docs

- mypyc/README.md
This README will go away once all the useful content is covered in the
new README or the main mypyc documentation.
> [mypyc] Add pointer to the new mypyc README

- mypyc/doc/introduction.rst
Improve clarity and add a comparison against Cython.
> [mypyc] Updates to introduction in the documentation

- docs/source/cheat_sheet.rst
- docs/source/command_line.rst
- docs/source/python2.rst
- mypy/fastparse2.py
- setup.py
> Make Python 2 support an extra

- .gitignore
- mypyc/doc/dict_operations.rst
- mypyc/doc/native_classes.rst
- mypyc/doc/str_operations.rst
Here are a few updates/fixes after a read through the mypyc docs.
For the corresponding primitive method updates, see:
- `str.replace`: https://github.com/python/mypy/pull/10088
- `dict.copy`: https://github.com/python/mypy/pull/9721
- `dict.clear`: https://github.com/python/mypy/pull/9724
> [mypyc] Small documentation updates

- mypy/strconv.py
This fixes strconv not displaying `False` and possibly other falsy values. I ran into this problem while writing tests for #10191.
No currently existing tests are affected by this change.
> Fix strconv not displaying False and possibly other falsy values

- mypy/join.py
- mypy/typeops.py
- test-data/unit/check-enum.test
> Recombine complete union of enum literals into original type (#9063)

- mypy/sitepkgs.py
distutils is deprecated in python 3.10, so we only import it if it is
needed, which should only be python < 3.2
All tests still pass. This is a trivial change and shouldn't cause any problems.
> Only import distutils if it is needed

- mypyc/lib-rt/dict_ops.c
- mypyc/lib-rt/pythonsupport.h
- mypyc/test-data/run-misc.test
_PyObject_HasAttrId() has been removed in https://github.com/python/cpython/pull/22629
Multiple test which failed on 3.10.0a6 are now working again.
All tests still work on python 3.9. mypyc-extra was also tested.
> Fix mypyc failing to compile on CPython 3.10.0a6

- mypyc/doc/conf.py
Silence an awkward mypy error if somebody tries to type check this
file.
> [mypyc] Ignore type error in conf.py used for doc generation

- mypyc/irbuild/expression.py
- mypyc/test-data/irbuild-unreachable.test
- mypyc/test-data/run-misc.test
- mypyc/test/test_irbuild.py
Unreachable generator expressions are still failing, but most others work.
Fixes mypyc/mypyc#761.
> [mypyc] Fix compilation of unreachable expressions

- mypyc/irbuild/builder.py
- mypyc/irbuild/classdef.py
- mypyc/test-data/run-tuples.test
Fix a compile error when an unboxed initializer is used for a boxed
final variable.
I had to tweak how enums are compiled to avoid breaking them as
a side effect.
Fixes mypyc/mypyc#815.
> [mypyc] Box initializers of final variables when required 

- mypyc/codegen/emitfunc.py
- mypyc/test/test_emitfunc.py
This reduces the number of lines in the generated C when compiling
the richards benchmark by about 5%.
The main benefit is making the generated C easier to read by humans.
This may also marginally improve the speed of compilation.
> [mypyc] Simplify generated C by omitting gotos to the next block

- mypy/messages.py
- mypyc/test-data/run-loops.test
- test-data/unit/check-inference.test
- test-data/unit/check-modules.test
- test-data/unit/check-tuples.test
- test-data/unit/check-unions.test
This pull request fixes issue reported in #7445 for **object is not iterable** error message
Updated test cases for the message. New test cases  not added.
> double quotes in 'object is not iterable' error message

- mypy/checker.py
- mypy/checkexpr.py
While reading throught the `mypy`'s source code these two things caught my eye:
1. `push_type_map` was re-implemented in-place for `check_for_comp`
2. ~~`push_type_map` had special handling for case when `type_map` argument is `None` which should not be possible, because `type_map: 'TypeMap'` and `no_implicit_optional = True` and `strict_optional = True` are on.~~ Ok, I have missed that `TypeMap` alias is defined as `Optional`, excluded.
Existing tests should cover this.
> Refactor push type map

- mypy/messages.py
- test-data/unit/check-typeddict.test
This pull request fixes issue reported in #7445 for `is not a valid TypedDict key` error message
> Use double quotes in error message "is not a valid TypedDict key"

- mypyc/irbuild/specialize.py
- mypyc/test-data/irbuild-isinstance.test
- mypyc/test-data/run-integers.test
- mypyc/test/test_irbuild.py
Prevent the coercion of things whose types are checked with isinstance
to other types - such coercion is not necessary and can lead to bugs.
Also, add test for avoiding coercion of isinstance() comparators.
Fixes mypyc/mypyc#811.
Ensured via compiling by hand and running the example given in mypyc/mypyc#811 has been fixed; added a test for the new code path that is generated.
> [mypyc] Don't coerce types checked with isinstance (#811)

- mypyc/irbuild/builder.py
- mypyc/irbuild/classdef.py
- mypyc/irbuild/statement.py
- mypyc/irbuild/util.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/run-misc.test
These need to be compiled as non-extension classes.
Also mypy has a special internal representation for these which doesn't
correspond to what's there at runtime and requires some hacks.
Fixes mypyc/mypyc#803.
> [mypyc] Support class-based TypedDict definitions

- docs/source/runtime_troubles.rst
This works for me locally, but the version on ReadTheDocs seems broken
> docs: fix RST markup

- mypyc/primitives/misc_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-isinstance.test
- mypyc/test-data/run-bools.test
Closes https://github.com/mypyc/mypyc/issues/821
For this piece of python code:
```py
def f(x: object) -> bool:
return isinstance(x, bool)
```
Previous version would generate:
```
def f(x):                                      
x, r0 :: object                            
r1 :: str                                  
r2 :: object                               
r3 :: int32                                
r4 :: bit                                  
r5 :: bool                                 
L0:                                            
r0 = builtins :: module                    
r1 = 'bool'                                
r2 = CPyObject_GetAttr(r0, r1)             
r3 = PyObject_IsInstance(x, r2)            
r4 = r3 >= 0 :: signed                     
r5 = truncate r3: int32 to …
```
> [mypyc] Add a primitive for loading bool type

- mypy/stubtest.py
> stubtest: check overloads are functions, don't early return

- mypyc/irbuild/expression.py
- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/specialize.py
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/run-sets.test
Closes https://github.com/mypyc/mypyc/issues/771 and https://github.com/python/mypy/pull/9707
Changes:
* Move code from `tranform_set_comprehension` to `translate_set_comprehension`
* Fix the unnecessary set creation (https://github.com/python/mypy/pull/9707#issuecomment-725549735)
Both generated IR test and functional test:
* Set built from iterators (`list` `tuple` `dict` `range`)
* Set built from nested generator
> [mypyc] Faster set creation with generator expression

- docs/source/error_code_list.rst
- mypy/fastparse.py
- mypy/fastparse2.py
- mypy/messages.py
- mypy/semanal.py
- test-data/unit/check-async-await.test
- test-data/unit/check-classes.test
- test-data/unit/check-columns.test
- test-data/unit/check-errorcodes.test
- test-data/unit/check-fastparse.test
- test-data/unit/check-incremental.test
- test-data/unit/check-inference.test
- test-data/unit/check-literal.test
- test-data/unit/check-modules.test
- test-data/unit/check-multiple-inheritance.test
- test-data/unit/check-optional.test
- test-data/unit/parse-errors.test
This pull request fixes issue reported in #7445  for `in async function`, `Cannot determine type of` and `syntax error in type comment` error messages
> Use double quotes errors 'in async function, 'Cannot determine type of' and 'syntax error in type comment'

- mypyc/codegen/emitfunc.py
The vtable index is only needed for when we actually go through a  vtable lookup. I don't believe this is actually a major performance improvement, but it should make it clearer what's important for each branch.
This was found while working through [this mypyc issue](https://github.com/mypyc/mypyc/issues/826)
> Only lookup vtable indices if needed for method call emits

- mypy/reachability.py
- test-data/unit/check-unreachable-code.test
Closes #10264.
Consider reversed order of operands when trying to compare version info. When reversed order is used, operator is reversed as well for correct comparison.
> Consider reversed operands order when comparing version info

- test-data/samples/generators.py
typshed mistakenly set itertools.count as a function while it is actually a class. Meaning that it returns a class instance and then this clashes with the filter assignment in the test.
I want to fix the typeshed side but the mypy test on THEIR repo fails because of this.
Mypy behaves the same but tests should be more in line with itertools actual typing.
> Fix Generators typeshed test

- docs/source/class_basics.rst
- docs/source/error_code_list.rst
- mypy/plugins/attrs.py
- mypy/plugins/dataclasses.py
- mypy/semanal.py
- test-data/unit/check-attr.test
- test-data/unit/check-columns.test
- test-data/unit/check-dataclasses.test
- test-data/unit/check-errorcodes.test
- test-data/unit/check-flags.test
- test-data/unit/check-incomplete-fixture.test
- test-data/unit/check-incremental.test
- test-data/unit/check-modules-case.test
- test-data/unit/check-modules.test
- test-data/unit/check-newsemanal.test
- test-data/unit/fine-grained-blockers.test
- test-data/unit/fine-grained-cycles.test
- test-data/unit/fine-grained-follow-imports.test
- test-data/unit/fine-grained-modules.test
- test-data/unit/fine-grained.test
- test-data/unit/pep561.test
- test-data/unit/semanal-errors.test
- test-data/unit/semanal-modules.test
This pull request fixes issue reported in #7445  for `dont mix` and `has no attributes` error messages
> Use double quotes errors in 'dont mix' and 'has no attributes'

- mypy/checker.py
- test-data/unit/check-isinstance.test
Fixes #4445
This makes mypy use expressions like `type(x) == T` during type narrowing similar to how it already does for `isinstance(x, T)`.
This also adds support for using `type(x) is T`, as well as checking the types of multiple variables at the same time, like `type(x) == type(y) == T`.
This doesn't do any type narrowing when multiple literal types are present in the comparison, such as in `type(x) == int == str` or `type(x) == int == int`. Expressions of that kind should always be False if those literal types aren't all the same, and are relatively pointless if all of the literal types are the same, so I think it's fine not supporting those. I can try adding support for the case when those literal types are the same if necessary.
I added several tests to make sure that mypy was …
> Use type(x) == T for type narrowing

- mypy/checker.py
- test-data/unit/check-typeguard.test
Closes #9928.
Issue an error about incompatible signature when trying to override typeguard method with non-typeguard one.
> Issue an error when overriding typeguard with non-typeguard in subclass

- mypy/meet.py
- test-data/unit/check-expressions.test
Closes #8296.
Check if types are AnyType instances after simplifying them (lines 167-170).
> Check for AnyType after simplifying

- docs/source/final_attrs.rst
There were several things to imporve in `Final` docs:
1. For some reason it was `ID: Final[float] = 1`, while `1` is clearly `int`
2. There was also a quite misleading phrase about `ID: Final = 1` being `int` and not `Literal[1]`
> Fixes Final docs

- .github/workflows/test.yml
- .github/workflows/test_stubgenc.yml
I have removed some infrastructure code that checked-out non-existent `git submodules`, I have also removed empty `.gitmodules` file, because it was a bit confusing (people tend to have it when there's something inside). I was pretty sure that `mypy` still uses `typeshed` submodule and I was really confused to see that it is empty. 😕 
Now, it is plain simple again.
Related https://github.com/python/mypy/commit/ba037888eccd0f63e193d0fefd8f4e9265b8e3d3
Related https://github.com/python/mypy/pull/9973
Related https://github.com/python/mypy/issues/9971
> Removes git-submodules artifacts

- docs/source/error_code_list.rst
- mypy/semanal.py
- mypy/test/teststubtest.py
- test-data/unit/check-attr.test
- test-data/unit/check-class-namedtuple.test
- test-data/unit/check-classes.test
- test-data/unit/check-dataclasses.test
- test-data/unit/check-errorcodes.test
- test-data/unit/check-functions.test
- test-data/unit/check-incremental.test
- test-data/unit/check-modules.test
- test-data/unit/check-newsemanal.test
- test-data/unit/check-newsyntax.test
- test-data/unit/check-newtype.test
- test-data/unit/check-overloading.test
- test-data/unit/check-python38.test
- test-data/unit/check-redefine.test
- test-data/unit/check-semanal-error.test
- test-data/unit/check-statements.test
- test-data/unit/check-unsupported.test
- test-data/unit/fine-grained.test
- test-data/unit/semanal-errors.test
This pull request fixes issue reported in #7445   for `already defined`, `is nonlocal and global`, `No binding for nonlocal` and `is already defined in local` error messages
> Use double quotes errors in `already defined`, `is nonlocal and global`, `No binding for nonlocal` and `is already defined in local`

- docs/source/metaclasses.rst
- mypy/semanal.py
- mypyc/irbuild/expression.py
- mypyc/test-data/commandline.test
- mypyc/test-data/exceptions.test
- mypyc/test-data/refcount.test
- mypyc/test-data/run-primitives.test
- mypyc/transform/uninit.py
- test-data/unit/check-classes.test
- test-data/unit/check-newsemanal.test
- test-data/unit/check-python2.test
- test-data/unit/fine-grained.test
- test-data/unit/semanal-errors.test
This pull request fixes issue reported in #7445 for Metaclass related errors `Inconsistent metaclass structure`, `Invalid metaclass `, and `Metaclasses not inheriting`
Also covers error `referenced before assignment`
> Use double quotes in Metaclass related errors

- mypy/nodes.py
- mypy/semanal.py
- test-data/unit/check-fastparse.test
- test-data/unit/check-functions.test
- test-data/unit/check-modules.test
- test-data/unit/parse-python2.test
This pull request fixes issue reported in #7445 for Metaclass related errors `Duplicate argument` and `Cannot assign multiple modules`
> Use double quotes in errors `Duplicate argument` and `Cannot assign multiple modules`

- .travis.yml
Python 3.5 always fails in CI these days. So a) it's annoying and a bad contributor experience, b) we're effectively not testing against Python 3.5 anyway
Linking https://github.com/python/mypy/issues/9950
> Stop running Python 3.5 in CI

- mypyc/doc/using_type_annotations.rst
Changed the return type annotation for `__init__` from `int` to `None`
In one of the examples in `mypyc`'s documentation, the constructor doesn't have a correct return type
```python
class Point:
def __init__(self, x: int, y: int) -> int:
...
```
I have changed it to `None` (according to [`mypy`'s documentation](https://mypy.readthedocs.io/en/stable/class_basics.html#annotating-init-methods) for example)
No particular test plan, it is a simple typo fix in the documentation.
> Fix type annotations in a documentation example

- mypy/messages.py
- test-data/unit/check-errorcodes.test
- test-data/unit/check-typeddict.test
- test-data/unit/pythoneval.test
This pull request fixes issue reported in #7445 for  TypeDict Key related errors `Extra key`, `Missing key`, `Expected key` and `Unexpected key`.
> Use double quotes in errors related to TypeDict Keys

- mypy/messages.py
- test-data/unit/check-typeddict.test
Added a section to the incompatible_argument function in mypy.messages that is executed when trying to add an incompatible type to a TypedDict. Required adding some imports from mypy.nodes to allow for the isinstance to work.
Fixes #10253 
Verified changes with the sample code provided in the issue as well as some other sample TypedDict implementations, below.
```
Foo = TypedDict('Foo', {'a': int})
blah: Foo = {'a': 4}
blah['a'] = ["r", 3]
Foo = TypedDict('Foo', {'a': str})
blah: Foo = {'a': 'lol'}
blah['a'] = 1
```
Also modified the `testCannotSetItemOfTypedDictWithIncompatibleValueType` test to check for the new error message.
> TypedDict incompatible type message more understandable

- docs/source/error_code_list.rst
- mypy/semanal.py
- mypy/semanal_newtype.py
- mypy/semanal_typeddict.py
- test-data/unit/check-classes.test
- test-data/unit/check-errorcodes.test
- test-data/unit/check-incremental.test
- test-data/unit/check-namedtuple.test
- test-data/unit/check-newsemanal.test
- test-data/unit/check-newtype.test
- test-data/unit/check-redefine.test
- test-data/unit/check-typeddict.test
- test-data/unit/semanal-errors.test
This pull request fixes issue reported in #7445 for errors related to `NewType`, `TypeVar`, `namedTuple` and `TypedDict`
> Use double quotes in errors related to NewType, TypeVar, namedTuple and TypedDict

- mypy_self_check.ini
Using obsolete Python 3.5 breaks typeshed's execution of mypy's self
check, as typeshed does not support Python 3.5 anymore.
Cf. python/typeshed#5242
> Use Python 3.9 for mypy self check

- mypy/plugins/dataclasses.py
- test-data/unit/check-dataclasses.test
At runtime, the callable properties of dataclasses are handled in the
way one would expect: they are not passed a `self` argument.  Mypy,
however, just sees them as callable class attributes and generates
errors about missing arguments.  This is a special case of what is
discussed in #708.  I donʼt have a general solution for that problem,
but for dataclasses, I can fix it by automatically converting the
callable entries in a data class into (settable) properties.  That makes
them work properly via-a-vis the typechecker.
Added unit tests which verify:
- callable dataclass properties no longer generate mypy errors about arity mismatches
- neither as class init arguments
- nor via property assignment
- nor when calling a property on an instance
- callable …
> Extend the dataclass plugin to deal with callable properties

- mypy/stubtest.py
- mypy/test/teststubtest.py
Make it clearer that we didn't actually run the core stubtest logic
> stubtest: improve build error messages

- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/specialize.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/list_ops.c
- mypyc/lib-rt/str_ops.c
- mypyc/lib-rt/tuple_ops.c
- mypyc/primitives/list_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/run-lists.test
Closes https://github.com/mypyc/mypyc/issues/473
* Reconstruct `tuple_creation_from_generator_helper` to `preallocate_space_helper`
* Rewrite `new_tuple_with_length`. Now we need only to pass in length.
* Add new primitive for list initialization.
* Support faster list comprehension in some simple situations.
> [mypyc] Pre-allocate space in list comprehensions

- mypy/checker.py
This changes the documentation style for the arguments to `find_type_equals_check` to be closer to what the rest of the code base is using, as mentioned by @JukkaL at https://github.com/python/mypy/pull/10284#discussion_r611574539.
> Fix argument documentation style in find_type_equals_check

- mypy/semanal.py
- test-data/unit/check-modules.test
Propagate the value of `__all__` from the imported module.
Fixes #10381.
> Fix re-exporting __all__ in a stub file

- mypy/typeops.py
- test-data/unit/check-python38.test
This fixes `make_simplified_union` if multiple instances of the same type but with different `last_known_value`s are passed to it.
Previously it would falsely keep the `last_known_value` of the first occurrence:
```python
make_simplified_union([Literal[1]?, Literal[2]?])   # Results in Literal[1]?
```
I'm not sure if this can currently actually occur at runtime, but I ran into this problem while developing #10191 and decided to submit it as a separate PR, as it's not directly related to #10191.
More specifically I need it for match statements such as
```python
match m:
case 1 | 2 as num:
reveal_type(num)  # Union[Literal[1]?, Literal[2]?]
```
Note that I need to use instances with last known value and can't use LiteralType as that would prevent changing the value of `num`.
With this …
> Fix make_simplified_union for instances with last_known_value

- mypy/subtypes.py
- mypy/typeops.py
- test-data/unit/check-enum.test
For example, consider this enum:
```
class E(Enum):
A = 1
B = 1
```
This PR makes `E` compatible with `Literal[E.A, E.B]`.
Also fix mutation of the argument list in
`try_contracting_literals_in_union`.
This fixes some regressions introduced in #9097.
> Make enum type compatible with union of all enum item literals

- docs/source/running_mypy.rst
- mypy/modulefinder.py
- test-data/unit/check-modules.test
When using `mypy_path` or `MYPYPATH`, allow storing Python 2 only stubs and
source files under the `@python2` subdirectory of search path entries. This is
only used when type checking in Python 2 mode.
Closes #10391.
> First look into @python2 subdirectory of search path items

- mypy/test/teststubtest.py
I couldn't track down the exact change that caused this test to fail, but python now stores the full path to the module in `test_module.bad.__code__.co_filename` instead of just the filename, despite the file being in the current working directory.
Because the working directory is unknown where the output is actually checked we just remove it from the output. This only affects tests.
> Fixed a teststubtest test failing in python 3.10

- mypy/modulefinder.py
- mypy/stubtest.py
This implements python/typeshed#5304.
I verified this manually with the following test script:
```python
import datetime
```
And running mypy using Python 3.9 in the following situations:
| `VERSIONS` file | mypy parameters | expected result |
| ---------------------- | ----------------------- | --------------------- |
| 2.7                      | none                     | passes               |
| 2.7-3.10              | none                     | passes               |
| 2.7-3.9                | none                     | passes               |
| 2.7-3.8                | none                     | cannot find stub |
| 2.7                      | `--python-version=3.8` | passes       |
| 2.7-3.9                | `--python-version=3.8` | passes        |
| 2.7-3.8                | …
> Support max version marker of stdlib typeshed modules

- mypy/test/data.py
- test-data/unit/check-errorcodes.test
- test-data/unit/cmdline.test
- test-data/unit/fine-grained-blockers.test
- test-data/unit/fine-grained-suggest.test
- test-data/unit/parse.test
- test-data/unit/semanal-errors.test
- test-data/unit/semanal-statements.test
Python 3.10 changes a bunch of parser error messages. This commit introduces the version>= argument to [out] sections of tests, which allows testing against the new messages on newer python versions.
[out] sections are overwritten by other [out] sections following them.
I also thought about supporting other comparisons such as `<`, `==` and others, while not having later out sections overwrite earlier out sections, but decided on this approach for simplicity.
This was tested on `Python 3.10.0a7+ (heads/master:0cad068, Apr 30 2021, 14:45:23)` (shortly before 3.10.0b1). Note that Travis CI nighly is still stuck on  3.10.0a5+.
> Fix a bunch of tests broken by python 3.10

- docs/source/error_code_list.rst
- mypy/checkexpr.py
- mypy/messages.py
- test-data/unit/check-errorcodes.test
Previously this was inconsistent, and some TypedDict operations used
the 'misc' error code, which is dangerous to ignore. TypedDict related
errors seem to be some of most commonly ignored error with the 'misc'
error code.
> Use typeddict-item error code for more errors

- mypy/plugins/enums.py
- test-data/unit/check-enum.test
- test-data/unit/lib-stub/enum.pyi
If the enum value initializer has a NewType type, it should be
reflected in the type of the `value` attribute. It was broken because
the special casing for `__new__` introduced in #10057 didn't consider
the `__new__` in `IntEnum` as special.
Fixes #10411.
> Fix inference of IntEnum value attribute type

- mypy/checkexpr.py
- test-data/unit/check-narrowing.test
A union of enum literals was merged back to the enum type, which broke
type narrowing. Disable merging in this case to work around the
issue.
The fix feels a bit ad hoc. However, I'd rather not spend a lot of
time figuring out a general fix, since this seems like a pretty rare
edge case.
Fixes #10414.
> Fix narrowing down TypedDict unions with enum literal types

- mypy/plugins/functools.py
Even if the plugin doesn't work yet, generating an error is a
regression. The decorator used to silently do nothing in earlier
mypy versions.
Not having the plugin doesn't complelety prevent type checking code
using `total_ordering`.
> Don't report error when using total_ordering in Python 2 mode

- test-data/unit/check-narrowing.test
Class-based TypedDict syntax requires Python 3.6+.
> Fix TypedDict test case on Python 3.5

- mypy/plugins/enums.py
The enum stubs for Python 2 are slightly different from Python 3.
The fix in #10412 didn't quite work in Python 2 mode, since `IntEnum`
doesn't define `__new__`, and the `__new__` from `builtins.int` is
found instead. Work around this by skipping any `__new__` methods
found in built-in types.
I gave up trying to write a test case for this. It's tricky because
`enum` is in Python 3 stdlib but not in Python 2 stdlib.
> Fix inference of IntEnum value attribute type (Python 2)

- docs/source/kinds_of_types.rst
This is a documentation typo fix.
> Fix typo “a cases” in kinds_of_types.rst

- docs/source/config_file.rst
As per https://github.com/python/mypy/issues/9940, a `[mypy]` section is now required in `setup.cfg` in order for config to be loaded from that file. However, the docs are out of date.
This PR removes that out of date clause.
I'm not sure if this fixes the linked issue, but I know that removing this clause would have saved me a few hours of head banging - and therefore would save others too.
GitHub renders the change OK, so I'm assuming sphinx will also build it fine.
> Remove invalid note in docs: setup.cfg *does* need [mypy] section

- mypy/modulefinder.py
- test-data/unit/python2eval.test
Previously we could find stubs both in `stdlib/@python2` and
`stdlib` for the same top-level package, which could result in a
mix of Python 2 and 3 stubs being used.
Now if we find stubs for a package in the `@python2` directory, we
skip the parent directory.
Fixes #10421.
> Don't use Python 3 stdlib stubs in Python 2 mode

- mypy/meet.py
- test-data/unit/check-narrowing.test
We could narrow `Type[T]` to `<nothing>` when tested against a
metaclass, which is not useful. Now we don't do any narrowing
in this case.
Fixes #10423.
> Don't narrow Type[X] with a metaclass

- mypy/test/testtypes.py
- mypy/test/typefixture.py
This commit adds tests for `make_simplified_union`, including the new functionality added in #10373 
The only thing not tested is contracting enum literals back to the enum type, as `TypeFixture` currently doesn't support enum types. I might add that later.
> Add tests for make_simplified_union

- mypy/semanal.py
- test-data/unit/check-functools.test
- test-data/unit/fixtures/property.pyi
Add support for `functools.cached_property` decorator. https://docs.python.org/3/library/functools.html#functools.cached_property
Closes #8913
Closes https://github.com/python/typeshed/issues/3963
I added a new test case. Additionally, I used this snipped to verify mypy during development of the patch
```py
from functools import cached_property
class Parent:
@property
def prop(self) -> int:
...
class Child(Parent):
def __init__(self):
self._prop = 4
@cached_property
def prop(self) -> int:
print("Calc value ..")
return self._prop ** 2
c = Child()
print(c.prop)
print(c.prop)  # Returns cached value
c.prop = 24  # Overwrite cached value
print(c.prop)
c.prop = "Hello World"  # incompatiable types
print(c.prop)
```
> Add support for ``functools.cached_property``

- mypy/nodes.py
- test-data/unit/check-incremental.test
The `from_module_getattr` attribute of `Var` was not serialized, so
subsequent runs didn't know about this being from `__getattr__` and
tried to create a cross-ref to the definition which doesn't actually
exist, resulting in a crash.
Fixes #10429.
> Fix crash related to module-level __getattr__ in incremental mode

- mypy/semanal.py
- mypy/semanal_enum.py
- mypy/semanal_namedtuple.py
- mypy/semanal_newtype.py
- mypy/semanal_shared.py
- mypy/semanal_typeddict.py
- test-data/unit/check-incremental.test
The name of the nested tuple type was inconsistent. Sometimes if was stored 
using the full name in the module symbol table.
Also improve the internal API for creating classes to be less error-prone.
Work on #7281.
> Fix crash with nested NamedTuple in incremental mode

- mypy/nodes.py
- mypy/semanal.py
- mypy/typeanal.py
- test-data/unit/check-incremental.test
Don't create `TypeAliasType` for aliases defined within functions,
since the target can't be looked up using the full name, as we drop
function symbol tables after we've finished processing them.
Fixes #7281.
> Fix crash with type alias inside __init__ in incremental mode

- mypyc/lib-rt/CPy.h
- mypyc/test/test_cheader.py
Also add test that will find things missing in headers, as long as they follow
our naming convention (`CPy*`).
> [mypyc] Add missing header declaration for CPyStr_IsTrue

- docs/source/final_attrs.rst
Spotted in https://mypy.readthedocs.io/en/stable/final_attrs.html
> Fix “they is” typo in Final docs

- mypy/join.py
- test-data/unit/check-tuples.test
Fixes #10400 
This PR prevents passing in a `TypeJoinVisitor` to `PlaceholderType#accept` (which only expects `SyntheticTypeVisitor`s).
There's probably a better way, as `PlaceholderType` claims "After semantic analysis, no placeholder types must exist," yet this happens after semantic analysis (see line 1552 in the crash traceback)... So, the better way would involve not getting to this `join_types` function in the first place, but I'm not sure where to put a check.
~~I'm not quite sure how to add tests for this (especially since there's no `testjoin.py` in `mypy/test`)...~~ ~~(I think I figured this out, I'll add them eventually)~~ Added a regression test. Additionally, I verified this works locally with the reproduction code from the issue linked:
```
$ mypy repro.py
repro.py:7: error: …
```
> Fix unresolved reference + tuples crashing

- mypy/checkexpr.py
- test-data/unit/check-flags.test
Fixes #10454
The logic here is similar to what we do in visit_call_expr_inner
> Infer unreachability for await no_return()

- mypy/build.py
- mypy/checker.py
- mypy/checkexpr.py
Fix few typos in the comments.
No testing required. Only changes comments.
> Fix typos in comments.

- mypy/modulefinder.py
I plan to use inline comments in the VERSIONS file (for comments about single packages like `_typeshed`). This PR ignores those as well as comments on their own line.
> Allow inline comments in VERSIONS

- .github/workflows/mypy_primer.yml
Port https://github.com/python/typeshed/pull/5452
We didn't have the global permission set, so maybe it wasn't broken, but
explicitly setting permissions seems like a good thing
> mypy_primer: fix comment permissions

- mypy/errors.py
- mypy/messages.py
- mypy/semanal.py
- mypy/typeanal.py
- test-data/unit/check-expressions.test
- test-data/unit/check-generic-alias.test
- test-data/unit/check-ignore.test
- test-data/unit/check-incremental.test
- test-data/unit/check-narrowing.test
- test-data/unit/check-python38.test
- test-data/unit/check-semanal-error.test
- test-data/unit/check-typeddict.test
- test-data/unit/check-warnings.test
- test-data/unit/errorstream.test
- test-data/unit/fine-grained-blockers.test
- test-data/unit/semanal-errors.test
- test-data/unit/semanal-types.test
This pull request fixes issue reported in #7445 for errors related to `TypedDict key must be a string literal`, `Unexpected "..."`, `used with a non-method`, `cast and divmod expectes 2 arguments`, `is not a valid base class`, `unused "type: ignore" comment`, `outside loop and outside function `
> Use double quotes in errors

- mypy/modulefinder.py
This enables custom mypy configurations where only Python 3 is supported.
> Allow running mypy if Python 2 typeshed stubs aren't installed

- mypy/semanal.py
- test-data/unit/check-final.test
Fixes #10477
Do not allow to use Final and ClassVar at same time.
Code bellow:
```python
from typing import Final, ClassVar
class A:
a: Final[ClassVar[int]]
```
After this PR will produce an error:
```
error: Variable should not be annotated with both ClassVar and Final
```
But currently, it will not raise any error.
> Do not allow to use Final and ClassVar at same time

- mypy/types.py
This came up in python/typeshed#5473: mypy started crashing when
I made a function return TypeGuard[Type[Any]]. I wasn't able to
reproduce this locally so far in a standalone file, but verified that removing the
assertion fixes the crash.
> Remove assertion from TypeGuard serialization

- mypy/build.py
- mypy/modulefinder.py
- test-data/unit/fine-grained-modules.test
It doesn't work with mypy daemon.
Fixes #10015.
> Don't suggest --install-types in daemon mode

- docs/source/running_mypy.rst
- mypy/build.py
- mypy/semanal.py
- test-data/unit/README.md
- test-data/unit/check-flags.test
- test-data/unit/check-incremental.test
- test-data/unit/check-modules.test
- test-data/unit/cmdline.test
- test-data/unit/daemon.test
- test-data/unit/fine-grained-modules.test
- test-data/unit/parse-errors.test
- test-data/unit/semanal-errors.test
This pull request fixes issue reported in #7445 for errors related to `Inconsistent use of * in function`, `is a type variable and only valid in type context`, `Import of x ignored`.
Also updated unit test data readme file(test-data/unit/README.md) for error `Name "zzz" already defined`
> Double quotes in errors "Inconsistent use of * in function", "is a type variable and only valid in type context" and "Import of x ignored"

- mypy/constraints.py
- mypy/erasetype.py
- mypy/expandtype.py
- mypy/fixup.py
- mypy/indirection.py
- mypy/join.py
- mypy/meet.py
- mypy/sametypes.py
- mypy/server/astdiff.py
- mypy/server/astmerge.py
- mypy/server/deps.py
- mypy/subtypes.py
- mypy/type_visitor.py
- mypy/typeanal.py
- mypy/types.py
- mypy/typetraverser.py
- test-data/unit/check-typeguard.test
In python/typeshed#5473, I tried to switch a number of `inspect` functions to use the new `TypeGuard` functionality. Unfortunately, mypy-primer found a number of crashes in third-party libraries in places where a TypeGuard function was ANDed together with some other check. Examples:
- https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/util/inspect.py#L252
- https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/ext/coverage.py#L212
- https://github.com/streamlit/streamlit/blob/develop/lib/streamlit/elements/doc_string.py#L105
The problems trace back to the decision in #9865 to make TypeGuardType not inherit from ProperType: in various conditions that are more complicated than a simple `if` check, mypy wants everything to become a ProperType. Therefore, to fix the crashes I had to make …
> Fix crash on TypeGuard plus "and"

- mypy/stubgenc.py
https://github.com/python/typeshed/pull/5516 makes changes to getattr
that would introduce type errors here.
`infer_sig_from_docstring` will return False if `docstr` is None, so the code itself is fine.
> stubgenc: type check for getattr changes

- mypy/build.py
- mypy/checkstrformat.py
- mypy/fastparse2.py
- mypy/message_registry.py
- mypy/messages.py
- mypy/plugins/attrs.py
- mypy/semanal.py
- mypy/semanal_enum.py
- test-data/unit/check-async-await.test
- test-data/unit/check-attr.test
- test-data/unit/check-custom-plugin.test
- test-data/unit/check-enum.test
- test-data/unit/check-expressions.test
- test-data/unit/check-flags.test
- test-data/unit/check-python2.test
This pull request fixes issue reported in #7445 for below errors:
1. does not explicitly export attribute
2. Unsupported format character
3. key not found in mapping
4. Format character support
5. Unexpected keyword argument
6. plugin related errors
7. return with value in async
8. cant pass both
9. not supported 
> Double quotes in errors messages

- mypyc/irbuild/specialize.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/run-lists.test
* Move simple `tuple` and `list` creation to new functions. Each specializer only focus on one situation now.
* Add `int.__pow__` in `test-data/fixture`
This change should pass all existing tests.
> [mypyc] Modify specializers and add int.__pow__ in test-data/fixture

- mypyc/ir/rtypes.py
- mypyc/test/test_analysis.py
- mypyc/test/test_exceptions.py
- mypyc/test/test_irbuild.py
- mypyc/test/test_refcount.py
- mypyc/test/testutil.py
relates https://github.com/mypyc/mypyc/issues/776
This is a super quick workaround. So far the issue mostly (if not completely) occurs in `c_pyssize_t` so making this rtype emits `native_int` would solve the issue. As a result, the `replace_native_int` pass in IR test is now removed.
> [mypyc] Emit native_int instead of int64/int32 in IR test output 

- docs/source/command_line.rst
Resolves #10538 by adding security documentation.
> Resolves #10538; add security documentation for --install-types

- mypy/build.py
- mypy/modulefinder.py
Since this code path involves mypy recommending installation of a stub
package, I thought I'd rename the enum to make it slightly clearer
that this should only be triggered for packages we know to be good.
Linking #10538
> rename STUBS_NOT_INSTALLED to APPROVED_STUBS_NOT_INSTALLED

- mypy/nodes.py
#10542 had a vague error come up due to a PlaceholderNode that did not get replaced. This PR simply adds the full name of the node so that these can be better traced back.
The error was:
```
...
assert not isinstance(self.node, PlaceholderNode)
AssertionError
```
Will now be slightly more helpful:
```
...
assert not isinstance(self.node, PlaceholderNode), '%s' % fullname
AssertionError: spacy.ml.models.multi_task.Doc
```
There's the possibility that something bigger needs to happen here (why is it still a PlaceholderNode?), but this was enough to help me to figure out how to move #10542 forward.
Manually tested with the code provided by @ZeeD `from spacy import load` ran through mypy with `--strict`
> Resolves #10542 Add fullname of node that is still a PlaceholderNode when assertion fails

- docs/source/config_file.rst
One example references `[[tools.mypy.overrides]]` when all other examples reference `[[tool.mypy.overrides]]`.  I'm guessing the odd one out is incorrect.
> Fix typo in config_file.rst

- mypy/state.py
- mypy/test/helpers.py
- mypy/test/testsubtypes.py
- mypy/test/testtypes.py
- mypyc/test/testutil.py
- Context managers used in tests should do their cleanups in `finally` so that tests don't bleed into each other and cause unrelated tests to fail (and send us down a wild goose chase)
- Add `__tracebackhide__` per https://docs.pytest.org/en/6.2.x/example/simple.html#writing-well-integrated-assertion-helpers to allow failed test output to have less "noise"
> Improve pytest quality of life

- mypy/checker.py
- test-data/unit/check-unreachable-code.test
Makes `42 or False` result in `Error: Right operand of "or" is never evaluated` when invoked with [--warn-unreachable](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unreachable).
> Unreachable expressions: treat non-zero ints as truthy

- mypy/build.py
- mypy/options.py
- test-data/unit/check-modules.test
It has to be specified as a per-module option, if the library used
to have bundled stubs. This way mypy won't silently start ignoring
these missing stubs.
This makes `ignore_missing_imports` special by making it work a bit
differently, depending on whether it's set globally or per module.
The new behavior is less surprising. This makes it possible to ignore
arbitrary missing third-party stub packages, even those which used to
have bundled stubs.
Fixes #10283.
Originally implemented by @TheCleric in #10283. This is somewhat 
simpler alternative implementation which is easier to reason about and
may perform better in some cases of very large configs.
> Make ignore_missing_imports work for libs which had bundled stubs

- mypyc/irbuild/statement.py
Fixes https://github.com/mypyc/mypyc/issues/842
Re ran the actions and nothing failed, and it solves the issues with `importlib.util.resolve_name` failing.
Before:
```sh
(venv) James@Jamess-Air python-betterproto % mypyc src/betterproto/*.py
File "/Users/James/PycharmProjects/python-betterproto/build/setup.py", line 5, in <module>
ext_modules=mypycify(['src/betterproto/__init__.py', 'src/betterproto/_types.py', 'src/betterproto/_version.py', 'src/betterproto/casing.py'], opt_level="3"),
File "/Users/James/PycharmProjects/python-betterproto/venv/lib/python3.9/site-packages/mypyc/build.py", line 487, in mypycify
groups, group_cfilenames = mypyc_build(
File "/Users/James/PycharmProjects/python-betterproto/venv/lib/python3.9/site-packages/mypyc/build.py", …
```
> [mypyc] Fix relative imports in `__init__.py`s

- mypyc/irbuild/for_helpers.py
- mypyc/test-data/run-misc.test
This could result in a crash if the second evaluation results
in a shorter list, such as in this example (besides being incorrect
overall):
```
a = [s for s in f.readlines()]
```
`f.readlines()` was called twice, resulting in an empty list on
the second call. This caused the list object constructed in the
comprehension to have a NULL item, which is invalid.
This fixes `mypy --install-types` in compiled mode.
Fixes #10596.
> [mypyc] Fix evaluation of iterable in list comprehension twice

- mypyc/codegen/emitmodule.py
- mypyc/irbuild/context.py
- mypyc/irbuild/expression.py
- mypyc/irbuild/function.py
- mypyc/irbuild/statement.py
- mypyc/test-data/commandline.test
And avoid triggering mypy assertion failures on errors.
Fixes mypyc/mypyc#866.
Opened mypyc/mypyc#868 to track the async feature work.
> [mypyc] Produce unimplemented errors on unsupported async features

- mypyc/irbuild/builder.py
- mypyc/irbuild/statement.py
- mypyc/primitives/misc_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/run-imports.test
Fixes mypyc/mypyc#851
This fixes a bug where code compiled with mypyc would crash on from imports (`from x import y`) if:
- y is a module
- mypy doesn't know that y is a module (due to an ignore_missing_imports configuration option or something else)
The bug was caused by using getattr to import modules (i.e. `y = getattr(x, 'y')`) and changing this to `import x.y as y` when it can determine that y is a module. This doesn't work when we don't know that y is a module.
I changed the from import handling to use something similar to the method shown in the [`__import__` docs](https://docs.python.org/3/library/functions.html#__import__). I also removed the special casing of from imports for modules (`from x import y` where y is a module) mentioned earlier, because these changes make that …
> [mypyc] Avoid crash when importing unknown module with from import

- mypy/build.py
- mypy/modulefinder.py
- mypy/stubinfo.py
- mypy/util.py
- test-data/unit/check-modules.test
Previously we used `google` as the package prefix for `google.protobuf`.
That wasn't correct, since there are other, unrelated packages in the Google
namespace, such as `google.cloud`.
This fixes the prefix to to be `google.protobuf`.
Fixes #10601.
> Fix confusion between stubs for google.protobuf and google.cloud

- docs/source/config_file.rst
The list of locations in the second paragraph of `docs/source/config_file.rst` is missing `pyproject.toml` and the user config files.
This change refers to the complete list in the previous paragraph instead of listing all locations again.
No tests needed, as no code was changed. See https://github.com/python/mypy/blob/master/mypy/defaults.py for correctness.
> Remove misleading list of default locations

- mypy/main.py
- mypy/options.py
- test-data/unit/cmdline.test
It also doesn't show errors, making it useful in CI jobs.
Example:
```
$ mypy --install-types --non-interactive -c 'import click'
Installing missing stub packages:
/Users/jukka/venv/mypy/bin/python3 -m pip install types-click
Collecting types-click
Using cached types_click-7.1.0-py2.py3-none-any.whl (13 kB)
Installing collected packages: types-click
Successfully installed types-click-7.1.0
```
Work on #10600.
> Support --install-types --non-interactive that doesn't prompt

- mypy/stubgen.py
- test-data/unit/stubgen.test
Use `typing.NamedTuple` in stubgen, instead of `collections.namedtuple`.
I modified the existing tests and added another test for an empty namedtuple, to ensure that `Any` is not imported unnecessarily.
> stubgen: Use NamedTuple class syntax

- mypy/stubgen.py
- test-data/unit/stubgen.test
Previously, the generation of a variable initialized (`= ...`) was
inconsistent between top-level and class-level variables. Since the
initializer has no function in stubs, stubgen will now never generate
it.
Existing unit tests were updated.
> stubgen: never generate variable initializer

- mypy/test/data.py
- pytest.ini
Closes #10604
This adds support for marking test cases in *.test files as [xfails](https://docs.pytest.org/en/latest/how-to/skipping.html#xfail-mark-test-functions-as-expected-to-fail) by adding `-xfail` to the end of the test case name.
I wasn't sure if I should turn on [`xfail_strict`](https://docs.pytest.org/en/latest/how-to/skipping.html#strict-parameter) in the pytest config. Turning that on would probably make it less likely that we would end up with tests that are still marked as xfails long after they're fixed, but it might be annoying have the test suite fail because a test marked as xfail started passing.
I couldn't find a way to write tests for this change, so I changed some existing tests by marking them as xfail and made sure they were treated as xfails when they failed, and …
> Add support for using xfail in test cases

- mypyc/codegen/emitmodule.py
This frees everything created in the generated initialization function so that we don't leak memory in the case of an error during initialization, as mentioned in https://github.com/python/mypy/pull/10586#pullrequestreview-678090095.
> [mypyc] Add cleanup at end of init function

- mypy/checkmember.py
- test-data/unit/check-dataclasses.test
- test-data/unit/check-functions.test
- test-data/unit/check-functools.test
- test-data/unit/check-selftype.test
Fixes #708 and Fixes #5485
Prevent handling as bounded method of callable members declared as instance variables.
> Fix callable instance variable support

- mypyc/test-data/run-singledispatch.test
- mypyc/test/test_run.py
This adds some run tests to run-singledispatch.test for situations that are likely to be common or that seem like they would be edge cases that we don't handle correctly.
Most of these tests are commented out because mypyc doesn't properly support singledispatch yet, and the few that aren't commented out only work because they're written in a way that causes mypyc to use the standard library implementation of singledispatch.
There are some situations where I added tests that check whether mypyc sticks to what the standard library's implementation does, even though those situations are probably bugs that should probably be mypy errors. For example, `testTypeAnnotationsDisagreeWithRegisterArgument` checks whether mypyc uses the argument to register for dispatch instead of the type …
> [mypyc] Add mypyc run tests for singledispatch

- mypy/checkexpr.py
- mypy/nodes.py
- test-data/unit/check-unreachable-code.test
`ExpressionChecker.check_boolean_op` supports two potentially conflicting ways of determining whether an expression is always true/false: name-based checks from semantic analysis (e.g. `name in options.always_true`) and type narrowing in `TypeChecker.find_isinstance_check` (*). The two ways can be set to conflict, e.g.
```python
COMPILE_TIME_TRUE: None
```
In the above case, `COMPILE_TIME_TRUE` would be always true per semanal and always false per `find_isinstance_check`, which results in an assertion failure here:
https://github.com/python/mypy/blob/5eb4de443269b906d2e8b2292dbf472ce17d0e1f/mypy/checkexpr.py#L2828
and here:
https://github.com/python/mypy/blob/5eb4de443269b906d2e8b2292dbf472ce17d0e1f/mypy/checkexpr.py#L2832
This change reconciles the two, by prioritizing the semanal flags …
> check_boolean_op: clean up semanal/type-based reachability

- mypyc/irbuild/builder.py
- mypyc/irbuild/statement.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/misc_ops.c
- mypyc/primitives/misc_ops.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/run-imports.test
Fixes https://github.com/mypyc/mypyc/issues/707
> [mypyc] Raise ImportError instead of AttributeError when from-import fails

- mypy/stubinfo.py
pyopenssl's types package name was corrected in typeshed. It's now also available for Python 3.
> pyopenssl types package corrected

- mypy/test/testcheck.py
- test-data/unit/check-singledispatch.test
This adds mypy tests for singledispatch, most of which are either based on the use of singledispatch in stubtest.py or seem like they would be common errors. All of these tests are currently skipped because mypy unsurprisingly doesn't catch these errors yet due to the lack of singledispatch support.
I ended up adding some new error messages for some tests, but I'm not intending for those to be the final error messages that we actually end up using. I just wanted to put something for those errors as a stand-in that we can replace later if anyone has any other preferences.
> Add tests for singledispatch

- docs/source/runtime_troubles.rst
Postponed evaluation of annotations was deferred to 3.11 - update the docs.
Closes #10648
> Address #10648

- mypy/checker.py
- test-data/unit/check-redefine.test
- test-data/unit/check-unreachable-code.test
Fixes #9615, fixes #9682
Both issue reports hit the faulty cast on L2803. This changes the logic
so that that cast is actually always true. If not, we just end up doing
whatever the fallback else clause does; this resulted in behaviour that
matched what I expected.
After that, the #9682 hit another crash in checker.py, where var.node
was None instead of a Var. It seemed reasonable to just branch instead.
> Fix faulty casts in checker

- mypy/main.py
There are no tests since our test framework makes it tricky to
write tests for these kinds of scenarios. Tested manually.
Work on #10600.
> Improve error reporting when --install-types has no cache

- mypy/main.py
- test-data/unit/cmdline.test
If the first build finds missing stub packages, run the build a second
time after installing types. Only show errors from the final build.
Example output:
```
$ mypy --install-types --non-interactive t.py
Installing missing stub packages:
/Users/jukka/venv/mypy/bin/python3 -m pip install types-redis
Collecting types-redis
Using cached types_redis-3.5.2-py2.py3-none-any.whl (11 kB)
Installing collected packages: types-redis
Successfully installed types-redis-3.5.2
t.py:2: error: Unsupported operand types for + ("int" and "str")
```
Work on #10600.
> Run build a second time when using --install-types --non-interactive 

- test-data/unit/check-expressions.test
- test-data/unit/fixtures/bool.pyi
`testNonBooleanContainsReturnValue` is testing that `in` always evaluates as bool (per https://github.com/python/mypy/pull/5688).
This test worked due to fixture's lack of knowledge that `issubclass(bool, int)`. To more correctly test, let's use distinct types bool and str.
> Fix testNonBooleanContainsReturnValue

- test-data/unit/check-unreachable-code.test
- test-data/unit/lib-stub/builtins.pyi
It was indeed weird that `Union[builtins.bool, Literal[True]]` wasn't simplified by `make_simplified_union` to `builtins.bool`. This was simply because `builtins.bool` wasn't defined in test-data/unit/lib-stub/builtins.pyi.
It's important to keep fixtures nimble, but this is too much of a gotcha IMO not to have `bool` defined. (Also, I intend to define it in a follow-up PR anyway so it could have a `__bool__` method.)
> fix testSemanticAnalysisFalseButTypeNarrowingTrue

- mypy/stubinfo.py
Depends on python/typeshed#5669
> pkg_resources is now in types-setuptools

- mypy/binder.py
- test-data/unit/check-typeguard.test
This is a quick fix to unblock the 0.910 release.
The type guard type can be unrelated to the original type, so we
shouldn't join it. I'm not sure whether this is right from first
principles, but it seems to address the issue.
Fixes #10671.
> Fix crash with assignment to variable guarded with TypeGuard

- mypy/renaming.py
As title. Related to Guido’s coding style suggestion in #1184
Existing tests with `# flags: --allow-redefinition` should pass. No new test cases were added
> refactor: add contextmanager to VariableRenameVisitor

- mypy/checker.py
- test-data/unit/check-custom-plugin.test
- test-data/unit/plugins/method_in_decorator.py
Currently, when methods are used in decorators, instead of correctly calling `get_method_hook` with `'{module_name}.{class_name}.{method_name}'` (with `module_name`, `class_name`, and `method_name` filled in with their correct values), `get_function_hook` is called instead with `'{method_name} of {class_name}'`. This PR fixes this bug by calling `get_method_hook` correctly.
Technically, this may break some plugins if they relied on the fact that `get_function_hook` would be called on methods used in decorators, because with this PR those calls get moved to `get_method_hook`. I'm guessing that this is rare, but I don't know for sure if any plugins rely on that.
Currently, this only works when you access the method in the decorator itself, instead of assigning the method to a local …
> Call get_method_hook when methods are used in decorators

- mypy/build.py
- mypy/modulefinder.py
- test-data/unit/check-modules.test
If we encounter an import of a submodule of a package with installed
stubs, and the submodule doesn't exist, don't ask to install stubs
since that's not going to help. Also make it possible to ignore this
error using `--ignore-missing-imports`.
Work on #10645.
> Don't ask to install a stub package if stubs are installed

- mypy/checker.py
- test-data/unit/check-async-await.test
When using lvalue context to re-infer call to an overloaded function,
the inferred tuple type can switch to Any. Defensively accept this. It
probably means that an Any component in argument types causes ambiguity.
Fixes #10653.
> Fix crash when inferring multiple assignment with overloaded function

- misc/build_wheel.py
URL update in comment.
I think most of this script is covered by the new "config" mode coming in cibuildwheel 2.0 (probably in a few weeks); but that also only supports Python 3.6+, so 3.5 will need to be dropped before moving to 2.0.
Noticed this when adding https://github.com/mypyc/mypy_mypyc-wheels/pull/23
> docs: updating URL in comment

- mypy/stubtest.py
`SymbolTableNode.node` can be None, which means that we may accidentally end up passing None to `verify` for the first argument, despite the fact that `verify` doesn't have any implementations that allow for the dispatch type being None. This PR fixes that by making sure the dispatch type isn't None before calling `verify`.
This also should make it possible for mypy to type check after the introduction of the singledispatch plugin from #10694.
> Avoid passing None to verify in stubtest.py

- mypy/checkexpr.py
- mypy/plugin.py
This changes the `get_method_signature_hook` and `get_function_signature_hook` plugin hooks to let them return any `FunctionLike` type instead of limiting them to just `CallableType`.
This allows plugins to return `Overloaded` for the signature of a function, which is useful if there are multiple possible signatures for a specific function or method call, and the one that gets used is only determined at runtime. This situation came up when working on the singledispatch plugin from #10694.
> Allow plugin signature hooks to return FunctionLike

- mypy/stubtest.py
This changes the type of the first argument of `verify` to be a supertype of the dispatch types of all registered implementations, including the implementation for `Missing`.
This allows the singledispatch plugin from #10694 to type check stubtest.py, as the plugin requires that the dispatch type for all registered implementations is a subtype of the first argument of the main singledispatch function to make type checking calls to singledispatch functions easier.
> Make dispatch types of `verify` subtypes of `verify`'s first argument

- mypy/checkexpr.py
- test-data/unit/check-overloading.test
I believe this should help with some issues that come up with #10694.
> Try ignoring Anys in type object callables for purposes of overload ambiguity

- mypy/meet.py
- test-data/unit/check-narrowing.test
Fixes #10605 
This PR extends type narrowing by a type from a generic argument. This is achieved by handling a specific case while narrowing some type with `TypeVarType`: if the lower bound of that type and `upper_bound` of type variable is the same type as `upper_bound`, then the type can be narrowed to that type variable.
> Narrow type with typevar when the lower bound of its upper bound and that type is same

- mypy/plugins/common.py
- mypy/plugins/default.py
- mypy/plugins/singledispatch.py
- test-data/unit/check-singledispatch.test
This adds a singledispatch plugin to the default collection of plugins for mypy that type checks uses of singledispatch. The plugin is enough to get some of the tests in check-singledispatch.test to start working (with some modifications to correct some mistakes in the tests), so those tests get changed from xfails to regular tests.
This has a lot of limitations about what it can type check so far, including:
- no support for passing types as arguments to `register` - Currently the plugin only supports using type annotations, and will not do any type checking if there are any arguments to `register` other than the function to register.
- no support for singledispatchmethod
- no support for using `registry` or `dispatch`
In all of these cases, mypy should default to the typeshed definition …
> Add initial singledispatch typechecking support

- mypyc/irbuild/classdef.py
- mypyc/test-data/commandline.test
These only worked with the simplified stubs used in tests.
> [mypyc] Fix class-based named tuples

- mypy/main.py
- test-data/unit/check-incremental.test
dmypy requires local-partial-types, so without specifying it, we generate
a cache that is useless to dmypy.
Prompted by #10735.
Tested manually generating a cache for mypy and then checking it with dmypy.
> Make --cache-fine-grained imply --local-partial-types

- mypyc/irbuild/for_helpers.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/specialize.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/str_ops.c
- mypyc/primitives/dict_ops.py
- mypyc/primitives/str_ops.py
- mypyc/test-data/irbuild-str.test
- mypyc/test-data/irbuild-tuple.test
- mypyc/test-data/run-lists.test
- mypyc/test-data/run-tuples.test
Closes https://github.com/mypyc/mypyc/issues/835
* Add a branch for `str_rpimitive` in `builtin_len`
* Reduce redundant code
* Faster list/tuple built from str
* Add run tests for faster list/tuple built from str
* Modify one irbuild test. The original one is redundant.
> [mypyc] Add a special case for str_rprimitive in builder.builtin_len

- mypy/plugins/singledispatch.py
- test-data/unit/check-singledispatch.test
When calling a function that has been registered as an implementation for a singledispatch function, currently, mypy doesn't type check arguments to those functions when those functions are called directly (instead of through the main singledispatch function). This fixes that by preserving the type of the registered function even after the register decorator has been used.
I added a test that made sure that we report errors when using registered functions directly.
> Preserve types of functions registered with singledispatch

- mypyc/irbuild/builder.py
- mypyc/irbuild/context.py
- mypyc/irbuild/function.py
- mypyc/irbuild/prebuildvisitor.py
- mypyc/primitives/misc_ops.py
- mypyc/test-data/run-singledispatch.test
This PR adds initial support for compiling functions marked with singledispatch by generating IR that checks the type of the first argument and calls the correct implementation, falling back to the main singledispatch function if none of the registered implementations have a dispatch type that matches the argument.
Currently, this only supports both one-argument versions of `register` (passing a type as an argument to register or using type annotations), and only works if `register` is used as a decorator.
Several of the tests in run-singledispatch.test that were previously marked as xfail are now able to pass, so those are changed to regular tests.
> [mypyc] Add initial support for compiling singledispatch functions

- mypy/semanal.py
- mypy/typeanal.py
- test-data/unit/check-generic-alias.test
This fixes these issues:
* Allow variable-length `tuple` (`tuple[int, ...]`) in type aliases
* Allow generic built-in types (e.g. `list[int]`) in stubs in all Python versions
Fixes #9980. Fixes #10303. Fixes #10731.
> Fixes to generic builtin types

- mypyc/irbuild/specialize.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/str_ops.c
- mypyc/primitives/str_ops.py
- mypyc/test-data/run-strings.test
Closes https://github.com/mypyc/mypyc/issues/876
```py
@benchmark
def str_format_format_method() -> None:
a = []
tmp_str = "Foobar"
for i in range(1000):
for _ in range(5):
a.append('{}'.format(tmp_str))
a.append('{}-{}'.format(tmp_str, i))
a.append('{} {} str'.format(i, i * 2.0))
n = 0
for i in range(100):
for s in a:
n += len("foobar {} stuff".format(s))
ss = "foobar {} stuff".format(s)
n += len("{}-{}-{}".format(i, s, ss))
assert n == 36897500, n
```
```
running str_format_format_method
..........
interpreted: 0.574899s (avg of 5 iterations; stdev 0.25%)
compiled:    0.156026s (avg of 5 iterations; stdev 0.63%)
compiled is 3.685x faster
```
> [mypyc] Rewrite CPyStr_Build using a simplification of _PyUnicode_JoinArray

- mypy/exprtotype.py
- mypy/plugins/attrs.py
- mypy/semanal.py
- mypy/semanal_namedtuple.py
- mypy/semanal_newtype.py
- mypy/semanal_typeddict.py
- mypy/typeanal.py
- test-data/unit/check-classes.test
- test-data/unit/check-union-or-syntax.test
- test-data/unit/fixtures/type.pyi
- test-data/unit/fixtures/typing-full.pyi
Support the `X | Y` syntax (PEP 604) in type aliases, casts, type applications 
and base classes.
These are only available in Python 3.10 mode and probably won't work in
stubs when targeting earlier Python versions yet.
Work on #9880.
> Support union type syntax in runtime contexts

- mypy/checker.py
- mypy/exprtotype.py
- mypy/plugin.py
- mypy/plugins/attrs.py
- mypy/semanal.py
- mypy/semanal_namedtuple.py
- mypy/semanal_newtype.py
- mypy/semanal_typeddict.py
- mypy/typeanal.py
- test-data/unit/check-union-or-syntax.test
Previously it only worked when the target Python version was 3.10. Now type
aliases like these work in stubs on all Python versions:
```
A = str | None
```
Since type objects don't support `__or__` before 3.10 (in typeshed), skip some 
type checking of type alias definitions in stubs. Defensively only skip these things
in stubs, even though they could be redundant in other contexts as well.
Work on #9880.
> Support new union syntax in stubs always in runtime context 

- mypyc/irbuild/prebuildvisitor.py
This PR makes mypyc avoid mutating the AST while searching decorators for any singledispatch `register` calls, as requested in https://github.com/python/mypy/pull/10753#discussion_r663295437.
> [mypyc] Avoid mutating the AST when processing singledispatch `register` calls

- mypy/checker.py
- test-data/unit/check-union-or-syntax.test
- test-data/unit/fixtures/isinstance_python3_10.pyi
- test-data/unit/lib-stub/types.pyi
Support things like `isinstance(x, int | str)` in Python 3.10
Closes #9880.
> Support new union type syntax with isinstance

- docs/source/more_types.rst
This PR documents the special meaning of ellipses for default values in overloads. The only reference I could find to this behavior in non-code writing [is this comment](https://github.com/python/mypy/issues/6580#issuecomment-586547247) by @Michael0x2a.
If you think it's inaccurate that this is (or should be) a best practice I'll rephrase that sentence, but it's my impression that it is.
The change renders like this locally (`make html`):
> Document special meaning of `...` in overloads

- mypyc/irbuild/specialize.py
- mypyc/primitives/int_ops.py
- mypyc/test-data/irbuild-str.test
Closes https://github.com/mypyc/mypyc/issues/875
* Shorter IR code when calling tagged integer in `str.format`
* 3.8x faster when running microbenchmark (master branch is about 3.6x)
> [mypyc] Faster int conversion in str.format

- mypyc/irbuild/specialize.py
- mypyc/test-data/irbuild-str.test
- mypyc/test-data/run-strings.test
This pull request adds a specializer for faster constructing f-string, which is translated into str.join() previously in mypy AST. 
IR building tests: 
* {var}
* empty string
* literal string
* unsupported method
Speed up:
```
running str_format_fstring
..........
interpreted: 0.295028s (avg of 5 iterations; stdev 2.3%)
compiled:    0.188493s (avg of 5 iterations; stdev 1.7%)
compiled is 1.565x faster
```
on this case:
```
@benchmark
def str_format_fstring() -> None:
a = []
tmp_str = "Foobar"
for i in range(1000):
for _ in range(5):
a.append(f'{tmp_str}')
a.append(f'{tmp_str}-{i}')
a.append(f'{i} {i*2.0} str')
n = 0
for i in range(100):
for s in a:
n += len(f"foobar {s} stuff")
ss = f"foobar {s} stuff"
n += len(f"{i}-{s}-{ss}")
assert n == 36897500, n
```
Current master branch is 0.380x.
> [mypyc] Initial optimization for f-string through a str.join() specializer

- mypy/argmap.py
- mypy/checkexpr.py
- mypy/constraints.py
- mypy/fastparse.py
- mypy/fastparse2.py
- mypy/infer.py
- mypy/messages.py
- mypy/nodes.py
- mypy/plugin.py
- mypy/semanal.py
- mypy/strconv.py
- mypy/stubgen.py
- mypy/stubtest.py
- mypy/suggestions.py
- mypy/test/testinfer.py
- mypy/typeanal.py
- mypy/types.py
- mypyc/codegen/emitwrapper.py
- mypyc/ir/func_ir.py
- mypyc/irbuild/builder.py
- mypyc/irbuild/function.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/mapper.py
- mypyc/irbuild/util.py
- test-data/unit/plugins/arg_kinds.py
This is cleaner and more precise and will allow us to add convenience
methods to the class.
(I added one convenience method so far, to verify that mypyc doesn't
choke on it...)
> Make ARG_* into an actual enum class instead of just using int everywhere

- mypy/argmap.py
- mypy/checkexpr.py
- mypy/join.py
- mypy/messages.py
- mypy/nodes.py
- mypy/plugins/functools.py
- mypy/plugins/singledispatch.py
- mypy/strconv.py
- mypy/stubgen.py
- mypy/stubtest.py
- mypy/subtypes.py
- mypy/suggestions.py
- mypy/typeanal.py
- mypy/types.py
- mypyc/ir/func_ir.py
- mypyc/irbuild/function.py
- mypyc/irbuild/ll_builder.py
Part of the motivation here is that I want to make positional-only
arguments be properly reflected in the argument kinds, and having most
of the logic done through helpers will make that easier.
> Use helper methods for a lot of ArgKind checks

- mypyc/irbuild/expression.py
- mypyc/test-data/irbuild-classes.test
- mypyc/test-data/run-classes.test
Accessing an instance attribute through a native class object results in
unexpected behavior at runtime (e.g. `<attribute 'x' of 'C' objects>`)
so reject these during compilation.
Also produce a note that suggests how to work around the issue.
Fixes mypyc/mypyc#814.
> [mypyc] Reject instance attribute access through class object

- mypy/stubgen.py
- mypy/traverser.py
- test-data/unit/stubgen.test
Stubgen: Support functions that yield values:
```python
def foo():
x = yield 123
return ""
def bar():
yield
```
will be generated as:
```python
from collections.abc import Generator
from typing import Any
def foo() -> Generator[Any, Any, Any]: ...
def bar() -> Generator[None, None, None]: ...
```
Before this change, these function were annotated with a `None` return type.
This PR doesn't support `yield from` expressions (see #10744).
Tests for this feature and a few corner cases were added.
> stubgen: Add support for yield statements

- mypyc/analysis/dataflow.py
- mypyc/irbuild/nonlocalcontrol.py
- mypyc/test-data/exceptions.test
- mypyc/transform/refcount.py
Currently the finally path has a hacky pointless branch
on a register that is potentially NULL in order to convince
refcounting to do the right thing.
I want to add another case that would require this, so just fix
refcounting to properly account for error values in registers.
> Make refcounting handle error values loaded into registers

- mypy/checkexpr.py
- mypy/fastparse.py
- mypy/messages.py
- mypy/semanal.py
- test-data/unit/check-inference.test
- test-data/unit/check-redefine.test
- test-data/unit/check-singledispatch.test
This PR causes mypy to not show an error if a function named `_` is redefined, as a single underscore is often used as a name for a throwaway function.
This handles the case where `_` is used as an alias for `gettext` by differentiating between functions that are aliased as `_` but defined with another name, and functions that are defined as `_`. Overwriting a function named `_` is allowed, but overwriting a function named something else but aliased as `_` is not allowed, which should prevent people from accidentally overwriting `gettext` after importing it.
This also turns calling a function named `_` directly into an error, as currently we keep track of the type of the first definition if there are multiple functions defined as `_`, instead of the type of the last definition, and …
> Allow redefinition of underscore functions

- mypy/fastparse.py
- mypy/fastparse2.py
- mypy/messages.py
- mypy/nodes.py
- mypy/typeops.py
- mypy/types.py
- mypyc/irbuild/mapper.py
- test-data/unit/check-classes.test
- test-data/unit/check-python38.test
I was originally planning to address this by adding an ARG_POS_ONLY
kind (as a concrete win for what I hoped would be a generally positive
refactor), but it was actually really easy to fix it on its own, and
then we can address the refactor purely on its own merits.
> Properly track positional-only arguments for unannotated functions

- mypyc/ir/func_ir.py
- mypyc/irbuild/function.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/mapper.py
- mypyc/test-data/fixtures/testutil.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/run-classes.test
- mypyc/test-data/run-functions.test
- mypyc/test-data/run-python38.test
- mypyc/test-data/run-singledispatch.test
Currently these mostly segfault.
The main tricky case here is with *args and **kwargs (which we need to
deal with always when generating pycall glue and also when a native
function takes them), though we also need to take care to coerce error
values when forwarding optional arguments.
I also accidentally fixed a bug where we would compile `f(a, *b, c)`
as `f(a, c, *b)`.
> Fix handling of default arguments in generated glue methods

- mypy/stubgen.py
- test-data/unit/stubgen.test
`namedtuple` accepts field names defined with a combination of comma and spaces ([docs](https://docs.python.org/3/library/collections.html#collections.namedtuple)/[source](https://github.com/python/cpython/blob/919ad537510fdc2c750109e0bc4eceea234324b2/Lib/collections/__init__.py#L355)); update stubgen to handle this case in the same way as the source.
Added a test for this case.
> stubgen: Handle commas in namedtuple field definition

- build-requirements.txt
- mypy-requirements.txt
- mypy/config_parser.py
- mypy/modulefinder.py
- setup.py
There wasn't an issue about this so not sure if this PR is welcome. It was a quick drive-by to make, however, so opened it anyways as a discussion starter. :smile: 
This switches TOML parser from `toml` (TOML v0.5 compatible) to `tomli` (TOML v1 compatible) with the idea that it's nice if mypy is able to read pyproject.toml even if it contains newer TOML syntax. Even if mypy doesn't need that syntax, pyproject.toml is shared by many other tools (often company internal ones that we don't know about) so would be great to not block them.
[A couple other](https://github.com/nedbat/coveragepy/issues/1180) projects also made the switch recently.
> Switch from `toml` to `tomli` for TOML v1 support

- mypy/plugins/singledispatch.py
- test-data/unit/check-singledispatch.test
This fixes a crash that occurs when someone tries to create a singledispatch function with incorrect arguments and then tries to register an implementation for that singledispatch function.
This crash first appeared when type checking ibis in mypy_primer (see https://github.com/python/mypy/pull/10830#issuecomment-881786093) when type checking the use of singledispatch at https://github.com/ibis-project/ibis/blob/0671630426808a9fb55a9f6f4e662e126124c6b1/ibis/backends/spark/datatypes.py#L83.
I added a new test to reproduce the crash.
> Avoid crash in singledispatch plugin for incorrect singledispatch arguments

- mypyc/lib-rt/getargsfast.c
- mypyc/test-data/run-functions.test
In `CPyArg_ParseStackAndKeywordsSimple`, we don't check if the parser is
initialized, so on the first call, `min` and `max` will be zero and so
zero arguments being passed will always pass the test. Add an initialization
check.
Fixes #872.
> [mypyc] Fix fastcall positional fast path when parser is uninitialized

- mypy/checkexpr.py
- mypy/fastparse.py
- mypy/fastparse2.py
- mypy/nodes.py
- mypy/semanal.py
- mypy/util.py
- mypyc/codegen/emitmodule.py
- mypyc/common.py
- mypyc/ir/class_ir.py
- mypyc/ir/func_ir.py
- mypyc/ir/module_ir.py
- mypyc/ir/ops.py
- mypyc/irbuild/function.py
- mypyc/irbuild/prepare.py
- mypyc/test-data/run-misc.test
- mypyc/test-data/run-singledispatch.test
This PR adds support for compiling functions named `_` even when there are multiple functions named `_` (which previously would lead to a C compiler error as we tried to generate 2 functions with the same name).
This also adds support for using a function named `_` for a registered implementation of a singledispatch function.
I added 2 new tests, and I changed a test for underscore functions in run-singledispatch.test from an xfail test to a regular test.
> [mypyc] Add support for underscore functions

- misc/build_wheel.py
- misc/sync-typeshed.py
- mypyc/irbuild/classdef.py
- scripts/mypyc
Remove redundant `import`'s and `type_obj`
> Remove redundant `import`'s and `type_obj`

- mypyc/irbuild/expression.py
- mypyc/irbuild/format_str_tokenizer.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/specialize.py
- mypyc/test-data/fixtures/typing-full.pyi
- mypyc/test-data/irbuild-str.test
- mypyc/test-data/run-strings.test
- mypyc/test/test_stringformatting.py
We add a special path for %-style string formatting, which previously is compiled by calling a % binary op. 
The `translate_str_format_percent_sign` serves as an interface from `transform_op_expr` to a specializer for string formatting. A regex tokenizer for %-style format string would parse the original strings into two lists, one is literals and the other is formatting operations.
Currently we directly match the `List[str]` with conversions only for %s and %d cases. In the following PRs, `FormatOp` would be used for better code structure.
`join_formatted_strings`, shared with `str.format()`, merges two lists into one final string using `str_build_op` which is much faster than `str.join`.
This PR adds several run tests and irbuilding tests. 
The performance on microbenchmarks is: 
master …
> [mypyc] Tokenizer for printf-style format string

- .github/workflows/test.yml
- .travis.yml
- test-requirements.txt
virtualenv's 16.7.11 release yesterday appears to have broken our CI by updating the embedded version of pip to something that doesn't support python 2 (see https://github.com/python/mypy/issues/10407#issuecomment-883946075 for more info).
This is probably not an ideal long-term fix seeing as we're eventually going to need to switch to virtualenv 20 for python 3.10 support (see #10407), but this should fix CI long enough to find a better fix for this, whether that means:
- Dropping the failing python2 tests entirely (see #10846)
- Figuring out why the installed virtualenv isn't using the embedded pip 20.3.4, which does have python 2 support (maybe try installing virtualenv on python2 or something?)
- Switching to virtualenv 20 and hoping it has a fix for this
I have no clue how to test …
> Temporarily pin virtualenv to 16.7.10 to fix CI failures

- mypy/modulefinder.py
- mypy/pyinfo.py
- setup.py
- test-requirements.txt
This works around a change in virtualenv 20.x where the site-packages folder is added to the `PYTHONPATH` variable. We detect if the python executable is in a virtualenv by comparing the prefix and base prefix, and ignoring the issue if the site-package folder is under the virtualenv prefix.
This is an alternative to https://github.com/python/mypy/pull/10846
Fixes https://github.com/python/mypy/issues/10407
> Fix mypy for new virtualenv

- setup.py
Right now it is impossible to navigate from `pypi.org` to docs or github repo.
This commit fixes it.
> Improves `urls` on https://pypi.org/project/mypy

- docs/source/literal_types.rst
This feature is not-really known from my experience. I had to explain it several times to other devs.
But, I think that this technique should be widely recognised! It is awesome!
Refs https://github.com/python/mypy/issues/6366
> Adds docs about exhaustive literal and enum checks

- mypy/build.py
- mypyc/irbuild/function.py
- mypyc/test-data/run-singledispatch.test
This PR changes the order that the dispatch function checks dispatch types of registered implementations to always check any of the class's subclasses (if any have registered implementations) before checking the class itself.
That matches the semantics of the standard library implementation of singledispatch more closely, which goes up the MRO of the argument's type and uses the registered implementation that corresponds with the first type that it finds that is also a dispatch type.
I added a test to run-singledispatch.test that reproduces this bug.
> [mypyc] Fix order of dispatch type checking in singledispatch functions

- mypy/semanal.py
Recreating equivalent ParamSpecExpr objects causes the equality check in
is_same_symbol in add_symbol_table_node to fail, causing a name already
defined error.
> Fix ParamSpec semanal issue

- mypy/checkstrformat.py
- test-data/unit/check-expressions.test
- test-data/unit/fixtures/python2.pyi
According to [PEP461](https://www.python.org/dev/peps/pep-0461/), conversion type %c performs differently for string and bytes. In addition, `b'%c’ % str` is not supported in Python3.
CPython Python3: 
```py
ss = 'a'
bb = b'a'
ii = 97
ff = 97.0
print('%c' % ss)
print('%c' % ii)
print(b'%c' % bb)
print(b'%c' % ii)
```
CPython Python2: 
```py
print('%c' % ss)
print('%c' % bb)
print('%c' % ii)
print(b'%c' % ss)
print(b'%c' % bb)
print(b'%c' % ii)
```
> Fix %c string and bytes interpolation

- mypy/checkstrformat.py
- mypy/messages.py
- test-data/unit/check-expressions.test
- test-data/unit/fixtures/python2.pyi
This PR is a follow-up to https://github.com/python/mypy/pull/10869.
* Add more tests for %c interpolation
* The error msg of mypy now is bassically the same  as CPython. We offer hints for incompatible types.
* Change type of `Checkers` from `Tuple[Callable[[Expression], None], Callable[[Type], None]]` to ``Tuple[Callable[[Expression], None], Callable[[Type], bool]]``. `check_expr ` can get a False from `check_type` and stop generating same error message.
Adds several new test cases.
CPython behaviors:
```py
'%c' % b''   # E: "%c" requires int or char
'%c' % b'ab' # E: "%c" requires int or char
b'%c' % b''   # E: "%c" requires int or char
b'%c' % b'aa' # E: "%c" requires int or char
```
> Use customized error message for %c interpolation

- mypy/stubtest.py
Should fix the issue in https://github.com/python/typeshed/pull/5762
> stubtest: be safer with inspect.signature

- mypyc/irbuild/builder.py
- mypyc/irbuild/function.py
- mypyc/irbuild/main.py
- mypyc/irbuild/prebuildvisitor.py
- mypyc/irbuild/prepare.py
- mypyc/test-data/run-singledispatch.test
This adds support for being able to register an implementation of a singledispatch function in a different file than the singledispatch function was defined, as long as both the implementations and the main singledispatch function are in the same SCC.
I added a test with an implementation being registered in a different module than the original singledispatch function.
> [mypyc] Allow registering implementations for singledispatch functions in different files

- mypy/constraints.py
- test-data/unit/check-inference-context.test
When trying to match `list[T]` and `list[str] | Any`, previously we
gave up, because the union items caused conflicting inferred values
for `T` (`str` and `Any`). Work around the issue by dropping `Any`
constraints if there are multiple sets of contraints, since we
prefer more precise types.
This fixes false positives resulting from python/typeshed#5557,
which changed some return types to contain unions with `Any` items.
See mypy primer results in #10881 for a real-world example of this
in sphinx.
> Improve type inference special case that involves union with Any

- mypyc/irbuild/function.py
- mypyc/test-data/irbuild-singledispatch.test
- mypyc/test/test_irbuild.py
This adds support for using native calls to registered implementations when generating dispatch functions for singledispatch functions, instead of always using non-native calls, which can significantly speed up singledispatch (see benchmark results below). We don't use native calls when the registered implementation is a decorated function, as using a native call would ignore any changes the decorator made to the function.
These are the results from running the sum_tree_singledispatch both with this change and on the current master (7808e8265cd4cb29dc7f05ff58ab945ab3f2d20b).
```
interpreted: 0.694200s (avg of 5 iterations; stdev 1%)
compiled:    0.661199s (avg of 5 iterations; stdev 1.3%)
compiled is 1.050x faster
```
```
interpreted: 0.701401s (avg of 5 iterations; stdev 1.4%)
compiled: …
```
> [mypyc] Use native calls in singledispatch dispatch functions

- mypyc/codegen/emit.py
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/run-bytes.test
`bytearray` is treated as a subtype of bytes by mypy, even though they behavior differently in some cases. We keep this design and check bytearray before calling corresponding cpython API.
Adds tests for `bytearray` creation.
> [mypyc] Add bytearray support

- docs/source/command_line.rst
Fixes #10250 
Adds an example on how to use the OR-operator to combine two regular expressions in order to ignore multiple file or directory names.
> Add new regex example to --exclude docs

- mypy/stubtest.py
- mypy/test/teststubtest.py
> stubtest: check type aliases

- mypy/checkstrformat.py
- mypyc/irbuild/format_str_tokenizer.py
- mypyc/irbuild/specialize.py
- mypyc/test-data/irbuild-str.test
`parse_conversion_specifiers` and `parse_format_value` from `mypy.checkstrformat` can be reused when compiling string formatting. `can_optimize_format` and `split_braces` are useless now.
Adding a `start_pos` as an attribute of `ConversionSpecifier` can not only help parse literals but also help generate useful error messages in the future.
> [mypyc] Refactor: reuse format string parser

- mypyc/doc/dict_operations.rst
- mypyc/doc/list_operations.rst
- mypyc/primitives/dict_ops.py
- mypyc/primitives/list_ops.py
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-lists.test
Resolves mypyc/mypyc#882.
Instead of loading the type and calling it via the vectorcall convention let's use PyList_New / PyDict_New directly to create these empty collections. This mimics the behaviour constructing empty list and dict literals.   
- Added two more irbuild test cases, one for each type
- Built the mypyc documentation locally and checked it for any markup issues
> [mypyc] Optimize construction via list() & dict()

- mypy/checker.py
Resolves #9691
As mentioned in that issue, this is a huge performance win. On the
codebase I'm currently working on, it halves a cacheless interpreted
mypy runtime. The linked issue contains a benchmark run.
> Skip overlapping overload checks in ignored files

- mypy/test/config.py
- mypy/test/data.py
We currently assert that test-data is present in `mypy.test.config`;
delay that until we actually do collection, so that things are at
least importable.
> Make the test system marginally less hostile to external reuse

- mypy/test/testpep561.py
This test was original skipped because nesting a virtualenv inside of a venv on macOS was a problem, but now that we use a newer virtualenv, hopefully that issue has gone away.
> Try removing skipped test on macOS

- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/bytes_ops.c
- mypyc/primitives/bytes_ops.py
- mypyc/test-data/irbuild-bytes.test
- mypyc/test-data/run-bytes.test
This is mostly adapted from how it is done for str. We call undocumented API function _CPyBytes_Join which behaves similarly to the publicly available unicode one. Care is taken to deal with the case where we happen to have bytearray instead. As a result of needing to do the CheckExact anyway, we also support wonky subclasses of bytes.
Added both ir and runtime tests. Benchmark yielded reasonable gains but the benchmark also included concat which is likely slower than join.
> [mypyc] Add primitive for bytes join() method

- mypyc/irbuild/ll_builder.py
- mypyc/test-data/irbuild-bytes.test
- mypyc/test-data/run-bytes.test
Similar to list and tuple, we can directly get length of bytes from `PyVarObject->ob_size`
Implements part of mypyc/mypyc#880.
* Add an irbuild test
* Add run tests for bytearray(There are already several run tests for bytes)
> [mypyc] Faster len(bytes)

- mypy-requirements.txt
- setup.py
While we figure out what the plan is in coordination with black and
pip (see #10893), just pin to the previous version of tomli that isn't
causing our CI to fail.
> Pin tomli to 1.1.0

- mypy/build.py
- test-data/unit/check-incremental.test
- test-data/unit/pep561.test
Since PEP561-installed namespace packages only show up in
FindModuleCache as a side-effect, the submodules need to be listed
first in the dependencies for things to work. This was handled already
in the Import case but not the ImportFrom case.
Also fix the cache handling of namespace packages so it doesn't always
get reported stale.
Fixes #9852.
> Fix caching behavior of PEP561-installed namespace packages

- mypyc/irbuild/function.py
- mypyc/irbuild/ll_builder.py
- mypyc/irbuild/main.py
- mypyc/irbuild/prepare.py
- mypyc/test-data/irbuild-singledispatch.test
- mypyc/test-data/run-singledispatch.test
This changes the implementation of singledispatch to look up the correct registered implementation to use at runtime using the MRO of the passed argument, instead of using a chain of `isinstance` checks for each registered implementation, for the reasons mentioned in https://github.com/mypyc/mypyc/issues/802#issuecomment-886119662.
This doesn't support dynamically registering implementations yet, so 2 of the existing singledispatch tests that rely on that are marked as xfails for now.
I added a test based on the example in https://github.com/mypyc/mypyc/issues/802#issuecomment-886119662.
> [mypyc] Use MRO of argument for dispatch in singledispatch functions

- mypyc/irbuild/function.py
- mypyc/irbuild/prepare.py
- mypyc/lib-rt/CPy.h
- mypyc/lib-rt/misc_ops.c
- mypyc/primitives/misc_ops.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-singledispatch.test
- mypyc/test-data/run-singledispatch.test
This adds support for registering implementations for singledispatch functions at runtime by generating a `register` method for compiled singledispatch functions that adds a function to the registry of implementations at runtime.
The 2 tests that were marked as xfails in #10930 are now regular tests. In addition, 2 new tests are added to test the dynamic registration code.
> [mypyc] Add support for dynamically registering singledispatch functions

- mypyc/codegen/emitclass.py
- mypyc/ir/class_ir.py
- mypyc/irbuild/function.py
- mypyc/lib-rt/misc_ops.c
- mypyc/primitives/dict_ops.py
- mypyc/test-data/irbuild-singledispatch.test
- mypyc/test-data/run-singledispatch.test
This adds a cache to the dispatching code for singledispatch functions, which makes calling singledispatch functions much faster.
The benchmark results for the [sum_tree_singledispatch](https://github.com/mypyc/mypyc-benchmarks/blob/735dff13e7c2c079a9881bcc4792a7363b98822e/microbenchmarks/singledispatch.py#L45) benchmark:
```
running sum_tree_singledispatch
..........
interpreted: 0.325256s (avg of 5 iterations; stdev 0.21%)
compiled:    0.057567s (avg of 5 iterations; stdev 3.3%)
compiled is 5.650x faster
```
I added a test to make sure that the cache is correctly invalidated when a new function is registered.
> [mypyc] Use a cache to speed up singledispatch calls

- mypyc/irbuild/builder.py
- mypyc/irbuild/function.py
- mypyc/test-data/irbuild-singledispatch.test
Fixes mypyc/mypyc#881
This makes generated code use native calls to singledispatch functions whenever possible, which makes singledispatch functions faster.
This PR:
```
running sum_tree_singledispatch
..........
interpreted: 0.593835s (avg of 5 iterations; stdev 2.4%)
compiled:    0.044264s (avg of 5 iterations; stdev 2.1%)
compiled is 13.416x faster
```
Current master (4c90aa42e6a74f127956124aec94f55dbc46a281):
```
running sum_tree_singledispatch
..........
interpreted: 0.588636s (avg of 5 iterations; stdev 1.4%)
compiled:    0.059705s (avg of 5 iterations; stdev 1.5%)
compiled is 9.859x faster
```
I added an irbuild test to make sure that we were using native calls to singledispatch functions.
> [mypyc] Use native calls to singledispatch functions

- mypy/messages.py
- test-data/unit/check-errorcodes.test
When we use `# ignore[typeddict-item]` associated notes are not ignored
I have added a unittests to cover it
> fix: ignore[typeddict-item] also ignore associated notes

- docs/source/running_mypy.rst
Fix typo in doc:
```diff
-command following command
+following command
```
[Rebuild the docs](https://github.com/python/mypy/blob/master/docs/README.md)
> fix doc typo

- mypy/stubgen.py
That's the last unsued import I found.
Related #11041
> Removes unused `mypy.errors` import from `stubgen`

- mypyc/common.py
- mypyc/irbuild/context.py
- mypyc/irbuild/function.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/run-functions.test
Per mypyc/mypyc#718, renaming the original function name in the module
mapping causes the `__name__` of decorated functions to have be
something like `__mypyc_*_decorator_helper__`. When checking if just
using the original name as the module name (and then later the function
will be overridden by the decorated value) no tests fail. And there are
indeed tests that exhibit rather complex decorator behavior so it seems
there may not actually be anything wrong with using the original name.
Added a runtime test that exhibits better `__name__` behavior, existing tests to prevent regression.
> [mypyc] Remove decorator_helper_name

- docs/source/error_code_list2.rst
I've noticed we don't prefix with `typing.` elsewhere in the doc, so I'll remove the prefixes to make it more fluent to read.
> error_code_list2.rst: typo + edit

- docs/source/common_issues.rst
It was really not clear for some users that you can use `issubclass` as well.
> Docs: adds a note about `issubclass` usage in `common_issues.rst`

- docs/source/command_line.rst
In our testing, mypy appears to treat code like this as an *implicit* re-export. If `--no-implicit-reexport` is given, mypy will disallow it.
```python
from X import Y as Z  # Non-matching name.
```
Even though it treats code like this as an *explicit* re-export:
```python
from X import Y as Y  # Matching name.
```
For stub files specifically, [PEP 484 has this note](https://www.python.org/dev/peps/pep-0484/#stub-files), emphasis mine:
> Modules and variables imported into the stub are not considered exported from the stub unless the import uses the `import ... as ...` form or the equivalent `from ... import ... as ...` form. (UPDATE: To clarify, the intention here is that **only names imported using the form `X as X` will be exported, i.e. the name before and after as must be the …
> Docs: show how `--no-implicit-reexport` handles `from X import Y as Z`

- mypy/checker.py
- mypy/checkexpr.py
- mypy/checkmember.py
- mypy/constraints.py
- mypy/expandtype.py
- mypy/fixup.py
- mypy/indirection.py
- mypy/join.py
- mypy/meet.py
- mypy/messages.py
- mypy/plugins/attrs.py
- mypy/plugins/common.py
- mypy/plugins/singledispatch.py
- mypy/sametypes.py
- mypy/semanal.py
- mypy/semanal_infer.py
- mypy/server/astdiff.py
- mypy/server/astmerge.py
- mypy/server/deps.py
- mypy/subtypes.py
- mypy/suggestions.py
- mypy/type_visitor.py
- mypy/typeops.py
- mypy/types.py
- mypy/typetraverser.py
Closes https://github.com/python/mypy/issues/2112
This PR changes the FunctionLike.items from method to property. By doing so, the `items` field is consistent with other types such as `TupleType` and is distinguished from `dict.items()`
```py
@property
@abstractmethod
def items(self) -> List['CallableType']: pass
```
> Change FunctionLike.items from method to property

- mypy/stubdoc.py
- mypy/stubgenc.py
- mypy/test/teststubgen.py
This fixes three issues encountered while trying to generate stubs from a c module:
1.  Fix bug when inferring signatures with no args.  In this case, the signature has one arg which has an empty name.
2. Add a self arg to the inferred signature for a method, when it is omitted from docstring signature.  stubgen has a feature that will read the signature from the function's docstrings, but it would happily accept methods that did not specify a self-arg.   
3. Use 'cls' as self arg for classmethods without signature info.  Simple fix to produce better stubs for classmethods defined in c modules.
Each of these changes has a test which clearly shows the change.
I've left each of these changes as their own commit, and each _could_ be a separate MR, but they are so simple I've left them in one …
> [stubgen] Fix a few bugs with stubgen of c modules

- .github/workflows/test.yml
I liked the names we had in Travis. In particular, this helps disambiguate mypyc tests from mypy tests when mypy is compiled with mypyc.
> Use descriptive names in CI

- mypy/test/testpep561.py
I saw that this variable is unused and removed it
verified with
```rg _NAMESPACE_PROGRAM```
> Remove unused variable in testpep561.py

- mypyc/lib-rt/exc_ops.c
Guido plans to remove PyCode_New from CPython CAPI.
See: https://bugs.python.org/issue45122
closes: https://github.com/python/mypy/issues/11066
> bpo-45122: Remove PyCode_New from mypyc

- mypy/checker.py
- test-data/unit/check-statements.test
> Fixes `raise CustomError` creationg with  `__init__` with arguments

- docs/source/config_file.rst
Historically `--strict` was only supported on the command line, but commit cb0ceb02848494f3dab2d976035f0d56682a7045 (#8192) added this option to the config file in 0.770. Document the config file option.
[Rebuilt](https://github.com/python/mypy/blob/master/docs/README.md#building-the-documentation) the docs.
(Did you know that Read the Docs supports [automatic preview builds for pull requests](https://docs.readthedocs.io/en/stable/pull-requests.html)? It’d be neat if someone would turn that on for this repository.)
> Document ‘strict’ config file option

- mypy/messages.py
- test-data/unit/check-generic-subtyping.test
Fixes #10948
I have briefly discussed the problem with @hauntsaninja on Gitter.
The solution is straightforward.  All checks were there, but a missing `isinstance` check prevented the detected errors from being reported.
The added test case includes examples for getting, setting, and deleting undefined attributes.
> Report attribute access errors for TypeVar bound to Union.

- docs/source/more_types.rst
Add needed `covariant=True` for example to pass type checking at `page.first_chunk()` as intended.
> Correct example annotation `self`

- mypy/plugins/dataclasses.py
- test-data/unit/check-dataclasses.test
- test-data/unit/fixtures/dataclasses.pyi
> Fixes mypy crash on `dataclasses.field(**unpack)`

- docs/source/type_narrowing.rst
> Adds docs about `:=` and `TypeGuard`

- mypy/checker.py
An unnecessary default return was removed, `return` (or any other statement) after a `while True` with no `break` condition will never be executed
> Remove `return output` in `refine_parent_types`

- mypy/checkexpr.py
- mypy/semanal.py
> Adds `in_checked_function()` to semanal similar to the one in checker

- mypy/semanal_namedtuple.py
- test-data/unit/check-namedtuple.test
- test-data/unit/semanal-namedtuple.test
While working on https://github.com/python/mypy/issues/11047 I've noticed that `mypy` reports the same error for both `collection.namedtuple()` and `typing.NamedTuple()`.
I've tried to fix to report the correct name.
> Adds better NamedTuple error messages

- mypyc/ir/rtypes.py
- mypyc/irbuild/builder.py
- mypyc/test-data/irbuild-dict.test
- mypyc/test-data/irbuild-lists.test
- mypyc/test-data/irbuild-set.test
- mypyc/test-data/irbuild-statements.test
- mypyc/test-data/refcount.test
- mypyc/test-data/run-lists.test
Fixes mypyc/mypyc#759 and probably some other issues. Including only
the change to coerce the Register assignments fixes the missing
type coercion for the specialized next-generator case, but causes some
unusual box-then-unbox from short_ints.
These odd coercions are caused by the dict keys in dict literals being
considered short_int, but dict_next_rtuple_single/pair return types bein
annotated as int_primitive. Changing this to short_int_rprimitive removes
the odd coercisions. The remainder of the diff is fixing the irbuild
testcase output to have short_int.
> [mypyc] Coerce Register assignments

- mypyc/irbuild/builder.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/run-misc.test
Fixes mypyc/mypyc#702 by replacing "'" with "__redef__",
although this assumes nothing else will ever use demangling
for now.
Only locals need any fix; a run testcase was added to verify
that it works already for globals, and since the fix for locals
is on the ir level only an ir testcase is added.
> [mypyc] Remangle names produced by allow-redefinition

- mypy/modulefinder.py
- mypy/nodes.py
- mypyc/irbuild/format_str_tokenizer.py
All enums in `mypy` are unique. Eventhough, current state of `enum_plugin` does not support `@unique` checking during `mypy` run, it is a good thing to have.
It will raise `ValueError: duplicate values found in <enum 'ArgKind'>: CUSTOM -> ARG_NAMED` during development if this rule is violated.
> Marks unique enums as `@unique`

- docs/source/type_narrowing.rst
> Add type narrowing docs about `callable`

- mypy/errors.py
- mypy/fastparse.py
- mypy/fastparse2.py
- test-data/unit/check-errorcodes.test
Fixes https://github.com/python/mypy/issues/11157
For `--warn-unused-ignored`, currently `Errors.used_ignored_lines` keeps track of only the line numbers without error codes when errors appeares on the line with `# type: ignore` or `# type: ignore[...]`.
This PR changes `used_ignored_lines` so that it also keeps track of error codes and that information used in `generate_unused_ignore_errors` to show an error message like `unused "type: ignore[attr-defined]" comment`.
I'm very new to mypy code base and one thing I'm not so confident about my change is that I might be using `MISC` error codes in an unintended way.
Please let me know if this approach is correct and I appreciate any feedback.
Thank for the review!
There are some tests using `--warn-unused-ignores`, but this PR didn't change …
> fix: warn unused ignores when not all specified error codes are used

- mypy/plugins/dataclasses.py
- test-data/unit/check-dataclasses.test
Fixes https://github.com/python/mypy/issues/10248
The crash due to `dataclasses.field` was fixed in the recent PR https://github.com/python/mypy/pull/11137, but the error message was wrong when positional arguments are used.
I update the error message based on the https://github.com/python/mypy/issues/10248#issuecomment-924904033 (Thanks @JelleZijlstra!)
In `_collect_field_args`, I used `CallExpr.arg_kinds` to filter only "named" keyword argument, which hopefully is not the wrong usage of `ArgKind`.
I appreciate any feedback and thanks for the review!
Please see `testDataclassFieldWithPositionalArguments` in `test-data/unit/check-dataclasses.test`.
> Fix error message for dataclasses.field with positional argument

- mypy/binder.py
- mypy/checker.py
- mypy/literals.py
- test-data/unit/check-python38.test
- test-data/unit/check-unreachable-code.test
Authored by @kprzybyla in #9288. Helps with issue mentioned in #9229.
I fixed some nits and tests, but Github didn't like it when I tried to push to the original branch, so opening a new PR.
> Improve type narrowing for walrus operator in conditional statements

- mypy/checker.py
- mypy/checkexpr.py
- test-data/unit/check-callable.test
- test-data/unit/check-optional.test
Closes #11212
Previously `mypy` was ignoring `lambda` scope in `handle_cannot_determine_type`.
I guess it was done to fix some `lambda` related crashes.
I've also noticed one crash with this new solution in existing test. I happened because when right `or` part is unreachable, there's not `binder.frame` for it. So, I've made a temporary scope of it.
> Now `lambda` is counted as a valid context in `handle_cannot_determine_type`

- mypy/checkstrformat.py
- mypyc/test-data/run-strings.test
- test-data/unit/check-errorcodes.test
- test-data/unit/check-expressions.test
It does not mention `.format()` anymore.
Closes #10979
> Fixes error message for `f` string and `str-bytes-safe`

- mypy/subtypes.py
- test-data/unit/check-literal.test
> Checks `Instance` and `Literal` subtypes correctly, refs #11232

- mypy/checkmember.py
Currently `TypeChecker.named_type` is been called inside `MemberContext.builtin_type` thus this PR renames `MemberContext.builtin_type` with `named_type` for consistency.
Another reason for this change is that we sometimes call this function for non-builtins.
> Rename MemberContext.builtin_type with named_type

- mypy/nodes.py
- mypy/types.py
Quick review of changes:
1. I had to move all class-level values into `self.` definitions, because class attributes and incompatible with `__slots__`. This seems like a good idea for me, because there was no reason for them to be class-level. I can even imagine several bugs based on over-use of class-level attributes mutation. It might take more memory in some cases though.
2. I've added several `TODO` items to `op: str`, it seems like `Enum` would be a better fit there
Closes #11195
> Add `__slots__` to all types and nodes

- mypy/semanal.py
- test-data/unit/semanal-errors.test
> Fixes type vars semanal with `ParamSpec`

- mypy/checker.py
- test-data/unit/check-narrowing.test
Fixes #8925.
Consider the following narrowing (more realistically with TypedDicts),
and the current outcome:
```py
class A:
tag: Literal["A"]
class B:
tag: Literal["B"]
abo: A | B | None
if abo is not None and abo.tag == "A":
reveal_type(abo.tag)  # Type is Literal["A"]
reveal_type(abo)  # Type is A | B
```
The RHS of the comparison correctly takes into account the LHS, and the
`abo.tag` expression is correctly narrowed based on it, but this does
not propagate upward to then narrow `abo` to `A`.
The problem is that `and`/`or`/`not`/assignment expressions recurse using
the `find_isinstance_check_helper` function, which omits the
`propagate_up_typemap_info` calls that its parent function
`find_isinstance_check` performs.
Fix this by replacing these recursive `find_isinstance_check_helper` …
> Fix narrowing information not propagated in assignment and boolean expressions

- mypy/checker.py
- test-data/unit/check-narrowing.test
Fixes #9308.
The code in `refine_parent_types()` bailed out when it encountered
something other than a TypedDict in the union, including a nested union
of TypedDicts. This caused the narrowing to fail.
Fix it by making it iterate over the flattened union items.
Added a unit test case. It fails before and passes after.
> Fix narrowing of nested union of TypedDicts

- test-data/unit/plugins/arg_kinds.py
- test-data/unit/plugins/decimal_to_int.py
- test-data/unit/plugins/depshook.py
- test-data/unit/plugins/type_anal_hook.py
Refs https://github.com/python/mypy/pull/11242
Looks like this is it, no more unused imports.
> Removes unused import from `test-data/unit/plugins`

- mypy/checker.py
Removes the unused `kind` argument. Related to https://github.com/python/mypy/issues/4082.
> Remove the `kind` argument of checker.lookup

- mypy/expandtype.py
- mypy/fastparse.py
- mypy/server/astmerge.py
- mypy/test/test_find_sources.py
- mypy/test/typefixture.py
- mypy/typeanal.py
- mypy/types.py
Follow up to https://github.com/python/mypy/pull/11237 and https://github.com/python/mypy/pull/11235
Maybe we should check this in CI? 🤔
> Removes unused imports in mypy

- mypy/fastparse.py
- test-data/unit/check-fastparse.test
- test-data/unit/parse.test
> Improves error message for parsing `slice` in annotations

- mypy/test/data.py
- mypy/test/helpers.py
- test-data/unit/daemon.test
- test-data/unit/fine-grained-follow-imports.test
This matters with namespace packages enabled - since an (otherwise) empty folder with
some .2 files in it will be considered a namespace package. This is
truer - by only writing the files at the point of the step. This helps
unblock #9636
I confirmed that this helps fix some of the failures in #9636. I confirmed all preexisting tests continue to work.
> incremental testsuite: don't write subsequent step files until they are needed

- mypy/fscache.py
- mypy/modulefinder.py
- test-data/unit/check-modules-case.test
For example `from a import B` should not find a namespace
package `a/B/`. Fix by using case aware isdir on fscache.
Helps unblock #9636
There are several existing tests for this area. I split one of the tests by namespace package for straddling.
I also tested this diff on top of #9636 and confirmed it helps!
> Fix case mismatching modules during namespace package search

- docs/source/class_basics.rst
> Adds docs about new `__slots__` feature

- mypyc/irbuild/ll_builder.py
While working on #11263 I've noticed that this function is not used. It was used only in one place some time ago: https://github.com/python/mypy/commit/818cc4e0ac2b5d17c161fb65547ab77ead23ed28#diff-fb1a240667c19f142d8f7686411c3e8185eb94720e6bb005099ab7c1d57f878aR157
Maybe it is safe to remove it.
> Removes possibly unused `builtin_call`

- docs/source/running_mypy.rst
- mypy/modulefinder.py
Also re-order docs and make them more greppable
Helps with e.g. complaints in #9944
> Make error more self-explanatory when missing stubs or py.typed

- mypy/fscache.py
- test-data/unit/cmdline.test
This helps unblock #9636. With namespace packages, the
code to crawl upward would not stop anywhere and would
run into temp directories with invalid module names. Normally
it would stop when it found a dir without an __init__.py,
but it was placing an implicit fake bazel __init__ there.
Bazeled environments can't really have invalid module name
directories, so this should help fix.
Added tests for namespace-packages and no-namespace-packages
> Disallow invalid identifiers from getting implicit bazel __init__.py

- mypyc/codegen/emitfunc.py
- mypyc/common.py
- mypyc/irbuild/constant_fold.py
- mypyc/irbuild/expression.py
- mypyc/irbuild/ll_builder.py
- mypyc/test-data/analysis.test
- mypyc/test-data/fixtures/ir.py
- mypyc/test-data/irbuild-basic.test
- mypyc/test-data/irbuild-constant-fold.test
- mypyc/test-data/irbuild-strip-asserts.test
- mypyc/test-data/run-integers.test
- mypyc/test/test_emitfunc.py
- mypyc/test/test_irbuild.py
Work on mypyc/mypyc#772.
Replace things like '5 + 8' with '13' during IR building. Also adds
support for negative int literals, such as -5 (the negation gets
constant folded).
Arithmetic and bitwise operations that produce int results
are supported, plus string concatenation. Comparisons and float
operations are not supported yet, among other things.
This is a little tricky because of error cases, such as division by
zero. The approach here is to avoid constant folding error cases. We
still won't produce compile-time errors for them.
We do potentially lots of extra work by repeatedly trying to constant
fold expressions, but it didn't seem to slow down self-compilation 
measurably, so the effect seems minor at most. Some caching could 
help this if it becomes a problem.
> [mypyc] Constant fold int operations and str concat

- docs/source/config_file.rst
Closes #11122
This PR makes solves the described issue and makes the documentation better for users.
File location : docs/source/config_file.rst
To describe a Python version instead of DIGIT.DIGIT, it is better as MAJOR.MINOR since Python 3.10 version has minor '10' which is not a digit.
> Changed DIGIT.DIGIT to MAJOR.MINOR resolving #11122

- mypy/messages.py
- mypy/subtypes.py
- test-data/unit/check-typeguard.test
Now two functions are not considered subtypes if:
1. First returns `TypeGuard`, other returns `bool`. We respect subtyping direction here. `TypeGuard` is considered to be subtype of `bool`
2. First returns `TypeGuard[int]`, second returns `TypeGuard[str]`
Closes #11307
> Changes how `TypeGuard` types are checked in subtypes
